- demo-shell-ng2/app/components/app-layout/app-layout.component.html
- demo-shell-ng2/app/components/datatable/datatable-demo.component.html
- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/components/login/login-demo.component.html
- demo-shell-ng2/app/components/search/search.component.html
- demo-shell-ng2/app/components/settings/settings.component.html
- demo-shell-ng2/app/components/social/social.component.html
- demo-shell-ng2/app/components/tag/tag.component.html
- demo-shell-ng2/config/webpack.common.js
- demo-shell-ng2/resources/i18n/en.json
- ng2-components/ng2-alfresco-viewer/index.ts
- ng2-components/ng2-alfresco-viewer/src/components/unknown-format/unknown-format.component.html
- ng2-components/ng2-alfresco-viewer/src/i18n/en.json
- ng2-components/ng2-alfresco-webscript/index.ts
- ng2-components/ng2-alfresco-webscript/src/i18n/en.json
- ng2-components/ng2-alfresco-webscript/src/webscript.component.html
- ng2-components/ng2-alfresco-webscript/src/webscript.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1684
**Does this PR …
> [ADF-1684] Sanitise the component and Demo shell from embedded strings

- ng2-components/ng2-activiti-processlist/src/components/process-comments.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/comments.component.html
- ng2-components/ng2-activiti-tasklist/src/components/comments.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/i18n/en.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1695 …
> [ADF-1695] Comment component - Fix the header key

- docs/README.md
- ng2-components/README.md
- ng2-components/config/buildFullDocIndex.js
- ng2-components/ng2-activiti-analytics/README.md
- ng2-components/ng2-activiti-diagrams/README.md
- ng2-components/ng2-activiti-form/README.md
- ng2-components/ng2-activiti-processlist/README.md
- ng2-components/ng2-activiti-tasklist/README.md
- ng2-components/ng2-alfresco-core/README.md
- ng2-components/ng2-alfresco-datatable/README.md
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-login/README.md
- ng2-components/ng2-alfresco-search/README.md
- ng2-components/ng2-alfresco-social/README.md
- ng2-components/ng2-alfresco-tag/README.md
- ng2-components/ng2-alfresco-upload/README.md
- ng2-components/ng2-alfresco-userinfo/README.md
- ng2-components/ng2-alfresco-viewer/README.md
- ng2-components/ng2-alfresco-webscript/README.md
> - [ ] Bugfix
Moved doc index page inside docs folder and renamed to README.md. Scripts and links updated accordingly. Changes applied to Development branch in a separate PR, as requested. …
> [ADF-1586] Moved and renamed docs index file

- demo-shell-ng2/app/components/activiti/activiti-demo.component.html
- docs/viewer.component.md
- ng2-components/ng2-alfresco-viewer/index.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer-info-drawer.component.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer-toolbar.component.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.spec.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
> - [ ] Bugfix
- Viewer component now allows content projection for the Toolbar and …
> [ADF-1744] content projection for toolbar and info drawer

- docs/user-info.component.md
- ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.scss
- ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts
- ng2-components/ng2-activiti-tasklist/src/components/people.component.html
- ng2-components/ng2-activiti-tasklist/src/components/people.component.scss
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/pipes/user-initial.pipe.spec.ts
- ng2-components/ng2-alfresco-core/src/pipes/user-initial.pipe.ts
- ng2-components/ng2-alfresco-userinfo/README.md
- ng2-components/ng2-alfresco-userinfo/src/assets/fake-bpm-user.service.mock.ts
- ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.html
- ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.scss
- ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.spec.ts
- ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.ts
> - [ ] Bugfix
No username is showed next the user info component
Username is showed …
> [ADF - 1681] Added username and created initials pipe for user info

- docs/README.md
- ng2-components/config/buildFullDocIndex.js
> - [ ] Bugfix
There are some pipes in the Core library but they aren't listed in the index.
Pipes are listed in their own section as with components, …
> [ADF-1586] Updated doc indexing to include pipes

- scripts/npm-clean.sh
> add clean lock file to clean script

- demo-shell-ng2/app/components/app-layout/app-layout.component.html
- demo-shell-ng2/app/components/app-layout/app-layout.component.ts
- ng2-components/ng2-activiti-analytics/src/components/widgets/date-range/date-range.widget.ts
- ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/date/date.editor.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/date/date.editor.ts
- ng2-components/ng2-activiti-tasklist/src/components/start-task.component.ts
- ng2-components/ng2-alfresco-core/src/components/view/card-view-dateitem.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/view/card-view-dateitem.component.ts
- ng2-components/ng2-alfresco-core/src/components/view/card-view.component.spec.ts
- ng2-components/ng2-alfresco-core/src/material.module.ts
- ng2-components/ng2-alfresco-core/src/services/alfresco-content.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/alfresco-settings.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard-bpm.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/authentication.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/search.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/sites-api.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/thumbnail.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/translate-loader.spec.ts
- ng2-components/ng2-alfresco-core/src/services/translation.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/translation.service.ts
- ng2-components/ng2-alfresco-core/src/services/user-preferences.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/user-preferences.service.ts
> - [ ] Bugfix
Datapicker not localizable
Datapicker localizable
**Does this PR …
> [ADF-1694] Datepicker should be localizable

- demo-shell-ng2/app/components/files/files.component.html
- docs/README.md
- docs/node-delete.directive.md
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/directives/node-delete.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/node-delete.directive.ts
- ng2-components/ng2-alfresco-core/src/i18n/en.json
> [ADF-1745] Delete multiple nodes

- demo-shell-ng2/app/components/app-layout/app-layout.component.ts
> Fix dev build

- ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.html
- ng2-components/ng2-alfresco-userinfo/src/models/bpm-user.model.ts
- ng2-components/ng2-alfresco-userinfo/src/models/ecm-user.model.ts
> - [X] Bugfix
When user name is null or empty is showed as N/A
When user name is null …
> [ADF-1681] removed N/A default value

- demo-shell-ng2/app/app.component.ts
- demo-shell-ng2/app/components/file-view/file-view.component.html
- ng2-components/ng2-alfresco-viewer/src/components/pdfViewer.component.html
- ng2-components/ng2-alfresco-viewer/src/components/unknown-format/unknown-format.component.html
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html
- ng2-components/ng2-alfresco-viewer/src/i18n/en.json
> [ADF-829] i18n support for Viewer

- ng2-components/ng2-alfresco-login/src/components/login.component.html
- ng2-components/ng2-alfresco-login/src/components/login.component.scss
- ng2-components/ng2-alfresco-login/src/components/login.component.spec.ts
- ng2-components/ng2-alfresco-login/src/i18n/en.json
remove blue success label from Login dialogue
> [ADF-1620] remove blue success label from the dialog

- demo-shell-ng2/app/app.component.ts
> - [x] Bugfix
The translation service must be called at the beginning of the …
> The translation service must be called at the beginning of the bootstrap

- ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.html
- ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-documentlist/src/i18n/en.json
> - [ ] Bugfix
Task Attachment - The columns are not localized
Task Attachment - The …
> [ADF-1758] Task Attachment - The columns are not localized

- ng2-components/ng2-alfresco-core/src/services/sites-api.service.ts
> - [X] Bugfix
Pagination is applied to the sites dropdown
Pagination is not applied …
> [ADF-1651] removed pagination from site service query

- ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.ts
> [ADF-1753] Upload - uploaded files counter doesn't update

- ng2-components/ng2-activiti-processlist/src/components/process-instance-header.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/process-instance-header.component.ts
- ng2-components/ng2-activiti-processlist/src/i18n/en.json
- ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer-layout.component.scss
* Made all the keys localised for process header
* Added style for adf-info-drawer according to zeplin specification
> - [ ] Bugfix
**What is the current behaviour?** (You can also link to an …
> [ADF-1760] Process Info Drawer - The keys must be localized

- docs/README.md
> - [x] Bugfix
Links to doc files in docs/README.md were broken.
Links are now fixed.
> [ADF-1756] Fixed bad links in docs index

- docs/FormFieldValidator.md
- docs/README.md
- docs/form-field.model.md
- docs/form-rendering.service.md
- docs/form.component.md
- docs/seeAlsoGraph.json
- docs/widget.component.md
> - [ ] Bugfix
> - [ ] Yes
> - [x] No
Please can the reviewer have a quick look at the Form Field model page to see that the descriptions of …
> [ADF-1586] Added doc files for Form library

- demo-shell-ng2/app.config-dev.json
- demo-shell-ng2/app.config-prod.json
- docs/README.md
- docs/log.service.md
- ng2-components/ng2-activiti-form/src/components/form.component.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/process-filters.component.spec.ts
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/view/card-view-mapitem.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/view/card-view-textitem.component.spec.ts
- ng2-components/ng2-alfresco-core/src/models/log-levels.model.ts
- ng2-components/ng2-alfresco-core/src/services/log.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/log.service.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts
- ng2-components/package.json
> - [ ] Bugfix
The log service provide 6 level of logs:
Name | Level
-|-
TRACE |5;
DEBUG |4;
INFO |3;
WARN |2;
ERROR |1;
SILENT |0;
You can configure the log level …
> [ADF-1723] LogService configuration

- demo-shell-ng2/app/components/app-layout/app-layout.component.scss
> - [x] Bugfix
Hide username in demoshell for small devices …
> [ADF-1648] Hide username in demoshell for small devices

- docs/README.md
> - [x] Bugfix
Non-generated links to README files were broken.
Links fixed manually. Link checking tool reports no errors and links seem to work OK on GitHub. …
> [ADF-1756] Fixed problem with non-generated links

- ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.scss
- ng2-components/ng2-activiti-tasklist/src/components/start-task.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1757
**Does this PR …
> [ADF-1757] 'Label' appears on the top of form widgets

- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
> [ADF-1762] Document List - Sorting by Size is incorrect

- ng2-components/ng2-activiti-tasklist/src/components/task-details.component.html
- ng2-components/ng2-activiti-tasklist/src/components/task-details.component.scss
- ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer-layout.component.scss
- ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.scss
> - [X] Bugfix
Task details with infodrawer was not properly responsive
Task details …
> [ADF-1725] added responsive layout for task details and infodrawer

- demo-shell-ng2/app/components/app-layout/app-layout.component.html
- docs/language-menu.component.md
- docs/process-list.component.md
- ng2-components/ng2-alfresco-core/src/components/language-menu/language-menu.component.ts
> - [x] Bugfix
Wrong selector name
fixed …
> [ADF-1782] Language menu - Fix typo

- demo-shell-ng2/app/components/login/login-demo.component.html
- ng2-components/ng2-alfresco-login/index.ts
- ng2-components/ng2-alfresco-login/src/assets/authentication.service.mock.ts
- ng2-components/ng2-alfresco-login/src/components/login.component.html
- ng2-components/ng2-alfresco-login/src/components/login.component.spec.ts
- ng2-components/ng2-alfresco-login/src/components/login.component.ts
- ng2-components/ng2-alfresco-login/src/models/login-error.event.ts
- ng2-components/ng2-alfresco-login/src/models/login-submit.event.ts
- ng2-components/ng2-alfresco-login/src/models/login-success.event.ts
- strongly typed events
- remove deprecated content
> [ADF-1065] strongly typed events, removed deprecations

- ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer-layout.component.scss
> [ADF-1765] Info Drawer - Review the specification

- ng2-components/config/app.config.json
- ng2-components/ng2-alfresco-core/src/services/log.service.ts
> - [x] Bugfix
log service doesn't log
log service log …
> [ADF-1723] Fix log service

- ng2-components/ng2-alfresco-core/index.ts
> [ADF-18092] add missing pipe export

- ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.html
- ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.ts
- ng2-components/ng2-activiti-tasklist/src/i18n/en.json
> - [x] Bugfix
Use the translation keys of task component …
> [ADF-1758] Task Attachment - Use the translation keys of task component

- ng2-components/ng2-alfresco-core/src/components/context-menu/context-menu-holder.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/context-menu/context-menu-holder.component.ts
- prevents native context menu when the material context menu is displayed
> [ADF-1708] prevent native context menu for Menu component

- ng2-components/ng2-activiti-processlist/src/i18n/en.json
> - [ ] Bugfix
PROCESS_NAME key is missing
PROCESS_NAME key is present
**Does this PR …
> [ADF-1808] Process component - Should provide the PROCESS_NAME key

- ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.scss
> - [] Bugfix
Userinfo is not displayed correctly on small devices
improved userinfo …
>  [ADF-1783] added some more responsibility to userinfo component

- ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.ts
- ng2-components/ng2-activiti-tasklist/src/i18n/en.json
Make the existing one more specific
> - [ ] Bugfix
The "DOWNLOAD_AUDIT" "TASK_NAME" …
> [ADF-1807] Task attachment - Should provide new translation keys

- demo-shell-ng2/.angular-cli.json
- demo-shell-ng2/src/styles.css
- remove MDL dependency (including dialog polyfill needed for old MDL dialogs)
- fix CSS issue with html/body size (restore the same fix we had earlier)
> remove MDL, fix CSS issues

- ng2-components/ng2-activiti-processlist/src/components/start-process.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/start-process.component.ts
- ng2-components/ng2-activiti-tasklist/src/components/start-task.component.html
- ng2-components/ng2-activiti-tasklist/src/components/start-task.component.spec.ts
> - [x] Bugfix
START_PROCESS.ERROR.START
ADF_PROCESS_LIST.START_PROCESS.ERROR.START …
> [ADF-1819] Start task - Use the correct translation path

- docs/viewer.component.md
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.spec.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
**Please check if the PR fulfils these requirements**
> - [ ] Bugfix
- allow subscribing to the toolbar button events: share, download, print …
> [ADF-1804] viewer toolbar events

- demo-shell-ng2/package.json
- ng2-components/ng2-activiti-analytics/package.json
- ng2-components/ng2-activiti-form/package.json
- ng2-components/ng2-activiti-processlist/package.json
- ng2-components/ng2-activiti-tasklist/package.json
- ng2-components/ng2-alfresco-core/package.json
- ng2-components/package.json
> [ADF-1824] fix moment js secuirty issue

- demo-shell-ng2/resources/i18n/en.json
- demo-shell-ng2/src/app/components/files/files.component.html
- demo-shell-ng2/src/app/components/files/files.component.ts
- docs/upload-button.component.md
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
> - [ ] Bugfix
Support for max file size constraints in Upload button component
> - [ ] Yes
> - …
> [ADF-788] Support for max file size constraints in Upload button component

- demo-shell-ng2/.angular-cli.json
- demo-shell-ng2/.gitignore
- demo-shell-ng2/package.json
> - [x] Bugfix
Versions.json was not served after moving to angular-cli.
Now it is …
> [ADF-1830] Fix versions.json serving

- ng2-components/ng2-activiti-processlist/src/components/process-instance-header.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/process-instance-header.component.ts
- ng2-components/ng2-activiti-processlist/src/i18n/en.json
> - [ ] Bugfix
the businessKey property is not rendered
the businessKey property is …
> [ADF-1822] Process header - Should show the businessKey property

- demo-shell-ng2/src/polyfills.ts
> - [x] Bugfix
[Document List] IE 11 erro on click
[Document List] Is not throw any …
> [ADF-1832] [Document List] IE 11 error on click

- demo-shell-ng2/.angular-cli.json
> - [x] Bugfix
remove compatibility pdf-js that crash the app on IOS
https://issues.alfresco.com/jira/browse/ADF-1780 …
> [ADF-1780] remove compatibility pdf-js that crash the app on IOS

- docs/version-manager.component.md
- ng2-components/ng2-alfresco-documentlist/index.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1784
Fixed
**Does this …
> [ADF-1784] Fix empty folder drag&drop message for small devices

- demo-shell-ng2/src/app.config.json
- demo-shell-ng2/src/app/components/files/custom-sources.component.ts
- docs/document-list.component.md
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
- ng2-components/ng2-alfresco-documentlist/src/models/preset.model.ts
> [ADF-1794] Document List - users can see sites they are not members of

- demo-shell-ng2/src/app/components/file-view/file-view.component.html
- docs/viewer.component.md
- ng2-components/ng2-alfresco-viewer/index.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer-sidebar.component.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.scss
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.spec.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
> - [ ] Bugfix
rename 'info-drawer' to 'sidebar' to avoid confusion with the info …
> rename 'info-drawer' to 'sidebar'

- ng2-components/ng2-alfresco-login/src/components/login.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1589
Fixed
**Does this …
> [ADF-1589] IE11 style fix

- ng2-components/ng2-alfresco-login/src/components/login.component.spec.ts
- ng2-components/ng2-alfresco-login/src/components/login.component.ts
> - [x] Bugfix
Fix saving user preferences for multiple accounts
**Does this PR …
> [ADF-1839] fix issue with switching accounts

- demo-shell-ng2/.editorconfig
- demo-shell-ng2/resources/i18n/en.json
- demo-shell-ng2/src/app/components/files/files.component.html
- demo-shell-ng2/src/app/components/files/files.component.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
- ng2-components/ng2-alfresco-upload/src/i18n/en.json
add translation message versioning
missing editorconfig settings
> - [ ] Bugfix
emit message error max fie size
add translation message versioning
missing …
> [ADF-788] Emit error message for max file size

- docs/README.md
- docs/angular-material-design.md
- docs/document-list.component.md
- docs/seeAlsoGraph.json
- docs/summary.json
- docs/version-list.component.md
- docs/version-manager.component.md
> - [ ] Bugfix
Added an introduction to Angular Material in the user guide section. Also fixed a broken link and some formatting issues in a couple of other pages.
> - [ …
> [ADF-616] Document Angular Material Design

- demo-shell-ng2/.angular-cli.json
- demo-shell-ng2/package.json
- demo-shell-ng2/src/custom-style.scss
- demo-shell-ng2/src/styles.scss
- ng2-components/ng2-alfresco-core/styles/_theming.scss
- ng2-components/ng2-alfresco-core/styles/_typography.scss
- ng2-components/ng2-alfresco-core/styles/prebuilt/adf-blue-orange.scss
- ng2-components/ng2-alfresco-core/styles/prebuilt/adf-blue-purple.scss
- ng2-components/ng2-alfresco-core/styles/prebuilt/adf-cyan-orange.scss
- ng2-components/ng2-alfresco-core/styles/prebuilt/adf-cyan-purple.scss
- ng2-components/ng2-alfresco-core/styles/prebuilt/adf-green-orange.scss
- ng2-components/ng2-alfresco-core/styles/prebuilt/adf-green-purple.scss
- ng2-components/ng2-alfresco-core/styles/prebuilt/adf-indigo-pink.scss
- ng2-components/ng2-alfresco-core/styles/prebuilt/adf-pink-bluegrey.scss
- ng2-components/ng2-alfresco-core/styles/prebuilt/adf-purple-green.scss
- ng2-components/ng2-alfresco-login/src/components/login.component.html
- ng2-components/ng2-alfresco-login/src/components/login.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1846
Done
**Does this …
> [ADF-1846] Fix IE11, add material typography, remove design lite

- docs/viewer.component.md
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.scss
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.spec.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
> - [ ] Bugfix
Allow displaying sidebar component to the `left` or `right`.
**Does …
> [ADF-1853] Viewer: support left/right sidebar positioning

- docs/README.md
- docs/seeAlsoGraph.json
- docs/site.model.md
- docs/sites-api.service.md
> - [ ] Bugfix
Added docs for Sites Api service with some extra info in Sites Model.
> - [ ] Yes
> - [x] No
> [ADF-1586] Added Core services docs

- ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1601
Fixed
**Does this …
> [ADF-1601] Fix capitalisation error

- docs/document-list.component.md
> [ADF-1857] Document List - error event documentation

- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html
> - [ ] Bugfix
Automation IDs for toolbar buttons (Viewer) …
> [ADF-1855] automation ids for Viewer

- demo-shell-ng2/src/app/components/activiti/activiti.component.html
> - [x] Bugfix
Demoshell's process service was not working.
TA-DAAAA. It is working …
> [No issue number] Demoshell fix

- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
> [ADF-1863] Document List - custom sources - emit errors

- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
> - [x] Bugfix
1. Actual result: When setting max file size to 0, all files can be uploaded.
Expected result: When setting max file size to 0, only 0 bytes files can be uploaded.
**Does this PR …
> [ADF-788] fix error negative and zero value for max file size

- ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.component.scss
> - [ ] Bugfix
No background color
Fetch the background color from the theme
**Does …
> [ADF-1862] Adf Toolbar - Fetch the background color from the theme

- ng2-components/ng2-alfresco-documentlist/index.ts
> - [x] Bugfix
Export the ShareDataRow type from the index.ts.
**Does this PR …
> [ADF-1859] export ShareDataRow type

- docs/document-list.component.md
- ng2-components/ng2-alfresco-datatable/src/components/datatable/location-cell.component.spec.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/location-cell.component.ts
> [ADF-1856] Document List - location fails for granular permissions

- ng2-components/ng2-activiti-tasklist/src/components/task-list.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/task-list.component.ts
> - [x] Bugfix
The currentTaskId is not highlighted 
The currentTaskId should be …
> [ADF-1872] TaskList component - The currentTaskId should be highlighted 

- ng2-components/ng2-activiti-processlist/src/components/process-list.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/process-list.component.ts
> - [ ] Bugfix
The currentProcessId isn't highlighted
The currentProcessId should be …
> [ADF-1875] ProcessList - The currentProcessId should be highlighted

- demo-shell-ng2/package.json
- ng2-components/ng2-activiti-analytics/package.json
- ng2-components/ng2-activiti-diagrams/package.json
- ng2-components/ng2-activiti-form/package.json
- ng2-components/ng2-activiti-processlist/package.json
- ng2-components/ng2-activiti-tasklist/package.json
- ng2-components/ng2-alfresco-core/package.json
- ng2-components/ng2-alfresco-core/src/services/translation.service.ts
- ng2-components/ng2-alfresco-datatable/package.json
- ng2-components/ng2-alfresco-documentlist/package.json
- ng2-components/ng2-alfresco-login/package.json
- ng2-components/ng2-alfresco-search/package.json
- ng2-components/ng2-alfresco-social/package.json
- ng2-components/ng2-alfresco-tag/package.json
- ng2-components/ng2-alfresco-upload/package.json
- ng2-components/ng2-alfresco-userinfo/package.json
- ng2-components/ng2-alfresco-viewer/package.json
- ng2-components/ng2-alfresco-webscript/package.json
- ng2-components/package.json
> - [x] Bugfix
- upgrade the ngx-translate dependency to enable fallback languages
- …
> [ADF-1878] translation service upgrade and fixes

- ng2-components/ng2-alfresco-core/src/components/view/card-view.module.ts
> Fix production mode component dependency

- docs/README.md
- docs/summary.json
- docs/theming.md
- docs/typography.md
> - [x] Bugfix
Typography Documentation …
> [ADF-1867] Typography Documentation

- ng2-components/ng2-alfresco-core/src/models/log-levels.model.ts
- ng2-components/ng2-alfresco-core/src/services/log.service.spec.ts
> - [x] Bugfix
Warn log is not working properly  …
> [ADF-1723] log service warn fix

- ng2-components/ng2-alfresco-core/src/services/auth-guard-bpm.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard-bpm.service.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard-ecm.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard-ecm.service.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard.service.ts
- ng2-components/ng2-alfresco-core/src/services/authentication.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/authentication.service.ts
- ng2-components/ng2-alfresco-login/src/assets/authentication.service.mock.ts
- ng2-components/ng2-alfresco-login/src/components/login.component.spec.ts
- ng2-components/ng2-alfresco-login/src/components/login.component.ts
> [ADF-1633] Login should redirect to original path

- docs/deleted-nodes-api.service.md
- docs/node.service.md
- docs/nodes-api.service.md
- docs/seeAlsoGraph.json
> - [ ] Bugfix
> - [x ] Documentation
> …
> [ADF-1586] NodeService documentation

- demo-shell-ng2/src/app/components/app-layout/app-layout.component.ts
> - [x] Bugfix
The Layout demo shell labels are not translated. 
Translation support …
> [ADF-1877] - Layout demo shell not localized

- demo-shell-ng2/src/app.config.json
- demo-shell-ng2/src/app/components/activiti/activiti.component.html
- demo-shell-ng2/src/app/components/activiti/activiti.component.ts
- docs/process-list.component.md
- docs/task-list.component.md
- ng2-components/ng2-activiti-processlist/src/components/process-list.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/process-list.component.ts
- ng2-components/ng2-activiti-processlist/src/models/process-preset.model.ts
- ng2-components/ng2-activiti-tasklist/src/components/task-list.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/task-list.component.ts
- ng2-components/ng2-activiti-tasklist/src/models/task-preset.model.ts
> - [ ] Bugfix
* Task/process list columns are not customized.
* Task/process list …
> [ADF-1749] Task/Process List - Should be able to customize the rendered columns from JSON

- ng2-components/ng2-activiti-tasklist/src/components/start-task.component.html
> - [x] Bugfix
Form fields in start task were not correctly aligned
Form fields are …
> [ADF-1825] - Form field in start task no aligned

- demo-shell-ng2/resources/i18n/en.json
- ng2-components/ng2-activiti-form/src/i18n/en.json
- ng2-components/ng2-activiti-processlist/src/i18n/en.json
- ng2-components/ng2-activiti-tasklist/src/i18n/en.json
- ng2-components/ng2-alfresco-core/src/i18n/en.json
- ng2-components/ng2-alfresco-upload/src/i18n/en.json
- ng2-components/ng2-alfresco-viewer/src/i18n/en.json
- ng2-components/ng2-alfresco-webscript/src/i18n/en.json
> Dev andy adf 1877

- docs/activiti-alfresco-content.service.md
> - [ ] Bugfix
> - [x ] Documentation
> …
> [ADF-1586] ActivitiAlfrescoContentService documentation

- docs/process-content.service.md
> - [ ] Bugfix
> - [ x] Documentation
> …
> [ADF-1586] ProcessContentService documentation

- docs/process.service.md
> - [ X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Bugfix
> - [ x] Documentation
> …
> [ADF-1586] ProcessService documentation

- ng2-components/ng2-activiti-tasklist/src/assets/task-details.mock.ts
- ng2-components/ng2-activiti-tasklist/src/components/task-header.component.html
- ng2-components/ng2-activiti-tasklist/src/components/task-header.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/task-header.component.ts
- ng2-components/ng2-activiti-tasklist/src/models/task-details.model.ts
- ng2-components/ng2-activiti-tasklist/src/models/user-group.model.ts
- ng2-components/ng2-alfresco-userinfo/index.ts
> - [x] Bugfix
* The task-header component will display a Requeue button for assigned tasks. …
> [ADF-1712] The <adf-task-header component displays a Requeue button for none pooled tasks

- demo-shell-ng2/src/app/components/files/version-manager-dialog-adapter.component.html
> - [ x ] Bugfix
aot build fails
aot build runs …
> remove unexpected parameter

- ng2-components/ng2-activiti-tasklist/package.json
> - [ ] Bugfix
The tasklist doesn't have a user profile dependency
The tasklist has a …
> Fix tasklist dependency

- ng2-components/ng2-activiti-tasklist/index.ts
> fix task dependency issue

- docs/form-field.component.md
> [ADF-1586] FormFieldComponent documentation

- docs/file-draggable.directive.md
> [ADF-1586] FileDraggableDirective documentation

- demo-shell/src/styles.scss
- lib/core/viewer/components/pdfViewer.component.scss
- lib/core/viewer/components/pdfViewerHost.component.scss
Addresses:
- two scrollbars in the Viewer, issues with PDF scrolling
- PDF viewer margin fixes
- incorrect PDF toolbar position after angular/material upgrade
> fix layout issues

- docs/README.md
- lib/config/buildFullDocIndex.js
> - [ ] Bugfix
Doc index now corresponds to the new library structure and links to source files in the index point to the right place.
> - [ ] Yes
> - [x] No
> [ADF-1955] Updated doc index and script for new folder structure

- docs/alfresco-content.service.md
- docs/bpm-user.model.md
- docs/ecm-user.model.md
- docs/form-field.model.md
- docs/permissions-style.model.md
- docs/user-process.model.md
> - [x] Bugfix
Links to source files in docs are broken.
Links to source files in docs are fixed. …
> [ADF-1955] Fixed broken links to source files

- docs/process-content.service.md
- lib/core/form/components/widgets/content/content.widget.spec.ts
- lib/core/form/components/widgets/content/content.widget.ts
- lib/core/form/components/widgets/upload/upload.widget.spec.ts
- lib/core/form/components/widgets/upload/upload.widget.ts
- lib/core/form/services/process-content.service.spec.ts
- lib/core/form/services/process-content.service.ts
**Depends on https://github.com/Alfresco/alfresco-js-api/pull/292**
Allow previewing renditions for APS content
> [ADF-1889] fix preview of the APS content

- docs/search-control.component.md
- docs/search.component.md
- lib/content-services/mock/search.component.mock.ts
- lib/content-services/search/components/search-control.component.html
- lib/content-services/search/components/search-control.component.spec.ts
- lib/content-services/search/components/search-control.component.ts
- lib/content-services/search/components/search-trigger.directive.ts
- lib/content-services/search/components/search.component.spec.ts
- lib/content-services/search/components/search.component.ts
> - [ ] Bugfix
The search component query are based on the queryNode api
The search …
> [ADF-1918] added new search api service to search component

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/search/search-result.component.html
- demo-shell/src/app/components/search/search-result.component.ts
- lib/content-services/content-node-selector/content-node-selector.component.html
- lib/content-services/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/content-node-selector/content-node-selector.component.ts
- lib/content-services/document-list/components/document-list.component.html
- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/core/pagination/pagination.component.ts
> - [ ] Bugfix
Pagination component is present within document list
Removed pagination …
> [ADF-1805] rebased documentlist pagination removal

- demo-shell/src/app/components/activiti/activiti.component.html
- demo-shell/src/app/components/activiti/activiti.component.scss
- demo-shell/src/app/components/activiti/activiti.component.ts
- lib/process-services/attachment/process-attachment-list.component.html
- lib/process-services/attachment/task-attachment-list.component.html
- lib/process-services/i18n/en.json
> - [x] Bugfix
* Not able to open an attached file within a Task/process.
*  Will able …
> [ADF-1950] Not able to open an attached file within a Task.

- lib/content-services/document-list/components/document-list.component.scss
> [ADF-1973] NoPermission template missing style

- lib/core/context-menu/context-menu-holder.component.spec.ts
- lib/core/context-menu/context-menu-holder.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1969
Fixed, the quick …
> [ADF-1969] Fix buggy context-menu behaviour after cdk update

- demo-shell/src/custom-style-dev.scss
- demo-shell/src/custom-style.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1971
Fixed.
See …
> Fix login scroll-lesness issue

- demo-shell/src/app/services/in-memory-form.service.ts
> [ADF-1922] added check for undefined field

- lib/process-services/app-list/apps-list.module.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1972
Fixes
**Does this …
> [ADF-1972] BPM App list layout fix

- demo-shell/src/app/components/form/form.component.ts
> [ADF-1922] added prevent default onOutcomeClicked

- demo-shell/src/app/services/in-memory-form.service.ts
> [ADF-1922] fixed pipeline error

- lib/core/form/components/widgets/dynamic-table/dynamic-table.widget.scss
- lib/core/form/components/widgets/form.scss
- lib/core/form/components/widgets/hyperlink/hyperlink.widget.scss
- lib/core/login/components/login.component.html
- lib/core/styles/_default-class.scss
- lib/core/styles/_index.scss
- lib/process-services/attachment/process-attachment-list.component.scss
- lib/process-services/attachment/task-attachment-list.component.scss
- lib/process-services/styles/_index.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1975
Fixed.
**Does this …
> [ADF-1975] Fixing missing style mixin invocations

- demo-shell/src/app/components/app-layout/app-layout.component.html
- demo-shell/src/app/components/app-layout/app-layout.component.scss
- demo-shell/src/app/components/search/search-bar.component.html
- demo-shell/src/app/components/search/search-bar.component.ts
- lib/content-services/search/components/search-control.component.html
- lib/content-services/search/components/search-control.component.scss
- lib/content-services/search/components/search-control.component.ts
- lib/content-services/search/components/search-trigger.directive.ts
> - [x] Bugfix
- removes the hack from the demo shell styles (app layout)
- fixes …
> [ADF-1980] fix search component styles

- lib/process-services/people/people-search.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1948
Fixed
**Does this …
> [ADF-1948] Fix rxjs debounceTime

- lib/core/services/auth-guard-ecm.service.spec.ts
- lib/core/services/auth-guard-ecm.service.ts
> [ADF-1993] AuthGuardEcm - canActivateChild is missing

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
Disable "create folder" dialogue if the user has no permission.
> [ADF-1774] auto-disable "new folder" dialog in demo shell

- demo-shell/src/app/components/activiti/activiti.component.ts
- lib/core/form/components/widgets/dynamic-table/date-cell-validator-model.ts
- lib/core/form/components/widgets/dynamic-table/dynamic-row-validation-summary.model.ts
- lib/core/form/components/widgets/dynamic-table/dynamic-table.widget.model.ts
- lib/core/form/components/widgets/dynamic-table/editors/row.editor.html
- lib/core/form/components/widgets/dynamic-table/editors/row.editor.spec.ts
- lib/core/form/components/widgets/dynamic-table/editors/row.editor.ts
- lib/core/form/components/widgets/dynamic-table/number-cell-validator.model.ts
- lib/core/form/components/widgets/dynamic-table/required-cell-validator.model.ts
- lib/core/form/components/widgets/error/error.component.html
- lib/core/form/components/widgets/error/error.component.ts
> - [X] Bugfix
Dynamic Table are not using the same error object for validation …
> [ADF-1921] fixed error message for dynamic table

- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.scss
> [ADF-2001] change fxLayout to column

- lib/process-services/app-list/apps-list.component.scss
> - [x] Bugfix
App list styles are not correct, lines goes through the box.
Css fixed. …
> [ADF-NO-ISSUE] Fix app-list css issue

- lib/core/directives/node-permission.directive.spec.ts
- lib/core/directives/node-permission.directive.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1965
Fixed
**Does this …
> [ADF-1965] Restore original functionality of node-permission directive

- lib/content-services/content-node-selector/content-node-selector.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2006
Fixed
**Does this …
> [ADF-2006] Fix document list style misalignment in copy/move dialog

- docs/process-filter.service.md
- docs/process.service.md
> [ADF-1586] ProcessService & ProcessFilterService documentation update because of 2.0 reorg

- docs/task-filter.service.md
- docs/tasklist.service.md
> [ADF-1586] TaskListService & TaskFilterService documentation

- lib/content-services/content-node-selector/public-api.ts
> - [x] Bugfix
Add missing export for the interface …
> add missing export

- lib/core/login/components/login.component.scss
> - [x] Bugfix
Make the login on small device great again.
Fixed.
**Does this PR …
> [ADF_NO-ISSUE] Make login small screen size compatible

- docs/people-list.component.md
> [ADF-1586] PeopleListComponent documentation update because of 2.0 reorg

- docs/comment-list.component.md
> [ADF-1586] CommentListComponent documentation update because of 2.0 reorg

- lib/content-services/content-node-selector/content-node-selector.component.scss
- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2006
Fixed
**Does this …
> [ADF-2006] Fix misalignment in FF also

- docs/task-details.component.md
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.spec.ts
- lib/process-services/task-list/components/task-details.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2012
Fixed
**Does this …
> [ADF-2012] Remove sidebar functionality from task details

- lib/content-services/social/like.component.spec.ts
- lib/content-services/social/like.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2009
Fixed
**Does this …
> [ADF-2009] Fix Like component to be reactive on change of nodeId parameter

- docs/process-content.service.md
> [ADF-1586] ProcessContentService documentation update because of 2.0 reorg

- demo-shell/src/app/components/files/files.component.html
- docs/upload.service.md
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2022
Fixed
**Does this …
> [ADF-2022] Make allowed extension more obvious

- docs/task-details.component.md
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.spec.ts
- lib/process-services/task-list/components/task-details.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2012
Fixed
**Does this …
> [ADF-2012] Restore functionality, which was removed the brainless way

- docs/accordion-group.component.md
- docs/accordion.component.md
- docs/analytics-generator.component.md
- docs/analytics-report-list.component.md
- docs/analytics.component.md
- docs/apps-list.component.md
- docs/checklist.component.md
- docs/comments.component.md
- docs/create-process-attachment.component.md
- docs/create-task-attachment.component.md
- docs/file-uploading-dialog.component.md
- docs/like.component.md
- docs/rating.component.md
- docs/seeAlsoGraph.json
- docs/sites-dropdown.component.md
> - [ ] Bugfix
Removed unnecessary tables of contents from docs and added See Also sections where appropriate.
> - [ ] Yes
> - [x] No
> [ADF-1586] Removed ToCs and added See Alsos

- docs/node-permission.directive.md
- lib/content-services/upload/components/upload-button.component.ts
- lib/content-services/upload/components/upload-drag-area.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2029
Fixed
**Does this …
> [ADF-2029] Fix node-permission directive for delete

- lib/content-services/search/components/search-control.component.html
- lib/content-services/search/components/search-control.component.scss
- lib/content-services/search/components/search-control.component.spec.ts
- lib/content-services/search/components/search-control.component.ts
- lib/content-services/search/components/search-trigger.directive.ts
> - [X] Bugfix
Arrow for result not supported.
Changing browser tab will not disable the search box …
> [ADF-2002] added ARROW support for search autocomplete results

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- docs/pagination.component.md
- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/core/pagination/paginated-component.interface.ts
- lib/core/pagination/pagination.component.spec.ts
- lib/core/pagination/pagination.component.ts
> - [x] Bugfix
- Provide integration for Document List and Pagination
- update demo …
> [ADF-2016] pagination integration for document list

- docs/FormFieldValidator.md
- docs/activiti-alfresco.service.md
- docs/app-config.service.md
- docs/authentication.service.md
- docs/card-view.component.md
- docs/data-column.component.md
- docs/datatable.component.md
- docs/document-actions.service.md
- docs/document-list.component.md
- docs/extensibility.md
- docs/folder-actions.service.md
- docs/form.component.md
- docs/form.service.md
- docs/log.service.md
- docs/node-permission.directive.md
- docs/nodes-api.service.md
- docs/notification.service.md
- docs/translation.service.md
- docs/user-preferences.service.md
- docs/widget.component.md
> - [ ] Bugfix
Updated import statements in doc code samples to use the new folder structure.
> - [ ] Yes
> - [x] No
> [ADF-1586] Updated paths of import statements in docs

- demo-shell/src/app/components/process-service/process-attachments.component.html
- demo-shell/src/app/components/process-service/process-attachments.component.ts
- demo-shell/src/app/components/process-service/process-service.component.ts
- demo-shell/src/app/components/process-service/task-attachments.component.html
- demo-shell/src/app/components/process-service/task-attachments.component.ts
- lib/process-services/attachment/task-attachment-list.component.ts
- lib/process-services/process-list/components/process-filters.component.spec.ts
- lib/process-services/process-list/services/process-filter.service.ts
- lib/process-services/process-list/services/process.service.spec.ts
- lib/process-services/process-list/services/process.service.ts
- lib/process-services/task-list/public-api.ts
- lib/process-services/task-list/services/task-upload.service.ts
> - [x] Bugfix
Drag and drop is not working on Processes - attachment List
export ActivitiContentService
ProcessService.createOrUpdateProcessInstanceVariables has …
> [ADF-2035] Drag and drop is not working on Processes - attachment List

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/overlay-viewer/overlay-viewer.component.html
- demo-shell/src/app/components/overlay-viewer/overlay-viewer.component.ts
- docs/viewer.component.md
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
Fix issue related to subsequent reopenings of the Viewer in the …
> [ADF-2032] viewer reopening fixes

- lib/core/viewer/components/pdfViewer.component.scss
- lib/core/viewer/components/pdfViewerHost.component.scss
- lib/core/viewer/components/viewer.component.scss
> - [x] Bugfix
- fix styles for PDF viewer: vertical height, toolbar position
- fix …
> [ADF-2033] viewer style fixes

- demo-shell/src/app/components/overlay-viewer/overlay-viewer.component.ts
- demo-shell/src/app/components/search/search-result.component.html
- demo-shell/src/app/components/search/search-result.component.ts
- demo-shell/src/app/components/webscript/webscript.component.ts
- docs/search-control.component.md
- docs/search.component.md
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/mock/search.component.mock.ts
- lib/content-services/search/components/search-control.component.html
- lib/content-services/search/components/search-control.component.ts
- lib/content-services/search/components/search.component.ts
> - [x] Bugfix
ADF-2045
[Demo-Shell]Pagination is not working properly on Search Results Page …
> [ADF-2045] Pagination is not working properly on Search Results Page

- BROWSER-SUPPORT.md
- INTRODUCTION.md
- PREREQUISITES.md
- README.md
- docs/README.md
- docs/extensibility.md
- docs/notification.service.md
- docs/stencils.md
- docs/summary.json
- replace "Angular 2" with just "Angular"
- replace some "Angular 1" occurrences with "AngularJS"
- remove some old/outdated info
> cleanup angular versions

- demo-shell/src/app/components/process-service/process-attachments.component.html
- demo-shell/src/app/components/process-service/task-attachments.component.html
- lib/process-services/attachment/task-attachment-list.component.html
- lib/process-services/attachment/task-attachment-list.component.spec.ts
- lib/process-services/attachment/task-attachment-list.component.ts
> [ADF-1711] Task Attachment list - fix custom template

- INTRODUCTION.md
- README.md
- lib/content-services/README.md
- lib/insights/README.md
- lib/process-services/README.md
> - [ ] Bugfix
Updated links to source folders and docs in README files, etc. Also made a few small content changes (eg, removed "ng2").
> - [ ] Yes
> - [x] No
> [ADF-2046] Updated links in README files for new folder structure

- demo-shell/src/app/components/search/search-result.component.html
- demo-shell/src/app/components/search/search-result.component.ts
- lib/content-services/search/components/search-control.component.html
> Renamed customSearchNode to customQueryBody into search control

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/process-service/process-attachments.component.ts
- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- demo-shell/src/app/components/process-service/task-attachments.component.ts
- docs/process-attachment-list.component.md
- docs/task-attachment-list.component.md
- lib/process-services/attachment/attachment.module.ts
- lib/process-services/attachment/process-attachment-list.component.ts
- lib/process-services/attachment/task-attachment-list.component.ts
- lib/process-services/task-list/task-list.module.ts
> [ADF-1711] Task Attachment list - Fix the TaskService dependency

- lib/core/styles/_mixins.scss
- lib/process-services/app-list/apps-list.component.html
- lib/process-services/app-list/apps-list.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1959
Fixed
**Does this …
> [ADF-1959] Fix line clamp temporary

- lib/content-services/search/components/search-control.component.html
> Adding automation-id to search-control component

- demo-shell/src/app.config.json
- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- lib/core/services/user-preferences.service.spec.ts
- lib/core/services/user-preferences.service.ts
> [ADF-2025] Task List - The pagination should be fetched from the UserPreference

- docs/viewer.component.md
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2060
Fixed.
**Does this …
> [ADF-2060] Update viewer documentation

- lib/content-services/content-node-selector/content-node-selector.component.html
- lib/content-services/content-node-selector/content-node-selector.component.scss
- lib/content-services/content-node-selector/content-node-selector.module.ts
- lib/content-services/content-node-selector/name-location-cell/name-location-cell.component.html
- lib/content-services/content-node-selector/name-location-cell/name-location-cell.component.scss
- lib/content-services/content-node-selector/name-location-cell/name-location-cell.component.spec.ts
- lib/content-services/content-node-selector/name-location-cell/name-location-cell.component.ts
- lib/content-services/styles/_index.scss
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1431
Implemented. …
> [ADF-1431] Destination Picker: Display path of the folder in search results

- demo-shell/src/app/components/about/about.component.ts
> Fix the title of Model column in ECM License datatable.

- docs/card-view.component.md
- lib/core/card-view/card-view-textitem.component.html
- lib/core/card-view/card-view-textitem.component.ts
- lib/process-services/task-list/components/task-header.component.spec.ts
- lib/process-services/task-list/components/task-header.component.ts
> - [ ] Bugfix
Currently the priority property of the task header is NOT editable
The …
> [ADF-1826] Task Header - The priority property should be editable

- lib/content-services/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/content-node-selector/content-node-selector.service.spec.ts
- lib/content-services/content-node-selector/content-node-selector.service.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2061
Fixed
**Does this …
> [ADF-2061] Fix content node selector search

- lib/core/card-view/card-view-textitem.component.ts
* Fixed the console error coming while adding description or priority in task details
> - [x] Bugfix
console error …
> [ADF-2069] Error is displayed on console when adding a description to a task.

- lib/core/pagination/pagination.component.spec.ts
- lib/core/pagination/pagination.component.ts
> - [ ] Bugfix
Adds special CSS class if pagination is empty, helps building …
> [ADF-2049] special CSS class if pagination is empty

- lib/core/form/components/widgets/core/index.ts
> - [x] Bugfix
Add missing exports …
> [ADF-1888] add missing exports

- lib/process-services/task-list/public-api.ts
> - [x] Bugfix
Adds missing exports for task-list  …
> [ADF-1926] add missing exports

- demo-shell/src/app.config.json
- docs/task-list.component.md
- lib/process-services/task-list/components/task-list.component.spec.ts
- lib/process-services/task-list/components/task-list.component.ts
> - [ ] Bugfix
Right now, the static columns (customisable from app.config.json ) and the custom one are mutually …
> [ADF-2102] Task List - Provide a way to support custom html template and static columns at same time

- lib/core/form/components/form.component.html
- lib/core/form/components/form.component.scss
- lib/core/form/components/form.component.spec.ts
- lib/core/form/components/form.component.ts
> [ADF-2094] Task Form - Doesn't follow the specification

- docs/info-drawer.component.md
- lib/core/info-drawer/info-drawer.component.html
- lib/core/info-drawer/info-drawer.component.spec.ts
- lib/core/info-drawer/info-drawer.component.ts
> - [ ] Bugfix
Provide a way to select a different tab …
> [ADF-2103] Info Drawer - Provide a way to select a different tab

- lib/process-services/task-list/components/task-list.component.ts
> - [x] Bugfix
* Right now, the static columns (customisable from app.config.json ) and the custom one are mutually …
> [ADF-2102] Task List - fix array concat error

- demo-shell/src/app/components/process-service/process-service.component.html
- lib/process-services/process-list/services/process-filter.service.spec.ts
- lib/process-services/process-list/services/process-filter.service.ts
- lib/process-services/task-list/services/task-filter.service.spec.ts
- lib/process-services/task-list/services/task-filter.service.ts
> - [x] Bugfix
* Not able to see the 'My tasks' filter when clicking on a newly created app. …
> [ADF-2067] Not able to see the 'My tasks' filter when clicking on a newly created app.

- lib/core/form/components/form-field/form-field.component.ts
> Custom Stencil - Fix adf is not defined 

- lib/core/form/components/form.component.scss
- lib/core/styles/_index.scss
> [ADF-2109] Task Form - The form doesn't fit in the mobile screen

- demo-shell/src/app/components/process-service/process-service.component.ts
- lib/content-services/document-list/components/document-list.component.ts
* Changed the service fetching page sizes in document-list component
* uncommented a line in process-service.component.ts to show page-sizes in task-list
> - [x] Bugfix …
> [ADF-2119] Document List - The pagination should be fetched from the UserPreference

- lib/core/services/translate-loader.service.ts
> - [x] Bugfix
Disable caching for translation files to allow loading newer …
> cache busting for translation files

- lib/core/datatable/components/datatable/filesize-cell.component.ts
- lib/core/i18n/en.json
- lib/core/i18n/ru.json
- lib/core/pipes/file-size.pipe.spec.ts
- lib/core/pipes/file-size.pipe.ts
- lib/core/services/translation.service.ts
> - [ ] Bugfix
- provides i18n support for the "fileSize" pipe
**Does this PR …
> [ADF-1999] i18n support for file size pipe

- docs/extensibility.md
> - [ ] Bugfix
Updated the guide with the correct APS reference
**Does this PR …
> [ADF-2122] documentation updates

- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.scss
> - [x] Bugfix
- Add support to customize custom extension containers styles (extra …
> [ADF-2116] viewer styling improvements

- .travis.yml
- lib/config/karma.conf-all.js
> - [ ] Bugfix
- Adds missing "Headless Chrome" settings
- removes unnecessary cache …
> add missing headless chrome setup for Travis

- docs/README.md
- docs/activiti-alfresco.service.md
- docs/folder-create.directive.md
- docs/folder-edit.directive.md
- docs/form-field.model.md
- docs/host-settings.component.md
- docs/like.component.md
- docs/node-restore.directive.md
- docs/node.service.md
- docs/process-content.service.md
- docs/rating.component.md
- docs/start-process.component.md
- docs/tag-actions.component.md
- docs/tag-list.component.md
- docs/tag-node-list.component.md
- docs/upload-button.component.md
- docs/user-info.component.md
- docs/version-list.component.md
- lib/config/DocProcessor/docProcessor.js
- lib/config/DocProcessor/doctool.config.json
- lib/config/DocProcessor/ngHelpers.js
- lib/config/DocProcessor/tools/index.js
- lib/config/DocProcessor/tools/seealso.js
- lib/config/DocProcessor/tools/toc.js
- lib/config/DocProcessor/tools/tscProps.js
- lib/config/DocProcessor/tools/tscProps.ts
- lib/config/DocProcessor/unistHelpers.js
> - [ ] Bugfix
New doc tools added. Currently only the indexing tool is enabled because the changes need to be introduced in stages (otherwise many files would need to be modified at once). The changes to the MD files are to ensure the …
> [ADF-2127] Started introducing new doc tools

- .travis.yml
- lib/config/karma.conf-all.js
- lib/content-services/content-node-selector/content-node-selector.component.ts
- lib/core/card-view/card-view-textitem.component.ts
> - [ ] Bugfix
Travis stopped to work
Add fixed stable version of chrome in Travis …
> [fix-build] add stable version chrome in travis conf

- lib/content-services/document-list/components/content-column/content-column.component.ts
- lib/content-services/folder-directive/folder-create.directive.ts
- lib/content-services/folder-directive/folder-edit.directive.ts
- lib/content-services/search/components/search-trigger.directive.ts
- lib/content-services/upload/directives/file-draggable.directive.ts
- lib/core/context-menu/context-menu.directive.ts
- lib/core/data-column/data-column.component.ts
- lib/core/directives/highlight.directive.ts
- lib/core/directives/node-delete.directive.ts
- lib/core/directives/node-favorite.directive.ts
- lib/core/directives/node-permission.directive.ts
- lib/core/directives/node-restore.directive.ts
- lib/core/directives/upload.directive.ts
- lib/core/form/components/widgets/checkbox/checkbox.widget.ts
- lib/core/form/components/widgets/number/number.widget.ts
- lib/core/form/components/widgets/text/text-mask.component.ts
- lib/core/pagination/infinite-pagination.component.ts
- lib/insights/analytics-process/components/widgets/checkbox/checkbox.widget.ts
- lib/insights/analytics-process/components/widgets/date-range/date-range.widget.ts
- lib/insights/analytics-process/components/widgets/dropdown/dropdown.widget.ts
- lib/insights/analytics-process/components/widgets/duration/duration.widget.ts
- lib/insights/analytics-process/components/widgets/number/number.widget.ts
- lib/process-services/process-list/components/process-audit.directive.ts
- lib/process-services/task-list/components/task-audit.directive.ts
- lib/tslint.json
> - [ ] Bugfix
Enforce this rule in our tslint.json 
"no-input-rename": true,
"no-output-rename": true, …
> [ADF-1775] No input and No Output rename tslint rule

- lib/core/mock/traslation.service.mock.ts
- lib/core/pipes/file-size.pipe.ts
> - [x] Bugfix
Fix translation for 0-byte files …
> [ADF-1999] fix file size translation for 0 bytes

- docs/README.md
- docs/alfresco-api.service.md
- docs/analytics-generator.component.md
- docs/analytics-report-list.component.md
- docs/analytics.component.md
- docs/app-config.service.md
- docs/authentication.service.md
- docs/comment-list.component.md
- docs/content-action.component.md
- docs/content.widget.md
- docs/context-menu.directive.md
- docs/data-column.component.md
- docs/datatable.component.md
- docs/document-list.component.md
- docs/form-list.component.md
- docs/node-name-tooltip.pipe.md
- docs/search.component.md
- docs/viewer.component.md
- docs/webscript.component.md
- lib/config/DocProcessor/docProcessor.js
- lib/config/DocProcessor/doctool.config.json
- lib/config/DocProcessor/tools/index.js
- lib/config/DocProcessor/tools/toc.js
> - [ ] Bugfix
Reconstructed and combined previous PRs. Tools, tables of contents and index page have been updated.
> - [ ] Yes
> - [x] No
> [ADF-2135] Updated tables of contents and tools

- .travis.yml
- lib/config/karma.conf-all.js
- lib/core/services/content.service.ts
- lib/core/services/thumbnail.service.ts
- lib/package.json
> - [ ] Bugfix
Last version of scss-bundle has problems with comments
> - [ ] Yes
> - [x] No
If …
> [no-issue] downgrade scss bundle and some other minor fix

- lib/content-services/document-list/components/document-list.component.ts
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/core/login/components/login.component.ts
- lib/process-services/task-list/components/task-list.component.ts
> - [ ] Bugfix
Added JSDoc for a few components. Preparing to test the property/event table tools.
> - [ ] Yes
> - [x] No
> [ADF-1769] Added JSDoc for components

- docs/form.component.md
- docs/login.component.md
- docs/logout.directive.md
- docs/node-permission.directive.md
- docs/nodes-api.service.md
- docs/notification.service.md
- docs/pagination.component.md
- docs/people-search.component.md
- docs/people.component.md
- docs/process-comments.component.md
- docs/process-instance-details.component.md
- docs/process-instance-header.component.md
- docs/process-instance-tasks.component.md
- docs/process-list.component.md
- docs/search-control.component.md
- docs/toolbar.component.md
- docs/upload.directive.md
> - [ ] Bugfix
Updated remaining tables of contents.
> - [ ] Yes
> - [x] No
> [ADF-2135] Updated tables of contents

- lib/core/sidebar/sidebar-action-menu.component.html
> [ADF-2172]Adding data-automation-id for create task/process button

- docs/accordion-group.component.md
- docs/accordion.component.md
- docs/angular-material-design.md
- docs/auth-guard-bpm.service.md
- docs/auth-guard-ecm.service.md
- docs/auth-guard.service.md
- docs/bpm-user.model.md
- docs/bpm-user.service.md
- docs/breadcrumb.component.md
- docs/comment-process.model.md
- docs/comment-process.service.md
- docs/content-node-selector.component.md
- docs/content.service.md
- docs/ecm-user.model.md
- docs/ecm-user.service.md
- docs/extensibility.md
> - [ ] Bugfix
Started updating See Also sections in docs using the new tool. Resubmitting to fix problems with an earlier PR.
> - [ ] Yes
> - [x] No
> [ADF-2152] Updated See Also sections in docs

- docs/document-list.component.md
- lib/config/DocProcessor/tools/tscProps.js
- lib/config/DocProcessor/tools/tscProps.ts
- lib/config/DocProcessor/unistHelpers.js
- lib/content-services/document-list/components/document-list.component.ts
> - [ ] Bugfix
Fixed some errors in the generated Markdown text and added code style to types. Also removed default value column from the table and replaced with a line in the description column. The reason for this is that the default …
> [ADF-1769] Updates to prop table script

- lib/content-services/content-node-selector/content-node-dialog.service.spec.ts
- lib/content-services/content-node-selector/content-node-dialog.service.ts
- lib/core/card-view/card-view.module.ts
- lib/core/viewer/components/viewer.component.ts
- lib/process-services/content-widget/attach-folder-widget.component.html
- lib/process-services/content-widget/attach-folder-widget.component.scss
- lib/process-services/content-widget/attach-folder-widget.component.spec.ts
- lib/process-services/content-widget/attach-folder-widget.component.ts
- lib/process-services/content-widget/content-widget.module.ts
- lib/process-services/process-list/components/start-process.component.ts
- lib/process-services/task-list/components/task-details.component.ts
> - [ ] Bugfix
No widget is provided for attach folder
New widget is added for attach …
> [ADF-325] added attach folder widget

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/search/search-result.component.html
- demo-shell/src/app/components/search/search-result.component.ts
> - [X] Bugfix
The result are not refreshed when an element is deleted
The result are …
>  [ADF-2053] improved search result adding refresh on delete

- docs/FormFieldValidator.md
- docs/README.md
- docs/favorites-api.service.md
- docs/file-draggable.directive.md
- docs/file-size.pipe.md
- docs/file-uploading-dialog.component.md
- docs/filter.model.md
- docs/folder-actions.service.md
- docs/folder-create.directive.md
- docs/form-field.component.md
- docs/form-field.model.md
- docs/form-rendering.service.md
- docs/form.component.md
- docs/form.service.md
- lib/config/DocProcessor/doctool.config.json
- lib/package.json
> - [ ] Bugfix
Updated some more See Also sections. Also set up the doc script to generate just the index and replaced the old "npm run docindex" in package.json.
> - [ …
> [ADF-2152] Added See Also sections and updated doc tools

- lib/process-services/process-list/components/start-process.component.scss
- lib/process-services/task-list/components/start-task.component.scss
> - [x] Bugfix
The card with is with 66% and the margin are wrong
The card with is …
> [ADF-2179] Start Task/Process - Improve the size for the mobile devices

- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2133
Fixed
**Does this …
> [ADF-2133] Remove wrapping form datatable header

- lib/process-services/process-list/components/process-instance-header.component.ts
- lib/process-services/task-list/components/task-header.component.ts
> - [x] Bugfix
The default keys are not traslated
The default keys contains the …
> [ADF-2173] Task/Process header - Fix default translation keys

- docs/accordion-group.component.md
- docs/accordion.component.md
- docs/apps-list.component.md
- docs/breadcrumb.component.md
- docs/checklist.component.md
- docs/comment-list.component.md
- docs/comments.component.md
- docs/content-action.component.md
- docs/create-process-attachment.component.md
- docs/create-task-attachment.component.md
- docs/data-column.component.md
- docs/document-list.component.md
- docs/dropdown-breadcrumb.component.md
- lib/config/DocProcessor/tools/tscProps.js
- lib/config/DocProcessor/tools/tscProps.ts
- lib/content-services/breadcrumb/breadcrumb.component.ts
- lib/content-services/document-list/components/content-action/content-action.component.ts
- lib/core/collapsable/accordion-group.component.ts
- lib/core/data-column/data-column.component.ts
- lib/process-services/app-list/apps-list.component.ts
- lib/process-services/attachment/create-process-attachment.component.ts
- lib/process-services/attachment/create-task-attachment.component.ts
- lib/process-services/comments/comment-list.component.ts
- lib/process-services/comments/comments.component.ts
- lib/process-services/task-list/components/checklist.component.ts
> - [ ] Bugfix
Added JSDocs to sources. Also fixed two issues with the prop table tool: Markdown wasn't transferred properly from the JSDoc comments and get/set accessors weren't picked up correctly as properties.
**Does this PR …
> [ADF-1769] Added JSDocs and updated prop table script

- demo-shell/package.json
> Fix build - Add @angular-devkit/core as dev dependency

- demo-shell/resources/i18n/de.json
- demo-shell/resources/i18n/en.json
- demo-shell/resources/i18n/it.json
- demo-shell/src/app/components/files/files.component.ts
> - [X] Bugfix
The tooltip message is not correctly translated
The tooltip message is …
> [ADF-2183] fixed translation on no permission tooltip

- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2178
Fixed
**Does this …
> [ADF-2178] Fix localisation in Datetimepicker

- demo-shell/src/app/components/files/files.component.html
- docs/infinite-pagination.component.md
- lib/content-services/document-list/components/document-list.component.ts
- lib/core/pagination/infinite-pagination.component.spec.ts
- lib/core/pagination/infinite-pagination.component.ts
- lib/core/pagination/paginated-component.interface.ts
- lib/core/pagination/pagination.component.spec.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2157
Fixed
**Does this …
> [ADF-2157] Infinite pagination target supporting

- lib/config/DocProcessor/tools/tscProps.js
- lib/config/DocProcessor/tools/tscProps.ts
> - [ ] Bugfix
Updated prop table script to handle components that inherit properties from other component classes (eg, Dropdown Breadcrumb). No changes to any doc files or component source files. …
> [ADF-1769] Updated prop table script to handle inherited classes

- demo-shell/src/app/components/process-service/process-service.component.ts
> - [x] Bugfix
An error happens when the same process filter has been clicked
The user …
> [ADF-2115] Demo Shell - remove processInstanceId reset

- lib/core/styles/_index.scss
- lib/core/viewer/components/pdfViewer.component.html
- lib/core/viewer/components/pdfViewer.component.scss
- lib/core/viewer/components/pdfViewerHost.component.scss
- lib/core/viewer/components/txtViewer.component.scss
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.scss
> - [x] Bugfix
Style fixes as per design docs:
- fix the background colour
- fix …
> style fixes for viewer

- lib/content-services/content-node-selector/content-node-dialog.service.spec.ts
- lib/content-services/content-node-selector/content-node-dialog.service.ts
> - [X] Bugfix
No message is showed when user does not have permission on copy and move action …
> [ADF-2196] fixed error message for no permission on copy and move

- lib/process-services/task-list/components/task-header.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2205
Fixed
**Does this …
> [ADF-2205] Fix missing translation

- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
See comment of https://issues.alfresco.com/jira/browse/ADF-2186
Fixed …
> [ADF-2186] Fix sidebar node reloading issue

- lib/core/form/components/widgets/amount/amount.widget.scss
> - [x] Bugfix
The margin top was not aligned inside the amount widget
The amount …
> [ADF-2213] Start form - Fix margin top

- docs/README.md
- docs/renditions.service.md
> - [ ] Bugfix
Updated Renditions service docs with new method details, descriptions and links.
> - [ ] Yes
> - [x] No
> [ADF-2201] Updated renditions service docs

- demo-shell/src/app.config.json
- demo-shell/src/app/app.component.ts
- lib/core/login/components/login.component.spec.ts
- lib/core/login/components/login.component.ts
- lib/core/models/redirection.model.ts
- lib/core/services/auth-guard-bpm.service.spec.ts
- lib/core/services/auth-guard-bpm.service.ts
- lib/core/services/auth-guard-ecm.service.spec.ts
- lib/core/services/auth-guard-ecm.service.ts
- lib/core/services/auth-guard.service.spec.ts
- lib/core/services/auth-guard.service.ts
- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
>  [ADF-2200] fixed problem with redirection url

- lib/core/form/components/form.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2209
Fixed
**Does this …
> [ADF-2209] Fix css error

- demo-shell/src/app.config.json
- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/start-process.component.md
- lib/process-services/process-list/components/start-process.component.html
- lib/process-services/process-list/components/start-process.component.spec.ts
- lib/process-services/process-list/components/start-process.component.ts
> - [x] Bugfix
change the property name from processDefinition to processDefinitionName …
> [ADF-2188] Start Process - Change processDefinition property and fix bug

- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
> [ADF-2200] fixed redirectUrl check

- lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/content-node-selector/content-node-selector.service.spec.ts
- lib/content-services/content-node-selector/content-node-selector.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2221
fixed bug
**Does this …
> [ADF-2221] Search fails on Content Node Selector

- docs/README.md
- docs/authentication.service.md
- docs/card-view.component.md
- docs/file-uploading-dialog.component.md
- docs/form-field.model.md
- docs/search-control.component.md
- docs/search.component.md
- docs/task-details.model.md
- docs/task-header.component.md
> - [ ] Bugfix
Fixed broken links found by a link checker tool.
> - [ ] Yes
> - [x] No
> [ADF-2201] Fixed broken links

- lib/content-services/content.module.ts
- lib/insights/insights.module.ts
- lib/process-services/process.module.ts
> - [x] Bugfix
If you import the library in a 2.0.0 project you are going to have an error for multiple material …
> [No-issue] export material only from the core

- docs/start-process.component.md
> - [ ] Bugfix
Remove app.config reference from doc  …
> [ADF-2188] Start process - Remove app.config reference from doc

- lib/content-services/content-node-selector/content-node-dialog.service.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/i18n/en.json
> - [x] Bugfix
Added new keys which need to be translated in all available languages. …
> [ADF-2000] Destination picker is not completely translated

- docs/viewer.component.md
- lib/core/i18n/en.json
- lib/core/mock/event.mock.ts
- lib/core/styles/_index.scss
- lib/core/viewer/components/imgViewer.component.html
- lib/core/viewer/components/imgViewer.component.scss
- lib/core/viewer/components/imgViewer.component.spec.ts
- lib/core/viewer/components/imgViewer.component.ts
- lib/core/viewer/components/pdfViewer.component.html
- lib/core/viewer/components/pdfViewer.component.scss
- lib/core/viewer/components/pdfViewer.component.ts
- lib/core/viewer/components/txtViewer.component.scss
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.scss
- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [ ] Bugfix
- [ADF-2206](https://issues.alfresco.com/jira/browse/ADF-2206): …
> [ADF-1412] Viewer enhancements

- lib/process-services/comments/comment-list.component.html
> - [X] Bugfix
Comment list are not ordered by created By user
Comment list are …
> [ADF-2215] modified key to allow search for createdBy email

- lib/core/i18n/en.json
- lib/core/services/thumbnail.service.ts
- lib/core/viewer/components/imgViewer.component.html
- lib/core/viewer/components/imgViewer.component.spec.ts
- lib/core/viewer/components/imgViewer.component.ts
- lib/core/viewer/components/pdfViewer.component.html
- lib/core/viewer/components/pdfViewer.component.scss
- lib/core/viewer/components/viewer.component.scss
> - [ ] Bugfix
- basic panning support, it is now possible to drag the image after …
> [ADF-1416] image viewer enhancements

- docs/README.md
- docs/rating.component.md
- docs/search-control.component.md
- docs/search.component.md
- docs/sidebar-action-menu.component.md
- docs/sites-dropdown.component.md
- lib/content-services/search/components/search-control.component.ts
- lib/content-services/search/components/search.component.ts
- lib/content-services/site-dropdown/sites-dropdown.component.ts
- lib/content-services/social/rating.component.ts
- lib/core/sidebar/sidebar-action-menu.component.ts
> - [ ] Bugfix
Added JSDocs and prop tables for components. Also fixed some broken links in README.md.
> - [ ] Yes
> - [x] No
> [ADF-1769] Added JSDocs and prop tables

- appveyor.yml
> - [x] Bugfix
appveyor is not owrking
appveyor …
> [NO-ISSUE] appveyor build fix experimenting

- lib/core/info-drawer/info-drawer.module.ts
- lib/core/sidebar/sidebar-action.module.ts
> - [ ] Bugfix
adds missing exports and declarations
Note: does not fully fix the AoT …
> AOT: add missing exports and declarations

- docs/start-form.component.md
- docs/start-process.component.md
- docs/start-task.component.md
- docs/tag-actions.component.md
- docs/tag-list.component.md
- docs/tag-node-list.component.md
- docs/task-attachment-list.component.md
- lib/content-services/tag/tag-actions.component.ts
- lib/content-services/tag/tag-list.component.ts
- lib/content-services/tag/tag-node-list.component.ts
- lib/core/form/components/start-form.component.ts
- lib/process-services/attachment/task-attachment-list.component.ts
- lib/process-services/process-list/components/start-process.component.ts
- lib/process-services/task-list/components/start-task.component.ts
> - [ ] Bugfix
Added prop tables and JSDocs.
> - [ ] Yes
> - [x] No
> [ADF-1769] Added prop tables and JSDocs

- demo-shell/package.json
- lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/content-node-selector/content-node-selector.service.spec.ts
- lib/content-services/content-node-selector/content-node-selector.service.ts
- lib/content-services/document-list/components/document-list.component.ts
> - [x] Bugfix
Please see https://issues.alfresco.com/jira/browse/ADF-2242
fixed bug …
> [ADF-2242] Search on custom sources is not working.

- demo-shell/src/app/components/files/files.component.html
- docs/content-action.component.md
- lib/content-services/document-list/components/content-action/content-action.component.spec.ts
- lib/content-services/document-list/components/content-action/content-action.component.ts
- lib/content-services/document-list/models/content-action.model.ts
> - [ ] Bugfix
You must specify the target for document and folder to show the action …
> [ADF-2163] added target all for content actions

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/process-list.component.md
- docs/task-list.component.md
- lib/core/pagination/pagination.component.spec.ts
- lib/core/pagination/pagination.component.ts
- lib/process-services/attachment/process-attachment-list.component.spec.ts
- lib/process-services/attachment/process-attachment-list.component.ts
- lib/process-services/attachment/task-attachment-list.component.spec.ts
- lib/process-services/comments/comments.component.spec.ts
- lib/process-services/comments/process-comments.component.spec.ts
- lib/process-services/mock/process/process-instances-list.mock.ts
- lib/process-services/process-list/components/process-list.component.ts
- lib/process-services/process-list/models/process-list.model.ts
- lib/process-services/process-list/services/process.service.spec.ts
- lib/process-services/process-list/services/process.service.ts
- lib/process-services/task-list/components/task-list.component.ts
> - [ ] Bugfix
There is no way to paginate the process list result
The Process list …
> [ADF-2123] Process list - Provide a way to paginate the results

- docs/host-settings.component.md
- lib/core/settings/host-settings.component.spec.ts
- lib/core/settings/host-settings.component.ts
> - [ ] Bugfix
* ECM/BPM host URL changes are not emitted.
* Added event emitters for …
> [ADF-2245] Setting Component - Emit an event to detect the changed url

- lib/process-services/comments/comment-list.component.html
> - [x] Bugfix
? is breaking the correct sorting evaluation
fixed the sorting key for …
> [ADF-2215] fixed sorting key for comment list

- lib/core/form/services/widget-visibility.service.spec.ts
- lib/core/form/services/widget-visibility.service.ts
> - [X] Bugfix
Visibility for radio button and dropdown is not evaluated correctly …
> [ADF-2199] fixed check for radio button and dropdown

- docs/content.service.md
- docs/cookie.service.md
- docs/deleted-nodes-api.service.md
- docs/discovery-api.service.md
- docs/document-actions.service.md
- docs/document-list.service.md
- docs/ecm-user.service.md
- lib/config/DocProcessor/tools/tscProps.js
- lib/config/DocProcessor/tools/tscProps.ts
- lib/content-services/document-list/services/document-actions.service.ts
- lib/content-services/document-list/services/document-list.service.ts
- lib/core/services/content.service.ts
- lib/core/services/cookie.service.ts
- lib/core/services/deleted-nodes-api.service.ts
- lib/core/services/discovery-api.service.ts
- lib/core/userinfo/services/ecm-user.service.ts
> - [ ] Bugfix
Added JSDocs for the methods of several services and generated methods lists in the doc files. Fixed a script bug that occurred when a parameter has no type declared. Also added warnings for methods and parameters with no …
> [ADF-1769] Added JSDocs and methods and updated script

- demo-shell/resources/i18n/en.json
> [ADF-2243] added removed keys

- lib/core/form/components/widgets/core/form-field-types.ts
- lib/core/form/components/widgets/core/form-field-validator.spec.ts
- lib/core/form/components/widgets/core/form-field-validator.ts
- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/components/widgets/date-time/date-time.widget.html
- lib/core/form/components/widgets/date-time/date-time.widget.scss
- lib/core/form/components/widgets/date-time/date-time.widget.spec.ts
- lib/core/form/components/widgets/date-time/date-time.widget.ts
- lib/core/form/components/widgets/date/date.widget.spec.ts
- lib/core/form/components/widgets/index.ts
- lib/core/form/form.module.ts
- lib/core/form/services/form-rendering.service.ts
- lib/core/material.module.ts
> [ADF-1925] created datetime widget

- lib/core/i18n/en.json
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.scss
> - [ ] Bugfix
Update Viewer look and feel to be closer to the design spec:
- move …
> [ADF-1418] Viewer enhancements

- lib/core/viewer/components/pdfViewer.component.spec.ts
- lib/core/viewer/components/pdfViewer.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2290 …
> [ADF-2290] PDF Viewer - scroll event dispatch outside view container

- docs/login.component.md
- lib/core/app-config/app-config.service.ts
- lib/core/app-config/schema.json
- lib/core/services/alfresco-api.service.ts
- lib/core/services/authentication.service.ts
> - [x] Bugfix
When the provider is AUTH2 an exception is throw during the login process …
> [ADF-2289] Login with oauth2 provider

- lib/core/form/components/form.component.spec.ts
- lib/core/form/components/form.component.ts
- lib/core/form/components/start-form.component.spec.ts
- lib/core/form/components/start-form.component.ts
- lib/core/form/components/widgets/core/form-field-validator.ts
> [ADF-2225] visibility and validation must be done after form is parsed

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/insights/package.json
- lib/package.json
- lib/process-services/package.json
> - [ ] Bugfix
Update momentjs to the version 2.20.1
> - [ ] Yes
> - [x] No
If this PR contains …
> [ADF-2231] momentjs update

- demo-shell/src/index.html
> - [ ] Bugfix
ripristinate loading spinner demo shell …
> [ADF-2293] add loading demo shell

- lib/core/login/components/login.component.html
- lib/core/login/components/login.component.spec.ts
> - [ ] Bugfix
no autocomplete attribute present
Login autocomplete attribute added to …
> [ADF-2267] Login autocomplete attribute

- demo-shell/src/app/components/search/search-bar.component.html
- docs/search-control.component.md
- lib/content-services/mock/public-api.ts
- lib/content-services/mock/search-control.component.mock.ts
- lib/content-services/search/components/empty-search-result.component.html
- lib/content-services/search/components/empty-search-result.component.ts
- lib/content-services/search/components/search-control.component.html
- lib/content-services/search/components/search-control.component.spec.ts
- lib/content-services/search/components/search-control.component.ts
- lib/content-services/search/search.module.ts
>  [ADF-1876] added custom empty result tag for search result control

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/search/search-extended.component.html
> [ADF-2243] Fixed extended search demo translation

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/task-list.component.md
- lib/process-services/task-list/components/task-list.component.ts
* Used pagination interface
> - [ ] Bugfix
* pagination Interface was not used in taskList component.
**What is the …
> [ADF-2212] Task List - Improve the pagination using the interface

- docs/process-instance-header.component.md
- lib/core/app-config/schema.json
- lib/process-services/process-list/components/process-instance-header.component.spec.ts
- lib/process-services/process-list/components/process-instance-header.component.ts
> - [ ] Bugfix
* No way customise process header properties 
* Properties can be …
> [ADF-2298] Process Header - Make it customizable from config file

- docs/notification.service.md
- docs/page-title.service.md
- docs/people-content.service.md
- docs/people-process.service.md
- docs/rating.service.md
- docs/shared-links-api.service.md
- docs/sites.service.md
- docs/storage.service.md
- lib/content-services/social/services/rating.service.ts
- lib/core/services/notification.service.ts
- lib/core/services/page-title.service.ts
- lib/core/services/people-content.service.ts
- lib/core/services/people-process.service.ts
- lib/core/services/shared-links-api.service.ts
- lib/core/services/sites.service.ts
- lib/core/services/storage.service.ts
> - [ ] Bugfix
Added more JSDocs for services with corresponding method lists in .md files.
> - [ ] Yes
> - [x] No
> [ADF-1769] Added JSDocs for services

- demo-shell/src/app/components/process-service/process-service.component.html
> [ADF-2307] Adding of an id tag for Process services navigation bar

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- docs/README.md
- docs/node-download.directive.md
- lib/content-services/content.module.ts
- lib/content-services/directives/node-download.directive.spec.ts
- lib/content-services/directives/node-download.directive.ts
- lib/content-services/document-list/services/document-actions.service.spec.ts
- lib/content-services/document-list/services/document-actions.service.ts
- lib/content-services/document-list/services/folder-actions.service.ts
- lib/content-services/document-list/services/node-actions.service.ts
- lib/content-services/index.ts
> - [ ] Bugfix
- new Node Download directive contributed by ACA
- integrate download …
> [ADF-2161] download directive

- lib/core/services/authentication.service.ts
- lib/core/services/user-preferences.service.spec.ts
- lib/core/services/user-preferences.service.ts
- lib/process-services/task-list/services/task-filter.service.ts
> - [x] Bugfix
> - [] Feature
https://issues.alfresco.com/jira/browse/ADF-2265
**Does this PR …
> [ADF-2265] fix user preference null value

- demo-shell/src/app/components/process-service/process-service.component.ts
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.ts
> - [ ] Bugfix
* Process Initiator is able to save but not complete the task.
* …
> [ADF-2118]  Process Initiator should be able to complete a task

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/process-list.component.md
- docs/task-list.component.md
- lib/process-services/process-list/components/process-list.component.ts
> - [ ] Bugfix
* When changing the page, the same results are displayed in the process list …
> [ADF-2123] Process Pagination - There is no way to paginate the result

- docs/content-metadata.component.md
> - [ ] Bugfix
Documentation was broken
Fixed …
> [ADF-XZY] Update content-metadata.component.md

- demo-shell/src/app/components/files/files.component.html
- lib/content-services/i18n/en.json
> - [x]The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Bugfix
> - [ …
> [ADF-2260] Action menu translation is missing when right clicking on a file/folder.

- docs/apps-list.component.md
- lib/process-services/app-list/apps-list.component.html
- lib/process-services/app-list/apps-list.component.scss
- lib/process-services/app-list/apps-list.component.spec.ts
- lib/process-services/app-list/apps-list.component.ts
- lib/process-services/app-list/apps-list.module.ts
- lib/process-services/i18n/en.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2297
**Does this PR …
> [ADF-2297] App-list - The component shows "No Apps found" until all the apps are loaded

- lib/core/events/base.event.ts
> - [x] Bugfix
- restore original implementation
- simulate DOM event API by providing …
> [ADF-2301] restore original BaseEvent implementation

- docs/file-draggable.directive.md
- docs/folder-create.directive.md
- docs/folder-edit.directive.md
- docs/highlight.directive.md
- docs/node-delete.directive.md
- docs/node-download.directive.md
- docs/node-favorite.directive.md
- docs/node-permission.directive.md
- docs/node-restore.directive.md
- docs/process-audit.directive.md
- docs/task-audit.directive.md
- docs/upload.directive.md
- lib/config/DocProcessor/tools/tscProps.js
- lib/config/DocProcessor/tools/tscProps.ts
- lib/content-services/directives/node-download.directive.ts
- lib/content-services/folder-directive/folder-create.directive.ts
- lib/content-services/folder-directive/folder-edit.directive.ts
- lib/content-services/upload/directives/file-draggable.directive.ts
- lib/core/directives/highlight.directive.ts
- lib/core/directives/node-delete.directive.ts
- lib/core/directives/node-favorite.directive.ts
- lib/core/directives/node-permission.directive.ts
- lib/core/directives/node-restore.directive.ts
- lib/core/directives/upload.directive.ts
- lib/process-services/process-list/components/process-audit.directive.ts
- lib/process-services/task-list/components/task-audit.directive.ts
> - [ ] Bugfix
Added JSDocs for directives. Also a minor change to the script to make it recognise directives.
> - [ ] Yes
> - [x] No
> [ADF-1769] Added JSDocs for directives

- lib/core/form/components/start-form.component.html
> Adding a data-automation-id for Start Process button in a start event

- demo-shell/package.json
- integration/base_ver_2_app/protractor.conf.js
- lib/content-services/content-node-selector/content-node-selector.module.ts
- lib/content-services/content-node-selector/public-api.ts
- lib/content-services/package.json
- lib/core/core.module.ts
- lib/core/package.json
- lib/core/services/translate-loader.service.ts
- lib/insights/package.json
- lib/package.json
- lib/process-services/package.json
- scripts/test-e2e-bc.sh
> - [ ] Bugfix
- Upgrade to the latest ngx-translate/core
- Remove some of the old …
> [ADF-2316] upgrade ngx-translate

- lib/core/styles/_mixins.scss
- lib/process-services/app-list/apps-list.component.scss
- lib/process-services/styles/_index.scss
> - [x] Bugfix
* App tile in app-list shows unnecessary "…" on Firefox
* Removed the …
> [ADF-2305] Process app tiles on process workspace landing page show "…" in Firefox

- docs/process-list.component.md
- lib/process-services/process-list/components/process-list.component.spec.ts
- lib/process-services/process-list/components/process-list.component.ts
- lib/process-services/task-list/components/task-list.component.spec.ts
> - [ ] Bugfix
* Right now, the static columns (customisable from app.config.json ) and the custom one are mutually …
> [ADF-2326] Process List - Provide a way to support custom html template and static columns at same time.

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/trashcan/trashcan.component.html
- demo-shell/src/app/components/trashcan/trashcan.component.scss
- demo-shell/src/app/components/trashcan/trashcan.component.ts
- docs/node-delete.directive.md
- lib/core/directives/node-delete.directive.spec.ts
- lib/core/directives/node-delete.directive.ts
- lib/core/services/translate-loader.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2340
> - [ ] Yes
> - [x] No
If this …
> [ADF-2340] add trashcan in demo shell and definitely delete in delete directive

- demo-shell/src/app/components/files/files.component.html
- lib/content-services/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/content-node-selector/content-node-selector-panel.component.scss
- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/content-node-selector/content-node-selector.component.html
- lib/content-services/content-node-selector/content-node-selector.component.scss
- lib/content-services/content-node-selector/content-node-selector.component.ts
- lib/content-services/i18n/en.json
- lib/content-services/site-dropdown/sites-dropdown.component.scss
- lib/content-services/site-dropdown/sites-dropdown.component.ts
- lib/core/datatable/components/datatable/datatable.component.scss
- lib/core/services/translate-loader.service.ts
> - [x] Bugfix
- [ADF-2169](https://issues.alfresco.com/jira/browse/ADF-2169) …
> [ADF-2169] Destination Picker fixes

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/files/metadata-dialog-adapter.component.html
- demo-shell/src/app/components/files/metadata-dialog-adapter.component.ts
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/content-metadata/services/basic-properties.service.ts
- lib/content-services/content-metadata/services/content-metadata.service.ts
- lib/core/services/translate-loader.service.ts
> - [x] Bugfix
please see : 
https://issues.alfresco.com/jira/browse/ADF-2311
**Does …
> [ADF-2311] fix metadata components with folders

- lib/core/viewer/components/viewer.component.scss
> [ADF-2355] Viewer - text color opacity

- lib/content-services/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/content-node-selector/name-location-cell/name-location-cell.component.ts
- lib/core/form/components/widgets/date/date.widget.html
- lib/core/form/components/widgets/people/people.widget.html
> - [x] Bugfix
Fix templates that reference missing or non-existing properties.
**Does …
> fixes for AoT

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- docs/datatable.component.md
- docs/document-list.component.md
- lib/content-services/document-list/components/document-list.component.html
- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
…tatable
> - [ ] Bugfix
Improvement after the demo …
> [demo] improvement

- lib/core/pagination/pagination.component.html
- lib/core/pagination/pagination.component.scss
* Added a unique class for pageSize in pagination-component
> - [x] Bugfix
* …
> [ADF-2354] Paginator Component - Add an unique id to the overlay menu

- lib/core/form/components/widgets/upload/upload.widget.ts
- lib/core/i18n/en.json
- lib/process-services/content-widget/attach-file-widget.component.html
- lib/process-services/content-widget/attach-file-widget.component.ts
- lib/process-services/content-widget/attach-file-widget.components.spec.ts
> [ADF-2300] added menu option to attach file widget

- demo-shell/src/app/components/files/files.component.ts
> - [X] Bugfix
Is not possible create new folders
In the document list are present now …
> [ADF-2343] fix document list viewchild pointer in demo shell

- lib/process-services/people/components/people-list/people-list.component.html
- lib/process-services/people/components/people-list/people-list.component.scss
- lib/process-services/people/components/people-search-field/people-search-field.component.ts
- lib/process-services/people/people.module.scss
> [ADF-2346] fixed the people list task style

- lib/process-services/task-list/components/start-task.component.scss
> [ADF-2329] fixed padding for start task window for all themes

- lib/process-services/process-list/services/process-filter.service.spec.ts
- lib/process-services/process-list/services/process.service.spec.ts
- lib/process-services/task-list/services/task-filter.service.spec.ts
- lib/process-services/task-list/services/tasklist.service.spec.ts
> - [ ] Bugfix
Remove test bed from PS in services
> - [ ] Yes
> - [ ] No
If this PR contains a …
> [no-issue] improve test part 1 PS

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/site-dropdown/sites-dropdown.component.html
- lib/content-services/site-dropdown/sites-dropdown.component.spec.ts
- lib/content-services/site-dropdown/sites-dropdown.component.ts
- lib/core/core.module.ts
> - [x] Bugfix
Fix default site Demo shell
> - [ ] Yes
> - [ ] No
If this PR contains a breaking …
> [ADF-2367] [Demo shell] Fix default site 

- docs/form.component.md
> - [ ] Bugfix
* Missing documentation to render json in a form component
* Added …
> [ADF-2261] Missing documentation to render json in a form component

- lib/core/services/translation.service.ts
> - [x] Bugfix
Properly notify TranslatePipe on new languages being loaded.
**Does …
> [ADF-2378] i18n fixes

- lib/content-services/version-manager/version-list.component.ts
- lib/content-services/version-manager/version-manager.component.html
- lib/content-services/version-manager/version-manager.component.ts
> - [X] Bugfix
Refresh list after upload …
> [ADF-2374] upload version refresh list

- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/user-preferences.service.md
- lib/core/services/user-preferences.service.spec.ts
- lib/core/services/user-preferences.service.ts
- lib/process-services/task-list/components/task-list.component.ts
> - [ ] Bugfix
pagination size was just a property for user preference and tasklist component wasn't correctly …
> [ADF-2387] added a stream for pagination size change

- lib/core/viewer/components/pdfViewer-thumbnails.component.scss
- lib/core/viewer/components/pdfViewer-thumbnails.component.spec.ts
- lib/core/viewer/components/pdfViewer-thumbnails.component.ts
- lib/core/viewer/components/pdfViewer.component.html
- lib/core/viewer/components/pdfViewer.component.scss
- lib/core/viewer/components/pdfViewer.component.spec.ts
- lib/core/viewer/components/pdfViewer.component.ts
- lib/core/viewer/components/viewer.component.scss
> [ADF-2388, ADF-2375] PDF Viewer - show buffer thumbnail on pagechange

- lib/core/viewer/components/viewer.component.html
> [ADF-2429] Viewer - media file full screen

- Dockerfile
> - [ ] Bugfix
Reduce resulting docker image size from 51 mb to 15 mb
**Does this PR …
> [ADF-2424] reduce docker image size

- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
> - [x] Bugfix
Please see https://issues.alfresco.com/jira/browse/ADF-2406
Fixed …
> [ADF-2406] [Document Picker] Unnecessary extra request is made on Load more click  

- lib/core/viewer/components/imgViewer.component.scss
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2337
Fixed
**Does this …
> [ADF-2337] Fix viewer dark theme issues

- docs/process-list.component.md
- lib/process-services/process-list/components/process-list.component.html
- lib/process-services/process-list/components/process-list.component.ts
> - [ ] Bugfix
* MultiSelect property of data-table was not exposed by process-list
* …
> [ADF-2394] Process List Component - Should expose the mutiSelect property

- lib/process-services/task-list/components/task-list.component.ts
> - [ ] Bugfix
* The tasklist component follows old pagination strategy. …
> [ADF-2412] Task List - refactoring.

- demo-shell/src/app/components/tag/tag.component.ts
- lib/config/export-check/export-2.2.0.json
- lib/config/export-check/export-check-config.json
- lib/package.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2417 …
> [ADF-2417] remove tag id as default value from demo shell

- demo-shell/src/app/app.component.scss
- demo-shell/src/app/components/files/files.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1787 and …
> [ADF-1787] Fix mobile styles

- lib/core/viewer/components/pdfViewer.component.scss
> - [x] Bugfix
See comments of https://issues.alfresco.com/jira/browse/ADF-2337
Fixed …
> [ADF-2337] Fix dark theme for viewing pdf files also.

- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.spec.ts
- lib/process-services/task-list/components/task-details.component.ts
> - [x] Bugfix
* Complete button is visible to involved users for tasks without form. …
> [ADF-2320] Complete button is visible on an involved task

- docs/process.service.md
- lib/process-services/process-list/services/process.service.ts
> - [ ] Bugfix
A user reported on the ADF Technical Questions chat that process.service.md documented a return type incorrectly. The file is actually not in the form expected by the …
> [ADF-2458] Updated doc to standard format

- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
> - [x] Bugfix
please see https://issues.alfresco.com/jira/browse/ADF-2421
fixed …
> [ADF-2421] Unable to copy / move a file from Recent or Favorites when user has only granular permissions on the file

- demo-shell/.angular-cli.json
- demo-shell/e2e/app.e2e-spec.ts
- demo-shell/e2e/app.po.ts
- demo-shell/package.json
- demo-shell/src/app/app.component.spec.ts
- demo-shell/src/polyfills.ts
- demo-shell/src/tsconfig.spec.json
- demo-shell/tslint.json
- lib/config/karma.conf-all.js
- lib/content-services/search/components/search-trigger.directive.ts
- lib/content-services/search/components/search.component.spec.ts
- lib/content-services/version-manager/version-manager.component.ts
- lib/content-services/version-manager/version-upload.component.ts
- lib/core/datatable/components/datatable/data-row-action.event.ts
- lib/core/models/product-version.model.ts
- lib/core/viewer/components/pdfViewer.component.spec.ts
- lib/core/viewer/components/pdfViewer.component.ts
- lib/core/viewer/components/txtViewer.component.spec.ts
- lib/core/viewer/components/viewer.component.spec.ts
- lib/process-services/task-list/models/filter.model.ts
- scripts/README.md
- scripts/start.sh
- tslint.json
> - [] Bugfix
fix e2e and test in demo shell
and https://issues.alfresco.com/jira/browse/ADF-2461 …
> [ADF-2240] fix e2e and test in demo shell 

- docs/document-list.component.md
- docs/viewer.component.md
> - [ ] Bugfix
Reviewed component doc files and added "Last reviewed" date field.
> - [ ] Yes
> - [x] No
> [ADF-2451] Reviewed docs for components

- demo-shell/src/app/components/file-view/file-view.component.html
- demo-shell/src/app/components/file-view/file-view.component.ts
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.html
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
- demo-shell/src/app/material.module.ts
- docs/upload-button.component.md
- lib/content-services/i18n/en.json
- lib/content-services/upload/components/upload-button.component.ts
- lib/content-services/upload/components/upload-version-button.component.ts
- lib/content-services/upload/public-api.ts
- lib/content-services/upload/upload.module.ts
- lib/content-services/version-manager/version-upload.component.html
- lib/core/models/file.model.ts
- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2368
Fixed
**Does this …
> [ADF-2368] Version manager update

- lib/process-services/comments/comment-list.component.spec.ts
> - [ ] Bugfix
appveyor cs test fix …
> [no-issue] appveyor CS test fix

- lib/content-services/tag/tag-actions.component.html
> Add data-automation-id to an error message displayed on the Tag Page.

- docs/user-preferences.service.md
> [ADF-2443] fixed documentation

- demo-shell/src/app/components/search/search-config-test.service.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/content-node-selector/content-node-selector.service.spec.ts
- lib/content-services/content-node-selector/content-node-selector.service.ts
- lib/content-services/search/components/search.component.ts
- lib/core/interface/search-configuration.interface.ts
- lib/core/services/search-configuration.service.ts
- lib/core/services/search.service.ts
> - [x] Bugfix
After the change in the definition of the js-api those types in the code are not correct anymore …
> [ADF-No-issue-number] search problem type fix

- docs/authentication.service.md
- docs/content-node-dialog.service.md
- docs/search-control.component.md
- docs/sites-dropdown.component.md
- docs/start-process.component.md
- docs/task-attachment-list.component.md
- docs/task-details.component.md
- lib/content-services/site-dropdown/sites-dropdown.component.ts
- lib/core/services/authentication.service.ts
> - [ ] Bugfix
Reviewed docs for some more components.
> - [ ] Yes
> - [x] No
> [ADF-2451] Reviewed component docs

- docs/log.service.md
- lib/core/services/log.service.spec.ts
- lib/core/services/log.service.ts
> - [ ] Bugfix
to allow third pat integrations I added this message bus. Meanwhile I was trying to write an article to integrate our log service with other …
> [ADF-2477] message bus in log service

- lib/core/viewer/components/mediaPlayer.component.scss
> - [ ] Bugfix
On small devices the video is overflowing the screen borders
The video …
> [ADF-1810] fixed visualisation for small devices

- lib/content-services/tag/tag-actions.component.ts
- lib/content-services/tag/tag-list.component.spec.ts
- lib/content-services/tag/tag-list.component.ts
- lib/content-services/tag/tag-node-list.component.ts
> - [X] Bugfix
add check if nodeid is present in tag components
> - [ ] Yes
> - [X] No
If this …
> [ADF-2468] add check if nodeid is present in tag components

- demo-shell/src/app/components/theme-picker/theme-picker.html
> Add data-automation-id for theming

- CODE_OF_CONDUCT.md
> - [ ] Bugfix
Code of Conduct document …
> [ADF-2491] CODE_OF_CONDUCT.md

- lib/core/models/comment-process.model.ts
- lib/process-services/comments/comment-list.component.html
- lib/process-services/comments/comment-list.component.scss
- lib/process-services/comments/comment-list.component.spec.ts
- lib/process-services/comments/comment-list.component.ts
> - [ ] Bugfix
Comment list was using datatable to show the comments
We removed the …
> [ADF-2353] replaced datatable with mat-list

- demo-shell/src/app/components/files/files.component.ts
> - [X] Bugfix
Document list is not correctly refreshed in the standard paginated mode …
> [ADF-2480] document list reload should be always performed

- lib/process-services/mock/task/task-details.mock.ts
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.spec.ts
- lib/process-services/task-list/components/task-details.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2492
**Does this PR …
> [ADF-2492] Task without a form is not displayed when the assignment is preselected on APS

- docs/process-services/task-standalone.component.md
- lib/process-services/i18n/en.json
- lib/process-services/styles/_index.scss
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.spec.ts
- lib/process-services/task-list/components/task-standalone.component.html
- lib/process-services/task-list/components/task-standalone.component.scss
- lib/process-services/task-list/components/task-standalone.component.spec.ts
- lib/process-services/task-list/components/task-standalone.component.ts
- lib/process-services/task-list/public-api.ts
- lib/process-services/task-list/task-list.module.ts
> - [ ] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-2452
* Add a new …
> [ADF-2452] Task Standalone component

- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.html
> [ADF-2535] Content Metadata - group title translation

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.scss
- demo-shell/src/app/components/files/files.component.ts
- docs/content-services/file-uploading-dialog.component.md
- docs/content-services/folder-create.directive.md
- docs/content-services/folder-edit.directive.md
- docs/content-services/upload-button.component.md
- docs/content-services/upload-drag-area.component.md
- lib/content-services/dialogs/folder.dialog.spec.ts
- lib/content-services/dialogs/folder.dialog.ts
- lib/content-services/folder-directive/folder-create.directive.spec.ts
- lib/content-services/folder-directive/folder-create.directive.ts
- lib/content-services/folder-directive/folder-edit.directive.spec.ts
- lib/content-services/folder-directive/folder-edit.directive.ts
- lib/content-services/upload/components/file-uploading-dialog.component.html
- lib/content-services/upload/components/file-uploading-dialog.component.ts
- lib/content-services/upload/components/file-uploading-list.component.spec.ts
- lib/content-services/upload/components/file-uploading-list.component.ts
- lib/content-services/upload/components/upload-drag-area.component.spec.ts
- lib/content-services/upload/components/upload-drag-area.component.ts
- lib/core/directives/node-delete.directive.spec.ts
- lib/core/directives/node-delete.directive.ts
- lib/core/directives/node-restore.directive.spec.ts
- lib/core/directives/node-restore.directive.ts
- lib/process-services/app-list/select-apps-dialog-component.ts
> -  [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Bugfix
notify service refactoring 
get translate eliminitation in favor of instant
add error event where necessary
fix config problem during test
When an …
> [ASD-2483] Validate folder name on change

- demo-shell/src/app/components/process-service/process-attachments.component.ts
- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- demo-shell/src/app/components/process-service/task-attachments.component.ts
- lib/content-services/content-metadata/content-metadata.module.ts
- lib/content-services/document-list/components/document-list.component.html
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/search/search.module.ts
- lib/core/core.module.ts
- lib/core/services/upload.service.ts
- lib/process-services/attachment/create-process-attachment.component.spec.ts
- lib/process-services/task-list/services/process-upload.service.ts
- lib/process-services/task-list/services/task-upload.service.ts
> - [x] Bugfix
Update code to provide AoT compatibility …
> [ADF-2531] support for AoT and production builds

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.scss
- demo-shell/src/custom-style-dev.scss
- demo-shell/src/custom-style.scss
> - [X] Bugfix
Info drawer for Versions is not properly displayed
Info drawer for …
> [ADF-2018] Hide details button when it's displayed on a smartphone

- demo-shell/src/app/components/files/custom-sources.component.html
- demo-shell/src/app/components/files/custom-sources.component.ts
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/form/form-list.component.html
- demo-shell/src/app/components/form/form-list.component.ts
- demo-shell/src/app/components/process-service/process-attachments.component.ts
- demo-shell/src/app/components/process-service/task-attachments.component.ts
- demo-shell/src/app/components/trashcan/trashcan.component.ts
- lib/content-services/breadcrumb/dropdown-breadcrumb.component.html
- lib/content-services/breadcrumb/dropdown-breadcrumb.component.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/search/components/search-control.component.html
- lib/content-services/search/components/search-control.component.ts
- lib/content-services/upload/components/file-uploading-dialog.component.ts
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
- lib/process-services/people/components/people-list/people-list.component.html
- lib/process-services/people/components/people-list/people-list.component.ts
- lib/process-services/people/components/people-selector/people-selector.component.html
- lib/process-services/people/components/people-selector/people-selector.component.ts
- lib/process-services/people/components/people/people.component.html
- lib/process-services/people/components/people/people.component.ts
- lib/process-services/process-list/components/process-instance-details.component.html
- lib/process-services/process-list/components/process-instance-details.component.ts
- lib/process-services/process-list/components/start-process.component.html
- lib/process-services/process-list/components/start-process.component.ts
> - [x] Bugfix
I removed the Removed the viewchild use with the component reference in order to fix some issue in the dist version …
> [no-issue] remove viewChildren use

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/insights/package.json
- lib/package.json
- lib/process-services/package.json
Update ADF packages version 2.3.0-beta5
> Update ADF packages version 2.3.0-beta5

- integration/base_ver_2_app/src/app/app.module.ts
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/content-services/content-metadata/content-metadata.module.ts
- lib/content-services/content-metadata/public-api.ts
- lib/content-services/content.module.ts
- lib/content-services/dialogs/dialog.module.ts
- lib/content-services/site-dropdown/sites-dropdown.module.ts
- lib/content-services/social/like.component.ts
- lib/content-services/social/rating.component.ts
- lib/content-services/social/social.module.ts
- lib/process-services/app-list/apps-list.module.ts
- lib/process-services/process-list/process-list.module.ts
- lib/process-services/task-list/components/task-details.component.ts
> [ADF-2531] Fixes for production mode

- demo-shell/src/app/components/app-layout/app-layout.component.html
> Adding data-automation-id

- demo-shell/src/app/app.component.html
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/components/log/log.component.css
- demo-shell/src/app/components/log/log.component.html
- demo-shell/src/app/components/log/log.component.ts
- lib/core/services/log.service.ts
> - [ ] Bugfix
I added in the demo shell a new log component that can be opened using add CTRL + L shortcut. …
> [ADF-2477] add new log component in demo shell

- demo-shell/src/app/components/app-layout/app-layout.component.html
- demo-shell/src/app/components/files/files.component.scss
> - [x] Bugfix
Assorted Files component in demo shell, in different breakpoints. …
> [ADF-EASTER_EGG] Fix assorted styles for files in different breakpoints

- lib/core/viewer/components/viewer.component.html
> - [x] Bugfix
Use system tooltips for top Viewer menu to reflect the floating menus …
> [ADF-2592] Different types of tooltips appear in the viewer

- demo-shell/src/app/components/search/search-result.component.ts
- lib/content-services/search/search-query-builder.service.spec.ts
- lib/content-services/search/search-query-builder.service.ts
> - [x] Bugfix
Fix search filter not using Pagination settings with QueryBody
**Does …
> [ADF-2595] use pagination settings with search filter

- demo-shell/src/app/components/search/search-result.component.ts
> - [x] Bugfix
Update demo shell to fix the issue with initial pagination settings …
> [ADF-2595] fix demo shell pagination for search filter

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.html
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
> - [ ] Bugfix
Updated the demo-shell to have a toggle for the user to be able to …
> [ADF-2561] add showComments toggle on demo-shell

- demo-shell/src/app.config.json
- lib/core/services/alfresco-api.service.ts
> - [ ] Bugfix
There is no way to change the contextBPMRoot
you can customise you …
> [ADF-2609] Provide a way to change the contextBpmRoot from the app.config file

- demo-shell/src/app/components/files/files.component.html
- docs/README.md
- docs/content-services/README.md
- docs/content-services/content-node-dialog.service.md
- docs/content-services/node-lock.directive.md
- lib/content-services/content-node-selector/content-node-dialog.service.spec.ts
- lib/content-services/content-node-selector/content-node-dialog.service.ts
- lib/content-services/dialogs/dialog.module.ts
- lib/content-services/dialogs/node-lock.dialog.html
- lib/content-services/dialogs/node-lock.dialog.spec.ts
- lib/content-services/dialogs/node-lock.dialog.ts
- lib/content-services/dialogs/public-api.ts
- lib/content-services/directives/content-directive.module.ts
- lib/content-services/directives/node-lock.directive.spec.ts
- lib/content-services/directives/node-lock.directive.ts
- lib/content-services/directives/node-share.directive.spec.ts
- lib/content-services/document-list/components/content-action/content-action.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/document-list/services/document-actions.service.spec.ts
- lib/content-services/document-list/services/document-actions.service.ts
- lib/content-services/document-list/services/node-actions.service.service.spec.ts
- lib/content-services/document-list/services/node-actions.service.ts
- lib/content-services/material.module.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
- lib/core/i18n/en.json
- lib/core/models/permissions.enum.ts
- lib/core/services/content.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2540
Lock & unlock nodes …
> [ADF-2540] Lock node feature

- lib/core/app-config/schema.json
> - [ ] Bugfix
Add the contextRootBPM and contextRootECM to the schema validator …
> [ADF-2609] Add the contextRootBPM and contextRootECM to the schema validator

- docs/core/card-view.component.md
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.scss
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/card-view/interfaces/card-view-item-properties.interface.ts
- lib/core/card-view/interfaces/card-view-item.interface.ts
- lib/core/card-view/models/card-view-baseitem.model.ts
- lib/process-services/task-list/components/task-header.component.spec.ts
- lib/process-services/task-list/components/task-header.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2614
**Does this PR …
> [ADF-2614] Edit icon misses in Info-drawer Assignee

- demo-shell/resources/i18n/en.json
- demo-shell/src/app.config.json
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.html
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
- docs/content-services/version-list.component.md
- lib/content-services/content.module.ts
- lib/content-services/dialogs/confirm.dialog.ts
- lib/content-services/dialogs/dialog.module.ts
- lib/content-services/dialogs/public-api.ts
- lib/content-services/i18n/en.json
- lib/content-services/version-manager/version-list.component.html
- lib/content-services/version-manager/version-list.component.spec.ts
- lib/content-services/version-manager/version-list.component.ts
- lib/content-services/version-manager/version-manager.component.html
- lib/content-services/version-manager/version-manager.component.ts
- lib/content-services/version-manager/version-upload.component.html
- lib/core/app-config/schema.json
> - [ ] Bugfix
ADF-2567: Delete a version
ADF-2632: Version Manager should support …
> [ADF-2567] delete a version

- lib/core/sidenav-layout/components/layout-container/layout-container.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-2636
Fixed
**Does this …
> [ADF-2636] Fix Safari's thrown error

- lib/core/form/components/widgets/core/form-field-validator.spec.ts
- lib/core/form/components/widgets/core/form-field-validator.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2501
**Does this PR …
> [ADF-2501]Checkbox form Widget - TASK "Complete" button not grayed out when widget set as required

- docs/core/alfresco-api.service.md
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/core/services/alfresco-api.service.spec.ts
- lib/core/services/alfresco-api.service.ts
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
Update Viewer upon metadata changes, in case the updated node is the …
> [ADF-2625] updating viewer on node editing

- lib/process-services/package.json
> - [x] Bugfix
Is not importing the content service
Is importing the content service …
> [ADF-2660] Process Service Lib - Fix wrong dependency

- demo-shell/src/app/components/files/files.component.html
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2455
Show default icon when …
> [ADF-2455] Fallback thumbnail fix

- lib/content-services/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/services/document-list.service.spec.ts
- lib/content-services/document-list/services/document-list.service.ts
- lib/content-services/folder-directive/folder-edit.directive.spec.ts
- lib/core/pagination/infinite-pagination.component.html
- lib/core/pagination/infinite-pagination.component.ts
- lib/core/pagination/paginated-component.interface.ts
- lib/core/services/notification.service.spec.ts
- lib/core/viewer/components/viewer.component.spec.ts
> - [x] Bugfix
Some test around the codebase where skipped I re-enabled them
**Does …
> [NO-ISSUE] RE enable failing test

- lib/core/form/components/widgets/amount/amount.widget.scss
- lib/core/form/components/widgets/container/container.widget.scss
- lib/core/form/components/widgets/text/text.widget.spec.ts
- lib/core/form/components/widgets/text/text.widget.ts
> - [x] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-2607
* Removed css to …
> [ADF-2607] Task Form - Number Widget placeholder no longer displayed

- demo-shell/src/app.config.json
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/services/debug-app-config.service.ts
- docs/content-services/version-list.component.md
- docs/content-services/version-manager.component.md
- lib/content-services/i18n/en.json
- lib/content-services/version-manager/version-list.component.html
- lib/content-services/version-manager/version-list.component.spec.ts
- lib/content-services/version-manager/version-list.component.ts
- lib/content-services/version-manager/version-manager.component.html
- lib/content-services/version-manager/version-manager.component.spec.ts
- lib/content-services/version-manager/version-manager.component.ts
- lib/content-services/version-manager/version-upload.component.html
- lib/content-services/version-manager/version-upload.component.ts
- lib/core/app-config/schema.json
> - [x] Bugfix
- fix the demo shell breaking default values of the app config service …
> [ADF-2672] version manager fixes

- lib/config/DocProcessor/templates/tutIndex.combyne
- lib/config/DocProcessor/tools/tutorialIndex.js
- lib/config/DocProcessor/tools/tutorialIndex.ts
> - [ ] Bugfix
Added a indexing script in preparation for a series of tutorials that Francesco is currently writing.
> - [ ] Yes
> - [x] No
> [ADF-2679] Added tutorial index tool

- demo-shell/src/app/components/files/files.component.ts
> - [X] Bugfix
no snack bar for deleted items
snack bar for deleted items
**Does this …
> [ADF-2687] enabled snack bar for delete confirmation

- lib/content-services/site-dropdown/sites-dropdown.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2681
Case sensitive bug fix …
> [ADF-2681] Sites list dropdown fix

- docs/README.md
- docs/content-services/README.md
- docs/content-services/custom-resources.service.md
- docs/core/README.md
- docs/core/comment-content.service.md
- docs/process-services/README.md
- docs/versionIndex.md
> - [ ] Bugfix
Added docs for two of the new services and updated the indexes.
> - [ ] Yes
> - [x] No
> [ADF-2670] Added new docs for 2.3 features

- docs/README.md
- docs/content-services/README.md
- docs/core/viewer.component.md
- docs/process-services/start-process.component.md
- docs/undocStoplist.json
- lib/config/DocProcessor/reviewChecker.js
- lib/config/DocProcessor/reviewChecker.ts
> - [ ] Bugfix
Updated doc indexes to remove new search subcomponents that are covered in the main search filter page. Also clarified the usage of the sharedLinkId property in the Viewer component. …
> [ADF-2670] Updated doc indexes for 2.3

- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/breadcrumb/breadcrumb.component.ts
- lib/content-services/breadcrumb/navigable-component.interface.ts
- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2682
https://issues.alfresco.com/jira/browse/ADF-2685 …
> [ADF-2682] Fix pagination, bradcrumb, general reload scenarios

- docs/README.md
- docs/tutorials/README.md
- docs/tutorials/new-component.md
- docs/tutorials/new-view.md
- docs/tutorials/preparing-environment.md
- docs/user-guide/summary.json
- lib/config/DocProcessor/doctool.config.json
- lib/config/DocProcessor/templates/tutIndex.combyne
- lib/config/DocProcessor/tools/index.js
- lib/config/DocProcessor/tools/tutorialIndex.js
- lib/config/DocProcessor/tools/tutorialIndex.ts
> - [ ] Bugfix
Added the first of Francesco's tutorials along with a few minor changes to the scripts and templates.
> - [ ] Yes
> - [x] No
> [ADF-2679] Added first tutorials

- demo-shell/src/app/components/files/files.component.ts
- docs/core/app-config.service.md
- lib/core/app-config/app-config.service.spec.ts
- lib/core/app-config/app-config.service.ts
- lib/core/services/user-preferences.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2676
Pagination bug fixed in …
> [ADF-2676] Demo shell pagination bug fix

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/insights/package.json
- lib/package.json
- lib/process-services/package.json
Update ADF packages version 2.3.0-beta10
> Update ADF packages version 2.3.0-beta10

- docs/content-services/content-action.component.md
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2695
**Does this PR …
> [ADF-2695] DocumentList content action documentation

- docs/README.md
- docs/content-services/README.md
- docs/content-services/content-metadata.component.md
- docs/content-services/content-node-selector-panel.component.md
- docs/content-services/document-list.component.md
- docs/content-services/document-list.service.md
- docs/content-services/search-filter.component.md
- docs/content-services/search-query-builder.service.md
- docs/content-services/search.component.md
- docs/content-services/upload-drag-area.component.md
- docs/content-services/version-manager.component.md
- docs/core/README.md
- docs/core/alfresco-api.service.md
- docs/core/content.service.md
- docs/core/datatable.component.md
- docs/core/pagination.component.md
- docs/core/user-preferences.service.md
- docs/process-services/process-list.component.md
- docs/process-services/task-details.component.md
- docs/process-services/task-list.component.md
- docs/versionIndex.md
> - [ ] Bugfix
Checked and updated docs for 2.3. Most changes were minor. The largest change is probably moving the Search Query Builder service into its own page (was previously a section in the Search Filter page).
**Does this PR …
> [ADF- 2670] Checked and updated docs for 2.3

- lib/core/core.module.ts
- lib/process-services/task-list/task-list.module.ts
> - [ ] Bugfix
data pipe is provided only from the process module
data pipe provided …
> Dev mromano add data pipe

- demo-shell/src/app/components/app-layout/app-layout.component.html
- demo-shell/src/app/components/app-layout/app-layout.component.scss
- lib/core/sidenav-layout/components/layout-container/layout-container.component.html
- lib/core/sidenav-layout/components/layout-container/layout-container.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2711
**Does this PR …
> [ADF-2711] fix cdk scrollable sidenav

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/insights/package.json
- lib/package.json
- lib/process-services/package.json
> - [ ] Bugfix
package.json update version …
> bump 2.3.0 package.json

- docs/content-services/folder-create.directive.md
- docs/content-services/folder-edit.directive.md
- docs/core/sidenav-layout.component.md
- lib/content-services/dialogs/folder.dialog.html
- lib/content-services/dialogs/folder.dialog.spec.ts
- lib/content-services/dialogs/folder.dialog.ts
- lib/content-services/folder-directive/folder-create.directive.spec.ts
- lib/content-services/folder-directive/folder-create.directive.ts
- lib/content-services/folder-directive/folder-edit.directive.spec.ts
- lib/content-services/folder-directive/folder-edit.directive.ts
- lib/core/sidenav-layout/components/sidenav-layout/sidenav-layout.component.spec.ts
- lib/core/sidenav-layout/components/sidenav-layout/sidenav-layout.component.ts
> - [ ] Bugfix
Features needed for APM, incremental changes
Implemented
**Does this PR …
> [APM-7] Feature enhancement for the create and edit folder directive

- .dockerignore
> - [ ] Bugfix
Docker ignore file …
> [no-issue] Docker ignore

- docs/content-services/folder-create.directive.md
- lib/content-services/dialogs/folder.dialog.spec.ts
- lib/content-services/dialogs/folder.dialog.ts
- lib/content-services/folder-directive/folder-create.directive.spec.ts
- lib/content-services/folder-directive/folder-create.directive.ts
- lib/content-services/permission-manager/components/permission-list/no-permission.component.ts
- lib/content-services/permission-manager/permission-manager.module.ts
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/APM-25
Implemented
**Does …
> [AMA-25] Create Folder directive enhancement: custom nodeType

- docs/content-services/version-list.component.md
> - [x] Bugfix
Fix error in the example code. …
> Fix error in the documentation example

- demo-shell/src/app/components/process-service/process-service.component.html
- lib/core/collapsable/accordion-group.component.html
- lib/core/collapsable/accordion-group.component.scss
- lib/core/collapsable/accordion-group.component.spec.ts
- lib/core/collapsable/accordion-group.component.ts
- lib/core/collapsable/accordion.component.spec.ts
- lib/core/collapsable/accordion.component.ts
- lib/core/material.module.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2709
**Does this PR …
> [ADF-2709] Replace the ADF accordion with material accordion

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- docs/content-services/document-list.component.md
- docs/core/data-column.component.md
- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/version-manager/version-list.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [ ] Bugfix
- support `*ngIf` for DataColumn in DT/DL components
- documentation …
> [ADF-2589] conditional visibility for DL/DT components

- lib/core/form/services/widget-visibility.service.spec.ts
- lib/core/form/services/widget-visibility.service.ts
> - [x] Bugfix
The field is not visible even though the visibility condition is true …
> [ADF-2825] ADF Form - Fix form visibility related to the process variables

- lib/content-services/directives/node-download.directive.spec.ts
- lib/content-services/directives/node-download.directive.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2766
**Does this PR …
> [ADF-2766] Download Node Directive does not work with Shared Links

- lib/core/form/services/widget-visibility.service.spec.ts
- lib/core/form/services/widget-visibility.service.ts
> - [x] Bugfix
Unit test were failing
fixed …
> [ADF-2825] Form Visibility - fix unit test related to the visibility 

- lib/core/sidebar/sidebar-action-menu.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2771
**Does this PR …
> [ADF-2771] Sidebar action menu component - UX review

- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- lib/process-services/task-list/components/task-filters.component.spec.ts
- lib/process-services/task-list/components/task-filters.component.ts
> - [ ] Bugfix
URL cannot support filter id
https://issues.alfresco.com/jira/browse/ADF-2788 …
> [ADF-2788] Filter task url involved

- docs/tutorials/README.md
- docs/tutorials/creating-the-app-using-yeoman.md
- docs/tutorials/customising-login.md
- docs/tutorials/new-component.md
- docs/tutorials/new-view.md
- docs/tutorials/preparing-environment.md
- docs/tutorials/using-components.md
- docs/tutorials/working-with-data-table.md
> - [ ] Bugfix
Reviewed text of the new tutorials.
> - [ ] Yes
> - [x] No
> [ADF-2679] Reviewed tutorials

- lib/content-services/breadcrumb/breadcrumb.component.scss
- lib/core/viewer/components/viewer.component.scss
> - [x] Bugfix
- [ADF-2900] fix for the Firefox and Viewer scrolling
- [ADF-2901] …
> style fixes

- demo-shell/src/app/components/files/custom-sources.component.html
- demo-shell/src/app/components/files/custom-sources.component.ts
- lib/content-services/document-list/services/custom-resources.service.ts
> - [ ] Bugfix
Extend demo shell "custom sources" page with "download" button to be …
> [ADF-2766] download button for custom sources

- docs/core/login.component.md
- docs/core/notification.service.md
- docs/core/page-title.service.md
- docs/core/pagination.component.md
- docs/core/search-api.service.md
- docs/core/search-configuration.service.md
- docs/core/shared-links-api.service.md
- docs/core/sidebar-action-menu.component.md
- docs/core/sites.service.md
- docs/core/start-form.component.md
- docs/core/storage.service.md
- docs/core/text-mask.component.md
- docs/core/thumbnail.service.md
- docs/core/toolbar.component.md
- docs/core/translation.service.md
- docs/core/user-info.component.md
- docs/core/user-preferences.service.md
> - [ ] Bugfix
Added class members headings to core docs.
> - [ ] Yes
> - [x] No
> [ADF-2847] Added class members heading to core docs

- docs/insights/analytics-generator.component.md
- docs/insights/analytics-report-list.component.md
- docs/insights/analytics.component.md
- docs/insights/diagram.component.md
- docs/process-services/apps-list.component.md
- docs/process-services/checklist.component.md
- docs/process-services/create-process-attachment.component.md
- docs/process-services/create-task-attachment.component.md
- docs/process-services/people-list.component.md
- docs/process-services/people-search.component.md
- docs/process-services/people.component.md
- docs/process-services/process-attachment-list.component.md
- docs/process-services/process-comments.component.md
- docs/process-services/process-filter.service.md
- docs/process-services/process-filters.component.md
- docs/process-services/process-instance-details.component.md
- docs/process-services/process-instance-header.component.md
- docs/process-services/process-instance-tasks.component.md
- docs/process-services/process-list.component.md
- docs/process-services/process.service.md
- docs/process-services/start-process.component.md
- docs/process-services/start-task.component.md
- docs/process-services/task-attachment-list.component.md
- docs/process-services/task-details.component.md
- docs/process-services/task-filter.service.md
- docs/process-services/task-filters.component.md
- docs/process-services/task-header.component.md
- docs/process-services/task-list.component.md
- docs/process-services/task-standalone.component.md
- docs/process-services/tasklist.service.md
> - [ ] Bugfix
Added class members heading to the remaining doc files.
> - [ ] Yes
> - [x] No
> [ADF-2847] Added class members headings to process and insights docs

- lib/config/DocProcessor/docProcessor.js
- lib/config/DocProcessor/tools/tsInfo.js
- lib/config/DocProcessor/tools/tsInfo.ts
> - [ ] Bugfix
Improved doc tool error handling. Now shows errors grouped by the name of the file where they occur.
> - [ ] Yes
> - [x] No
> [ADF-2911] Improved error message handling in doc tools

- lib/core/sidenav-layout/components/layout-container/layout-container.component.scss
- lib/core/styles/_index.scss
> - [x] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-2772
* Added border-right …
> [ADF-2772] Sidenav Layout - UX review

- docs/content-services/content-metadata.component.md
- docs/content-services/content-node-dialog.service.md
- docs/content-services/custom-resources.service.md
- docs/content-services/folder-create.directive.md
- docs/content-services/folder-edit.directive.md
- docs/content-services/node-lock.directive.md
- docs/content-services/node-permission.service.md
- docs/content-services/permission-list.component.md
- lib/config/DocProcessor/docProcessor.js
- lib/config/DocProcessor/tools/tsInfo.js
- lib/config/DocProcessor/tools/tsInfo.ts
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/content-services/content-node-selector/content-node-dialog.service.ts
- lib/content-services/directives/node-lock.directive.ts
- lib/content-services/document-list/services/custom-resources.service.ts
- lib/content-services/folder-directive/folder-create.directive.ts
- lib/content-services/folder-directive/folder-edit.directive.ts
- lib/content-services/index.ts
- lib/content-services/permission-manager/components/add-permission/add-permission-dialog.component.ts
- lib/content-services/permission-manager/components/permission-list/permission-list.component.ts
- lib/content-services/permission-manager/permission-manager.module.ts
- lib/content-services/permission-manager/services/node-permission.service.ts
- lib/core/sidenav-layout/components/layout-container/layout-container.component.scss
- lib/core/styles/_index.scss
> - [ ] Bugfix
Updated JSDocs for content services files. 
> - [ ] Yes
> - [x] No
> [ADF-2905] Updated JSDocs for content services

- docs/core/app-config.service.md
- docs/core/bpm-user.service.md
- docs/core/card-view.component.md
- docs/core/comment-content.service.md
- docs/core/content.service.md
- docs/core/context-menu.directive.md
- docs/core/favorites-api.service.md
- docs/core/form-rendering.service.md
- docs/core/form.service.md
- lib/core/app-config/app-config.service.ts
- lib/core/card-view/components/card-view/card-view.component.ts
- lib/core/context-menu/context-menu.directive.ts
- lib/core/form/services/form.service.ts
- lib/core/services/comment-content.service.ts
- lib/core/services/content.service.ts
- lib/core/services/dynamic-component-mapper.service.ts
- lib/core/services/favorites-api.service.ts
- lib/core/userinfo/services/bpm-user.service.ts
> - [ ] Bugfix
Updated docs for core components.
> - [ ] Yes
> - [x] No
> [ADF-2905] Updated JSDocs for core

- .angular-cli.json
- demo-shell/src/app.config.json
- docs/content-services/search-filter.component.md
- lib/content-services/i18n/en.json
- lib/content-services/search/components/search-check-list/search-check-list.component.html
- lib/content-services/search/components/search-check-list/search-check-list.component.spec.ts
- lib/content-services/search/components/search-check-list/search-check-list.component.ts
- lib/content-services/search/components/search-chip-list/search-chip-list.component.html
- lib/content-services/search/components/search-date-range/search-date-range.component.html
- lib/content-services/search/components/search-date-range/search-date-range.component.scss
- lib/content-services/search/components/search-filter/models/response-facet-query-list.model.ts
- lib/content-services/search/components/search-filter/models/search-filter-list.model.ts
- lib/content-services/search/components/search-filter/search-filter.component.html
- lib/content-services/search/components/search-filter/search-filter.component.scss
- lib/content-services/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
- lib/content-services/search/components/search-number-range/search-number-range.component.html
- lib/content-services/search/components/search-number-range/search-number-range.component.scss
- lib/content-services/search/components/search-radio/search-radio.component.html
- lib/content-services/search/components/search-radio/search-radio.component.ts
- lib/content-services/search/components/search-slider/search-slider.component.html
- lib/content-services/search/response-facet-field.interface.ts
- lib/core/app-config/schema.json
- package-lock.json
- package.json
> - [x] Bugfix
Numerous fixes for Search functionality:
- [ADF-2896] Slider: Not …
> search fixes

- lib/core/login/components/login.component.spec.ts
- lib/core/login/components/login.component.ts
- lib/core/mock/authentication.service.mock.ts
- lib/core/models/redirection.model.ts
- lib/core/services/auth-guard-bpm.service.spec.ts
- lib/core/services/auth-guard-bpm.service.ts
- lib/core/services/auth-guard-ecm.service.spec.ts
- lib/core/services/auth-guard-ecm.service.ts
- lib/core/services/auth-guard.service.spec.ts
- lib/core/services/auth-guard.service.ts
- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
> [ADF-2904] Search - redirect breaks application

- lib/core/form/components/widgets/text/text-mask.component.ts
- lib/core/services/highlight-transform.service.ts
- lib/core/services/log.service.ts
- lib/core/services/notification.service.ts
- lib/core/services/shared-links-api.service.ts
- lib/core/services/sites.service.ts
- lib/core/services/storage.service.ts
- lib/core/services/thumbnail.service.ts
- lib/core/services/translation.service.ts
- lib/core/services/user-preferences.service.ts
> - [ ] Bugfix
Added JSDocs for core components and services.
> - [ ] Yes
> - [x] No
> [ADF-2905] Added JSDocs for core

- lib/core/sidenav-layout/components/layout-container/layout-container.component.scss
> [ADF-2772] Sidenav Layout - fix height

- lib/core/services/auth-guard-bpm.service.spec.ts
- lib/core/services/auth-guard-bpm.service.ts
- lib/core/services/auth-guard-ecm.service.spec.ts
- lib/core/services/auth-guard-ecm.service.ts
- lib/core/services/auth-guard.service.spec.ts
- lib/core/services/auth-guard.service.ts
> [ADF-2964] Auth Guard - error when state is not an active route

- demo-shell/src/app.config.json
- docs/content-services/search-filter.component.md
- lib/content-services/search/components/search-number-range/search-number-range.component.spec.ts
- lib/content-services/search/components/search-number-range/search-number-range.component.ts
- lib/content-services/tag/tag-actions.component.spec.ts
- lib/content-services/tag/tag-actions.component.ts
> - [x] Bugfix
- [ADF-2914](https://issues.alfresco.com/jira/browse/ADF-2914) …
> [ADF-2914] support for number range patterns

- docs/content-services/file-uploading-dialog.component.md
- docs/content-services/node-permission.service.md
- docs/content-services/version-list.component.md
- docs/core/accordion-group.component.md
- docs/core/accordion.component.md
- docs/core/auth-guard-bpm.service.md
- docs/core/auth-guard-ecm.service.md
- docs/core/auth-guard.service.md
- docs/core/card-item-types.service.md
- docs/core/card-view-item.interface.md
- docs/core/card-view.component.md
- docs/core/form-field.component.md
- docs/core/form-rendering.service.md
- lib/config/DocProcessor/tools/tsInfo.js
- lib/config/DocProcessor/tools/tsInfo.ts
> - [ ] Bugfix
Reviewed docs for core and content services. Broke Card View docs into a few separate files (I've requested Andras's review on this). Also added a class name to the list of exceptions in the prop table script.
**Does this …
> [ADF-2824] Reviewed docs for core and content services

- .angular-cli.json
- lib/config/webpack.style.js
- lib/core/sidenav-layout/components/layout-container/layout-container.component.scss
- lib/core/sidenav-layout/components/layout-container/layout-container.component.ts
> - [x] Bugfix
Styles were ruined.
Fixed. …
> [ADF_NOISSUE] Fix styling and sidenav layout fixes

- lib/process-services/people/components/people-search/people-search.component.ts
- lib/process-services/process-list/services/process-filter.service.ts
- lib/process-services/process-list/services/process.service.ts
- lib/process-services/task-list/components/task-standalone.component.ts
- lib/process-services/task-list/services/task-filter.service.ts
- lib/process-services/task-list/services/tasklist.service.ts
> - [ ] Bugfix
Added JSDocs for process services.
> - [ ] Yes
> - [x] No
> [ADF-2905] Added JSDocs for process services

- demo-shell/src/app.config.json
- demo-shell/src/app/components/login/login.component.html
- docs/core/app-config.pipe.md
- lib/core/app-config/app-config.module.ts
- lib/core/app-config/app-config.pipe.ts
> - [ ] Bugfix
Adds a new `adfAppConfig` pipe that allows fetching values directly …
> [ADF-2973] Angular pipe to get application configuration settings

- lib/content-services/permission-manager/components/add-permission/add-permission-dialog.component.ts
> - [X] Bugfix
private attributes breaks AOT
removed private …
> [ADF-NO-PRIVATE] removed private property which breaks AOT

- demo-shell/src/app/components/trashcan/trashcan.component.html
- demo-shell/src/app/components/trashcan/trashcan.component.ts
- lib/content-services/document-list/data/share-datatable-adapter.spec.ts
- lib/content-services/document-list/data/share-datatable-adapter.ts
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/date-cell.component.ts
- lib/core/datatable/data/object-datatable-adapter.ts
- lib/core/pipes/time-ago.pipe.spec.ts
- lib/core/pipes/time-ago.pipe.ts
- lib/core/services/highlight-transform.service.ts
> - [X] Bugfix
time ago pipe is not localised.
time ago pipe is now localised
**Does …
> [ADF-2699] added localisation for time ago pipe

- lib/content-services/document-list/components/document-list.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2813
fixed
**Does this PR …
> [ADF-2813] set default sorting for documents list

- demo-shell/src/app/components/permissions/demo-permissions.component.ts
> - [X] Bugfix
Duplicate permission message is not showed
Duplicate permission message …
> [ADF-2826] fixed wrong parsing for error message

- lib/content-services/breadcrumb/breadcrumb.component.html
- lib/content-services/breadcrumb/breadcrumb.component.scss
- lib/content-services/breadcrumb/breadcrumb.component.ts
- lib/content-services/breadcrumb/dropdown-breadcrumb.component.scss
- lib/content-services/breadcrumb/dropdown-breadcrumb.component.ts
- lib/core/datatable/components/datatable/datatable.component.scss
> - [X] Bugfix
Toolbar overflows when names are too long or there are too many folders …
> [ADF-2739] Improved breadcrumb logic

- demo-shell/src/app/components/process-service/process-service.component.ts
> - [X] Bugfix
Create start task button don't work at first click 'cause the filters were reloaded …
> [ADF-2967] fixed create new task navigation

- docs/core/app-config.service.md
- lib/core/app-config/app-config.service.spec.ts
- lib/core/app-config/app-config.service.ts
> - [ ] Bugfix
Allow dynamic procotol substitution to allow switching to …
> [ADF-2961] support for protocol substition in app config files

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- docs/content-services/content-action.component.md
- lib/content-services/document-list/components/content-action/content-action.component.spec.ts
- lib/content-services/document-list/components/content-action/content-action.component.ts
- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/document-list/models/content-action.model.ts
> - [ ] Bugfix
- support for conditional visibility (see docs)
- updated docs with …
> [ADF-2503] conditional visibility for content actions

- lib/content-services/upload/components/upload-button.component.spec.ts
- lib/content-services/upload/components/upload-button.component.ts
- lib/content-services/upload/components/upload-version-button.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2995
**Does this PR …
> [ADF-2995] Permissions - Consumer should be able to upload a new version for his file on a private site

- demo-shell/src/app/components/process-service/process-service.component.html
> - [x] Bugfix
The icon is not shown
The icon is shown …
> [ADF-2992] Demo shell  Sinenav action fix icons 

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.html
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
- docs/content-services/version-list.component.md
- lib/content-services/upload/components/base-upload/upload-base.spec.ts
- lib/content-services/upload/components/base-upload/upload-base.ts
- lib/content-services/upload/components/upload-version-button.component.ts
- lib/content-services/version-manager/version-upload.component.html
- lib/content-services/version-manager/version-upload.component.scss
- lib/core/models/file.model.ts
- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2563
**Does this PR …
> [ADF-2563] Improve versioning functionality

- lib/content-services/i18n/en.json
- lib/content-services/search/components/search-date-range/search-date-range.component.html
- lib/content-services/search/components/search-date-range/search-date-range.component.ts
> - [x] Bugfix
Please see https://issues.alfresco.com/jira/browse/ADF-2997
Please see …
> [ADF-2997] The meaning of the range fields is not clear

- demo-shell/src/app/components/login/login.component.scss
> - [x] Bugfix
style fixes for demo shell …
> [ADF-2044] (demo shell) login css fixes

- lib/core/form/services/form-rendering.service.spec.ts
- lib/core/services/dynamic-component-mapper.service.ts
> - [ ] Bugfix
Override the existing widgets by default and throw errors if explicitly …
> [ADF-1997] override custom form widgets by default

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- lib/core/form/components/widgets/upload/upload.widget.ts
- lib/core/form/services/activiti-alfresco.service.spec.ts
- lib/core/form/services/activiti-alfresco.service.ts
- lib/process-services/content-widget/attach-file-widget.component.html
- lib/process-services/content-widget/attach-file-widget.component.ts
- lib/process-services/content-widget/attach-file-widget.components.spec.ts
- lib/process-services/process-list/components/start-process.component.html
- lib/process-services/process-list/components/start-process.component.ts
> - [X] Bugfix
file loaded from Content service is not previewed
file is now correctly …
> [ADF-2726] fixed save content for external repository

- lib/content-services/document-list/services/node-actions.service.spec.ts
- lib/content-services/document-list/services/node-actions.service.ts
- lib/content-services/i18n/de.json
- lib/content-services/i18n/en.json
- lib/content-services/i18n/es.json
- lib/content-services/i18n/fr.json
- lib/content-services/i18n/it.json
- lib/content-services/i18n/ja.json
- lib/content-services/i18n/nb.json
- lib/content-services/i18n/nl.json
- lib/content-services/i18n/pt-BR.json
- lib/content-services/i18n/ru.json
- lib/content-services/i18n/zh-CN.json
> - [x] Bugfix
- fix typo in resource files …
> [ADF-3052] fix typo in the resource key

- lib/content-services/search/components/search-number-range/search-number-range.component.html
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2923
When the user press "Enter" in both editable fields …
> [ADF-2923] button type added

- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [X] Bugfix
on super slow connections the select icon is removed
on super slow …
> [ADF-2608] added a fix to handle selection on slow connection problem

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- docs/core/node-favorite.directive.md
- lib/core/directives/node-favorite.directive.spec.ts
- lib/core/directives/node-favorite.directive.ts
> [ADF-3062] NodeFavoriteDirective - remove isFavorite check

- docs/tutorials/creating-javascript-app-using-alfresco-js-api.md
- docs/tutorials/working-with-nodes-api-service.md
- docs/tutorials/working-with-nodes-js-api.md
> - [ ] Bugfix
Reviewed latest tutorial content.
> - [ ] Yes
> - [x] No
> [ADF-2679] Reviewed latest tutorial content

- lib/content-services/search/components/search-filter/search-filter.component.html
- lib/content-services/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
- lib/content-services/search/search-query-builder.service.ts
> - [x] Bugfix
- [ADF-2927](https://issues.alfresco.com/jira/browse/ADF-2927): Add …
> [ADF-2927] search filter enhancements

- demo-shell/src/app/components/login/login.component.html
- demo-shell/src/app/components/login/login.component.ts
> [ADF-2985] Demo shell - Provide an easy way to test the security issue

- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/process-services/filter.model.md
- lib/process-services/task-list/components/task-filters.component.html
- lib/process-services/task-list/components/task-filters.component.spec.ts
- lib/process-services/task-list/components/task-filters.component.ts
- lib/process-services/task-list/models/filter.model.ts
> - [x] Bugfix
User is not redirected to active process when completing the first task as initiator …
> [ADF-2854] Fix demoshell task/process filter and routing

- docs/README.md
- docs/core/README.md
- docs/core/app-config.pipe.md
- docs/core/buttons-menu.component.md
- docs/core/menu-button.model.md
- lib/core/buttons-menu/buttons-menu.component.ts
> - [ ] Bugfix
Reviewed/added docs for some of the new 2.4 components.
> - [ ] Yes
> - [x] No
> [ADF-2824] Reviewed docs for new components in 2.4

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/core/datatable.component.md
- docs/process-services/process-list.component.md
- docs/process-services/task-list.component.md
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/process-services/process-list/components/process-list.component.html
- lib/process-services/process-list/components/process-list.component.spec.ts
- lib/process-services/process-list/components/process-list.component.ts
- lib/process-services/task-list/components/task-list.component.html
- lib/process-services/task-list/components/task-list.component.spec.ts
- lib/process-services/task-list/components/task-list.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3082
**Does this PR …
> [ADF-3082] Task Filter - Custom Task filters don't work

- lib/process-services/task-list/components/task-list.component.css
- lib/process-services/task-list/components/task-list.component.html
> - [x] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-3041
* A new general …
> [ADF-3041] - Task List Empty State Issue

- demo-shell/src/app/components/files/files.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2685 …
> [ADF-2685] fix demo shell gallery view switch

- demo-shell/src/app/components/log/log.component.ts
- lib/content-services/dialogs/share.dialog.html
- lib/content-services/dialogs/share.dialog.spec.ts
- lib/content-services/dialogs/share.dialog.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2710
**Does this PR …
> [ADF-2710] Fix conflict link creation id in shared link

- lib/core/form/components/widgets/core/form-field-validator.spec.ts
- lib/core/form/components/widgets/core/form-field-validator.ts
> - [x] Bugfix
Please see https://issues.alfresco.com/jira/browse/ADF-2698
Fixed issue …
> [ADF-2698] Date and time Widget - UTC vs local time issue

- lib/content-services/search/components/search-filter/search-filter.component.html
- lib/content-services/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
- lib/content-services/search/search-query-builder.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3108
**Does this PR …
> [ADF-3108] Search - facetQueries panel renders when not defined in configuration

- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/core/datatable.component.md
- docs/process-services/task-list.component.md
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/core/datatable/data/data-column.schema-assembler.ts
- lib/core/datatable/data/data-table.schema.ts
- lib/core/datatable/public-api.ts
- lib/process-services/mock/public-api.ts
- lib/process-services/mock/task/task-list.mock.ts
- lib/process-services/task-list/components/task-list.component.html
- lib/process-services/task-list/components/task-list.component.spec.ts
- lib/process-services/task-list/components/task-list.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3039
**Does this PR …
> [ADF-3039] Task List - Enanchement

- docs/core/toolbar.component.md
> - [ ] Bugfix
Updated docs with the example of `spacer` element.
**Does this PR …
> [ADF-3112] update toolbar docs

- docs/core/card-view-item.interface.md
- lib/core/card-view/interfaces/card-view-item-properties.interface.ts
- lib/core/card-view/models/card-view-baseitem.model.spec.ts
- lib/core/card-view/models/card-view-baseitem.model.ts
> - [ ] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-3114
Implemented. …
> [ADF-3114] Add custom data holder for CardViewItems

- lib/core/form/components/widgets/people/people.widget.html
- lib/core/form/components/widgets/people/people.widget.scss
- lib/core/form/components/widgets/people/people.widget.spec.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2754
Tests are randomly failing. …
> [ADF-2754] People component tests fixed and style improvement

- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
- fix the order of the selected items to reflect visual order …
> [ADF-3131] fix selection order for DT/DL

- demo-shell/src/app/components/process-service/process-service.component.html
- docs/process-services/process-list.component.md
- lib/process-services/i18n/en.json
- lib/process-services/process-list/components/process-list.component.html
- lib/process-services/process-list/components/process-list.component.spec.ts
- lib/process-services/process-list/components/process-list.component.ts
- lib/process-services/process-list/process-list.module.ts
> - [ ] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-3066
*  A new general …
> [ADF-3066] ProcessList Component - Empty State issue.

- lib/core/form/components/widgets/date/date.widget.spec.ts
> - [ ] Bugfix
Fixed a failing test …
> [ADF-fix date widget test] Fixing a randomly failing test

- docs/process-services/apps-list.component.md
- lib/process-services/app-list/apps-list.component.html
- lib/process-services/app-list/apps-list.component.scss
- lib/process-services/app-list/apps-list.component.spec.ts
- lib/process-services/app-list/apps-list.component.ts
- lib/process-services/app-list/apps-list.module.ts
- lib/process-services/i18n/en.json
> - [ ] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-3067
*  A new general …
> [ADF-3067] App-list Empty State.

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/notifications/notifications.component.html
- demo-shell/src/app/components/notifications/notifications.component.scss
- demo-shell/src/app/components/notifications/notifications.component.ts
> - [ ] Bugfix
- adds new "Notifications" route and area to demo shell, allows testing …
> notification service demo and testing area

- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.scss
> - [x] Bugfix
- fix title area alignment …
> [ADF-3116] fix viewer title style

- demo-shell/src/app/components/process-service/process-service.component.html
- lib/process-services/i18n/en.json
- lib/process-services/task-list/components/task-list.component.html
> - [x] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-3132
* Changed icon and …
> [ADF-3132] TaskList empty state doesn't respect the specification

- lib/content-services/search/components/search-filter/search-filter.component.ts
> - [x] Bugfix
Please see Jira issue https://issues.alfresco.com/jira/browse/ADF-3134 …
> [ADF-3134] fix increasing search calls issue

- docs/process-services/apps-list.component.md
- docs/process-services/checklist.component.md
- docs/process-services/create-process-attachment.component.md
- docs/process-services/create-task-attachment.component.md
- docs/process-services/people-list.component.md
- docs/process-services/people-search.component.md
- docs/process-services/people.component.md
- docs/process-services/process-attachment-list.component.md
- docs/process-services/process-audit.directive.md
- docs/process-services/process-comments.component.md
- docs/process-services/process-filter.service.md
- docs/process-services/process-filters.component.md
- docs/process-services/process-instance-details.component.md
- docs/process-services/process-instance-tasks.component.md
- docs/process-services/process-list.component.md
- docs/process-services/process.service.md
- docs/process-services/start-process.component.md
- docs/process-services/start-task.component.md
- docs/process-services/task-attachment-list.component.md
- docs/process-services/task-audit.directive.md
- docs/process-services/task-details.component.md
- docs/process-services/task-filter.service.md
- docs/process-services/task-filters.component.md
- docs/process-services/task-header.component.md
- docs/process-services/task-list.component.md
- docs/process-services/task-standalone.component.md
- docs/process-services/tasklist.service.md
- tools/doc/tools/typeLinker.js
- tools/doc/tools/typeLinker.ts
> - [ ] Bugfix
Updated process services docs with the latest type linker features.
> - [ ] Yes
> - [x] No
> [ADF-2764] Applied new type linker features to proc services docs

- demo-shell/src/app/components/datatable/datatable.component.html
- demo-shell/src/app/components/datatable/datatable.component.ts
> - [ ] Bugfix
refs #3441
Simple demo shell example on how a custom filtering can be …
> [ADF-3153] simple filtering for datatable

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- docs/content-services/content-action.component.md
- lib/content-services/document-list/components/content-action/content-action.component.ts
- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/document-list/models/content-action.model.ts
- lib/core/context-menu/context-menu-holder.component.ts
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [ ] Bugfix
provide support for binding to `[disabled]` property:
- raw values
- …
> [ADF-2859] conditional evaluation of disabled state for content actions

- demo-shell/src/app.config.json
> - [x] Bugfix
The default provider is OAUTH
The default provider is ALL (ECM and BPM) …
> [ADF-3156] App config default ALL (BPM and ECM) provider

- lib/core/datatable/components/datatable/datatable.component.spec.ts
> removing wrong fdescribe

- lib/core/settings/host-settings.component.ts
> - [x] Bugfix
The form is invalid even though all the fields are valid
The form is …
> [ADF-3161] Host Setting - Fix invalid form

- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [ ] Bugfix
restore original selection order as per reviews and requests.
The ACA …
> restore historical selection order

- lib/process-services/i18n/en.json
* Added a missing translation keys.
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3173 …
> [ADF-3173] [Task List] - Empty list message is not translated

- demo-shell/src/app/app.component.scss
- demo-shell/src/app/components/app-layout/app-layout.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-3185
Fixed, while …
> [ADF-3185] Fix dropdown panel in viewer toolbar  because of z-index

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/insights/package.json
- lib/process-services/package.json
- package.json
Update ADF packages version 2.4.0-beta13
> Update ADF packages version 2.4.0-beta13

- docs/content-services/search-check-list.component.md
- docs/content-services/search-date-range.component.md
- docs/content-services/search-filter.component.md
- docs/content-services/search-filter.service.md
- docs/content-services/search-number-range.component.md
- docs/content-services/search-query-builder.service.md
- docs/content-services/search-radio.component.md
- docs/content-services/search-slider.component.md
- docs/content-services/search-text.component.md
- docs/content-services/search-widget.interface.md
- tools/doc/doctool.config.json
> - [ ] Bugfix
Reviewed the new search component docs for 2.4. The main task was moving information from the very long search filter page into separate pages but I have also added some basic docs for the supporting services.
**Does this …
> [ADF-2824] Reviewed search docs for 2.4

- lib/core/app-config/schema.json
- lib/core/models/oauth-config.model.ts
> - [x] Bugfix
unused field
removed …
> [ADF-3183] SSO Schema json part - Remove unused field

- lib/core/login/components/login.component.spec.ts
- lib/core/login/components/login.component.ts
- lib/core/mock/authentication.service.mock.ts
- lib/core/models/redirection.model.ts
- lib/core/services/auth-guard-bpm.service.spec.ts
- lib/core/services/auth-guard-bpm.service.ts
- lib/core/services/auth-guard-ecm.service.spec.ts
- lib/core/services/auth-guard-ecm.service.ts
- lib/core/services/auth-guard.service.spec.ts
- lib/core/services/auth-guard.service.ts
- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3181
**Does this PR …
> [ADF-3181] Auth Guard - redirect by string url

- lib/process-services/task-list/components/task-details.component.html
> - [X] Bugfix
Component not loading because it variable was not initialised due to a typo. …
> [ADF-3210] Typo People Search

- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3196
**Does this PR …
> [ADF-3196] [Task list / Process list] - The 'Task details' are not diplayed for the selected Task

- lib/core/services/nodes-api.service.ts
> - [x] Bugfix
Edit metadata button disappears after updating one of the fields.
Fixed …
> [ADF-3176] Fixed permissionsissue when editing metadata

- lib/content-services/version-manager/version-upload.component.html
- lib/content-services/version-manager/version-upload.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3212
Not able to upload new version of a file.
Buttons …
> [ADF-3212] Upload version buttons wrapping fixed

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/insights/package.json
- lib/process-services/package.json
- package.json
Update ADF packages version 2.4.0-beta14
> Update ADF packages version 2.4.0-beta14

- demo-shell/resources/i18n/en.json
- lib/content-services/breadcrumb/dropdown-breadcrumb.component.html
> - [x] Bugfix
Translation fix for breadcrumb dropdown …
> [no-issue] fix translations

- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-3190
Fixed
**Does this …
> [ADF-3190] Fix rerendering issue with content-meta-data

- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3176
The value is changed. The file content is reloaded. …
> [ADF-3176] file content reload fixed

- lib/core/services/alfresco-api.service.ts
- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
- lib/core/testing/setupTestBed.ts
> - [X] Bugfix
move ticket store logic in js-api …
> [ADF-3224] move ticket store logic in js-api

- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [X] Bugfix
The permissions of the node were missing when fetching them. …
> [ADF-3212] Fixed permission issues when updating version

- docs/core/login.component.md
- lib/core/login/components/login.component.ts
- lib/core/services/alfresco-api.service.ts
- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
- lib/core/services/settings.service.ts
> fix login oauth cookie problem

- lib/core/viewer/components/pdfViewer.component.ts
> - [x] Bugfix
update PDF view event if the scale is the same (fixes issue with blank …
> [ADF-3176] fix missing pdf viewer update when scale is the same

- demo-shell/src/app/components/log/log.component.ts
> - [x] Bugfix
Object messages are not logged
EVerything passed to the log component …
> [ADF-3242] removed filter for string in example log component

- demo-shell/src/app/app.component.ts
> - [x] Bugfix
check 401 and redirect to login in demo shell …
> [ADF-3224] check 401 and redirect demo shell

- lib/core/form/components/widgets/people/people.widget.html
- lib/core/form/components/widgets/people/people.widget.spec.ts
- lib/core/form/components/widgets/people/people.widget.ts
> - [X] Bugfix
People widget is incorrectly displayed in readonly mode
Now people …
> [ADF-3248] fixed readonly status for people widget

- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
> - [ ] Bugfix
we don't check the current provider
we check the provider
**Does this …
> [ADF-3251] Authentication Service - Check if used loggedin based on the provider

- lib/process-services/process-list/components/process-list.component.css
- lib/process-services/task-list/components/task-list.component.css
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3262
**Does this PR …
> [ADF-3262] Remove avoidable css style from task/process list component

- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
Custom columns are not align in datatable component.
It aligns all the …
> [ADF-3199] Datatable layout fix

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/breadcrumb-demo/breadcrumb-demo.component.ts
- demo-shell/src/app/components/content-node-selector/content-node-selector.component.html
- demo-shell/src/app/components/content-node-selector/content-node-selector.component.scss
- demo-shell/src/app/components/content-node-selector/content-node-selector.component.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.scss
- lib/content-services/document-list/components/document-list.component.ts
> - [ ] Bugfix
Added example page for content node selector component
**Does this PR …
> [ADF-2769] Added example page for content node selector

- lib/core/form/components/widgets/dynamic-table/dynamic-table.widget.html
> - [ ] Bugfix
Shows the value for the boolean on dynamic table as : True/False
Shows …
> [ADF-3267] changed true/false values showed with a readonly checkbox

- lib/core/form/components/widgets/dynamic-table/editors/datetime/datetime.editor.html
- lib/core/form/components/widgets/dynamic-table/editors/datetime/datetime.editor.scss
- lib/core/form/components/widgets/dynamic-table/editors/datetime/datetime.editor.spec.ts
- lib/core/form/components/widgets/dynamic-table/editors/datetime/datetime.editor.ts
- lib/core/form/components/widgets/dynamic-table/editors/row.editor.html
- lib/core/form/components/widgets/index.ts
> - [ ] Bugfix
Added datetime editor support for dynamic tables
**Does this PR …
> [ADF-3268] added datetime widget for dynamic table

- lib/core/i18n/en.json
- lib/core/settings/host-settings.component.html
- lib/core/settings/host-settings.component.ts
> - [ ] Bugfix
the uriLogout is not exposed
the uriLogout is exposed
**Does this PR …
> [ADF-3252] Host Setting - Expose uriLogout

- docs/process-services/attach-form.component.md
- docs/process-services/task-standalone.component.md
- lib/process-services/i18n/en.json
- lib/process-services/task-list/components/attach-form.component.html
- lib/process-services/task-list/components/attach-form.component.scss
- lib/process-services/task-list/components/attach-form.component.spec.ts
- lib/process-services/task-list/components/attach-form.component.ts
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.scss
- lib/process-services/task-list/components/task-details.component.spec.ts
- lib/process-services/task-list/components/task-details.component.ts
- lib/process-services/task-list/components/task-standalone.component.html
- lib/process-services/task-list/components/task-standalone.component.scss
- lib/process-services/task-list/components/task-standalone.component.ts
- lib/process-services/task-list/public-api.ts
- lib/process-services/task-list/task-list.module.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2494
There is no way to attach a form in task standalone …
> [ADF-2494] Task Standalone - Provide a way to attach a form

- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/report-issue/report-issue.component.html
- demo-shell/src/app/components/report-issue/report-issue.component.scss
- demo-shell/src/app/components/report-issue/report-issue.component.ts
- lib/core/i18n/en.json
> - [ ] Bugfix
There is no report issue page for 403 error.
Fake report issue page …
> [ADF-3149] New Report Issue page created

- lib/process-services/task-list/components/no-task-detail-template.directive.spec.ts
- lib/process-services/task-list/components/task-details.component.ts
> - [X] Bugfix
When user try to involve people in creating a new task, an error is raised …
> [ADF-3281] - fixed error when user try to involve people

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/insights/package.json
- lib/process-services/package.json
- package.json
Update ADF packages version 2.5.0-beta1
> Update ADF packages version 2.5.0-beta1

- demo-shell/src/app/components/permissions/demo-permissions.component.ts
> - [X] Bugfix
No tooltip is showed by clicking on Add User or Group button
The no …
> [ADF-2671] fixed retrieving of error message

- lib/content-services/document-list/components/document-list.component.ts
> - [X] Bugfix
When user click on download action an error is logged on console
no …
> [ADF-3301] - added a check when handler is null

- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.html
- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.spec.ts
- lib/core/card-view/models/card-view-selectitem.model.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3298
Fixed
**Does this PR …
> [ADF-3298] Select CardView item label removed

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/card-view/card-view.component.html
- demo-shell/src/app/components/card-view/card-view.component.scss
- demo-shell/src/app/components/card-view/card-view.component.ts
- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.scss
- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3312
Implemented
**Does …
> [ADF-3312] CardViewItem in demo-shell

- lib/core/services/authentication.service.ts
- lib/core/services/cookie.service.ts
> - [X] Bugfix
Remember me cookie is wrongly evaluated
Remember me cookie is evaluated …
> [ADF-3255] fixed remember me behaviour

- lib/core/services/page-title.service.spec.ts
- lib/core/services/page-title.service.ts
> - [x] Bugfix
fix title translation when reloading page or using slow networks
**Does …
> [ADF-3328] fix title translation

- demo-shell/src/app.config.json
- lib/content-services/search/search-query-builder.service.ts
> - [x] Bugfix
Proper reset to defaults, fixes issues with global config mutations. …
> [ADF-3292] fix reset to defaults

- demo-shell/src/app/components/notifications/notifications.component.html
- demo-shell/src/app/components/notifications/notifications.component.ts
- docs/core/notification.service.md
- lib/core/services/notification.service.spec.ts
- lib/core/services/notification.service.ts
> - [x] Bugfix
The snackbar does not accept a custom configuration.
https://issues.alfresco.com/jira/browse/ADF-3286 …
> [ADF-3286] Snackbar now supports custom configuration

- demo-shell/src/app/components/files/files.component.html
- e2e/pages/adf/tagPage.js
- e2e/tag_component.e2e.ts
- e2e/viewer_content_services_component.e2e.ts
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.ts
- package-lock.json
> - [ ] Bugfix
Reinsert e2e tag test …
> Reinsert e2e tag test

- e2e/card-view-component.e2e.ts
- e2e/pages/adf/cardViewPageComponent.js
- e2e/pages/adf/navigationBarPage.js
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3275
https://issues.alfresco.com/jira/browse/ADF-3193 …
> [ADF-3193, ADF-3275]  CardView e2e tests

- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
Please check https://issues.alfresco.com/jira/browse/ADF-3324
Please …
> [ADF-3324] Preview - unshared file breaks preview

- e2e/pages/adf/tagPage.js
- e2e/process_attachmentList_actionMenu.e2e.ts
- e2e/tag_component.e2e.ts
> [no-issue] e2e delete tag test

- e2e/pages/adf/process_services/tasksPage.js
- e2e/task_attachmentList_actionMenu.e2e.ts
> - [ ] Bugfix
Automated test for Attachment List on Tasks. …
> [ADF-3025] Create automated test for attachment list for tasks

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/app-layout/app-layout.component.html
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/form/demo-form.ts
- demo-shell/src/app/components/header-data/header-data.component.html
- demo-shell/src/app/components/header-data/header-data.component.scss
- demo-shell/src/app/components/header-data/header-data.component.ts
- demo-shell/src/app/components/header-data/header-data.service.ts
- lib/core/layout/components/header/header.component.scss
- lib/core/layout/components/header/header.component.spec.ts
- lib/core/layout/components/header/header.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3339
new component added to …
> [ADF-3339] added test component for header

- docs/process-services/task-standalone.component.md
- lib/process-services/i18n/en.json
- lib/process-services/task-list/components/attach-form.component.html
- lib/process-services/task-list/components/attach-form.component.scss
- lib/process-services/task-list/components/attach-form.component.spec.ts
- lib/process-services/task-list/components/attach-form.component.ts
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.ts
- lib/process-services/task-list/components/task-header.component.spec.ts
- lib/process-services/task-list/components/task-header.component.ts
- lib/process-services/task-list/components/task-standalone.component.html
- lib/process-services/task-list/components/task-standalone.component.ts
- lib/process-services/task-list/services/tasklist.service.ts
> [ADF-3237] Change and remove form from a task

- demo-shell/resources/i18n/en.json
- e2e/pages/adf/core/toggleState.js
- e2e/pages/adf/dialog/uploadToggles.js
- e2e/pages/adf/process_services/dialog/taskDetailsToggles.js
- e2e/pages/adf/process_services/taskDetailsPage.js
- e2e/start_task_custom_app.e2e.ts
- e2e/start_task_task_app.e2e.ts
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.scss
> [ADF-3369] Add toggle for showHeaderContent property

- lib/core/collapsable/accordion-group.component.spec.ts
- lib/core/collapsable/accordion-group.component.ts
> [ADF-3354] accordion group - revert tests & conditions

- docs/core/empty-content.component.md
> Fix update-content tag documentation

- CONTRIBUTING.md
> Typo convention

- e2e/core/card-view/metadata-smoke-tests.e2e.ts
> - [ ] Bugfix
Fixed flaky test …
> Fixed metadata flaky test

- e2e/pages/adf/commentsPage.ts
- e2e/process-services/comment_component_processes.e2e.ts
- e2e/process-services/comment_component_tasks.e2e.ts
> - [ ] Bugfix
Automated tests for comments - Process services - tasks
**Does this PR …
> [ADF-3377] Create automated tests for comments-Tasks

- e2e/core/card-view/metadata-smoke-tests.e2e.ts
- e2e/pages/adf/process_services/processServicesPage.js
- e2e/process-services/process_filters_component.e2e.ts
> - [ ] Bugfix
Stabilising tests …
> Stabilize tests

- e2e/pages/adf/process_services/dialog/createChecklistDialog.js
- e2e/pages/adf/process_services/taskDetailsPage.js
- e2e/pages/adf/process_services/tasksPage.js
- e2e/process-services/checklist_component.e2e.ts
- e2e/process-services/people_component.e2e.ts
> [ADF-3368]Create automated tests for checklist and people components

- e2e/core/header_component.e2e.ts
- e2e/pages/adf/core/headerPage.ts
- e2e/pages/adf/navigationBarPage.js
- lib/core/layout/components/header/header.component.html
> - [ ] Bugfix
Automated test regarding header component …
> [ADF-3399] Create automated tests to cover Header component

- demo-shell/src/app/components/notifications/notifications.component.html
- demo-shell/src/app/components/notifications/notifications.component.ts
- e2e/content-services/notifications_component.e2e.ts
- e2e/pages/adf/notificationPage.js
> - [ ] Bugfix
E2e tests
https://issues.alfresco.com/jira/browse/ADF-3388
**Does this …
> [ADF-3388] E2e tests for notification component added

- lib/content-services/search/components/search-chip-list/search-chip-list.component.html
- lib/content-services/search/components/search-chip-list/search-chip-list.component.spec.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
> - [x] Bugfix
Fix a regression with chip list and "close" buttons.
**Does this PR …
> [ADF-3406] fix chip list integration regression

- demo-shell/src/app.config.json
- demo-shell/src/app/components/process-list-demo/process-list-demo.component.html
- demo-shell/src/app/components/process-list-demo/process-list-demo.component.ts
- demo-shell/src/app/components/process-service/process-service.component.html
- docs/process-services/process-list.component.md
- lib/process-services/i18n/en.json
- lib/process-services/process-list/components/process-list.component.spec.ts
- lib/process-services/process-list/components/process-list.component.ts
- lib/process-services/process-list/models/filter-process.model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3308
* Removed 'name' input …
> [ADF-3308] ProcessList Component - Provide a way to filter the list by fields

- lib/process-services/process-list/components/process-list.component.spec.ts
> Fix failing unit test related to the double merge of ADF 3141 and 3308

- demo-shell/src/app/components/process-service/process-service.component.html
- lib/process-services/process-list/components/process-filters.component.spec.ts
- lib/process-services/process-list/components/process-filters.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3284
**Does this PR …
> [ADF-3284] ProcessFilter - preselect filter param

- e2e/content-services/search_component.e2e.ts
- e2e/content-services/search_page_component.e2e.ts
- e2e/core/card-view/aspect-oriented-config.e2e.ts
- e2e/core/card-view/card-view-component.e2e.ts
- e2e/core/login/redirection.e2e.ts
- e2e/core/login/remember_me.e2e.ts
- e2e/process-services/form_widgets_component.e2e.ts
- e2e/process-services/pagination_tasklist_addingTasks.e2e.ts
- e2e/process-services/process_filters_component.e2e.ts
- e2e/process-services/start_process_component.e2e.ts
- e2e/process-services/start_task_custom_app.e2e.ts
- e2e/process-services/start_task_task_app.e2e.ts
- e2e/process-services/task_list_pagination.e2e.ts
> [ADF-3417]Fixing test rail ID's

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/process-service/process-service.component.ts
- demo-shell/src/app/components/task-list-demo/task-list-demo.component.html
- demo-shell/src/app/components/task-list-demo/task-list-demo.component.scss
- demo-shell/src/app/components/task-list-demo/task-list-demo.component.ts
- docs/process-services/task-list.component.md
- lib/process-services/task-list/components/task-list.component.ts
- lib/process-services/task-list/models/filter.model.ts
> - [ ] Bugfix
Not able to filter the task list
provide a way to filter the task list …
> [ADF-3103] Added new inputs, columns and overall improvement to Task List Demo

- e2e/content-services/document_list_component.e2e.ts
> [ADF-3421] Changed Test Rail IDs

- demo-shell/src/app/components/app-layout/app-layout.component.html
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/header-data/header-data.component.html
- demo-shell/src/app/components/header-data/header-data.component.scss
- demo-shell/src/app/components/header-data/header-data.component.ts
- demo-shell/src/app/components/header-data/header-data.service.ts
> - [ ] Bugfix
Demo-shell update. …
> [ADF-3358] Header - update demo shell component

- e2e/content-services/search_multiselect.e2e.ts
- e2e/pages/adf/searchFiltersPage.js
- lib/content-services/search/components/search-filter/search-filter.component.html
> - [ ] Bugfix
E2E tests for Multi-selection on facets …
> [ADF-3367] Multi-selection on facets (e2e)

- lib/content-services/search/components/search-filter/search-filter.component.html
- lib/content-services/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
> - [x] Bugfix
Please see Jira issue https://issues.alfresco.com/jira/browse/ADF-3400 …
> [ADF-3400] fix buckets update on search filter

- docs/content-services/content-metadata.component.md
- docs/content-services/upload-drag-area.component.md
- docs/core/header.component.md
- docs/core/login.component.md
> - [ ] Bugfix
A few little bits of tidying up as part of the doc review.
> - [ ] Yes
> - [x] No
> [ADF-3425] Minor edits to doc files

- e2e/pages/adf/process_services/attachFormPage.ts
- e2e/pages/adf/process_services/formFields.js
- e2e/process-services/attach_form_component.e2e.ts
> - [ ] Bugfix
Automated test for Attach form component …
> [ADF-3414] Create automated test for Attach form component

- e2e/content-services/directives/create_folder_directive.e2e.ts
- e2e/content-services/search_component.e2e.ts
- e2e/core/header_component.e2e.ts
- e2e/core/viewer_content_services_component.e2e.ts
- e2e/pages/adf/contentServicesPage.js
- e2e/pages/adf/dialog/createFolderDialog.js
- e2e/pages/adf/dialog/searchDialog.js
- e2e/pages/adf/viewerPage.js
- lib/content-services/dialogs/folder.dialog.html
- scripts/pr-deploy.js
> - [ ] Bugfix
directive crete folder new e2e …
> [no-issue-e2e] directive crete folder new e2e

- e2e/content-services/document_list_actions.e2e.ts
- e2e/content-services/document_list_component.e2e.ts
- e2e/pages/adf/contentServicesPage.js
- e2e/pages/adf/dialog/contentList.js
- lib/core/context-menu/context-menu-holder.component.ts
- lib/core/viewer/components/pdfViewer.component.html
> - [ ] Bugfix
E2E tests for action row …
> [e2e] Added document list actions [E2E]

- demo-shell/src/app/components/task-list-demo/task-list-demo.component.html
- demo-shell/src/app/components/task-list-demo/task-list-demo.component.ts
- docs/process-services/task-list.component.md
> - [] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3103
The tasks datatable …
> [ADF-3103] Added new inputs & columns Task List Demo - Rebase

- lib/core/toolbar/toolbar.component.scss
- scripts/README.md
… the material component
The colour of the toolbar doens't change  …
> [ADF-3450] remove css override background color, is already manged by the material component

- demo-shell/src/app.config.json
- e2e/content-services/search_multiselect.e2e.ts
- e2e/pages/adf/searchFiltersPage.js
- lib/content-services/search/components/search-chip-list/search-chip-list.component.html
- lib/content-services/search/components/search-filter/search-filter.component.html
- lib/content-services/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
- lib/content-services/search/search-configuration.interface.ts
- lib/content-services/search/search-query-builder.service.spec.ts
- lib/content-services/search/search-query-builder.service.ts
> - [x] Bugfix
Please see https://issues.alfresco.com/jira/browse/ADF-3435 and …
> [ADF-3435][ADF-3436] fix search chips

- lib/core/form/components/widgets/people/people.widget.html
- lib/core/form/components/widgets/people/people.widget.spec.ts
- lib/core/form/components/widgets/people/people.widget.ts
> - [X] Bugfix
There is one particular case when we select an option we will see [object] as a value in the input …
> [ADF-3424] Start task - Object display instead of value for assignee

- demo-shell/src/app/components/process-service/process-service.component.ts
- lib/core/form/components/start-form.component.ts
- lib/core/form/components/widgets/upload/upload.widget.ts
> - [x] Bugfix
- handle content clicks for start form
- fix subscription leak for …
> viewer fixes for demo shell

- lib/insights/diagram/components/tooltip/diagram-tooltip.component.html
- lib/insights/diagram/components/tooltip/diagram-tooltip.component.spec.ts
> - [ x ] Bugfix
doesn't show heatmap values
show heat map values
**Does this PR …
> [ADF-3463] add missing information to report diagram

- demo-shell/src/app/components/files/files.component.ts
- e2e/actions/ACS/upload.actions.ts
- e2e/actions/APS/apps.actions.ts
- e2e/actions/drop.actions.ts
- e2e/actions/users.actions.ts
- e2e/content-services/document_list_actions.e2e.ts
- e2e/pages/adf/contentServicesPage.js
- e2e/pages/adf/process_services/attachmentListPage.ts
- e2e/pages/adf/process_services/widgets/AttachFile.js
- e2e/pages/adf/versionManagerPage.ts
- e2e/standalone_task.e2e.ts
- e2e/util/util.js
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/document-list/data/share-datatable-adapter.ts
- lib/core/pagination/infinite-pagination.component.spec.ts
- lib/core/pagination/infinite-pagination.component.ts
- package-lock.json
- package.json
- protractor.conf.js
> - [x] Bugfix
Infinite pagination stop to  work after deleted a file
Infinite …
> [ADF-2629] Fix infinite pagination

- lib/core/form/components/widgets/people/people.widget.ts
> [ADF-3274] People widget - observable fix

- lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/document-list/services/custom-resources.service.ts
> - [x] Bugfix
Please see https://issues.alfresco.com/jira/browse/ADF-3362 and …
> [ADF-3362][ADF-3361] Search on document picker with custom site list - fix

- demo-shell/src/app/components/task-list-demo/task-list-demo.component.html
- demo-shell/src/app/components/task-list-demo/task-list-demo.component.ts
- lib/process-services/task-list/components/task-list.component.ts
- lib/process-services/task-list/models/task-list.model.ts
- lib/process-services/task-list/services/tasklist.service.ts
> - [x] Bugfix
App id is required and it shouldn't.
https://issues.alfresco.com/jira/browse/ADF-3432
**What is the …
> [ADF-3432 ]Added size and page control to task list demo

- demo-shell/resources/i18n/en.json
- demo-shell/resources/i18n/es.json
- demo-shell/resources/i18n/fr.json
- demo-shell/resources/i18n/it.json
- demo-shell/resources/i18n/ja.json
- demo-shell/resources/i18n/nb.json
- demo-shell/resources/i18n/nl.json
- demo-shell/resources/i18n/pt-BR.json
- lib/core/comments/comments.component.html
- lib/core/i18n/de.json
- lib/core/i18n/en.json
- lib/core/i18n/es.json
- lib/core/i18n/fr.json
- lib/core/i18n/it.json
- lib/core/i18n/ja.json
- lib/core/i18n/nb.json
- lib/core/i18n/nl.json
- lib/core/i18n/pt-BR.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3475
**Does this PR …
> [ADF-3475] Comments - Add comment button default translation

- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-standalone.component.ts
- protractor.conf.js
- scripts/test-e2e-lib.sh
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3473 …
> [ADF-3473] Show complete button when you can't attach a form

- e2e/content-services/upload/user_permission.e2e.ts
- e2e/pages/adf/dialog/contentList.js
> - [ ] Bugfix
Fixing tests for User Permissions …
> Fixing E2E tests in User Permissions

- e2e/content-services/search_component.e2e.ts
- e2e/content-services/tag_component.e2e.ts
> - [ ] Bugfix
Including tests that should pass, despite the bugs.
**Does this PR …
> Including tests that are supposed to pass

- e2e/content-services/notifications_component.e2e.ts
- e2e/pages/adf/notificationPage.js
> - [ ] Bugfix
Providing a fix for notifications test …
> Providing a fix for notifications test

- lib/core/datatable/components/datatable/datatable-cell.component.spec.ts
- lib/core/datatable/components/datatable/date-cell.component.ts
> - [x] Bugfix
Fix formatting values for data columns.
fixes #3664
**Does this PR …
> [ADF-3494] fix formatting for date columns

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.scss
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3119
Layout broken when it's displayed in gallery mode …
> [ADF-3119] Gallery mode layout fixed for document list

- lib/core/layout/components/layout-container/layout-container.component.html
- lib/core/layout/components/layout-container/layout-container.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3493
Sidenav overflowing on top of content on Internet …
> [ADF-3493] Sidenav on top of content on IE bug fix

- e2e/pages/adf/process_services/taskFiltersPage.js
- e2e/process-services/task_filters_component.e2e.ts
> - [ ] Bugfix
Providing a fix for task list failing tests …
> [ADF-3519] Providing a fix for task list failing tests

- e2e/content-services/notifications_component.e2e.ts
- e2e/pages/adf/notificationPage.js
> - [ ] Bugfix
Fixing failing tests for Notifications component
**Does this PR …
> Fixing tests for Notifications component

- e2e/content-services/search_page_component.e2e.ts
- e2e/pages/adf/dialog/contentList.js
- e2e/pages/adf/searchResultsPage.js
> - [ ] Bugfix
Fixing failing tests and uncommenting tests for Search Page
**Does this …
> Fixing tests for Search Page

- e2e/content-services/search_multiselect.e2e.ts
> - [ ] Bugfix
Stabilising tests for Search - Multiselect …
> Stabilising tests for Search - Multiselect

- e2e/content-services/comments/comment_component.e2e.ts
- e2e/pages/adf/commentsPage.ts
> - [ ] Bugfix
Create automated tests for comments - Content Services PT2
**Does this …
> [ADF-3378] Create automated tests for comments - Content Services PT2

- e2e/pages/adf/process_services/attachFormPage.ts
- e2e/process-services/attach_form_component.e2e.ts
> - [ ] Bugfix
Updated automated tests for attach form component
**Does this PR …
> [ADF-3481] Updated automated tests for attach form component

- e2e/pages/adf/process_services/taskDetailsPage.js
- e2e/process-services/task_details_form.e2e.ts
> - [ ] Bugfix
e2e tests for Task Details - Changing/Removing Form
The second test will be failing until [ADF-3413] …
> [ADF-3237] Task Details - Create a way to change and remove a form (e2e)

- lib/process-services/app-list/icon.model.ts
- lib/process-services/task-list/components/task-filters.component.html
- lib/process-services/task-list/components/task-filters.component.spec.ts
- lib/process-services/task-list/components/task-filters.component.ts
> - [ ] Bugfix
Icons are mocked, we don't show icons coming from API calls. …
> [ADF-3397] Task filter - icons added

- lib/core/datatable/components/datatable/date-cell.component.ts
> - [x] Bugfix
take into account bindings and format changes …
> [ADF-3494] date format fix

- lib/core/form/components/widgets/dynamic-table/editors/date/date.editor.html
- lib/core/form/components/widgets/dynamic-table/editors/date/date.editor.spec.ts
- lib/core/form/components/widgets/dynamic-table/editors/date/date.editor.ts
- lib/core/form/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.html
- lib/core/form/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.spec.ts
> - [X] Bugfix
Validation was not performed correctly on date widget editor and dropdown editor …
> [ADF-3427] fixed wrong validation for dropdown widget and date widget

- e2e/content-services/unshare_file.e2e.ts
- e2e/pages/adf/contentServicesPage.js
- e2e/pages/adf/dialog/shareDialog.ts
> - [ ] Bugfix
Create automated test to cover the 'Unshared file should show 404 page' functionality.
**What is the …
> [ADF-3535] Create automated test for Unshared file

- demo-shell/src/app/components/permissions/demo-permissions.component.html
- e2e/content-services/permissions_component.e2e.ts
- e2e/pages/adf/permissionsPage.ts
> - [ ] Bugfix
Automated tests for Permissions - Search …
> [ADF-3498] Automated tests for Permissions - Search

- lib/core/assets/silent-refresh.html
> - [x] Bugfix
The adf doesn't provide a static page that can be used by the js api when the implicit flow silent …
> [ADF-3531] OAuth Implicit flow Silent login - Provide a static page that the js-api can call out of the box

- demo-shell/src/app/components/app-layout/app-layout.component.html
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/header-data/header-data.component.html
- demo-shell/src/app/components/header-data/header-data.component.ts
- demo-shell/src/app/components/header-data/header-data.service.ts
- docs/core/header.component.md
- docs/core/sidenav-layout.component.md
- lib/core/layout/components/header/header.component.html
- lib/core/layout/components/header/header.component.spec.ts
- lib/core/layout/components/header/header.component.ts
- lib/core/layout/components/layout-container/layout-container.component.html
- lib/core/layout/components/layout-container/layout-container.component.ts
- lib/core/layout/components/sidenav-layout/sidenav-layout.component.html
- lib/core/layout/components/sidenav-layout/sidenav-layout.component.spec.ts
- lib/core/layout/components/sidenav-layout/sidenav-layout.component.ts
- lib/core/layout/helpers/animations.ts
> - [ ] Bugfix
The Sidebar is always on teh left
Sidebar option to show the sidebar on …
> [ADF-3512] SidenavLayoutComponent option to show the sidebar on the right

- lib/content-services/search/components/search-trigger.directive.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3546
**Does this PR …
> [ADF-3546] Search Input - TypeError when doing a Sign out while having something typed in the search input	

- demo-shell/src/app/components/file-view/file-view.component.html
- lib/core/core.module.ts
- lib/core/viewer/components/viewer.component.ts
- lib/core/viewer/public-api.ts
- lib/core/viewer/services/view-util.service.ts
> - [ ] Bugfix
port printing support from ACA …
> [ADF-3443] basic printing support

- e2e/content-services/tag_component.e2e.ts
- e2e/pages/adf/tagPage.js
- lib/content-services/tag/services/tag.service.ts
- lib/content-services/tag/tag-list.component.html
- lib/content-services/tag/tag-list.component.scss
- lib/content-services/tag/tag-list.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3507
The Tag List Component …
> [ADF-3507] Added show more/fewer items buttons in Tag List Component

- docs/content-services/custom-resources.service.md
- docs/content-services/document-list.service.md
- docs/content-services/inherited-button.directive.md
- docs/content-services/node-permission-dialog.service.md
- docs/content-services/permission-list.component.md
- docs/content-services/tag.service.md
- docs/content-services/upload-button.component.md
- docs/content-services/upload-drag-area.component.md
- lib/content-services/document-list/services/custom-resources.service.ts
- lib/content-services/document-list/services/document-list.service.ts
- lib/content-services/permission-manager/components/inherited-button.directive.ts
- lib/content-services/permission-manager/components/permission-list/permission-list.component.ts
- lib/content-services/permission-manager/services/node-permission-dialog.service.ts
- lib/content-services/search/components/search-radio/search-radio.component.ts
- lib/content-services/search/components/search-slider/search-slider.component.ts
- lib/content-services/search/components/search-text/search-text.component.ts
- lib/content-services/tag/services/tag.service.ts
- lib/content-services/upload/components/base-upload/upload-base.ts
- lib/core/services/cookie.service.ts
> - [ ] Bugfix
Updates to doc comments and doc files.
> - [ ] Yes
> - [x] No
> [ADF-3551] Updates for doc review

- lib/core/app-config/app-config.service.ts
> - [x] Bugfix
cache busting for app config file …
> [ADF-3553] cache busting for app config

- docs/content-services/node-share.directive.md
- docs/core/app-config.service.md
- docs/core/authentication.service.md
- docs/core/datatable.component.md
- docs/core/empty-content.component.md
- docs/core/error-content.component.md
- docs/core/host-settings.component.md
- docs/core/login.component.md
- docs/core/node.service.md
- docs/core/search-configuration.service.md
- lib/content-services/directives/node-share.directive.ts
- lib/core/app-config/app-config.service.ts
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/core/form/services/node.service.ts
- lib/core/interface/search-configuration.interface.ts
- lib/core/login/components/login.component.ts
- lib/core/services/authentication.service.ts
- lib/core/services/search-configuration.service.ts
- lib/core/settings/host-settings.component.ts
- lib/core/templates/empty-content/empty-content.component.ts
- lib/core/templates/error-content/error-content.component.ts
- tools/doc/tools/toc.js
> - [] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Bugfix
Updates for doc review.
> - [ ] Yes
> - [x] No
> [ADF-3551] Doc review updates

- e2e/content-services/unshare_file.e2e.ts
- e2e/pages/adf/errorPage.js
> - [ ] Bugfix
Fix failing test for unshare file …
> [ADF-3558] Fix failing test for unshare file

- e2e/pages/adf/process_services/processListPage.js
- e2e/pages/adf/process_services/startProcessPage.js
- e2e/process-services/process_filters_component.e2e.ts
- lib/process-services/process-list/components/start-process.component.html
- lib/process-services/process-list/components/start-process.component.spec.ts
- lib/process-services/process-list/components/start-process.component.ts
Reverts Alfresco/alfresco-ng2-components#3701
> Revert "[ADF-3382] Replace dropdown with autocomplete for start a process"

- e2e/core/header_component.e2e.ts
- e2e/pages/adf/core/headerPage.ts
> - [ ] Bugfix
Create an automated test to cover sidebar position
**Does this PR …
> [ADF-3556] Create an automated test to cover sidebar position

- e2e/content-services/tag_component.e2e.ts
- e2e/pages/adf/tagPage.js
> - [ ] Bugfix
Automated test to cover hide-remove option on a tag
**Does this PR …
> [ADF-3548] Create an automated test to cover hide-remove option on a tag

- demo-shell/src/app/components/task-list-demo/task-list-demo.component.html
- demo-shell/src/app/components/task-list-demo/task-list-demo.component.scss
- demo-shell/src/app/components/task-list-demo/task-list-demo.component.ts
- docs/process-services/task-list.component.md
- lib/core/pagination/pagination.component.spec.ts
- lib/process-services/task-list/components/task-list.component.spec.ts
- lib/process-services/task-list/components/task-list.component.ts
- lib/process-services/task-list/models/filter.model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3438
As a user, I want to have fields where I can change …
> [ADF-3438] Task List Demo - created date filter and pagination

- e2e/pages/adf/process_services/processFiltersPage.js
- e2e/process-services/processlist_pagination.e2e.ts
> - [ ] Bugfix
Automated tests for Process List - Sorting after changing 'Items per page' …
> [ADF-2996] Automated test for Process List - Sorting + fixing some details

- e2e/pages/adf/process_services/dialog/startTaskDialog.js
- e2e/pages/adf/process_services/taskDetailsPage.js
- e2e/pages/adf/process_services/taskFiltersPage.js
- e2e/pages/adf/process_services/tasksListPage.js
- e2e/process-services/task_filters_component.e2e.ts
- e2e/process-services/task_filters_sorting.e2e.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3335
Added automation test …
> [ADF-3335] Added automation tests for task filter sorting

- demo-shell/src/app/components/process-service/process-service.component.html
- lib/process-services/process-list/components/process-filters.component.html
- lib/process-services/process-list/components/process-filters.component.spec.ts
- lib/process-services/process-list/components/process-filters.component.ts
- lib/process-services/task-list/components/task-filters.component.spec.ts
> - [ ] Bugfix
Icons are mocked, we don't show icons coming from API calls. …
> [ADF-3415] Process filter - icons added

- e2e/content-services/unshare_file.e2e.ts
- e2e/pages/adf/dialog/shareDialog.ts
> - [ ] Bugfix
Fixing failing test for unshare file …
> [ADF-3558] Fixing failing test for unshare file

- lib/core/viewer/components/txtViewer.component.scss
- lib/core/viewer/components/viewer.component.scss
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
fixes for text viewer:
- proper text alignment
- vertical scrolling for large files …
> [ADF-3357] text viewer fixes

- e2e/content-services/permissions_component.e2e.ts
- e2e/content-services/unshare_file.e2e.ts
- e2e/pages/adf/core/headerPage.ts
- e2e/pages/adf/dialog/shareDialog.ts
- e2e/pages/adf/permissionsPage.ts
- package.json
- scripts/lint.sh
> - [ ] Bugfix
Create an automated test to cover 'Add group' on permissions
**Does …
> [ADF-3560] Create an automated test to cover 'Add group' on permissions

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.scss
- demo-shell/src/app/components/process-service/process-service.component.ts
- e2e/pages/adf/process_services/appNavigationBarPage.js
- e2e/pages/adf/process_services/dialog/taskDetailsToggles.js
- e2e/process-services/start_task_custom_app.e2e.ts
- e2e/process-services/start_task_task_app.e2e.ts
- lib/process-services/process-list/components/process-filters.component.spec.ts
- lib/process-services/process-list/components/process-filters.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3422
New tab named …
> [ADF-3422] Process Services - Create settings tab

- lib/core/form/components/widgets/people/people.widget.html
- lib/core/form/components/widgets/people/people.widget.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3562
People widget was using ngModel and a form control at …
> [ADF-3562] People Widget reactive form

- e2e/pages/adf/process_services/taskFiltersPage.js
- e2e/process-services/task_filters_component.e2e.ts
- e2e/process-services/task_filters_sorting.e2e.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3566
Clean up of code. …
> [ADF-3566] Task filters automation tests cleanup

- protractor.conf.js
> [ADF-3505] Create report for any  E2E retry

- demo-shell/src/app/components/task-list-demo/task-list-demo.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3438
Pagination issues in Task list demo page
**What is …
> [ADF-3438] Bugs in Task List Demo Component fixed

- .gitignore
- demo-shell/src/app/components/file-view/file-view.component.html
- demo-shell/src/app/components/file-view/file-view.component.ts
- docs/core/viewer.component.md
- e2e/content-services/tag_component.e2e.ts
- e2e/core/viewer_properties.e2e.ts
- e2e/pages/adf/versionManagerPage.ts
- e2e/pages/adf/viewerPage.js
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.scss
- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
- lib/process-services/task-list/components/task-details.component.ts
left sidebar
fix height width no overlay viewer
> - [ ] Bugfix
new viewer properties test
left sidebar
fix height width no overlay viewer …
> [ADF-3332][ADF-3352] Add property e2e test and leftsidebar viewer 

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/extensions/package.json
- lib/insights/package.json
- lib/process-services/package.json
- package.json
Update ADF packages version 2.6.0-beta6
> Update ADF packages version 2.6.0-beta6

- demo-shell/src/app/components/task-list-demo/task-list-demo.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3438
Pages started counting from zero as an array would do …
>  [ADF-3438] Page input fixed in Task List Demo

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/task-list-demo/task-list-demo.component.html
- demo-shell/src/app/components/task-list-demo/task-list-demo.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3573
Pagination displays NaN when page size is changed …
> [ADF-3573] Task list pagination on Task List Demo page fix

- e2e/content-services/tag_component.e2e.ts
- e2e/pages/adf/tagPage.js
> - [ ] Bugfix
Create automated test for Show more/ less button on Tag component. …
> [ADF-3594] Create automated test for Show more/less button on Tag page

- e2e/content-services/search/search_filters.e2e.ts
- e2e/pages/adf/searchFiltersPage.js
> - [ ] Bugfix
Automated test for Show More/Less button in Search Filters
**Does this …
> [ADF-3563] Automated test for Show More - Less button in Search Filters

- demo-shell/src/app/app.component.ts
> - [x] Bugfix
app-level workaround for i18n issue caused by 3rd party lib (ngx-translate/core)
refs #3796 
**What is …
> [ADF-3575] i18n workaround for non-supported langs

- lib/core/layout/components/header/header.component.html
- lib/core/layout/components/header/header.component.scss
> - [x] Bugfix
Please check https://issues.alfresco.com/jira/browse/ADF-3491 …
> [ADF-3491] Logo link should be also on logo text

- .travis.yml
- e2e/pages/adf/contentServicesPage.js
- e2e/pages/adf/core/toggleState.js
- e2e/pages/adf/process_services/dialog/appSettingsToggles.js
- e2e/pages/adf/process_services/taskDetailsPage.js
- e2e/pages/adf/process_services/tasksPage.js
- e2e/pages/adf/process_services/widgets/Widget.js
- e2e/process-services/attach-file-widget.e2e.ts
- e2e/process-services/attach_form_component.e2e.ts
- e2e/process-services/checklist_component.e2e.ts
- e2e/process-services/comment_component_tasks.e2e.ts
- e2e/process-services/form_widgets_component.e2e.ts
- e2e/process-services/pagination_tasklist_addingTasks.e2e.ts
- e2e/process-services/people_component.e2e.ts
- e2e/process-services/sort_tasklist_pagination.e2e.ts
- e2e/process-services/standalone_task.e2e.ts
- e2e/process-services/start_task_custom_app.e2e.ts
- e2e/process-services/start_task_task_app.e2e.ts
- e2e/process-services/task-audit.e2e.ts
- e2e/process-services/task_attachmentList_actionMenu.e2e.ts
- e2e/process-services/task_filters_component.e2e.ts
- e2e/process-services/task_list_pagination.e2e.ts
- lib/process-services/task-list/components/task-details.component.html
> [no-issue] clean e2e test PS

- lib/process-services/task-list/components/start-task.component.html
- lib/process-services/task-list/components/start-task.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3009
Error persists even on valid dates when using …
>  [ADF-3009] Start task with due date error fix

- e2e/core/header_component.e2e.ts
- e2e/pages/adf/navigationBarPage.js
> [ADF-3602]Add a test for logo text

- e2e/pages/adf/process_services/startProcessPage.js
- e2e/process-services/start_process_component.e2e.ts
- e2e/util/resources.js
- lib/process-services/process-list/components/start-process.component.html
> [ADF-3596]Create automated tests for start process

- demo-shell/src/app/components/form/form.component.html
- demo-shell/src/app/components/form/form.component.scss
- demo-shell/src/app/components/form/form.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3607
JSON editor added to …
> [ADF-3607] JSON Upload File & Editor in Form Page

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/extensions/package.json
- lib/insights/package.json
- lib/process-services/package.json
- package.json
Update ADF packages version 2.6.0-beta7
> Update ADF packages version 2.6.0-beta7

- docs/README.md
- docs/content-services/README.md
- docs/core/README.md
- docs/core/datatable.component.md
- docs/core/header.component.md
- docs/core/login-dialog-panel.component.md
- docs/core/login-dialog.component.md
- docs/core/login-dialog.service.md
- docs/release-notes/RelNote161.md
- docs/release-notes/RelNote170.md
- docs/release-notes/RelNote180.md
- docs/release-notes/RelNote190.md
- docs/release-notes/RelNote200.md
- docs/release-notes/RelNote210.md
- docs/release-notes/RelNote220.md
- docs/release-notes/RelNote230.md
- docs/release-notes/RelNote240.md
- docs/release-notes/RelNote250.md
- docs/versionIndex.md
- tools/doc/doctool.config.json
- tools/doc/tools/toc.js
> - [ ] Bugfix
Added docs for Login Dialog component/service. Fixed broken links and made minor changes to table of contents tool to fix link problems with auto-generated page anchors. …
> [ADF-3551] Doc fixes for release

- docs/core/viewer.component.md
> - [ ] Bugfix
Added docs for Viewer printing feature. The allowPrint property and the print event were already documented, so I've just added a bit of explanation in its own section. Let me know if more explanation is required.
**Does …
> [ADF-3564] Added brief docs for viewer printing feature

- e2e/pages/adf/process_services/startProcessPage.js
- e2e/process-services/start_process_component.e2e.ts
- lib/process-services/process-list/components/start-process.component.spec.ts
- lib/process-services/process-list/components/start-process.component.ts
> - [x] Bugfix
No process is selected by default
https://issues.alfresco.com/jira/browse/ADF-3639 …
> [ADF-3639] Fix default selected process at Start Process Component

- lib/core/form/components/form.component.html
- lib/core/form/components/start-form.component.html
- lib/process-services/process-list/components/start-process.component.html
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.spec.ts
> - [x] Bugfix
fix readonly form in complete task …
> [ADF-3528] fix readonly form in complete task

- lib/content-services/karma.conf.js
- lib/core/core.module.ts
- lib/core/karma.conf.js
- lib/core/mock/translation.service.mock.ts
- lib/core/services/translate-loader.service.ts
- lib/core/services/translation.service.ts
- lib/process-services/attachment/process-attachment-list.component.spec.ts
- lib/process-services/attachment/task-attachment-list.component.spec.ts
- lib/process-services/karma.conf.js
- lib/process-services/process-list/components/process-list.component.spec.ts
- lib/process-services/task-list/components/task-list.component.spec.ts
- lib/process-services/task-list/components/task-standalone.component.spec.ts
> - [x] Bugfix
fallback to the default language if app fails to load translation file …
> [ADF-3630] fix i18n fallback behaviour

- lib/core/form/components/widgets/people/people.widget.html
- lib/core/form/components/widgets/people/people.widget.spec.ts
- lib/core/form/components/widgets/people/people.widget.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3629
Involved user is not displayed on People Widget …
> [ADF-3629] Fix involved user bug on People Widget

- lib/core/services/translate-loader.service.ts
> - [x] Bugfix
add 3 retries to address the latency and request failures
**Does this …
> [ADF-3630] add 3 retries for language file fetch

- demo-shell/resources/i18n/ru.json
- lib/core/services/translate-loader.service.ts
> - [x] Bugfix
fix translation resolving and error handling
(previously forkJoine was failing on first exception …
> [ADF-3654] translation fixes

- demo-shell/src/app/components/files/files.component.html
- lib/content-services/content-node-share/content-node-share.dialog.ts
> - [ ] Bugfix
> - [x Refactoring (no functional changes, no api changes)
https://issues.alfresco.com/jira/browse/ADF-3530
**Does this PR …
> [ADF-3530] Share file dialog - expiration date update

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/about/about.module.ts
- demo-shell/src/app/components/breadcrumb-demo/breadcrumb-demo.module.ts
- demo-shell/src/app/components/card-view/card-view.module.ts
- demo-shell/src/app/components/config-editor/config-editor.module.ts
- demo-shell/src/app/components/content-node-selector/content-node-selector.module.ts
- demo-shell/src/app/components/datatable/datatable.module.ts
- demo-shell/src/app/components/files/custom-sources.module.ts
- demo-shell/src/app/components/header-data/header-data.module.ts
- demo-shell/src/app/components/header-data/header-data.service.ts
- demo-shell/src/app/components/notifications/notifications.module.ts
- demo-shell/src/app/components/process-list-demo/process-list.module.ts
- demo-shell/src/app/components/settings/settings.module.ts
- demo-shell/src/app/components/social/social.module.ts
- demo-shell/src/app/components/tag/tag.module.ts
- demo-shell/src/app/components/task-list-demo/task-list.module.ts
- demo-shell/src/app/components/trashcan/trashcan.module.ts
- demo-shell/src/app/components/webscript/webscript.module.ts
> - [ ] Bugfix
Add lazy loading support for various features in demo shell
**Does this …
> lazy loading support for demo shell

- demo-shell/resources/i18n/en.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3585
Missing translation …
> [ADF-3585] Add translation to minValue error on Task List Demo Page

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/process-list-demo/process-list-demo.component.html
- demo-shell/src/app/components/process-list-demo/process-list-demo.component.scss
- demo-shell/src/app/components/process-list-demo/process-list-demo.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3586
https://issues.alfresco.com/jira/browse/ADF-3588 …
> [ADF-3586] Refactor Process List page and fix query bugs

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/extensions/package.json
- lib/insights/package.json
- lib/process-services/package.json
- package.json
Update ADF packages version 2.7.0-beta2
> Update ADF packages version 2.7.0-beta2

- lib/content-services/content-node-share/content-node-share.dialog.spec.ts
- lib/content-services/karma.conf.js
- lib/core/karma.conf.js
- lib/core/viewer/components/mediaPlayer.component.spec.ts
- lib/core/viewer/components/pdfViewer.component.spec.ts
- lib/core/viewer/components/viewer.component.spec.ts
- lib/insights/karma.conf.js
- lib/process-services/attachment/task-attachment-list.component.spec.ts
- lib/process-services/karma.conf.js
> - [ ] Bugfix
reintroduce viewer skipped test …
> [no-issue] reintroduce viewer test

- e2e/pages/adf/process_services/formPage.ts
- e2e/process-services/form_component.e2e.ts
> - [ ] Bugfix
Automated test for start task date error message
**Does this PR …
> [ADF-3616] Automated test for start task date error message

- ALFRESCOCORS.md
- BROWSER-SUPPORT.md
- CONTRIBUTING.md
- INTRODUCTION.md
- PREREQUISITES.md
- README.md
> - [ ] Bugfix
Reviewed text, links and information for the README.md file and its friends in the root folder. Apparently, the "Deploy to AWS" button was only ever an experiment and is now well out of date, so I have just removed that …
> [ADF-3682] Review of main README and other information pages

- lib/process-services/i18n/en.json
- lib/process-services/i18n/it.json
- lib/process-services/task-list/components/checklist.component.html
- lib/process-services/task-list/components/checklist.component.spec.ts
> - [X] Bugfix
Checklist labels are not translated
Checklist labels are translated …
> [ADF 3635] Added translation label to checklist dialog

- lib/content-services/content-node-selector/content-node-dialog.service.spec.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/mock/document-list.service.mock.ts
- lib/content-services/search/components/search-control.component.ts
- lib/content-services/search/components/search-trigger.directive.ts
- lib/core/form/components/form.component.spec.ts
- lib/core/form/components/widgets/dropdown/dropdown.widget.spec.ts
- lib/core/form/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.spec.ts
- lib/core/form/components/widgets/functional-group/functional-group.widget.spec.ts
- lib/core/form/components/widgets/people/people.widget.spec.ts
- lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.spec.ts
- lib/core/form/components/widgets/typeahead/typeahead.widget.spec.ts
- lib/core/form/services/ecm-model.service.spec.ts
- lib/core/form/services/ecm-model.service.ts
- lib/core/form/services/form.service.ts
- lib/core/pagination/infinite-pagination.component.ts
- lib/core/services/authentication.service.ts
- lib/core/services/renditions.service.ts
- lib/core/services/translate-loader.service.ts
- lib/insights/analytics-process/services/analytics.service.ts
- lib/process-services/content-widget/attach-file-widget-dialog-component.interface.ts
- lib/process-services/process-list/services/process-filter.service.ts
- lib/process-services/task-list/components/start-task.component.spec.ts
- lib/process-services/task-list/services/task-filter.service.ts
- lib/tslint.json
- package-lock.json
- package.json
- tslint.json
> - [ ] Bugfix
remove rxjs-compat layer
fix issues with old rxjs usage
**Does this PR …
> [ADF-3593] remove rxjs-compat layer

- demo-shell/resources/i18n/en.json
- demo-shell/src/app.config.json
- e2e/pages/adf/searchFiltersPage.ts
- lib/content-services/i18n/en.json
- lib/content-services/search/components/search-filter/models/response-facet-query-list.model.ts
- lib/content-services/search/components/search-filter/search-filter.component.html
- lib/content-services/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3668
fixes …
> [ADF-3668] Search filter buckets are set to 0 after any search filtering

- e2e/content-services/search/search_page_component.e2e.ts
> [ADF-3688]Add test for search page

- lib/process-services/task-list/components/task-header.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3689
https://issues.alfresco.com/jira/browse/ADF-3690 …
> [ADF-3676] fix task header component duplicates

- e2e/content-services/lock_file.e2e.ts
- e2e/pages/adf/dialog/contentList.js
- e2e/pages/adf/lockFilePage.ts
> - [ ] Bugfix
Automated Test For Lock component …
> [ADF-3396] Create automated Test For Lock component

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/files/metadata-dialog-adapter.component.html
- demo-shell/src/app/components/files/metadata-dialog-adapter.component.ts
- lib/content-services/content-metadata/interfaces/organised-property-group.interface.ts
- lib/content-services/content-metadata/services/content-metadata.service.ts
- lib/content-services/content-metadata/services/property-groups-translator.service.ts
> - [ ] Bugfix
Create a custom type, don't define any title
Add a property to the custom type, don't define any …
> [ADF-3609 ] fallback for metadata and undefined value check

- e2e/models/APS/TaskModel.js
- e2e/pages/adf/process_services/taskDetailsPage.ts
- e2e/process-services/start_task_custom_app.e2e.ts
- e2e/process-services/start_task_task_app.e2e.ts
- e2e/process-services/task_details.e2e.ts
- e2e/util/constants.js
> [ADF-3692] Add task details tests

- e2e/process-services/apps-section.e2e.ts
- e2e/util/constants.js
- e2e/util/resources.js
- package-lock.json
- package.json
> [ADF-3017]Update app

- lib/core/form/components/form.component.spec.ts
- lib/core/form/components/form.component.ts
- lib/core/form/components/widgets/core/form-outcome.model.ts
- lib/core/form/components/widgets/core/form.model.ts
- lib/core/i18n/de.json
- lib/core/i18n/en.json
- lib/core/i18n/es.json
- lib/core/i18n/fr.json
- lib/core/i18n/it.json
- lib/core/i18n/ja.json
- lib/core/i18n/nb.json
- lib/core/i18n/nl.json
- lib/core/i18n/pt-BR.json
- lib/core/i18n/ru.json
- lib/core/i18n/zh-CN.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3561
Action buttons on forms are hardcoded se they cannot …
> [ADF-3561] Fix form action buttons translation

- e2e/content-services/search/search_filters.e2e.ts
- e2e/pages/adf/dialog/contentList.js
- e2e/pages/adf/paginationPage.js
- e2e/pages/adf/searchFiltersPage.ts
> - [ ] Bugfix
Automated test to cover the search filter buckets scenario
**Does this …
> [ADF-3696] Create an automated test to cover the search filter buckets scenario

- lib/process-services/task-list/components/task-list.component.spec.ts
- lib/process-services/task-list/components/task-list.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3571
https://issues.alfresco.com/jira/browse/ADF-3578 …
> [ADF-3571] Fix Dates on Task List Component

- lib/core/form/components/widgets/date-time/date-time.widget.scss
- lib/core/form/components/widgets/date/date.widget.scss
- lib/core/form/components/widgets/form.scss
- scripts/download-build-in-cs.js
> - [x] Bugfix
Fix deploy PR relative path …
> [no-issue] Fix deploy PR

- e2e/pages/adf/process_services/startProcessPage.js
- e2e/process-services/start_process_component.e2e.ts
> - [ ] Bugfix
Automated test for start process placeholder …
> [ADF-3700] Create an automated test to cover the process placeholder

- e2e/process-services/widgets/amount_widget.e2e.ts
- e2e/process-services/widgets/attach_folder_widget.e2e.ts
- e2e/process-services/widgets/checkbox_widget.e2e.ts
- e2e/process-services/widgets/date_time_widget.e2e.ts
- e2e/process-services/widgets/date_widget.e2e.ts
- e2e/process-services/widgets/dropdown_widget.e2e.ts
- e2e/process-services/widgets/dynamic_table_widget.e2e.ts
- e2e/process-services/widgets/header_widget.e2e.ts
- e2e/process-services/widgets/hyperlink_widget.e2e.ts
- e2e/process-services/widgets/multi_line_widget.e2e.ts
- e2e/process-services/widgets/number_widget.e2e.ts
- e2e/process-services/widgets/people_widget.e2e.ts
- e2e/process-services/widgets/radio_buttons_widget.e2e.ts
- e2e/process-services/widgets/text_widget.e2e.ts
- e2e/util/resources.js
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3671
Names not matching coding style  …
> [ADF-3671] Rename Automation Tests

- e2e/pages/adf/process_services/analyticsPage.js
> [ADF-3732]Fix analytics test

- protractor.conf.js
> [ADF-3665]Fix the HTML report

- e2e/content-services/share-file/share_file.e2e.ts
- e2e/pages/adf/dialog/shareDialog.ts
- lib/content-services/content-node-share/content-node-share.dialog.spec.ts
> - [ ] Bugfix
> - x ] Build related changes
Share dialog e2e test are failing if is the last day of the month due how we calculate tomorrow
**What …
> [no-issue] fix share dialog test for scenario of last day of the month

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/extensions/package.json
- lib/insights/package.json
- lib/process-services-cloud/package.json
- lib/process-services/package.json
- package.json
Update ADF packages version 2.7.0-beta5
> Update ADF packages version 2.7.0-beta5

- e2e/content-services/search/components/search-text.e2e.ts
- e2e/content-services/search/search.config.json
- e2e/content-services/search/search_filters.e2e.ts
- e2e/content-services/search/search_multiselect.e2e.ts
- e2e/models/ACS/folderModel.js
- e2e/pages/adf/configEditorPage.ts
- e2e/pages/adf/content_services/search/components/search-checkList.ts
- e2e/pages/adf/content_services/search/components/search-text.ts
- e2e/pages/adf/content_services/search/search-categories.ts
- e2e/pages/adf/searchFiltersPage.ts
- e2e/pages/adf/searchResultsPage.ts
- lib/content-services/search/components/search-check-list/search-check-list.component.html
> [ADF-3715]Refactor search filters page

- e2e/core/datatable/data-table-component.e2e.ts
- e2e/pages/adf/dataTablePage.js
- e2e/pages/adf/process_services/tasksListPage.js
- e2e/pages/adf/process_services/tasksPage.ts
- e2e/process-services/Task_details_no_form.e2e.ts
- e2e/process-services/attach-file-widget.e2e.ts
- e2e/process-services/attach_form_component.e2e.ts
- e2e/process-services/checklist_component.e2e.ts
- e2e/process-services/comment_component_tasks.e2e.ts
- e2e/process-services/form_widgets_component.e2e.ts
- e2e/process-services/pagination_tasklist_addingTasks.e2e.ts
- e2e/process-services/people_component.e2e.ts
- e2e/process-services/sort_tasklist_pagination.e2e.ts
- e2e/process-services/standalone_task.e2e.ts
- e2e/process-services/start_task_custom_app.e2e.ts
- e2e/process-services/start_task_task_app.e2e.ts
- e2e/process-services/task-audit.e2e.ts
- e2e/process-services/task_attachmentList_actionMenu.e2e.ts
- e2e/process-services/task_details.e2e.ts
- e2e/process-services/task_details_form.e2e.ts
- e2e/process-services/task_filters_component.e2e.ts
- e2e/process-services/task_filters_sorting.e2e.ts
- e2e/process-services/task_list_pagination.e2e.ts
> Refactor tasksListPage

- demo-shell/src/app/components/task-list-demo/task-list-demo.component.ts
- lib/process-services/task-list/components/task-list.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3578
DueAfter Filters time was 00:00:000.000 so when the …
> [ADF-3578] Fix DueAfter Filter for Task List

- docs/core/language-menu.component.md
- docs/user-guide/internationalization.md
> - [ ] Bugfix
Added docs about the locale language selection process.
> - [ ] Yes
> - [x] No
> [ADF-3731] Added more detail about locale language selection

- docs/content-services/node-share.directive.md
- docs/content-services/tree-view.component.md
- docs/core/login-dialog-panel.component.md
- docs/process-services-cloud/process-list-cloud.component.md
- lib/content-services/content-node-share/content-node-share.directive.ts
- lib/content-services/tree-view/components/tree-view.component.ts
- lib/core/login/components/login-dialog-panel.component.ts
- lib/process-services-cloud/src/lib/process-list-cloud/components/process-list-cloud.component.ts
> - [ ] Bugfix
Reviewed new component docs and updated JSDoc comments.
> - [ ] Yes
> - [x] No
> [ADF-3745] Doc review updates

- e2e/content-services/upload/user_permission.e2e.ts
- tslint.json
> [no-issue] add fit in the banned word

- .travis.yml
- e2e/core/login/login-sso/login_sso.e2e.ts
- e2e/pages/adf/loginApsPage.ts
- e2e/pages/adf/settingsPage.ts
- e2e/test.config.js
- scripts/test-e2e-lib.sh
> [ADF-3739] E2E test - login with SSO

- e2e/pages/adf/process_services/processDetailsPage.js
- e2e/pages/adf/process_services/processListPage.ts
- e2e/process-services/empty_process_list_component.e2e.ts
- e2e/util/resources.js
> [ADF-3756]Refactor process list component

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.component.ts
> - [ ] Bugfix
When the disk is full a clear error in test will be displayed
**Does …
> [no-issue] add clear error in test when disk quota is reached

- .travis.yml
- scripts/smart-build.sh
> Travis - Exit 1 in case one on the build libs fails

- docs/content-services/content-action.component.md
- docs/content-services/file-uploading-dialog.component.md
- docs/content-services/folder-create.directive.md
- docs/content-services/inherited-button.directive.md
- docs/content-services/node-download.directive.md
- docs/content-services/node-lock.directive.md
- docs/content-services/permission-list.component.md
- docs/core/card-item-types.service.md
- docs/core/context-menu.directive.md
- docs/core/form-field.component.md
- docs/core/form-list.component.md
- docs/core/form-rendering.service.md
- docs/core/header.component.md
- docs/core/highlight.directive.md
- docs/core/node-delete.directive.md
- docs/core/node-permission.directive.md
- docs/core/node.service.md
- docs/core/pagination.component.md
- docs/core/sidebar-action-menu.component.md
- docs/core/sidenav-layout.component.md
- docs/core/text-mask.component.md
- docs/core/upload.directive.md
- docs/core/user-preferences.service.md
- docs/process-services/attach-form.component.md
- lib/core/layout/components/header/header.component.ts
- lib/core/services/dynamic-component-mapper.service.ts
- tools/doc/doctool.config.json
> - [ ] Bugfix
More doc review updates.
> - [ ] Yes
> - [x] No
> [ADF-3745] Updates for doc review (20-11-2018)
