ng2-components/ng2-alfresco-viewer/src/pdfViewer.component.css
=> Fix overlap scrollbar

scripts/npm-clean.sh, scripts/npm-link-demo-shell.sh, scripts/npm-publish.sh, scripts/start.sh
updated all scripts except update-version.sh to be able to
run from anywhere. Previously you had to be in the scripts
directory to run them.
fixes #361
=> scripts can be run from anywhere

ng2-components/ng2-alfresco-login/i18n/en.json, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html
=> Add alt text to login page logo

demo-shell-ng2/app/components/login/login-demo.component.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationService.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationService.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoSettingsService.service.ts, ng2-components/ng2-alfresco-upload/src/assets/AlfrescoSettingsService.service.mock.ts
=> Moved the providers inside AlfrescoSetting

ng2-components/ng2-alfresco-datatable/src/components/datatable.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable.component.ts, ng2-components/ng2-alfresco-documentlist/i18n/en.json, ng2-components/ng2-alfresco-documentlist/src/components/content-action-list.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-action.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-column-list.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-column.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list-breadcrumb.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.ts
=> Add alt text for file and folder icons in documentlist

ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationECM.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationService.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoContentService.service.ts
=> Fix ContentService

ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationService.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationService.service.ts
=> Fix logout problem

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
Add data-automation-id for action menu
=> Add data-automation-id to action menu

ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html
=> Fix tabindex

ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
=> Emit event when the folder is created

ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
=> Fix undo problem

ng2-components/ng2-activiti-form/src/components/activiti-form.component.html, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/hyperlink/hyperlink.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/hyperlink/hyperlink.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/hyperlink/hyperlink.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/index.ts, ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/number/number.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/widget.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/widget.model.ts
Adds following widgets to the Form renderer:
- Radio Buttons
- Hyperlink
- Header
- Dropdown
=> Activiti Form widgets

ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.html
Needed to add some improvement for UploaderComponent test
=> Added new data-automation-id to uploader

demo-shell-ng2/app/components/files/files.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-text/display-text.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/display-text/display-text.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/display-text/display-text.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/index.ts, ng2-components/ng2-activiti-form/src/components/widgets/widget.model.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationBPM.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationService.service.spec.ts, ng2-components/ng2-alfresco-documentlist/src/models/content-action.model.ts
Form
- Remove hardcoded admin:admin credentials
- Display Value widget
- Display Text widget
- improvements for rendering unset task names
Core
- Fix BPM authentication ticket
Demo app
- Document List shows Activiti actions for the folders as well
=> Form and Document List enhancements

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.ts, demo-shell-ng2/app/app.routes.ts, demo-shell-ng2/app/components/index.ts, demo-shell-ng2/app/components/login/login-demo.component.ts, demo-shell-ng2/app/components/search/search-bar.component.ts, demo-shell-ng2/systemjs.config.js, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html
Migrate to latest stable angular/router component instead of the deprecated angular/router-deprecated one.
=> Migrate to angular/router component

demo-shell-ng2/package.json
this will make it compatible with the docker container.
Tested locally and worked as a charm!
=> instructing wsrv to start with 0.0.0.0 instead that with localhost

demo-shell-ng2/app/app.routes.ts, demo-shell-ng2/app/components/activiti/form-viewer.component.css, demo-shell-ng2/app/components/activiti/form-viewer.component.html, demo-shell-ng2/app/components/activiti/form-viewer.component.ts, demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts, demo-shell-ng2/app/components/index.ts, ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.ts, ng2-components/ng2-alfresco-core/src/components/material/index.ts, ng2-components/ng2-alfresco-core/src/components/material/mdl-tabs.directive.ts
- New mdl-tabs directive that covers major MDL tabs issues with dynamic content
- Simple Form Viewer component and separate route to view Activiti Tasks
- Simple redirection to Form Viewer from the Document List context actions
=> Tabs widget enhancements, Form Viewer route

ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationECM.service.ts
=> fix the function call

ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationBPM.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationBase.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationECM.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthenticationService.service.ts
=> The alfrescoSetting property is present twice

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.ts, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts, ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
=> Fix error dialog not initialized

ng2-components/ng2-activiti-tasklist/README.md
=> Add documentation about applicationId and processId

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.ts
=> OnDestroy call unsubscribe

ng2-components/ng2-alfresco-documentlist/src/components/document-list.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.ts
- reduce amount of unnecessary data reloads
=> #581 Document list calls 3 times same endpoint

ng2-components/ng2-activiti-form/karma.conf.js, ng2-components/ng2-activiti-form/package.json, ng2-components/ng2-activiti-form/src/components/activiti-form.component.html, ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/.gitignore, ng2-components/ng2-activiti-form/src/components/widgets/checkbox/checkbox.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/number/number.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/widget.component.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/widget.component.ts, ng2-components/ng2-activiti-form/src/models/task-process-variable.model.ts, ng2-components/ng2-activiti-form/src/models/widget-visibility.model.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.spec.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.ts
=> Dev valbano visibility 545

ng2-components/ng2-alfresco-documentlist/README.md, ng2-components/ng2-alfresco-documentlist/index.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.ts, ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts, ng2-components/ng2-alfresco-documentlist/src/models/document-library.model.ts
- expose ‘properties’ for the Node model
- Row filtering support for Document List (refs #522)
- Custom image resolver for Document List (refs #532)
=> DocumentList component improvements

ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.html
=> Changed label to person

ng2-components/ng2-alfresco-login/README.md, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.css, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts
- support for changing logo image
- support for changing background css
=> #534 login customisation support

ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-types.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/index.ts, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.ts
=> Upload widget for Activiti Form

demo-shell-ng2/app/components/files/files.component.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.html
- fixes #601
- introduces support for fallback thumbnails (DataTable, DocumentList)
=> #601 support for fallback thumbnails

ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.ts
=> Add withCredentials flag to upload file XHR request

ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.html
=> Add missing label in dropdown widget

ng2-components/ng2-activiti-tasklist/demo/src/main.ts, ng2-components/ng2-activiti-tasklist/demo/systemjs.config.js
=> Fix activiti tasklist demo

ng2-components/ng2-alfresco-documentlist/src/components/document-list.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.ts
=> #657 Enforce single-click navigation for mobile browsers

demo-shell-ng2/i18n/en.json, ng2-components/ng2-alfresco-documentlist/karma.conf.js, ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.spec.ts, ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
=> #429 preserve sorting on navigation and paging

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
=> refresh tasklist after complete task

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts, ng2-components/ng2-activiti-tasklist/src/models/filter.model.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
=> Activiti Task List does not show all entries

demo-shell-ng2/app/components/login/login-demo.component.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.spec.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts, ng2-components/ng2-alfresco-login/src/i18n/en.json, ng2-components/ng2-alfresco-login/src/i18n/it.json
=> Fix login providers

demo-shell-ng2/app/components/datatable/datatable-demo.component.html
=> Fix contrast for wave

demo-shell-ng2/app/components/files/files.component.html
=> Added label to filter upload

ng2-components/ng2-activiti-form/src/components/activiti-form.component.css, ng2-components/ng2-activiti-form/src/components/activiti-form.component.html, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-types.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/index.ts, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
- basic Typeahead widget
- 100% code/block unit test coverage for typeahead widget
=> Support for Typeahead widget within Activiti form #633

ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.ts
removed custom http data requests with the corresponding activiti REST
api
=> #689 greatly reduced dropdown code

demo-shell-ng2/app/components/login/login-demo.component.html, demo-shell-ng2/app/components/login/login-demo.component.ts, ng2-components/ng2-alfresco-login/README.md, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts, ng2-components/ng2-alfresco-login/src/models/form-outcome-event.model.ts, ng2-components/ng2-alfresco-login/src/models/form-submit-event.model.ts
=> Extend the validation of the login form

demo-shell-ng2/app/app.component.html
=> Added tab index to language and login menu options

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, ng2-components/ng2-activiti-processlist/README.md, ng2-components/ng2-activiti-processlist/src/components/activiti-comments.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-details.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.ts
- Renamed components to process-instance-*
- Renamed ID parameter to processInstanceId
Refs #573
=> New README for process instance list components

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.html, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.html
=> Added tab and title to upload list elements

ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-types.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/group-user.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/group.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/functional-group/functional-group.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/functional-group/functional-group.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/functional-group/functional-group.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/functional-group/functional-group.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/index.ts, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
- Support for Group of People widget within Activiti form #636 
- Support for People widget within Activiti form #635
=> People and Group of People widgets

demo-shell-ng2/app/components/login/login-demo.component.css, demo-shell-ng2/app/components/login/login-demo.component.html, demo-shell-ng2/app/components/login/login-demo.component.ts, ng2-components/ng2-alfresco-login/README.md, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts
=> Give the possibility to customize the login form validation rules

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts
=> Add first task selection on filter change

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.css, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
Fix for selection in Safari and Firefox.
=> Fix for selection in firefox and Safari

ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
fixes #724 
due to some reason Activiti stores/serializes null as a “null” string
rather than value for a ‘formKey’ property; added checks for this case
=> Task without a Form is handled incorrectly

ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.ts
=> Fix wrong reference to search term

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/index.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts, ng2-components/ng2-activiti-tasklist/src/models/filter.model.ts, ng2-components/ng2-activiti-tasklist/src/models/task-details.model.ts, ng2-components/ng2-activiti-tasklist/src/models/user.model.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
=> Add default tasks filters

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-apps-grid.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
=> Add LayoutType property to render List/Grid of the activiti apps

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.ts
=> Select the first filter as default

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
=> #747 fix readonly mode for rest radio buttons

demo-shell-ng2/app/components/activiti/activiti-demo.component.html
=> Shows Apps in tab section

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.ts
=> Fix special characters

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.html
=> Remove Date pipe

demo-shell-ng2/app/app.component.ts
=> Ensure logout link still redirects to login page after session time-out

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.css
=> Filter the tasks/processes by Date instead of Name

ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.ts
=> add the default Task App

ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.ts
=> Fix bug undefined filname

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.ts
=> FilterList is shown twice

README.md, ng2-components/README.md, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.spec.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.ts, scripts/npm-link-demo-shell.sh
#771 
Also fixed an error for upload.widget.ts
=> Dev valbano fix visibility tests

demo-shell-ng2/app/components/login/login-demo.component.ts
(Text was also mis-leading stating 11 chars not 15)
Refs #781
=> Remove maximum username length validation

ng2-components/README.md
=> add build demo doc

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.html, ng2-components/ng2-activiti-tasklist/index.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json, ng2-components/ng2-activiti-tasklist/src/models/task-details.model.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
Also finishes off implementation of a Complete (Task) button for tasks without a form, which the standalone tasks initially do not have.
Refs #530
=> Add start task button component and add to demo-shell

ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts
=> Automatically open the new task when the task is completed

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.ts, ng2-components/ng2-activiti-form/src/components/widgets/functional-group/functional-group.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/functional-group/functional-group.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/number/number.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/widget.component.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/widget.component.ts, ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.spec.ts, ng2-components/ng2-alfresco-documentlist/src/models/document-library.model.ts
=> Fixes for Activiti Form (validation and rendering)

ng2-components/ng2-activiti-processlist/src/models/filter.model.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.ts, ng2-components/ng2-activiti-tasklist/src/models/filter.model.ts, ng2-components/ng2-activiti-tasklist/src/models/icon.model.ts
=> Add custom color and icon

ng2-components/ng2-activiti-processlist/src/components/activiti-comments.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
=> Comment and Checklist diplayed are not for the correct task

demo-shell-ng2/index.html, demo-shell-ng2/package.json, ng2-components/ng2-activiti-form/package.json, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-types.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/index.ts
- basic input control for dates
- ‘required’ validator
- ‘min/max date’ value validators
closes #632
=> #632 Date widget for Activiti Form

ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-types.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/index.ts
minimalistic ‘Amount’ widget implementation
closes #634
=> #634 Amount widget for Activiti Form

demo-shell-ng2/app/components/search/search-bar.component.html, demo-shell-ng2/app/components/search/search-bar.component.ts, ng2-components/ng2-alfresco-search/README.md, ng2-components/ng2-alfresco-search/index.ts, ng2-components/ng2-alfresco-search/karma.conf.js, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.css, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.ts, ng2-components/ng2-alfresco-search/src/services/alfresco-thumbnail.service.spec.ts, ng2-components/ng2-alfresco-search/src/services/alfresco-thumbnail.service.ts
- Removed old `router-deprecated`
- Added lots more tests, brings coverage over 98%
=> Fix search page navigation from search box

ng2-components/ng2-activiti-form/package.json, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.ts, ng2-components/ng2-activiti-form/src/declarations.d.ts
additional date picker with min/max value support
refs #632
=> Value picker dialog for Date widget

ng2-components/ng2-activiti-processlist/karma.conf.js, ng2-components/ng2-activiti-processlist/package.json, ng2-components/ng2-activiti-processlist/src/assets/activiti-process.service.mock.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.spec.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
=> Auto-create default process-instance filters

ng2-components/ng2-activiti-form/karma.conf.js, ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/functional-group/functional-group.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/functional-group/functional-group.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/number/number.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/textfield-widget.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/widget.component.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/widget.component.ts
includes several bug fixes and code improvement based on unit testing results
=> Unit tests for Activiti Form component

ng2-components/ng2-activiti-form/src/components/widgets/core/tab.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.spec.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.ts
=> Dev valbano 839

ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/container.model.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/container.model.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.spec.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.ts
=> Dev valbano 903

ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.html
=> Fix index for multiple radio buttons

ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.ts
=> Fix visibility check for radio buttons

ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.spec.ts
Some test were not detecting the visibility in the right way. This fix the test to make the correct detection.
=> Fixed test to detect fail correctly

ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.spec.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.ts
=> Fix Visibility check for equal dates

ng2-components/ng2-alfresco-datatable/src/components/pagination/pagination-provider.ts, ng2-components/ng2-alfresco-datatable/src/components/pagination/pagination.component.ts, ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
- rendering improvements
- performance improvements 
fixes #478
=> Pagination component improvements

demo-shell-ng2/index.html, demo-shell-ng2/package.json, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.ts, ng2-components/ng2-activiti-tasklist/.gitignore, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.ts, ng2-components/ng2-activiti-tasklist/src/declarations.d.ts
- fix: People, comment and checklist dialogs do not appear (IE, Safari)
- fix: IE-related polyfills to fix DatePicker issues
- fix: PDF viewer for FF/IE11
- fix: upload widget not uploading files (Safari, FF, IE)
refs #930
=> IE compatibility fixes

demo-shell-ng2/app/components/search/search-bar.component.html, ng2-components/ng2-alfresco-search/README.md, ng2-components/ng2-alfresco-search/src/assets/alfresco-search.component.mock.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.ts, ng2-components/ng2-alfresco-search/src/services/alfresco-search.service.spec.ts
=> Tab into search results

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
=> #964 support currency symbols for amount column

ng2-components/ng2-activiti-diagrams/README.md, ng2-components/ng2-activiti-diagrams/demo/index.html, ng2-components/ng2-activiti-diagrams/demo/package.json, ng2-components/ng2-activiti-diagrams/demo/src/main.ts, ng2-components/ng2-activiti-diagrams/demo/systemjs.config.js, ng2-components/ng2-activiti-diagrams/demo/tslint.json
=> diagrams documentation and demo

ng2-components/ng2-activiti-analytics/README.md, ng2-components/ng2-activiti-analytics/demo/index.html, ng2-components/ng2-activiti-analytics/demo/package.json, ng2-components/ng2-activiti-analytics/demo/src/main.ts, ng2-components/ng2-activiti-analytics/demo/systemjs.config.js, ng2-components/ng2-activiti-analytics/demo/tslint.json, ng2-components/ng2-activiti-analytics/package.json, ng2-components/ng2-activiti-analytics/src/components/analytics.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.ts
=> Analytics demo and documentation

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.ts
=> 'required' validation for dynamic table

BROWSER-SUPPORT.md, README.md
=> Update documentation with Browser Support details

ng2-components/ng2-activiti-analytics/src/assets/analyticsParamsReportComponent.mock.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts, ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts
=> Fix process definition api

ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.html
=> highlight selected filter

ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts
=> fixed validation summary reset for Login

ng2-components/ng2-activiti-tasklist/index.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-people-search.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-people-search.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-people-search.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-people-search.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.ts, ng2-components/ng2-activiti-tasklist/src/components/index.ts, ng2-components/ng2-activiti-tasklist/src/i18n/it.json, ng2-components/ng2-activiti-tasklist/src/services/activiti-people.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-people.service.ts
=> Fix People add on Task details

ng2-components/ng2-activiti-analytics/src/models/chart.model.ts
=> Fix xAxes labels

ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.html
=> fix dropdown label accessibility

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
=> fix date formatting for completed forms

ng2-components/ng2-activiti-analytics/src/assets/analyticsComponent.mock.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.ts, ng2-components/ng2-activiti-analytics/src/models/chart.model.ts, ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts
=> Add MultiBarChart

ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.css, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.html
=> Fix report filter hover

ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.css, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.html
=> Fix activiti process filter hover

ng2-components/ng2-activiti-analytics/src/components/analytics.component.html, ng2-components/ng2-activiti-analytics/src/models/chart.model.ts, ng2-components/ng2-activiti-diagrams/demo/src/main.ts
=> Multibar chart xAxes label

demo-shell-ng2/app/app.component.css, demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.ts, demo-shell-ng2/index.html, demo-shell-ng2/package.json
includes minor code readability improvements
=> Add missing user info reference

ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.ts, ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts
=> Add createDefaultReports feature

ng2-components/ng2-activiti-analytics/src/components/widgets/date-range/date-range.widget.ts
=> Fix date picker accessibility

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-header.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-header.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.ts
=> Fix datePipe exception

demo-shell-ng2/app/components/search/search-bar.component.html, demo-shell-ng2/app/components/search/search.component.html, ng2-components/ng2-alfresco-search/README.md, ng2-components/ng2-alfresco-search/src/assets/alfresco-search.service.mock.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.ts, ng2-components/ng2-alfresco-search/src/services/alfresco-search.service.spec.ts, ng2-components/ng2-alfresco-search/src/services/alfresco-search.service.ts
=> Update search component to work with 0.4.0 JS API

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
=> fix attach widget rendering (complete form)

ng2-components/ng2-activiti-tasklist/src/assets/task-details.mock.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json
=> Notify errors to the user when completing tasks

ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.css
=> tasklist: fix tooltips for Chrome

PREREQUISITES.md
=> Update docs with new Alfresco version needed

ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
=> Fix process definition by appId

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.ts
=> Reload processlist after starting new process

ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts, ng2-components/ng2-activiti-analytics/src/models/chart.model.ts, ng2-components/ng2-activiti-analytics/src/models/report.model.ts
=> Custom reports

ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
=> Fix date conversion

ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.ts
=> Fix reset processDefinition

ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.ts, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
=> Dev valbano 1044

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.ts
=> Enable task details dialog from process details on non-Chrome browsers

ng2-components/ng2-activiti-tasklist/src/assets/activiti-apps.mock.ts, ng2-components/ng2-activiti-tasklist/src/assets/task-details.component.mock.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.ts, ng2-components/ng2-activiti-tasklist/src/components/no-task-detail-template.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json
=> New tests for tasklist component

demo-shell-ng2/app/components/files/files.component.ts
=> Added more check for file component on demo shell

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.html
=> fix date time display

ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.html
=> fix dynamic table rendering on tabs

demo-shell-ng2/app/components/login/login-demo.component.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts
=> Fix Demo shell login flags

PREREQUISITES.md, nginx.conf
- Remove headers_more module lines (not needed)
- Improve docs
=> Allow use of nginx on Windows

ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.ts
=> #1020 define a default value for layoutType

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.spec.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.ts
```
[X] Bugfix
[ ] Feature
```
No default option is selected even when in activiti is chosen one
Default option on dropdown is automatically selected
#957 
=> #957 - Added default dropdown option

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/demo/src/main.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts, ng2-components/ng2-activiti-tasklist/src/models/filter.model.ts
=> Remove the FilterModel with flat property

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.spec.ts
=> Readonly checkbox value

ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.html, ng2-components/ng2-activiti-tasklist/src/i18n/en.json, ng2-components/ng2-activiti-tasklist/src/i18n/it.json
```
[X] Bugfix
[ ] Feature
```
Dialog label is : CANCEL
Dialog label is : CLOSE
#1001 
```
```
=> #1001 - fix label for dialog

demo-shell-ng2/app/components/activiti/activiti-demo.component.css
=> fix zindex

demo-shell-ng2/i18n/en.json, demo-shell-ng2/i18n/it.json
just removes conflicting blocks from the demo shell. the proper i18n customisations will be introduced later.
fixes #828
=> #828 remove conflicting and obsolete i18n blocks

ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.ts
=> Display selected file name when re-selected after clear

ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.html, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.ts, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.ts
```
[ x ] Bugfix
[ ] Feature
```
no behaviour changed
no behaviour changed
#1080 
```
```
=> #1080 - Added coverage for changes due the start form component

ng2-components/ng2-activiti-processlist/src/assets/activiti-start-process.component.mock.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.css, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.ts, ng2-components/ng2-activiti-processlist/src/i18n/en.json
- Remove use of any in component and add types
- Small refactoring of method name
- Add many more tests
Refs #1066
=> Reset form when cancel button clicked

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-processlist/index.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process-dialog.component.css, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process-dialog.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process-dialog.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process-dialog.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.css, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.ts
=> Move Start Process functions into dedicated screen

demo-shell-ng2/index.html, ng2-components/ng2-activiti-form/README.md, ng2-components/ng2-activiti-form/docs/stencils.md, ng2-components/ng2-activiti-form/src/components/form-field/form-field.component.spec.ts, ng2-components/ng2-activiti-form/src/components/form-field/form-field.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-templates.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts, ng2-components/ng2-activiti-form/stencils/runtime.adf.js, ng2-components/ng2-activiti-form/stencils/runtime.ng1.js
- dynamic compilation of stencils (templates + controllers) stored within Activiti
- documentation updates
refs #875
=> Runtime stencil compilation

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.ts
=> Fix validation of number field values

demo-shell-ng2/app/components/login/login-demo.component.ts
```
[ x] Bugfix
[ ] Feature
```
#1147 
```
- [ x] No
```
=> Remove log

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.html
=> Fix closing task details when completed from process tasks list

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.ts
```
[ X ] Bugfix
[ ] Feature
```
#1115 
```
- [ X ] No
```
=> #1115 - Fix Visibility for readonly start form

ng2-components/ng2-alfresco-core/src/models/component.model.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoTranslation.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoTranslation.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoTranslationLoader.service.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.ts
```
[x] Bugfix
[ ] Feature
```
When you change the language the translation nothing occurs
When you change the language the translation is done
https://github.com/Alfresco/alfresco-ng2-components/issues/1145
```
```
=> #1145 Fix multi-language

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-details.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-details.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ x] No
```
=> #1143 - Fix double element on start process

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.css, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x ] No
```
=> #1134 - Added scroll for big dialog on process detail

demo-shell-ng2/app/app.component.css
```
[ x] Bugfix
[ ] Feature
```
#1178 
#1178 
```
[ ] Yes
[ x ] No
```
=> #1178 show header bar on mobile and tablet

demo-shell-ng2/app/app.component.css, demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.ts, demo-shell-ng2/index.html
```
[x ] Bugfix
[ ] Feature
```
The top left menu doesn't have navigation options
The top right menu has navigation options 
```
[ ] Yes
[x ] No
```
=> fix header options for mobile

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
```
[x] Bugfix
[ ] Feature
```
Upload notifications are fired for each file in the folder
It should be a single toast message for the overall process.
```
[ ] Yes
[x] No
```
=> #1181 Show toast message once

ng2-components/ng2-alfresco-core/src/services/AlfrescoTranslationLoader.service.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/empty-folder-content.spec.ts, ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Improve test document list
```
[ ] Yes
[ ] No
```
=> Improve test coverage document list

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.css
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ x] No
```
=> #1134 - Fix Scrolling on completed process task

ng2-components/ng2-activiti-form/src/services/ecm-model.service.spec.ts, ng2-components/ng2-activiti-form/src/services/ecm-model.service.ts
```
[ ] Bugfix
[x] Feature
```
https://github.com/Alfresco/alfresco-ng2-components/issues/649
```
[ ] Yes
[x] No
```
=> Move the ecm-model service methods of the form component inside the js api

ng2-components/ng2-alfresco-documentlist/index.ts, ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.html, ng2-components/ng2-alfresco-documentlist/src/components/document-list.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.css, ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.html, ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.ts, ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.spec.ts, ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.ts
```
[ ] Bugfix
[x] Feature
```
you can't create a New Folder
A Create Folder button is added
```
[ ] Yes
[x] No
```
=> Create Folder in document list

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-processlist/demo/src/main.ts, ng2-components/ng2-activiti-processlist/index.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-comments.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-details.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-details.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-variables.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-variables.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-variables.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.spec.ts, ng2-components/ng2-activiti-processlist/src/i18n/en.json, ng2-components/ng2-activiti-processlist/src/models/process-instance-variable.model.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.spec.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
=> Process variables component

demo-shell-ng2/app/components/home/home.component.spec.ts, demo-shell-ng2/config/karma-test-shim.js, demo-shell-ng2/config/karma.conf.js, demo-shell-ng2/config/webpack.test.js, demo-shell-ng2/package.json
- Unit testing configuration 
- dummy test for testing process check
=> webpack: fix unit testing configuration

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html
```
[ ] Bugfix
[ ] Feature
```
#1195 
```
[ ] Yes
[ ] No
```
=> #1195 add scroll to completed dynamic table

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
```
[x ] Bugfix
[ ] Feature
```
#1215 
```
[ ] Yes
[ ] No
```
=> #1215 use alfresco-js-api for upload file

demo-shell-ng2/app/components/home/home.component.css, demo-shell-ng2/app/components/home/home.component.html, demo-shell-ng2/app/components/home/home.component.ts, demo-shell-ng2/app/components/login/login-demo.component.css, demo-shell-ng2/app/components/login/login-demo.component.html, demo-shell-ng2/app/components/login/login-demo.component.ts, demo-shell-ng2/app/components/setting/setting.component.html
- [x ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
```
[ ] Bugfix
[ ] Feature
[x ] Other... style:
```
improve style : home, settings and login
```
[ ] Yes
[ ] No
```
If this PR contains a breaking change, please describe the impact and migration path for existing applications: …
=> improve mobile login,home and settings styles

demo-shell-ng2/app/components/home/home.component.css, demo-shell-ng2/app/components/home/home.component.html
- improve feature list UI (remove bullet styles, improve icon and text
positioning)
- improve card headers (icons and text positioning)
=> UI polish for Home page

demo-shell-ng2/config/loaders/debug.js, demo-shell-ng2/config/webpack.common.js, demo-shell-ng2/package.json
- new ‘debug-loader’ to help debugging webpack rules
- dynamically find and resolve all alfresco libraries
=> webpack config improvements

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
```
[x ] Bugfix
[ ] Feature
```
#1157 
```
[ ] Yes
[ ] No
```
=> #1157 reload process list

demo-shell-ng2/app/components/activiti/activiti-demo.component.css, demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-form/src/components/form-field/form-field.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.css, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts
```
[x ] Bugfix
[ ] Feature
```
#1176 
```
[ ] Yes
[ ] No
```
=> #1176 improve responsiveness task list and process list

ng2-components/ng2-activiti-diagrams/src/components/activities/diagram-task.component.html, ng2-components/ng2-activiti-diagrams/src/components/diagram.component.spec.ts, ng2-components/ng2-activiti-diagrams/src/components/raphael/index.ts, ng2-components/ng2-activiti-diagrams/src/components/raphael/raphael-multiline-text.component.ts
```
[x] Bugfix
[ ] Feature
```
Text longer than the task size are showed outside
We applied the same activiti rules for the task text
```
[ ] Yes
[x] No
```
=> #1183 - fix text formatting in diagram tasks

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
```
[x ] Bugfix
[ ] Feature
```
#1146 
```
[ ] Yes
[ ] No
```
=> #1146 load right filter on create task

ng2-components/ng2-activiti-processlist/src/models/filter-process.model.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
```
[ x] Bugfix
[ ] Feature
```
#1141 
```
[ ] Yes
[ ] No
```
=> #1141 fix process filter creation

ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.spec.ts, ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
The Report API are inside the Angular2 Service
The Report API are inside the js API
```
[ ] Yes
[x] No
```
=> Move the Report API inside the js API

ng2-components/ng2-activiti-analytics/src/components/analytics-report-heat-map.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.html
```
[x] Bugfix
[ ] Feature
```
#1220 
```
[ ] Yes
[x] No
```
=> Analitycs heading

ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.html
```
[x] Bugfix
[ ] Feature
```
#1244 
```
[ ] Yes
[ ] No
```
=> Create Folder Fix firefox style

ng2-components/ng2-activiti-analytics/src/components/widgets/date-range/date-range.widget.ts, ng2-components/ng2-activiti-analytics/src/models/report.model.ts
```
[x] Bugfix
[ ] Feature
```
#1219 
```
[ ] Yes
[x] No
```
=> Analytics default date range

ng2-components/ng2-activiti-processlist/demo/package.json
=> Add missing router dependency for processlist demo

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.html
=> Check that the process has a start form before attempting to display it

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.css, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics.component.ts, ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts
```
[x] Bugfix
[ ] Feature
```
#1174
```
[ ] Yes
[ ] No
```
=> Report rename

ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.html, ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Create Folder - placeholder

ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.html, ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.ts
```
[x] Bugfix
[ ] Feature
```
#1249 
```
[ ] Yes
[ ] No
```
=> fix folder name

demo-shell-ng2/.gitignore, demo-shell-ng2/app/components/about/about.component.ts, demo-shell-ng2/config/webpack.common.js, demo-shell-ng2/package.json
```
[x] Bugfix
[ ] Feature
```
About page doesn't work with webpack 
About page works with webpack 
```
[ ] Yes
[x] No
```
=> About page webpack compatible

ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.ts
```
[x] Bugfix
[ ] Feature
```
User details are not resetted whenever the user is not logged in with a specific provider
User details are resetted if the user is not logged in with a specific provider
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please describe the impact and migration path for …
=> #1072 - reset user details when the user is not logged in

ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.css, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts
```
[x] Bugfix
[ ] Feature
```
#1174 
```
[ ] Yes
[x] No
```
=> Rename report focus

ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthentication.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthentication.service.ts
```
[x] Bugfix
[ ] Feature
```
logout fail
logout doesn't fail
```
[ ] Yes
[ ] No
```
=> Cannot login after logging out

ng2-components/ng2-activiti-diagrams/src/components/diagram.component.css, ng2-components/ng2-activiti-diagrams/src/components/diagram.component.html, ng2-components/ng2-activiti-diagrams/src/components/diagram.component.ts, ng2-components/ng2-activiti-diagrams/src/models/diagram.model.ts
```
[x] Bugfix
[ ] Feature
```
#1276 
```
[ ] Yes
[x] No
```
=> Dynamic diagram size

ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.html
=> Ensure MDL upgradeElement() gets called on process name text input

demo-shell-ng2/app/components/files/files.component.html
=> Fix navigation to example folders

demo-shell-ng2/package.json, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
```
[ x] Bugfix
[ ] Feature
```
#1251 
#1266 
```
[ ] Yes
[ ] No
```
=> #1251 #1266 fix form visibility and performance

demo-shell-ng2/app/app.component.html, demo-shell-ng2/index.html
```
[x] Bugfix
[ ] Feature
```
https://github.com/Alfresco/alfresco-ng2-components/issues/1299
now is on the right also in IE 11
```
[ ] Yes
[ ] No
```
=> 1299 Internet Explorer Header bar wrong menu button positioning

ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.ts
=> Fix search control after logging out and back in

demo-shell-ng2/app/vendor.ts, demo-shell-ng2/config/webpack.common.js, demo-shell-ng2/index.html, demo-shell-ng2/package.json
=> fixes for IE

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json, ng2-components/ng2-activiti-tasklist/src/i18n/it.json, ng2-components/ng2-activiti-tasklist/src/models/task-details.model.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
```
[ ] Bugfix
[x] Feature
```
#1305 
```
[ ] Yes
[x] No
```
=> Claim a task

ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json, ng2-components/ng2-activiti-tasklist/src/models/form.model.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
```
[ ] Bugfix
[ x ] Feature
```
#1233 
```
[ ] Yes
[ ] No
```
=> #1233 attach form to a task

ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.ts
```
[ ] Bugfix
[ ] Feature
```
#1255 
```
[ ] Yes
[ ] No
```
=> #1255 remove onInit, we already add comments with onChange

ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html
```
[ x ] Bugfix
[ ] Feature
```
#1319 
```
[ ] Yes
[ ] No
```
=> #1319 regressed external content - transclusion

demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts, ng2-components/ng2-alfresco-upload/src/services/upload.service.spec.ts, ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
=> Fix uploads from folders opened from search results

demo-shell-ng2/app/app.component.css, demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.ts, demo-shell-ng2/app/components/activiti/activiti-demo.component.css, demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/home/home.component.css, demo-shell-ng2/config/webpack.common.js, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.css, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html
```
[ ] Bugfix
[x ] Feature
```
improve style demo shell
```
[ ] Yes
[ ] No
```
=> improve style demo shell

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
```
[x ] Bugfix
[ ] Feature
```
#1327 
```
[ ] Yes
[ ] No
```
=> #1327 do not call server when dropdown are readonly

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.ts, demo-shell-ng2/app/app.module.ts, demo-shell-ng2/app/components/activiti/custom-editor/custom-editor.component.ts
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[ ] No
```
=> add header missing app.component and minor clean

ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.spec.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
```
[x] Bugfix
[ ] Feature
```
#1308 
```
[ ] Yes
[x] No
```
=> Start process - custom outcome

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.ts
```
[x] Bugfix
[ ] Feature
```
#1331 
```
[ ] Yes
[x] No
```
=> Date is required

appveyor.yml, demo-shell-ng2/package.json, ng2-components/ng2-activiti-analytics/tsconfig.json, ng2-components/ng2-activiti-diagrams/tsconfig.json, ng2-components/ng2-activiti-form/tsconfig.json, ng2-components/ng2-activiti-processlist/tsconfig.json, ng2-components/ng2-activiti-tasklist/tsconfig.json, ng2-components/ng2-alfresco-core/package.json, ng2-components/ng2-alfresco-core/tsconfig.json, ng2-components/ng2-alfresco-datatable/tsconfig.json, ng2-components/ng2-alfresco-documentlist/tsconfig.json, ng2-components/ng2-alfresco-login/tsconfig.json, ng2-components/ng2-alfresco-search/tsconfig.json, ng2-components/ng2-alfresco-tag/tsconfig.json, ng2-components/ng2-alfresco-upload/tsconfig.json, ng2-components/ng2-alfresco-userinfo/tsconfig.json, ng2-components/ng2-alfresco-viewer/tsconfig.json, ng2-components/ng2-alfresco-webscript/tsconfig.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this …
=> fix window build

.travis.yml, ng2-components/ng2-activiti-analytics/package.json, ng2-components/ng2-activiti-diagrams/package.json, ng2-components/ng2-activiti-form/package.json, ng2-components/ng2-activiti-processlist/package.json, ng2-components/ng2-activiti-tasklist/package.json, ng2-components/ng2-alfresco-core/package.json, ng2-components/ng2-alfresco-datatable/package.json, ng2-components/ng2-alfresco-documentlist/package.json, ng2-components/ng2-alfresco-login/package.json, ng2-components/ng2-alfresco-search/package.json, ng2-components/ng2-alfresco-tag/package.json, ng2-components/ng2-alfresco-upload/package.json, ng2-components/ng2-alfresco-userinfo/package.json, ng2-components/ng2-alfresco-viewer/package.json, ng2-components/ng2-alfresco-webscript/package.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
```
[ ] Yes
[x] No
```
=> improve travis build

ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1345 
```
[ ] Yes
[ ] No
``` …
=> Analytics date - fix material design

ng2-components/ng2-activiti-analytics/src/components/analytics.component.html, ng2-components/ng2-activiti-analytics/src/i18n/en.json, ng2-components/ng2-activiti-analytics/src/i18n/it.json, ng2-components/ng2-activiti-analytics/src/models/chart.model.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1346 
```
[ ] Yes
[x] No
``` …
=> Analytics - Hide chart for zero values

ng2-components/ng2-alfresco-login/index.ts
```
```
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this …
=> fix module creation for login component in forRoot

ng2-components/ng2-activiti-processlist/src/components/activiti-process-comments.component.css, ng2-components/ng2-activiti-processlist/src/components/activiti-process-comments.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-comments.component.html
```
```
```
[x] Bugfix
[ ] Feature
```
#1324 
```
[ ] Yes
[ ] No
``` …
=> Show long comment

demo-shell-ng2/config/webpack.test.js
```
```
```
[ ] Bugfix
[ ] Feature
```
#1378 
```
[ ] Yes
[ ] No
``` …
=> #1378 fix test config for webpack

ng2-components/ng2-activiti-analytics/src/components/analytics.component.css, ng2-components/ng2-activiti-analytics/src/components/analytics.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.ts, ng2-components/ng2-activiti-analytics/src/models/chart.model.ts, ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1224
```
[ ] Yes
[x] No
``` …
=> Detailed Task Statistics - Analytics

ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.ts
=> hide save button from start form

ng2-components/ng2-activiti-analytics/package.json, ng2-components/ng2-activiti-diagrams/package.json, ng2-components/ng2-activiti-form/package.json, ng2-components/ng2-activiti-processlist/package.json, ng2-components/ng2-activiti-tasklist/package.json, ng2-components/ng2-alfresco-core/package.json, ng2-components/ng2-alfresco-datatable/package.json, ng2-components/ng2-alfresco-documentlist/package.json, ng2-components/ng2-alfresco-login/package.json, ng2-components/ng2-alfresco-search/package.json, ng2-components/ng2-alfresco-tag/package.json, ng2-components/ng2-alfresco-upload/package.json, ng2-components/ng2-alfresco-userinfo/package.json, ng2-components/ng2-alfresco-viewer/package.json, ng2-components/ng2-alfresco-webscript/package.json
```
```
```
[x ] Bugfix
[ ] Feature
[ x] Build related changes
```
#1385 
```
[ ] Yes
[ ] No …
```
=> #1385 fix build:w task

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe: Non functional
```
#1393 
```
[ ] …
```
=> #1393 remove old redirect code

ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html
```
```
```
[x] Bugfix
[ ] Feature
```
Task created via checklist is not listed on task filter
Task created via checklist is listed on …
=> #1259 - fix assignee for checklist task

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts
=> Fix sorting of processlist list items

ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.ts
=> Prevent live search from being run too soon

ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.ts
=> #1411 support 'form refresh' for start forms

ng2-components/ng2-alfresco-viewer/src/componets/viewer.component.css
- Display ellipsis
- Use full width of the title div
Refs #1325
=> Better support for long file names in viewer

ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthentication.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoContent.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoSettings.service.ts, ng2-components/ng2-alfresco-core/src/services/AlfrescoTranslation.service.ts, ng2-components/ng2-alfresco-core/src/services/alfresco-api.service.ts, ng2-components/ng2-alfresco-core/src/services/auth.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/auth.service.ts, ng2-components/ng2-alfresco-core/src/services/renditions.service.spec.ts, ng2-components/ng2-alfresco-documentlist/src/assets/document-list.service.mock.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts, ng2-components/ng2-alfresco-login/demo/src/main.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts, ng2-components/ng2-alfresco-userinfo/demo/src/main.ts, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.html, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.ts, ng2-components/ng2-alfresco-userinfo/src/services/bpm-user.service.ts
```
```
```
[ x] Bugfix
[ ] Feature
```
#1387 , I have also refactored the authService and apiService... the injection pattern was used in wrong way.
**What is the …
=> #1387 fix img for systemjs and refactoring apiservice

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts, ng2-components/ng2-activiti-tasklist/src/models/filter.model.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this …
=> #1259 - checklist task does not appear on tasklist after creation

ng2-components/ng2-alfresco-viewer/src/componets/notSupportedFormat.component.html
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```
[ ] Yes
[x] No
```
If this …
=> Wording for unsupported file could be better #1428

ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.ts
=> hide titles for start forms

ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts, ng2-components/ng2-activiti-diagrams/src/services/diagrams.service.ts, ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.ts, ng2-components/ng2-activiti-form/src/services/activiti-alfresco.service.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-people.service.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts, ng2-components/ng2-alfresco-core/src/services/renditions.service.ts, ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.ts, ng2-components/ng2-alfresco-search/src/services/alfresco-search.service.ts, ng2-components/ng2-alfresco-tag/src/services/tag.service.ts, ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
refs #1373 
- fixes for error handling in various services
- console output should now be improved
Note that the original error is related to process implementation, same error can be reproduced outside of ADF in former Activiti UI.
=> fix error handling and "this" context

ng2-components/ng2-activiti-analytics/package.json
```
```
```
[x] Bugfix
[ ] Feature
```
#1440 
```
[ ] Yes
[ ] No
``` …
=> Chart.js - fix version library

ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.css, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts, ng2-components/ng2-alfresco-datatable/src/data/datatable-adapter.ts, ng2-components/ng2-alfresco-datatable/src/data/object-datatable-adapter.ts, ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
Support for showing selected row for the components:
- DataTable
- DocumentList
- Activiti TaskList
- Activiti ProcessList
fixes #170 
Examples:
=> selected row highlight

ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-outcome.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Current behaviour always shows complete for start form
Start form shows start process when no …
=> #1432 - Added new system outcome : Start Process

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Click on task detail of process shows an empty tasklist
Click on task detail of process shows the …
=> #1431 - reload tasklist when user click on task

demo-shell-ng2/app/components/home/home.component.html
```
```
```
[x] Bugfix
[ ] Feature
```
wrong wording for home page cards
fix wording for home page cards …
=> #1447 - fixed wording for home page

ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
```
```
```
[ x ] Bugfix
[ ] Feature
```
#1387 
```
[ ] Yes
[ ] No …
```
=> #1387 fix rename document-list file

ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Typed word for checklist is remembered by the dialog
Dialog input is cleaned after submit/cancel …
=> #1441 - clean checklist input after submit or cancel action

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-processlist/src/models/filter-process.model.ts, ng2-components/ng2-activiti-processlist/src/models/index.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
=> Process filters should use own model class not task filter

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
=> Load process definitions for Tasks app

ng2-components/ng2-activiti-form/README.md, ng2-components/ng2-activiti-form/src/components/activiti-form.component.html, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this …
=> #1455 - added new check to show-hide validation icon next form title

.vscode/settings.json, demo-shell-ng2/config/webpack.dev.js, demo-shell-ng2/package.json
refs #1476 
- enable accessing demo shell from network (enables test server or VM scenarios)
=> Improve webpack dev config

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.html, ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.ts, ng2-components/ng2-alfresco-upload/src/i18n/en.json, ng2-components/ng2-alfresco-upload/src/i18n/it.json
```
```
```
[x] Bugfix
[ ] Feature
```
#1449 
```
[ ] Yes
[x] No
``` …
=> Wrong grammar with single file uploaded

demo-shell-ng2/package.json, ng2-components/ng2-activiti-diagrams/package.json
```
```
```
[x] Bugfix
[ ] Feature
```
#1439 
```
[ ] Yes
[ ] No
``` …
=> Chart.js - Fix version inside demoshell

ng2-components/ng2-activiti-form/src/components/activiti-form.component.html, ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.html, ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-outcome.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1467 
```
[ ] Yes
[x] No
``` …
=> #1467 Manage customs outcome

demo-shell-ng2/app/components/login/login-demo.component.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.spec.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1480 
```
[ ] Yes
[x] No
``` …
=> Login - change required username characters

demo-shell-ng2/custom-translation/alfresco-login/i18n/en.json, demo-shell-ng2/custom-translation/alfresco-login/i18n/it.json, ng2-components/ng2-alfresco-login/src/assets/authentication.service.mock.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.spec.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts, ng2-components/ng2-alfresco-login/src/i18n/en.json, ng2-components/ng2-alfresco-login/src/i18n/it.json
```
```
```
[ ] Bugfix
[ x] Feature
```
#1406 
```
[ ] Yes
[ ] No
``` …
=> #1406 improve CSRF and CORS errors reporting

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, demo-shell-ng2/app/components/activiti/form-viewer.component.html
```
```
```
[x] Bugfix
[ ] Feature
```
Tasklist is empty when task is selected via process detail
Tasklist is populated with the task …
=> #1431 - fix tasklist on click process task detail

demo-shell-ng2/custom-translation/alfresco-login/i18n/en.json, demo-shell-ng2/custom-translation/alfresco-login/i18n/it.json, ng2-components/ng2-alfresco-login/src/assets/authentication.service.mock.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.spec.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts, ng2-components/ng2-alfresco-login/src/i18n/en.json, ng2-components/ng2-alfresco-login/src/i18n/it.json
```
```
```
[ x ] Bugfix
[ ] Feature
```
#1443 
```
[ ] Yes
[ ] No …
```
=> #1443 improve license error - login component

ng2-components/ng2-activiti-analytics/src/components/widgets/dropdown/dropdown.widget.html, ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json
```
```
```
[x] Bugfix
[ ] Feature
```
#1479 
```
[ ] Yes
[x] No
``` …
=> Set default select option

ng2-components/ng2-alfresco-viewer/src/componets/notSupportedFormat.component.css, ng2-components/ng2-alfresco-viewer/src/componets/notSupportedFormat.component.html
```
```
```
[x] Bugfix
[ ] Feature
```
#1429 
```
[ ] Yes
[x] No
``` …
=> Fix unsupported files margin

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.css, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
=> improved focus outline for datatable rows

demo-shell-ng2/app/components/files/files.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html, ng2-components/ng2-alfresco-datatable/src/data/datatable-adapter.ts, ng2-components/ng2-alfresco-documentlist/README.md, ng2-components/ng2-alfresco-documentlist/src/components/content-column/content-column.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-column/content-column.component.ts
=> Support for column (cell) templates

ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.css, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.css
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this …
=> #1454 - Align element in form

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
=> Display process instance details after Start Process

ng2-components/ng2-activiti-processlist/src/assets/activiti-process-instances-list.mock.ts, ng2-components/ng2-activiti-processlist/src/assets/activiti-process.model.mock.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-details.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-details.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-details.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts
Implemented change for processlist and process details
Refs #1461
=> Display name and date for process instances if no name present

demo-shell-ng2/app/components/login/login-demo.component.ts, demo-shell-ng2/custom-translation/alfresco-login/i18n/en.json, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts, ng2-components/ng2-alfresco-login/src/i18n/en.json
```
```
```
[x] Bugfix
[ ] Feature
```
#1480 
```
[ ] Yes
[x] No
``` …
=> Fix dynamic value inside the min length error message

ng2-components/ng2-activiti-form/src/components/activiti-form.component.html, ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.html, ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-outcome.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.html
```
```
```
[x] Bugfix
[ ] Feature
```
#1467 
```
[ ] Yes
[ ] No
``` …
=> Filter start form outcomes

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-form/README.md, ng2-components/ng2-activiti-form/index.ts, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts, ng2-components/ng2-activiti-form/src/events/form-error.event.ts, ng2-components/ng2-activiti-form/src/events/form-field.event.ts, ng2-components/ng2-activiti-form/src/events/form.event.ts, ng2-components/ng2-activiti-form/src/events/index.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
refs #1474 
FormService now exposes the following events:
- formLoaded (formRendered alternative)
- formFieldValueChanged
- taskCompleted
- taskCompletedError
- taskSaved
- taskSavedError
Documentation updates
=> basic form events hooks and readme updates

ng2-components/ng2-alfresco-datatable/README.md, ng2-components/ng2-alfresco-documentlist/README.md
=> documentation updates

ng2-components/ng2-alfresco-documentlist/src/models/document-library.model.ts
=> Fix build errors when using latest JS-API

ng2-components/ng2-alfresco-core/src/services/auth-guard-bpm.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/auth-guard-bpm.service.ts, ng2-components/ng2-alfresco-core/src/services/auth-guard-ecm.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/auth-guard-ecm.service.ts, ng2-components/ng2-alfresco-core/src/services/auth-guard.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/auth-guard.service.ts
```
```
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe:
```
test auth guard
```
[ ] …
```
=> Add test auth-guard

demo-shell-ng2/app/app.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If this …
=> #1564 remove unused code

ng2-components/ng2-alfresco-upload/src/components/upload-button.component.html, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
=> Allow button label to be added via staticTitle input

ng2-components/ng2-activiti-analytics/README.md, ng2-components/ng2-activiti-analytics/src/components/analytics-generator.component.css, ng2-components/ng2-activiti-analytics/src/components/analytics-generator.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-generator.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-generator.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.css, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.css, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html, ng2-components/ng2-activiti-analytics/src/i18n/en.json, ng2-components/ng2-activiti-analytics/src/models/chart.model.ts
```
```
```
[ ] Bugfix
[x] Feature
```
#1583 
```
[ ] Yes
[ ] No
``` …
=> Analytics - Improve look and feel and user experience

ng2-components/ng2-alfresco-documentlist/src/i18n/ru.json, ng2-components/ng2-alfresco-login/src/i18n/ru.json, ng2-components/ng2-alfresco-upload/src/i18n/ru.json
```
[X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
```
```
[ ] Bugfix
[ ] Feature
[X ] Other... Please describe: Russian translate
```
```
[ ] Yes
[X] No
```
=> Dev kodermax translate

scripts/npm-build-bundle-all.sh
```
```
```
[ ] Bugfix
[ ] Feature
[ x Build related changes
```
remove unnecessary build  command …
=> remove double build npm-build-bundle-all.sh

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-analytics/README.md, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.css, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics.component.ts, ng2-components/ng2-activiti-analytics/src/components/widgets/dropdown/dropdown.widget.ts, ng2-components/ng2-activiti-analytics/src/i18n/en.json, ng2-components/ng2-activiti-analytics/src/models/report.model.ts, ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts, ng2-components/ng2-alfresco-core/src/services/alfresco-api.service.ts
```
```
```
[ ] Bugfix
[x] Feature
```
It is not possible perform any of this operations for the reports
Added the chance to Save, …
=> #1184 - Added option to reports : Save, Delete and Export to CSV

demo-shell-ng2/config/webpack.common.js, demo-shell-ng2/config/webpack.test.js
```
```
```
[x ] Bugfix
[ ] Feature
```
development build doesn't work with node 5
development build works  node 5
**Does this PR …
=> Demo shell build problem with Node 5 #1602

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Spelling in issue and PR templates
``` …
=> Fix spelling in ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE

demo-shell-ng2/app/components/home/home.component.css, demo-shell-ng2/app/components/home/home.component.html, demo-shell-ng2/app/components/login/login-demo.component.html, demo-shell-ng2/app/components/setting/setting.component.html, ng2-components/ng2-activiti-processlist/demo/package.json, ng2-components/ng2-activiti-processlist/package.json, ng2-components/ng2-alfresco-login/src/i18n/en.json, ng2-components/ng2-alfresco-login/src/i18n/it.json, ng2-components/ng2-alfresco-login/src/i18n/ru.json, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.html
```
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
#1512 
```
[ ] Yes
[x] No
``` …
=> ADF Rebranding

ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts, ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1521 
```
[ ] Yes
[x] No
``` …
=> Fix getProcesses service call

ng2-components/ng2-alfresco-viewer/src/componets/notSupportedFormat.component.html, ng2-components/ng2-alfresco-viewer/src/componets/pdfViewer.component.html, ng2-components/ng2-alfresco-viewer/src/componets/viewer.component.html
```
```
```
[x] Bugfix
[ ] Feature
```
#1534
#1536 
#1537
```
[ ] Yes …
```
=> Viewer - Accessibility alternative text

demo-shell-ng2/app/app.module.ts, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, demo-shell-ng2/app/components/search/search.component.ts, demo-shell-ng2/package.json, demo-shell-ng2/tslint.json
```
```
```
[x ] Bugfix
[ ] Feature
```
tslint is executed in demoshell #1641 …
=> add tslint in demo shell #1641

ng2-components/ng2-alfresco-viewer/package.json, ng2-components/ng2-alfresco-viewer/src/services/rendering-queue.services.ts
```
[ x Tests for the changes have been added (for bug fixes / features)
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> rendering service header

ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.spec.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts
```
```
```
[ x] Bugfix
[ ] Feature
```
username is not trimmed 
trim username …
=> trim username onBlur #1575

ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.css, ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.html, ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.spec.ts, ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.ts, ng2-components/ng2-alfresco-tag/src/components/tag-list.component.ts, ng2-components/ng2-alfresco-tag/src/components/tag-node-list.component.ts, ng2-components/ng2-alfresco-tag/src/i18n/en.json, ng2-components/ng2-alfresco-tag/src/i18n/it.json, ng2-components/ng2-alfresco-tag/src/services/tag.service.ts
add translation
fix placeholder #1506
```
```
```
[ ] Bugfix
[x] Feature
```
there are no error message if the tag is already present …
=> tag validation #1592

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/components/setting/setting.component.html
```
```
```
[x] Bugfix
[ ] Feature
```
#1512 
```
[ ] Yes
[ ] No
``` …
=> Rebranding fixes

ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts, ng2-components/ng2-alfresco-search/src/services/alfresco-search.service.ts, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts, ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
latest TS/TSLint libs detect couple of problems related to private apis
used earlier; changing to public in order to fix compilation
=> fix compilation errors with latest TS/TSLint

ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.ts
=> sequential loading order

demo-shell-ng2/README.md, demo-shell-ng2/config/webpack.common.js
```
```
```
[ ] Bugfix
[x ] Feature
```
After a discussion on the gitter channel about how to customize a component with a relative path I think could be easy for …
=> add public files js css and images copied in the demo shell dist

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html
=> fix display-value rendering for checkboxes

demo-shell-ng2/README.md, demo-shell-ng2/config/webpack.common.js
```
```
```
[x ] Bugfix
[ ] Feature
```
If you don;t have an image folder in the build you receive an error
Better to copy the entire …
=> copy entire public folder

ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.html
```
```
```
[x ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> fix clean placeholder tag actions #1506

demo-shell-ng2/tsconfig.json
fixes issues with building for Windows
```
```
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Demo shell fails to build on Windows due to some TypeScript typings files
**What is the …
=> Update tsconfig.json for demo shell

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-variables.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/events/base-ui.event.ts, ng2-components/ng2-alfresco-core/src/events/base.event.ts, ng2-components/ng2-alfresco-datatable/index.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/data-cell.event.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/data-row-action.event.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts, ng2-components/ng2-alfresco-datatable/src/data/datatable-adapter.ts, ng2-components/ng2-alfresco-documentlist/index.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts, ng2-components/ng2-alfresco-documentlist/src/components/node.event.ts
=> cancellable events for DataTable and DocumentList

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/index.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
refs #1464 
- toggle task details header
- toggle visibility of involve/comments/checklist
=> more control over task details header

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/components/tag/tag.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> #1512 fix text demo shell

ng2-components/ng2-activiti-form/src/components/activiti-content.component.html, ng2-components/ng2-activiti-form/src/components/activiti-content.component.ts, ng2-components/ng2-activiti-form/src/services/form.service.spec.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1236
```
[ ] Yes
[ ] No
``` …
=> Fix Thumbnail preview

ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.css, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.html, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.spec.ts, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.ts
- fix image paths to be relative rather than rooted (for user info,
refs #1606)
- fix full name rendering
- fix styling for ‘job title’ (refs #1626)
=> user-info component fixes

ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts
Fix ObjectDataRow
Tasklist
Processlist
```
```
```
[x] Bugfix
[ ] Feature
```
#1625 …
=> Processlist doesn't load the correct colum value

demo-shell-ng2/config/karma.conf.js, demo-shell-ng2/package.json
=> migrate from PhantomJS to Chrome

ng2-components/ng2-activiti-form/src/components/activiti-form.component.html, ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/checkbox/checkbox.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/display-text/display-text.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/functional-group/functional-group.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/hyperlink/hyperlink.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/number/number.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.html
refs #1714 
- provides support for `className` field that Angular 1 designer allows
to define for Forms and Form Fields
=> support for setting CSS classes in the designer

ng2-components/ng2-alfresco-upload/README.md, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.html, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
[ x] Documentation
```
documentation and test added to the staticTitle propertie …
=> add test and documentation staticTitle option #1570

demo-shell-ng2/app/components/about/about.component.css, demo-shell-ng2/app/components/about/about.component.html, demo-shell-ng2/app/components/about/about.component.ts, demo-shell-ng2/app/components/files/files.component.css, demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/setting/setting.component.css, demo-shell-ng2/app/components/setting/setting.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-generator.component.css, ng2-components/ng2-activiti-analytics/src/components/analytics-generator.component.html, ng2-components/ng2-activiti-analytics/src/components/widgets/duration/duration.widget.css, ng2-components/ng2-activiti-analytics/src/components/widgets/duration/duration.widget.html, ng2-components/ng2-activiti-form/src/components/activiti-form.component.css, ng2-components/ng2-activiti-form/src/components/activiti-form.component.html, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.css, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.css, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
html style 
```
[ ] Yes …
```
=> remove style in html #1678

ng2-components/ng2-activiti-analytics/karma.conf.js, ng2-components/ng2-activiti-diagrams/karma.conf.js, ng2-components/ng2-activiti-form/karma.conf.js, ng2-components/ng2-alfresco-datatable/karma.conf.js, ng2-components/ng2-alfresco-documentlist/karma.conf.js, ng2-components/ng2-alfresco-login/karma.conf.js, ng2-components/ng2-alfresco-search/karma.conf.js, ng2-components/ng2-alfresco-tag/karma.conf.js, ng2-components/ng2-alfresco-upload/karma.conf.js, ng2-components/ng2-alfresco-userinfo/karma.conf.js, ng2-components/ng2-alfresco-viewer/karma.conf.js, ng2-components/ng2-alfresco-webscript/karma.conf.js
```
```
```
[ ] Bugfix
[ ] Feature
```
remove event model from coverage
```
[ ] Yes
[ ] No
```
If this PR contains a breaking change, please …
=> remove event model from coverage

ng2-components/ng2-alfresco-datatable/README.md, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
```
```
```
[ x ] Bugfix
[ ] Feature
```
#1750 
```
[ ] Yes
[ ] No …
```
=> #1750 add ngOnchange on data input

ng2-components/ng2-activiti-analytics/package.json, ng2-components/ng2-activiti-diagrams/package.json, ng2-components/ng2-activiti-form/package.json, ng2-components/ng2-activiti-processlist/package.json, ng2-components/ng2-activiti-tasklist/package.json, ng2-components/ng2-alfresco-datatable/package.json, ng2-components/ng2-alfresco-documentlist/package.json, ng2-components/ng2-alfresco-login/package.json, ng2-components/ng2-alfresco-search/package.json, ng2-components/ng2-alfresco-tag/package.json, ng2-components/ng2-alfresco-upload/package.json, ng2-components/ng2-alfresco-userinfo/package.json, ng2-components/ng2-alfresco-viewer/package.json, ng2-components/ng2-alfresco-webscript/package.json, scripts/README.md, scripts/npm-build-all.sh, scripts/npm-clean.sh, scripts/npm-publish.sh, scripts/start.sh
```
```
```
[x ] Bugfix
[ ] Feature
```
clean task doesn't work properly …
=> fix clean script and build all

ng2-components/ng2-activiti-processlist/karma.conf.js, ng2-components/ng2-activiti-tasklist/karma.conf.js, ng2-components/ng2-alfresco-core/karma.conf.js
```
```
```
[ ] Bugfix
[ ] Feature
```
missing event coverage exclude …
=> missing event coverage exclude

ng2-components/ng2-activiti-form/src/components/activiti-content.component.css, ng2-components/ng2-activiti-form/src/components/activiti-content.component.html, ng2-components/ng2-activiti-form/src/components/activiti-content.component.spec.ts, ng2-components/ng2-activiti-form/src/components/activiti-content.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/services/content.service.ts, ng2-components/ng2-alfresco-core/src/services/index.ts
refs #1745 
See screenshot below for a sample how different modes will work
=> Form: support for embedded document view

ng2-components/ng2-activiti-analytics/karma.conf.js, ng2-components/ng2-activiti-diagrams/karma.conf.js, ng2-components/ng2-activiti-form/karma.conf.js, ng2-components/ng2-activiti-processlist/karma.conf.js, ng2-components/ng2-activiti-tasklist/karma.conf.js, ng2-components/ng2-alfresco-core/karma.conf.js, ng2-components/ng2-alfresco-datatable/karma.conf.js, ng2-components/ng2-alfresco-documentlist/karma.conf.js, ng2-components/ng2-alfresco-login/karma.conf.js, ng2-components/ng2-alfresco-search/karma.conf.js, ng2-components/ng2-alfresco-tag/karma.conf.js, ng2-components/ng2-alfresco-upload/karma.conf.js, ng2-components/ng2-alfresco-userinfo/karma.conf.js, ng2-components/ng2-alfresco-viewer/karma.conf.js, ng2-components/ng2-alfresco-webscript/karma.conf.js
```
```
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
timeout can occurs during the test running in the build
increase inactivity timeout test …
=> increase inactivity timeout test

appveyor.yml
```
```
```
[ ] Bugfix
[ ] Feature
```
appveyor build script …
=> appveyor fix new build script

ng2-components/ng2-activiti-analytics/karma.conf.js, ng2-components/ng2-activiti-diagrams/karma.conf.js, ng2-components/ng2-activiti-form/karma.conf.js, ng2-components/ng2-activiti-processlist/karma.conf.js, ng2-components/ng2-activiti-tasklist/karma.conf.js, ng2-components/ng2-alfresco-core/karma.conf.js, ng2-components/ng2-alfresco-datatable/karma.conf.js, ng2-components/ng2-alfresco-documentlist/karma.conf.js, ng2-components/ng2-alfresco-login/karma.conf.js, ng2-components/ng2-alfresco-search/karma.conf.js, ng2-components/ng2-alfresco-tag/karma.conf.js, ng2-components/ng2-alfresco-upload/karma.conf.js, ng2-components/ng2-alfresco-userinfo/karma.conf.js, ng2-components/ng2-alfresco-viewer/karma.conf.js, ng2-components/ng2-alfresco-webscript/karma.conf.js
```
```
```
[ ] Bugfix
[ ] Feature
```
timeout failing
timeout increase …
=> add timeout increase karma tests

demo-shell-ng2/app/components/login/login-demo.component.ts, ng2-components/ng2-alfresco-login/src/i18n/it.json, ng2-components/ng2-alfresco-login/src/i18n/ru.json
```
```
```
[x] Bugfix
[ ] Feature
```
#1666 
```
[ ] Yes
[ ] No …
```
=> Login - Fix dynamic translate parameter

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
The filter is not selected when user create a new task
The filter is selected when user create …
=> #1517 - Added new behaviour when user create a new task

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-form/src/components/activiti-content.component.ts, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/content-link.model.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-alfresco-viewer/README.md, ng2-components/ng2-alfresco-viewer/src/components/imgViewer.component.html, ng2-components/ng2-alfresco-viewer/src/components/imgViewer.component.spec.ts, ng2-components/ng2-alfresco-viewer/src/components/imgViewer.component.ts, ng2-components/ng2-alfresco-viewer/src/components/mediaPlayer.component.spec.ts, ng2-components/ng2-alfresco-viewer/src/components/mediaPlayer.component.ts, ng2-components/ng2-alfresco-viewer/src/components/pdfViewer.component.spec.ts, ng2-components/ng2-alfresco-viewer/src/components/pdfViewer.component.ts, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1679 
```
[ ] Yes
[x] No …
```
=> Integration beetwen Viewer and Activiti Content

ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/number/number.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.html
```
```
```
[x] Bugfix
[ ] Feature
```
#1724 
```
[ ] Yes
[ ] No …
```
=> Activiti form - Required filed should have an asterisk inside the label

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.css, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
=> fix long names in columns (ellipsis-cell class)

ng2-components/ng2-activiti-form/src/components/widgets/checkbox/checkbox.widget.html
- migrate to angular/material checkboxes, #1667
- add required indicator #1725 
- various fixes and improvements (caused by migration)
=> fix checkboxes (Form)

demo-shell-ng2/app/vendor.ts
- add missing alfresco-js-api to the vendors
- add missing 3D viewer related libs to the vendors (fixes issue with
app bundle having duplicates)
=> bundle improvements

demo-shell-ng2/app/vendor.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
warning message about hammerjs
add hammerjs …
=> add hammerjs demo shell

ng2-components/ng2-activiti-analytics/demo/systemjs.config.js, ng2-components/ng2-activiti-diagrams/demo/systemjs.config.js, ng2-components/ng2-activiti-form/demo/systemjs.config.js, ng2-components/ng2-activiti-processlist/demo/systemjs.config.js, ng2-components/ng2-activiti-tasklist/demo/systemjs.config.js, ng2-components/ng2-alfresco-datatable/demo/systemjs.config.js, ng2-components/ng2-alfresco-documentlist/demo/systemjs.config.js, ng2-components/ng2-alfresco-login/demo/systemjs.config.js, ng2-components/ng2-alfresco-search/demo/systemjs.config.js, ng2-components/ng2-alfresco-tag/demo/systemjs.config.js, ng2-components/ng2-alfresco-userinfo/demo/systemjs.config.js, ng2-components/ng2-alfresco-viewer/demo/systemjs.config.js, ng2-components/ng2-alfresco-webscript/demo/systemjs.config.js
```
```
```
[ ] Bugfix
[ ] Feature
```
@angular/material missing in demo folders dep
@angular/material dep added
**Does this PR …
=> add @angular/material dep on demos systemjs conf

ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
refs #1704 
- fix previously missed Display Value date conversion
=> remove hardcoded date format

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, demo-shell-ng2/config/webpack.prod.js
```
```
```
[x ] Bugfix
[ ] Feature
```
Minification is not working because of alfresco-js-api
Now minification is  working because …
=> Minification fix #1693

demo-shell-ng2/app/components/datatable/datatable-demo.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
=> fix datatable multi select checkboxes

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts
refs #1624 
- add missing support for columns in process list
=> add custom columns support for process list

ng2-components/ng2-alfresco-datatable/src/components/pagination/pagination.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.spec.ts, scripts/npm-build-all.sh
```
```
```
[x ] Bugfix
[ ] Feature
```
#1593
```
[ ] Yes
[z ] No …
```
=> fix dropdown visibility #1593

ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-tasks.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1679 
```
[ ] Yes
[ ] No …
```
=> Start Form - Close the dialog before open the viewer

ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.spec.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1660 
```
[ ] Yes
[ ] No …
```
=> The process filters should not be created twice

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1670 
```
[ ] Yes
[ ] No …
```
=> Activiti form - Dropdown display label in complete form

demo-shell-ng2/app/components/activiti/activiti-demo.component.css, demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-start-task.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json
- fix navigation within process details
- fix ‘create task’ button name (was ‘start task’ previously)
- put ‘create task’ and ‘start process’ buttons to proper places in
layout
=> demo app improvements (ADF-432)

ng2-components/ng2-activiti-form/src/components/activiti-content.component.html, ng2-components/ng2-activiti-form/src/components/activiti-content.component.spec.ts, ng2-components/ng2-activiti-form/src/components/activiti-content.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```
[ ] Yes
[ ] No
```
If …
=> Improve activiti content coverage

ng2-components/ng2-alfresco-core/karma.conf.js, ng2-components/ng2-alfresco-core/src/services/notification.service.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
unit test notification service are missing
unit test notification service
**Does this PR …
=> Notification service test

ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.component.ts, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe:
```
test coverage document menu  …
=> add test document menu component

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
#1704
```
```
```
[x] Bugfix
[ ] Feature
```
#1704 
```
[ ] Yes
[ ] …
```
=> Activiti form - Custom date format

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/src/assets/tasklist-service.mock.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Once the user add a checklist task it cannot be deleted
Checklist task can now be deleted …
=> #1426 - Checklist task delete action

ng2-components/ng2-alfresco-userinfo/src/assets/fake-bpm-user.service.mock.ts, ng2-components/ng2-alfresco-userinfo/src/assets/fake-ecm-user.service.mock.ts, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.html, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.spec.ts, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.ts, ng2-components/ng2-alfresco-userinfo/src/models/bpm-user.model.ts, ng2-components/ng2-alfresco-userinfo/src/models/ecm-user.model.ts, ng2-components/ng2-alfresco-userinfo/src/services/bpm-user.service.spec.ts, ng2-components/ng2-alfresco-userinfo/src/services/ecm-user.service.spec.ts
```
```
```
[ ] Bugfix
[x] Feature
```
User info shows on banner only the first/last name of the user
User info will show full name of …
=> #ADF-452-userinfo show full name on the banner

ng2-components/ng2-activiti-processlist/src/assets/activiti-process.service.mock.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-processlist/src/models/filter-process.model.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.spec.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts, ng2-components/ng2-activiti-tasklist/src/models/filter.model.ts
```
```
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> Provide a way to retrieve the process filter by id or name

ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
```
```
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> Provide a way to retrieve the task filter by Id or by name

ng2-components/ng2-alfresco-datatable/src/components/pagination/pagination.component.css
=> fix pagination styles

ng2-components/ng2-activiti-tasklist/src/components/activiti-checklist.component.html
- move click handler from button icon to a button itself (fixes all browsers behaviour)
=> ADF-65: fix checklist buttons

demo-shell-ng2/app/components/setting/setting.component.css, demo-shell-ng2/app/components/setting/setting.component.html, demo-shell-ng2/app/components/setting/setting.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
No check is provided on settings
Addresses on settings must start with http(s)://(\\)
**Does …
=> #ADF-498 added check for valid settings addresses

ng2-components/ng2-alfresco-viewer/README.md
- update readme
- fix examples
=> [ADF-477] Viewer readme cleanup

demo-shell-ng2/app/components/files/files.component.css, demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.html, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
- add support for [disabled] attribute
- move to angular/material icons
- improve demo shell layout (files.component)
refs #1833
=> [ADF-502] upload button enhancements

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, ng2-components/ng2-activiti-processlist/README.md, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.ts, ng2-components/ng2-alfresco-core/src/components/collapsable/accordion.component.ts
Follow the component guide style
The accordion should be open by default
```
```
```
[ ] Bugfix
[ ] Feature
```
**Does this PR …
=> Accordion - Guide style

ng2-components/ng2-alfresco-upload/README.md, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.html, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> Fix bug related to upload button permission

ng2-components/ng2-alfresco-upload/index.ts
=> [ADF-547] add missing module exports

ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
Fix for Issue #DW-44: New service that returns application details for a given appId.
https://issues.alfresco.com/jira/browse/DW-44
=> [DW-44] - Task Service - Add a new method to get the application details by Id

ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.spec.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
Fix for Issue#DW-46: New service that returns application details for a given appId. This service should be part of ng2-activiti-processlist component.
https://issues.alfresco.com/jira/browse/DW-46
=> [DW-46] - Process Service - Add a new method to get the application details by Id

ng2-components/ng2-alfresco-social/src/components/like.component.spec.ts, ng2-components/ng2-alfresco-social/src/components/like.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
clean the like component  after nodeId has been changed …
=> clean like component after change of input Id

ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts
added hasIcon input to hide/show filter icons.
=> [DW-49]: Add new input to process activiti-filters component to show/hide icons

ng2-components/ng2-alfresco-login/README.md, ng2-components/ng2-alfresco-login/package.json, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.spec.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts
```
```
```
[ ] Bugfix
[x ] Feature
```
change default behaviour of new show properties …
=> invert show default properties

demo-shell-ng2/config/loaders/license-check.js, demo-shell-ng2/config/webpack.common.js, demo-shell-ng2/package.json, ng2-components/config/assets/license_header.txt, ng2-components/config/assets/license_header_add.txt, ng2-components/config/custom-loaders/license-check.js, ng2-components/config/webpack.common.js, scripts/npm-build-all.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
the license check is now in webpack …
=> [ADF-579] - move license check in webpack

ng2-components/config/webpack.test.js
```
```
```
[ x] Bugfix
[ ] Feature
```
fix sourcemap broken
```
[ …
```
=> [ADF-593] - fix sourcemap

ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-564] TaskList - Do not reload the tasks when the taskId and currentTask are the same

ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> fixed test for pipeline to match new angular4 changes on simple change

ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.html, ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.spec.ts, ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.ts
- added on click emitter to heading
- added hide/show functionality based on group content.
=> [DW-50]: New features for accordion-group component

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-analytics/README.md, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-242] Select the first in the list when the report is deleted

ng2-components/ng2-alfresco-core/src/directives/upload.directive.spec.ts, ng2-components/ng2-alfresco-core/src/directives/upload.directive.ts
fix upload directive for Safari
=> [ADF-606] fix upload directive for Safari

ng2-components/ng2-alfresco-documentlist/README.md, ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-action/content-action-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-action/content-action.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-column/content-column-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-column/content-column.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts, ng2-components/ng2-alfresco-documentlist/src/components/empty-folder/empty-folder-content.component.spec.ts
Extra DOM events with bubbling support for DocumentList:
- node-click
- node-dblclick
=> [ADF-548] node-click and node-dblclick DOM events

ng2-components/ng2-alfresco-core/src/directives/upload.directive.spec.ts, ng2-components/ng2-alfresco-core/src/directives/upload.directive.ts, ng2-components/ng2-alfresco-upload/src/directives/file-draggable.directive.spec.ts, ng2-components/ng2-alfresco-upload/src/directives/file-draggable.directive.ts
- native HTML5 DnD for document list and drag area components
=> [ADF-615] significant performance improvements for drag and drop

ng2-components/ng2-alfresco-core/README.md, ng2-components/ng2-alfresco-core/src/services/alfresco-authentication.service.ts, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.ts
Rename Auth Service events:
- loginSubject -> onLogin
- logoutSubject -> onLogout
=> [ADF-562] auth service api improvements

ng2-components/ng2-alfresco-core/src/services/alfresco-authentication.service.ts
- support for getting ECM/BPM username values
**Requires next version of alfresco-js-api**
=> [ADF-653] auth service enhancements

Dockerfile, ng2-components/ng2-activiti-form/index.ts, ng2-components/ng2-activiti-form/package.json, ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/form-field/form-field.component.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/index.ts, ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/text/text-mask.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.ts
```
```
```
[ ] Bugfix
[X] Feature
```
No mask is applied on a text input element on the form
Activiti mask is applied to text element …
=> [ADF-147] Add input mask to Text Widget on Form

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
```
```
```
[x ] Bugfix
[ ] Feature
```
Value for dropdown is taken incorrectly when is referred to previous forms
Value is now showed …
=> [ADF-647] Fix retrieving value for dropdown

.travis.yml, scripts/README.md, scripts/npm-build-all.sh, scripts/npm-publish.sh
```
```
```
[ ] Bugfix
[ ] Feature
[ x] Build related changes
```
```
[ ] Yes
[ ] No
```
If …
=> group test

demo-shell-ng2/app/components/setting/setting.component.css
```
```
```
[x] Bugfix
[ ] Feature
```
Fixed windows size is not correct for firefox browsers
Fixed windows size is now correct for …
=> [ADF-509] - fixed settings window dimension

demo-shell-ng2/app/components/files/files.component.css, demo-shell-ng2/app/components/files/files.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
example added for not overlay mode viewer
```
[ ] Yes
[ ] No
```
If this PR contains a breaking …
=> [ADF-659] example to not overlay mode viewer

demo-shell-ng2/app/components/files/files.component.html
```
```
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe:
```
Better description for a label
```
[ ] Yes
[ ] No
```
If this PR contains a breaking change, please …
=> [ADF-655] Change label permission button

demo-shell-ng2/app/components/about/about.component.ts, demo-shell-ng2/config/webpack.common.js, demo-shell-ng2/package.json
```
```
```
[ x] Bugfix
[ ] Feature
```
about page is not displaying components version 
about page is now ok
**Does this PR …
=> [ADF-656] about component fix

ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Execute undo when user clicks the 'Undo' and not when snackbar is dismissed (in 3 seconds or …
=> [ADF-690] fix upload area snackbar behaviour

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts, ng2-components/ng2-alfresco-upload/src/models/file.model.ts, ng2-components/ng2-alfresco-upload/src/services/upload.service.spec.ts, ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
- remove old unused settings (formFields variable)
- individual options for uploaded files …
=> [ADF-610] Upload button and DnD area should not upload hidden files and folders

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, demo-shell-ng2/resources/i18n/en.json, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics.component.ts, ng2-components/package.json
```
```
```
[X] Bugfix
[ ] Feature
```
When a report is deleted the details in demo shell is not uploaded.
When a report is saved, no report is selected after …
=> [ADF-242] Fixed behaviour for saving/deleting reports

ng2-components/ng2-alfresco-core/src/services/alfresco-content.service.ts, ng2-components/ng2-alfresco-viewer/README.md, ng2-components/ng2-alfresco-viewer/index.ts, ng2-components/ng2-alfresco-viewer/src/components/mediaPlayer.component.spec.ts, ng2-components/ng2-alfresco-viewer/src/components/pdfViewer.component.spec.ts, ng2-components/ng2-alfresco-viewer/src/components/txtViewer.component.css, ng2-components/ng2-alfresco-viewer/src/components/txtViewer.component.html, ng2-components/ng2-alfresco-viewer/src/components/txtViewer.component.spec.ts, ng2-components/ng2-alfresco-viewer/src/components/txtViewer.component.ts, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.spec.ts, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
```
```
```
[ ] Bugfix
[x ] Feature
```
txt extension file can be showed …
=> [ADF-613] Add plain text viewer

ng2-components/ng2-alfresco-upload/README.md, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.html, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts, ng2-components/ng2-alfresco-upload/src/directives/file-draggable.directive.spec.ts, ng2-components/ng2-alfresco-upload/src/directives/file-draggable.directive.ts
```
```
```
[ ] Bugfix
[x] Feature
```
- [disabled]=“expression” support for drop upload area
- extended underlying directive with …
=> [ADF-573] ability to disable drop upload area

ng2-components/ng2-alfresco-core/README.md
```
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-602] Accordion component - Add basic documentation

ng2-components/ng2-alfresco-viewer/README.md, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.spec.ts, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
```
```
```
[ ] Bugfix
[ x] Feature
```
wav and mp3 enabling
``` …
```
=> wav and Mp3 enabling viewer

ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.ts
```
```
```
[X] Bugfix
[ ] Feature
```
It is not possibile select a row in dynamic table via keyboard only navigation
It is possibile …
=> [ADF-707] Ability to select a row on a dynamic table

ng2-components/ng2-activiti-analytics/index.ts, ng2-components/ng2-activiti-analytics/src/models/index.ts
- exported chart and report models
=> [ADF-737] Analytics report - Should expose the Models

demo-shell-ng2/app/components/datatable/datatable-demo.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> Add data-automation-id to multi select checkbox

ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
proper extraction of File objects from the FileList
=> [ADF-723] fix file upload bug

demo-shell-ng2/package-lock.json, ng2-components/package-lock.json
Add lock files for npm v5; does nothing for earlier versions, so is not harmful.
=> [ADF-722] lock files for npm 5

demo-shell-ng2/app/components/login/login-demo.component.css, demo-shell-ng2/app/components/login/login-demo.component.html, demo-shell-ng2/app/components/login/login-demo.component.ts
Removes 'banned' input from login screen to avoid confusions on what it does.
=> [ADF-245] remove old 'banned' demo from login screen

ng2-components/ng2-alfresco-viewer/src/components/notSupportedFormat.component.spec.ts, ng2-components/ng2-alfresco-viewer/src/components/notSupportedFormat.component.ts, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-686] Viewer notSupportedComponent - add blobFile as input

.travis.yml, ng2-components/config/karma.conf-all.js
```
```
```
[ x] Bugfix
[ ] Feature
```
Code coverage fix
```
[ …
```
=> Merge code coverage of all Components

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, ng2-components/ng2-activiti-processlist/README.md, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-processlist/src/models/filter-process.model.ts, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-tasklist/src/models/filter.model.ts
```
```
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-702] Task/Process Filter - Provide a way to change the default filter

demo-shell-ng2/app/components/about/about.component.html, demo-shell-ng2/app/components/about/about.component.ts
```
```
```
[ ] Bugfix
[x ] Feature
```
With the alpha packages at the moment to see where it refers you need to copy the link of the gitish on your browser. …
=> [ADF-761] Add info and link on the current last git commit

.vscode/settings.json, demo-shell-ng2/app/app.module.ts, demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts, demo-shell-ng2/app/dialogs/create-folder.dialog.ts, demo-shell-ng2/app/material.module.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-header.component.spec.ts, ng2-components/ng2-alfresco-core/README.md, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.component.css, ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.component.html, ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.component.ts, ng2-components/ng2-alfresco-core/src/material.module.ts, ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.css
- simple toolbar component (core lib)
- readme updates (core lib)
- update demo shell with toolbar component demo (document list)
=> [ADF-754] toolbar component

demo-shell-ng2/app/components/about/about.component.ts, ng2-components/ng2-alfresco-viewer/src/components/imgViewer.component.ts, ng2-components/ng2-alfresco-viewer/src/components/txtViewer.component.css, ng2-components/ng2-alfresco-viewer/src/components/txtViewer.component.spec.ts, ng2-components/ng2-alfresco-viewer/src/components/txtViewer.component.ts, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
```
```
```
[ x] Bugfix
[ ] Feature
```
the blob input now works also in the text viewer …
=> [ADF-739] Fix blob input in text viewer

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
> - [ ] Bugfix
Checkboxes in the Github issue and pull request templates.
There are no checkboxes in markdown.
**What …
=> GitHub issue & pull request template change

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts, ng2-components/ng2-alfresco-datatable/src/data/object-datatable-adapter.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-773] Datatable - Unable to use a custom template inside the column

ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.spec.ts, ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
```
```
```
[X] Bugfix
[ ] Feature
```
Not centralised call for getting process filters
All the call are centralised to one method …
=> [ADF-780] centralised call for process filters api

ng2-components/ng2-activiti-processlist/README.md, ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.html, ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.ts, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/src/components/adf-task-attachment-list.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/adf-task-attachment-list.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Thumbnail doesn't work in attachments processlist
Now the thumbnails are showed correctly …
=> [ADF-779] Fix thumbnail task process list

ng2-components/ng2-alfresco-login/index.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.css, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.spec.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts, ng2-components/ng2-alfresco-login/src/i18n/en.json, ng2-components/package-lock.json
```
```
```
[x] Bugfix
[x] Feature
```
Issues are listed here: https://github.com/Alfresco/alfresco-ng2-components/issues/900
Every …
=> [ADF-589] Login component different bug fixes

ng2-components/ng2-activiti-tasklist/src/components/activiti-people-search.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-alfresco-datatable/src/data/object-datatable-adapter.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts, ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts, ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.ts, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
switch off type checking for 'require' keyword …
=> fix issues with the require keyword (angular cli)

ng2-components/ng2-activiti-analytics/.npmignore, ng2-components/ng2-activiti-diagrams/.npmignore, ng2-components/ng2-activiti-form/.npmignore, ng2-components/ng2-activiti-processlist/.npmignore, ng2-components/ng2-activiti-tasklist/.npmignore, ng2-components/ng2-alfresco-core/.npmignore, ng2-components/ng2-alfresco-datatable/.npmignore, ng2-components/ng2-alfresco-documentlist/.npmignore, ng2-components/ng2-alfresco-login/.npmignore, ng2-components/ng2-alfresco-search/.npmignore, ng2-components/ng2-alfresco-social/.npmignore, ng2-components/ng2-alfresco-tag/.npmignore, ng2-components/ng2-alfresco-upload/.npmignore, ng2-components/ng2-alfresco-userinfo/.npmignore, ng2-components/ng2-alfresco-viewer/.npmignore, ng2-components/ng2-alfresco-webscript/.npmignore
```
```
```
[ x] Bugfix
[ ] Feature
```
dist folder is present in the  npm package but not used anymore
remove unused dist folder …
=> [ADF-797] Remove dist folder from npm distributed package , leave src and bundles

demo-shell-ng2/app/app.component.ts, demo-shell-ng2/config/webpack.common.js
```
```
```
[x ] Bugfix
[ ] Feature
```
Setup proxy server in webpack demo-shell to avoid CORS problem and skip the configuration of external module or external proxy …
=> [ADF-804] Webpack proxy setup to avoid CORS problem

.travis.yml
updates Travis config to use node 8 and npm 5
=> update travis to node 8

ALFRESCOCORS.md, PREREQUISITES.md
```
```
```
[ ] Bugfix
[ ] Feature
[ x] Documentation
```
```
[ ] Yes
[ x] No
```
If this PR contains a breaking change, please describe the impact and migration path for existing …
=> [ADF-78] Update CORS help

demo-shell-ng2/app.config.json, demo-shell-ng2/config/webpack.common.js, ng2-components/ng2-alfresco-core/README.md, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/services/app-config.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/app-config.service.ts, ng2-components/ng2-alfresco-core/src/services/index.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Introduces new Application Configuration Service that allows providing global settings.
**Does …
=> [ADF-814] application configuration service

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.ts, demo-shell-ng2/app/components/files/files.component.html, ng2-components/ng2-alfresco-documentlist/src/assets/document-list.component.mock.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts, ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.spec.ts, ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
```
```
```
[X] Bugfix
[ ] Feature
```
There is no check on file drag and drop for permissions
Permission are now checked for current …
=> [ADF-510] Drag&Drop check permission to allow user to upload a file

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.css, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts
```
```
```
[ x] Bugfix
[ ] Feature
```
The empty template was wrongly removed in the previous PR …
=> [ADF-524] Fix empty state after the loading introduction

demo-shell-ng2/package-lock.json, demo-shell-ng2/package.json
fixes regression related to missing "intl" dependency within demo shell app
=> add missing intl dependency for demo shell

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-833] DataTable -  improve the single and double click event

ng2-components/ng2-activiti-tasklist/README.md
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-840] Task header basic documentation

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-687] - Task attachment list - Disable the button if the task is completed

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
```
```
```
[ x] Bugfix
[ ] Feature
```
The loading state is showed under the current results 
The Loading state when is active …
=> [ADF-524] Fix loading state datatable

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-884] FormComponent - Compilation error

ng2-components/ng2-alfresco-userinfo/src/models/ecm-user.model.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-883] UserInfo - compilation errors

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.module.ts, demo-shell-ng2/app/app.routes.ts, demo-shell-ng2/app/components/index.ts, demo-shell-ng2/app/components/login/login-demo.component.html, demo-shell-ng2/app/components/settings/settings.component.css, demo-shell-ng2/app/components/settings/settings.component.html, demo-shell-ng2/app/components/settings/settings.component.ts, demo-shell-ng2/app/services/debug-app-config.service.ts, demo-shell-ng2/tsconfig.json
- custom app settings service to use isolated storage (demo shell)
- restore settings UI
- redirect angular and rxjs to the same version as components use.
=> [ADF-881] app settings page

ng2-components/ng2-activiti-processlist/src/components/adf-create-process-attachment.component.ts, ng2-components/ng2-activiti-tasklist/src/components/adf-create-task-attachment.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-893] Create task/process attachment Compilation error

ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-794] Activiti people - New look and feel design

ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
```
```
```
[X] Bugfix
[ ] Feature
```
Completing a form on new created task make application fail due a wrong object reference
Fixed …
=> [ADF-842] Fixed type for taskdetails

ng2-components/ng2-activiti-tasklist/src/i18n/en.json, ng2-components/ng2-activiti-tasklist/src/i18n/it.json
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> Involved People component - Missing keys

demo-shell-ng2/package.json, ng2-components/package-base.json, ng2-components/package.json
```
```
```
[ ] Bugfix
[ ] Feature
[ x] Build related changes
```
```
[ ] Yes
[ ] No
``` …
=> Appveyor test

ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.ts, ng2-components/ng2-activiti-tasklist/src/models/task-details.model.ts
```
```
```
[x ] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ADF-842
```
[x …
```
=> [ADF-842] Create new TaskDetailsModel in loadNextTask

ng2-components/ng2-activiti-form/src/services/activiti-content-service.ts, ng2-components/ng2-activiti-tasklist/src/components/adf-create-task-attachment.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-930] Attachment list - Fix create 

demo-shell-ng2/app/components/form/demo-form.ts, demo-shell-ng2/app/components/form/form-demo.component.css, demo-shell-ng2/app/components/form/form-demo.component.html, demo-shell-ng2/app/components/form/form-demo.component.ts, ng2-components/ng2-activiti-form/README.md, ng2-components/ng2-activiti-form/src/assets/activiti-form.component.mock.ts, ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
passing data as input in the form, the values are considered only before the form is loaded. …
=> [ADF-907] - Form reacts to data added in input

ng2-components/ng2-activiti-form/src/services/activiti-content-service.ts, ng2-components/ng2-activiti-processlist/src/components/adf-create-process-attachment.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
If …
=> [ADF-930] Processes Attachment - fix upload

demo-shell-ng2/package-lock.json, demo-shell-ng2/package.json, ng2-components/ng2-activiti-analytics/package.json, ng2-components/ng2-activiti-diagrams/package.json, ng2-components/ng2-activiti-form/package.json, ng2-components/ng2-activiti-processlist/package.json, ng2-components/ng2-activiti-tasklist/package.json, ng2-components/ng2-alfresco-core/package.json, ng2-components/ng2-alfresco-datatable/package.json, ng2-components/ng2-alfresco-documentlist/package-lock.json, ng2-components/ng2-alfresco-documentlist/package.json, ng2-components/ng2-alfresco-login/package.json, ng2-components/ng2-alfresco-search/package.json, ng2-components/ng2-alfresco-social/package.json, ng2-components/ng2-alfresco-tag/package.json, ng2-components/ng2-alfresco-upload/package.json, ng2-components/ng2-alfresco-userinfo/package.json, ng2-components/ng2-alfresco-viewer/package.json, ng2-components/ng2-alfresco-webscript/package.json, ng2-components/package.json, scripts/npm-build-all.sh
```
```
```
[ ] Bugfix
[ ] Feature
```
Update typescript version 2.3.4 …
=> Update typescript version 2.3.4

README.md
> - [ ] Bugfix
> - [ ] Yes
> - [X] No
=> Fix markdown syntax and wording on README.md

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.ts, ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
```
```
```
[X] Bugfix
[ ] Feature
```
On Push detect change strategy is applied to the component.
Removed on push detect strategy to …
=> [ADF - 778] Fixed error on wrong change detection strategy

demo-shell-ng2/app/components/form/form-demo.component.html, demo-shell-ng2/app/components/form/form-demo.component.ts, ng2-components/ng2-activiti-form/README.md, ng2-components/ng2-activiti-form/index.ts, ng2-components/ng2-activiti-form/src/components/adf-form-list.component.html, ng2-components/ng2-activiti-form/src/components/adf-form-list.component.spec.ts, ng2-components/ng2-activiti-form/src/components/adf-form-list.component.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/empty-folder/empty-folder-content.component.spec.ts
```
```
```
[ ] Bugfix
[x] Feature
[x] Documentation
```
New functionality
The component should show all the form as a list …
=> [ADF-914] Form List Component

demo-shell-ng2/app.config-dev.json, demo-shell-ng2/app.config-prod.json, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts, ng2-components/ng2-alfresco-core/README.md, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/services/app-config.service.ts, ng2-components/ng2-alfresco-core/src/services/user-preferences.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/user-preferences.service.ts, ng2-components/ng2-alfresco-core/tsconfig.json, ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.spec.ts, ng2-components/ng2-alfresco-tag/src/components/tag-list.component.spec.ts, ng2-components/ng2-alfresco-tag/src/components/tag-node-list.component.spec.ts, ng2-components/ng2-alfresco-tag/src/services/tag.service.spec.ts, ng2-components/ng2-alfresco-upload/src/services/upload.service.spec.ts, ng2-components/ng2-alfresco-webscript/src/webscript.component.spec.ts
Features:
- User Preferences Service
- App Config Service supports default settings from code (for unit testing scenarios)
- upgraded unit tests to use proper app config settings for ajax mocks
=> [ADF-983] User Preferences Service

ng2-components/ng2-alfresco-documentlist/README.md, ng2-components/ng2-alfresco-documentlist/src/components/content-action/content-action.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-action/content-action.component.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts, ng2-components/ng2-alfresco-documentlist/src/models/content-action.model.ts, ng2-components/ng2-alfresco-documentlist/src/services/document-actions.service.spec.ts, ng2-components/ng2-alfresco-documentlist/src/services/document-actions.service.ts, ng2-components/ng2-alfresco-documentlist/src/services/folder-actions.service.spec.ts, ng2-components/ng2-alfresco-documentlist/src/services/folder-actions.service.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.ts, ng2-components/ng2-alfresco-search/src/i18n/en.json
```
```
```
[x] Bugfix
[x] Feature
```
Delete is not working in the seacrh results.
Delete is working in the seacrh results. Either we …
=> [ADF-523] Fix delete operation in the search component

ng2-components/ng2-alfresco-documentlist/README.md, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
Add @Input decorator for the "loading" property in Document List component
=> [ADF-1015] make "loading" state two-way bindable (document list)

demo-shell-ng2/app/components/files/files.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-documentlist/index.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/material.module.ts
- upgrade to md-menu
- fix the issue with missing icons
- extend demo shell to show icons for actions
- fix the issue with border problems in Firefox
- remove commented out samples in demo shell (there's readme for that instead)
=> [ADF-770] upgrade to md-menu

ng2-components/ng2-alfresco-core/src/services/notification.service.spec.ts
=> Fix error on test into core component

ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/adf-task-attachment-list.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/adf-empty-list.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/adf-empty-list.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/adf-empty-list.component.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts, ng2-components/ng2-alfresco-datatable/src/directives/loading-template.directive.spec.ts, ng2-components/ng2-alfresco-datatable/src/directives/no-content-template.directive.spec.ts, ng2-components/ng2-alfresco-datatable/src/i18n/en.json, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/empty-folder/empty-folder-content.directive.spec.ts, ng2-components/ng2-alfresco-documentlist/src/i18n/en.json
- i18n support for DataTable's "empty" screen"
- i18n support for DocumentList's "empty" screen"
=> [ADF-1026] i18n support for "empty" screen

ng2-components/ng2-activiti-processlist/index.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-variables.component.css, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-variables.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-variables.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-variables.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.css, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts, ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.css, ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.html, ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.ts, ng2-components/ng2-activiti-processlist/src/i18n/en.json, ng2-components/ng2-activiti-tasklist/index.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/adf-task-attachment-list.component.css, ng2-components/ng2-activiti-tasklist/src/components/adf-task-attachment-list.component.html, ng2-components/ng2-activiti-tasklist/src/components/adf-task-attachment-list.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/adf-task-attachment-list.component.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json
- added loader in tasklist and task-attachment-list component
- added loader in processlist, process-variable-list and process-attachment-list component
=> [ADF - 1030] Datatable - enable isLoading to show the spinner in all the components

ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-variables.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-process-instance-variables.component.ts, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.html, ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts, ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.html, ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.ts, ng2-components/ng2-activiti-tasklist/src/components/adf-task-attachment-list.component.html, ng2-components/ng2-activiti-tasklist/src/components/adf-task-attachment-list.component.ts
=> [ADF-1073] Replace loadingFlag with isLoading

ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.css, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/adf-comment-list.component.css
… people
> - [x] Bugfix
The comment component is directly showed inside the task details component …
=> [ADF-1044] Task Details - Use the latest version of the comment component

ng2-components/ng2-alfresco-core/src/services/upload.service.spec.ts
> - [X] Bugfix
wrong self reference to core in upload service test
fixed referral to …
=> Fixed wrong referral to core in upload service tests

ng2-components/ng2-activiti-form/README.md, ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/no-task-detail-template.component.spec.ts
> - [X] Bugfix
Involved person in the task can complete the task
Involved person in …
=> [ADF-923] Added check for only involved user cannot complete a task

ng2-components/ng2-alfresco-search/README.md, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.ts
=> [ADF-1042] Search folder documentation and add wildcard * 

demo-shell-ng2/app/components/search/search-bar.component.html, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/pipes/text-highlight.pipe.ts, ng2-components/ng2-alfresco-search/README.md, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.css, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.ts, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.html, ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.ts
> - [ ] Bugfix
No highlighting
Search results highlighting …
=> [ADF-1039] Search results highlighting

ng2-components/ng2-activiti-form/config/webpack.common.js, ng2-components/ng2-activiti-processlist/config/webpack.common.js, ng2-components/ng2-alfresco-datatable/config/webpack.common.js, ng2-components/ng2-alfresco-social/config/webpack.common.js, ng2-components/ng2-alfresco-tag/config/webpack.common.js, ng2-components/ng2-alfresco-upload/config/webpack.common.js, ng2-components/ng2-alfresco-userinfo/config/webpack.common.js, ng2-components/ng2-alfresco-viewer/config/webpack.common.js, ng2-components/ng2-alfresco-webscript/config/webpack.common.js
> - [ ] Bugfix
add sass configuration in all the component common webpack configuration
> - [ ] …
=> Add SASS configuration in all the component common webpack configuration

ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/services/deleted-nodes-api.service.ts, ng2-components/ng2-alfresco-core/src/services/favorites-api.service.ts, ng2-components/ng2-alfresco-core/src/services/nodes-api.service.ts, ng2-components/ng2-alfresco-core/src/services/people-api.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/people-api.service.ts, ng2-components/ng2-alfresco-core/src/services/search-api.service.ts, ng2-components/ng2-alfresco-core/src/services/shared-links-api.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/shared-links-api.service.ts, ng2-components/ng2-alfresco-core/src/services/sites-api.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/sites-api.service.ts
Content-related services
- DeletedNodesApiService
- FavoritesApiService
- NodesApiService
- PeopleApiService
- SearchApiService
- SharedLinksApiService
- SitesApiService
=> [SFSNG-724] content services

CONTRIBUTING.md
> - [ ] Bugfix
> - [ ] Yes
> - [x] No
If this PR contains a breaking change, please describe the impact and migration path for …
=> Contribution guide start

demo-shell-ng2/app/components/about/about.component.css, demo-shell-ng2/app/components/about/about.component.html, demo-shell-ng2/app/components/about/about.component.ts, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/models/product-version.model.ts, ng2-components/ng2-alfresco-core/src/services/discovery-api.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/discovery-api.service.ts
> - [ ] Bugfix
Into the about tab of demo shell ecm/bpm product information are showed …
=> [ADF-487] added discovery information to about component

ng2-components/ng2-activiti-processlist/src/components/start-process.component.html, ng2-components/ng2-activiti-processlist/src/components/start-process.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/start-process.component.ts
```
```
```
[ ] Bugfix
[x] Feature
```
* Removed conditional statements from HTML …
=> [ADF-1117] Activiti Start Process - Migrate to MD

ng2-components/ng2-alfresco-core/src/services/alfresco-content.service.ts
add extra params to the AlfrescoContentService members:
- getDocumentThumbnailUrl
- getContentUrl
=> [ADF-1086] update content apis with extra params

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
Fix bugs related to selection management when "checkboxes" mode is on.
=> [ADF-1134] selection management fixes

ng2-components/ng2-alfresco-viewer/README.md
Add section on configuring PDF.js library for webpack-enabled apps.
=> [ADF-1136] improved Viewer readme

ng2-components/ng2-activiti-tasklist/src/components/task-header.component.ts
- changed parent name key from processDefnitionId to processInstanceId
=> [ADF-1140] Task header - Wrong parent name key

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.ts, demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts, ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.component.scss, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
- separate language picker
- separate "more" menu
- toolbar theme picker
=> replace MDL sidebar with material2 menus

scripts/npm-prepublish.sh
> - [ ] Bugfix
Add option to  change the registry in npm-prepublish.sh
> - [ ] Yes
> - [x] No
If …
=> [ADF-1158] updated the prepublish script with registry option

ng2-components/ng2-activiti-processlist/src/components/process-instance-details.component.css, ng2-components/ng2-activiti-processlist/src/components/process-instance-details.component.html, ng2-components/ng2-activiti-processlist/src/components/process-instance-details.component.ts, ng2-components/ng2-activiti-processlist/src/i18n/en.json
> - [x] Bugfix
There is no way to add a comment
Add a button that shows the process …
=> [ADF-1142] Process instance details - should show the comment componen

ng2-components/ng2-activiti-tasklist/src/components/comment-list.component.css, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.css
> - [x] Bugfix
No scroll was shown for the comment component in demo shell
max-height …
=> [ADF-1081] Scroll bar is missing in comments component

ng2-components/ng2-activiti-tasklist/src/components/start-task.component.html, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.ts
> - [x] Bugfix
Assignee dropdown shows null value for username.
Added conditions to …
=> [ADF-1138] Start Task Form Assignee dropdown show null value inside

ng2-components/ng2-activiti-processlist/src/components/process-instance-details.component.html, ng2-components/ng2-activiti-processlist/src/components/process-instance-details.component.ts
> - [x] Bugfix
The show button is not showed
Add the show diagram button
**Does this …
=> [ADF-1151] Process details - Add the show diagram button

ng2-components/ng2-activiti-processlist/src/components/start-process.component.css, ng2-components/ng2-activiti-processlist/src/components/start-process.component.html
> - [x] Bugfix
Start process form was not aligned properly
Removed unnecessary …
=> [ADF-1147] Form is not rendered properly when starting a new process.

demo-shell-ng2/app/app.component.css, demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.ts, demo-shell-ng2/index.html
Demo App enhancements
- remove MDL references from the main application component
- new app menu bar based on angular/material (with "primary" theme)
=> (demo app) Application menu bar enhancements

ng2-components/ng2-activiti-form/src/services/form.service.spec.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
> - [x] Bugfix
The response return the response object
The response returns the …
=> [ADF-1162] Form List - Fix the getForms service response

demo-shell-ng2/app/components/settings/settings.component.html
> - [x] Bugfix
Users were able to set urls ending with / in the settings which caused different type of errors with …
=> [ADF-978] Prevent settings urls to end with /

ng2-components/ng2-alfresco-core/src/components/view/card-view-textitem.component.scss
> - [x] Bugfix
Ui distortion of card view's text item was present.
Not anymore... …
=> [ADF-1148] Fix styling issues of card view's text item.

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list-row.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.spec.ts, ng2-components/ng2-alfresco-upload/src/services/file-uploading.service.spec.ts
> - [ ] Bugfix
> - [ ] Other... Please describe: Unit tests …
=> [ADF-924] Upload Component unit tests

ng2-components/ng2-activiti-tasklist/src/components/apps-list.component.html
> - [X ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Bugfix
> - [X ] Other... Please describe:  508 compliance for government sites
We didn't know what you needed from a testing perspective.  please advise …
=> [ADF-1201] 508 Compliance Resolution for the App tiles.

ng2-components/ng2-alfresco-core/src/services/favorites-api.service.ts
- fix the crash related to remapping entities
=> fix the favorites api

ng2-components/ng2-activiti-form/index.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.scss, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.ts
> - [X] Bugfix
When multiple files are uploaded on the upload widget, they are not correctly managed.
**What is the …
=> [ADF-1048] Upload widget can manage multiple files.

ng2-components/ng2-alfresco-core/src/models/site.model.ts, ng2-components/ng2-alfresco-core/src/services/sites-api.service.ts
> - [ ] Bugfix
Pagination node is not added on Site Model
Site Model has pagination …
=> Added node pagination to SiteModel

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.scss
=> [ADF-1162] Form List - Fix date field css

ng2-components/ng2-activiti-processlist/src/components/process-instance-details.component.css, ng2-components/ng2-activiti-processlist/src/components/process-instance-header.component.css, ng2-components/ng2-activiti-processlist/src/components/process-instance-header.component.html, ng2-components/ng2-activiti-tasklist/src/components/task-header.component.html, ng2-components/ng2-activiti-tasklist/src/components/task-header.component.scss
> - [x] Bugfix
Tasks/Processes header components have different margins …
=> [ADF-1168]  Tasks header component and Processes header component have different margins

demo-shell-ng2/app/components/settings/settings.component.html, demo-shell-ng2/config/webpack.common.js
> - [x] Bugfix
See ticket ADF-978 and ADF-1200
In case of wrong urls, user get proper …
=> [ADF-1200] Error handling for wrong host urls

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.ts
> - [x] Bugfix
The Start Task/Process Form is not closed on click of cancel button. …
=> [ADF-1175] Start Process and Start Task Forms don't close when Cancel button is clicked

demo-shell-ng2/app/components/about/about.component.ts
> - [X] Bugfix
If user log in only on one platform (ACS/APS) an error is throwed on the page. …
=> [ADF-1216] Added platform logged check for about component

ng2-components/ng2-activiti-tasklist/src/components/people.component.css, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.html
> - [x] Bugfix
The components are not alined
The components are alined
**Does this PR …
=> [ADF-1228] Task Details - The People and Involve component are not aligned

ng2-components/ng2-activiti-tasklist/src/components/task-filters.component.ts
> - [x] Bugfix
After a new task creation, a wrong task filter is selected
After a new …
=> [ADF-1229] Task Filter - Wrong task filter is selected when a new task is created

ng2-components/ng2-alfresco-datatable/README.md, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
Support automatic translation for column headers.
=> [ADF-1051] Optional automatic translation of column headers

ng2-components/ng2-activiti-tasklist/src/assets/start-task.mock.ts, ng2-components/ng2-activiti-tasklist/src/assets/tasklist-service.mock.ts, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.html, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.ts, ng2-components/ng2-activiti-tasklist/src/services/tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/tasklist.service.ts
> - [x] Bugfix
* Not able to start a task when changing the assignee if the logged in user is not admin
**What is the …
=> [ADF-1143] [TaskList] - Not able to start a task when changing the assignee from the 'Start Task' form

CONTRIBUTING.md
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1281
=> [ADF-1281] Test naming convention in the contribution guide

ng2-components/ng2-alfresco-core/src/components/view/card-view-dateitem.component.html
> - [x] Bugfix
Datapicker is not showed in the middle.
Datapicker is displaying  in …
=> [ADF-1265] Task Header - Datapicker is not showed in the middle.

ng2-components/ng2-activiti-form/README.md, ng2-components/ng2-activiti-form/src/components/start-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.spec.ts, ng2-components/ng2-activiti-form/src/events/index.ts, ng2-components/ng2-activiti-form/src/events/validate-form-field.event.ts, ng2-components/ng2-activiti-form/src/events/validate-form.event.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
Form Service enhancements
- new `validateForm` event (with custom behaviour support)
- new `validateFormField` event (with custom behaviour support)
Form enhancements
- Form Model now owns all Field validators and provides a way to replace or extend the set.
Includes readme updates for the APIs added.
=> [ADF-1091] Validation layer enhancements for Form component

ng2-components/ng2-activiti-tasklist/src/components/task-details.component.spec.ts
> - [x] Bugfix
Unit tests are failing
Fixed …
=> [ADF-1301] Task Details - Fix unit tests

demo-shell-ng2/app/app.module.ts, demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts, demo-shell-ng2/app/dialogs/download-zip.dialog.ts, demo-shell-ng2/app/material.module.ts
"Download as Zip" feature demo (requires 5.2.1 platform API)
- download single selected file
- download multiple selected files as ZIP
- download one or multiple selected folders as ZIP
- download all mixed content as ZIP (file + folder)
- download dialog
=> [ADF-1300] Download as Zip feature and dialog

ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.html, ng2-components/ng2-alfresco-viewer/src/components/pdfViewer.component.html
Fixes for AoT enabled builds, addresses the issue: "Bad method signatures on component functions"
refs #2175
=> (fix) Bad method signatures on component functions

ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.scss
=> breadcrumb style enhancements

scripts/extract-langs.sh, scripts/import-langs.sh
> - [] Tests for the changes have been added (for bug fixes / features)
> - [] Docs have been added / updated (for bug fixes / features)
> - [] Bugfix
> - [] Feature
> - [] Code style update (formatting, local variables)
> - [] Refactoring (no functional changes, no api changes)
> - [] Build related changes
> - [] Documentation
Added two scripts to extract and import i18n files from the project into a directory structure the i18n team expects for their tooling.
=> Add scripts to help the i18n team extract and import stings

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/index.ts, ng2-components/ng2-activiti-tasklist/src/components/no-task-detail-template.directive.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/people-search.component.css, ng2-components/ng2-activiti-tasklist/src/components/people-search.component.html, ng2-components/ng2-activiti-tasklist/src/components/people-search.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/people-search.component.ts, ng2-components/ng2-activiti-tasklist/src/components/people.component.html, ng2-components/ng2-activiti-tasklist/src/components/people.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.css, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/task-header.component.css, ng2-components/ng2-activiti-tasklist/src/components/task-header.component.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json
- added clickable in header-assignee property of task-header component based on task status
- changed people-search component to change the header based on type
- implemented assign task to user component in task-details component
- added test case for the changes related to assign task to user
=> [ADF-1088] Task Header in TaskDetails component shows Assignee but is not editable

ng2-components/ng2-alfresco-core/src/models/file.model.ts, ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.html, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.ts
=> [ADF-1348] Upload Dialog - 'Cancel All' button does not render

ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.ts
configure i18n service for pagination
=> [ADF-1354] fix pagination i18n setup

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.html, ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.ts, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.ts, ng2-components/ng2-alfresco-upload/src/i18n/en.json
=> [ADF-1358] Upload Dialog - Uploaded indicator should take in consideration cancelled files

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.scss
=> [ADF-1366] Upload Dialog - Prevent color inheritance

demo-shell-ng2/app/vendor.ts
Fix issue with pdf worker not being loaded.
=> [ADF-1370] fix the pdf worker setup

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
- fix the issue with unselecting the row on double-click
- allow unselecting the rows with multi-selection and modifier key
=> [ADF-1234] selection management enhancements for DT/DL

demo-shell-ng2/app/components/files/files.component.html, ng2-components/ng2-alfresco-upload/README.md, ng2-components/ng2-alfresco-upload/index.ts, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.html, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts, ng2-components/ng2-alfresco-upload/src/material.module.ts
Allow setting custom tooltips via `tooltip` property
=> [ADF-1372] support for tooltips (Upload button)

demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts, ng2-components/ng2-alfresco-core/src/components/data-column/data-column.component.ts, ng2-components/ng2-alfresco-datatable/README.md, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts, ng2-components/ng2-alfresco-datatable/src/data/datatable-adapter.ts, ng2-components/ng2-alfresco-datatable/src/material.module.ts, ng2-components/ng2-alfresco-documentlist/README.md
- Support for tooltip formatters
- Material tooltips support for DataTable and DocumentList
- Demo shell enhancements to demonstrate custom tooltips
=> [ADF-1021] custom tooltip formatter for data columns

ng2-components/ng2-activiti-analytics/README.md, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.ts, ng2-components/ng2-activiti-analytics/src/components/widgets/date-range/date-range.widget.html, ng2-components/ng2-activiti-analytics/src/components/widgets/date-range/date-range.widget.ts
> - [ ] Bugfix
Remove debug option from adf-analytics is a unique behaviour that we don't want support …
=> [ADF-520] remove debug option analytics

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/resources/i18n/en.json
> - [x] Bugfix
replace mdl tab with Material2 tab
https://issues.alfresco.com/jira/browse/ADF-1052 …
=> [ADF-1052] replace mdl tab with Material2 tab

ng2-components/ng2-activiti-tasklist/src/components/start-task.component.ts, ng2-components/ng2-activiti-tasklist/src/services/tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/tasklist.service.ts
> - [ ] Bugfix
Is not possible to assigne a task to an User is the user doesn't have a valid email …
=> [ADF-1316] Start task - Add a new service assignByUserId

ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.scss, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts, ng2-components/ng2-activiti-analytics/src/i18n/en.json, ng2-components/ng2-activiti-analytics/src/i18n/it.json
> - [x] Bugfix
replace header analytics with adf-toolbar
> - [ ] Yes
> - [x] No
If this PR …
=> [ADF-1395] replace header analytics with adf-toolbar

ng2-components/ng2-activiti-form/index.ts, ng2-components/ng2-activiti-form/src/components/form-list.component.spec.ts, ng2-components/ng2-activiti-form/src/components/material.module.ts, ng2-components/ng2-activiti-form/src/components/start-form.component.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.scss, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.spec.ts
> - [X] Bugfix
placeholder overlapping the label in the form component
Fix placeholder …
=> [ADF-1384] fix placeholder overlapping with label in form

demo-shell-ng2/app/components/tag/tag.component.css, demo-shell-ng2/app/components/tag/tag.component.html, ng2-components/ng2-alfresco-tag/index.ts, ng2-components/ng2-alfresco-tag/src/components/material.module.ts, ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.css, ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.html, ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.scss, ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.spec.ts, ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.ts, ng2-components/ng2-alfresco-tag/src/components/tag-list.component.html, ng2-components/ng2-alfresco-tag/src/components/tag-list.component.scss, ng2-components/ng2-alfresco-tag/src/components/tag-list.component.spec.ts, ng2-components/ng2-alfresco-tag/src/components/tag-list.component.ts, ng2-components/ng2-alfresco-tag/src/components/tag-node-list.component.css, ng2-components/ng2-alfresco-tag/src/components/tag-node-list.component.html, ng2-components/ng2-alfresco-tag/src/components/tag-node-list.component.scss, ng2-components/ng2-alfresco-tag/src/components/tag-node-list.component.spec.ts, ng2-components/ng2-alfresco-tag/src/components/tag-node-list.component.ts
> - [ ] Bugfix
move from mdl to Material2 from tag component
> - [ ] Yes
> - [x] No
If this PR …
=> [ADF-1240] move from mdl to Material2 from tag component

ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.scss, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.scss, ng2-components/ng2-activiti-form/src/components/widgets/error/error.component.scss, ng2-components/ng2-activiti-form/src/components/widgets/error/error.component.ts
> - [x] Bugfix
fix error and amount widget style problem
> - [ ] Yes
> - [ ] No
If this PR contains a breaking change, please describe the impact and migration path for existing …
=> [ADF-1384] fix error and amount widget style problem

ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.scss, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.scss
> - [x] Bugfix
Different issues relating to the styling of the activiti form.
ADF …
=> [ADF-1329] Fix grid style in the activiti form

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-types.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts
> - [x] Bugfix
Group type was not treated as a container type.
Now, it is.
**Does this …
=> [ADF-1327] Fix group form field type to be treated as a container

ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.html
> - [x] Bugfix
See: https://issues.alfresco.com/jira/browse/ADF-1328
Behaviour is …
=> [ADF-1328] - Fix multiline text issues in activiti form

ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.ts, ng2-components/ng2-activiti-diagrams/src/components/tooltip/diagram-tooltip.component.ts
> - [X] Bugfix
The tooltip was showed on the bottom of element and sometimes drops on the bottom of the screen
**What …
=> [ADF-1096] added cursor strategy to diagram tooltip

ng2-components/ng2-alfresco-viewer/src/components/viewer-dialog.component.html, ng2-components/ng2-alfresco-viewer/src/components/viewer-dialog.component.scss, ng2-components/ng2-alfresco-viewer/src/components/viewer-dialog.component.ts
Add support for basic mime types for Viewer Dialog demo
=> support for basic mime types in Viewer dialog

ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.html, ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.ts
> - [x] Bugfix
See the issues listed in the header
Every issue has been fixed
**Does …
=> [ADF-1420] - Fix for 1420, 1425, 1426 and 1428 issues

demo-shell-ng2/app/app.module.ts, demo-shell-ng2/app/components/activiti/form-node-viewer.component.ts, demo-shell-ng2/app/components/activiti/form-viewer.component.ts, demo-shell-ng2/app/components/form/form-list-demo.component.ts, demo-shell-ng2/app/components/settings/settings.component.ts, demo-shell-ng2/app/components/theme-picker/theme-picker.ts, ng2-components/ng2-activiti-diagrams/src/components/tooltip/diagram-tooltip.component.ts
=> Bug fixes on the demo shell

demo-shell-ng2/app/theme.scss
=> Add undescore before color.scss

demo-shell-ng2/app/theme.scss, demo-shell-ng2/config/webpack.common.js, demo-shell-ng2/config/webpack.dev.js, demo-shell-ng2/config/webpack.prod.js
=> ADF Theme Dev/Prod mode

demo-shell-ng2/app/theme.scss
=> ADF Theme - Rollback underscore change

ng2-components/ng2-alfresco-login/src/components/login.component.html
=> Switching data automation id password for show/hide password.

scripts/npm-publish.sh
=> removing the directive to remove the node_modules folder

ng2-components/ng2-alfresco-documentlist/index.ts
=> [ADF-1465] Document List - Export NodeActionsService

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.html, ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.scss, ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.spec.ts, ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.ts, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list-row.component.scss, ng2-components/ng2-alfresco-upload/src/i18n/en.json
=> [ADF-1457] Upload Dialog - Cancel all confirmation dialog

ng2-components/ng2-activiti-tasklist/src/components/start-task.component.html, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.ts
> - [x] Bugfix
Create task form does not respond if task is created without assignee
* …
=> [ADF-1432] Can not create a task

ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.scss, ng2-components/ng2-alfresco-upload/src/components/file-uploading-list-row.component.scss
=> [ADF-1468] Upload Dialog - Remove import colors

ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.scss, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts, ng2-components/ng2-alfresco-documentlist/src/services/node-actions.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1364
Styling is fixed …
=> [ADF-1364] - Fix pagination styling issues in documentlist and copy & move

demo-shell-ng2/app/components/login/login-demo.component.css, demo-shell-ng2/app/components/login/login-demo.component.html
> - [X] Bugfix
On the demo shell when a switch provider is clicked the value is changed but not the status.
**What is …
=> [ADF-1454] resolved login switch problem

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.scss
Fix border overlapping for DataTable rows
=> [ADF-1476] border style fixes for data table rows

ng2-components/ng2-activiti-form/src/components/widgets/content/content.widget.html
> - [ ] Bugfix
CSRA 508 change to add alt tags for thumbnals
=> Activiti Form - Alt tag added for thumbnail preview

demo-shell-ng2/app/components/activiti/activiti-demo.component.css, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/index.ts
Add missing properties about the pagination inside the tasklist readme
> - [x] Bugfix
The pagination isn't correctly …
=> [ADF-1309] Fix demo shell pagination style

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
> - [ ] Bugfix
> - [X ] Other... Please describe:
Redid the fork to get past all the rebasing.
508 changes for the datatable
=> Added Tabbing to datatable and keyboard functionality

ng2-components/README.md, ng2-components/config/custom-loaders/generateListComponent.js
> - [x] Bugfix
README index contained no links. This was due to a problem with ng2-components/config/custom-loaders/generateListComponent.js. Regular expressions in the code didn't take both …
=> [ADF-1453] Restructure README.md files

demo-shell-ng2/app/components/activiti/activiti-demo.component.css, ng2-components/ng2-activiti-tasklist/src/components/task-filters.component.html, ng2-components/ng2-activiti-tasklist/src/components/task-filters.component.scss
> - [x] Bugfix
> - [ ] Other... Please describe
Padding is missing in task fillters
* Fixed padding
* Migrated from mdl …
=> [ADF-1480] Padding is missing from Task List

demo-shell-ng2/package-lock.json, demo-shell-ng2/package.json
fixes console warning:
[DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
=> update wsrv version to fix warnings

demo-shell-ng2/app/components/files/files.component.css, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.scss
- fix issue with screen reader label not being translated
- fix issue with column taking the width of the screen reader label
=> fix issues with the icons column in DT/DL

ng2-components/ng2-activiti-tasklist/src/components/checklist.component.ts
> - [ ] Bugfix
The placeholder remains on the page
FIx the mdl issue but in the new …
=> [ADF-1487] ADF checklist - fix mdl issue

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
> - [X] Bugfix
An error was thrown when user click on process task to see the task details. …
=> [ADF-1442] added selectedIndex managing for tab group on activiti demo

ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.scss
> - [x] Bugfix
Report title is not aligned
* Fixed report title alignment
**Does this …
=> [ADF-1407] Editing a Report title should be aligned

ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1497
Issue is fixed. …
=> [ADF-1497] Fix wrong empty folder message

ng2-components/ng2-activiti-analytics/src/components/widgets/date-range/date-range.widget.html, ng2-components/ng2-activiti-form/index.ts, ng2-components/ng2-activiti-form/src/components/widgets/hyperlink/hyperlink.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/hyperlink/hyperlink.widget.scss, ng2-components/ng2-activiti-processlist/src/components/process-attachment-list.component.ts, ng2-components/ng2-activiti-processlist/src/components/process-instance-variables.component.html, ng2-components/ng2-activiti-processlist/src/services/process.service.ts, ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.ts, ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.html, ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.html, ng2-components/ng2-alfresco-login/index.ts, ng2-components/ng2-alfresco-login/src/components/login.component.html, ng2-components/ng2-alfresco-login/src/components/login.component.spec.ts, ng2-components/ng2-alfresco-login/src/components/login.component.ts, ng2-components/ng2-alfresco-login/src/directives/login-footer.directive.spec.ts, ng2-components/ng2-alfresco-login/src/directives/login-header.directive.spec.ts, ng2-components/ng2-alfresco-login/src/material.module.ts, ng2-components/ng2-alfresco-search/index.ts, ng2-components/ng2-alfresco-search/src/components/search-control.component.html, ng2-components/ng2-alfresco-search/src/components/search.component.ts
Fixed code to make it compatible with AoT static checks (Angular CLI)
=> [ADF-1502] Fixes for AoT checks in Angular CLI

ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.scss
=> [ADF-1498] fix pagination height missalignment 

ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1500
Fixed
**Does this …
=> [ADF-1500] Table header fix

ng2-components/ng2-activiti-processlist/src/components/process-filters.component.html, ng2-components/ng2-activiti-processlist/src/components/process-filters.component.scss
=> [ADF-1494] Processlist Filter - Fix padding

ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-indigo-pink.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-pink-bluegrey.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-purple-green.css, ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.scss
=> [ADF-1498] fix pagination

demo-shell-ng2/app/components/files/files.component.html, ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.spec.ts, ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.ts, ng2-components/ng2-alfresco-upload/README.md, ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts, ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
> - [X] Bugfix
restoring wrong changes applied by ADF-1458 …
=> [ADF-1458] revert changes applied for upload button

ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.scss, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/error/error.component.scss, ng2-components/ng2-activiti-form/src/components/widgets/functional-group/functional-group.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.scss, ng2-components/ng2-activiti-form/src/components/widgets/number/number.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.scss, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/radio-buttons/radio-buttons.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.html
=> [ADF-1512] fixed required style problem and others minor twitch for form

ng2-components/ng2-activiti-tasklist/src/components/checklist.component.css, ng2-components/ng2-activiti-tasklist/src/components/checklist.component.html, ng2-components/ng2-activiti-tasklist/src/components/checklist.component.ts
=> [ADF-1487] Checklist - Remove MDL from input field and use MD

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, demo-shell-ng2/app/components/form/form-demo.component.html, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1509 …
=> [ADF-1509] clean form name in task header only when change task id

ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-indigo-pink.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-pink-bluegrey.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-purple-green.css, ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer-layout.component.scss, ng2-components/ng2-alfresco-core/styles/_index.scss
=> add dynamic color background info drawer

demo-shell-ng2/app/components/form/form-list-demo.component.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1513 …
=> [ADF-1513] fix tab form service

appveyor.yml, demo-shell-ng2/app/components/activiti/activiti-demo.component.css, demo-shell-ng2/app/components/activiti/activiti-demo.component.html, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-indigo-pink.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-pink-bluegrey.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-purple-green.css, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.scss, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.scss, ng2-components/ng2-alfresco-documentlist/styles/index.scss
=> fix minor theming issues

ng2-components/ng2-alfresco-login/src/components/login.component.scss
> - [x] Bugfix
Styling issues are present.
Styling issues are not present.
**Does this …
=> Fix different styling issues after upgrading to 1.8

ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.ts
> - [X] Bugfix
an invalid date wasn't correctly saved onto form fields.
The validation was not applied
**What is the …
=> [ADF-1499] fixed validation and value setting on date widget

ng2-components/ng2-alfresco-core/src/components/view/card-view-textitem.component.scss, ng2-components/ng2-alfresco-core/src/components/view/card-view.component.scss, ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.scss, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.scss
> - [x] Bugfix
As described in the title
As described in the title
**Does this PR …
=> Remove piercing operators from components which lost the encapsulation

ng2-components/ng2-alfresco-core/src/utils/momentDateAdapter.ts
> - [X] Bugfix
When user chose a day between 1-12 clicking again on the date widget will make the date swap
**What is …
=> [ADF-1516] added parsing on date check

demo-shell-ng2/app/components/login/login-demo.component.html, ng2-components/ng2-alfresco-login/README.md, ng2-components/ng2-alfresco-login/index.ts, ng2-components/ng2-alfresco-login/src/components/login.component.spec.ts, ng2-components/ng2-alfresco-login/src/components/login.component.ts, ng2-components/ng2-alfresco-login/src/directives/login-footer.directive.spec.ts, ng2-components/ng2-alfresco-login/src/directives/login-header.directive.spec.ts
> - [x]  The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Bugfix
It is now possible to define a route that is used to redirect the page …
=> [ADF-1524] support redirection on successful login

demo-shell-ng2/app/app.component.scss, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/date/date.editor.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/row.editor.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/index.ts, ng2-components/ng2-activiti-form/src/events/validate-dynamic-table-row.event.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
> - [ ] Bugfix
- Provide support for custom validation with Dynamic Table widget …
=> [ADF-1090] support custom dynamic table row validation

demo-shell-ng2/app/components/home/home.component.scss, ng2-components/ng2-activiti-analytics/src/components/analytics-generator.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.scss, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.scss, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts, ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts, ng2-components/ng2-activiti-analytics/src/components/analytics.component.html, ng2-components/ng2-activiti-analytics/src/components/widgets/checkbox/checkbox.widget.html, ng2-components/ng2-activiti-analytics/src/components/widgets/dropdown/dropdown.widget.scss, ng2-components/ng2-activiti-analytics/src/components/widgets/duration/duration.widget.html, ng2-components/ng2-activiti-analytics/src/components/widgets/duration/duration.widget.scss, ng2-components/ng2-activiti-analytics/src/components/widgets/number/number.widget.html, ng2-components/ng2-activiti-analytics/src/components/widgets/number/number.widget.scss, ng2-components/ng2-activiti-analytics/src/components/widgets/number/number.widget.ts, ng2-components/ng2-activiti-analytics/src/material.module.ts
> - [ ] Bugfix
Mdl is present in the code.
Mdl is NOT present in the code.
**Does this …
=> [ADF-1250] Remove MDL from Analytics

ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.html, ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1478
Fixed
**Does this …
=> [ADF-1478] Make the pagination more responsive

ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1444
Fixed
**Does this …
=> [ADF-1444] Fix name display issue

demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts
Removes unused checkbox. This is a "demo shell"-only change.
=> [ADF-1496] remove unused checkbox from demo shell

ng2-components/ng2-alfresco-viewer/src/components/viewer-dialog/viewer-dialog.component.html, ng2-components/ng2-alfresco-viewer/src/components/viewer-dialog/viewer-dialog.component.ts, ng2-components/ng2-alfresco-viewer/src/components/viewer-dialog/viewer-dialog.settings.ts, ng2-components/ng2-alfresco-viewer/src/services/viewer.service.ts
**Please check if the PR fulfils these requirements**
> - [ ] Bugfix
Allows toggling toolbar elements for the Viewer Dialog when using Viewer …
=> [ADF-1542] allow toggling viewer dialog toolbar elements

ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts
=> [ADF-1537] The people input field should be present

ng2-components/ng2-activiti-form/src/components/form.component.ts, ng2-components/ng2-activiti-form/src/services/form-rendering.service.ts, ng2-components/ng2-activiti-tasklist/src/components/tasklist.component.ts
> - [ ] Bugfix
The form type string is not checked
The form type string is checked …
=> [ADF-1521] Form string type is not rendered

demo-shell-ng2/app/app.module.ts, demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.scss, demo-shell-ng2/package.json
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1526
Fixed
**Does this …
=> [ADF-1526] Fix minimal responsiveness of demo app's activiti section

ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1479
> - [ ] Yes
> - [ ] No
If this …
=> [ADF-1479] Fix change page size 

demo-shell-ng2/app/app.module.ts, ng2-components/ng2-alfresco-userinfo/index.ts
> - [x] Bugfix
Rename UserInfoComponentModule to UserInfoModule
**Does this PR …
=> [ADF-1504] change name export module userinfo

ng2-components/ng2-activiti-analytics/src/i18n/en.json, ng2-components/ng2-activiti-form/src/i18n/en.json, ng2-components/ng2-activiti-processlist/src/i18n/en.json, ng2-components/ng2-activiti-tasklist/src/i18n/en.json, ng2-components/ng2-alfresco-datatable/src/i18n/en.json, ng2-components/ng2-alfresco-documentlist/src/i18n/en.json, ng2-components/ng2-alfresco-login/src/i18n/en.json, ng2-components/ng2-alfresco-search/src/i18n/en.json, ng2-components/ng2-alfresco-tag/src/i18n/en.json, ng2-components/ng2-alfresco-upload/src/i18n/en.json
Updates to the l18n files for ADF-1515
=> [ADF-1515] Internationalization - ADF strings review

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.scss, demo-shell-ng2/app/components/about/about.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-process-attachments.component.html, demo-shell-ng2/app/components/activiti/activiti-show-diagram.component.html, demo-shell-ng2/app/components/activiti/activiti-task-attachments.component.html, demo-shell-ng2/app/components/activiti/form-node-viewer.component.html, demo-shell-ng2/app/components/activiti/form-viewer.component.html, demo-shell-ng2/app/components/datatable/datatable-demo.component.css, demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/login/login-demo.component.html, demo-shell-ng2/app/components/search/search-bar.component.html, demo-shell-ng2/app/components/search/search.component.html, demo-shell-ng2/app/components/search/search.component.scss, demo-shell-ng2/app/components/search/search.component.ts, demo-shell-ng2/app/components/tag/tag.component.html, ng2-components/ng2-alfresco-search/src/components/search-control.component.html, ng2-components/ng2-alfresco-search/src/components/search-control.component.scss
remove old alfresco and activiti prefix
fix login toggle mobile devices
> - [x] Bugfix
fix toolbar and page port view for size in small devices
remove old alfresco …
=> [ADF-ADF-1553] Fix toolbar and page port view for size in small devices

ng2-components/ng2-activiti-tasklist/src/services/people.service.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
- fix issues with selection management
- fix unit tests for People apis
=> [ADF-1488] reset selection on Document List data change

demo-shell-ng2/app/components/activiti/activiti-process-attachments.component.html, demo-shell-ng2/app/components/activiti/activiti-process-attachments.component.ts, demo-shell-ng2/app/components/activiti/activiti-task-attachments.component.html, demo-shell-ng2/app/components/activiti/activiti-task-attachments.component.ts, ng2-components/ng2-activiti-processlist/src/components/process-attachment-list.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.spec.ts
> - [ ] Bugfix
the drag and drop is shown
the drag and drop is not shown
**Does this …
=> [ADF-1503] Task/Process Attachments - Disable when the task/process is completed

ng2-components/ng2-activiti-form/src/components/widgets/error/error.component.scss, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.html, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.scss, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-indigo-pink.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-pink-bluegrey.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-purple-green.css
=> [ADF-1570] Start Task - Align due date field

demo-shell-ng2/app/components/activiti/activiti-process-attachments.component.html, demo-shell-ng2/app/components/activiti/activiti-task-attachments.component.html
=> [ADF-1503] Attachment list component - Disable drag drop component for completed process/task

demo-shell-ng2/config/webpack.common.js
- adds extra settings for demo shell to solve the issues with native login dialogs while REPO team fiexes underlying issues.
- enable support for running demo shell against remote servers (backends)
=> proxy setup to fix native login dialog (for local runs)

docs/document-list.component.md, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-indigo-pink.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-pink-bluegrey.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-purple-green.css, ng2-components/ng2-alfresco-core/src/components/pagination/infinite-pagination.component.html, ng2-components/ng2-alfresco-core/src/components/pagination/infinite-pagination.component.scss, ng2-components/ng2-alfresco-core/src/components/pagination/infinite-pagination.component.spec.ts, ng2-components/ng2-alfresco-core/src/components/pagination/infinite-pagination.component.ts, ng2-components/ng2-alfresco-core/src/components/pagination/pagination.module.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable-cell.component.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts, ng2-components/ng2-alfresco-documentlist/README.md, ng2-components/ng2-alfresco-documentlist/index.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.html, ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.scss, ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.ts, ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.service.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts, ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts, ng2-components/ng2-alfresco-documentlist/src/i18n/en.json
> - [x] Bugfix
Pagination is not working for the copy&move dialog properly
Infinite …
=> [ADF-1364] Infinite scrolling for Copy & Move

docs/task-header.component.md, ng2-components/ng2-activiti-tasklist/README.md, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/task-header.component.html, ng2-components/ng2-activiti-tasklist/src/components/task-header.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/task-header.component.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json, ng2-components/ng2-activiti-tasklist/src/services/tasklist.service.spec.ts, ng2-components/ng2-activiti-tasklist/src/services/tasklist.service.ts
> - [ ] Bugfix
Requeue button is not there.
Requeue button is there.
**Does this PR …
=> [ADF-226] Add requeue button to task header

demo-shell-ng2/app/components/search/search-bar.component.html, demo-shell-ng2/app/components/search/search-bar.component.ts, docs/search-control.component.md, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-indigo-pink.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-pink-bluegrey.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-purple-green.css, ng2-components/ng2-alfresco-documentlist/index.ts, ng2-components/ng2-alfresco-search/README.md, ng2-components/ng2-alfresco-search/src/components/search-autocomplete.component.html, ng2-components/ng2-alfresco-search/src/components/search-autocomplete.component.ts, ng2-components/ng2-alfresco-search/src/components/search-control.component.html, ng2-components/ng2-alfresco-search/src/components/search-control.component.scss, ng2-components/ng2-alfresco-search/src/components/search-control.component.spec.ts, ng2-components/ng2-alfresco-search/src/components/search-control.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1238
https://issues.alfresco.com/jira/browse/ADF-1557
Expandable parameter has been removed 
**Does this …
=> [ADF-1238] Search debounce click issue fix and minor style clean

demo-shell-ng2/app/components/settings/settings.component.html, demo-shell-ng2/app/components/settings/settings.component.ts
Apply should be disable if there is an error
> - [ ] Bugfix
The changes are saved also when the back button is …
=> [ADF-1581] Demo shell - Improve host setting configuration check

ng2-components/ng2-activiti-form/src/components/form.component.scss, ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.scss, ng2-components/ng2-activiti-form/src/components/widgets/error/error.component.scss, ng2-components/ng2-activiti-tasklist/src/components/start-task.component.scss, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-indigo-pink.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-pink-bluegrey.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-purple-green.css
> - [x] Bugfix
Styling issues, see: https://issues.alfresco.com/jira/browse/ADF-1582 …
=> [ADF-1582] Revert error widget style modification

ng2-components/ng2-activiti-processlist/src/components/process-instance-tasks.component.html
=> [ADF-1580] Demo shell - Call start form with processInstance instead of processDefinition

ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.scss
> - [x] Bugfix
#https://issues.alfresco.com/jira/browse/ADF-1590
**Does this PR …
=> [ADF-1590] Cursor pointer is not displayed on expand/collapse Task and Process Filters

ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-indigo-pink.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-pink-bluegrey.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-purple-green.css, ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1590
Fixed
**Does this …
=> [ADF-1590] Fix styles for task and process list accordion

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
> - [ ] Bugfix
The active task is not displayed 
The active task is correct displayed …
=> [ADF-1561] Demo shell - Check taskList exist

ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-orange.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-purple.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-indigo-pink.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-pink-bluegrey.css, ng2-components/ng2-alfresco-core/prebuilt-themes/adf-purple-green.css, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1585
Styles are fixed. …
=> [ADF-1585] - Fix datatable styles

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1577
Fixed.
**Does this …
=> [ADF-1577] Show missing list after starting a process

ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1594
Fixed.
**Does this …
=> [ADF-1594] Fix datewidget's moment issue

ng2-components/ng2-activiti-tasklist/src/components/comment-list.component.html, ng2-components/ng2-activiti-tasklist/src/components/comment-list.component.scss, ng2-components/ng2-activiti-tasklist/src/i18n/en.json
> - [ ] Bugfix
> - [ X] Other... Please describe:
Added comments titles and translation hooks
508 compliant
> - [ ] Yes
> - [ X] No
=> Update to comments for 508 compliance with translation

ng2-components/ng2-activiti-form/src/assets/entry-module.mock.ts, ng2-components/ng2-activiti-form/src/assets/start-form.component.mock.ts, ng2-components/ng2-activiti-form/src/components/start-form.component.spec.ts
=> [ADF-1608] Start Form - Improve the unit test cases.

ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.html, ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.scss
Fixed issue with long report names
=> [ADF-1562] fix layout issues for report list

ng2-components/ng2-alfresco-core/src/dialogs/download-zip.dialog.ts, ng2-components/ng2-alfresco-core/src/i18n/en.json
=> [ADF-1616] UA review of Download as ZIP title

ng2-components/ng2-alfresco-documentlist/src/components/content-action/content-action.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1506
Fixed
**Does this …
=> [ADF-1506] Fix shared service design issue

demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts, ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer.component.spec.ts, ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.spec.ts, ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1583
Fixed
**Does this …
=> [ADF-1583] Fix change detection error (the quick way)

docs/datatable.component.md, ng2-components/ng2-activiti-tasklist/src/components/tasklist.component.html, ng2-components/ng2-activiti-tasklist/src/components/tasklist.component.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
> - [ ] Bugfix
- new `row-keyup` bubbling DOM event for DataTable
- TaskList updates …
=> [ADF-1610] raise keyboard events, improve task list keyboard handling

demo-shell-ng2/app.config-dev.json, demo-shell-ng2/app.config-prod.json, demo-shell-ng2/app/app.component.ts, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/services/app-config.service.ts, ng2-components/ng2-alfresco-core/src/services/page-title.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/page-title.service.ts
- page title service (ported from SFS)
=> [ADF-1622] page title service

ng2-components/ng2-alfresco-core/src/services/auth-guard-ecm.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/auth-guard-ecm.service.ts
- improved validation and redirection for ecm guard auth (ported from the SFS)
=> [ADF-1621] improved ecm auth guard

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.scss, demo-shell-ng2/app/app.component.ts, demo-shell-ng2/app/app.routes.ts, demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts, demo-shell-ng2/app/material.module.ts, demo-shell-ng2/app/theme.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1611
Responsiveness …
=> [ADF-1611] Adding some responsiveness to demo shell app

demo-shell-ng2/app/app.component.html, demo-shell-ng2/app/app.component.scss, demo-shell-ng2/app/app.component.ts, demo-shell-ng2/app/app.routes.ts, demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.ts, demo-shell-ng2/app/material.module.ts, demo-shell-ng2/app/theme.scss
Reverts Alfresco/alfresco-ng2-components#2408
=> Revert "[ADF-1611] Adding some responsiveness to demo shell app"

ng2-components/ng2-activiti-tasklist/src/components/task-header.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/task-header.component.ts
> - [ ] Bugfix
If the task doesn't have a process the parent name is blank
Task Header …
=> [ADF-1632] Task Header - The default parent name value should be None

ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1628
Fixed
**Does this …
=> [ADF-1628] Fix selection reset issue

ng2-components/ng2-alfresco-search/src/components/search-control.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1631
Fixed
**Does this …
=> [ADF-1631] Fix input line-height issue

ng2-components/ng2-activiti-processlist/src/components/processlist.component.html, ng2-components/ng2-activiti-processlist/src/components/processlist.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/processlist.component.ts, ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1626
Fixed
**Does this …
=> [ADF-1626] Fix double tabbing issue in datatable

demo-shell-ng2/app/app.component.ts, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/services/page-title.service.spec.ts, ng2-components/ng2-alfresco-core/src/services/page-title.service.ts
=> add suffix page title service

ng2-components/ng2-alfresco-login/src/components/login.component.html, ng2-components/ng2-alfresco-login/src/components/login.component.scss
> - [x] Bugfix
Error messages change the  size of login component
Fix error message …
=> [ADF-1642] Fix error message size

docs/data-column.component.md, docs/document-list.component.md, docs/login.component.md, docs/metadata-indicators.md, docs/task-details.component.md, docs/viewer.component.md
> - [ ] Bugfix
remove all the reference to deprecated <template> from the documentation …
=> [ADF-1603] remove all the reference to deprecated <template> from the documentation

ng2-components/ng2-activiti-form/src/components/form.component.ts, ng2-components/ng2-activiti-tasklist/src/components/task-audit.directive.ts, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.ts, ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
> - [ ] Bugfix
remove unnecessary console log
> - [ ] Yes
> - [x] No
If this PR contains a …
=> remove console log

ng2-components/ng2-activiti-form/src/assets/formDefinition.mock.ts, ng2-components/ng2-activiti-form/src/assets/formDefinitionReadonly.mock.ts, ng2-components/ng2-activiti-form/src/assets/formDefinitionVisibiity.mock.ts, ng2-components/ng2-activiti-form/src/components/form.component.ts, ng2-components/ng2-activiti-form/src/components/form.component.visibility.spec.ts
> - [x] Bugfix
The visibiliti is checked after the form is rendered
Check the …
=> [ADF-1629] Form component - Check the visibility before rendering the form

ng2-components/ng2-alfresco-core/src/services/alfresco-api.service.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
> - [x] Bugfix
Support page number selector for document list …
=> [ADF-1637] support page picker for document list

demo-shell-ng2/app/components/files/files.component.html, demo-shell-ng2/app/components/files/files.component.scss, ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/dropdown-breadcrumb.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1630
Fixed
**Does this …
=> [ADF-1630] Fix breadcrumb responsiveness

ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
> - [ ] Bugfix
New page size now correctly preserved in user preferences and restored …
=> [ADF-1651] fix page size not being saved

ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.html, ng2-components/ng2-alfresco-userinfo/src/components/user-info.component.scss
> - [x] Bugfix
User info name is not centred
User info name is centred
**Does this PR …
=> [ADF-1662] [User info] name is not centred

docIndex.md, docs/data-column.component.md, docs/document-list.component.md, docs/permissions-style.model.md, docs/seeAlsoGraph.json
> - [ ] Bugfix
Moved content from Document List component page into Permission Style model and DataColumn.
> - [ ] Yes
> - [x] No
=> [ADF-1586] Added doc files for Document List library

ng2-components/ng2-alfresco-login/src/components/login.component.html, ng2-components/ng2-alfresco-login/src/components/login.component.scss, ng2-components/ng2-alfresco-login/src/components/login.component.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1664 …
=> [ADF-1664] fix color text login for dark theme

ng2-components/ng2-activiti-tasklist/src/i18n/en.json
A couple of very minor changes (I'll raise a Jira next time, sorry!)
=> Dev ahealey oct newstringsreview

demo-shell-ng2/app/components/form/form-list-demo.component.ts, ng2-components/ng2-activiti-form/src/services/assets/form.service.mock.ts, ng2-components/ng2-activiti-form/src/services/form.service.spec.ts, ng2-components/ng2-activiti-form/src/services/form.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1667 …
=> [ADF-1667] Form Demo - Fix Form Service parseForm

demo-shell-ng2/app/components/activiti/activiti-demo.component.html, demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1668 …
=> [ADF-1668] Demo shell - Change task/process details on double click

docIndex.md, docs/DataTableAdapter.md, docs/data-column.component.md, docs/datatable.component.md, docs/document-list.component.md, docs/seeAlsoGraph.json, docs/tasklist.component.md, docs/undocStoplist.json
> - [ ] Bugfix
DataTableAdapter docs moved from DataTable and expanded in DataTableAdapter.md. Links and reference from other docs updated.
> - [ ] Yes
> - [x] No
=> [ADF-1586] Updated Datatable docs

ng2-components/ng2-activiti-form/src/services/widget-visibility.service.spec.ts, ng2-components/ng2-activiti-form/src/services/widget-visibility.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1671 …
=> [ADF-1671] visibility fix use id instead of name during comparison

ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
=> [ADF-1677] fix issues with paging

demo-shell-ng2/app/components/about/about.component.html, demo-shell-ng2/app/components/about/about.component.ts, demo-shell-ng2/app/components/activiti/activiti-demo.component.html, ng2-components/ng2-activiti-processlist/src/components/process-instance-details.component.html, ng2-components/ng2-activiti-tasklist/src/assets/task-details.mock.ts, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.ts
> - [x] Bugfix
make comments always editable for process
make comments editable only when there are users involved …
=> [ADF-1666] Comments can not be added to completed tasks and processes

ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts, ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
fix pagination issue related to switching from standard source to an aliased one
=> [ADF-1677] pagination fixes

ng2-components/ng2-activiti-tasklist/src/assets/task-details.mock.ts, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.html, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.spec.ts, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.ts, ng2-components/ng2-activiti-tasklist/src/components/task-header.component.ts, ng2-components/ng2-activiti-tasklist/src/models/task-details.model.ts
> - [x] Bugfix
fix task comment when the task is running …
=> [ADF-1689] fix task comment when the task is running

ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts
> - [X] Bugfix
Field value is not correctly updated when the form field is cleared …
=> [ADF-1688] Update value for the form field when is empty string

ng2-components/ng2-activiti-form/index.ts, ng2-components/ng2-activiti-form/src/components/form-custom-button.directive.ts, ng2-components/ng2-activiti-form/src/components/start-form.component.html, ng2-components/ng2-activiti-form/src/components/start-form.component.ts, ng2-components/ng2-activiti-processlist/src/components/start-process.component.html, ng2-components/ng2-activiti-processlist/src/components/start-process.component.scss, ng2-components/ng2-activiti-processlist/src/components/start-process.component.ts, ng2-components/ng2-activiti-processlist/src/i18n/en.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1672
* Implemented New …
=> [ADF-1672] Start Process - Improve the look and feel

ng2-components/ng2-activiti-tasklist/src/components/task-details.component.html, ng2-components/ng2-activiti-tasklist/src/i18n/en.json, ng2-components/ng2-activiti-tasklist/src/i18n/it.json, ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer.component.html, ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer.component.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1697 …
=> [ADF-1697] ADF InfoDrawer - Title and tabs label must be localizable

demo-shell-ng2/app/components/activiti/demo-field-validator.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/error-message.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts, ng2-components/ng2-activiti-form/src/components/widgets/core/index.ts, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/error/error.component.html, ng2-components/ng2-activiti-form/src/components/widgets/error/error.component.ts, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts, ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.spec.ts, ng2-components/ng2-activiti-form/src/i18n/en.json
> - [ ] Bugfix
No translation is provided for form field validators
Translation is …
=> [ADF-1679] added translation for form field validators

docs/context-menu.directive.md, ng2-components/ng2-alfresco-core/src/components/context-menu/context-menu-holder.component.spec.ts, ng2-components/ng2-alfresco-core/src/components/context-menu/context-menu-holder.component.ts, ng2-components/ng2-alfresco-core/src/components/context-menu/context-menu.module.ts
=> [ADF-1708] Context Menu - Material Design implementation

demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
> - [X] Bugfix
Process list is not updated when a task is completed
Process list is …
=> [ADF-1663] refreshing process list when a task is completed

ng2-components/ng2-activiti-tasklist/src/components/apps-list.component.html, ng2-components/ng2-activiti-tasklist/src/components/apps-list.component.ts, ng2-components/ng2-activiti-tasklist/src/i18n/en.json, ng2-components/ng2-activiti-tasklist/src/i18n/it.json
> - [X] Bugfix
My Task app name is never translated
My Task app name is now translated …
=> [ADF-1707] added translation for My Task default app

ng2-components/ng2-activiti-processlist/src/assets/process.model.mock.ts, ng2-components/ng2-activiti-processlist/src/assets/process.service.mock.ts, ng2-components/ng2-activiti-processlist/src/components/processlist.component.spec.ts, ng2-components/ng2-activiti-processlist/src/components/processlist.component.ts, ng2-components/ng2-activiti-processlist/src/models/process-instance-filter.model.ts, ng2-components/ng2-activiti-processlist/src/services/process.service.spec.ts, ng2-components/ng2-activiti-processlist/src/services/process.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1716 …
=> [ADF-1716] ProcessList - Remove processDefinitionKey from Process Model

ng2-components/ng2-activiti-form/src/i18n/it.json
> - [ ] Bugfix
Added more translation keys. …
=> [ADF-1679] added it translation for form validator messages

demo-shell-ng2/app/components/files/files.component.scss, ng2-components/ng2-activiti-processlist/src/components/process-attachment-list.component.scss, ng2-components/ng2-activiti-tasklist/src/components/comment-list.component.scss, ng2-components/ng2-activiti-tasklist/src/components/people-search.component.scss, ng2-components/ng2-activiti-tasklist/src/components/people.component.scss, ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.scss, ng2-components/ng2-activiti-tasklist/src/components/task-details.component.scss
> - [x] Bugfix
Drop the deep combinator …
=> [ADF-1614] /deep/ combinator is no longer supported

demo-shell-ng2/app/components/files/files.component.scss
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ADF-1630
Fixed
**Does this …
=> [ADF-1630] Ultimate breadcrumb flex fix fox

demo-shell-ng2/app/components/files/files.component.html, docIndex.md, docs/node-favorite.directive.md, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/directives/node-favorite.directive.spec.ts, ng2-components/ng2-alfresco-core/src/directives/node-favorite.directive.ts
=> [ADF-1729] Mark Files and Folders as Favorite

demo-shell-ng2/app/components/social/social.component.html, demo-shell-ng2/app/components/social/social.component.scss, demo-shell-ng2/app/components/tag/tag.component.html, demo-shell-ng2/app/components/tag/tag.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1648 …
=> [ADF-1648] fix demo layout tag and social

ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.html, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.spec.ts, ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1722
**Does this PR …
=> [ADF-1684] [object Object] appears in People control when selecting the same name

demo-shell-ng2/app/components/files/custom-sources.component.html, demo-shell-ng2/app/components/files/custom-sources.component.ts, docIndex.md, docs/node-restore.directive.md, ng2-components/ng2-alfresco-core/index.ts, ng2-components/ng2-alfresco-core/src/directives/node-restore.directive.spec.ts, ng2-components/ng2-alfresco-core/src/directives/node-restore.directive.ts, ng2-components/ng2-alfresco-core/src/i18n/en.json
=> [ADF-1733] Restore files and folders from Trash
