- PREREQUISITES.md
Hi,
Some doc changes to point out that 5.2.a is needed and that the easiest way to enable CORS is via module JAR download and install
> Update to PREREQUISITES.md

- demo-shell-ng2/app/components/files/files.component.ts
- ng2-components/ng2-activiti-form/src/services/form.service.ts
- ng2-components/ng2-alfresco-documentlist/index.ts
Extends demo shell with BPM integration example for Document List
- tries reaching Activiti for published apps/processes and populates context/action menus for document list with demo actions based on process definition names.
- displays process definition id upon action execution
> Populate context/action menus with BPM process names

- ng2-components/ng2-activiti-form/README.md
- ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts
- ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts
- ng2-components/ng2-activiti-form/src/components/widgets/core/form-outcome-event.model.ts
- ability to prevent default outcome behaviour (i.e. custom validation)
- new ‘executeOutcome’ event for DocumentList
- unit tests
> #589 ability to prevent default outcome behaviour

- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.ts
> Dev valbano 897

- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/boolean/boolean.editor.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/boolean/boolean.editor.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/text/text.editor.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/text/text.editor.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
- use cross browser `event.target` instead of IE-specific
`event.srcElement`
refs #960
> fix: Cannot save a dynamic table if certain property types are added

- ng2-components/ng2-activiti-form/src/components/widgets/core/dynamic-table.model.ts
- ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.css
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/date/date.editor.html
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/date/date.editor.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/date/date.editor.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/text/text.editor.html
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/text/text.editor.ts
- fixed: validate and edit only editable date columns
- new: editable input for date column editor
- new: display required validation state for date editor (input field)
- new: date validation for manually inputed value
- fixed: min/max date ranges changed to (-100 years from now to +100 years
from now) for date widget and date column editor
- new: Horizontal scrollbar for dynamic table
- fixed: showing currently symbol for the rows (non-complete forms)
- new: currency symbol for the editor label (row editor)
refs #637
> Dynamic Table bug fixes

- ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.css
- ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.html
- material remove button (same look cross browser)
- word wrapping for long file names
closes #748
**Short name:**
**Long name:**
> attach widget improvements

- demo-shell-ng2/wsrv-config.json
- ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html
- ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
- ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.css
- ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.html
- ng2-components/ng2-activiti-tasklist/src/components/activiti-task-header.component.ts
- add support for displaying form name in task header (only when form
loaded)
- fix live reload for task-details component (demo shell)
- code improvements (including type-safe events)
refs #805
> display form name in task header

- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.ts
```
[ X ] Bugfix
[ ] Feature
```
Typeahead widget is not working on start process form
Typeahead widget is correctly populated
#1091 
- [ X ] No
> #1091 - fix typeahead widget

- .travis.yml
```
[x] Bugfix
[ ] Feature
```
#1102 Travis build must link the dependency alfresco-ng2-components-* package
```
```
> #1102 add link ng2-component dependecy during the build in travis

- demo-shell-ng2/app/app.component.css
- demo-shell-ng2/app/app.component.html
```
[x] Bugfix
[ ] Feature
```
on firefox / safari and ie user info profile button is shifted up
on all browsers should be now centered
#1033 
```
```
> #1033 - fix demo shell for user info profile icon

- ng2-components/ng2-activiti-tasklist/src/components/activiti-people-search.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
```
[x] Bugfix
[ ] Feature
```
Build broken in the following points:
```
src/components/activiti-people-search.component.spec.ts(104,21): error TS2339: Property 'value' does not exist on type 'Element'.
src/components/upload-button.component.ts(223,43): error TS2339: Property 'value' does not exist on type 'Observable<any>'.
src/components/upload-drag-area.component.ts(196,39): error TS2339: Property 'value' does not exist on type 'Observable<any>'.
```
**This PR introduces a breaking change:** (check one …
> fix any type build

- ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.css
- ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html
```
[x] Bugfix
[ ] Feature
```
The dynamic table fields are not grayed when the task is completed
The dynamic table fields are grayed when the task is completed
https://github.com/Alfresco/alfresco-ng2-components/issues/1085
```
```
> greyed dynamic table fields

- ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.spec.ts
- ng2-components/ng2-activiti-form/src/services/activiti-alfresco.service.ts
- ng2-components/ng2-activiti-form/src/services/node.service.ts
- ng2-components/ng2-activiti-processlist/src/components/activiti-filters.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.spec.ts
- ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
- ng2-components/ng2-activiti-tasklist/src/components/activiti-filters.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
- ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthentication.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthentication.service.ts
- ng2-components/ng2-alfresco-core/src/services/AlfrescoContent.service.ts
- ng2-components/ng2-alfresco-documentlist/src/assets/document-list.service.mock.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-actions.service.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.ts
- ng2-components/ng2-alfresco-search/src/services/alfresco-search.service.spec.ts
- ng2-components/ng2-alfresco-search/src/services/alfresco-search.service.ts
- ng2-components/ng2-alfresco-webscript/src/webscript.component.ts
```
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
Remove deprecated use of getAlfrescoApi …
> Remove deprecated use of getAlfrescoApi() #1094

- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/demo/src/main.ts
- ng2-components/ng2-alfresco-documentlist/index.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.ts
- allow setting custom root path
- document-list module now re-exports datatable module (no need
importing it separately if document-list is already used)
- documentation updates and fixes
refs #1167
> document-list improvements

- demo-shell-ng2/app/components/files/files.component.css
- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/components/files/files.component.ts
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
- expose ‘error’ event
- change path only on successful navigation
- extend demo shell with error handling and reporting
- additional unit tests for document-list
> #159 improved error reporting for document-list

- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.css
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.html
adding top margin helps solving issue with horizontal scrollbar issue
for Safari when mouse is attached or system scrollbars visibility set
to ‘always’ (macOS)
fixes #986
> fix horizontal scrollbar issue for Safari

- demo-shell-ng2/app/app.component.html
- demo-shell-ng2/app/app.component.ts
- demo-shell-ng2/app/app.declarations.d.ts
- demo-shell-ng2/app/app.module.ts
- demo-shell-ng2/app/app.routes.ts
- demo-shell-ng2/app/components/home/home.component.html
- demo-shell-ng2/app/components/home/home.component.ts
- demo-shell-ng2/app/components/index.ts
- ng2-components/ng2-activiti-analytics/package.json
- ng2-components/ng2-activiti-diagrams/package.json
- ng2-components/ng2-activiti-form/package.json
- ng2-components/ng2-activiti-processlist/package.json
- ng2-components/ng2-activiti-tasklist/package.json
- ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.css
- ng2-components/ng2-activiti-tasklist/src/components/activiti-apps.component.html
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard-bpm.service.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard-ecm.service.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard.service.ts
- ng2-components/ng2-alfresco-core/src/services/index.ts
- ng2-components/ng2-alfresco-datatable/package.json
- ng2-components/ng2-alfresco-documentlist/package.json
- ng2-components/ng2-alfresco-login/package.json
- ng2-components/ng2-alfresco-search/package.json
- ng2-components/ng2-alfresco-tag/package.json
- ng2-components/ng2-alfresco-upload/package.json
- ng2-components/ng2-alfresco-userinfo/package.json
- ng2-components/ng2-alfresco-viewer/package.json
- ng2-components/ng2-alfresco-webscript/package.json
- auth guards for all routes 
- ecm/bpm related auth guards (redirect to login if ecm/bpm login required for current session)
- new Home page with summaries and redirects to features
- make app text white as per request
refs #1197 
Additional content:
**Home page**:
**CSS improvements**:
> Demo shell improvements

- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.css
```
[x] Bugfix
[ ] Feature
```
typeahead suggestions goes behind elements
the form resize to fit the suggestions , also added max-height to avoid to big resizing
```
[ ] Yes
[x ] No
```
**Other …
> #1165 - fixed overlay for typeahead

- demo-shell-ng2/app/app.routes.ts
- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/components/files/files.component.ts
- demo-shell-ng2/app/components/search/search-bar.component.html
- demo-shell-ng2/app/components/search/search-bar.component.ts
- demo-shell-ng2/app/components/search/search.component.html
- demo-shell-ng2/app/components/search/search.component.ts
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.ts
- ng2-components/ng2-alfresco-search/README.md
- ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.spec.ts
- ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.ts
- ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.ts
- ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.html
- ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.spec.ts
- ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.ts
- Uses router to pass ID of the folder
- Modified document list component to accept folder ID without path
- Current limitations
- Breadcrumb cannot currently be shown when navigating via folder id
- Clicking between folders does not update the current route
Refs #666
> Allow navigation to folders from search results

- ng2-components/ng2-alfresco-core/src/services/AlfrescoAuthentication.service.ts
- ng2-components/ng2-alfresco-core/src/services/AlfrescoContent.spec.ts
```
[x] Bugfix
[ ] Feature
```
1. Login to Activiti only
 2. Go to Login, switch off Activiti and enable ECM checkbox
 3. Login again
 4. Now isolated storage has 2 tickets, one for old activiti and one for new ecm
Login must cleanup everything on each Login
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, …
> Clean the login storage ticket info before to login

- demo-shell-ng2/config/webpack.common.js
- demo-shell-ng2/package.json
- exclude node_modules within every symlinked component library
- exclude source folders from watching (as needs getting bundles instead)
> exclude various folders from live reload

- demo-shell-ng2/app/components/search/search-bar.component.html
- demo-shell-ng2/app/components/search/search.component.html
- Currently it is necessary to destroy the viewer between views
Refs #1315
> Fix file viewer from search results the second time

- ng2-components/ng2-activiti-analytics/gulpfile.ts
- ng2-components/ng2-activiti-analytics/package.json
- ng2-components/ng2-activiti-diagrams/gulpfile.ts
- ng2-components/ng2-activiti-diagrams/package.json
- ng2-components/ng2-activiti-form/gulpfile.ts
- ng2-components/ng2-activiti-form/package.json
- ng2-components/ng2-activiti-processlist/gulpfile.ts
- ng2-components/ng2-activiti-processlist/package.json
- ng2-components/ng2-activiti-tasklist/gulpfile.ts
- ng2-components/ng2-activiti-tasklist/package.json
- ng2-components/ng2-alfresco-core/gulpfile.ts
- ng2-components/ng2-alfresco-core/package.json
- ng2-components/ng2-alfresco-datatable/gulpfile.ts
- ng2-components/ng2-alfresco-datatable/package.json
- ng2-components/ng2-alfresco-documentlist/gulpfile.ts
- ng2-components/ng2-alfresco-documentlist/package.json
- ng2-components/ng2-alfresco-login/gulpfile.ts
- ng2-components/ng2-alfresco-login/package.json
- ng2-components/ng2-alfresco-search/gulpfile.ts
- ng2-components/ng2-alfresco-search/package.json
- ng2-components/ng2-alfresco-tag/gulpfile.ts
- ng2-components/ng2-alfresco-tag/package.json
- ng2-components/ng2-alfresco-upload/gulpfile.ts
- ng2-components/ng2-alfresco-upload/package.json
- ng2-components/ng2-alfresco-userinfo/gulpfile.ts
- ng2-components/ng2-alfresco-userinfo/package.json
- ng2-components/ng2-alfresco-viewer/gulpfile.ts
- ng2-components/ng2-alfresco-viewer/package.json
- ng2-components/ng2-alfresco-webscript/gulpfile.ts
- ng2-components/ng2-alfresco-webscript/package.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
the UMD build rewrite the JS file in order to inject the template without regenerate the source map
Generate the sourcemap JS during the UMD build
```
[ ] Yes
[ ] No
``` …
> generate JS sourcemap during the UMD build

- ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
```
```
```
[x] Bugfix
[ ] Feature
```
typeahead widget is not showed on completed form
typeahead widget is showed on completed form …
> #1303 - fix typeahead show for completed tasks

- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/components/files/files.component.ts
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/demo/package.json
- ng2-components/ng2-alfresco-documentlist/demo/src/main.ts
- ng2-components/ng2-alfresco-documentlist/demo/tslint.json
- ng2-components/ng2-alfresco-documentlist/package.json
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-actions.service.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-actions.service.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.ts
refs #1366 
Addresses the following issues:
- DocumentList fails navigating user home subfolders #1366 
- Get the correct node path for a normal user #1280
- Document List should deal with node ID rather than path #505
- Custom root support for Breadcrumb #528
Greatly reduced Breadcrumb code, no more relative path parsing (`node.path` exposed by `alfresco-js-api` is used instead)
**Introduces breaking changes**:
- `currentFolderPath` property is no longer supported and replaced with a combination of `currentFolderId: string` and `folderNode: MinimalNodeEntryEntity` properties
> Node ID-based navigation for document list

- demo-shell-ng2/index.html
```
```
```
[x] Bugfix
[ ] Feature
```
Year picker not working for FF
Added missing polyfill for FF, refs #1403 …
> Add missing polyfill for Firefox (date picker)

- demo-shell-ng2/index.html
```
```
```
[x] Bugfix
[ ] Feature
```
Loading Bar doesn't appear anymore  at the beginning 
Show loading bar at beginning 
**Does this …
> #1297 Loading Bar doesn't appear anymore

- demo-shell-ng2/app/components/activiti/activiti-demo.component.html
- demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
- Ensures that the newly-started process is *always* shown
- No need to reload the list any more as not shown
- Filter component shows no selected filter when starting process
- User can exit Start Process by clicking a filter again
Refs #1332, #1307
> Hide the process list when starting and after started new process

- ng2-components/ng2-activiti-tasklist/src/components/activiti-people-search.component.ts
- ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.html
```
```
```
[x] Bugfix
[ ] Feature
```
Input search is not cleaned when the dialog is closed
Input search is cleaned when the dialog is …
> #1485 - add clean input search on close

- ng2-components/ng2-activiti-tasklist/src/components/activiti-people-search.component.html
- ng2-components/ng2-activiti-tasklist/src/components/activiti-people-search.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/activiti-people-search.component.ts
- ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.html
- ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/activiti-people.component.ts
- ng2-components/ng2-activiti-tasklist/src/i18n/en.json
- ng2-components/ng2-activiti-tasklist/src/i18n/it.json
```
```
```
[x] Bugfix
[ ] Feature
```
Message not translated. Searching a white space shows all the results. Clean search doesn't hide the results. …
> #1484 - clean search result when nothing is typed in the search input

- ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.html
- ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/i18n/en.json
```
```
```
[x] Bugfix
[ ] Feature
```
If no process definition are available an empty dropdown is showed and no message appear
If no …
> #1495 - Added no process definition message on start process

- demo-shell-ng2/app/components/files/files.component.ts
fixes ‘change detection’ crash in demo app (“Expression has changed after it was checked”) when using search with document list multiple times
> fix 'change detection crash' when using router multiple times

- ng2-components/ng2-alfresco-datatable/README.md
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
- ng2-components/ng2-alfresco-upload/README.md
- ng2-components/ng2-alfresco-upload/index.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
Refs #1559
**Breaking Changes**
- Input `UploadButtonComponent.showUdoNotificationBar` renamed to `showNotificationBar`
- Input `UploadDragAreaComponent.showUdoNotificationBar` renamed to `showNotificationBar`
- Input `DocumentListComponent.fallbackThubnail` renamed to `fallbackThumbnail`
> Fix typos in component properties

- ng2-components/ng2-alfresco-datatable/README.md
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
> ability to change position of the dropdown menu (left|right)

- ng2-components/ng2-activiti-analytics/src/assets/analyticsParamsReportComponent.mock.ts
- ng2-components/ng2-activiti-analytics/src/components/analytics-generator.component.ts
- ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts
- ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
#1631 
Should create an empty form when the process definitions are empty
**Does this PR …
> Analytics - Empty form 

- ng2-components/ng2-alfresco-core/src/components/context-menu/context-menu.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/components/context-menu/context-menu.directive.ts
- ng2-components/ng2-alfresco-datatable/README.md
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
refs #1677 
- new `contextMenu` property for DataTable to toggle custom menus
- allow native context menu for DataTable/DocumentList
> support for toggling custom context menu

- .vscode/settings.json
- ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.ts
- ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/number/number.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.html
refs #1720 
- fix ‘readonly highlighting when input fields loaded with values
- Start Form raises base ‘FormLoaded’ event (including FormService
emits)
> form component fixes

- demo-shell-ng2/app/components/files/files.component.html
- ng2-components/ng2-alfresco-core/README.md
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/directives/upload.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/upload.directive.ts
- ng2-components/ng2-alfresco-datatable/README.md
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.css
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.css
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.html
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
- ng2-components/ng2-alfresco-upload/src/directives/file-draggable.directive.spec.ts
- ng2-components/ng2-alfresco-upload/src/directives/file-draggable.directive.ts
- ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
refs #510 
- fix: Cannot upload the same folder in different subfolders (#1732)
- new core/UploadDirective to allow dropping files to any html element
- enhanced file dropping for DataTable rows (disabled by default)
- enhanced file dropping for DocumentList rows (disabled by default)
- upload drop area now handles file uploads for child elements (i.e.
rows in the document list)
Notes: only drop supported so far; the new directive only decorates existing html elements, it cannot modify DOM and so cannot inject `<input type=“file”>` to invoke a dialog.
> improved uploading of files

- ng2-components/ng2-alfresco-core/README.md
- ng2-components/ng2-alfresco-core/src/directives/upload.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/upload.directive.ts
refs #510 
- adds support for clicking to select files and/or folders (UploadDirective)
- allows decorating any elements with a click, drop or combined modes
- Safari compatibility for dropping files to folders
**what is not supported with this PR**:
- dropping external folders on folders to upload (will be a separate issue/pr)
> upload: new 'click' mode with file/folder dialog support

- ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.html
- ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.ts
- ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.css
- ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.html
- ng2-components/ng2-alfresco-upload/src/components/file-uploading-list.component.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.html
- ng2-components/ng2-alfresco-upload/src/i18n/en.json
- ng2-components/ng2-alfresco-upload/src/i18n/it.json
- ng2-components/ng2-alfresco-upload/src/i18n/ru.json
- ng2-components/ng2-alfresco-upload/src/services/upload.service.spec.ts
- ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
Various upload dialog improvements
- fix: headers alignment
- fix: Name column alignment
- fix: rename ‘CANCEL’ button to ‘Cancel all’ (as it’s what it does)
- fix: ‘Cancel all’ button still visible after all upload complete
- new: improved layout and api for file upload components
- new: strongly typed methods for UploadService
Before:
After:
> upload dialog improvements

- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.model.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/date/date.editor.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/dropdown/dropdown.editor.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/editors/row.editor.spec.ts
refs #1611 
- fix the problem with start/complete buttons disabled for valid required datatable 
- dynamic table widget no longer creates a copy of field model, but
uses original one, fixes the problem with validation and state
management
- update unit tests
> fix dynamic table validation

- ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.html
- ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.spec.ts
- ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.ts
```
```
```
[x ] Bugfix
[ ] Feature
```
disable add button when no valid nodeid is provided …
> disable add button when no valid ID is provided #1591

- ng2-components/ng2-activiti-form/src/components/activiti-content.component.ts
- ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
- ng2-components/ng2-alfresco-core/src/services/content.service.ts
- set ‘show thumbnail’ to true by default
- add support for safe downloads in Safari (upcoming 10.1 and TP)
> bug fixes for thumbnails and Safari download

- demo-shell-ng2/app/components/tag/tag.component.ts
- ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.css
- ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.html
```
```
```
[x ] Bugfix
[ ] Feature
```
When you go on to the tag page initially and enter a tag name the placeholder remains.
The …
> use mdl input for tag #1506

- ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts
- ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Firefox and Safari are not able to export reports. 
Component is not using the centralized system for download.
**What is the …
> #1654 - move download management to content service from core

- ng2-components/ng2-activiti-analytics/src/components/analytics-generator.component.css
- ng2-components/ng2-activiti-analytics/src/components/analytics-generator.component.html
refs #1668 
- migrate buttons to angular/material
- move buttons to the left (workaround for tooltips)
> workaround for tooltips

- demo-shell-ng2/app/components/activiti/activiti-demo.component.html
- ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.ts
- ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Process definition overview is always showed even when user check the filters for a specific app …
> #1657 - Added filter for 'Process definition overview'

- ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.spec.ts
- ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.ts
refs #1728 
- show original message for CORS/offline problems
> use original error message for CORS/offline state in login

- ng2-components/ng2-activiti-form/src/services/form.service.spec.ts
- ng2-components/ng2-activiti-form/src/services/form.service.ts
```
```
```
[] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Removed private api call. Refactored the test file.
Workflowgroups and workflowuser were using the private api call.
**What is …
> #1712 - Removed old private api call for wokflows users and groups

- ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.html
- ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts
- ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
On saved reports the save and export button are not showed without touching the form
On saved …
> #1652 - Save and Export should appear on saved reports

- ng2-components/ng2-alfresco-documentlist/karma.conf.js
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
```
```
```
[x ] Bugfix
[ ] Feature
```
Pagination is present also in  in empty folders #1595 
hide Pagination in empty folders …
> hide Pagination in empty folder #1595

- demo-shell-ng2/app/components/files/files.component.html
- ng2-components/ng2-alfresco-datatable/README.md
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- move ngSwitch outside of the ngFor directive (to avoid issues)
- improved template maintainance (without ngFor template hack)
- readme updates to reflect new features
> datatable improvements

- ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.model.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.ts
- readonly mode for “Dynamic Table”
- “Display Value” now just uses “Dynamic Table” if needed (previously
rendered the table itself)
- support for “tableEditable” settings
refs #1610
> [ADF-237] Form renderer enhancements

- demo-shell-ng2/app/components/activiti/activiti-demo.component.html
- ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts
- ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.html
- ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
- debug button is now disabled by default for the Form and Task Details
- debug mode now enabled by the demo shell explicitly
> [ADF-495] disable debug button by default

- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/components/setting/setting.component.html
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.component.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.ts
```
```
```
[ ] Bugfix
[x] Feature
```
On create menu of document list no permission is checked when user try to create a folder …
> Added permission check on documentlist action menu

- ng2-components/ng2-activiti-tasklist/src/assets/tasklist-service.mock.ts
- ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts
- ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.ts
Fix for Issue #DW-43: Incompatible comparison between string and integer variables in getTaskFilterById service
https://issues.alfresco.com/jira/browse/DW-43
> [DW-43] Task Service - Fix the input type from string to number

- ng2-components/ng2-activiti-processlist/src/assets/activiti-process.service.mock.ts
- ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.spec.ts
- ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
Fix for Issue#DW-45: getProcessFilterById service in activiti-process.service.ts (https://github.com/Alfresco/alfresco-ng2-components/blob/development/ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts) has a comparison between two variables of different types. and parameter issue.
https://issues.alfresco.com/jira/browse/DW-45
> [DW-45] Process Service - Fix the input type from string to number

- ng2-components/ng2-activiti-analytics/src/assets/analytics.service.mock.ts
- ng2-components/ng2-activiti-analytics/src/services/analytics.service.spec.ts
- ng2-components/ng2-activiti-analytics/src/services/analytics.service.ts
Fix for Issue#DW-47: Create a service that returns report details for a given report name as part of ng2-activiti-analytics component. There is no spec file for this service thats why skipped Unit Testcase.
https://issues.alfresco.com/jira/browse/DW-47
> [ADF- 556] Analytics Service - Add a new method to get the report details by name

- demo-shell-ng2/app/components/activiti/activiti-demo.component.html
- demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
- ng2-components/ng2-activiti-analytics/README.md
- ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.ts
- ng2-components/ng2-activiti-diagrams/README.md
- ng2-components/ng2-activiti-diagrams/src/assets/diagramActivities.mock.ts
- ng2-components/ng2-activiti-diagrams/src/assets/diagramBoundary.mock.ts
- ng2-components/ng2-activiti-diagrams/src/assets/diagramEvents.mock.ts
- ng2-components/ng2-activiti-diagrams/src/assets/diagramGateways.mock.ts
- ng2-components/ng2-activiti-diagrams/src/assets/diagramIntermediate.mock.ts
- ng2-components/ng2-activiti-diagrams/src/assets/diagramStructural.mock.ts
- ng2-components/ng2-activiti-diagrams/src/assets/diagramThrow.mock.ts
- ng2-components/ng2-activiti-diagrams/src/components/diagram.component.spec.ts
- ng2-components/ng2-activiti-diagrams/src/components/diagram.component.ts
- ng2-components/ng2-activiti-diagrams/src/components/raphael/raphael-multiline-text.component.ts
- ng2-components/ng2-activiti-diagrams/src/models/diagram.model.ts
- ng2-components/ng2-activiti-diagrams/src/services/diagrams.service.ts
- ng2-components/ng2-activiti-tasklist/src/components/activiti-tasklist.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.html
- ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.ts
```
```
```
[ ] Bugfix
[x] Feature
```
Process diagram widget does not show the state of process instance.
https://issues.alfresco.com/jira/browse/ADF-402 
**What is …
> [ADF-402] Process Diagram Widget - Show the current process state

- ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-types.ts
- ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts
- provide support for showing generated documents in Display Value widget
```
```
```
[x] Bugfix
[ ] Feature
```
**Does this PR …
> [ADF-642] form renderer fixes

- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
It is not possible to drop/upload many types of files due to the wrong file type check
- …
> [ADF-641] fix upload issues with various file types

- ng2-components/ng2-activiti-processlist/README.md
- ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.ts
- ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
```
```
```
[ x] Bugfix
[ ] Feature
```
activiti-start-process should accept list of process variable in input https://issues.alfresco.com/jira/browse/ADF-528 …
> [ADF-528] activiti-start-process should accept list of process variable in input

- demo-shell-ng2/app/components/activiti/activiti-demo.component.html
- ng2-components/ng2-activiti-tasklist/src/components/adf-task-attachment-list.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/data/object-datatable-adapter.ts
```
```
```
[x] Bugfix
[x] Feature
[ ] Refactoring (no functional changes, no API changes)
```
- restore data table ability showing external images (i.e. URLs)
- new 'icon' type for columns …
> [ADF-675] fix external images rendering for datatable 

- demo-shell-ng2/config/webpack.common.js
- demo-shell-ng2/config/webpack.dev.js
- demo-shell-ng2/config/webpack.prod.js
…ay that the production runner will override the path during the build
```
```
```
[ ] Bugfix
[ ] Feature
```
Demo shell npm run build doesn't work on …
> [ADF-694] Split the module runner ts-loader 

- demo-shell-ng2/app/components/files/files.component.ts
- ng2-components/ng2-alfresco-upload/README.md
- ng2-components/ng2-alfresco-upload/index.ts
- ng2-components/ng2-alfresco-upload/src/events/folder-created.event.ts
- ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
```
```
```
[ ] Bugfix
[x] Feature
```
- extend UploadService with 'folderCreated' event to be able reacting on folder uploads …
> [ADF-640] reload document list on folder upload

- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
- ng2-components/ng2-alfresco-datatable/src/data/datatable-adapter.ts
- ng2-components/ng2-alfresco-datatable/src/data/object-datatable-adapter.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
```
```
```
[x] Bugfix
[x] Feature
[ ] Refactoring (no functional changes, no API changes)
```
- fix `hasValue` API for data rows (avoid 'false' value to be evaluated as missing value)
- …
> [ADF-621] show drop effect on folders only

- ng2-components/ng2-alfresco-core/README.md
- ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.html
- ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
https://issues.alfresco.com/jira/browse/ADF-696
Entire group header is not clickable
Accordion (expand) icon hiding logic …
> [ADF-696] Entire accordion group header should be clickable

- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dynamic-table/dynamic-table.widget.ts
```
```
```
[X] Bugfix
[ ] Feature
```
The focus goes on the first element in the page after adding a new line on DynamicTableWidget …
> [ADF-709] add autofocus when a new row is added on dynamic table widget

- ng2-components/config/karma.conf-all.js
Provides support for running unit tests in Headless mode if a developer has Chrome 59 or later installed.
> [ADF-758] support for headless chrome

- ng2-components/ng2-activiti-tasklist/src/models/icon.model.ts
> - [x] Bugfix
Some of the Bootstrap icons are not properly mapped to the Angular Material icons. In this bug the …
> [ADF-526] Adding new icon (sent) for Bootstrap to Material icon mapping

- ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.component.css
> - [x] Bugfix
As described in [ADF-689]: "Upload list dialogue is rendered behind Document List toolbar"
**What is …
> [ADF-689] Fix alfresco-document-menu-action styling (z-index)

- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/components/files/files.component.ts
- ng2-components/ng2-alfresco-core/src/directives/upload.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/upload.directive.ts
- ng2-components/ng2-alfresco-core/src/utils/file-utils.ts
- ng2-components/ng2-alfresco-core/src/utils/index.ts
- ng2-components/ng2-alfresco-upload/README.md
- ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
- ng2-components/ng2-alfresco-upload/src/directives/file-draggable.directive.ts
- ng2-components/ng2-alfresco-upload/src/models/file.model.ts
- ng2-components/ng2-alfresco-upload/src/services/upload.service.spec.ts
- ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
Numerous upload enhancements:
- limits concurrent downloads not to block UI
- flattens hierarchy on folder upload
- performs a single traversal of the entire folder hierarchy and ends with a complete file list
- allows now dropping folders on existing folders
- overall code improvements
- cleanup demo shell demo for the document list
Marked for deprecation:
- UploadButtonComponent.showNotificationBar
- UploadButtonComponent.currentFolderPath
- UploadDragAreaComponent.showNotificationBar
- UploadDragAreaComponent.currentFolderPath
> [ADF-643] upload enhancements

- ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.ts
```
```
```
[x] Bugfix
[ ] Feature
```
getProcessFilterByName api in activiti-process.service does not return filter for the given filter name and appId. It always …
> [ADF-780] Process service - getProcessFilterByName wrong behaviour

- demo-shell-ng2/app/components/activiti/activiti-demo.component.html
- demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
- ng2-components/ng2-activiti-processlist/src/components/activiti-create-process-attachment.component.css
- ng2-components/ng2-activiti-processlist/src/components/activiti-create-process-attachment.component.html
- ng2-components/ng2-activiti-processlist/src/components/adf-create-process-attachment.component.css
- ng2-components/ng2-activiti-processlist/src/components/adf-create-process-attachment.component.html
- ng2-components/ng2-activiti-processlist/src/components/adf-create-process-attachment.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/adf-create-process-attachment.component.ts
- ng2-components/ng2-activiti-processlist/src/components/adf-process-attachment-list.component.ts
- ng2-components/ng2-activiti-processlist/src/components/index.ts
- ng2-components/ng2-activiti-processlist/src/i18n/en.json
```
```
```
[ ] Bugfix
[X] Feature
```
There is no button allowing users to upload content on process attachment list
Added a button …
> [ADF-740] Add button for process attachment list

- ng2-components/ng2-alfresco-upload/src/events/file.event.ts
- ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
```
```
```
[ ] Bugfix
[x] Feature
```
It is not possible to get created node upon file upload
Upload service now exposes created …
> [ADF-811] upload service exposes created nodes

- ng2-components/ng2-alfresco-viewer/src/components/pdfViewer.component.html
```
[X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
```
```
[X] Bugfix
[ ] Feature
```
When using a screen reader user can NOT tab into any of the elements/buttons within the previewer e.g. close button, maximise, …
> [ADF-180] Adding tabindices to viewer control elements

- ng2-components/ng2-alfresco-viewer/src/components/pdfViewer.component.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Pdf viewing (overlay mode independent)
Zoom and Fullscreen buttons are not working correctly in the viewer if the pdf contains …
> [ADF-784] Fix current page number issue in the viewer

- ng2-components/ng2-alfresco-datatable/README.md
- ng2-components/ng2-alfresco-datatable/index.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.css
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
- ng2-components/ng2-alfresco-datatable/src/directives/index.ts
- ng2-components/ng2-alfresco-datatable/src/directives/loading-template.component.spec.ts
- ng2-components/ng2-alfresco-datatable/src/directives/loading-template.component.ts
- ng2-components/ng2-alfresco-datatable/src/directives/no-content-template.component.spec.ts
- ng2-components/ng2-alfresco-datatable/src/directives/no-content-template.component.ts
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/index.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.css
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
```
```
```
[ ] Bugfix
[X ] Feature
```
When the datatbale is in a intermediate   state now it show the empty template
I have added …
> [ADF-524] Datatable loading state

- demo-shell-ng2/app/app.component.ts
```
```
```
[x ] Bugfix
[ ] Feature
```
When no port is present in the windows.location obj the setting index result with : that should not there
**What is the …
> Fix host configuration in demo-shell when no port is present

- ng2-components/ng2-activiti-form/src/components/widgets/attach/attach.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/text/text.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
```
```
```
[X] Bugfix
[ ] Feature
```
using form passing readonly attribute doesn't render readonly all the fields
using form passing …
> [ADF-494] fixed readonly rendering for forms

- ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts
```
```
```
[ x] Bugfix
[ ] Feature
```
The default radio button should not be get in consideration if is not selected a default options in the form editor …
> [ADF-810] fix default value radio button

- ng2-components/ng2-activiti-form/README.md
- ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts
- ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts
- ng2-components/ng2-activiti-form/src/services/form.service.ts
- support for subscribing for form outcome execution events (`executeOutcome`)
- ability to cancel outcome execution events
> [ADF-851] execute-outcome event for form service

- ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.html
- ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.ts
- ng2-components/ng2-alfresco-upload/src/events/file.event.ts
- ng2-components/ng2-alfresco-upload/src/services/upload.service.spec.ts
- ng2-components/ng2-alfresco-upload/src/services/upload.service.ts
```
```
```
[ ] Bugfix
[X] Feature
```
Close button is always showed for upload dialog.
Upload dialog list is never cleared.
Upload …
> [ADF-778] cancel window for upload dialog shows only on complete

- ng2-components/ng2-activiti-analytics/package.json
- ng2-components/ng2-activiti-diagrams/package.json
- ng2-components/ng2-activiti-form/package.json
- ng2-components/ng2-activiti-processlist/package.json
- ng2-components/ng2-activiti-tasklist/package.json
- ng2-components/ng2-alfresco-core/package.json
- ng2-components/ng2-alfresco-datatable/package.json
- ng2-components/ng2-alfresco-documentlist/package.json
- ng2-components/ng2-alfresco-login/package.json
- ng2-components/ng2-alfresco-search/package.json
- ng2-components/ng2-alfresco-social/package.json
- ng2-components/ng2-alfresco-tag/package.json
- ng2-components/ng2-alfresco-upload/package.json
- ng2-components/ng2-alfresco-userinfo/package.json
- ng2-components/ng2-alfresco-viewer/package.json
- ng2-components/ng2-alfresco-webscript/package.json
```
```
```
[ ] Bugfix
[ ] Feature
```
the prepublish script has been deprecated in node 8 
the prepublish script was running in …
> [ADF-919] Prepublish script deprecation in favour of prepublishOnly node 8

- ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.spec.ts
> - [X] Bugfix
Date button is not disabled on readonly forms
Date button is now …
> [ADF - 950] - disabling date button on readonly form

- ng2-components/ng2-activiti-form/index.ts
- ng2-components/ng2-activiti-form/src/components/activiti-start-form.component.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.css
- ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/amount/amount.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/container/container.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/tabs/tabs.widget.spec.ts
> - [ ] Bugfix
amount widget uses material design ligth spec. The currency symbol is next to the label.
**What is the …
> [ADF - 334] Added prefix to amount widget

- ng2-components/ng2-activiti-diagrams/src/components/diagram.component.spec.ts
- ng2-components/ng2-activiti-diagrams/src/components/tooltip/diagram-tooltip.component.html
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/components/material/mdl-tooltip.directive.ts
```
```
```
[x] Bugfix
[ ] Feature
```
Tooltip was not working (intermittently displayed or not) in the process diagrams.
Tooltip is …
> [ADF-402] MDL tooltip not displayed bug fix

- ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/activiti-start-process.component.ts
> - [x] Bugfix
The loadProcess is not called when the appId is null
https://issues.alfresco.com/jira/browse/ADF-733 …
> [ADF-733] Start Process - appId not mandatory

- demo-shell-ng2/app.config-dev.json
- demo-shell-ng2/app.config-prod.json
- ng2-components/ng2-activiti-analytics/src/components/analytics-report-list.component.spec.ts
- ng2-components/ng2-activiti-analytics/src/components/analytics-report-parameters.component.spec.ts
- ng2-components/ng2-activiti-form/src/services/form.service.spec.ts
- ng2-components/ng2-alfresco-core/README.md
- ng2-components/ng2-alfresco-core/src/services/alfresco-content.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/app-config.service.ts
- ng2-components/ng2-alfresco-core/src/services/renditions.service.spec.ts
- ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.spec.ts
- ng2-components/ng2-alfresco-tag/src/components/tag-node-list.component.spec.ts
- ng2-components/ng2-alfresco-tag/src/services/tag.service.spec.ts
- ng2-components/ng2-alfresco-upload/src/services/upload.service.spec.ts
- ng2-components/ng2-alfresco-webscript/src/webscript.component.spec.ts
Provides ability for AppConfigService to evaluate "hostname" and "port" variables within string values
> [ADF-967] evaluate "hostname" and "port" for string settings

- demo-shell-ng2/app.config-dev.json
- demo-shell-ng2/app/app.component.html
- demo-shell-ng2/app/app.module.ts
- demo-shell-ng2/app/app.routes.ts
- demo-shell-ng2/app/components/form/form-demo.component.css
- demo-shell-ng2/app/components/form/form-demo.component.html
- demo-shell-ng2/app/components/form/form-demo.component.ts
- demo-shell-ng2/app/components/form/form-list-demo.component.ts
- demo-shell-ng2/app/services/in-memory-form.service.ts
- ng2-components/ng2-activiti-form/src/services/form.service.ts
Provides examples on the following APIs (to be also covered by a separate blog post)
- storing/retrieving complex data in the application config
- using custom in-memory service for the form data
> [ADF-850] example on using in-memory form data

- demo-shell-ng2/app/components/datatable/datatable-demo.component.html
- demo-shell-ng2/app/components/datatable/datatable-demo.component.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
> - [X] Bugfix
> - [] Other... Please describe:
The datatable won't refresh if the data passed when the table is not empty.
The datatable will be …
> [ADF-966] added the ability to reflect data change on datatable

- ng2-components/ng2-activiti-form/src/components/activiti-form.component.spec.ts
- ng2-components/ng2-activiti-form/src/components/activiti-form.component.ts
- ng2-components/ng2-activiti-form/src/components/adf-form-list.component.spec.ts
> - [X] Bugfix
The form is loaded twice and causing double call to all the rest dropdown. …
> [ADF-957] removed double call to load form

- ng2-components/ng2-activiti-diagrams/src/components/tooltip/diagram-tooltip.component.html
- ng2-components/ng2-activiti-diagrams/src/components/tooltip/diagram-tooltip.component.scss
- ng2-components/ng2-activiti-diagrams/src/components/tooltip/diagram-tooltip.component.spec.ts
> - [x] Bugfix
Too long property values distorted the tooltip.
Tooltip should look …
> [ADF-1001] Fix styling issues with tooltip and increase code coverage

- demo-shell-ng2/app/components/login/login-demo.component.css
- demo-shell-ng2/app/components/login/login-demo.component.html
- demo-shell-ng2/app/components/login/login-demo.component.ts
- ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.css
- ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.html
> - [x] Bugfix
Login component didn't shrink when the loginActions or the footerTemplate are disabled.
**What is the …
> [ADF-939] Make the login component responsive again (now the height)

- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
> - [X] Bugfix
on single file drop the snack bar was not showed
on single file drop …
> [ADF-819] added snackbar to single file drop

- ng2-components/ng2-alfresco-documentlist/src/components/content-column/content-column-list.component.ts
- ng2-components/ng2-alfresco-documentlist/src/components/content-column/content-column.component.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-actions.service.ts
- ng2-components/ng2-alfresco-documentlist/src/services/folder-actions.service.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/services/folder-actions.service.ts
- ng2-components/ng2-alfresco-documentlist/tsconfig.json
- fix the issue with 'isEmpty' in the document list
- mark some of the old content as deprecated (raising console logs for now)
- remove unused local variables/imports
> [ADF-1006] fix 'isEmpty' issue and code cleanup

- ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/upload/upload.widget.ts
> - [X] Bugfix
Multiple attribute is never added even if should be there by APS config. …
> [ADF-858] added multiple attribute to upload widget

- demo-shell-ng2/app/components/activiti/activiti-process-attachments.component.css
- demo-shell-ng2/app/components/activiti/activiti-process-attachments.component.html
- demo-shell-ng2/app/components/activiti/activiti-process-attachments.component.ts
- demo-shell-ng2/app/components/activiti/activiti-task-attachments.component.css
- demo-shell-ng2/app/components/activiti/activiti-task-attachments.component.ts
- ng2-components/ng2-activiti-processlist/src/components/adf-create-process-attachment.component.css
- ng2-components/ng2-activiti-processlist/src/components/adf-create-process-attachment.component.html
- ng2-components/ng2-activiti-processlist/src/components/adf-create-process-attachment.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/adf-create-process-attachment.component.ts
- ng2-components/ng2-activiti-tasklist/src/components/adf-create-task-attachment.component.css
- ng2-components/ng2-activiti-tasklist/src/components/adf-create-task-attachment.component.html
Change the design button
Fix the Event with the name inside the Readme
> - [ ] Bugfix
The create attachment shows the …
> [ADF-971] Create task/process attachment should show the new button

- ng2-components/ng2-alfresco-core/src/services/user-preferences.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/user-preferences.service.ts
- the settings prefix is now stored in the local storage as 'USER_PROFILE' value to allow restoring back on page redirects or reloads
> [ADF-1070] fix issue with user preferences and page reload

- ng2-components/ng2-alfresco-core/src/services/alfresco-api.service.ts
- ng2-components/ng2-alfresco-core/src/services/alfresco-authentication.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/alfresco-authentication.service.ts
- ng2-components/ng2-alfresco-core/src/services/alfresco-content.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/alfresco-settings.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/alfresco-settings.service.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard-bpm.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard-ecm.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/auth-guard.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/thumbnail.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/user-preferences.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/user-preferences.service.ts
- fixes issue with the providers being switched to 'ALL'  after page reload
> [ADF-1047] preserve login providers between page reloads

- ng2-components/ng2-alfresco-datatable/README.md
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.scss
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- improve DataTable (and derived components) styles according to the UX guidelines.
- the focus ring remains the same for accessibility reasons
- support for toggling header in DataTable
- Document List automatically hides header for empty content
**Styles**
**Toggle Header**
> [ADF-992] improve datatable styles according to UX guidelines

- demo-shell-ng2/app/components/files/files.component.html
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar-title.component.ts
- ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.component.css
- ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.component.html
- ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.component.scss
- ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.component.ts
- ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.module.ts
- simple "title" property to render toolbar title
- advanced "adf-toolbar-title" element for compound toolbars
- separate "ToolbarModule" module 
- extended demo shell to show breadcrumb as part of the title
- SASS styles
> [ADF-993] toolbar improvements

- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/components/files/files.component.ts
- ng2-components/ng2-alfresco-core/config/webpack.common.js
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/assets/images/ft_ic_folder_disable.svg
- ng2-components/ng2-alfresco-core/src/models/permissions.enum.ts
- ng2-components/ng2-alfresco-core/src/services/alfresco-content.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/alfresco-content.service.ts
- ng2-components/ng2-alfresco-core/src/services/thumbnail.service.ts
- ng2-components/ng2-alfresco-datatable/README.md
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
- ng2-components/ng2-alfresco-datatable/src/data/datatable-adapter.ts
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/index.ts
- ng2-components/ng2-alfresco-documentlist/karma.conf.js
- ng2-components/ng2-alfresco-documentlist/src/components/content-action/content-action.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-menu-action.component.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
- ng2-components/ng2-alfresco-documentlist/src/models/permissions-style.model.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-actions.service.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.ts
- ng2-components/ng2-alfresco-documentlist/src/services/folder-actions.service.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/services/folder-actions.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/secure/RapidBoard.jspa?rapidView=529&projectKey=ADF&view=detail&selectedIssue=ADF-1040
| Name | Type | Default | …
> [ADF-1040] Change document list style rows based on permissions model

- demo-shell-ng2/app/components/activiti/activiti-demo.component.html
- demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
> - [ ] Bugfix
The start task is rendered inside the task filter zone
Add a button to …
> [ADF-1078] Move the start task component in a different zone

- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/components/files/files.component.ts
- ng2-components/ng2-alfresco-datatable/README.md
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
- ng2-components/ng2-alfresco-datatable/src/directives/loading-template.directive.spec.ts
- ng2-components/ng2-alfresco-datatable/src/directives/loading-template.directive.ts
- ng2-components/ng2-alfresco-datatable/src/directives/no-content-template.directive.spec.ts
- ng2-components/ng2-alfresco-datatable/src/directives/no-content-template.directive.ts
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
DataTable
- `row-select` and `row-unselect` DOM events
- `selection` property that holds current selection (rows)
- improved selection management for the "checkboxes" mode
DocumentList
- `node-select` and `node-unselect` DOM events
- `selection` property that holds current selection (nodes)
- updated demo shell
- selection modes picker
- toggle "checkboxes" mode
- show current selection in another element
> [ADF-1115] selection management for DT/DL components

- ng2-components/ng2-alfresco-viewer/src/components/notSupportedFormat.component.html
- ng2-components/ng2-alfresco-viewer/src/components/notSupportedFormat.component.spec.ts
- ng2-components/ng2-alfresco-viewer/src/components/notSupportedFormat.component.ts
> - [x] Bugfix
Polling of bigger files' rendition creation was continued after the viewer was closed.
**What is the …
> [ADF-1003] Stop polling after viewer is closed.

- demo-shell-ng2/app/components/activiti/activiti-demo.component.css
- demo-shell-ng2/app/components/activiti/activiti-demo.component.html
- ng2-components/ng2-activiti-processlist/src/components/process-instance-details.component.html
- ng2-components/ng2-activiti-processlist/src/components/process-instance-details.component.ts
- ng2-components/ng2-activiti-tasklist/src/components/task-details.component.css
- ng2-components/ng2-activiti-tasklist/src/components/task-details.component.html
- ng2-components/ng2-activiti-tasklist/src/components/task-details.component.ts
> - [x] Bugfix
md menu in mdl dialog gets displayed behind the dialog model
* Removed …
> [ADF-1149] 'Remove' involved people of a task button is displayed beind the dialog

- ng2-components/ng2-activiti-processlist/src/services/process.service.spec.ts
- ng2-components/ng2-activiti-processlist/src/services/process.service.ts
> - [x] Bugfix
The process service was using the task service method to create the default process filter
**What is …
> [ADF-1155] The Process and Task filters are not displayed properly

- ng2-components/ng2-alfresco-core/src/models/file.model.spec.ts
- ng2-components/ng2-alfresco-core/src/models/file.model.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
> - [x] Bugfix
File with unaccepted extension is uploaded when 'Format' in browser's File upload dialog is set to …
> [ADF-1097] Don't upload file if extension is not acceptable

- ng2-components/ng2-alfresco-core/src/services/thumbnail.service.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/empty-list.component.ts
solves issues with "Cannot find name 'require'." errors when linking to Angular CLI.
> [ADF-1146] improve Angular CLI compatibility

- ng2-components/ng2-alfresco-core/src/services/favorites-api.service.ts
fixes the bug for Safari when dates get corrupted on double conversion (createdAt/modifiedAt are already dates)
> [ADF-1208] remove useless date conversion

- demo-shell-ng2/app/components/files/files.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/content-node-selector/content-node-selector.component.html
Replace last occurrences of 'template' in Angular components (moved to 'ng-template')
> [ADF-720] replace 'template' with 'ng-template'

- ng2-components/ng2-activiti-form/src/components/form-field/form-field.component.ts
> - [X] Bugfix
When a form is opened in readonly state the custom component registered is not used, but is showed …
> [ADF-224] fix the rendering of custom stencils when form is opened in readonly state.

- demo-shell-ng2/app/components/files/files.component.html
- ng2-components/ng2-alfresco-core/README.md
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.ts
- ng2-components/ng2-alfresco-core/src/directives/node-permission.md
- New `NodePermissionDirective` (`adf-node-permission`)
- update readme with a link to directive docs
- update demo shell to demonstrate the directive in the toolbar (delete button)
> [ASF-1227] new adf-node-permission directive

- demo-shell-ng2/app/components/activiti/activiti-demo.component.html
- demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
> - [x] Bugfix
The task audit button is rendered also when there is no taskId
Hide the …
> [ADF-1298] Task audit log - Hide the task audit button when there is no taskId

- demo-shell-ng2/app/app.routes.ts
- demo-shell-ng2/app/components/activiti/activiti-demo.component.ts
- demo-shell-ng2/app/components/activiti/activiti-show-diagram.component.ts
Change the current route for diagram process
> - [x] Bugfix
The back button redirect the user to the task list
**What …
> [ADF-1252] Diagram process - The back button should redirect the user to the process list

- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/vendor.ts
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.ts
- support for custom root element name for breadcrumb
- renamed "Company Home" to "Personal Files" in demo shell
> [ADF-1213] ability to redefine the root element in the breadcrumb 

- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/resources/i18n/en.json
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/package.json
- ng2-components/ng2-alfresco-core/src/pipes/time-ago.pipe.ts
- new 'adfTimeAgo' pipe that uses moment.js to format/display date/time
- simple demo in the demo app to format 'created on' column
> [ADF-1318] adfTimeAgo pipe and demo

- demo-shell-ng2/app/components/files/files.component.html
Minor update to remove the 'MDL' usage from the "Content Services" demo page (demo shell)
> remove mdl from "Content Services" page (demo shell)

- ng2-components/ng2-activiti-tasklist/README.md
- ng2-components/ng2-activiti-tasklist/src/components/tasklist.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/tasklist.component.ts
- ng2-components/ng2-activiti-tasklist/src/services/tasklist.service.spec.ts
- ng2-components/ng2-activiti-tasklist/src/services/tasklist.service.ts
> - [ ] Bugfix
There is no way to list all tasks of a process instance irrespective of state/status …
> [ADF-1116] Task list without any status filter

- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/components/files/files.component.ts
- demo-shell-ng2/app/components/search/search.component.html
- demo-shell-ng2/app/components/search/search.component.ts
- ng2-components/ng2-alfresco-search/README.md
- ng2-components/ng2-alfresco-search/src/components/search.component.html
- ng2-components/ng2-alfresco-search/src/components/search.component.ts
> - [x] Bugfix
Folder contents are not displayed when double clicking an empty folder in Search Page component
**What …
> [ADF-1219] Files and search component fix with routing support

- ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.html
- ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.scss
- ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.ts
- ng2-components/ng2-alfresco-core/src/i18n/en.json
> - [x] Bugfix
Stylesheets have been updated to match the design
If `[pagination]` attribute is `undefined` then the …
> [ADF-1386] If pagination attribute is undefined shows inconsistent range

- demo-shell-ng2/app/components/files/files.component.html
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/pipes/file-size.pipe.spec.ts
- ng2-components/ng2-alfresco-core/src/pipes/file-size.pipe.ts
- ng2-components/ng2-alfresco-datatable/index.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable-cell.component.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/location-cell.component.ts
- ng2-components/ng2-alfresco-datatable/src/data/object-datatable-adapter.ts
- ng2-components/ng2-alfresco-datatable/src/directives/loading-template.directive.spec.ts
- ng2-components/ng2-alfresco-datatable/src/directives/no-content-template.directive.spec.ts
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
New column types:
- fileSize: renders node size with conversion to bytes, kb/mb/etc
- location: renders clickable hyperlinks to the parent folder of the node
Updated column types:
- date: extra support for 'timeAgo' format
> [ADF-1404] Data Column enhancements for Document List

- demo-shell-ng2/app/components/files/files.component.html
- demo-shell-ng2/app/components/files/files.component.ts
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.ts
- ng2-components/ng2-alfresco-core/src/directives/node-permission.md
- ng2-components/ng2-alfresco-core/src/interface/injection.tokens.ts
- ng2-components/ng2-alfresco-upload/README.md
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.html
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
> - [ ] Bugfix
Upload button and upload drag area component are too different in interfaces, try to make them more …
> [ADF-1188] Upload related components, unify interfaces, deprecate disableWithNoPermission

- ng2-components/ng2-alfresco-core/src/pipes/time-ago.pipe.spec.ts
- ng2-components/ng2-alfresco-core/src/pipes/time-ago.pipe.ts
> - [x] Bugfix
* Returns "invalid date" when the input is empty.
* Returns Empty …
> [ADF-1456]  timeAgo Pipe - Return invalid date when the input is empty.

- ng2-components/ng2-activiti-processlist/index.ts
- ng2-components/ng2-activiti-processlist/src/components/process-attachment-list.component.html
- ng2-components/ng2-activiti-processlist/src/components/process-attachment-list.component.scss
- ng2-components/ng2-activiti-processlist/src/components/process-attachment-list.component.spec.ts
- ng2-components/ng2-activiti-tasklist/index.ts
- ng2-components/ng2-activiti-tasklist/src/components/people-search.component.html
- ng2-components/ng2-activiti-tasklist/src/components/people-search.component.ts
- ng2-components/ng2-activiti-tasklist/src/components/people.component.html
- ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.html
- ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.scss
- ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/task-details.component.html
- ng2-components/ng2-alfresco-datatable/index.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/empty-list.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/empty-list.component.ts
- ng2-components/ng2-alfresco-documentlist/index.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.scss
> - [x] Bugfix
NO_ERRORS_SCHEMA/CUSTOM_ELEMENTS_SCHEMA was used in task-list, process-list and document-list …
> [ADF-1466] Ng2-activiti-tasklist module uses NO_ERRORS_SCHEMA schema, which hides underlying error

- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.scss
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
Provides accessibility enhancements for DataTable and derived components:
- tabbing through the column headers
- tabbing through the cells
- focus rings for cells and headers
- keyboard (Enter key) support for column headers: sorting change
- keyboard (Enter key) support for rows: navigation to a folder or file preview
> [ADF-1267] accessibility enhancements for datatable

- ng2-components/ng2-alfresco-viewer/src/components/viewer-dialog.component.html
- ng2-components/ng2-alfresco-viewer/src/components/viewer-dialog.component.scss
- ng2-components/ng2-alfresco-viewer/src/components/viewer-dialog.component.ts
- ng2-components/ng2-alfresco-viewer/src/material.module.ts
Prerequisite for the Info Drawer integration with the Viewer Dialog. Provides the following features:
- display info drawer container to the left of the file
- toggle drawer container from the toolbar
- display toolbar button only when the drawer is supported
> [ADF-1483] info drawer integration support

- ng2-components/ng2-alfresco-viewer/src/services/viewer.service.ts
Minor Viewer Dialog improvements:
- allow viewing by node id (scenarios when a node is not available, like Shared Link)
> allow showing viewer based on only node id

- demo-shell-ng2/app/components/files/files.component.html
- ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.ts
- ng2-components/ng2-alfresco-upload/README.md
- ng2-components/ng2-alfresco-upload/src/components/upload-button.component.ts
- ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.ts
> - [X] Bugfix
Upload button is not disabled when the attribute disabled is changed, this is due overlapping of the …
> [ADF-1458] wrongly named input attribute - renamed disabled into disable

- ng2-components/ng2-activiti-form/src/components/form-field/form-field.component.ts
check for the type property before resolving a wrapped field (addresses issue with empty field objects coming with form definition)
> [ADF-1525] fix wrapped field resolving

- ng2-components/ng2-activiti-form/src/components/widgets/content/content.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/content/content.widget.scss
- ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts
- ng2-components/ng2-activiti-form/src/components/widgets/document/document.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/document/document.widget.ts
- ng2-components/ng2-activiti-form/src/components/widgets/index.ts
- ng2-components/ng2-activiti-form/src/services/form-rendering.service.ts
> - [ ] Bugfix
The generated documents are no longer displayed on the form.
Introduces …
> [ADF-1528] new "document" widget

- demo-shell-ng2/app.config-dev.json
- demo-shell-ng2/app.config-prod.json
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
> - [ ] Bugfix
For the moment layout presets are hard coded into the document list. …
> [ADF-1522] allow loading layout presets from app.config

- ng2-components/ng2-alfresco-viewer/src/components/pdfViewer.component.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer-dialog/pdf-view/pdf-view.component.ts
> - [x] Bugfix
The PDF viewers (both standard and the lightweight version for the Viewer Dialog) have memory leaks …
> [ADF-1538] fix memory leaks for pdf viewers

- ng2-components/ng2-activiti-tasklist/src/components/apps-list.component.css
> - [x] Bugfix
When an app has a long name, is displayed under the logo.
long name are …
> [ADF-1455]  long app name are displayed under the logo in the applist

- ng2-components/ng2-activiti-form/src/components/widgets/multiline-text/multiline-text.widget.html
> - [x] Bugfix
In the new multi-line field in ADF 1.8, a red required warning line is shown incorrectly in a few …
> [ADF-1533] Multi-line form max length 

- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/breadcrumb.component.ts
- ng2-components/ng2-alfresco-documentlist/src/components/breadcrumb/dropdown-breadcrumb.component.spec.ts
> - [x] Bugfix
Provide support for specifying custom root id for the breadcrumb.
Allow …
> [ADF-1531] breadcrumb enhancements

- ng2-components/ng2-alfresco-datatable/index.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable-cell.component.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.html
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.spec.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/date-cell.component.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/filesize-cell.component.ts
- ng2-components/ng2-alfresco-datatable/src/components/datatable/location-cell.component.ts
- ng2-components/ng2-alfresco-datatable/src/directives/loading-template.directive.spec.ts
- ng2-components/ng2-alfresco-datatable/src/directives/no-content-template.directive.spec.ts
> - [x] Bugfix
Tooltips for column headers are not translated, instead, the plain i18n resource keys are used. …
> [ADF-1547] tooltip fixes and enhancements

- ng2-components/ng2-activiti-processlist/src/i18n/en.json
> - [x] Bugfix
* Process fields are not translated when starting a process and on process page …
> [ADF-1560] Process fields are not translated when starting a process and on process page

- ng2-components/ng2-activiti-form/src/components/widgets/core/group-user.model.ts
- ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts
> - [x] Bugfix
People widget doesn't' render properly the user suggestion when the user doesn't have a profile image …
> [ASD-1569] Fix people widget form component when no images are present

- ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer.component.html
- ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer.component.ts
- ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer.md
> - [ ] Bugfix
A output event in adf-info-drawer component to get the current active …
> [ADF-1574] Info Drawer - Add a mechanism to know the current active tab

- demo-shell-ng2/package.json
- demo-shell-ng2/wsrv-config.js
- proxy settings for `/ecm` and `/bpm`, can now use the same `app.config.json`
- workaround for `www-authenticate` issue
> improved "start:dist" script

- ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.spec.ts
> - [x] Bugfix
Drop-down doesn't display the value if the field is readonly
The …
> [ADF-1597] Dropdown widget should show the value in readonly mode

- ng2-components/ng2-activiti-processlist/src/components/process-attachment-list.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/process-attachment-list.component.ts
- ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/task-attachment-list.component.ts
- ng2-components/ng2-alfresco-core/src/directives/upload.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/upload.directive.ts
> - [x] Bugfix
* ADF-1291 - Attachment list is not refreshed instantly after upload/drag and drop
* #2377 - Unable to …
> [ADF-1291] Attachment list is not instantly refreshed after upload

- ng2-components/ng2-activiti-form/src/components/start-form.component.ts
- ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts
- ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/dropdown/dropdown.widget.ts
- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.ts
- ng2-components/ng2-activiti-form/src/services/form.service.ts
> - [x] Bugfix
After a process is started, the value is fetch using the processDefinition instead it should fetched …
> [ADF-1595] Typeahead - Fetch the value from the process variables

- demo-shell-ng2/app.config-dev.json
- demo-shell-ng2/app.config-prod.json
- ng2-components/ng2-alfresco-documentlist/README.md
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.html
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
Allow setting `supportedPageSizes` property for DocumentList via HTML attributes or global app config.
> [ADF-1545] configurable 'supportedPageSizes' for document list

- ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-orange.css
- ng2-components/ng2-alfresco-core/prebuilt-themes/adf-blue-purple.css
- ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-orange.css
- ng2-components/ng2-alfresco-core/prebuilt-themes/adf-cyan-purple.css
- ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-orange.css
- ng2-components/ng2-alfresco-core/prebuilt-themes/adf-green-purple.css
- ng2-components/ng2-alfresco-core/prebuilt-themes/adf-indigo-pink.css
- ng2-components/ng2-alfresco-core/prebuilt-themes/adf-pink-bluegrey.css
- ng2-components/ng2-alfresco-core/prebuilt-themes/adf-purple-green.css
- ng2-components/ng2-alfresco-datatable/src/components/datatable/datatable.component.scss
> - [x] Bugfix
Ellipsis property was not working in data columns using custom HTML templates …
> [ADF-1615] Datatable - The ellipsis class doesn't work for a custom template

- demo-shell-ng2/app/app.component.html
- demo-shell-ng2/app/app.component.ts
- ng2-components/ng2-alfresco-core/README.md
- ng2-components/ng2-alfresco-core/index.ts
- ng2-components/ng2-alfresco-core/src/directives/logout.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/logout.directive.ts
> - [ ] Bugfix
Provides `adf-logout` directive to enable automatic logout for …
> [ADF-1613] logout directive

- ng2-components/ng2-activiti-tasklist/README.md
- ng2-components/ng2-activiti-tasklist/src/components/tasklist.component.html
- ng2-components/ng2-activiti-tasklist/src/components/tasklist.component.ts
> - [ ] Bugfix
There is no way to select more than one row in the tasklist
Add a …
> [ADF-1609] Tasklist - Provide a multiselection property

- ng2-components/ng2-alfresco-login/src/components/login.component.spec.ts
- ng2-components/ng2-alfresco-login/src/components/login.component.ts
> - [x] Bugfix
the login component is checking the 3 characters minLength for the username …
> [ADF-1618] Login component - should not check the username minLength as default

- ng2-components/ng2-alfresco-search/src/components/search-control.component.html
- ng2-components/ng2-alfresco-search/src/components/search-control.component.spec.ts
> - [x] Bugfix
Click on the Search Icon.
Add input.
Click on the search icon again: 
-Actual result: The Search …
> [ADF-1328] Fix closing search bar has not to trigger search

- ng2-components/ng2-activiti-form/src/components/start-form.component.ts
- ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts
- ng2-components/ng2-activiti-form/src/components/widgets/typeahead/typeahead.widget.spec.ts
- ng2-components/ng2-activiti-form/src/services/form.service.ts
/api/enterprise/process-instances/XXX
instead of
/api/enterprise/process-instances/382/variables
because the latest api returns 404 if the process is completed
> - [x] Bugfix
**What is the …
> [ADF-1640] Start form - Get the variables from the process instance API

- ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.html
- ng2-components/ng2-alfresco-core/src/components/pagination/pagination.component.scss
Restrict the size of the page selector dropdown to enable scrolling support.
> [ADF-1637] fix the menu height issue

- ng2-components/ng2-alfresco-core/src/services/translate-loader.service.ts
- ng2-components/ng2-alfresco-core/src/utils/object-utils.spec.ts
- ng2-components/ng2-alfresco-core/src/utils/object-utils.ts
> - [x] Bugfix
it is not possible to override ADF resource strings from the application …
> [ADF-1636] fix issues with i18n resource composing

- docs/viewer.component.md
- ng2-components/ng2-alfresco-viewer/src/components/pdfViewer.component.html
- ng2-components/ng2-alfresco-viewer/src/components/pdfViewer.component.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
- hide all demo/fake content by default: toolbar buttons and PDF viewer thumbnail button
> [ADF-1676] hide fake content in the viewer

- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
> - [x] Bugfix
When switching to different source the pagination settings are still used for the old one.
**What is …
> [ADF-1677] reset pagination on data source change

- ng2-components/ng2-activiti-form/src/components/widgets/core/form-field.model.ts
- ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts
- ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/people/people.widget.ts
- ng2-components/ng2-activiti-form/src/services/form.service.ts
> - [X] Bugfix
User suggestion keeps being showed when user has cleared the input text …
> [ADF-1653] cleaned user suggestion when input type is an empty string

- docs/README.md
- docs/node-name-tooltip.pipe.md
- ng2-components/ng2-alfresco-core/src/pipes/node-name-tooltip.pipe.spec.ts
- ng2-components/ng2-alfresco-core/src/pipes/node-name-tooltip.pipe.ts
> - [ ] Bugfix
Adds support for tooltip generation based on node details.
See …
> [ADF-1746] node name tooltip pipe

- docs/form.component.md
- ng2-components/ng2-activiti-form/src/assets/start-form.component.mock.ts
- ng2-components/ng2-activiti-form/src/components/form.component.spec.ts
- ng2-components/ng2-activiti-form/src/components/form.component.ts
- ng2-components/ng2-activiti-processlist/src/components/start-process.component.html
- ng2-components/ng2-activiti-processlist/src/components/start-process.component.spec.ts
- ng2-components/ng2-activiti-processlist/src/components/start-process.component.ts
> - [X] Bugfix
Start process button is disabled only when the form is invalid
Start …
> [ADF-1740] disabling start process button when the process name is empty

- ng2-components/ng2-activiti-form/src/components/widgets/core/form-field-validator.ts
- ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.spec.ts
- ng2-components/ng2-activiti-form/src/components/widgets/date/date.widget.ts
> - [X] Bugfix
When chosen a different date format with min and max date value the data picker is all disabled. …
> [ADF-1720] Fixed format for min date and max date

- ng2-components/ng2-activiti-tasklist/src/components/task-header.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/task-header.component.ts
- ng2-components/ng2-activiti-tasklist/src/i18n/en.json
- ng2-components/ng2-alfresco-core/src/components/view/card-view-dateitem.component.html
- ng2-components/ng2-alfresco-core/src/components/view/card-view-dateitem.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/view/card-view-mapitem.component.html
- ng2-components/ng2-alfresco-core/src/components/view/card-view-mapitem.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/view/card-view-textitem.component.html
- ng2-components/ng2-alfresco-core/src/components/view/card-view-textitem.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/view/card-view.module.ts
- ng2-components/ng2-alfresco-core/src/models/card-view-baseitem.model.ts
- ng2-components/ng2-alfresco-core/src/models/card-view-textitem.model.ts
> - [] Bugfix
Task Info Drawer Component is not localizable
Task Info Drawer should be …
> [ADF-1698] Task Info Drawer should be localizable

- ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer-layout.component.scss
* Revert the scss changes on Process Info Drawer
> - [ ] Bugfix
**Does this PR …
> Revert the scss changes on Process Info Drawer

- ng2-components/ng2-activiti-tasklist/src/assets/tasklist-service.mock.ts
- ng2-components/ng2-activiti-tasklist/src/services/tasklist.service.spec.ts
- ng2-components/ng2-activiti-tasklist/src/services/tasklist.service.ts
> - [x] Bugfix
* From DW side we use the method findAllTaskByState to fetch the active and completed status, but …
> [ADF-1747] Task service - findAllTaskByState return a wrong list.

- ng2-components/ng2-alfresco-core/src/services/app-config.service.spec.ts
- ng2-components/ng2-alfresco-core/src/services/app-config.service.ts
> - [ ] Bugfix
Add support for optional port number, `{:port}` emits `:8080` if port …
> [ADF-1778] optional port number

- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/data/share-datatable-adapter.ts
> [ADF-1815] Sort nodes by name

- docs/README.md
- docs/deleted-nodes-api.service.md
- docs/document-library.model.md
- docs/document-list.component.md
- docs/file-size.pipe.md
- docs/nodes-api.service.md
- docs/seeAlsoGraph.json
- docs/time-ago.pipe.md
- docs/user-initial.pipe.md
> - [ ] Bugfix
Added docs for Nodes Api service and Deleted Nodes Api service. Some supplementary detail in Document Library model. Some small docs about the pipes thrown in as a bonus. …
> [ADF-1586] Added docs for Core services

- demo-shell-ng2/src/index.html
fix the issue with reloading the page when HTML5 routing is used
note: the dot might be needed for Tomcat deployments and when using "#" for the routes, can be changed via `--base-href` flag (https://github.com/angular/angular-cli/wiki/build) when building the app.
> fix base path

- demo-shell-ng2/package.json
- demo-shell-ng2/proxy.conf.js
suppress native auth dialogue for ACS connections when running locally (dev mode)
> extend proxy config with native auth dialog fix

- ng2-components/ng2-alfresco-core/src/directives/node-delete.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/node-delete.directive.ts
- ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.spec.ts
- ng2-components/ng2-alfresco-core/src/directives/node-permission.directive.ts
- ng2-components/ng2-alfresco-core/src/directives/node-restore.directive.ts
- ng2-components/ng2-alfresco-documentlist/index.ts
- ng2-components/ng2-alfresco-tag/src/components/tag-node-list.component.scss
> - [x] Bugfix
1. Click on an empty folder:
Expected result: The delete icon button is disabled.
Actual result: The …
> [ADF-1786] fix delete and permission on the same button case

- demo-shell-ng2/src/app/components/file-view/file-view.component.html
- docs/viewer.component.md
- ng2-components/ng2-alfresco-viewer/index.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
- ng2-components/ng2-alfresco-viewer/src/directives/viewer-extension.directive.spec.ts
- ng2-components/ng2-alfresco-viewer/src/directives/viewer-extension.directive.ts
> - [ ] Bugfix
- rename 'extension-viewer' to 'add-viewer-extension'
- update the docs …
> [ADF-1843] rename 'extension-viewer' to 'add-viewer-extension'

- demo-shell-ng2/src/app/components/file-view/file-view.component.html
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.html
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.spec.ts
- ng2-components/ng2-alfresco-viewer/src/components/viewer.component.ts
Fixed
Added Unit tests for verifying the fix
> - [x] Bugfix
The display name is not updated if one is provideded …
> [ADF-1754] - Viewer's displayName property

- docs/datatable.component.md
- docs/info-drawer-layout.component.md
- docs/info-drawer.component.md
- docs/language-menu.component.md
- docs/metadata-indicators.md
- docs/node-delete.directive.md
- docs/node-favorite.directive.md
- docs/node-permission.directive.md
- docs/node-restore.directive.md
- docs/process-audit.directive.md
- docs/task-audit.directive.md
- docs/toolbar.component.md
> - [x] Bugfix
Outdated "md-" prefixes for Angular Material components in doc examples.
Prefixes replaced with the new "mat-" prefix. …
> [ADF-1820] Replaced md- prefix in docs with mat-

- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.spec.ts
- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.ts
> - [x] Bugfix
If the user preferences contain a page size value missing in the …
> [ADF-1682] pagination enhancements and fixes

- scripts/start.sh
> [ADF-1854] Use https to get specific alfresco-js-api branch

- ng2-components/ng2-activiti-tasklist/src/components/apps-list.component.html
- ng2-components/ng2-activiti-tasklist/src/components/apps-list.component.spec.ts
- ng2-components/ng2-activiti-tasklist/src/components/apps-list.component.ts
Enabling translation for application-list-component title
> - [x] Bugfix
the title for application list component is …
> [ADF-1772] fix for application name title translation

- ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.scss
> - [x] Bugfix
Try to click on the icon to close the menu, nothing happens 
Try to …
> [ADF-1866] Accordion menu - Doesn't collapse

- ng2-components/ng2-activiti-form/src/components/widgets/display-text/display-text.widget.html
- ng2-components/ng2-activiti-form/src/components/widgets/display-text/display-text.widget.scss
Fixed
> - [x] Bugfix
The text with line brakes is not wrapped correctly
Multiline text …
> [ADF-1861] - Line breaks not displayed in "Display Text" widget in forms

- docs/boilerplate.component.md
- docs/boilerplate.service.md
> - [ ] Bugfix
Added "boilerplate" files that can be used as templates for starting new component and service docs. The indexing script doesn't list them and Compodoc will ignore them, so it seems like a good idea to put them in the …
> [ADF-1586] Added boilerplate files to doc folder

- ng2-components/ng2-alfresco-core/src/components/info-drawer/info-drawer-layout.component.scss
- ng2-components/ng2-alfresco-core/src/components/view/card-view-dateitem.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1765
-  info drawer close button is too close to the right …
> [ADF-1765] - info drawer

- ng2-components/ng2-alfresco-core/src/components/toolbar/toolbar.component.scss
By default, toolbars use a neutral background color based on the current theme (light or dark). This can be changed to 'primary', 'accent', or 'warn'.
> - [ ] Bugfix …
> ADF Toolbar - Rollback background color.

- ng2-components/ng2-alfresco-documentlist/src/components/document-list.component.scss
> - [x] Bugfix
the whole layout becomes broken if the "drag and drop" translated text is too long (ex: japanese …
> [ADF-1865] [Document List] "Empty View" does not wrap long text

- docs/accordion-group.component.md
- ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.html
- ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.spec.ts
- ng2-components/ng2-alfresco-core/src/components/collapsable/accordion-group.component.ts
- ng2-components/ng2-alfresco-core/src/components/collapsable/collapsable.module.ts
- ng2-components/ng2-alfresco-core/src/material.module.ts
> - [ ] Bugfix
No way to show tooltip for accordion header icon
* Added tooltip for …
> [ADF-1906] Accordion Menu - Provide a way to show the tooltip

- lib/core/form/components/widgets/core/form-field.model.spec.ts
- lib/core/form/components/widgets/core/form-field.model.ts
> - [X] Bugfix
We are not correctly formatting data value when we retrieve it from APS …
> [ADF-1951] fixed parsing date value when on readonly mode

- lib/core/form/components/widgets/container/container.widget.html
- lib/core/form/components/widgets/container/container.widget.spec.ts
> - [X] Bugfix
Label appears on every group of form widget
Container Label is only …
> [ADF-1976] fixed visibility condition on container widget

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.scss
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/search/search-result.component.html
> - [x] Bugfix
toolbar and drag & drop are allowed on search result page
toolbar and …
> [ADF-1911] disabled toolbar and drag area on search results page

- lib/process-services/mock/task/task-details.mock.ts
- lib/process-services/task-list/components/task-header.component.html
- lib/process-services/task-list/components/task-header.component.spec.ts
- lib/process-services/task-list/components/task-header.component.ts
> - [x] Bugfix
* When assigning a user to a simple task, Requeue option displayed.
* …
> [ADF-1712] The <adf-task-header component displays a Requeue button for none pooled tasks

- lib/content-services/breadcrumb/dropdown-breadcrumb.component.scss
Relates to [ADF-1982], fixes issue with the `width` property being overwritten by material
> [ADF-1982] fix the issue with breadcrumb after material upgrade

- demo-shell/src/app/components/files/files.component.html
- docs/upload-button.component.md
- lib/content-services/upload/components/upload-button.component.html
- lib/content-services/upload/components/upload-button.component.spec.ts
- lib/content-services/upload/components/upload-button.component.ts
> - [x] Bugfix
- [ADF-2020]The upload button is not disabled when the 'enable upload' checkbox is not checked 
remove …
> [ADF-2020] The upload button is not disabled when the 'enable upload' checkbox is not checked  remove deprecated properties

- lib/core/info-drawer/info-drawer.component.html
- lib/core/info-drawer/info-drawer.component.spec.ts
- lib/core/info-drawer/info-drawer.component.ts
> - [x] Bugfix
Info drawer emits only the tab label as currentTab event data.
Info …
> [ADF-2007] Info Drawer - currentTab event should return a key not the label

- demo-shell/src/app/components/form/form.component.html
> - [x] Bugfix
The whole page is refreshed when clicking refresh form button on fake form example …
> [ADF-2019] removed refresh button from JSON example form

- docs/start-process.component.md
- docs/start-task.component.md
- docs/tag-actions.component.md
- docs/tag-node-list.component.md
- docs/task-attachment-list.component.md
- docs/task-details.component.md
- docs/task-filter.service.md
- docs/task-header.component.md
- docs/tasklist.service.md
- docs/toolbar-divider.component.md
- docs/toolbar-title.component.md
- docs/translation.service.md
- docs/upload-button.component.md
- docs/upload-drag-area.component.md
- docs/upload.service.md
- docs/user-info.component.md
- docs/viewer.component.md
> - [ ] Bugfix
Upload button docs showed a "parentId" property which is now obsolete.
The property is now updated to "rootFolderId". Also removed some …
> [ADF-2042] Fixed incorrect property name on Upload Button component docs

- docs/FormFieldValidator.md
- docs/activiti-alfresco.service.md
- docs/app-config.service.md
- docs/authentication.service.md
- docs/card-view.component.md
- docs/data-column.component.md
- docs/datatable.component.md
- docs/document-actions.service.md
- docs/document-list.component.md
- docs/extensibility.md
- docs/folder-actions.service.md
- docs/form.component.md
- docs/form.service.md
- docs/log.service.md
- docs/node-permission.directive.md
- docs/nodes-api.service.md
- docs/notification.service.md
- docs/translation.service.md
- docs/user-preferences.service.md
- docs/widget.component.md
> - [ ] Bugfix
Fix for an earlier PR that used path-style notation in import lines (eg, "lib/core/services") when they should have had the package notation ("@alfresco/adf-core"). Fortunately, Martin spotted my mistake :-) 
**Does this …
> [ADF-1586] Fixed incorrect import declarations in docs

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/core/pagination/paginated-component.interface.ts
- lib/core/pagination/pagination.component.html
- lib/core/pagination/pagination.component.spec.ts
- lib/core/pagination/pagination.component.ts
- do not show pagination elements when there is no data to manipulate
- emit next/prev page events only if there are items to paginate
> [ADF-2039] pagination fixes

- lib/content-services/search/components/search-control.component.html
- lib/content-services/search/components/search-control.component.scss
- lib/content-services/search/components/search-control.component.spec.ts
- lib/content-services/search/components/search-control.component.ts
> - [x] Bugfix
When search bar is active and user clicks onto another page element, the search input is still visible …
> [ADF-1924] - Some issues related to search bar

- docs/README.md
- docs/summary.json
> - [ ] Bugfix
Removed the Form Stencils page from the User Guide index (Ole believes that it doesn't work properly with 2.0, so we should remove it for release and fix later). …
> [ADF-2048] Removed form stencils page from User Guide

- docs/README.md
- docs/summary.json
> - [x] Bugfix
Link to Metadata Indicators Walkthrough page in user guide gets corrupted when processed by Compodoc (it uses the title as the filename and chokes on the colon character). …
> [ADF-2048] Fixed corrupted link in User Guide

- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.spec.ts
> - [X] Bugfix
setting showSidebar to true will show the sidebar even when the allowSidebar option is false
**What is …
> [ADF-1752] disable completely sidebar when allowSidebar option is false

- docs/viewer.component.md
- lib/core/viewer/components/viewer.component.ts
Add support for setting explicit viewer type when using URL values without file name and/or extension.
To be added post 2.0.
> [ADF-1889] support for explicit viewer type for URL

- lib/process-services/people/people.component.scss
This issue is now fixed
> - [x] Bugfix
The details for people  involved in a user task are displayed on one line …
> [ADF-2051] Involve people name is not displayed properly.

- docs/start-process.component.md
- lib/process-services/process-list/components/start-process.component.html
- lib/process-services/process-list/components/start-process.component.spec.ts
- lib/process-services/process-list/components/start-process.component.ts
> - [ ] Bugfix
Even If there is only one processDef present in process-start-form drop down,We have to manually …
> [ADF-2098] Start Process - the default process definition should be selected 

- lib/process-services/process-list/components/start-process.component.html
- lib/process-services/process-list/components/start-process.component.scss
- lib/process-services/task-list/components/start-task.component.html
- lib/process-services/task-list/components/start-task.component.scss
> - [x] Bugfix
* Start Task/Process - The start button does not have the primary colour …
> [ADF-2095] Start Task - The start button should have the primary colour

- demo-shell/package.json
- lib/core/services/renditions.service.ts
- lib/core/viewer/components/viewer.component.ts
> - [ ] Bugfix
- use special "image preview" rendition if PDF rendition not available …
> [ADF-2158] fallback to image preview if PDF rendition not available

- docs/start-process.component.md
- lib/process-services/mock/process/start-process.component.mock.ts
- lib/process-services/process-list/components/start-process.component.html
- lib/process-services/process-list/components/start-process.component.spec.ts
- lib/process-services/process-list/components/start-process.component.ts
> - [ ] Bugfix
Is not possible specify the processDefintion
- If your app has only one …
> [ADF-1880] processDefinitionId parameter in adf-start-process

- lib/core/sidebar/sidebar-action-menu.component.html
- lib/core/sidebar/sidebar-action-menu.component.scss
> - [x] Bugfix
* Overlay elements have wrong opacity and wrong bg color in dark themes. …
> [ADF-2174] Menus background color is not properly displayed in black themes

- docs/README.md
- docs/content-node-dialog.service.md
- docs/content-node-selector-panel.component.md
- docs/content-node-selector.component.md
> - [ ] Bugfix
All Content Node Dialog docs were contained in the Content Node Selector page.
The page is now split into separate pages for Content Node …
> [ADF-2201] Tidied Content Node Dialog docs

- lib/core/sidebar/sidebar-action-menu.component.scss
> - [x] Bugfix
* New Task option is smaller then Create Task drop down
* Width is for …
> [ADF-2208] The width of the 'New Task' option is smaller then Create Task drop down

- lib/core/mock/cookie.service.mock.ts
- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
- lib/core/services/cookie.service.ts
> - [x] Bugfix
For certain scenarios (loading with `file://` protocol within Electron for instance) the Cookies are …
> [ADF-2139] extra cookie availability check

- docs/README.md
> - [ ] Bugfix
Fix for the index page which was showing everything as "not currently documented". I think this might have happened when I interrupted the script while running the prop table tool. Sorry for that - it should all be back …
> [ADF-1769] Fixed index file that had been trashed unexpectedly

- docs/translation.service.md
> - [ ] Bugfix
Minor update: Gloria pointed out that the French example I used should have a space before the exclamation mark. The space is now added in correctly.
> - …
> [ADF-2228] Added missing space in French example

- lib/process-services/index.ts
> - [x] Bugfix
* ContentWidget Module and related classes are not exposed
* …
> [ADF-2251] ContentWidgetModule is not exposed from ADF

- docs/datatable.component.md
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [ ] Bugfix
Raise DOM bubbling "sorting-changed" event each time user clicks on …
> [ADF-2259] emit "sorting-changed" DOM event (DataTable)

- docs/content-node-dialog.service.md
- lib/config/DocProcessor/doctool.config.json
- lib/config/DocProcessor/tools/tscProps.js
- lib/config/DocProcessor/tools/tscProps.ts
- lib/config/DocProcessor/unistHelpers.js
- lib/content-services/content-node-selector/content-node-dialog.service.ts
> - [ ] Bugfix
The JSDoc/properties script now supports methods in services. I've added some JSDocs to content-node-dialog.service.md that can be seen in the Content Node Dialog service doc page. Any suggestions about improving the …
> [ADF-1769] Added support for methods to JSDoc tool

- demo-shell/src/app/components/files/files.component.ts
> - [x] Bugfix
* Translation is missing on delete warning messages when user has no permission. …
> [ADF-2263] Translation is missing on delete warning messages when user has no permission.

- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
> - [x] Bugfix
Please see Jira issue https://issues.alfresco.com/jira/browse/ADF-2175 …
> [ADF-2175] Document List requests are executed twice when opening the copy and move dialog

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
> - [x] Bugfix
* When we change the Pagination in task tab the new PageSize is not reflecting on reload and instead …
> [ADF-2324] Process Pagination - Items per page is not saved on user preferences

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
> - [ ] Bugfix
Breadcrumb displays wrong path after reloading the page. …
> [ADF-2026] fix breadcrumb demo shell navigation

- scripts/npm-clean.sh
> - [ ] Bugfix
When running the 'npm-clean.sh' script, 
the clean-lock command fails with message "sh: rimraf: …
> run clean-lock command first to prevent incomplete clean up

- docs/README.md
- docs/summary.json
- docs/undocStoplist.json
> - [ ] Bugfix
Removed undocumented components from the index (none of the ones added so far need documentation for 2.2.0, according to Andras's advice). Also restored the I18n article that had been lost from the guide section somehow. …
> [ADF-2357] Updated index for 2.2.0

- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.scss
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/process-services/attachment/process-attachment-list.component.scss
- lib/process-services/attachment/task-attachment-list.component.scss
> - [x] Bugfix
The header is now present even if the data table is empty
The header …
> [ADF-2344] Fix empty datatable hiding the header

- docs/version-manager.component.md
- lib/content-services/version-manager/version-manager.component.html
- lib/content-services/version-manager/version-manager.component.ts
- lib/content-services/version-manager/version-upload.component.html
- lib/content-services/version-manager/version-upload.component.ts
> - [ ] Bugfix
No callback on VersionUploadComponent and VersionManagerComponent. User will not know when file is …
> [ADF-2374] Add callback for VersionUploadComponent and VersionManagerComponent

- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
fix and tests added
> - [x] Bugfix
Please check https://issues.alfresco.com/jira/browse/ADF-2391 …
> [ADF-2391] skipCount is not reset on document-list when choosing a custom source from adf-sites-dropdown, nor the currentFolderId and folderNode

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/form/demo-form.ts
- demo-shell/src/app/components/form/fake-form.service.ts
- demo-shell/src/app/components/form/form-loading.component.html
- demo-shell/src/app/components/form/form-loading.component.scss
- demo-shell/src/app/components/form/form-loading.component.ts
- lib/core/form/components/form.component.spec.ts
- lib/core/form/components/widgets/core/form-field-validator.spec.ts
- lib/core/form/components/widgets/core/form-field.model.spec.ts
- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/components/widgets/core/form.model.ts
- lib/core/form/components/widgets/typeahead/typeahead.widget.ts
> - [X] Bugfix
Complex values (like dropdown widget) taken from process variable result cannot be used to feed the …
>  [ADF-2255] fixed loading for form loading data

- docs/task-details.component.md
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.spec.ts
- lib/process-services/task-list/components/task-details.component.ts
> - [ ] Bugfix
No event is raised when user claim/unclaim a task
claim task and …
>  [ADF-645] added claim and unclaim event for task details action

- demo-shell/src/app/components/files/files.component.html
- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/core/models/permissions.enum.ts
- lib/core/services/content.service.spec.ts
- lib/core/services/content.service.ts
> - [X] Bugfix
Copy action is not allowed even if the user has the relative 'read' permission on that folder.
**What …
> [ADF-2358] Always enabling copy action

- demo-shell/src/app/components/files/files.component.html
> - [X] Bugfix
Mobile menu on demo shell doesn't have any action associated so it's not working …
> [ADF-1814] added delete event to mobile menu

- docs/document-list.component.md
- lib/config/DocProcessor/docProcessor.js
- lib/config/DocProcessor/tools/tscProps.js
- lib/config/DocProcessor/tools/tscProps.ts
- lib/content-services/document-list/components/document-list.component.ts
> - [ ] Bugfix
Problem with property tables that have long default values: https://issues.alfresco.com/jira/browse/ADF-2456
When the default value is long, it …
> [ADF-2456] Fixed property table formatting

- lib/process-services/comments/comment-list.component.html
- lib/process-services/comments/comment-list.component.spec.ts
> - [ ] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-2457
* Added showHeader …
> [ADF-1572] Comment component - Hide the table header

- lib/config/DocProcessor/docProcessor.js
- lib/config/DocProcessor/tools/index.js
- lib/config/DocProcessor/tools/versionIndex.js
> - [ ] Bugfix
Updated doc tools so that they can find and index files correctly from subfolders within the docs folder. This will allow for gradual migration of doc files into folders corresponding to the ADF libraries.
**Does this PR …
> [ADF-2463] Update doc tools to work with subfolders

- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/process-service/process-service.component.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/core/services/user-preferences.service.spec.ts
- lib/core/services/user-preferences.service.ts
- lib/process-services/process-list/components/process-list.component.ts
- lib/process-services/task-list/components/task-list.component.ts
> - [ ] Bugfix
getDifferentPageSize is misbehaving
getDifferentPageSize is renamed as …
> [ADF-2443] renaming getDifferentPageSize to getDefaultPageSize

- lib/process-services/task-list/components/task-header.component.scss
> - [X] Bugfix
long text overflow when it's too long in task-header details tab
Added …
> [ADF-1913] added ellipsis to long category name

- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/document-list/services/document-actions.service.spec.ts
- lib/content-services/document-list/services/document-actions.service.ts
> - [X] Bugfix
When infinite scrolling is enabled the document list is not correctly refreshed …
> [ADF-2393] fixed reloading on delete with infinite scrolling

- lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
> - [x] Bugfix
Please see https://issues.alfresco.com/jira/browse/ADF-2397
fixed bug …
> [ADF-2397] Sometimes Load more on Content Node Selector does not load next page of results

- demo-shell/package.json
> - [x] Bugfix
After a long debug in the web community portal I discovered that the proxy configuration is at the moment used only with the command npm un …
> [no-issue] add proxy in start command

- demo-shell/src/app/components/files/files.component.html
> - [X] Bugfix
The toolbar buttons didn't perform the correct action on delete
The …
> [ADF-2393] added fix for infinite scrolling to the other delete buttons

- lib/process-services/process-list/services/process.service.spec.ts
- lib/process-services/process-list/services/process.service.ts
> - [ ] Bugfix
Reverting the [PR](https://github.com/Alfresco/alfresco-ng2-components/pull/3023) for [ADF-2405 Add new service to get all process definition …
> [ADF-2405] Add new service to get all process definition versions - REVERT

- docs/content-services/README.md
- docs/core/README.md
- docs/insights/README.md
- docs/process-services/README.md
- docs/user-guide/README.md
- lib/config/DocProcessor/tools/index.js
> - [ ] Bugfix
Added index pages for the doc subfolders, generated by the main indexing script. These probably won't be very useful for the GitHub docs but they should work quite well with the navigation structure in the Component …
> [ADF-2463] Added index pages to doc subfolders

- lib/core/form/components/widgets/text/text.widget.html
- lib/core/form/components/widgets/text/text.widget.spec.ts
- lib/core/form/components/widgets/text/text.widget.ts
> - [X] Bugfix
input mask placeholder is not showed when is set only the standard placeholder …
> [ADF-2486] input mask placeholder should be shown whenever it is present

- demo-shell/src/app/components/files/files.component.html
- docs/content-services/content-action.component.md
- lib/core/context-menu/context-menu-holder.component.ts
- lib/core/context-menu/context-menu.module.ts
> - [X] Bugfix
context menu is not translated on the fly
the translation is applied …
> [ADF-2484] moved translation into the context menu action

- lib/core/login/components/login.component.scss
> - [X] Bugfix
the logo at the login page is not being displayed in the right place  …
> [ADF-2454] fixing style for centering the logo

- docs/content-services/content-metadata.component.md
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.html
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.ts
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.html
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2504
Implemented
**Does …
> [ADF-2504] Add read-only mode for the content meta-data component

- docs/content-services/search.component.md
- docs/core/data-column.component.md
- docs/core/file-size.pipe.md
- docs/core/mime-type-icon.pipe.md
- docs/core/node-favorite.directive.md
- docs/core/node-name-tooltip.pipe.md
- docs/core/text-highlight.pipe.md
- docs/core/time-ago.pipe.md
- docs/core/translation.service.md
- docs/core/user-initial.pipe.md
- docs/process-services/people-list.component.md
- docs/process-services/people-search.component.md
- docs/process-services/process-attachment-list.component.md
- docs/process-services/process-list.component.md
- docs/process-services/task-attachment-list.component.md
- docs/process-services/task-list.component.md
- docs/user-guide/internationalization.md
- docs/user-guide/metadata-indicators.md
- docs/user-guide/stencils.md
> - [ ] Bugfix
Interpolation markers ("{{... }}") in Markdown code samples trigger off the interpolation feature in Jekyll and cause errors.
The code samples …
> [ADF-2526] Fixed interpolation marker issue in doc files

- demo-shell/src/app/components/files/files.component.ts
- lib/core/pagination/paginated-component.interface.ts
- lib/core/pagination/pagination.component.ts
> - [X] Bugfix
supporte page size was taken from the target and always the default value was taken. …
> [ADF-2444] supportedPageSize is used only via input parameter

- docs/content-services/upload-drag-area.component.md
- lib/content-services/upload/components/base-upload/upload-base.ts
- lib/content-services/upload/components/upload-button.component.ts
- lib/content-services/upload/components/upload-drag-area.component.spec.ts
- lib/content-services/upload/components/upload-drag-area.component.ts
- lib/content-services/upload/public-api.ts
> - [ ] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-711
* Added …
> [ADF-711] Drag and drop doesn't have the acceptedFilesType property

- docs/process-services/process-list.component.md
- lib/process-services/process-list/components/process-list.component.html
- lib/process-services/process-list/components/process-list.component.spec.ts
- lib/process-services/process-list/components/process-list.component.ts
> - [x] Bugfix
* First row is selected by default and there is no way to disable this behaviour.
* Once …
> [ADF-2505] ADF Processlist multi selection issues.

- docs/content-services/version-list.component.md
- docs/content-services/version-manager.component.md
- lib/content-services/version-manager/version-list.component.html
- lib/content-services/version-manager/version-list.component.spec.ts
- lib/content-services/version-manager/version-list.component.ts
- lib/content-services/version-manager/version-manager.component.html
- lib/content-services/version-manager/version-manager.component.spec.ts
- lib/content-services/version-manager/version-manager.component.ts
add input property to enable/disable viewing version comments
> - [ ] Bugfix
Further improvement on file versioning. Please see https://issues.alfresco.com/jira/browse/ADF-2561
**What is the …
> [ADF-2561] View comments on previous versions

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/file-view/file-view.component.html
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.html
- lib/core/card-view/components/card-view-boolitem/card-view-boolitem.component.html
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/i18n/en.json
> - [x] Bugfix
ADF-2624: All metadata card component children display parent info …
> tooltip and i18n fixes

- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [X] Bugfix
Pressing enter key throws the pressed key event but not trigger the row selection …
> [ADF-1714] added selection mechanism for enter key pressed on datatable

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/document-list/components/document-list.component.ts
> - [x] Bugfix
When navigating to search results or after closing a previewed file document list restarts always from …
> [ADF-2723] preventing document list to restart always from -my- folder

- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.html
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.ts
- lib/core/viewer/components/viewer.component.ts
> - [X] Bugfix
No node check permission was performed when use try to edit metadata for the selected node
**What is …
> [ADF-2601] added permission check to info editing button

- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-2703
* Selected Tab is …
> [ADF-2703] Info Drawer - Header does not navigate to name of default tab

- lib/config/DocProcessor/docProcessor.js
- lib/config/DocProcessor/doctool.config.json
> - [ ] Bugfix
Doc script can only have a single set of tools configured at a time. Changing configuration for different tasks (indexing and JSDocs) requires editing the config file.
**What …
> [ADF-2759] Updated doc script to allow multiple config profiles

- demo-shell/src/app/components/process-service/process-service.component.ts
> - [X] Bugfix
On demoshell at the moment when we click on the active task from the process and then we complete the …
> [ADF-2692] - refresh must be done on tab changes otherwise ViewChild obj refrence are null

- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [X] Bugfix
Once selected a single line with click another click won't unselect it …
> [ADF-2529] click will unselect the selected row

- lib/content-services/dialogs/folder.dialog.scss
- lib/content-services/dialogs/node-lock.dialog.html
- lib/content-services/version-manager/version-list.component.spec.ts
> - [X] Bugfix
Long names overflow in Lock dialog window
Long names now wrap to fit in …
> [ADF-2717] Long names fixed in lock dialog

- lib/config/DocProcessor/doctool.config.json
- lib/config/DocProcessor/ngHelpers.js
- lib/config/DocProcessor/tools/typeLinker.js
- lib/config/DocProcessor/tools/typeLinker.ts
> - [ ] Bugfix
Added a tool to find type names in Markdown files and convert them into links. The links point to the source file where the type is defined or to a doc file if one is available. For components, the tool can also handle …
> [ADF-2764] Added tool to add links to type names in Markdown files

- demo-shell/package.json
- lib/content-services/package.json
- lib/core/form/services/widget-visibility.service.spec.ts
- lib/core/form/services/widget-visibility.service.ts
- lib/core/package.json
- lib/insights/package.json
- lib/package.json
- lib/process-services/package.json
> - [x] Bugfix
Visibility condition doesn't work on tasks for a process that uses the same form on start event
**What …
> [ADF-2825] - Form visibility fix on Master

- lib/core/sidenav-layout/components/layout-container/layout-container.component.html
> - [X] Bugfix
Side nav closes when ESCAPE key is pressed
Side nav does not close when …
> [ADF-2767] Side nav closes when pressing escape key fixed

- lib/content-services/breadcrumb/breadcrumb.component.scss
- lib/core/datatable/components/datatable/datatable.component.scss
> - [X] Bugfix
Table not displaying content properly when name of files or folders are too long. …
> [ADF-2739] Long names in breadcrumb fixed

- demo-shell/src/custom-style.scss
- lib/core/datatable/components/datatable/datatable.component.scss
- lib/core/styles/_variables.scss
- lib/core/toolbar/toolbar.component.scss
> - [x] Bugfix
These components had a wrong background colour.
Following UI …
> [ADF-2760] Toolbar and datatable background colours fixed

- docs/core/accordion-group.component.md
- docs/core/alfresco-content.service.md
- docs/core/bpm-user.service.md
- docs/core/card-view.component.md
- docs/core/comment-list.component.md
- docs/core/comments.component.md
- docs/core/content.service.md
- docs/core/datatable.component.md
- docs/core/favorites-api.service.md
- docs/core/form-field.component.md
- docs/core/form-list.component.md
- docs/core/form-rendering.service.md
- docs/core/form.component.md
- docs/core/highlight-transform.service.md
- docs/core/host-settings.component.md
> - [ ] Bugfix
Another attempt to add the Class Members headings into some of the core docs.
> - [ ] Yes
> - [x] No
> [ADF-2847] Added class members heading to core docs

- demo-shell/src/app.config.json
- docs/content-services/search-filter.component.md
- lib/content-services/i18n/en.json
- lib/content-services/search/components/search-filter/models/response-facet-query-list.model.ts
- lib/content-services/search/components/search-filter/search-filter.component.html
- lib/content-services/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
- lib/content-services/search/components/search-slider/search-slider.component.html
- lib/content-services/search/components/search-slider/search-slider.component.spec.ts
- lib/content-services/search/components/search-slider/search-slider.component.ts
- lib/content-services/search/components/search-text/search-text.component.html
- lib/content-services/search/components/search-text/search-text.component.scss
- lib/content-services/search/components/search-text/search-text.component.spec.ts
- lib/content-services/search/components/search-text/search-text.component.ts
- lib/content-services/search/facet-query.interface.ts
- lib/content-services/search/search-configuration.interface.ts
- lib/content-services/search/search-query-builder.service.spec.ts
- lib/content-services/search/search-query-builder.service.ts
- lib/core/app-config/schema.json
> - [x] Bugfix
Fixes:
- [ADF-2896](https://issues.alfresco.com/jira/browse/ADF-2896) …
> search bug fixes and documentation updates

- lib/content-services/search/components/search-number-range/search-number-range.component.spec.ts
- lib/content-services/search/components/search-number-range/search-number-range.component.ts
> - [X] Bugfix
If FROM value is bigger than TO value, we still make an backend call, even if we know that list will …
> [ADF-2916] number range form validator added

- lib/core/sidenav-layout/components/layout-container/layout-container.component.html
> - [x] Bugfix
Sidenav closes on desktop size screen when ESC key is pressed. It also doesn't close when clicking …
> [ADF-2892] Sidenav now prevents closing itself when ESC key is pressed

- demo-shell/src/app/components/search/search-result.component.html
- demo-shell/src/app/components/search/search-result.component.ts
> - [X] Bugfix
Search service mess up with the new search result page
search-result …
> [ADF-2891] decoupled search service love

- demo-shell/src/app/components/process-service/process-service.component.html
- docs/core/sidebar-action-menu.component.md
- lib/core/sidebar/sidebar-action-menu.component.html
- lib/core/sidebar/sidebar-action-menu.component.scss
- lib/core/sidebar/sidebar-action-menu.component.ts
> - [x] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-2888
* Width for sidebar-action-menu-options was …
> [ADF-2888] UX doesn't respect the Sidenav specifiactions

- lib/content-services/permission-manager/components/add-permission/add-permission-panel.component.html
- lib/content-services/permission-manager/components/add-permission/add-permission-panel.component.spec.ts
> - [ ] Bugfix
Group everyone is showed only when there are result
Group everyone is …
> [ADF-2912] group everyone is always visible even for no search result

- tools/doc/mdNav.js
- tools/doc/mdNav.ts
- tools/doc/tools/tsInfo.js
- tools/doc/tools/tsInfo.ts
> - [ ] Bugfix
Blank JSDocs for an input or output will be copied into the Markdown files even if the Markdown table has docs for these properties. This means that useful doc text can be …
> [ADF-2979] Updated props script to avoid copying missing JSDocs

- lib/core/login/components/login.component.spec.ts
- lib/core/login/components/login.component.ts
> - [x] Bugfix
the event emit the password value too
only the username is emitted …
> [ADF-2985] Login - Only the username form control should be emitted by executeSubmit event

- demo-shell/src/app/app.component.ts
- lib/content-services/upload/components/base-upload/upload-base.spec.ts
- lib/content-services/upload/components/upload-button.component.spec.ts
- lib/core/mock/translation.service.mock.ts
- lib/core/services/page-title.service.spec.ts
- lib/core/services/page-title.service.ts
> - [ ] Bugfix
- allows using i18n resource keys as page titles
- watches and updates …
> [ADF-3028] i18n support for title service

- lib/core/viewer/components/viewer.component.scss
> - [x] Bugfix
Predictable/fixed max-width for Viewer name element.
**Does this PR …
> [ADF-2323] fixed constraint for viewer name width

- tools/doc/doctool.config.json
- tools/doc/mdNav.js
- tools/doc/mdNav.ts
- tools/doc/templates/service.combyne
- tools/doc/tools/tsInfo.js
- tools/doc/tools/tsInfo.ts
> - [ ] Bugfix
Blank JSDocs for methods and params will overwrite valid text in the method table in the Markdown file.
The tool now checks the Markdown and …
> [ADF-2979] Updated doc tools to avoid erasing MD docs with blank JSDocs in services

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/process-services/process-filters.component.md
- docs/process-services/task-filters.component.md
- lib/process-services/task-list/components/task-filters.component.spec.ts
- lib/process-services/task-list/components/task-filters.component.ts
> - [x] Bugfix
* For all apps, task list displays same set of tasks without app filter …
> [ADF-2884] Task List - Custom apps display all tasks

- demo-shell/src/app/components/files/files.component.html
- lib/content-services/breadcrumb/breadcrumb.component.html
- lib/content-services/breadcrumb/breadcrumb.component.scss
- lib/content-services/breadcrumb/dropdown-breadcrumb.component.html
- lib/content-services/breadcrumb/dropdown-breadcrumb.component.scss
- lib/content-services/content-node-selector/content-node-selector-panel.component.scss
> - [x] Bugfix
Style fixes:
- [ADF-3044] It is not possible to use breadcrumb outside …
> [ADF-3044] breadcrumb bug fixes

- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [X] Bugfix
Navigate in the default site via document list.
Go to datalists folder.
double click on a file
Notice …
> [ADF-2701] Fix no content node display

- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/process-services/task-list.component.md
- lib/process-services/task-list/components/task-list.component.ts
- lib/process-services/task-list/services/task-filter.service.ts
- lib/process-services/task-list/services/tasklist.service.spec.ts
- lib/process-services/task-list/services/tasklist.service.ts
> - [ ] Bugfix
We have a processDefinitionKey filter property but no code that is filtering the result
**What is the …
> [ADF-3065] TaskList component - Deprecate the processDefinitionKey

- lib/core/form/components/form.component.html
- lib/core/form/components/form.component.scss
- lib/core/form/components/form.component.visibility.spec.ts
- lib/core/mock/form/formDefinition.mock.ts
> - [X] Bugfix
showValidationIcon was an input attribute but not attached to any real function …
> [ADF-2999] readded form validation icon

- demo-shell/src/app/components/search/search-result.component.ts
- lib/content-services/search/search-query-builder.service.spec.ts
- lib/content-services/search/search-query-builder.service.ts
> - [x] Bugfix
- fixes [ADF-2913](https://issues.alfresco.com/jira/browse/ADF-2913): …
> [ADF-2913] search filter now remembers original user query

- lib/process-services/task-list/components/checklist.component.html
- lib/process-services/task-list/components/checklist.component.spec.ts
> - [X] Bugfix
Delete checklist button is enabled when the checklist task is completed …
> [ADF-2319] added a check for delete checklist button

- lib/content-services/search/components/search-check-list/search-check-list.component.html
- lib/content-services/search/components/search-check-list/search-check-list.component.scss
- lib/content-services/search/components/search-filter/search-filter.component.scss
> - [x] Bugfix
- [ADF-3060](https://issues.alfresco.com/jira/browse/ADF-3060) : …
> [ADF-3060] bold font for checked boxes

- demo-shell/src/app/components/files/files.component.html
- lib/core/directives/node-favorite.directive.spec.ts
- lib/core/directives/node-favorite.directive.ts
> - [ ] Bugfix
Revert changes since 5.2.x does not support isFavorite property
**Does …
> [ADF] revert ADF-3062 changes

- lib/core/form/components/widgets/core/form-field-validator.ts
> - [X] Bugfix
Error message for date is not formatted accordingly on the format set on APS …
> [ADF-2857] fixed message for date and date time widget

- docs/core/translation.service.md
- docs/user-guide/internationalization.md
> - [ ] Bugfix
It turned out that the procedure for registering new translation files and keys was quite well explained in the Translation service page already, but the i18n page didn't really draw attention to it properly. I've …
> [ADF-3087] Clarified section about adding/replacing keys in i18n guide

- lib/core/sidenav-layout/components/layout-container/layout-container.component.scss
- lib/core/toolbar/toolbar.component.scss
> - [ ] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-3068
* Sidebar background …
> [ADF-3068] ADF Sidenav/Toolbar - Ux background colour review

- lib/content-services/search/components/search-date-range/search-date-range.component.html
- lib/content-services/search/components/search-date-range/search-date-range.component.spec.ts
- lib/content-services/search/components/search-date-range/search-date-range.component.ts
- lib/core/utils/momentDateAdapter.ts
-fix localization
-fix tests
-show parse error
> - [ ] Bugfix
We must use the custom moment data adapter from adf-core because the behavior on date input has to be the same in all ADF.
**What is …
> [ADF-3042] Use the custom date adapter from adf-core on Search Date Range widget

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- docs/content-services/upload-drag-area.component.md
- lib/content-services/upload/components/base-upload/upload-base.spec.ts
- lib/content-services/upload/components/base-upload/upload-base.ts
- lib/content-services/upload/components/upload-button.component.ts
- lib/content-services/upload/components/upload-drag-area.component.ts
- lib/content-services/upload/components/upload-files.event.ts
- lib/content-services/upload/public-api.ts
- lib/core/services/upload.service.ts
> - [ ] Bugfix
- [ADF-3095](https://issues.alfresco.com/jira/browse/ADF-3095) Upload …
> [ADF-3095] ability to intercept, pause and resume upload process

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
> - [X] Bugfix
the animation are not loaded for the process tab
We have added a …
> [ADF-3102] added lazy loading for tab content to fix animations

- docs/content-services/content-action.component.md
- docs/content-services/document-list.component.md
- docs/content-services/search.component.md
- docs/core/info-drawer.component.md
- tools/doc/tools/tsInfo.js
- tools/doc/tools/tsInfo.ts
> - [ ] Bugfix
Union types (eg, "boolean | Function") are not displayed properly in the property table of the Content Action component. The vertical bar gets treated as a table column. …
> [ADF-2764] Fixed union type display glitches in property tables

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
> - [X] Bugfix
Sometimes clicking fast enough on the process tab make the pagination disappear.
This is a way more …
> [ADF-3111] [Demo shell] pagination is not showed when automation test are running

- docs/core/notification.service.md
- lib/core/services/notification.service.spec.ts
- lib/core/services/notification.service.ts
> - [ ] Bugfix
right now developers need to import TranslationService and translate messages in code before sending …
> [ADF-3118] translation support for notification service (snackbars)

- lib/content-services/dialogs/share.dialog.spec.ts
- lib/content-services/dialogs/share.dialog.ts
> - [X] Bugfix
When clicked on 'share' toolbar a new shared link is created if there's none. …
> [ADF-2710] removed default shared link creation at the opening

- demo-shell/src/app/components/form/form-list.component.html
- demo-shell/src/app/components/form/form-list.component.scss
- demo-shell/src/app/components/form/form-list.component.ts
> - [ ] Bugfix
Added a slide toggle to allow enable/disable the validation icon on the form. …
> [ADF-2999] added a way to test the validation icon on demo shell

- docs/process-services/process-list.component.md
> - [ ] Bugfix
Code samples use an obsolete property value "open".
Samples updated to the valid "all" property value. …
> [ADF-3133] Fixed inconsistency in doc example

- docs/content-services/file-draggable.directive.md
- lib/content-services/upload/components/upload-drag-area.component.html
- lib/content-services/upload/components/upload-drag-area.component.ts
- lib/content-services/upload/directives/file-draggable.directive.ts
> - [x] Bugfix
Right now, if user drops 10 files onto the drop area, there 10 separate single-upload events raised. …
> [ADF-3095] group uploaded files into single batch, IE fixes

- lib/core/directives/node-favorite.directive.spec.ts
- lib/core/directives/node-favorite.directive.ts
> - [ ] Bugfix
- don't fetch data from the server for each check for ACS 6.0 when …
> [ADF-3062] dual api support for Favorites

- docs/core/login.component.md
- lib/core/login/components/login.component.ts
> - [ ] Bugfix
The docs for the "showRememberMe" property in the login component don't mention what the checkbox actually does.
Added a note to the property …
> [ADF-3142] Added missing info about 'remember me' in login docs

- .travis.yml
- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/document-list/data/share-data-row.model.ts
- lib/content-services/document-list/data/share-datatable-adapter.spec.ts
- lib/content-services/document-list/data/share-datatable-adapter.ts
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/core/datatable/data/data-row.model.ts
- lib/core/datatable/data/object-datarow.model.ts
- lib/process-services/process-list/components/process-filters.component.spec.ts
- lib/process-services/task-list/components/task-filters.component.spec.ts
- lib/process-services/task-list/components/task-header.component.spec.ts
> - [x] Bugfix
error image resolver mimetype should not be part of datatable
the logic …
> [no-issue] error image resolver mimetype should not be part of datatable

- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/form/components/form.component.spec.ts
- lib/core/form/components/widgets/core/form-field.model.spec.ts
- lib/core/form/components/widgets/core/form-field.model.ts
> - [X] Bugfix
By default ADF form select first radio button option
No default …
> [ADF-3123] removed default choice for the first radio button

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- docs/content-services/content-action.component.md
- lib/content-services/document-list/components/content-action/content-action-list.component.ts
- lib/content-services/document-list/components/content-action/content-action.component.ts
- lib/content-services/document-list/components/document-list.component.html
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/document-list/models/content-action.model.ts
- lib/core/context-menu/context-menu-holder.component.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
This is a set of fixes for the previous updates in the scope of …
> [ADF-2859] fixes for the conditional visibility and disabled states

- lib/core/services/user-preferences.service.ts
- lib/core/settings/host-settings.component.ts
> - [x] Bugfix
the sso default setting is not fetched
the sso fields are filled in …
> [ADF-3195] Setting component - Fix default SSO config not filled in

- lib/content-services/upload/components/upload-drag-area.component.spec.ts
- lib/content-services/upload/components/upload-drag-area.component.ts
- lib/core/datatable/components/datatable/datatable.component.scss
> - [X] Bugfix
It is not possible to upload a file when on not opened folders
we …
> [ADF-3175] renabling upload on single target folder row

- docs/core/datatable.component.md
- docs/process-services/task-list.component.md
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/process-services/task-list/components/task-list.component.html
- lib/process-services/task-list/components/task-list.component.ts
> - [X] Bugfix
Double clicking on the tasklist duplicates the element clicked.
Starting a new task show the incorrect …
> [ADF-3196] fixed task selection and double click

- demo-shell/src/app/components/search/search-result.component.ts
- lib/content-services/search/search-query-builder.service.spec.ts
- lib/content-services/search/search-query-builder.service.ts
> - [x] Bugfix
If user selects a facet and then leaves the page, the settings are not reset next time the search is …
> [ADF-3217] reset previous search settings

- lib/core/datatable/components/datatable/datatable.component.ts
- lib/process-services/task-list/components/task-list.component.ts
> - [X] Bugfix
This 
The selection of the first element is not always performed
We …
> [ADF-3196] fixed selection of first tasklist element

- tools/doc/docProcessor.js
- tools/doc/mdNav.js
- tools/doc/mdNav.ts
- tools/doc/tools/tsInfo.js
- tools/doc/tools/tsInfo.ts
> - [ ] Bugfix
Fixed some bugs detected by running the tools with Linux (but unfortunately not the original bug I was looking for). Also added a verbose option to the doc tools that lists the doc files as they are processed. This should …
> [ADF-3203] Fixed doc tools bugs from Linux run and added verbose option

- lib/core/services/alfresco-api.service.ts
- lib/core/settings/host-settings.component.ts
> - [x] Bugfix
if the app.confi.json file doesn't contain the authType the get return nul …
> [ADF-3912] Setting Component - Return as default BASIC authType

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
> - [X] Bugfix
Drag&Drop file filtering is always applied
Drag&Drop file filtering is …
> [ADF-3233] fixed demo shell filtering for files on drag&drop]

- lib/core/services/sites.service.ts
> - [X] Bugfix
retrieving of ecm logged username in an incorrect way
using the …
> [ADF-3232] fixing retrieving for ecm user via site service

- docs/content-services/content-node-selector.component.md
- docs/content-services/file-draggable.directive.md
- docs/content-services/search-control.component.md
- docs/content-services/search.component.md
- docs/content-services/version-list.component.md
- docs/core/host-settings.component.md
- docs/core/infinite-pagination.component.md
- docs/core/node-restore.directive.md
- docs/insights/widget.component.md
- docs/process-services/task-list.component.md
- lib/process-services/task-list/components/task-list.component.ts
- tools/doc/tools/tsInfo.js
- tools/doc/tools/tsInfo.ts
> - [ ] Bugfix
Some deprecated property descriptions don't show the full comment text.
Updated the tools to show both the text from the deprecated tag line and …
> [ADF-3239] Fixed deprecated property descriptions

- lib/core/form/components/widgets/people/people.widget.spec.ts
- lib/core/form/components/widgets/people/people.widget.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3229
The result box is still displayed. …
> [ADF-3229] people widget list reseted if empty input

- lib/core/login/components/login.component.html
- lib/core/login/components/login.component.ts
> - [X] Bugfix
The 'Login' button is focused and 'Hide/Show' is skipped. …
> [ADF-2962] Login Hide/Show icon is not reachable

- lib/content-services/search/components/search-number-range/search-number-range.component.html
- lib/content-services/search/components/search-number-range/search-number-range.component.spec.ts
- lib/content-services/search/components/search-number-range/search-number-range.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3238
An error message should be displayed if value is …
> [ADF-3238] content size min error added

- lib/core/form/components/widgets/amount/amount.widget.html
- lib/core/form/components/widgets/amount/amount.widget.scss
> - [x] Bugfix
For custom currency input value is overlapped
Custom currency space is …
> [ADF-3266] fixed style for amount widget

- lib/core/models/user-process.model.ts
- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
- lib/process-services/task-list/components/task-details.component.spec.ts
- lib/process-services/task-list/components/task-details.component.ts
> - [X] Bugfix
Current logged in user for APS is taken from js-api instead of calling the proper API
**What is the …
> [ADF-2876] retrieving user from APS api and not from js-api

- demo-shell/src/app/components/app-layout/app-layout.component.html
- demo-shell/src/app/components/app-layout/app-layout.component.ts
> - [x] Bugfix
Sidenav button active even when there is no sidenav. …
> [ADF-2598] Sidenav button only visible when sidenav is enebled

- lib/core/form/components/widgets/container/container.widget.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3270
Header separator is not displayed in ADF.
**What is …
> [ADF-3270] header separator fix

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
> - [X] Bugfix
Start process is always showed when clicked on start or cancel
When …
> [ADF-2348] added actions on start and cancel start process buttons

- tools/doc/docProcessor.js
- tools/doc/doctool.config.json
- tools/doc/tools/index.js
- tools/doc/tools/toc.js
- tools/doc/tools/tsInfo.js
- tools/doc/tools/tsInfo.ts
- tools/doc/tools/tutorialIndex.js
- tools/doc/tools/tutorialIndex.ts
- tools/doc/tools/typeLinker.js
- tools/doc/tools/typeLinker.ts
- tools/doc/tools/versionIndex.js
> - [ ] Bugfix
Initial refactoring to simplify doc tools (there is plenty more that can be done but this is a good start). Tools now run one after another and doc files are cached in memory rather than loaded in twice each. This is …
> [ADF-3279] Initial refactoring of doc tools

- lib/content-services/upload/components/upload-drag-area.component.spec.ts
- lib/content-services/upload/components/upload-drag-area.component.ts
> - [X] Bugfix
Drag and drop a folder onto another folder doesn't upload the folder in the correct location.
**What …
> [ADF-3294] fixed drag and drop folder to onto a folder

- demo-shell/src/app/components/files/files.component.html
- lib/content-services/dialogs/share.dialog.ts
- lib/content-services/directives/node-share.directive.ts
> - [x] Bugfix
Share button gets disabled once it's clicked and never comes back to enabled again …
> [ADF-2599] Share button disabled after clicking it fixed

- lib/core/models/file.model.ts
- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
> - [ ] Bugfix
extra options where not added to addNode request performed
extra …
> [ADF-3263] added extra options to upload file for upload service

- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.scss
- lib/core/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
Gallery view breaks flex layout at the bottom. (Last row).
Now every …
> [ADF-2765] Fix for the gallery view in datatable component

- lib/process-services/process-list/components/process-filters.component.spec.ts
- lib/process-services/process-list/components/process-filters.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3284
Once we render the component if we change the …
> [ADF-3284] filterParam checking in onChanges

- docs/content-services/upload-version-button.component.md
> - [ ] Bugfix
Upload version button docs contain a section about upload restrictions. These restrictions no longer apply and so the docs are incorrect. …
> [ADF-3288] Removed restrictions from upload version button docs

- lib/content-services/search/components/search-filter/search-filter.component.html
- lib/content-services/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
- lib/content-services/search/search-query-builder.service.spec.ts
- lib/content-services/search/search-query-builder.service.ts
> - [x] Bugfix
add the grouping by the facet field, it is not possible to have: …
> [ADF-3367] facets multiselect fixes

- lib/core/info-drawer/info-drawer.component.html
- lib/core/info-drawer/info-drawer.component.scss
> - [x] Bugfix
label is not displayed in case there is an icon set on an adf-info-drawer-tab
This is because it is …
> Display icon and label in adf-info-drawer-tab

- lib/content-services/content-metadata/services/config/aspect-oriented-config.service.ts
- lib/content-services/content-metadata/services/config/indifferent-config.service.ts
- lib/content-services/content-metadata/services/config/layout-oriented-config.service.ts
> - [x] Bugfix
```
Warning: Can't resolve all parameters for IndifferentConfigService in …
```
> remove injectable decorator from non-services

- demo-shell/src/app/components/app-layout/app-layout.component.html
- docs/core/header.component.md
- lib/core/layout/components/header/header.component.html
- lib/core/layout/components/header/header.component.spec.ts
- lib/core/layout/components/header/header.component.ts
- lib/core/layout/layout.module.ts
> - [ ] Bugfix
Please see https://issues.alfresco.com/jira/browse/ADF-3360, …
> [ADF-3358][ADF-3359][ADF-3360] Logo link and tooltip and hex colors

- lib/content-services/dialogs/confirm.dialog.ts
> - [X] Bugfix
The styles for the delete version confirm popup are not correct
The …
> [ADF-2669] fixed style for confim buttons

- lib/content-services/test.ts
- lib/core/context-menu/context-menu-holder.component.spec.ts
- lib/core/directives/node-restore.directive.spec.ts
- lib/core/form/components/widgets/people/people.widget.spec.ts
- lib/core/form/components/widgets/typeahead/typeahead.widget.spec.ts
- lib/core/karma.conf.js
- lib/core/services/translate-loader.spec.ts
- lib/core/test.ts
- lib/core/testing/core.testing.module.ts
- lib/core/viewer/components/mediaPlayer.component.spec.ts
- lib/core/viewer/components/pdfViewer-password-dialog.spec.ts
- lib/core/viewer/components/pdfViewer-password-dialog.ts
- lib/core/viewer/components/pdfViewer-thumbnails.component.spec.ts
- lib/core/viewer/components/pdfViewer.component.spec.ts
- lib/core/viewer/components/pdfViewer.component.ts
- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/viewer.module.ts
- lib/insights/test.ts
- lib/process-services/test.ts
- package-lock.json
- package.json
> - [x] Bugfix
- PDF.js library is imported 2 times (one via the script import in `angular.json` and another by the …
> [ADF-3501] PDF view fixes

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- lib/process-services/task-list/components/task-details.component.html
- lib/process-services/task-list/components/task-details.component.ts
> - [X] Bugfix
a wrong slide property was inserted in task-details.
the slider for e2e …
> [ADF-3513] - removed wrong slide from task-detail component

- lib/content-services/search/components/search-date-range/search-date-range.component.ts
> - [x] Bugfix
Please check Jira issue https://issues.alfresco.com/jira/browse/ADF-3511 …
> [ADF-3511] The error message for "Created date" fields is not the correct one when are no inputs - fix

- lib/content-services/search/forms/live-error-state-matcher.ts
> - [x] Bugfix
Please check https://github.com/Alfresco/alfresco-ng2-components/issues/3736 and corresponding Jira …
> [ADF-3510] Search facets date-range goes invalid when empty - fix

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/process-services/process-filters.component.md
- lib/process-services/process-list/components/process-filters.component.spec.ts
- lib/process-services/process-list/components/process-filters.component.ts
> - [X] Bugfix
When a process filter is force selected via the component no event is sent and the process list is not …
> [ADF-3500] added an event to react when a filter is force selected

- demo-shell/src/app/components/shared-link-view/shared-link-view.component.html
- demo-shell/src/app/components/shared-link-view/shared-link-view.component.ts
- docs/core/viewer.component.md
- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [X] Bugfix
When the shared link is invalid the invalid viewer is showed
When the …
> [ADF-3324] added redirect to 404 page when the shared link is invalid

- lib/core/form/components/widgets/dynamic-table/dynamic-table.widget.html
- lib/core/form/components/widgets/dynamic-table/dynamic-table.widget.scss
> - [X] Bugfix
Dynamic Table Widget overflows the start process card when there are too many fields.
**What is the …
> [ADF-3509] - added autoscroll for dynamic table widget

- demo-shell/src/app/components/tag/tag.component.html
- demo-shell/src/app/components/tag/tag.component.ts
- docs/content-services/tag-node-list.component.md
- lib/content-services/tag/tag-node-list.component.html
- lib/content-services/tag/tag-node-list.component.spec.ts
- lib/content-services/tag/tag-node-list.component.ts
> - [ ] Bugfix
Currently the adf-tag-node-list component show the option to remove the tag. There is a need to make …
> [ADF-2640] remove option configurable

- lib/content-services/document-list/components/document-list.component.html
- lib/content-services/document-list/components/document-list.component.scss
- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3119
Datatable component not rendering layout properly …
> [ADF-3119] Document list styles refactored for datatable thumbnails

- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3532
Datatable cells overflowing when they are clicked …
> [ADF-3532] IE Datatable layout fix

- lib/process-services/task-list/components/start-task.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3009
Date is not checked after using date picker and error …
> [ADF-3009] Date picker checked on Start Task Component

- docs/README.md
- docs/content-services/README.md
- docs/content-services/content-metadata-card.component.md
- docs/user-guide/summary.json
- docs/versionIndex.md
> - [ ] Bugfix
Content metadata card component docs use the wrong class to get the property table because the filename is wrong (content-metadata.component.md instead of …
> [ADF-3577] Corrected doc filename for content metadata card component

- docs/content-services/document-list.component.md
- docs/content-services/document-list.service.md
- docs/content-services/file-draggable.directive.md
- docs/content-services/upload-drag-area.component.md
- docs/core/accordion-group.component.md
- docs/core/form.component.md
- docs/core/infinite-pagination.component.md
- docs/core/node-restore.directive.md
- docs/core/viewer.component.md
- docs/process-services/task-list.component.md
- lib/content-services/document-list/components/document-list.component.ts
- lib/content-services/document-list/services/document-list.service.ts
- lib/content-services/upload/components/base-upload/upload-base.ts
- lib/content-services/upload/components/upload-drag-area.component.ts
- lib/content-services/upload/directives/file-draggable.directive.ts
- lib/core/directives/node-restore.directive.ts
- lib/core/form/components/form.component.ts
- lib/core/form/components/widgets/widget.component.ts
- lib/core/form/services/form.service.ts
- lib/core/pagination/infinite-pagination.component.ts
- lib/core/viewer/components/viewer.component.ts
- lib/process-services/task-list/components/task-list.component.ts
- tools/doc/SourceInfoClasses.js
- tools/doc/SourceInfoClasses.ts
- tools/doc/yamlTemplates/propSyntaxSection.ejs
- tools/doc/yamlTemplates/property.ejs
- tools/doc/yamlTemplates/template.ejs
> - [ ] Bugfix
Accessor properties were not always shown correctly in doc file property tables. Some deprecated tags in doc comments were not being recognised. …
> [ADF-3587] Fixed doc comment problems

- demo-shell/src/polyfills.ts
- package.json
> [ADF-3592] remove web-animation-js not needed anymore in angular 6

- demo-shell/src/app/components/files/files.component.scss
- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
Cell values on Datatable component in Custom Source Page are unaligned because of a previous fix …
> [ADF-3614] Fix styling bug in Custom Sources Page

- lib/core/viewer/components/pdfViewer.component.spec.ts
- lib/core/viewer/components/pdfViewer.component.ts
- lib/core/viewer/components/viewer.component.spec.ts
> - [x] Bugfix
- release worker resources on the Viewer destroy
**Does this PR …
> [ADF-3610] fix pdf worker memory leak

- demo-shell/src/app/components/config-editor/config-editor.component.html
- demo-shell/src/app/components/config-editor/config-editor.component.ts
- demo-shell/src/app/components/file-view/file-view.component.html
- demo-shell/src/app/components/file-view/file-view.component.ts
- docs/core/viewer.component.md
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [X] Bugfix
Enable only right sidebar
Open the viewer
Current behaviour:
It shows two sidebar buttons, the left …
> [ADF-3643] Viewer shows both sidebar icons

- lib/process-services/process-list/components/start-process.component.scss
> - [X] Bugfix
Arrow is not displayed at the end of the autocomplete
Arrow is …
> [ADF-3642] moved on the end the arrow

- demo-shell/src/app/components/process-service/process-service.component.html
- docs/process-services/task-filters.component.md
- lib/process-services/task-list/components/task-filters.component.html
- lib/process-services/task-list/components/task-filters.component.spec.ts
- lib/process-services/task-list/components/task-filters.component.ts
> - [ ] Bugfix
rename hasIcon to shoIcon to be equal to process-filter
**Does this PR …
> [ADF-3595] rename hasIcon to showIcon to be equal to process-filter

- lib/core/app-config/schema.json
- lib/process-services/i18n/en.json
- lib/process-services/task-list/components/task-header.component.ts
- lib/process-services/task-list/models/task-details.model.ts
> - [ ] Bugfix
As a developer, I want be able to use all the task properties out of …
> [ADF-3676]  Task Header - Expose task properties out of the box

- e2e/content-services/share-file/share_file.e2e.ts
- e2e/content-services/share-file/unshare_file.e2e.ts
> - [ ] Bugfix
Making sure that automated test introduced for shared link follow ADF specifications (naming, test cases ID etc)
**What is the current behaviour?** (You can also link to an open …
> [ADF-3645] Rectoring names of e2e for shared link

- e2e/content-services/search/search_filters.e2e.ts
- e2e/pages/adf/searchFiltersPage.ts
> - [ ] Bugfix
Automated test to check that collapsed search filters stay collapsed after search. …
> [ADF-3644] Automated test for search filters collapse

- lib/content-services/document-list/components/document-list.component.ts
> - [ ] Bugfix
delay document list "loading" spinner for 1 second,
if the server response is fast enough the users …
> delayed document list spinner

- lib/core/form/components/widgets/date-time/date-time.widget.scss
- lib/core/form/components/widgets/date/date.widget.scss
- lib/core/form/components/widgets/form.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3655
Form widgets layout is broken on Internet Explorer 11 …
> [ADF-3655] Fix layout issue on IE 11

- demo-shell/tslint.json
- lib/tslint.json
- license-community.txt
- tools/tslint-rules/adfEnterpriseLicenseBannerRule.js
- tools/tslint-rules/adfEnterpriseLicenseBannerRule.ts
- tools/tslint-rules/package.json
- tslint.json
Create another tslint rule adf-enterprise-license
> - [ ] Bugfix
"adf-license-banner": …
> Improve the lint rule adf-license-banner

- lib/core/viewer/components/txtViewer.component.ts
> - [ ] Bugfix
Typescript error is thrown when using local copy of ng2-components from AMA:
```
ERROR in …
```
> [APM-520] Fixing typescript compilation error to work together with AMA

- lib/core/form/components/widgets/date-time/date-time.widget.scss
- lib/core/form/components/widgets/date/date.widget.scss
- lib/process-services/task-list/components/start-task.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3655
Date and date-time widget inputs don't show on IE 11. …
>  [ADF-3655] Fix styles on date, date-time and people widgets

- demo-shell/src/app/components/search/search-result.component.html
- e2e/pages/adf/content_services/search/components/search-checkList.ts
- lib/content-services/search/components/search-check-list/search-check-list.component.html
- lib/content-services/search/components/search-check-list/search-check-list.component.scss
- lib/content-services/search/components/search-filter/search-filter.component.html
- lib/content-services/search/components/search-filter/search-filter.component.scss
- lib/content-services/search/components/search-radio/search-radio.component.html
- lib/content-services/search/components/search-radio/search-radio.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3734
Search filters do not wrap when the name is too long. …
> [ADF-3734] Fix search filters not wrapping

- demo-shell/src/app/components/tree-view/tree-view-sample.component.html
- demo-shell/src/app/components/tree-view/tree-view-sample.component.ts
- docs/content-services/tree-view.component.md
- lib/content-services/tree-view/components/tree-view.component.html
- lib/content-services/tree-view/components/tree-view.component.spec.ts
- lib/content-services/tree-view/components/tree-view.component.ts
- lib/content-services/tree-view/data/tree-view-datasource.ts
> - [X] Bugfix
Changing node id will append subscription and trigger several times the children queries.
Invalid node …
> [ADF-3763] fixed subscription for node child and invalid node id

- docs/core/activiti-alfresco.service.md
> - [ ] Bugfix
Github ignores strings that appear like HTML tags, such as `<ExternalContentLink>` …
> Markup code headings as code

- docs/process-services-cloud/task-list-cloud.component.md
- lib/process-services-cloud/src/lib/task-list-cloud/components/task-list-cloud.component.ts
> - [ ] Bugfix
Task list cloud docs have the processDefinitionId property listed twice. This isn't a script problem - the doc file is new and the property table was copied manually from …
> [ADF-3782] Fixed doc comments for task list cloud component

- demo-shell/src/app/components/file-view/file-view.component.html
- demo-shell/src/app/components/file-view/file-view.component.ts
> - [X] Bugfix
User with no permission can attempt to put a comment on a file. …
> [ADF-2661] disabling comments when user doesn't have permissions

- docs/README.md
- docs/extensions/README.md
- tools/doc/docProcessor.js
- tools/doc/tools/index.js
> - [ ] Bugfix
Added a folder to house the docs for the Extensions library and added a corresponding section to the index pages. There are no docs for this library yet but we are now ready for them when they arrive :-)
**Does this PR …
> [ADF-3745] Added Extensions folder and index section to docs

- lib/content-services/version-manager/version-manager.component.scss
> - [x] Bugfix
The adf-new-version-container CSS class has a fixed 800px height and that provides problems with using …
> [ADF-3215] Fix Versions dialog height

- lib/core/datatable/components/datatable/datatable.component.html
> - [X] Bugfix
When checkboxes are enabled the row icon is wrongly changed to the selected one. …
> [ADF-3220] fixed icon change when multiselection is enabled

- lib/core/viewer/components/pdfViewerHost.component.scss
- stylelint-config.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3814
Page Host class had …
> [ADF-3814] Fix PDF file not centered on PDF Viewer

- lib/process-services-cloud/src/lib/app-list-cloud/components/app-list-cloud.component.html
- lib/process-services-cloud/src/lib/app-list-cloud/components/app-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process-list-cloud/components/process-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process-list-cloud/mock/process-list-service.mock.ts
- lib/process-services-cloud/src/lib/process-list-cloud/models/process-cloud-preset.model.ts
- lib/process-services-cloud/src/lib/start-task-cloud/components/people-cloud/people-cloud.component.html
- lib/process-services-cloud/src/lib/start-task-cloud/components/start-task-cloud.component.html
- lib/process-services-cloud/src/lib/start-task-cloud/components/start-task-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task-list-cloud/components/task-list-cloud.component.html
- lib/process-services-cloud/src/lib/task-list-cloud/components/task-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task-list-cloud/mock/fakeTaskResponseMock.ts
- lib/process-services-cloud/src/lib/task-list-cloud/models/task-preset-cloud.model.ts
… to its own translation file
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3785
There are some strings …
> [ADF-3785] Move translated strings used in Process Services Cloud

- docs/content-services/document-list.component.md
- lib/content-services/document-list/components/document-list.component.ts
> - [ ] Bugfix
Updated the unclear `sortingMode` property description for the document list based on the reply to a Gitter question.
> - [ ] Yes
> - [x] No
> [ADF-3816] Clarified misleading property description in Document List docs

- lib/process-services/i18n/en.json
- lib/process-services/process-list/components/start-process.component.html
- lib/process-services/process-list/components/start-process.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3282
App crashes when the length of the process is longer …
> [ADF-3282] Add maximum length validator to Start Process Form

- lib/core/viewer/components/imgViewer.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3815
Image viewer component renders differently with IE …
> [ADF-3815] Fix image render on Viewer Component for IE 11

- lib/content-services/upload/components/base-upload/upload-base.spec.ts
- lib/content-services/upload/components/base-upload/upload-base.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-2675
Files will be uploaded …
> [ADF-2675] The string given for 'Extension accepted' is not trim

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3124
The name is not properly displayed and the edit …
> [ADF-3124] Fix overflowing text on file info dialog values

- lib/content-services/search/components/search-sorting-picker/search-sorting-picker.component.html
- lib/content-services/search/components/search-sorting-picker/search-sorting-picker.component.spec.ts
- lib/content-services/search/components/search-sorting-picker/search-sorting-picker.component.ts
- lib/core/sorting-picker/sorting-picker.component.html
- lib/core/sorting-picker/sorting-picker.component.spec.ts
- lib/core/sorting-picker/sorting-picker.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3802
Default sorting always overwrites ascending value …
> [ADF-3802] Default ascending order fix

- lib/core/pagination/infinite-pagination.component.spec.ts
- lib/core/pagination/infinite-pagination.component.ts
> - [X] Bugfix
pageSize of 25 is always used
uses pageSize defined on the component or by the UserPreferencesService
if not defined
**Does …
> Fix pageSize value fetch for infinite pagination

- docs/user-guide/internationalization.md
- lib/core/login/components/login.component.html
- lib/core/login/components/login.component.ts
- lib/core/services/translate-loader.service.ts
- lib/core/services/translation.service.ts
- lib/core/services/user-preferences.service.spec.ts
- lib/core/services/user-preferences.service.ts
- lib/core/templates/error-content/error-content.component.spec.ts
- lib/core/templates/error-content/error-content.component.ts
> - [x] Bugfix
Browser cultures are not supported (i.e. `pt-BR` or `zh-CN`)
- support …
> [ADF-3784] support for browser cultures (i18n)

- lib/content-services/dialogs/library/library.dialog.html
- lib/content-services/dialogs/library/library.dialog.spec.ts
- lib/content-services/dialogs/library/library.dialog.ts
- lib/content-services/i18n/en.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3864
**Does this PR …
> [ADF-3864] Create library - no error is displayed when name contains white spaces only

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/files.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3822
The Create Library …
> [ADF-3822] Add Create Library button on mobile view

- docs/core/form-field.component.md
- docs/core/form-rendering.service.md
- docs/core/form.component.md
- docs/insights/README.md
- docs/insights/widget.component.md
- docs/release-notes/RelNote161.md
- docs/release-notes/RelNote170.md
- docs/release-notes/RelNote180.md
- docs/release-notes/RelNote190.md
- docs/release-notes/RelNote200.md
- docs/release-notes/RelNote210.md
- docs/release-notes/RelNote220.md
- docs/release-notes/RelNote240.md
- docs/release-notes/RelNote250.md
- docs/release-notes/RelNote260.md
- docs/user-guide/app-extensions.md
- docs/user-guide/transclusion.md
> - [ ] Bugfix
Fixed broken links in docs. These were mostly in the release notes, mainly old links where the paths have since changed. There were also a few incorrect type links (the problem that caused those links in the first place …
> [ADF-3745] Fixed broken links in docs

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/files.component.html
- lib/content-services/dialogs/library/library.dialog.html
- lib/content-services/dialogs/library/library.dialog.spec.ts
- lib/content-services/dialogs/library/library.dialog.ts
- lib/content-services/i18n/en.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3855
A new form validator …
> [ADF-3855] Add minimum length to library title

- docs/process-services/people.component.md
- docs/release-notes/RelNote161.md
- docs/release-notes/RelNote170.md
- docs/release-notes/RelNote180.md
- docs/release-notes/RelNote190.md
- docs/release-notes/RelNote200.md
- docs/release-notes/RelNote210.md
- docs/release-notes/RelNote220.md
- docs/release-notes/RelNote230.md
- docs/release-notes/RelNote240.md
- docs/release-notes/RelNote250.md
- docs/release-notes/RelNote260.md
> - [ ] Bugfix
GIF images are not handled correctly by the Builder Network tools and so they don't get published in the docs.
GIF image URLs changed to …
> [ADF-3911] Converted GIF image URLs to absolute

- lib/core/app-config/app-config.service.ts
- lib/core/settings/host-settings.component.html
- lib/core/settings/host-settings.component.spec.ts
- lib/core/settings/host-settings.component.ts
> - [ ] Bugfix
The identityHost is needed to call the API of admin keycloak
**Does …
> [ADF-3910] Expose the identityHost as part of the setting component

- demo-shell/src/app.config.json
- docs/core/app-config.service.md
- lib/core/app-config/app-config.service.ts
- lib/core/app-config/schema.json
- lib/core/services/alfresco-api.service.ts
- lib/core/viewer/components/pdfViewer.component.ts
> - [ ] Bugfix
- provide support for XMLHttpRequest.withCredentials (corresponding …
> [ADF-3938] support for XMLHttpRequest.withCredentials flag

- demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.ts
- demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.ts
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3866
https://issues.alfresco.com/jira/browse/ADF-3867 …
> [ADF-3866] Fix several bugs in Task List Cloud component

- lib/core/form/components/start-form.component.html
- lib/core/layout/components/sidebar-action/sidebar-action-menu.component.html
- lib/process-services/people/components/people-search/people-search.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-1344
Some old selectors are not working after adding the …
> [ADF-1344] Old directive selectors should still be usable

- docs/core/empty-content.component.md
- lib/content-services/document-list/components/document-list.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4000
Old template selectors were no longer working.
**What …
> [ADF-4000] Fix custom directive selectors on Datatable component

- docs/core/icon.component.md
- lib/core/icon/icon.component.html
- lib/core/icon/icon.component.ts
> - [ ] Bugfix
It is not possible to set the color of the underlying icon (accent, primary, etc.) …
> adf-icon: expose color property

- demo-shell/src/app/components/content-node-selector/content-node-selector.component.ts
- e2e/pages/adf/contentServicesPage.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
> - [x] Bugfix
If the rowFilter parameter is changed, then the excludeSiteContent is ignored …
> [ADF-3854] destination picker - exclude site content after rowFilter reset

- demo-shell/src/app/components/icons/icons.component.html
- docs/core/icon.component.md
- lib/core/icon/icon.component.ts
- lib/core/icon/icon.module.ts
- lib/core/services/thumbnail.service.ts
> - [x] Bugfix
Some icons from the Thumbnail service overwrite the Material icons when used in the <adf-icon> …
> [ADF-4010] fix icon clashes in adf-icon

- tools/doc/doctool.config.json
- tools/doc/tools/toc.js
> - [ ] Bugfix
Table of contents tool for the docs generates an incorrect anchor for the link when certain characters are in the corresponding heading text. …
> [ADF-4013] Fixed anchor generation in ToC doc tool

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3999
The metadata layout is broken …
> [ADF-3999] Regression - Fix metadata layout

- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
- lib/core/services/auth-guard-bpm.service.spec.ts
- lib/core/services/auth-guard-bpm.service.ts
- lib/core/services/auth-guard-ecm.service.spec.ts
- lib/core/services/auth-guard-ecm.service.ts
- lib/core/services/auth-guard.service.spec.ts
- lib/core/services/auth-guard.service.ts
> - [x] Bugfix
When you use a Kerberos env WithCredentials TRUE should disable the …
> [ADF-3938] withCredentials TRUE the authguard should be skipped

- protractor.conf.js
> - [ ] Bugfix
Enable time information for each e2e tests, should help to …
> display each test duration for e2e runs

- lib/core/core.module.ts
> - [x] Bugfix
The page is refreshed twice after login. User is redirected to /session-state...  …
> [ADF-3966] remove providers from Coremodule to avoid double loading api-service

- docs/README.md
- docs/abn-tree.yml
- docs/compatibility.md
- docs/versionIndex.md
> - [ ] Bugfix
Added version compatibility page. The info for v2.5 was missing from the original RtoR document but I've used the info from the version index for the time being. …
> [ADF-4016] Added page with version compatibility table

- docs/content-services/content-node-selector-panel.component.md
- docs/content-services/content-node-selector.component.md
- docs/content-services/document-list.component.md
- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/document-list/components/document-list.component.ts
> - [ ] Bugfix
Added italics to the "where" property to avoid confusion with the normal English usage of the word, as mentioned in #4275.
> - [ ] Yes
> - [x] No
> [ADF-3745] Added styling to *where* property for clarity

- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/core/pagination/infinite-pagination.component.spec.ts
- lib/core/pagination/infinite-pagination.component.ts
> - [x] Bugfix
Steps to reproduce the issue:
Login as your own user.
Create 2 Folders, Folder1 and Folder2.
Upload 2 files, fileA and fileB under Folder1, fileC and fileD under Folder2.
Navigate …
> [ADF-4039] Copy/Move of the files/folders is not working when the root folder of the user is chosen.

- lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/document-list/components/document-list.component.spec.ts
- lib/content-services/document-list/components/document-list.component.ts
- lib/core/pagination/infinite-pagination.component.ts
- lib/core/pagination/pagination.component.ts
> - [x] Bugfix
Preconditions
create a folder inside 'User Homes'
add file/folder inside it
make sure that it's displayed on a page > 2 (name it like 'z-something...')
Steps:
go inside ‘User …
> [ADF-4042] fix reset pagination issue when enter in a folder

- e2e/content-services/document-list/document-list-component.e2e.ts
> - [ ] Bugfix
This test is about visual elements, we agreed that we shouldn't automate this kind of tests.
**What is …
> Removing C268119 test that shouldn't be automated

- lib/content-services/content-node-selector/content-node-dialog.service.ts
> - [x] Bugfix
The attachfolder from a repository in the process service is a bit slow because it perform a call to …
> [ADF-4077] fix performance issue getSite in processservice usign -my-

- demo-shell/src/app/components/file-view/file-view.component.ts
> - [x] Bugfix
Go to adfdev.envalfersco.com
Login in Content Services
Upload a file
Open file with viewer
Click on …
> [ADF-4097] Fix add comment section

- lib/content-services/search/search-query-builder.service.ts
> - [x] Bugfix
Query Builder service crashes if no Search config provided in app.config.json …
> [ADF-2971] make search config optional

- lib/content-services/content-metadata/services/content-metadata.service.spec.ts
- lib/content-services/content-metadata/services/content-metadata.service.ts
- lib/content-services/content-node-share/content-node-share.dialog.spec.ts
> - [ ] Bugfix
property category is showing when all the properties are not there
As …
> [ADF-4099] The metadata group is always showed even though the properties are not there

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/app-layout/cloud/cloud-settings.component.html
- demo-shell/src/app/components/app-layout/cloud/cloud-settings.component.ts
- demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.ts
- demo-shell/src/app/components/app-layout/cloud/services/cloud-layout.service.ts
- demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.ts
> - [ ] Bugfix
It's not possible to disable redirection to task details when a task is clicked in the task list cloud …
> [ADF-4147] Add task details redirection toggle in cloud settings page

- demo-shell/src/app.config.json
- e2e/pages/adf/searchFiltersPage.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
- lib/content-services/search/facet-field.interface.ts
- lib/content-services/search/search-configuration.interface.ts
- lib/content-services/search/search-query-builder.service.spec.ts
- lib/content-services/search/search-query-builder.service.ts
> - [ ] Bugfix
There was a API limitation so that the response was not correct for the facet intervals that had labels with spaces inside them. This problem is now fixed.
The filter component is …
> [ADF-4083] search facetIntervals - empty spaced labels support 

- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.scss
- lib/core/i18n/en.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3861
The datatable component is missing labels on the …
> [ADF-3861] Make datatable 508 compliance according

- demo-shell/src/app.config.json
- demo-shell/src/app/components/search/search-result.component.html
- docs/content-services/search-chip-list.component.md
- docs/content-services/search-filter.component.md
- lib/content-services/i18n/en.json
- lib/content-services/search/components/search-chip-list/search-chip-list.component.html
- lib/content-services/search/components/search-chip-list/search-chip-list.component.ts
- lib/content-services/search/components/search-filter/models/search-filter-list.model.ts
- lib/content-services/search/components/search-filter/search-filter.component.html
- lib/content-services/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/search/components/search-filter/search-filter.component.ts
- lib/content-services/search/components/search-radio/search-radio.component.ts
- lib/content-services/search/search-configuration.interface.ts
- lib/core/app-config/schema.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3401
The new facet items received in the response are not …
> [ADF-3401] Search filters - fix facet update

- e2e/pages/adf/process-cloud/editProcessFilterCloudComponent.ts
- e2e/process-services-cloud/process-custom-filters.e2e.ts
- e2e/process-services-cloud/processListCloud.config.ts
> - [x] Bugfix
The appName dropdown in the Process Cloud filters has no duplicate …
> [ADF-3989] appname duplicated after switching between saved filters

- e2e/pages/adf/searchFiltersPage.ts
- e2e/search/search-filters.e2e.ts
> [ADF-4083] Parse 'escaped' empty spaced labels inside facetFields

- demo-shell/resources/i18n/ar.json
- docs/extensions/README.md
- docs/extensions/preview-extension.component.md
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.ts
- lib/extensions/src/lib/components/viewer/viewer-extension.interface.ts
> - [ ] Bugfix
As a developer, I want to create a viewer extension that can target …
> [ADF-4225] Viewer extension accept multiple file type

- lib/core/services/user-preferences.service.spec.ts
- lib/core/services/user-preferences.service.ts
…language picker
> - [X] Bugfix
Note I changed this behavior, if the user :
doesn't …
> [ADF-4215] not store locale if not present in app.config.json or changed by the language picker

- INTRODUCTION.md
- docs/user-guide/adf-introduction.md
> - [ ] Bugfix
Updated links and info in the introduction and moved it to the docs folder (but the new page is still linked from the original file). The main motivation for this is to give a good starting point when people search for …
> [ADF-4239] Updated and moved ADF introduction page

- demo-shell/src/app/components/permissions/demo-permissions.component.ts
… Page
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4205
Console error appears when the user does not …
> [ADF-4205] Demo-shell - Fix console error on Permissions page

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- docs/content-services/components/document-list.component.md
- lib/content-services/document-list/components/document-list.component.html
- lib/content-services/document-list/components/document-list.component.scss
- lib/content-services/document-list/components/document-list.component.ts
- lib/core/about/about.component.ts
> - [x] Bugfix
I can set up a property of the DocumentLIst to stick the header during …
> [ADF-4267] expose stiky heder in document list

- lib/core/layout/components/layout-container/layout-container.component.html
- lib/core/layout/components/layout-container/layout-container.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/secure/RapidBoard.jspa?rapidView=529&view=detail&selectedIssue=ADF-422 …
> [ADF-4229] Fix big space issue when ADF set to RTL 

- lib/content-services/search/components/search-date-range/search-date-range.component.html
- lib/content-services/search/components/search-number-range/search-number-range.component.html
- lib/content-services/search/components/search-radio/search-radio.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4179
Some of the classes that the facet button components …
> [ADF-4179] Regression - Fix styles of facet-buttons

- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4242
Inconsistent format date for process and task header …
> [ADF-4242] Make Date format uniform across components

- lib/core/datatable/components/datatable/datatable.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4287 
The long task names …
> [ADF-4287] Fix tasks UI in Process Cloud

- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4301
No accessibility border on cells when clicked
**What …
> [ADF-4301] Regression - Fix accessibility issue

- .travis.yml
- demo-shell/src/app/components/card-view/card-view.component.ts
- docs/core/components/card-view.component.md
- lib/core/card-view/components/card-view-mapitem/card-view-mapitem.component.scss
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.scss
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/card-view/interfaces/card-view-item-properties.interface.ts
- lib/core/card-view/interfaces/card-view-textitem-properties.interface.ts
- lib/core/card-view/models/card-view-textitem.model.ts
> - [x] Bugfix
When you have a clicakble item always show the edit icon
When you have …
> [ADF-4313] add click callback and remove icon if is not editable

- lib/content-services/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/content-node-selector/name-location-cell/name-location-cell.component.scss
- lib/content-services/content-node-selector/name-location-cell/name-location-cell.component.ts
- lib/core/datatable/components/datatable/datatable.component.html
> - [x] Bugfix
The breadcrumb of the content node selector does not show the current folder when it's a custom site. …
> [ADF-4264] Fix content node selector breadcrumb and styling

- docs/core/components/info-drawer-tab.component.md
- lib/core/info-drawer/info-drawer.component.html
- lib/core/info-drawer/info-drawer.component.scss
> - [x] Bugfix
Show icon, text or icon + text
Shrink tab headers for icon-only mode …
> [ADF-4330] info drawer fixes

- lib/core/i18n/en.json
- lib/core/templates/error-content/error-content.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4250
The error component displays errors that don't exist …
> [ADF-4250] Improve Error Content component

- demo-shell/src/app/components/home/home.component.scss
- lib/core/layout/components/layout-container/layout-container.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4279
The home component is not displayed in the middle …
> [ADF-4279] Demo-shell - Fix home component layout

- lib/core/settings/host-settings.component.html
- lib/core/settings/host-settings.component.ts
> - [x] Bugfix
Host Settings Dialog closes on Enter key pressed without saving changes in the form. …
> [ADF-4343] Fix bug closing dialog on Host Settings Component

- lib/testing/src/lib/core/protractor.util.ts
> - [ ] Bugfix
this PR introduces a tagged template `byCss` (ES6) that greatly reduces …
> add protractor utils class

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/confirm-dialog/confirm-dialog-example.component.html
- demo-shell/src/app/components/confirm-dialog/confirm-dialog-example.component.ts
- docs/content-services/dialogs/confirm.dialog.md
- lib/content-services/dialogs/confirm.dialog.html
- lib/content-services/dialogs/confirm.dialog.scss
- lib/content-services/dialogs/confirm.dialog.spec.ts
- lib/content-services/dialogs/confirm.dialog.ts
> - [ ] Bugfix
Content dialog not supporting custom html as message
Content dialog is …
> [ADF-4327] added templating for content dialog

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4270
No name is displayed …
> [ADF-4270] Fix empty name cell in process header cloud

- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.scss
- lib/core/datatable/components/datatable/date-cell.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4360
The template was missing a class that the datatable …
> [ADF-4360] Fix Ellipsis on Date Cell Template

- docs/content-services/services/search-query-builder.service.md
- lib/content-services/search/search-query-builder.service.spec.ts
- lib/content-services/search/search-query-builder.service.ts
> - [x] Bugfix
- Raise a new `error` event on internal search errors, so that apps can …
> [ADF-4193] search error notifications and empty results

- demo-shell/src/app.config.json
- docs/core/services/storage.service.md
- lib/content-services/document-list/services/document-actions.service.spec.ts
- lib/content-services/document-list/services/document-list.service.spec.ts
- lib/content-services/document-list/services/folder-actions.service.spec.ts
- lib/core/app-config/app-config.service.ts
- lib/core/app-config/debug-app-config.service.ts
- lib/core/directives/node-favorite.directive.spec.ts
- lib/core/mock/alfresco-api.service.mock.ts
- lib/core/services/alfresco-api.service.ts
- lib/core/services/storage.service.spec.ts
- lib/core/services/storage.service.ts
- lib/core/services/user-preferences.service.ts
- lib/process-services-cloud/karma.conf.js
- lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.spec.ts
- lib/process-services/karma.conf.js
- lib/process-services/process-list/services/process-filter.service.spec.ts
- lib/process-services/process-list/services/process.service.spec.ts
- lib/process-services/task-list/services/task-filter.service.spec.ts
- lib/process-services/task-list/services/tasklist.service.spec.ts
- lib/testing/src/lib/process-services-cloud/actions/testing-alfresco-api.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3887
Different ADF apps were sharing the same local …
> [ADF-3887] Different local storages for different ADF apps

- lib/core/datatable/components/datatable/json-cell.component.scss
- lib/core/datatable/components/datatable/json-cell.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4372
When json is to wide it breaks data column layout …
> [ADF-4372] Fix json type Data Column styles

- docs/tutorials/using-components.md
In the tutorial, when working with events, it says that we want to show an allert when submitting the login form but in the code just below it binds the allert to the "success" event and not to the "executeSubmit" event. Also calls the method mySuccessMethod and not myExecuteSubmitMethod as it does at the very and of the Tutorial.
So i made the appropriate changes to adjust the code and the tutorial to show how to properly bind an allert to the "eventSubmit" event.
Regards
Luca Biondo
> - [x] Docs have been added / updated (for bug fixes / …
> Fromo mySuccessMethod to myExecuteSubmitMethod

- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/app-layout/app-layout.component.ts
- demo-shell/src/app/components/datatable/drag-and-drop/datatable-dnd.component.html
- demo-shell/src/app/components/datatable/drag-and-drop/datatable-dnd.component.ts
- demo-shell/src/app/components/datatable/drag-and-drop/datatable-dnd.module.ts
- docs/core/components/datatable.component.md
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.ts
> - [ ] Bugfix
not possible to write a code that handles drop events on cells or headers  …
> [ADF-4213] drop events for DataTable component

- demo-shell/src/app/components/datatable/datatable.component.html
- demo-shell/src/app/components/datatable/datatable.component.ts
- e2e/content-services/permissions/permissions-component.e2e.ts
- e2e/content-services/permissions/site-permissions.e2e.ts
- e2e/pages/adf/contentServicesPage.ts
- e2e/proxy.ts
- lib/content-services/content-node-selector/content-node-selector-panel.component.scss
- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
Sticky header overflows when active
https://issues.alfresco.com/jira/browse/ADF-4374 …
> [ADF-4376] Fix Sticky Header in Datatable Component

- demo-shell/src/app/components/file-view/file-view.component.html
- demo-shell/src/app/components/file-view/file-view.component.ts
- docs/content-services/components/content-metadata-card.component.md
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.html
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.ts
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.html
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/content-services/content-metadata/components/content-metadata/mock-data.ts
> - [ ] Bugfix
It enables the user to open the info with the desired aspect in the …
> [ADF-4359] -  Add the possibility to chose wich panel to show first in info-drawer

- cspell.json
- lib/content-services/content-node-share/content-node-share.dialog.html
- lib/core/clipboard/clipboard.directive.ts
- lib/core/datatable/components/datatable/json-cell.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4423
https://issues.alfresco.com/jira/browse/ADF-4405
Json …
> [ADF-4405] [ADF-4423] Fix clipboard directive on json cell

- demo-shell/src/app/components/file-view/file-view.component.html
- demo-shell/src/app/components/file-view/file-view.component.ts
- docs/content-services/components/content-metadata-card.component.md
- e2e/content-services/metadata/metadata-properties.e2e.ts
- e2e/pages/adf/metadataViewPage.ts
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.html
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
- lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.ts
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.html
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/content-services/content-metadata/components/content-metadata/mock-data.ts
> - [ ] Bugfix
It enables the user to open the info with the desired aspect in the …
> [ADF-4359] - Add the possibility to chose wich panel to show first in info-drawer

- lib/core/form/components/widgets/core/form-field-validator.ts
> - [X] Bugfix
typeahead fail if the id of the object value is too big
typeahead …
> [ADF-4404] fix typeahead validation

- e2e/content-services/metadata/metadata-properties.e2e.ts
- e2e/pages/adf/metadataViewPage.ts
> - [ ] Bugfix
There is a 'Display Aspect' input field, where user can type the aspect …
> [ADF-4447] -  Should be able to choose which aspect to show expanded in the info-drawer

- scripts/remove-alfresco-dependencies.sh
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4411
Now the script keeps …
> [ADF-4411] Keep js-api dependency in remove-dep... script

- demo-shell/src/app/components/cloud/community/community-task-details-cloud.component.html
- lib/core/form/components/widgets/core/form-field.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4460
APS1 backend fails when an empty array is passed as …
> [ADF-4460] Fix for empty value upload widget on a form

- demo-shell/src/app/components/cloud/community/community-task-details-cloud.component.ts
- demo-shell/src/app/components/cloud/task-details-cloud-demo.component.ts
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
> - [ ] Bugfix
* Upload widget is mapped to cloud upload in different components that use task cloud form
**What is …
> [ADF-4454] Map upload field to UploadCloudWidget in task cloud form

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/pipes/multi-value.pipe.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4455
Metadata multivalue fields show and store items with …
> [ADF-4455] Fix whitespaces trim in multivalue metadata field

- lib/core/datatable/components/datatable/datatable.component.scss
- lib/core/layout/components/layout-container/layout-container.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4478
Datatable width broken on third party apps and empty …
> [ADF-4478] Fix layout container and empty template

- demo-shell/src/app/components/file-view/file-view.component.html
- demo-shell/src/app/components/files/files.component.html
- docs/core/components/info-drawer-tab.component.md
- docs/core/components/info-drawer.component.md
- lib/core/info-drawer/info-drawer.component.html
- lib/core/info-drawer/info-drawer.component.spec.ts
- lib/core/info-drawer/info-drawer.module.ts
- lib/process-services/task-list/components/task-details.component.html
> - [ ] Bugfix
Minor enhancement, add support for i18n for Info Drawer component and …
> [ADF-3126] i18n support for info drawer tabs

- docs/core/services/process-content.service.md
- lib/content-services/upload/components/upload-button.component.html
- lib/content-services/upload/components/upload-button.component.scss
- lib/core/form/components/widgets/upload/upload.widget.html
- lib/core/form/components/widgets/upload/upload.widget.scss
- lib/process-services-cloud/src/lib/form/components/upload-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/upload-cloud.widget.scss
- lib/process-services/content-widget/attach-folder-widget.component.html
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4467
The clickable area of the upload file widget does not …
> [ADF-4467] Fix Upload File Widget layout

- demo-shell/src/app/components/config-editor/config-editor.component.html
- demo-shell/src/app/components/config-editor/config-editor.component.ts
- e2e/content-services/upload/excluded-file.e2e.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4442
The config editor could only target those properties …
> [ADF-4442] Show whole app config in config editor

- lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts
- scripts/check-activiti-env.js
> Cloud - Fix the context name

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4476
Start process and start task components have …
> [ADF-4476] Unify layout for start process/task components

- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4588
**Does this PR …
> [ADF-4588] Datatable - fix copy content tooltip for ellipsis cell

- lib/tslint.json
- package.json
> - [x] Bugfix
The pre-commit hook fails on e2e.ts files
It now runs a different …
> Fix pre-commit hook

- demo-shell/src/app/components/app-layout/cloud/form-demo/cloud-form-demo.component.ts
- lib/core/form/services/widget-visibility.service.spec.ts
- lib/core/form/services/widget-visibility.service.ts
- lib/core/mock/form/widget-visibility.service.mock.ts
> - [x] Bugfix
* In cloud-form visiblity fails when the visibility conditions are configured based on form variables …
> [ADF-4546] Visibility conditions for Form variables don't work on Multiline Widget.

- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
Removed DELETED status
Modified unit test to check recent changes
> - [x] Bugfix
'Deleted' option is available in the …
> [ADF-4034] Task list cloud - The Deleted task is changing the Status from "Deleted" in "Canceled"

- demo-shell/src/app/app.component.scss
> - [ ] Bugfix
[ADF-4633](https://issues.alfresco.com/jira/browse/ADF-4633)
**Does …
> [ADF-4633] DemoShell - MatIcon directionality

- e2e/content-services/version/version-actions.e2e.ts
> - [x] Bugfix
After restoring the old version of the file, the document list in Content Services was not updated …
> [ADF-4462] - Should be possible to restore an old version of your file and the document list updated

- docs/process-services-cloud/components/form-cloud.component.md
- docs/process-services/components/form.component.md
- lib/core/form/components/form-base.component.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services/form/form.component.spec.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4441
Save button gets …
> [ADF-4441] Save button should be disabled when form fields are invalid

- lib/core/directives/node-delete.directive.ts
> - [x] Bugfix
when you want to use the "adf-delete" directive from a search result ("search api" which returns a …
> fix adf-delete directive NodeResult

- e2e/process-services-cloud/people-group-cloud-component.e2e.ts
> [ADF-4600] Should be able to filter groups based on composite roles

- demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.html
- e2e/process-services-cloud/people-group-cloud-component.e2e.ts
- lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.html
- lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
- lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4041
1. The preselected value is not displayed in the …
> [ADF-4041] Fix preselected user selection on People Cloud Component

- lib/core/about/about.component.html
> - [X] Bugfix
Alfresco Content Services URL label is missing inside About component …
> About component, Add missing Content Services URL label

- lib/core/pipes/time-ago.pipe.ts
> - [x] Bugfix
Date isn't displayed properly in DocumentList
https://issues.alfresco.com/jira/browse/ADF-4677
**What …
> [ADF-4677] Make time ago use Angular Date formats

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/card-view/models/card-view-baseitem.model.ts
> - [x] Bugfix
There are some properties for which the display is wrong. Please check issue: …
> [ADF-4696] Display name on metadata card

- demo-shell/src/app.config.json
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4721
The material datetime …
> [ADF-4721] Fix Material Datetime Picker date format

- lib/core/datatable/components/datatable/datatable.component.scss
> - [ ] Bugfix
> - [x] Other... Please describe: visual changes
https://issues.alfresco.com/jira/browse/ADF-4726
**Does …
> [ADF-4726] fileSize header is now left aligned with bottom cells

- lib/core/form/components/widgets/date-time/date-time.widget.ts
- lib/core/form/components/widgets/date/date.widget.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4682
The date in this two widgets do not match the display …
> [ADF-4682] Fix displayed date in date time and date widget

- e2e/core/viewer/viewer-content-services-component.e2e.ts
- e2e/pages/adf/viewerPage.ts
> - [x] Bugfix
The current behaviour is to show endless spinner when the file is unsupported in th viewer.
**What is …
> [ADF-4480] Viewer shows endless spinner for unsupported files

- e2e/process-services/dynamic-table-date-picker.e2e.ts
- lib/testing/src/lib/core/pages/form/widgets/dynamicTableWidget.ts
…e to save the dynamic table with non-required DateTime field.
> - [x] Bugfix
Before the Date was not saved properly …
> [ADF-4716][ADF-3247] Tests for checking saved date format

- lib/core/form/components/widgets/date-time/date-time.widget.ts
- lib/core/form/components/widgets/date/date.widget.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4754
The display date was …
> [ADF-4754] Fix Date Widget display value

- demo-shell/src/app/components/card-view/card-view.component.html
- demo-shell/src/app/components/card-view/card-view.component.ts
- docs/core/components/card-view.component.md
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.html
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
- lib/core/card-view/components/card-view-item-dispatcher/card-view-item-dispatcher.component.spec.ts
- lib/core/card-view/components/card-view-item-dispatcher/card-view-item-dispatcher.component.ts
- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.html
- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
- lib/core/card-view/components/card-view/card-view.component.html
- lib/core/card-view/components/card-view/card-view.component.ts
- lib/core/i18n/en.json
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
- lib/process-services/task-list/components/task-header.component.html
- lib/process-services/task-list/components/task-header.component.ts
> - [ ] Bugfix
* There was no way to set date value to empty.
* There was no way to set select none.
**What is the …
> [ADF-4755][CardViewDate&SelectItemComponent] Provide a way to reset date and none option as default.

- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
- lib/process-services-cloud/src/lib/form/services/form-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
> - [ ] Bugfix
Process definition id is mandatory for form with attach file
To meet …
> [ADF-4753] - fixed calling for standalone task

- e2e/process-services/form-widgets-component.e2e.ts
- lib/core/form/services/form-rendering.service.spec.ts
- lib/core/form/services/form-rendering.service.ts
- lib/testing/src/lib/core/pages/form/widgets/displayValueWidget.ts
- lib/testing/src/lib/core/pages/form/widgets/widget.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4572
Display value field is …
>  [ADF-4572] Display value widget display issue when it has no value

- lib/core/form/components/widgets/core/form-field.model.ts
- lib/process-services-cloud/src/lib/form/models/form-cloud.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4788
Due to the way we parse process variables on Cloud …
> [ADF-4788] Fix parsing of process variables from APS2 BE

- lib/core/form/components/widgets/core/form-field-validator.spec.ts
- lib/core/form/components/widgets/core/form-field-validator.ts
- lib/core/form/components/widgets/date/date.widget.ts
- lib/process-services-cloud/src/lib/form/components/date-cloud/date-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/date-cloud/date-cloud.widget.scss
- lib/process-services-cloud/src/lib/form/components/date-cloud/date-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/date-cloud/date-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
- lib/process-services-cloud/src/lib/form/form-cloud.module.ts
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4775
The date widget is not compatible anymore with the …
> [ADF-4775] Make date widget compatible with APS1 and APS2

- lib/cli/bin/.gitignore
- lib/cli/bin/adf-cli
- lib/cli/package-lock.json
- lib/cli/package.json
- lib/cli/tsconfig.json
> - [ ] Bugfix
Improve the ADF CLI behavior when using locally:
- add missing …
> allow "npm link" when using cli tool

- lib/process-services/task-list/components/task-header.component.spec.ts
- lib/process-services/task-list/components/task-header.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4795
After completing a task, its form is still clickable …
> [ADF-4795] The form is editable after completing the task in APS

- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/components/widgets/date-time/date-time.widget.ts
> - [x] Bugfix
The datetime is saved an hour less when completing a form task in Process Services APS1.
Upload the …
> [ADF-4800] fix date issue +1 time zone in date widget

- docs/core/components/card-view.component.md
> - [ ] Bugfix
> - [ X ] Documentation
The Card View component documentation incorrectly labels the date format field as a "boolean"
**What …
> Documentation fix for Card View component

- e2e/pages/adf/process-services/taskDetailsPage.ts
- e2e/process-services/task-details.e2e.ts
> - [ ] Bugfix
Automation for non-editable task details when the task is completed. …
> [ADF-4809] Automation for non-editable task details when completed

- scripts/check-env/check-cs-env.js
> - [ ] Bugfix
Disk full prevent the execution of the e2e
Try to upload a file before …
> Check remote env if is full before to start the e2e CS

- scripts/travis/build/build.sh
> - [ ] Bugfix
The new about page takes the running commit sha from the package.json. For this reason we need to …
> [ADF-4852] Make use of ADF-CLI command to update sha

- lib/core/form/components/widgets/amount/amount.widget.html
- lib/core/form/components/widgets/amount/amount.widget.spec.ts
- lib/core/form/components/widgets/amount/amount.widget.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4764
The placeholder is shown in readOnly mode and this …
> [ADF-4764] Hide placeholder in Amount Widget in readOnly mode

- cspell.json
- docs/README.md
- docs/content-services/directives/toggle-icon.directive.md
- docs/versionIndex.md
- e2e/content-services/upload/cancel-upload.e2e.ts
- e2e/content-services/version/version-actions.e2e.ts
- lib/content-services/i18n/en.json
- lib/content-services/upload/components/file-uploading-dialog.component.html
- lib/content-services/upload/components/file-uploading-list-row.component.html
- lib/content-services/upload/components/file-uploading-list-row.component.scss
- lib/content-services/upload/directives/toggle-icon.directive.spec.ts
- lib/content-services/upload/directives/toggle-icon.directive.ts
- lib/content-services/upload/public-api.ts
- lib/content-services/upload/upload.module.ts
> - [x] Bugfix
[ADF-4865](https://issues.alfresco.com/jira/browse/ADF-4865)
**Does …
> [ADF-4865] Upload Dialog - row actions not accessible by keyboard alone

- lib/process-services/content-widget/attach-file-widget.component.ts
- lib/process-services/content-widget/attach-file-widget.components.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4794
We can able to upload …
> [ADF-4794] Not able to attach a second file to a form after one has already been attached

- lib/core/services/external-alfresco-api.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4868
**Does this PR …
> [ADF-4868] [APS-1] adf-content-node-selector seems broken when we upload from External Alfresco content service

- lib/core/form/form-base.module.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/APM-1413
Editor broke when …
> [APM-1413] Fix Json dialog on Form json widget

- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4925
Process variables are not correctly mapped and as a …
> [ADF-4925] Fix process variable mapping in Form Cloud component

- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
[ADF-4927](https://issues.alfresco.com/jira/browse/ADF-4927)
**Does …
> [ADF-4927] Document List - focus indicator on cells is not clearly visible

- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4925
Process variables are not correctly mapped and as a …
> [ADF-4925] Fix Process Variable mapping in ADF forms

- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/components/widgets/date-time/date-time.widget.spec.ts
- lib/core/form/components/widgets/date-time/date-time.widget.ts
- lib/core/form/components/widgets/date/date.widget.spec.ts
- lib/core/form/components/widgets/date/date.widget.ts
- lib/process-services-cloud/src/lib/form/components/date-cloud/date-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/date-cloud/date-cloud.widget.ts
> - [x] Bugfix
These widgets were validation the value of a their fields several times every time the value was …
> [ADF-4861] Fix memory leak in Date widgets and Form Cloud Model

- lib/content-services/upload/components/file-uploading-dialog.component.html
- lib/content-services/upload/components/file-uploading-dialog.component.spec.ts
- lib/content-services/upload/components/file-uploading-dialog.component.ts
- lib/content-services/upload/upload.module.ts
> - [x] Bugfix
[ADF-4953](https://issues.alfresco.com/jira/browse/ADF-4953)
**Does …
> [ADF-4953] Uploader - confirmation dialog actions should return focus to the upload dialog

- lib/content-services/content-metadata/components/content-metadata/content-metadata.component.html
- lib/core/comments/comments.component.html
- lib/core/info-drawer/info-drawer.component.html
> - [x] Bugfix
[ADF-4955](https://issues.alfresco.com/jira/browse/ADF-4955)
**Does …
> [ADF-4955] Info Drawer - Visual heading text is not marked as a heading

- e2e/content-services/directives/create-folder-directive.e2e.ts
- lib/core/notifications/components/notification-history.component.ts
> - [ ] Bugfix
As a user, I want to be able to check the notification history after that I refresh the page.
**What …
> [ADF-4954] Notification history persist

- e2e/process-services-cloud/tasks-custom-filters.e2e.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4949
SUSPENDED filter has …
> [ADF-4949] Add SUSPENDED state to the edit task filter

- lib/core/layout/components/header/header.component.scss
> - [ ] Bugfix
[ADF-4956](https://issues.alfresco.com/jira/browse/ADF-4956)
Box when …
> [ADF-4956] Header - Focus indicator is not clearly visible

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/secure/RapidBoard.jspa?rapidView=715&projectKey=APM&view=detail&select …
> [ADF-4964] Add enter and escape events for updating card view properties

- lib/process-services/src/lib/process-list/components/process-list.component.ts
- lib/process-services/src/lib/task-list/components/task-list.component.ts
> - [x] Bugfix
1. Make sure you have some process instances running, that were just started moments ago
2. Log in to Process Workspace as the initiator of those processes
3. Select the related …
> [DW-1491] Process instance start date incorrectly displayed

- lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.html
- lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.spec.ts
> - [x] Bugfix
Upload and deploy the attached app
Create a new process
Navigate to active task
Select a radio button …
> [AAE-174]  Show radio box in text box when read only

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
- lib/content-services/src/lib/i18n/en.json
- lib/core/datatable/components/datatable/datatable.component.html
- lib/testing/src/lib/core/pages/data-table-component.page.ts
> - [ ] Bugfix
Check issue "Move or copy - column headers are not provided" …
> [ADF-4966] Keep table headers - visually hidden when showHeader false

- lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4968,
Assignee property of taskCloudHeader is not …
> [ADF-4968 ] [TaskHeaderCloudComponent] Allow Assignee property to be clickable if the task in CREATED, ASSIGNED, SUSPENDED states

- demo-shell/src/app/components/card-view/card-view.component.ts
- docs/core/components/card-view.component.md
- docs/process-services-cloud/components/task-header-cloud.component.md
- lib/core/card-view/card-view.module.scss
- lib/core/card-view/card-view.module.ts
- lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.html
- lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.scss
- lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.spec.ts
- lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.ts
- lib/core/card-view/components/card-view.components.ts
- lib/core/card-view/interfaces/card-view-arrayitem-properties.interface.ts
- lib/core/card-view/models/card-view-arrayitem.model.ts
- lib/core/card-view/public-api.ts
- lib/core/card-view/services/card-item-types.service.ts
- lib/core/i18n/en.json
- lib/core/pipes/full-name.pipe.spec.ts
- lib/core/pipes/full-name.pipe.ts
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [ ] Bugfix
1. TaskHeaderCloud component does not expose candidate users/groups that were added during modeling …
> [ADF- 4871][TaskHeaderCloudComponent] Add Candidate Users/Groups properties

- lib/core/datatable/components/datatable/datatable-row.component.spec.ts
- lib/core/datatable/components/datatable/datatable-row.component.ts
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.scss
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
[ADF-2990](https://issues.alfresco.com/jira/browse/ADF-2990)
**Does …
> [ADF-2990] Datatable - access header row via keyboard

- lib/core/services/auth-guard-base.ts
- lib/core/services/auth-guard-bpm.service.spec.ts
- lib/core/services/auth-guard-ecm.service.spec.ts
- lib/core/services/auth-guard.service.spec.ts
> - [x] Bugfix
The redirect URL can loop if you don't use the login component and you have silent login on
**What is …
> Should not redirect if is SilentLogin on

- demo-shell/src/app/components/app-layout/app-layout.component.html
- **Please check if the PR fulfills these requirements**
> - [ ] Bugfix
Aria-expanded wasn't calculate correct
Aria-expanded is calculate …
> [ADF-4973] CLONE - Header - sidenav menu button expanded/collapsed state not exposed via ARIA

- lib/testing/src/lib/core/utils/browser-actions.ts
> - [ ] Bugfix
When the click method fails, the message is not clear: 
`click error element [object Object]`
**What …
> make error message more clear

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/validators/card-view-item-float.validator.ts
- lib/core/card-view/validators/card-view-item-int.validator.ts
> - [x] Bugfix
Validator fails when removing value from int/float card view item. It's not possible to remove it = …
> [AAE-485] Fix card view int item validator when value is empty

- lib/core/datatable/data/data-row.model.ts
> - [ ] Bugfix
allow indexed access to the DataRow instances, for example `row['obj']` …
> allow indexed access for DataRow objects

- lib/content-services/src/lib/search/components/search-filter/search-filter.component.scss
- lib/core/styles/_index.scss
- lib/core/styles/_mixins.scss
> - [ ] Bugfix
> - [x] Other... Please describe: improve accessibility
Please check Jira issue https://issues.alfresco.com/jira/browse/ADF-4984
**What …
> [ADF-4984] Focus indicator is not clearly visible- mat-expansion-panel

- e2e/process-services-cloud/task-list-properties.e2e.ts
> - [x] Bugfix
- fix `standalone` spelling in the e2e selector
**Does this PR …
> fix 'standalone' spelling

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
Adina noticed a problem with that fix. We need to find another solution for that.
This reverts commit 0e2504a53fb0687cf179e45b3ca3642986957239.
> - [x] Bugfix
**What is the current behaviour?** …
> REVERT [ADF-4988] CLONE - Toolbar Actions and Navigation - Dialog is closed focus is not returned to trigger

- e2e/core/card-view/card-view-component.e2e.ts
- lib/core/card-view/models/card-view-datetimeitem.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-898
The datetime card view …
> [AAE-898] Fix Datetime card view model custom format

- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/upload/components/upload-button.component.spec.ts
- lib/content-services/src/lib/upload/components/upload-button.component.ts
- lib/core/form/components/widgets/upload/upload.widget.spec.ts
- lib/core/form/components/widgets/upload/upload.widget.ts
- package-lock.json
- package.json
> - [x] Bugfix
provide `null` value for UploadWidget to support APS 1.x scenarios
note …
> [AAE-207] support aps 1.x for upload reset

- e2e/process-services-cloud/start-process-cloud.e2e.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
- lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
- lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-459
**Does this PR …
> [AAE-459] ProcessCloud - set process definition pre-filled value for one result only

- lib/process-services/src/lib/attachment/process-attachment-list.component.ts
- lib/process-services/src/lib/attachment/task-attachment-list.component.spec.ts
- lib/process-services/src/lib/attachment/task-attachment-list.component.ts
> - [x] Bugfix
We should call getContentPreview that conatin inside also getRawContent as backup …
> [ADF-5027] Fix APS rendition

- demo-shell/src/app/components/files/files.component.html
- docs/core/components/data-column.component.md
- docs/core/interfaces/datatable-adapter.interface.md
- lib/core/data-column/data-column.component.ts
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/data/data-column.model.ts
- lib/core/datatable/data/object-datacolumn.model.ts
> - [x] Bugfix
[ADF-5006](https://issues.alfresco.com/jira/browse/ADF-5006)
**Does …
> [ADF-5006] Datatable - custom cell template focus not working

- lib/core/comments/comments.component.html
- lib/core/comments/comments.component.spec.ts
- lib/core/comments/comments.component.ts
> - [x] Bugfix
[ADF-5007](https://issues.alfresco.com/jira/browse/ADF-5007)
**Does …
> [ADF-5007] Comments - textarea Escape event cannot be canceled

- docs/process-services-cloud/components/group-cloud.component.md
- lib/core/mock/identity-group.service.mock.ts
- lib/core/mock/identity-user.service.mock.ts
- lib/core/models/identity-group.model.ts
- lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
- lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/group/pipe/group-initial.pipe.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5034
**Does this PR …
> [ADF-5034] [GroupCloudComponent] Provide a way to make pre-selected groups read-only.

- lib/cli/scripts/init-aae-env.ts
- lib/cli/scripts/kubectl-clean-app.ts
> - [ ] Bugfix
There is no way
`adf-cli kubectl-clean-app --apps "my-app-1,my-app-2"` …
> Ability to clean the env passing apps name

- demo-shell/src/app/components/process-service/process-attachments.component.html
- demo-shell/src/app/components/process-service/task-attachments.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5001
The triggered process displays the Process audit log …
> [ADF-5001] Process Audit File Log APS1 section wrong instruction for complete processes

- lib/core/services/auth-guard-base.ts
- lib/core/services/auth-guard-bpm.service.spec.ts
- lib/core/services/auth-guard-bpm.service.ts
- lib/core/services/auth-guard-ecm.service.spec.ts
- lib/core/services/auth-guard-ecm.service.ts
- lib/core/services/auth-guard-sso-role.service.spec.ts
- lib/core/services/auth-guard-sso-role.service.ts
- lib/core/services/auth-guard.service.ts
> - [x] Bugfix
All the open modal dialogs needs handling and closing when the user logs out. …
> [ADF-5009] close all the dialogs after false canActivate event

- lib/core/services/thumbnail.service.ts
- lib/core/viewer/components/viewer.component.ts
> - [ ] Bugfix
With this modify is possible to open with the viewer the media type MP3 …
> [ADF-5025] add mp3 support mediatype viewer/thumbnail blob

- lib/core/i18n/en.json
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.html
> - [x] Bugfix
For single & multiple files attached:
you can remove the files attached …
> [ADF-5060] fix readonly attach file scenarios

- lib/core/services/auth-guard.service.ts
> - [x] Bugfix
In the console log it appears often a message JWT must have 3 parts
JWT …
> JWT error fix

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
> - [X] Bugfix
when focus enters the date-picker input, the calendar pops up causing a major change in content. …
> [ACA-2609] removes calendar popup on focus

- demo-shell/src/app/components/form/form.component.html
- lib/core/form/components/widgets/amount/amount.widget.spec.ts
- lib/core/form/components/widgets/amount/amount.widget.ts
> - [ ] Bugfix
the Modeler application needs to display readonly amount widgets but with the placeholders,
right now, …
> [AAE-936] injecting external settings for amount widget

- lib/core/i18n/en.json
- lib/core/sorting-picker/sorting-picker.component.html
> - [x] Bugfix
Button does not have specific title to describe behavior when read aloud by Screen Reader
**What is …
> [ACA-2605] - fix: add aria-label to toggle button

- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/core/i18n/en.json
> - [X ] Tests for the changes have been added (for bug fixes / features)
> - [X ] Docs have been added / updated (for bug fixes / features)
Currently, the aria-sort is reading the behavior to screen readers after the fact (after a user …
> [ACA-2567] -  sortable

- lib/core/datatable/components/datatable/datatable.component.html
> - [ x] Tests for the changes have been added (for bug fixes / features)
> - [x ] Docs have been added / updated (for bug fixes / features)
Currently the icon is trying to read with Alt text behind the scenes, while having tabindex="0" so …
> [ACA-2561] Datatable- Hiding Decorative Icons in table

- e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.html
- lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
> - [x] Bugfix
[ADF-5064](https://issues.alfresco.com/jira/browse/ADF-5064)
**Does …
> [ADF-5064] Info Drawer - More and Less Information buttons are reversed

- lib/content-services/src/lib/upload/components/file-uploading-list-row.component.scss
> #1256 Fix Icon alignment mismatch and the rows to have the same height.

- e2e/pages/adf/demo-shell/process-services/formDemoPage.ts
- e2e/process-services-cloud/form-field/date-widget.e2e.ts
- e2e/process-services-cloud/form-field/people-group-of-people.e2e.ts
- e2e/process-services-cloud/form-field/visibility-condition-tabs.e2e.ts
- e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
- e2e/resources/forms/people-group-formwidget-mocks.ts
- lib/testing/src/lib/core/pages/config-editor-page.ts
- lib/testing/src/lib/core/pages/public-api.ts
- lib/testing/src/lib/process-services-cloud/pages/form-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/public-api.ts
…people/group cloud widgets
> - [ x] Tests for the changes have been added (for bug fixes / features)
> - [ ] Bugfix
> - [x ] Refactoring (no functional changes, no api changes)
added e2e tests for readOnly property used in people/group cloudForm …
> [AAE-1453] added e2e tests for readOnly property used in people/group cloudForm

- lib/core/i18n/en.json
- lib/core/sorting-picker/sorting-picker.component.html
> - [X] Bugfix
> - [X] Other... Please describe: accessibility
There is no persistent, visible label for the search sort dropdown …
> [ACA-2599] added always visible label to sort, i18n

- lib/core/form/components/widgets/checkbox/checkbox.widget.html
- lib/core/form/components/widgets/checkbox/checkbox.widget.spec.ts
- lib/core/form/components/widgets/form.scss
The checkbox and dropdown widgets don't turn red when the form isn't valid (when it is required and …
> [ADF-4920] Fixed checkbox dropdown style when invalid

- lib/core/datatable/components/datatable/datatable-row.component.ts
- lib/core/datatable/components/datatable/datatable.component.html
Selected state of items in datatable is not conveyed. And is currently reading blank SVG image. …
> [ACA-2602]- Datatable - Selected state properly announced

- lib/content-services/src/lib/mock/add-permission.component.mock.ts
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.spec.ts
> - [X ] Bugfix
When looking for users to add permissions on a file only the first name of the users is displayed. …
> [ADF-5072] Permission panel shows first and last name of users

- e2e/core/card-view/card-view-component.e2e.ts
- e2e/pages/adf/cardViewComponentPage.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1839
**Does this PR …
> [AAE-1839] Card View E2E

- e2e/process-services/process-filters-component.e2e.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5080
done
**Does this PR …
> [ADF-5080] Process List e2e

- lib/core/form/components/widgets/hyperlink/hyperlink.widget.spec.ts
> - [ ] Bugfix
Automation for hyperlink widget tests 
Not unit tests for sting label, url, and displayText for …
> [AAE-1942] Automation for hyperlink widget tests 

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.scss
- lib/process-services/src/lib/task-list/components/task-header.component.spec.ts
> - [ ] Bugfix
> - [ x] Feature
Use of ellipsis when the value is non-multiline and too long for display. 
Multiline items are also …
> [ADF-5074] Scrollable card-view-textitem when value too long for display

- lib/core/pagination/pagination.component.html
- lib/core/pagination/pagination.component.spec.ts
- lib/core/pagination/pagination.component.ts
This happens when a search query is executed against Solr and not the DB.
**What is the current behaviour?** 
Described in #5352 
If totalItems …
> [#5352] Fix broken pagination if totalItems is missing

- lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.html
- lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.spec.ts
> - [x] Bugfix
When on readOnly mode the radio-button-widget is displaying its "value" (which is by default the …
> [AAE-2034] Display disabled radio button in read-only mode

- lib/core/about/about-application-modules/about-application-modules.component.spec.ts
- lib/core/about/about-product-version/about-product-version.component.spec.ts
- lib/core/about/about.module.ts
- lib/core/datatable/datatable.module.ts
> - [ ] Bugfix
Add the missing `DataColumnModule` reference to the `DataTableModule`. …
> add missing DataColumn module to DataTable

- e2e/content-services/document-list/document-list-copy-move-actions.e2e.ts
- e2e/pages/adf/content-services.page.ts
- lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1881
The following tests …
> [AAE-1881] Add E2E tests for document list actions

- lib/content-services/src/lib/upload/components/file-uploading-dialog.component.ts
- lib/content-services/src/lib/upload/components/file-uploading-list.component.ts
- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1977
File is still uploaded after upload is cancelled. …
> [AAE-1977] Fix file uploaded after cancelling upload

- demo-shell/src/app/components/card-view/card-view.component.ts
- docs/core/services/card-view-update.service.md
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/core/card-view/components/base-card-view.ts
- lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.ts
- lib/core/card-view/components/card-view-boolitem/card-view-boolitem.component.spec.ts
- lib/core/card-view/components/card-view-boolitem/card-view-boolitem.component.ts
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
- lib/core/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.ts
- lib/core/card-view/components/card-view-mapitem/card-view-mapitem.component.ts
- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/card-view/services/card-view-update.service.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
- lib/process-services/src/lib/task-list/components/task-details.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4522
Metadata value is not rolling back on error
**What is …
> [ADF-4522] Metadata value is not rolled back upon error

- e2e/content-services/share-file/share-file.e2e.ts
- e2e/pages/adf/dialog/share-dialog.page.ts
- lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
- lib/content-services/src/lib/content-node-share/content-node-share.dialog.spec.ts
- lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
> - [ X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [X ] Bugfix
After switching on the expiration toggle, the calendar appears. This is not proper from an …
> [ACA-2619][ACA-2616] a11y fixes for Share Link dialog

- docs/content-services/services/custom-resources.service.md
- lib/content-services/src/lib/document-list/services/custom-resources.service.ts
- lib/content-services/src/lib/document-list/services/document-list.service.ts
> - [x] Bugfix
[ADF-5087](https://issues.alfresco.com/jira/browse/ADF-5087)
**Does …
> [ADF-5087] Document List - custom sources 'where' clause not passed

- lib/core/form/components/widgets/amount/amount.widget.scss
- lib/core/form/components/widgets/form.scss
- lib/core/styles/_index.scss
> - [x] Bugfix
Prefix is black when widget's input is not focused. (and orange otherwise) …
> [AAE-1579] Fixing the style of the prefix of amount widget

- lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.html
- lib/core/i18n/en.json
> - [x] Bugfix
Button label of "Edit" is not read on Screen Reader
Button is read as …
> [ACA-2789] - edit button a11y fixes

- demo-shell/src/app.config.json
- docs/content-services/components/content-metadata-card.component.md
- lib/content-services/src/lib/content-metadata/interfaces/layout-oriented-config.interface.ts
- lib/content-services/src/lib/content-metadata/interfaces/property.interface.ts
- lib/content-services/src/lib/content-metadata/services/config/aspect-oriented-config.service.spec.ts
- lib/content-services/src/lib/content-metadata/services/config/aspect-oriented-config.service.ts
- lib/content-services/src/lib/content-metadata/services/config/layout-oriented-config.service.spec.ts
- lib/content-services/src/lib/content-metadata/services/config/layout-oriented-config.service.ts
- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
- lib/core/app-config/schema.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4673
This PR brings the …
> [ADF-4673] Add editable property to metadata config

- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1725
**Does this PR …
> [AAE-1725] ADF Task/Process filters - default filters should be recreated when they all get deleted

- lib/core/card-view/components/card-view/card-view.component.scss
> - [ ] Bugfix
Color of card view labels is slightly too light (black with 0.4 opacity). …
> [ADF-5092] Change card view label color

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
> - [ ] Bugfix
Icon color has a too light color for AA accessibility.
Icon …
> [ADF-5096] Icon on move dialog darker

- lib/core/info-drawer/info-drawer-layout.component.scss
> - [ ] Bugfix
Color of info drawer's labels is primary.
Color of info …
> [ADF-5091] Change info drawer labels color

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.scss
- lib/content-services/src/lib/styles/_index.scss
> - [ ] Bugfix
Share dialog texts are too light for AA accesibility.
Share …
> [ADF-5095] Update text color of share dialog

- lib/core/info-drawer/info-drawer-layout.component.scss
> - [x] Bugfix
$accent variable not defined in info-drawer theme.
$accent is now …
> [ADF-5091] Fix undefined accent variable

- lib/content-services/src/lib/document-list/components/document-list.component.scss
> - [ ] Bugfix
Some texts in the empty folder element displayed in the document-list component when the …
> [ADF-5101] Change empty folder text display colors

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/core/datatable/components/datatable/datatable.component.scss
> - [x ] Tests for the changes have been added (for bug fixes / features)
> - [x ] Code style update (formatting, local variables)
When changing to a custom site in node-selector (custom site list) the breadcrumb would not update …
> [ADF-4264] Fixed the breadcrumb when changing to custom site in node selector

- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [ ] Bugfix
https://github.com/Alfresco/alfresco-ng2-components/issues/4422 …
> [ADF-5102] Added indeterminate state for 'select all' in datatable

- lib/content-services/src/lib/content-node-selector/name-location-cell/name-location-cell.component.scss
> - [ ] Bugfix
Color of location text is rgba(0,0,0,0.5) and have only 4:1 contrast ratio with the …
> [ADF-5104] Change color of location text

- lib/content-services/src/lib/upload/components/file-uploading-dialog.component.scss
> - [ ] Bugfix
When an upload has canceled the color of the button in the header is being disabled. That …
> [ADF-5105] Force color of header button of upload dialog

- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
- lib/extensions/src/lib/config/navbar.extensions.ts
- lib/extensions/src/lib/config/schema/plugin-extension.schema.json
> - [ ] Bugfix
There is no way to know if user is loggedin base on external provider …
> Ability to check if loggedIn based on provider

- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.html
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
- lib/process-services/src/lib/i18n/en.json
> - [x] Bugfix
The title of the attach file widget dialog is fixed on the login dialog title. …
> [AAE-2200] Add dynamic title to attach-file-widget-dialog

- lib/process-services/src/lib/process-list/components/start-process.component.html
- lib/process-services/src/lib/process-list/components/start-process.component.scss
- lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process.component.ts
- lib/process-services/src/lib/styles/_index.scss
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-2983
The labels from creating a new process (process name …
> [ACA-2983] Changed the labels from the inputs name and type to always floating

- lib/content-services/src/lib/dialogs/folder.dialog.scss
> - [ ] Bugfix
The color of the disabled button is rgba(0,0,0,0.26) which is too light for AA Accessibility …
> [ACA-2493] Fix disabled create folder button color

- lib/core/styles/_index.scss
- lib/core/styles/_mixins.scss
> - [ ] Bugfix
Some texts in the mat-calendar and mat-datetimepicker-calendar have a low contrast ratio with …
> [ACA-2476] Fix color contrast in mat-calendar and mat-datetimepicker-calendar

- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-dialog.component.scss
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.scss
> - [ ] Bugfix
Too light color for disabled buttons in dialog's actions for AA accessibility requirements. …
> [ADF-5114] Change dialog action button color

- lib/core/comments/comment-list.component.scss
> - [ ] Bugfix
Texts in the comment component lack color contrast.
The color …
> [ACA-2523] Change comment colors

- lib/core/info-drawer/info-drawer-layout.component.scss
> - [ ] Bugfix
Labels of tabs in info drawer have a default opacity of 0.6 which create ussies for AA …
> [ACA-2520] Opacity of tab label of info drawer set to 1

- lib/content-services/src/lib/breadcrumb/dropdown-breadcrumb.component.scss
> - [ ] Bugfix
The color of the current folder name in the breadcrumb-dropdown component has a low contrast …
> [ACA-2577] Change color of dropdown-breadcrumb current folder

- lib/core/login/components/login.component.scss
> - [ ] Bugfix
When logging in, the login button change colors and its new colors lack color contrast for AA …
> [ACA-2556] Change checking and welcome colors in login button

- lib/process-services/src/lib/i18n/en.json
- lib/process-services/src/lib/process-list/components/start-process.component.html
- lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2321
The start button for new process is enabled even …
> [AAE-2321] Should not be able to start a process with space as name (Process Services)

- lib/core/form/components/form-base.component.ts
- lib/process-services-cloud/src/lib/form/components/cloud-form-rendering.service.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/public-api.ts
- lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
- lib/process-services/src/lib/content-widget/attach-folder-widget.component.ts
- lib/process-services/src/lib/form/form.component.spec.ts
- lib/process-services/src/lib/form/form.component.ts
- lib/process-services/src/lib/form/process-form-rendering.service.ts
- lib/process-services/src/lib/form/public-api.ts
- lib/process-services/src/lib/form/start-form.component.ts
> - [ ] Bugfix
Form and FormCloud register custom widgets in the constructor, so prevent any customisations of the …
> [ADF-5106] allow to redefine form widgets (APS 1.x and cloud)

- lib/core/comments/comment-list.component.scss
> - [x] Bugfix
The previous update of comment colors isn't working the way I implemented it (using the mat-contrast …
> [ACA-2523] Fix text color of comment user icon

- lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
- lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.ts
- lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
- lib/process-services-cloud/src/lib/process/services/process-cloud.service.ts
- lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
- lib/process-services-cloud/src/lib/services/base-cloud.service.ts
- lib/process-services-cloud/src/lib/services/user-preference-cloud.service.ts
- lib/process-services-cloud/src/lib/task/services/start-task-cloud.service.ts
- lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5120
Cloud services set their context root in their …
> [ADF-5120] Fix initialization error of PS cloud Services

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2423
In process process-services-cloud we can have spaces …
> [AAE-2321] Should not be able to start a process with space(s) in the beginning/end of process name (Process Services Cloud)

- demo-shell/src/app/components/files/files.component.scss
- lib/content-services/src/lib/dialogs/node-lock.dialog.html
- lib/content-services/src/lib/document-list/components/document-list.component.scss
- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5129
https://issues.alfresco.com/jira/browse/ADF-5130 …
> [ADF-5129][ADF-5130] Fix Lock in Gallery view and Lock Dialog

- lib/core/form/components/widgets/checkbox/checkbox.widget.html
- lib/core/form/components/widgets/checkbox/checkbox.widget.spec.ts
- lib/core/form/components/widgets/checkbox/checkbox.widget.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2487
The checkbox widget was always showing as checked …
> [AAE-2487] Fix Checkbox Widget bug

- lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5134
Both components, People and group cloud components …
> [ADF-5134] REGRESSION - Fix People and Group Components firing twice
