.travis.yml, scripts/affected-libs.sh, scripts/smart-build.sh, scripts/update-version.sh
…ile to see the current dependencies
> - [ ] Bugfix …
=> Travis - Prints the dependencies inside the logs

demo-shell/src/tsconfig.app.json, demo-shell/src/tsconfig.dev.json, demo-shell/tsconfig.json, lib/extensions/index.ts, tsconfig.json
> - [x] Bugfix
fix the demo shell and extensions setup …
=> fix demo shell build

e2e/content-services/search/components/search-checkList.e2e.ts, e2e/pages/adf/content_services/search/components/search-checkList.ts, e2e/pages/adf/searchFiltersPage.ts
> - [ ] Bugfix
Automated tests for Check List search filter …
=> [ADF-3706] Creation of Check List filter automated tests

.travis.yml, e2e/pages/adf/navigationBarPage.ts, e2e/pages/adf/process_services_cloud/appListCloudComponent.ts, e2e/pages/adf/process_services_cloud/processServiceCloudPage.ts, e2e/process-services-cloud/apps_section_cloud.e2e.ts
=> [ADF-3755] Add e2e test for app list

demo-shell/src/tsconfig.dev.json, lib/core/login/components/login-dialog-panel.component.html, lib/core/login/components/login-dialog-panel.component.scss
> - [X] Bugfix
Login dialog shows the button and the copyright
The button and the …
=> [ADF-3604] fixed style for login dialog

lib/core/mock/jwt-helper.service.spec.ts, lib/core/userinfo/models/identity-user.model.ts, lib/core/userinfo/services/identity-user.service.spec.ts, lib/core/userinfo/services/identity-user.service.ts
> - [ ] Bugfix
Core module changes required for start-task-cloud PR …
=> [ADF-3540] Start Task Cloud by cli - Core module changes

angular.json, lib/config/create-coverage-index.sh, lib/config/proxy-coverage.json, lib/process-services/karma.conf.js, package.json
=> [ADF-2788] Fix the process service coverage path and config

angular.json, lib/content-services/karma.conf.js
=> [ADF-3789] Fix the content service coverage path and config

demo-shell/resources/i18n/en.json, demo-shell/src/app/app.routes.ts, demo-shell/src/app/components/app-layout/app-layout.component.ts, demo-shell/src/app/components/cloud/process-list-cloud-example.component.html, demo-shell/src/app/components/cloud/process-list-cloud-example.component.scss, demo-shell/src/app/components/cloud/process-list-cloud-example.component.ts, demo-shell/src/app/components/task-list-cloud-demo/task-list-cloud-demo.component.ts, docs/process-services-cloud/process-filter-cloud.component.md, lib/process-services-cloud/src/lib/i18n/en.json, lib/process-services-cloud/src/lib/i18n/it.json, lib/process-services-cloud/src/lib/process-cloud/models/process-filter-cloud.model.ts, lib/process-services-cloud/src/lib/process-cloud/process-cloud.module.ts, lib/process-services-cloud/src/lib/process-cloud/process-filters-cloud/process-filters-cloud.component.html, lib/process-services-cloud/src/lib/process-cloud/process-filters-cloud/process-filters-cloud.component.scss, lib/process-services-cloud/src/lib/process-cloud/process-filters-cloud/process-filters-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process-cloud/process-filters-cloud/process-filters-cloud.component.ts, lib/process-services-cloud/src/lib/process-cloud/public-api.ts, lib/process-services-cloud/src/lib/process-cloud/services/process-filter-cloud.service.ts, lib/process-services-cloud/src/lib/process-list-cloud/components/process-list-cloud.component.html, lib/process-services-cloud/src/lib/process-services-cloud.module.ts
> - [ ] Bugfix
Create new process filter APS2 https://issues.alfresco.com/jira/browse/ADF-3749 …
=> [ADF-3749] Process Filter Component - APS2

angular.json
=> [ADF-3781] Enable code coverage on process services cloud

e2e/content-services/search/components/search-slider.e2e.ts, e2e/pages/adf/content_services/search/components/search-slider.page.ts, e2e/pages/adf/searchFiltersPage.ts, e2e/pages/adf/searchResultsPage.ts, lib/content-services/search/components/search-slider/search-slider.component.html
> - [ ] Bugfix
Automation tests for Search Size Slider filter …
=> [ADF-3714] E2E for Search Slider Filter

docs/process-services-cloud/task-filters-cloud.component.md, lib/process-services-cloud/src/lib/task-cloud/task-filters-cloud/task-filters-cloud.component.ts
> - [ ] Bugfix
Doc text was basically fine already. Added property descriptions to the doc comments and rebuilt with one minor typo corrected.
> - [ ] Yes
> - [x] No
=> [ADF-3764] Reviewed task filters cloud docs

lib/core/services/search-configuration.service.ts
> - [X] Bugfix
putting special characters in the query search will lead to errors …
=> [ADF-3256] added quote to handle special characters for query search

package-lock.json, package.json
> - [x] Bugfix
nrwl library even if is only a development library ir contains inside the event-emitter library we …
=> [event-emitter] update nrwl library

demo-shell/src/app.config.json, demo-shell/src/app/components/process-service/process-service.component.html, demo-shell/src/app/components/process-service/process-service.component.ts, docs/process-services/start-task.component.md, e2e/pages/adf/process_services/dialog/startTaskDialog.js, lib/process-services/i18n/en.json, lib/process-services/task-list/components/start-task.component.html, lib/process-services/task-list/components/start-task.component.scss, lib/process-services/task-list/components/start-task.component.spec.ts, lib/process-services/task-list/components/start-task.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3282
Added max name length, …
=> [ADF-3282] Refactor Start Task Component

lib/process-services-cloud/src/lib/process-cloud/process-filters-cloud/process-filters-cloud.component.html
> - [x] Bugfix
* Selected filter is not highlighed
* Selected filter not highlighed …
=> [Bugfix] Selected process cloud filter is not highlighted

docs/process-services/apps-list.component.md, docs/process-services/attach-form.component.md, docs/process-services/checklist.component.md, docs/process-services/create-process-attachment.component.md, docs/process-services/create-task-attachment.component.md, docs/process-services/people-list.component.md, docs/process-services/people-search.component.md, docs/process-services/people.component.md, docs/process-services/process-attachment-list.component.md, docs/process-services/process-audit.directive.md, docs/process-services/process-comments.component.md, docs/process-services/process-filter.service.md, docs/process-services/process-filters.component.md, docs/process-services/process-instance-details.component.md, docs/process-services/process-instance-header.component.md, docs/process-services/process-instance-tasks.component.md, docs/process-services/process-list.component.md, docs/process-services/process.service.md, docs/process-services/select-apps-dialog.component.md, docs/process-services/start-process.component.md, docs/process-services/start-task.component.md, docs/process-services/task-attachment-list.component.md, docs/process-services/task-audit.directive.md, docs/process-services/task-details.component.md, docs/process-services/task-filter.service.md, docs/process-services/task-filters.component.md, docs/process-services/task-header.component.md, docs/process-services/task-list.component.md, docs/process-services/task-standalone.component.md, docs/process-services/tasklist.service.md
> - [ ] Bugfix
Added source links to process services docs.
> - [ ] Yes
> - [x] No
=> [ADF-3801] Added source links for process services docs

.travis.yml
…ev and is not a PR
> - [ ] Bugfix …
=> Travis - Force the execution of unit test and e2e test on dev branch

docs/core/infinite-pagination.component.md
=> Typo in infinite-pagination docs

docs/core/search.service.md, lib/core/services/search.service.ts
> - [ ] Bugfix
Added doc comments and rewrote text slightly for the Search service.
> - [ ] Yes
> - [x] No
=> [ADF-3806] Updated Search Service docs

lib/core/about/about.component.html, lib/core/i18n/en.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3777
About Component is not localized …
=> [ADF-3777] Add localization for About Component

e2e/content-services/comments/comment_component.e2e.ts
> - [ ] Bugfix
Automate test to check that user with consumer permissions can't add a comment to a file.
**What is …
=> [ADF-2661] Automation test for comments of consumer user

demo-shell/src/app/components/process-list-demo/process-list-demo.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3817
https://issues.alfresco.com/jira/browse/ADF-3818 …
=> [ADF-3817] Make AppId field not required and set minimum value to 0

e2e/pages/adf/dataTablePage.ts, e2e/pages/adf/searchFiltersPage.ts, e2e/search/search_component.e2e.ts
> - [ ] Bugfix
Automated test for search by '%' …
=> [ADF-3256] Automation test for search by '%'

e2e/actions/APS-cloud/identity.ts, e2e/core/user_info_component_cloud.e2e.ts, e2e/pages/adf/dialog/userInfoDialog.ts
=> [ADF-3666] User info sso e2e tests

angular.json, lib/core/karma.conf.js
=> [ADF-3790] Fix core coverage

demo-shell/src/app/components/app-layout/cloud/cloud-filters-demo.component.html, demo-shell/src/app/components/app-layout/cloud/cloud-filters-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.html, demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.ts, demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/services/cloud-layout.service.ts, demo-shell/src/app/components/app-layout/cloud/start-task-cloud-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.ts, docs/process-services-cloud/task-filters-cloud.component.md, lib/core/mock/jwt-helper.service.spec.ts, lib/core/userinfo/components/user-info.component.spec.ts, lib/core/userinfo/components/user-info.component.ts, lib/core/userinfo/services/identity-user.service.spec.ts, lib/core/userinfo/services/identity-user.service.ts, lib/process-services-cloud/src/lib/process-cloud/process-filters-cloud/edit-process-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process-cloud/process-filters-cloud/process-filters-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process-cloud/process-filters-cloud/process-filters-cloud.component.ts, lib/process-services-cloud/src/lib/process-cloud/services/process-filter-cloud.service.ts, lib/process-services-cloud/src/lib/start-task-cloud/components/people-cloud/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/start-task-cloud/components/start-task-cloud.component.spec.ts, lib/process-services-cloud/src/lib/start-task-cloud/components/start-task-cloud.component.ts, lib/process-services-cloud/src/lib/task-cloud/models/filter-cloud.model.ts, lib/process-services-cloud/src/lib/task-cloud/services/task-filter-cloud.service.ts, lib/process-services-cloud/src/lib/task-cloud/task-filters-cloud/edit-task-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task-cloud/task-filters-cloud/task-filters-cloud.component.html, lib/process-services-cloud/src/lib/task-cloud/task-filters-cloud/task-filters-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task-cloud/task-filters-cloud/task-filters-cloud.component.ts
=> Fix process cloud page

demo-shell/src/app/components/app-layout/cloud/cloud-filters-demo.component.html, e2e/actions/APS-cloud/process-definitions.ts, e2e/actions/APS-cloud/process-instances.ts, e2e/actions/APS-cloud/query.ts, e2e/pages/adf/dataTablePage.ts, e2e/pages/adf/demo-shell/processCloudDemoPage.ts, e2e/pages/adf/navigationBarPage.ts, e2e/pages/adf/process_cloud/processFiltersCloudComponent.ts, e2e/pages/adf/process_cloud/processListCloudComponent.ts, e2e/process-services-cloud/process_filters_cloud.e2e.ts, e2e/process-services-cloud/task_filters_cloud.e2e.ts
=> [ADF-3807]Create automated tests for process filters

lib/content-services/document-list/components/document-list.component.ts
=> let maxItems only if !this._pagination

lib/extensions/src/lib/components/dynamic-component/dynamic.component.spec.ts, lib/extensions/src/lib/components/dynamic-component/dynamic.component.ts, lib/extensions/src/lib/services/component-register.service.ts, lib/extensions/src/lib/services/extension.service.spec.ts, lib/extensions/src/lib/services/extension.service.ts, lib/extensions/src/public_api.ts
> - [ ] Bugfix
We lack the ability to pass through data for dynamically loaded components in the adf-extensions …
=> [APM-419] Adding data input to dynamic component

lib/content-services/content-node-selector/content-node-selector-panel.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3811
Node icon and …
=> [ADF-3811] Node icon and name-location aren't properly aligned

e2e/pages/adf/dataTablePage.ts, e2e/pages/adf/demo-shell/processCloudDemoPage.ts, e2e/pages/adf/demo-shell/taskListDemoPage.ts, e2e/pages/adf/process_cloud/editProcessFilterCloudComponent.ts, e2e/pages/adf/process_cloud/processListCloudComponent.ts, e2e/process-services-cloud/process_custom_filters.e2e.ts, lib/process-services-cloud/src/lib/process-cloud/process-filters-cloud/edit-process-filter-cloud.component.html
=> [ADF-3774]Add process custom filter tests

e2e/pages/adf/process_services/dialog/startTaskDialog.ts, e2e/pages/adf/process_services/startProcessPage.ts, e2e/process-services/start_process_component.e2e.ts, e2e/process-services/start_task_task_app.e2e.ts
=> [ADF-3282] Add tests for length validation process/task name

lib/content-services/dialogs/library/library.dialog.spec.ts, lib/content-services/dialogs/library/library.dialog.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3851
**Does this PR …
=> [ADF-3851] Create Library - title case insensitive check

docs/README.md, docs/extensions/README.md, docs/extensions/dynamic-tab.component.md, docs/extensions/dynamic.component.md, docs/extensions/extension.service.md, docs/user-guide/README.md, docs/user-guide/app-extensions.md, lib/extensions/src/lib/components/dynamic-component/dynamic.component.ts, lib/extensions/src/lib/components/dynamic-tab/dynamic-tab.component.ts, lib/extensions/src/lib/services/extension.service.ts, tools/doc/doctool.config.json, tools/doc/tools/typeLinker.js, tools/doc/tools/typeLinker.ts
> - [ ] Bugfix
Added component pages and user guide page about extensions. I've tried to keep the docs general rather than referring to the Content App implementation. All feedback is welcome but there are a few points to draw your …
=> [ADF- 3846] Started Extensions library docs

demo-shell/resources/i18n/en.json, demo-shell/src/app/components/about/about.component.html, lib/core/about/about.component.html, lib/core/about/about.component.ts, lib/core/i18n/en.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3777
The About Component on Demo Shell was not localized. …
=> [ADF-3777] Add localization to About Page on Demo Shell

.vscode/settings.json, demo-shell/src/app/components/files/files.component.html, demo-shell/src/app/components/files/files.component.ts, docs/content-services/document-list.component.md, lib/content-services/dialogs/library/library.dialog.ts, lib/content-services/document-list/components/library-name-column/library-name-column.component.spec.ts, lib/content-services/document-list/components/library-name-column/library-name-column.component.ts, lib/content-services/document-list/components/library-role-column/library-role-column.component.spec.ts, lib/content-services/document-list/components/library-role-column/library-role-column.component.ts, lib/content-services/document-list/components/library-status-column/library-status-column.component.spec.ts, lib/content-services/document-list/components/library-status-column/library-status-column.component.ts, lib/content-services/document-list/components/name-column/name-column.component.spec.ts, lib/content-services/document-list/components/name-column/name-column.component.ts, lib/content-services/document-list/components/trashcan-name-column/trashcan-name-column.component.spec.ts, lib/content-services/document-list/components/trashcan-name-column/trashcan-name-column.component.ts, lib/content-services/document-list/document-list.module.ts, lib/content-services/i18n/de.json, lib/content-services/i18n/en.json, lib/content-services/i18n/es.json, lib/content-services/i18n/fr.json, lib/content-services/i18n/it.json, lib/content-services/i18n/ja.json, lib/content-services/i18n/nb.json, lib/content-services/i18n/nl.json, lib/content-services/i18n/pt-BR.json, lib/content-services/i18n/ru.json, lib/content-services/i18n/zh-CN.json, lib/core/datatable/components/datatable/datatable.component.scss, lib/extensions/src/lib/components/dynamic-column/dynamic-column.component.ts, lib/extensions/src/lib/extensions.module.ts
> - [ ] Bugfix
Extensibility related components ported from ACA:
- extensions: dynamic …
=> [ADF-3869] extensibility related components

lib/process-services-cloud/src/lib/app/public-api.ts
> - [x] Bugfix
the service is not exported
the service is exported
**Does this PR …
=> ADF process cloud - export app list cloud service

docs/content-services/document-list.component.md
> - [ ] Bugfix
Extend documentation for the migrated components.
@therealandeeee the …
=> [ADF-3869] update documentation

demo-shell/src/app/app.module.ts, demo-shell/src/app/app.routes.ts, demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.html, demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.ts, demo-shell/src/app/components/app-layout/cloud/start-process-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/start-process-cloud-demo.component.ts, docs/process-services-cloud/start-process-cloud.component.md, e2e/pages/adf/demo-shell/processCloudDemoPage.ts, e2e/pages/adf/material/datePickerPage.ts, e2e/search/components/search-date-range.e2e.ts, lib/process-services-cloud/src/lib/i18n/en.json, lib/process-services-cloud/src/lib/process-services-cloud.module.ts, lib/process-services-cloud/src/lib/process/process-cloud.module.ts, lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.html, lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.scss, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts, lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts, lib/process-services-cloud/src/lib/process/start-process/models/process-definition-cloud.model.ts, lib/process-services-cloud/src/lib/process/start-process/models/process-instance-cloud.model.ts, lib/process-services-cloud/src/lib/process/start-process/models/process-payload-cloud.model.ts, lib/process-services-cloud/src/lib/process/start-process/public-api.ts, lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts, lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts, lib/process-services-cloud/src/lib/process/start-process/start-process-cloud.module.spec.ts, lib/process-services-cloud/src/lib/process/start-process/start-process-cloud.module.ts, lib/process-services/process-list/components/process-filters.component.html, lib/process-services/task-list/components/task-filters.component.html
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3543
New Start Process …
=> [ADF-3543] Start Process Component for APS 2

docs/README.md, docs/process-services-cloud/README.md, docs/process-services-cloud/app-list-cloud.component.md, docs/process-services-cloud/edit-process-filter-cloud.component.md, docs/process-services-cloud/edit-task-filter-cloud.component.md, docs/process-services-cloud/process-filters-cloud.component.md, docs/process-services-cloud/process-list-cloud.component.md, docs/process-services-cloud/start-process-cloud.component.md, docs/process-services-cloud/start-task-cloud.component.md, docs/process-services-cloud/task-filters-cloud.component.md, docs/process-services-cloud/task-list-cloud.component.md, lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
> - [ ] Bugfix
Reviewed latest changes to process services cloud docs (text + doc comments, etc).
> - [ ] Yes
> - [x] No
=> [ADF-3745] Reviewed latest proc services cloud docs

.travis.yml, e2e/actions/APS-cloud/apiservice.ts, e2e/actions/APS-cloud/identity.ts, e2e/core/login/login-sso/login-sso.e2e.ts, e2e/core/user-info-component-cloud.e2e.ts, e2e/pages/adf/loginSSOPage.ts, e2e/process-services-cloud/apps-section-cloud.e2e.ts, e2e/process-services-cloud/process-custom-filters.e2e.ts, e2e/process-services-cloud/process-filters-cloud.e2e.ts, e2e/process-services-cloud/task-filters-cloud.e2e.ts, e2e/test.config.js, lib/core/userinfo/services/identity-user.service.ts, scripts/test-e2e-lib.sh
=> [ADF-3885]Change auth host path in cloud e2e tests

lib/content-services/package.json, lib/core/package.json, lib/extensions/package.json, lib/insights/package.json, lib/process-services-cloud/package.json, lib/process-services/package.json, lib/tsconfig.json, scripts/update-version.sh
=> Bamboo fails - Remove the the old js-api reference of and use the @alfresco's one

e2e/content-services/document-list/document-list-component.e2e.ts, e2e/pages/adf/contentServicesPage.ts, e2e/pages/adf/viewerPage.ts
> - [ ] Bugfix
Automation test for hyperlink navigation …
=> [ADF-3886] Automation test for hyperlink navigation

docs/README.md, docs/content-services/document-actions.service.md, docs/content-services/search-query-builder.service.md, docs/core/content.widget.md, docs/core/icon.component.md, docs/core/translation.service.md, docs/process-services/process.service.md, docs/process-services/start-task.component.md, lib/content-services/document-list/services/custom-resources.service.ts, lib/content-services/document-list/services/document-actions.service.ts, lib/content-services/search/search-query-builder.service.ts, lib/core/form/components/widgets/content/content.widget.ts, lib/core/icon/icon.component.ts, lib/core/services/translation.service.ts, lib/process-services/process-list/services/process.service.ts, lib/process-services/task-list/components/start-task.component.ts, package.json, tools/doc/doctool.config.json
> - [ ] Bugfix
Updated missing/incorrect properties and doc comments. Also tidied up the index page.
> - [ ] Yes
> - [x] No
=> [ADF-3745] Updated properties and doc comments

docs/process-services/apps-list.component.md
> - [ ] Bugfix
Fixed incorrect code sample (it had extra quote characters that produced an error).
> - [ ] Yes
> - [x] No
=> [ADF-3898] Fixed incorrect code sample

demo-shell/resources/i18n/en.json, demo-shell/src/app/app.routes.ts, demo-shell/src/app/components/app-layout/app-layout.component.ts, demo-shell/src/app/components/task-list-cloud/task-list-cloud-demo.component.html, demo-shell/src/app/components/task-list-cloud/task-list-cloud-demo.component.scss, demo-shell/src/app/components/task-list-cloud/task-list-cloud-demo.component.ts, demo-shell/src/app/components/task-list-cloud/task-list-cloud.module.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3783
A new page has been …
=> [ADF-3783] Create Task List Cloud Demo page

docs/process-services-cloud/people-cloud.component.md, e2e/actions/APS-cloud/identity.ts, lib/core/userinfo/services/identity-user.service.spec.ts, lib/core/userinfo/services/identity-user.service.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.html, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.html, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3812
* Added mullti …
=> [ADF-3812] Add multi selection and roles filtering to adf-cloud-people component	

docs/core/login.component.md
=> [ADF-3906] extend SSO docs

docs/README.md, docs/process-services-cloud/README.md, docs/process-services-cloud/app-list-cloud.component.md, docs/process-services-cloud/edit-process-filter-cloud.component.md, docs/process-services-cloud/edit-task-filter-cloud.component.md, docs/process-services-cloud/process-filter-cloud.service.md, docs/process-services-cloud/process-filters-cloud.component.md, docs/process-services-cloud/process-list-cloud.component.md, docs/process-services-cloud/start-process-cloud.component.md, docs/process-services-cloud/start-process-cloud.service.md, docs/process-services-cloud/start-task-cloud.component.md, docs/process-services-cloud/start-task-cloud.service.md, docs/process-services-cloud/task-filter-cloud.service.md, docs/process-services-cloud/task-filters-cloud.component.md, docs/process-services-cloud/task-list-cloud.component.md
> - [ ] Bugfix
Added experimental status to proc services cloud docs as requested in the JIRA case.
> - [ ] Yes
> - [x] No
=> [ADF-3902] Added experimental status to proc services cloud docs

docs/process-services-cloud/group-cloud.component.md, lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
> - [ ] Bugfix
Reviewed Group cloud component page and doc comments.
> - [ ] Yes
> - [x] No
=> [ADF-3745] Reviewed new Group cloud component docs

docs/process-services/people.component.md, docs/release-notes/RelNote161.md, docs/release-notes/RelNote170.md, docs/release-notes/RelNote180.md, docs/release-notes/RelNote190.md, docs/release-notes/RelNote200.md, docs/release-notes/RelNote210.md, docs/release-notes/RelNote220.md, docs/release-notes/RelNote230.md, docs/release-notes/RelNote240.md, docs/release-notes/RelNote250.md, docs/release-notes/RelNote260.md
Reverts Alfresco/alfresco-ng2-components#4159
=> Revert "[ADF-3911] Converted GIF image URLs to absolute"

lib/content-services/i18n/en.json, lib/content-services/upload/components/file-uploading-dialog.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3905
**Does this PR …
=> [ADF-3905]Upload Dialog - counter displays "Uploading 0 / 1"

e2e/core/icons-component.e2e.ts, e2e/pages/adf/iconsPage.ts, e2e/pages/adf/navigationBarPage.ts
=> [ADF-3900] Implement tests for Universal Icons component

.travis.yml, demo-shell/src/app/components/app-layout/cloud/apps-cloud-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/cloud-filters-demo.component.html, demo-shell/src/app/components/app-layout/cloud/cloud-filters-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/services/cloud-layout.service.ts, demo-shell/src/app/components/app-layout/cloud/start-process-cloud-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/start-task-cloud-demo.component.ts
> - [x] Bugfix
* The first filter from the task list is not selected as default. 
* User is redirected to 'My task' …
=> [ADF-3877][Task Filters cloud] - APS2 - The first filter from the list is not selected as default after reloading the same app

lib/core/datatable/components/datatable/datatable.component.html, lib/core/datatable/components/datatable/datatable.component.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3860
**Does this PR …
=> [ADF-3860] - Document List - change datatable to be recognized as a table

docs/README.md, docs/abn-tree.yml, docs/roadmap.md
> - [ ] Bugfix
Added roadmap page.
@fcorti The content is slightly different to what you specified. I think it should still be OK but let me know if I have "broken" anything critical. …
=> [ADF-3913] Added roadmap page

lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
> - [x] Bugfix
* Unable to start process as the API is invoked without payload
* Able …
=> [ADF-3909] [Start Process cloud] Can't start a process

docs/content-services/content-node-selector.component.md, docs/content-services/document-list.component.md, docs/content-services/document-list.service.md, docs/content-services/file-uploading-dialog.component.md, docs/content-services/search-control.component.md, docs/content-services/search-filter.component.md, docs/content-services/search-filter.service.md, docs/content-services/search-widget.interface.md, docs/content-services/search.component.md, docs/content-services/upload-button.component.md, docs/content-services/upload-drag-area.component.md, docs/content-services/version-list.component.md, tools/doc/yamlTemplates/template.ejs
> - [ ] Bugfix
Reviewed docs where deprecated items were removed, with mainly minor changes. Also fixed an issue with the source paths passed to the type linker tool from Typedoc. …
=> [ADF-3921] Reviewed docs where deprecated content was removed

docs/core/form.component.md, docs/core/host-settings.component.md, docs/core/infinite-pagination.component.md, docs/core/login.component.md, docs/core/node-restore.directive.md, docs/core/upload.service.md, docs/core/user-preferences.service.md, docs/core/viewer.component.md, docs/process-services/process-list.component.md
> - [ ] Bugfix
Reviewed docs where deprecated items were removed. Only minor changes but still awaiting decision on the renditions service and the data property of tasklist component. …
=> [ADF-3921] Reviewed docs where deprecated stuff was removed

e2e/content-services/document-list/document-list-component.e2e.ts, e2e/pages/adf/contentServicesPage.ts, e2e/pages/adf/dataTablePage.ts, e2e/pages/adf/dialog/contentListPage.ts
> - [ ] Bugfix
Adding some changes requested by Cristina after the branch was merged. …
=> [ADF-3886] Adding small changes

lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.html, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.scss
> - [x] Bugfix
* The Date validation message is not properly aligned
* The Date …
=> [ADF-3827] [Start task] - layout issue - the validation for date field not properly aligned

docs/README.md, docs/content-services/README.md, docs/content-services/file-upload-error.pipe.md, docs/content-services/file-uploading-dialog.component.md, docs/content-services/upload-button.component.md, docs/content-services/upload-drag-area.component.md, docs/process-services-cloud/README.md, docs/process-services-cloud/group-initial.pipe.md, tools/doc/doctool.config.json
> - [ ] Bugfix
Added docs for the new pipes.
> - [ ] Yes
> - [x] No
=> [ADF-3745] Added docs for the new pipes

docs/versionIndex.md
> - [ ] Bugfix
First draft of the version index for 3.0, which includes a retired components section now. Any ideas and suggestions about the format are more than welcome. …
=> [ADF-3745] Built initial version index for 3.0

docs/process-services-cloud/start-process-cloud.component.md, lib/process-services-cloud/src/lib/i18n/en.json, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3889
**Does this PR …
=> [ADF-3889] [Start Process Cloud] - APS2 - error displayed when try to  create a process with a name bigger the 255 characters

lib/core/directives/node-favorite.directive.ts
> - [x] Bugfix
this is a hotfix for the regression caused by missing 'nodeId' property …
=> favorites and shared links hotfix

lib/core/settings/host-settings.component.html, lib/core/settings/host-settings.component.spec.ts, lib/core/settings/host-settings.component.ts
> - [x] Bugfix
* https://issues.alfresco.com/jira/browse/ADF-3941
* IdentityHost is …
=> [ADF-3941] Settings Page - SSO -> Identity Host is not visible when open the page for the first time

e2e/content-services/lock-file.e2e.ts, e2e/content-services/share-file/share-file.e2e.ts, e2e/content-services/share-file/unshare-file.e2e.ts, e2e/core/user-info-component.e2e.ts, e2e/core/viewer/viewer-component.e2e.ts, e2e/pages/adf/contentServicesPage.ts, e2e/pages/adf/dialog/contentListPage.ts
=> [ADF-3931]Fix share and lock files automated tests

lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.html, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.ts
> - [x] Bugfix
There is no way to start a task without assignee
it is possible to …
=> [ADF-3826] StartTask without assignee

docs/process-services-cloud/process-list-cloud.component.md, lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts, lib/process-services-cloud/src/lib/process/process-list/mock/process-list-service.mock.ts, lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts, lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts, lib/process-services-cloud/src/lib/process/start-process/models/process-definition-cloud.model.ts, lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts, lib/process-services-cloud/src/lib/task/task-header/mocks/fake-task-details-response.mock.ts, lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-list/mock/fakeTaskResponseMock.ts, lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3837
**Does this PR …
=> [ADF-3837] - Removed unused service properties

docs/process-services-cloud/group-cloud.component.md, lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts, lib/process-services-cloud/src/lib/group/group-cloud.module.ts, lib/process-services-cloud/src/lib/process-services-cloud.module.ts, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.html, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.ts, lib/process-services-cloud/src/lib/task/start-task/models/start-task-cloud-request.model.ts, lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts, lib/process-services-cloud/src/lib/task/start-task/start-task-cloud.module.ts, lib/process-services-cloud/src/public-api.ts
> - [ ] Bugfix
There is no way to specify the candidateGroup for a task
There is a way …
=> [ADF-3946] Add the GroupCloudComponent to the StartTaskCloudComponent

e2e/pages/adf/demo-shell/process-services/processCloudDemoPage.ts, e2e/pages/adf/loginSSOPage.ts, e2e/pages/adf/process-services/startProcessPage.ts, e2e/process-services-cloud/start-process-cloud.e2e.ts
=> [ADF-3884] Added start process e2e tests

lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3939
https://issues.alfresco.com/jira/browse/ADF-3940 …
=> [ADF-3940] Fix Parent Name property in Task Header Cloud component

e2e/content-services/upload/uploader-component.e2e.ts
=> [ADF-3905] - Upload counter displays "Uploading 0 / 1"

docs/process-services-cloud/process-list-cloud.component.md, docs/process-services-cloud/task-list-cloud.component.md, lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3830
LandingTaskId and …
=> [ADF-3830] Remove landingTaskId and selectRowFirst properties

demo-shell/resources/i18n/en.json, demo-shell/src/app.config.json, demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.html, demo-shell/src/app/components/config-editor/config-editor.component.html, demo-shell/src/app/components/config-editor/config-editor.component.ts, docs/process-services-cloud/edit-task-filter-cloud.component.md, lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
… add live configuration for Task List Cloud Component
> - [x] Bugfix …
=> [ADF-3943] Remove non-working filters from Edit Task Filter Cloud

e2e/actions/APS-cloud/tasks.ts, e2e/pages/adf/process-cloud/taskDetailsCloudComponent.ts, e2e/process-services-cloud/task-details-cloud.e2e.ts
=> [ADF-3933]Implement automated tests for task header component

e2e/content-services/upload/uploader-component.e2e.ts, e2e/content-services/upload/user-permission.e2e.ts, e2e/pages/adf/contentServicesPage.ts, e2e/pages/adf/dialog/uploadDialog.ts
=> [ADF-3951] Added automated tests for failed uploading tooltips

lib/process-services-cloud/src/lib/group/components/group-cloud.component.scss, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.scss, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3956
* Start task cloud fields are not aligned.
**What is …
=> [ADF-3956] [Start Task Cloud] - Fields are not properly aligned

demo-shell/src/app.config.json, demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.ts, demo-shell/src/app/components/config-editor/config-editor.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3975
**Does this PR …
=> [ADF-3975] Fix TASK_FILTER_PROPERTY_KEYS Property in Tasks Cloud Demo component

demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.html
=> Fix the tasklist and processlist demoshell

e2e/core/settings-component.e2e.ts, e2e/pages/adf/loginPage.ts, e2e/pages/adf/navigationBarPage.ts, e2e/pages/adf/settingsPage.ts
=> [ADF-3967] Automate Settings Component

e2e/core/viewer/viewer-content-services-component.e2e.ts, e2e/pages/adf/viewerPage.ts
=> [ADF-3810] Should rearrange toolbar actions in Viewer

docs/process-services-cloud/edit-process-filter-cloud.component.md, lib/core/services/login-dialog.service.ts, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> - [ ] Bugfix
Updated a couple of remaining doc comments before code freeze.
> - [ ] Yes
> - [x] No
=> [ADF-3745] Updated doc comments

e2e/pages/adf/dialog/searchDialog.ts, lib/content-services/search/components/search-control.component.scss, lib/content-services/search/components/search-control.component.ts
> - [ ] Bugfix
Style
remove annoying dot at the end of search animation
**Does this PR …
=> [no-issue] remove annoying dot at the end of search animation

e2e/content-services/trashcan-pagination.e2e.ts, e2e/content-services/upload/excluded-file.e2e.ts, e2e/content-services/upload/uploader-component.e2e.ts, e2e/content-services/upload/user-permission.e2e.ts, e2e/pages/adf/dialog/uploadDialog.ts, e2e/pages/adf/material/formControllersPage.ts
=> [ADF-3959] Fixing trashcan-pagination tests

demo-shell/src/app.config.json, demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html, demo-shell/src/app/components/config-editor/config-editor.component.html, demo-shell/src/app/components/config-editor/config-editor.component.ts, lib/process-services-cloud/src/lib/i18n/en.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3872
Add the possibility in configuration editor to change …
=> [ADF-3872] Add live configuration for Process List Cloud on Demo Shell

docs/process-services-cloud/task-list-cloud.component.md, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3982
**Does this PR …
=> [ADF-3982] TaskListCloudComponent - Be able to filter tasks with all possible params

lib/core/layout/components/header/header.component.scss, lib/core/toolbar/toolbar-divider.component.ts
> - [x] Bugfix
Style fixes:
- alignment of the Logo
- divider styles
- various style …
=> header style fixes

e2e/pages/adf/dataTablePage.ts, e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts, e2e/pages/adf/dialog/editTaskFilterDialog.ts, e2e/pages/adf/process-cloud/editTaskFilterCloudComponent.ts, e2e/pages/adf/process_cloud/editTaskFilterCloudComponent.ts, e2e/process-services-cloud/edit-task-filters-component.e2e.ts, e2e/process-services-cloud/edit_task_filters_component.e2e.ts
=> [ADF-3848]Implement edit task filters tests

demo-shell/src/app/components/breadcrumb-demo/breadcrumb-demo.component.html, demo-shell/src/app/components/files/files.component.html, demo-shell/src/app/components/files/files.component.ts, docs/content-services/breadcrumb.component.md, lib/content-services/breadcrumb/breadcrumb.component.spec.ts, lib/content-services/breadcrumb/breadcrumb.component.ts, lib/content-services/breadcrumb/dropdown-breadcrumb.component.scss, lib/content-services/breadcrumb/dropdown-breadcrumb.component.spec.ts, lib/content-services/breadcrumb/dropdown-breadcrumb.component.ts, lib/content-services/breadcrumb/navigable-component.interface.ts, lib/content-services/content-node-selector/content-node-dialog.service.ts, lib/content-services/content-node-selector/content-node-selector-panel.component.html, lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts, lib/content-services/content-node-selector/content-node-selector-panel.component.ts, lib/content-services/document-list/components/document-list.component.spec.ts, lib/content-services/document-list/components/document-list.component.ts, lib/content-services/document-list/data/share-datatable-adapter.ts, lib/content-services/mock/document-list.component.mock.ts, lib/core/datatable/components/datatable/datatable.component.scss, lib/core/directives/highlight.directive.ts, lib/core/pagination/infinite-pagination.component.spec.ts, lib/core/pagination/infinite-pagination.component.ts, lib/core/services/highlight-transform.service.ts, package-lock.json, package.json
> - [x] Bugfix
Steps to reproduce the issue:
Navigate to DocumentList
Copy/Move a file
In the dialog, search for "*" …
=> [ADF-3930] Can't load more results in Copy/Move dialog

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts, lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts, lib/process-services-cloud/src/lib/process/start-process/models/process-payload-cloud.model.ts
=> [ADF-4001] StartProcessCloud - Fix payload with name

docs/tutorials/creating-the-app-using-yeoman.md
=> Made 3 minor typo changes in the section called "Using the application"

e2e/core/card-view/metadata-smoke-tests.e2e.ts, e2e/pages/adf/metadataViewPage.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3998
**Does this PR …
=> [ADF-3998] Fixing failing tests in metadata-smoke-tests

lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
> - [x] Bugfix
The applist is not clean after the appName change
The applist is clean …
=> [ADF-3988] Process Cloud - Reset the appList before calling the API

demo-shell/src/app.config.json
=> [ADF-3990]Make demo-shell use default edit process filters.

docs/core/empty-content.component.md
> - [ ] Bugfix
Replaced code samples in Empty content component docs with current best practice.
> - [ ] Yes
> - [x] No
=> [ADF-3745] Updated code samples for empty content component

lib/core/userinfo/services/identity-user.service.spec.ts, lib/core/userinfo/services/identity-user.service.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4003
**Does this PR …
=> [ADF-4003] Add roles filtering to PeopleCloudComponent

demo-shell/src/app/app.routes.ts, lib/content-services/breadcrumb/dropdown-breadcrumb.component.scss, lib/core/datatable/components/datatable/datatable.component.html, lib/core/datatable/components/datatable/datatable.component.scss, lib/core/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4017
Fix datatable layout. …
=> [ADF-4017] Fix several styling bugs

e2e/core/icons-component.e2e.ts, e2e/core/login/login-sso/login-sso.e2e.ts, e2e/core/user-info-component-cloud.e2e.ts, e2e/pages/adf/dataTablePage.ts, e2e/pages/adf/process-cloud/editTaskFilterCloudComponent.ts, e2e/pages/adf/process-cloud/startTasksCloudComponent.ts, e2e/pages/adf/settingsPage.ts, e2e/process-services-cloud/apps-section-cloud.e2e.ts, e2e/process-services-cloud/edit-task-filters-component.e2e.ts, e2e/process-services-cloud/process-custom-filters.e2e.ts, e2e/process-services-cloud/process-filters-cloud.e2e.ts, e2e/process-services-cloud/start-process-cloud.e2e.ts, e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts, e2e/process-services-cloud/task-details-cloud.e2e.ts, e2e/process-services-cloud/task-filters-cloud.e2e.ts, e2e/process-services-cloud/tasks-custom-filters.e2e.ts
=> [ADF-3828] - e2e add assignee tests

demo-shell/resources/i18n/en.json, demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.scss, demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4009
**Does this PR …
=> [ADF-4009] - People/GroupComponentDemoPage - add role input filter

lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
> - [x] Bugfix
owner is not part of the model
add owner as property
**Does this PR …
=> [ADF-4019] TaskListModel - Add owner as property

docs/process-services-cloud/edit-process-filter-cloud.component.md, docs/process-services-cloud/edit-task-filter-cloud.component.md, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
=> EditTaskCloud EditProcessCloud - Align the docs

lib/content-services/content-node-selector/content-node-selector-panel.component.html, lib/content-services/content-node-selector/content-node-selector-panel.component.ts, lib/content-services/document-list/components/document-list.component.spec.ts, lib/content-services/document-list/components/document-list.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4027 …
=> [ADF-4027] fix navigation to custom sources

lib/content-services/document-list/components/document-list.component.spec.ts, lib/core/pagination/infinite-pagination.component.spec.ts, lib/core/pagination/infinite-pagination.component.ts
=> fix infinite pagination test

lib/process-services-cloud/package.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4044
The Process Service Cloud dependencies were outdated. …
=> [ADF-4044] Update Process Services Cloud dependencies

.travis.yml, demo-shell/src/app/components/header-data/header-data.component.html, package-lock.json, package.json, scripts/license-list-generator.sh
> - [ ] Bugfix
Add license check to avoid some licenses and tool to create list
**Does …
=> add license 3th party generator/checker

lib/content-services/content-node-selector/content-node-selector-panel.component.ts, lib/content-services/document-list/components/document-list.component.ts, lib/core/datatable/components/datatable/datatable.component.scss, lib/core/pagination/infinite-pagination.component.ts
=> [ADF-4040]fix static default pagination

lib/process-services-cloud/src/lib/group/mock/group-cloud.mock.ts, lib/process-services-cloud/src/lib/group/models/group.model.ts, lib/process-services-cloud/src/lib/group/services/group-cloud.service.spec.ts, lib/process-services-cloud/src/lib/group/services/group-cloud.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4054
**Does this PR …
=> [ADF-4054] GroupCloudService - Use composite api to fetch group roles

docs/compatibility.md
=> fix versioning format in compatibility.md

lib/content-services/content-node-selector/content-node-selector-panel.component.html, lib/content-services/content-node-selector/content-node-selector-panel.component.scss, lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts, lib/content-services/content-node-selector/content-node-selector-panel.component.ts, lib/content-services/karma.conf.js, lib/core/karma.conf.js, lib/core/pagination/infinite-pagination.component.html, lib/core/pagination/infinite-pagination.component.spec.ts, lib/core/pagination/infinite-pagination.component.ts, lib/insights/karma.conf.js, lib/process-services/karma.conf.js
> - [x] Bugfix
sites-dropdown broken on Content Node Selector
[ACA] Search results aren't displayed when searching in Copy/Move dialog
[ACA] Can't load more …
=> [ADF-4056][ADF-4060][ADF-3930] Content Node Selector fix

lib/core/pagination/infinite-pagination.component.ts
=> fix typo pageSize in InfinitePaginationComponent

lib/core/form/services/process-content.service.spec.ts, lib/core/form/services/process-content.service.ts, lib/process-services/attachment/process-attachment-list.component.spec.ts, lib/process-services/attachment/process-attachment-list.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4055
**Does this PR …
=> [ADF-4055] ProcessAttachmentListComponent- add opt parameter on process-instances api call

docs/abn-tree.yml, docs/license-info/license-info-v3.0.0.md, package.json, tools/doc/licenseList.js, tools/doc/templates/licensePage.ejs
> - [ ] Bugfix
Added a new license list script that puts the output from license-checker through an EJS template to generate the Markdown page. The script takes a command line parameter which is just the version string for the filename …
=> [ADF-4069] Added updated license list tool

lib/insights/diagram/components/tooltip/diagram-tooltip.component.spec.ts, lib/insights/diagram/components/tooltip/diagram-tooltip.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4073
[Regression] The …
=> [ADF-4073] Fix Process Definition Heat map styling issue

docs/release-notes/RelNote300.md
> - [ ] Bugfix
Reviewed 3.0.0 release notes. Added links from items in new features list. Checked and fixed all links.
> - [ ] Yes
> - [x] No
=> [ADF-3745] Reviewed 3.0.0 release notes

docs/process-services-cloud/process-list-cloud.component.md
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4008
The list of available …
=> [ADF-4008] Add available columns to Process List Cloud documentation

docs/README.md, docs/compatibility.md, docs/license-info/license-info-v3.0.0.md
> - [ ] Bugfix
Added info for 3.0.0 to the compatibility page (with versions in correct three-digit format). Also added a link from the docs index to the License info and added some extra text to the license info page.
**Does this PR …
=> [ADF-4080] Updated compatibility page plus other minor fixes

lib/process-services-cloud/src/lib/process/process-list/public-api.ts, lib/process-services-cloud/src/lib/task/task-list/public-api.ts
> - [ ] Bugfix
Exposed unexposed services.
* ProcessListCloudService and TaskListCloudService are not exposed
**What …
=> [ADF-4084] Expose ProcessListCloudService and TaskListCloudService

lib/core/datatable/components/datatable/datatable.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3862
**Does this PR …
=> [ADF-3861] Document List - aria-label on checkbox and actions menu

docs/breaking-changes/breaking-change-2.6.0-3.0.0.md
> - [ ] Bugfix
breaking change documentation 2.x.x to 3.0.0 …
=> breaking change documentation 3.0.0

docs/README.md, docs/breaking-changes/breaking-change-2.6.0-3.0.0.md
> - [ ] Bugfix
Reviewed breaking changes page and added a link to it from the main docs README.md file.
**Note:** I replaced the absolute Github links with relative ones (eg, for Content node share directive) because the absolute links …
=> [ADF-3745] Reviewed breaking changes page

e2e/pages/adf/lockFilePage.ts, e2e/pages/adf/paginationPage.ts, e2e/pages/adf/process-services/widgets/dynamicTableWidget.ts, lib/content-services/dialogs/node-lock.dialog.html, lib/core/pagination/pagination.component.html
=> [ADF-NO-ISSUE] Changing locators using arial-label

demo-shell/src/app/components/file-view/file-view.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4097
The solution for this bug is not the fix that was …
=> [ADF-4097] Revert changes in Add comment button

demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4023
the layout is broken in DemoShell when displaying the …
=> [ADF-4023] Fix pagination layout issue in Process Cloud page

e2e/pages/adf/configEditorPage.ts, e2e/pages/adf/dataTablePage.ts, e2e/pages/adf/process-cloud/processListCloudComponent.ts, e2e/process-services-cloud/processList-cloud-component.e2e.ts, e2e/process-services-cloud/processListCloud.config.ts
=> [ADF-4012] Should be able to set default columns in adf-process-list-cloud	

lib/core/services/people-process.service.ts
> - [ ] Bugfix
When building and ADF app with local copy of the ng2-components, we get an error.
```
ERROR in …
```
=> Fix wrong types which prevents other apps to build upon local copies

demo-shell/src/app/app.routes.ts, demo-shell/src/app/components/app-layout/cloud/cloud-breadcrumb-component.html, demo-shell/src/app/components/app-layout/cloud/cloud-breadcrumb-component.ts, demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.html, demo-shell/src/app/components/app-layout/cloud/cloud-layout.component.ts, demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/start-process-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/start-process-cloud-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/start-task-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/start-task-cloud-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/task-details-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/task-details-cloud-demo.component.ts, demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.ts, docs/process-services-cloud/edit-process-filter-cloud.component.md, docs/process-services-cloud/edit-task-filter-cloud.component.md, docs/process-services-cloud/process-list-cloud.component.md, docs/process-services-cloud/task-header-cloud.component.md, docs/process-services-cloud/task-list-cloud.component.md, lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4067
**Does this PR …
=> [ADF-4067] Process Service Cloud change applicationName input

lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4068
**Does this PR …
=> [ADF-4068] StartTaskComponent - add description empty space validator

e2e/pages/adf/process-cloud/editTaskFilterCloudComponent.ts, e2e/process-services-cloud/edit-task-filters-component.e2e.ts, e2e/process-services-cloud/tasks-custom-filters.e2e.ts
=> [ADF-4121] Fix tasks-custom-filters test

lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html, lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-filters/task-filters-cloud.module.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4143
**Does this PR …
=> [ADF-4143] EditTaskFilterComponent - change date format

e2e/content-services/permissions-component.e2e.ts, e2e/pages/adf/permissionsPage.ts, lib/content-services/permission-manager/components/permission-list/permission-list.component.html
=> [ADF-4103] Remove User or Group from the Permission list

lib/process-services-cloud/src/lib/i18n/en.json
> - [ ] Bugfix
> - [x] Other... Please describe: Localisation info
Added the properties listed in ADF-4008 to the en.json file for Process services cloud (the props had already been added to process-list-cloud.component.md). I've tried to follow the format of the existing keys but of course, let me know if there are any issues.
**Does …
=> [ADF-4008] Added column keys to en.json for proc list cloud

demo-shell/resources/i18n/en.json, demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.scss, demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4038
**Does this PR …
=> [ADF-4038]  People/GroupCloudDemo - add appName filter

docs/roadmap.md
=> Updated roadmap.

lib/core/pipes/pipe.module.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4154
**Does this PR …
=> [ADF-4154] add FileTypePipe to module's providers

demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4128
**Does this PR …
=> [ADF-4153] TaskListCloud - fix details page redirect 

e2e/pages/adf/configEditorPage.ts, e2e/pages/adf/dialog/editProcessFilterDialog.ts, e2e/pages/adf/process-cloud/editProcessFilterCloudComponent.ts, e2e/process-services-cloud/process-custom-filters.e2e.ts
=> [ADF-3995]Implemented test cases for preserved value for process filter

lib/content-services/i18n/en.json, lib/content-services/site-dropdown/sites-dropdown.component.html, lib/content-services/site-dropdown/sites-dropdown.component.spec.ts, lib/content-services/site-dropdown/sites-dropdown.component.ts
> - [x] Bugfix
) Have a large number of sites created on ACS (e.g. 100).
2) Login as admin or as a specific user.
3) …
=> [ADF-3444] Site list displays only a certain number of sites.

e2e/content-services/permissions-component.e2e.ts, e2e/pages/adf/contentServicesPage.ts, e2e/pages/adf/dialog/contentListPage.ts, e2e/pages/adf/permissionsPage.ts
=> [ADF-4105] Role Site Dropdown is Displayed

demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/tasks-cloud-demo.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4023
Demo-shell: the pagination in the tasks list (cloud) …
=> [ADF-4023] Demo-shell - Fix pagination layout in tasks list

demo-shell/src/app/components/app-layout/cloud/cloud-settings.component.html, e2e/actions/APS-cloud/tasks.ts, e2e/pages/adf/configEditorPage.ts, e2e/pages/adf/contentServicesPage.ts, e2e/pages/adf/dataTablePage.ts, e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts, e2e/pages/adf/process-cloud/editTaskFilterCloudComponent.ts, e2e/process-services-cloud/task-list-properties.e2e.ts, e2e/process-services-cloud/task-list-selection.e2e.ts, e2e/process-services-cloud/taskListCloud.config.ts, e2e/process-services-cloud/tasks-custom-filters.e2e.ts
=> [ADF-4015] Implementing edit task filter automated tests

lib/process-services-cloud/src/lib/services/identity-user.service.ts, lib/process-services-cloud/src/lib/services/public-api.ts, lib/process-services-cloud/src/public-api.ts
=> Process Service Cloud - Add the identity user service

scripts/affected-libs.sh, scripts/npm-build-all.sh, scripts/npm-check-bundles.sh, scripts/npm-publish.sh, scripts/smart-build.sh, scripts/update-version.sh
=> add adf-testing to the pipeline and publish

scripts/ng-packagr.sh
=> Add build testing to ng packager

scripts/ng-packagr.sh
=> adf-testing - Add flatModuleFile into ng-package

lib/testing/ng-package.json, package.json
=> adf-testing - Change name of testing project and bundle size

lib/testing/src/README.md, scripts/npm-check-bundles.sh
=> adf-testing - Add basic Readme and exclude bundle checks

demo-shell/package.json, lib/content-services/package.json, lib/core/package.json, lib/extensions/package.json, lib/insights/package.json, lib/process-services-cloud/package.json, lib/process-services/package.json, package.json
Update ADF packages version 3.1.0-beta4
=> Update ADF packages version 3.1.0-beta4

Dockerfile, docker/entrypoint.sh, docker/nginx.conf, scripts/pr-publish.sh
> - [x] Bugfix
Security fixes and Docker image enhancements:
- fix the issue with …
=> [ADF-4158] improved Docker image security

demo-shell/src/app/components/datatable/datatable.component.ts, lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4122
Minor breakdown in ellipsis class on the recently …
=> [ADF-4122] Improve ellipsis class in Datatable component

e2e/pages/adf/searchFiltersPage.ts, e2e/search/search-filters.e2e.ts
> - [ ] Bugfix
The facet filter would show these 2 new facet intervals:
The Created …
=> [ADF-3497] - Facet intervals on search filter-expand-collapse

demo-shell/resources/i18n/ar.json, lib/content-services/i18n/ar.json, lib/core/i18n/ar.json, lib/insights/i18n/ar.json, lib/process-services-cloud/src/lib/i18n/ar.json, lib/process-services/i18n/ar.json
> - [ ] Bugfix
New Arabic i18n files support  …
=> [ADF-4184] new Arabic 18n files support

demo-shell/resources/i18n/en.json, demo-shell/src/app/app.routes.ts, docs/core/README.md, docs/core/auth-guard-sso-role.service.md, lib/core/i18n/en.json, lib/core/login/components/login.component.html, lib/core/login/components/login.component.spec.ts, lib/core/login/components/login.component.ts, lib/core/services/auth-guard-sso-role.service.spec.ts, lib/core/services/auth-guard-sso-role.service.ts, lib/core/services/authentication.service.ts, lib/core/services/public-api.ts
> - [ ] Bugfix
- When the user tries to access a route without the right access role the SSO role guard will redirect the user on a forbidden page
- If the SSO …
=> [ADF-3735] SSO Role guard and Login error improvement

lib/core/login/components/login.component.ts, lib/core/services/auth-guard-base.ts, lib/core/services/auth-guard-bpm.service.spec.ts, lib/core/services/auth-guard-bpm.service.ts, lib/core/services/auth-guard-ecm.service.spec.ts, lib/core/services/auth-guard-ecm.service.ts, lib/core/services/auth-guard.service.spec.ts, lib/core/services/auth-guard.service.ts, lib/core/services/public-api.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4183
- base class for 3 …
=> [ADF-4183] improved auth redirection

demo-shell/src/app/components/datatable/datatable.component.html, demo-shell/src/app/components/datatable/datatable.component.ts, e2e/pages/adf/dataTablePage.ts, lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4122
Some e2e tests were failing because of the …
=> [ADF-4122] Improve Datatable and fix broken e2e tests

demo-shell/resources/i18n/en.json, demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/people-groups-cloud-demo.component.ts, docs/core/identity-user.service.md, docs/process-services-cloud/people-cloud.component.md, lib/core/userinfo/services/identity-user.service.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
…lidations
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4048
**Does this …
=> [ADF-4048] PeopleCloudComponent - improve preselect input functionality

docs/content-services/document-list.component.md, lib/content-services/document-list/components/document-list.component.ts
> - [ ] Bugfix
Improved the description of the `allowDropFiles` property, following a suggestion from Cristina.
> - [ ] Yes
> - [x] No
=> [ADF-4189] Improved document list prop description

e2e/core/pagination-empty-current-page.e2e.ts, e2e/core/viewer/viewer-component.e2e.ts
=> [ADF-4061]Automate test for navigating to a non empty folder on last page

e2e/pages/adf/process-cloud/editTaskFilterCloudComponent.ts, e2e/process-services-cloud/edit-task-filters-component.e2e.ts
=> [ADF-4192]Remove wait for spinner from editTaskFilterCloudComponent test

.travis.yml, e2e/pages/adf/searchFiltersPage.ts, e2e/search/search-filters.e2e.ts, scripts/affected-folder.sh, scripts/affected-libs.sh, scripts/smart-build.sh, scripts/test-e2e-lib.sh
> - [ ] Bugfix
The Filter facet fields and queries are reseted when the search query …
=> [ADF-3401] Filter facets are not reseted when updating the search query

lib/content-services/dialogs/public-api.ts
=> [ADF-4223] Exporting folder-name validators to allow reuse

demo-shell/resources/i18n/en.json, demo-shell/src/app/components/app-layout/app-layout.component.html, demo-shell/src/app/components/app-layout/app-layout.component.ts, e2e/pages/adf/navigationBarPage.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4159
**Does this PR …
=> [ADF-4159] DemoShell - add nested menu on ProcessCloud

demo-shell/src/app/components/datatable/datatable.component.ts, lib/content-services/content-node-selector/content-node-selector-panel.component.scss, lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4196
The row was not always selected when this one was …
=> [ADF-4196] Improve Datatable component row click selection

demo-shell/src/app/components/logout/logout.component.html, e2e/core/login/redirection.e2e.ts, e2e/pages/adf/demo-shell/logoutPage.ts
> - [ ] Bugfix
Automation test for redirection after login page is reloaded.
**Does …
=> [ADF-4197] Automation test for redirection after page reload

demo-shell/src/app.config.json, demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html, demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.ts, docs/process-services-cloud/edit-process-filter-cloud.component.md, e2e/pages/adf/process-cloud/editProcessFilterCloudComponent.ts, e2e/process-services-cloud/process-custom-filters.e2e.ts, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts, lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts, lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3977
**Does this PR …
=> [ADF-3977] EditProcessComponent - Be able to change the sort and actions

e2e/core/login/login-component.e2e.ts, e2e/core/login/login-sso/login-sso.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/login-sso.page.ts
> - [ ] Bugfix
When the user tries to access a route without the right access role the …
=> [ADF-3735] SSO Login Error for login component

docs/roadmap.md, docs/user-guide/README.md, docs/user-guide/rtl-support.md
> - [ ] Bugfix
Added basic page to start off RTL language docs, which we will extend as features appear.
> - [ ] Yes
> - [x] No
=> [ADF-4228] Started basic doc for RTL support

demo-shell/src/app/components/process-service/process-service.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4076
The user is redirected to the active task but the …
=> [ADF-4076] Fix redirection to tasks tab on process task click

demo-shell/src/app/components/permissions/demo-permissions.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4205
In the previous PR we fixed one of the snackbar …
=> [ADF-4205] Fix permission error snackbar

lib/content-services/breadcrumb/breadcrumb.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/secure/RapidBoard.jspa?rapidView=529&view=detail&selectedIssue=ADF-195 …
=> [ADF-1954] Fix breadcrumb on IE 11

docs/extensions/components/preview-extension.component.md, docs/process-services-cloud/components/process-header-cloud.component.md, docs/process-services-cloud/services/process-header-cloud.service.md, lib/extensions/src/lib/components/viewer/preview-extension.component.ts
> - [ ] Bugfix
Reviewed recently-added component docs for 3.1.
> - [ ] Yes
> - [x] No
=> [ADF-4249] Started doc review for 3.1

docs/process-services/components/process-list.component.md, docs/process-services/components/task-list.component.md
> - [ ] Bugfix
Added explicit links/description for TaskDetailsModel and ProcessInstance to show the fields available in the list components.
> - [ ] Yes
> - [x] No
=> [ADF-588] Explicitly added task/process list model classes to docs

demo-shell/src/app/components/process-service/process-service.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4076
Another bug came up fixing the previous bug.
**What …
=> Fix redirection to tasks tab on process task click

demo-shell/src/app/components/trashcan/trashcan.component.html, e2e/pages/adf/process-cloud/processListCloudComponent.ts, e2e/pages/adf/process-cloud/taskListCloudComponent.ts, e2e/pages/adf/process-services/processFiltersPage.ts, e2e/pages/adf/process-services/processListPage.ts, e2e/pages/adf/process-services/tasksListPage.ts, lib/core/templates/empty-content/empty-content.component.html, lib/core/templates/empty-content/empty-content.component.scss
> - [x] Bugfix
The empty screens are not wrapping text on small screens (due to usage of `<p>` tag) …
=> fix responsiveness issues for empty screen

demo-shell/src/app/app.module.ts, demo-shell/src/app/components/app-layout/app-layout.component.html, demo-shell/src/app/components/app-layout/app-layout.component.scss, demo-shell/src/app/components/app-layout/cloud/directives/nested-menu-position.directive.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4233
**Does this PR …
=> [ADF-4233] DemoShell - change nested menu layout

demo-shell/src/app.config.json, docs/content-services/components/content-metadata-card.component.md, lib/content-services/content-metadata/components/content-metadata/content-metadata.component.html, lib/content-services/content-metadata/components/content-metadata/content-metadata.component.spec.ts, lib/content-services/content-metadata/components/content-metadata/content-metadata.component.ts, lib/content-services/content-metadata/interfaces/aspect-oriented-config.interface.ts, lib/content-services/content-metadata/interfaces/content-metadata-config.interface.ts, lib/content-services/content-metadata/interfaces/layout-oriented-config.interface.ts, lib/content-services/content-metadata/services/config/aspect-oriented-config.service.spec.ts, lib/content-services/content-metadata/services/config/aspect-oriented-config.service.ts, lib/content-services/content-metadata/services/config/content-metadata-config.factory.spec.ts, lib/content-services/content-metadata/services/config/indifferent-config.service.ts, lib/content-services/content-metadata/services/config/layout-oriented-config.service.spec.ts, lib/content-services/content-metadata/services/config/layout-oriented-config.service.ts, lib/content-services/content-metadata/services/content-metadata.service.spec.ts, lib/content-services/content-metadata/services/content-metadata.service.ts, lib/core/app-config/schema.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4162
The metadata component was missing include/exclude …
=> [ADF-4162] Add includeAll/exclude capabilities to metadata config

.travis.yml
> - [ ] Bugfix
execute docker step only in PR branch …
=> [ADF-3978] execute docker step only in PR branch

e2e/core/infinite-scrolling.e2e.ts
=> [ADF-4045]Add Delete folder when infinite scrolling is enabled test.

e2e/core/login/login-sso/login-sso.e2e.ts, e2e/pages/adf/loginPage.ts, e2e/test.config.js, lib/core/login/components/login.component.ts, lib/testing/src/lib/process-services-cloud/pages/login-sso.page.ts, protractor.conf.js
> - [ ] Bugfix
E2E tests for SSO login with implicitFlow false.
**Does this PR …
=> [ADF-4195] Automation tests for SSO login with implicitFlow false

docs/release-notes/RelNote161.md, docs/release-notes/RelNote170.md, docs/release-notes/RelNote180.md, docs/release-notes/RelNote190.md, docs/release-notes/RelNote200.md, docs/release-notes/RelNote210.md, docs/release-notes/RelNote220.md, docs/release-notes/RelNote230.md, docs/release-notes/RelNote240.md, docs/release-notes/RelNote250.md, docs/release-notes/RelNote260.md, docs/release-notes/RelNote300.md, tools/doc/doctool.config.json, tools/doc/mqDefs.js, tools/doc/mqDefs.ts, tools/doc/tools/gqIndex.js, tools/doc/tools/gqIndex.ts, tools/doc/tools/linkFixer.js, tools/doc/tools/linkFixer.ts, tools/doc/tsconfig.json
> - [ ] Bugfix
Added a tool to fix links between doc files automatically. Tested the tool by fixing the links in the release notes (also included in the PR).
> - [ ] Yes …
=> [ADF-4252] Added doc link fixing tool

lib/content-services/permission-manager/components/permission-list/permission-list.component.html, lib/content-services/permission-manager/components/permission-list/permission-list.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/secure/RapidBoard.jspa?rapidView=529&view=detail&selectedIssue=ADF-419 …
=> [ADF-4199] Fix permission manager UI

lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4263
* Fixed failing unit …
=> [ADF-4263][EditProcessFilterCloudComponent] Unit tests are failing

demo-shell/src/app/components/app-layout/app-layout.component.html, demo-shell/src/app/components/app-layout/cloud/directives/nested-menu-position.directive.ts, lib/core/about/about.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4233
**Does this PR …
=> [ADF-4233] - fixed nested menu layout for minimized sidebar menu

lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
=> Cloud people component - Fix the unit test related to the subject initialization

lib/core/pagination/pagination.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/secure/RapidBoard.jspa?rapidView=529&view=detail&selectedIssue=ADF-423 …
=> [ADF-4230] Fix pagination arrows direction when ADF set to RTL

demo-shell/src/app/components/files/files.component.html, demo-shell/src/app/components/files/files.component.scss, lib/core/datatable/components/datatable/datatable.component.scss, lib/core/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
- add the missing border for the last row
- fix the row height (add …
=> css fixes for datatable

lib/core/form/public-api.ts
> - [x] Bugfix
https://github.com/Alfresco/alfresco-ng2-components/issues/4478 …
=> [ADF-GITHUB-4478] Add missing WidgetVisibilityService export

docs/process-services-cloud/components/edit-task-filter-cloud.component.md
=> [ADF-3976] Update doc

demo-shell/src/app/app.component.html, demo-shell/src/app/app.component.scss, demo-shell/src/app/app.component.ts, demo-shell/src/app/components/config-editor/config-editor.component.html, demo-shell/src/app/components/config-editor/config-editor.component.ts
> - [ ] Bugfix
New configuration in the demo shell to set the RTL 
**Does this PR …
=> [ADF-4227] rtl configuration

.travis.yml, e2e/content-services/upload/excluded-file.e2e.ts, e2e/content-services/upload/uploader-component.e2e.ts, e2e/content-services/upload/user-permission.e2e.ts, e2e/pages/adf/contentServicesPage.ts, e2e/search/components/search-sorting-picker.e2e.ts, e2e/test.config.js, lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts
=> exclude upload folder test as far we don't find a solution in chrome 73

demo-shell/src/assets/app.extensions.json, lib/core/viewer/components/viewer.component.html, lib/core/viewer/components/viewer.component.ts, lib/extensions/src/lib/config/document-list.extensions.ts, lib/extensions/src/lib/config/icon.extensions.ts, lib/extensions/src/lib/config/rule.extensions.ts, lib/extensions/src/lib/services/app-extension.service.ts, lib/extensions/src/lib/services/extension-loader.service.ts, lib/extensions/src/lib/services/extension.service.spec.ts, lib/extensions/src/lib/services/extension.service.ts, lib/extensions/src/lib/services/rule.service.ts, lib/extensions/src/public-api.ts
> - [ ] Bugfix
- add some interfaces for the Extensions lib that were missing 
- …
=> extensibility improvements

lib/testing/src/lib/core/material/public-api.ts, lib/testing/src/lib/core/material/tabs.page.ts, lib/testing/src/lib/core/pages/public-api.ts, lib/testing/src/lib/core/pages/user-info.page.ts, lib/testing/src/lib/core/public-api.ts, lib/testing/src/lib/material/public-api.ts, lib/testing/src/lib/process-services-cloud/pages/public-api.ts, lib/testing/src/public-api.ts
=> [ADF-NO-ISSUE] Removing wrong dependencies in testing package

lib/content-services/index.ts, lib/content-services/tree-view/public-api.ts
> - [x] Bugfix
TreeViewService is not exported as a public class
TreeViewService is …
=> fix export tree-view component into content-services module

demo-shell/src/app/components/app-layout/cloud/processes-cloud-demo.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4281
The filter was passing a non-existent state property …
=> [ADF-4281] Regression - Fix process filter cloud selection

e2e/pages/adf/searchResultsPage.ts, e2e/search/search-component.e2e.ts, e2e/search/search.config.ts
> - [ ] Bugfix
Automation test for search result highlight …
=> [ADF-4265] Automation test for search highlight

docs/README.md, docs/abn-tree.yml, docs/upgrade-guide/upgrade26-30.md
> - [ ] Bugfix
Added a 2.6->3.0 upgrade guide based on the breaking changes for 3.0 and the structure of the previous guides. Also updated Builder Network YAML index file.
@fcorti I've done this as a draft PR for now. Please let me know …
=> [ADF-4146] Added 2.6 -> 3.0 upgrade guide

demo-shell/src/app/app.module.ts
=> Fix app layout

lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
=> [ADF-EditProcessFilterCloudComponent] Fixed failing Unit test

demo-shell/src/app/components/files/files.component.html, demo-shell/src/app/components/files/files.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4282
The content alignment …
=> [ADF-4282] Fix document list UI when on small screen devices

demo-shell/src/app/components/config-editor/config-editor.component.html, demo-shell/src/app/components/config-editor/config-editor.component.ts
editor.
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4155
**Does this PR …
=> [ADF-ApplicationDeploymentCloudService] Provide way to config applications from editor

lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts, lib/process-services-cloud/src/lib/task/directives/claim-task.directive.spec.ts
=> Process Cloud Service - Fix unit test related to claim

demo-shell/src/app/app.module.ts, demo-shell/src/app/components/files/files.component.ts, e2e/core/card-view/aspect-oriented-config.e2e.ts, e2e/core/card-view/metadata-smoke-tests.e2e.ts, e2e/proxy.ts, lib/content-services/document-list/components/library-name-column/library-name-column.component.ts, lib/content-services/document-list/components/library-role-column/library-role-column.component.spec.ts, lib/content-services/document-list/components/library-role-column/library-role-column.component.ts, lib/content-services/document-list/components/library-status-column/library-status-column.component.ts, lib/content-services/document-list/components/name-column/name-column.component.ts, lib/content-services/document-list/data/share-data-row.model.ts, lib/core/datatable/components/datatable/datatable-cell.component.spec.ts, lib/core/datatable/components/datatable/datatable-cell.component.ts, lib/core/datatable/components/datatable/date-cell.component.ts, lib/core/datatable/components/datatable/filesize-cell.component.ts, lib/core/datatable/components/datatable/location-cell.component.spec.ts, lib/core/datatable/components/datatable/location-cell.component.ts, lib/core/services/automation.service.ts, lib/core/services/public-api.ts
> - [ ] Bugfix
- sync cell text with the node updates …
=> [ADF-3794] Update individual rows without reloading DocumentList

demo-shell/src/app/components/file-view/file-view.component.html, demo-shell/src/app/components/file-view/file-view.component.ts, e2e/core/viewer/info-drawer.component.e2e.ts, e2e/pages/adf/viewerPage.ts, lib/core/info-drawer/info-drawer.component.html
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4298
Add automation tests …
=> [ADF-4298] Add e2e tests for info drawer

docs/process-services-cloud/components/edit-process-filter-cloud.component.md, docs/process-services-cloud/components/edit-task-filter-cloud.component.md
> - [ ] Bugfix
Updated the sort properties sections in Edit proc/task filter cloud to mention the default properties explicitly.
> - [ ] Yes
> - [x] No
=> [ADF-4300] Updated sort properties lists with the non-filter properties

demo-shell/src/app/components/files/files.component.html, demo-shell/src/app/components/files/files.component.scss, lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4305
Some changes last week had introduced some …
=> [ADF-4305] Regression - Fix document list component styling

demo-shell/src/app/components/files/files.component.html, lib/core/datatable/components/datatable/datatable.component.scss
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4325
Alignment issue of Created By column
**What is the …
=> [ADF-4325] Regression - Demo-Shell - Fix alignment in document-list

lib/process-services/people/components/people/people.component.html, lib/process-services/people/components/people/people.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4316
The layout seemed not to be correct in the people …
=> [ADF-4316] Regression - Fix People component layout

demo-shell/src/app.config.json, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.css, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.scss, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4287
Added space between …
=> [ADF-4287] Fix tasks UI in Process Cloud

lib/content-services/permission-manager/components/permission-list/permission-list.component.html, lib/content-services/permission-manager/components/permission-list/permission-list.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4324
The label is now set …
=> [ADF-4324] Fix Role label in Content Services permissions

demo-shell/src/app/app.routes.ts, demo-shell/src/app/components/app-layout/app-layout.component.ts, demo-shell/src/app/components/document-list/extension-presets/extension-presets.component.html, demo-shell/src/app/components/document-list/extension-presets/extension-presets.component.ts, demo-shell/src/app/components/document-list/extension-presets/extension-presets.module.ts, demo-shell/src/app/components/document-list/extension-presets/name-column/name-column.component.ts, demo-shell/src/assets/app.extensions.json, lib/content-services/document-list/components/library-name-column/library-name-column.component.ts, lib/content-services/document-list/components/library-role-column/library-role-column.component.ts, lib/content-services/document-list/components/library-status-column/library-status-column.component.ts, lib/content-services/document-list/components/name-column/name-column.component.ts, lib/content-services/document-list/components/trashcan-name-column/trashcan-name-column.component.ts, lib/core/datatable/components/datatable/datatable.component.html, lib/extensions/src/lib/services/app-extension.service.ts, package-lock.json
> - [ ] Bugfix
- add new extensibility section to demo shell
- add example of document …
=> document list extensions (demo shell)

docs/README.md, docs/core/services/nodes-api.service.md, docs/process-services-cloud/services/task-cloud.service.md, docs/release-notes/RelNote300.md, docs/release-notes/RelNote310.md
> - [ ] Bugfix
Edited latest changes to release notes. Fixed a few remaining bad links.
> - [ ] Yes
> - [x] No
=> [ADF-4249] Doc review updates

e2e/search/components/search-sorting-picker.e2e.ts, lib/content-services/search/components/search-sorting-picker/search-sorting-picker.component.spec.ts, lib/content-services/search/components/search-sorting-picker/search-sorting-picker.component.ts, lib/core/viewer/components/pdfViewer.component.spec.ts
> - [x] Bugfix
Please check https://issues.alfresco.com/jira/browse/ADF-4280
**Does …
=> [ADF-4280] fix initial display for search-sorting-picker

demo-shell/package.json, lib/content-services/package.json, lib/core/package.json, lib/extensions/package.json, lib/insights/package.json, lib/process-services-cloud/package.json, lib/process-services/package.json, lib/testing/package.json, package.json
=> 3.1.0 version package.json

lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4275
**Does this PR …
=> [ADF-4274] - Fix  users filtering on single selection mode

scripts/test-e2e-lib.sh
=> [ADF-4335]Update webdriver-manager

e2e/process-services-cloud/people-group-cloud-component.e2e.ts, lib/testing/src/lib/core/actions/identity/identity.service.ts
=> fix the failing test - people-group-cloud-component

lib/testing/src/lib/core/browser-visibility.ts
=> Fixed condition for TestConfig file

demo-shell/src/app/components/file-view/file-view.component.html, demo-shell/src/app/components/file-view/file-view.component.ts, e2e/core/viewer/info-drawer.component.e2e.ts, e2e/pages/adf/viewerPage.ts, lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
The behavior of the info drawer tab has changed and so the tests requirements …
=> [ADF-4298] Improve Info drawer e2e tests

e2e/content-services/document-list/document-list-actions.e2e.ts, e2e/pages/adf/contentServicesPage.ts
Added a new test for move file.
> - [ ] Bugfix …
=> [ADF-4046]Refactored document-list-actions tests.

e2e/process-services-cloud/edit-task-filters-component.e2e.ts, e2e/process-services-cloud/people-group-cloud-component.e2e.ts, e2e/process-services-cloud/process-custom-filters.e2e.ts, e2e/process-services-cloud/process-filters-cloud.e2e.ts, e2e/process-services-cloud/process-header-cloud.e2e.ts, e2e/process-services-cloud/processList-cloud-component.e2e.ts, e2e/process-services-cloud/task-filters-cloud.e2e.ts, e2e/process-services-cloud/task-header-cloud.e2e.ts, e2e/process-services-cloud/task-list-properties.e2e.ts, e2e/process-services-cloud/task-list-selection.e2e.ts, e2e/process-services-cloud/tasks-custom-filters.e2e.ts, e2e/process-services/people-component.e2e.ts
=> [ADF-4344]Fix e2e cloud tests.

e2e/content-services/version/version-permissions.e2e.ts, e2e/pages/adf/process-services/taskDetailsPage.ts, e2e/process-services/task-details-form.e2e.ts, protractor.conf.js
=> [ADF-4350]Fix cloud tests

demo-shell/src/app/components/app-layout/app-layout.component.ts, docs/core/services/user-preferences.service.md, lib/core/services/user-preferences.service.ts
> - [ ] Bugfix
expandedSideNav hasn't a proper user preference value that can be listened …
=> [ADF-4328] added expandedSideNav as new user preference value

angular.json, lib/core/settings/host-settings.component.html, lib/tslint.json
=> [no-issue] fix lint organization

docs/tutorials/activiti-7-and-adf.md
=> Update of the Activiti 7 tutorial after some new tests.

lib/core/layout/components/sidenav-layout/sidenav-layout.component.scss
> - [x] Bugfix
Broken layout on cloud page after adding ACA styling patches …
=> [ADF-4363] Fix sidenav layout

docs/content-services/components/content-metadata-card.component.md
> - [ ] Bugfix
Removed misleading example from Content Metadata docs.
> - [ ] Yes
> - [x] No
=> [ADF-4285] Removed incorrect example from content metadata docs

lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4275
**Does this PR …
=> [ADF-4275] - Fix preselect user validation for User Id

lib/core/login/components/login.component.html
> - [x] Bugfix
Tab navigation not working on Login page
https://issues.alfresco.com/jira/browse/ADF-4361
**What is …
=> [ADF-4361] Fix Tab navigation on Login page

e2e/process-services-cloud/start-process-cloud.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/public-api.ts, lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
=> [ADF-4365] Add start-process-cloud-component.page.ts page in @adf-testing

demo-shell/src/app/components/datatable/datatable.component.ts
> - [ ] Bugfix
A place where to test the json cell type in demo-shell is needed for testing purposes …
=> [ADF-4368] Add JSON cell to datatable in Demo-Shell for testing purposes

e2e/content-services/document-list/document-list-component.e2e.ts, e2e/process-services/comment-component-processes.e2e.ts, e2e/process-services/comment-component-tasks.e2e.ts
=> [ADF-4216] Recently uploaded files are missing 'ago' in the Created column

demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.html, docs/process-services-cloud/components/people-cloud.component.md, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.html, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.ts, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3934
**Does this PR …
=> [ADF-3934]  PeoplCloudComponent - add dynamic placeholder

lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts, lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts, lib/process-services-cloud/src/lib/task/start-task/mock/user-cloud.mock.ts, lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4357
**Does this PR …
=> [ADF-4357] TaskListCloud - change complete task condition

e2e/process-services/process-instance-details.e2e.ts
> - [ ] Bugfix
Automation test for process instance date format
**Does this PR …
=> [ADF-4367] Automation for process date format

demo-shell/src/app/components/cloud/tasks-cloud-demo.component.html, docs/process-services-cloud/components/edit-task-filter-cloud.component.md, lib/process-services-cloud/src/lib/i18n/en.json, lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4321
The edit task filter component is missing the task id …
=> [ADF-4321] Add Task Id filter to task cloud filters

docs/process-services-cloud/components/edit-process-filter-cloud.component.md
> - [ ] Bugfix
Updated property names to "name" and "id" in the table, text, and example.
> - [ ] Yes
> - [x] No
=> [ADF-4383] Updated filter props details in Edit proc cloud docs

lib/content-services/document-list/services/custom-resources.service.ts
> - [ ] Bugfix
- provide optional support for setting extra filters for the "recent …
=> [ADF-4384] improve recent files query

e2e/content-services/upload/remove-upload.e2e.ts, lib/content-services/i18n/en.json, lib/content-services/upload/components/file-uploading-list-row.component.html, lib/content-services/upload/components/file-uploading-list-row.component.spec.ts, lib/content-services/upload/components/file-uploading-list-row.component.ts, lib/content-services/upload/components/file-uploading-list.component.spec.ts, lib/content-services/upload/components/file-uploading-list.component.ts, lib/core/services/thumbnail.service.ts
> - [x] Bugfix
[ADF-4371](https://issues.alfresco.com/jira/browse/ADF-4371)
- deleting …
=> [ADF-4371] Versioning - revert upload version on delete

e2e/core/error-component.e2e.ts
> - [ ] Bugfix
Automation tests to check that when an error is thrown, accurate message is displayed.
**What is the …
=> [ADF-4373] Automation test for accurate error messages

lib/content-services/document-list/components/document-list.component.scss, lib/core/clipboard/clipboard.directive.ts, lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4386
**Does this PR …
=> [ADF-4386] ClipboardDirective - Fix style and remove value from tooltip

lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4291
**Does this PR …
=> [ADF-4921] TaskListCloud - fix lastModifiedTo date filter

e2e/process-services-cloud/process-custom-filters.e2e.ts, e2e/process-services-cloud/process-header-cloud.e2e.ts, e2e/process-services-cloud/processList-cloud-component.e2e.ts, e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts, e2e/process-services-cloud/task-filters-cloud.e2e.ts, e2e/process-services-cloud/task-header-cloud.e2e.ts, e2e/util/constants.js, lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts
=> [ADF-4354]Fix cloud tests one by one

demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.html, e2e/pages/adf/demo-shell/process-services/peopleGroupCloudComponentPage.ts, e2e/process-services-cloud/people-group-cloud-component.e2e.ts, lib/testing/src/lib/core/actions/identity/group-identity.service.ts, lib/testing/src/lib/core/actions/identity/identity.service.ts, lib/testing/src/lib/core/actions/identity/roles.service.ts, lib/testing/src/lib/core/models/user.model.ts, lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
=> [ADF-4278][ADF-4277] - Should fetch the preselect users

.travis.yml, demo-shell/proxy.conf.js, tslint.json
> - [ ] Bugfix
Run always all when is not a PR …
=> [build-issue] Run always all when is not a PR

docs/process-services-cloud/services/form-cloud.service.md
> - [ ] Bugfix
Removed duplicate title metadata from Form Cloud service docs, which was causing problems with publishing (spotted by one of the Builder Network developers). …
=> [ADF-4391] Removed duplicate title in Form Cloud service docs

e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts, lib/testing/src/lib/core/actions/identity/tasks.service.ts
=> [ADF-4274] Should be able to reassign the removed user when starting a new task.

e2e/pages/adf/demo-shell/process-services/taskDetailsCloudDemoPage.ts, e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts, e2e/process-services-cloud/task-header-cloud.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
=> [ADF-4311] - ProcessCloud - Incorrect label loaded for unclaim option -> "Resqueue" should be "Release"

docs/upgrade-guide/upgrade30-31.md
> - [ ] Bugfix
I'm not sure how this got lost but I've added the copy from my local branch again.
> - [ ] Yes
> - [x] No
=> [ADF-4260] Re-adding upgrade guide 3.0 -> 3.1

e2e/proxy.ts, protractor.conf.js, scripts/test-e2e-lib.sh
> - [ ] Bugfix
option to disable controlflow in e2e script …
=> protractor option disable controlflow option in e2e script

demo-shell/src/app/components/cloud/task-details-cloud-demo.component.html, demo-shell/src/app/components/cloud/task-details-cloud-demo.component.ts, docs/process-services-cloud/components/task-header-cloud.component.md, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4393
**Does this PR …
=> [ADF-4393] TaskHeaderCloud  - remove readOnly property

lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.html, lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.scss, lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.ts, lib/process-services-cloud/src/lib/i18n/en.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3983
When the user has no permissions the page gets stuck …
=> [ADF-3983] Add permission template to app list cloud

demo-shell/package.json, lib/content-services/package.json, lib/core/package.json, lib/extensions/package.json, lib/insights/package.json, lib/process-services-cloud/package.json, lib/process-services/package.json, lib/testing/package.json, package.json
Update ADF packages version 3.2.0-beta6
=> Update ADF packages version 3.2.0-beta6

demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.html, demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4043
**Does this PR …
=> [ADF-4043] Demo Shell- Fix roles display

e2e/core/card-view/metadata-smoke-tests.e2e.ts, lib/content-services/version-manager/version-list.component.spec.ts, lib/content-services/version-manager/version-list.component.ts, lib/core/datatable/components/datatable/datatable-cell.component.spec.ts, lib/core/datatable/components/datatable/datatable-cell.component.ts
> - [x] Bugfix
[ADF-4400](https://issues.alfresco.com/jira/browse/ADF-4400)
**Does …
=> [ADF-4400] Versioning - restore does not update the document list

e2e/content-services/version/version-actions.e2e.ts, e2e/pages/adf/trashcanPage.ts, lib/testing/src/lib/core/pages/data-table-component.page.ts
> - [ ] Bugfix
Automation test to make sure a file isn't deleted when we cancel upload of a new version.
**What is …
=> [ADF-4396] Automation test for cancelling new version upload

demo-shell/src/app/app.routes.ts, demo-shell/src/app/components/app-layout/app-layout.component.ts, demo-shell/src/app/components/datatable/copy-content/datatable.component.html, demo-shell/src/app/components/datatable/copy-content/datatable.component.ts, demo-shell/src/app/components/datatable/copy-content/datatable.module.ts, demo-shell/src/app/components/datatable/datatable.component.html, demo-shell/src/app/components/datatable/datatable.component.ts, e2e/core/datatable/data-table-component.e2e.ts, e2e/pages/adf/demo-shell/dataTablePage.ts, e2e/pages/adf/navigationBarPage.ts, lib/testing/src/lib/core/browser-visibility.ts, lib/testing/src/lib/core/pages/data-table-component.page.ts
=> [ADF-4390]Added copyContent datatable cell tests

demo-shell/src/app/components/cloud/task-details-cloud-demo.component.html, demo-shell/src/app/components/cloud/task-details-cloud-demo.component.ts, docs/process-services-cloud/components/task-form-cloud.component.md, lib/core/i18n/en.json, lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts, lib/process-services-cloud/src/lib/form/components/task-form-cloud.component.html, lib/process-services-cloud/src/lib/form/components/task-form-cloud.component.scss, lib/process-services-cloud/src/lib/form/components/task-form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/form/components/task-form-cloud.component.ts, lib/process-services-cloud/src/lib/form/form-cloud.module.ts, lib/process-services-cloud/src/lib/form/models/form-cloud.model.ts, lib/process-services-cloud/src/lib/form/public-api.ts, lib/process-services-cloud/src/lib/i18n/en.json, lib/process-services-cloud/src/lib/styles/_index.scss, lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts, lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts
> - [ ] Bugfix
There is no component to render variaous actions(claim/unclaim/save/complete/cancel) and form of a …
=> [ADF-4349] Cloud - task-form-component - Create a new component

e2e/content-services/upload/remove-upload.e2e.ts, lib/content-services/i18n/en.json, lib/content-services/upload/components/file-uploading-dialog.component.scss, lib/content-services/upload/components/file-uploading-list-row.component.html, lib/content-services/upload/components/file-uploading-list-row.component.scss, lib/content-services/upload/components/file-uploading-list-row.component.spec.ts, lib/content-services/upload/components/file-uploading-list.component.spec.ts, lib/content-services/upload/components/file-uploading-list.component.ts
> - [ ] Bugfix
[ADF-4410](https://issues.alfresco.com/jira/browse/ADF-4410)
- uploaded …
=> [ADF-4410] Upload dialog - remove delete action of version upload 

demo-shell/src/app/components/document-list/extension-presets/name-column/name-column.component.ts, demo-shell/src/app/components/files/files.component.html, demo-shell/src/app/components/trashcan/trashcan.component.html, docs/core/components/datatable.component.md, lib/content-services/content-node-selector/name-location-cell/name-location-cell.component.ts, lib/content-services/document-list/components/library-name-column/library-name-column.component.ts, lib/content-services/document-list/components/library-role-column/library-role-column.component.ts, lib/content-services/document-list/components/library-status-column/library-status-column.component.ts, lib/content-services/document-list/components/name-column/name-column.component.ts, lib/content-services/document-list/components/trashcan-name-column/trashcan-name-column.component.ts, lib/core/datatable/components/datatable/datatable-cell.component.ts, lib/core/datatable/components/datatable/datatable.component.scss, lib/core/datatable/components/datatable/date-cell.component.ts, lib/core/datatable/components/datatable/json-cell.component.ts, lib/core/datatable/components/datatable/location-cell.component.ts
> - [x] Bugfix
Please check https://issues.alfresco.com/jira/browse/ADF-4401
**Does …
=> [ADF-4401] Fix DL issues because of nested 'adf-datatable-cell' items

lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4291
lastModifiedTo filter not working properly for …
=> [ADF-4291] Fix lastModifiedTo filter on processes

e2e/proxy.ts, e2e/search/components/search-checkList.e2e.ts, e2e/search/components/search-date-range.e2e.ts, e2e/search/components/search-number-range.e2e.ts, e2e/search/components/search-radio.e2e.ts, e2e/search/components/search-slider.e2e.ts, e2e/search/components/search-sorting-picker.e2e.ts, e2e/search/components/search-text.e2e.ts, e2e/search/search-component.e2e.ts, e2e/search/search-filters.e2e.ts, e2e/search/search-multiselect.e2e.ts
=> [NO-ISSUE] speed up search test

.travis.yml, e2e/content-services/permissions/site-permissions.e2e.ts, e2e/content-services/version/version-actions.e2e.ts, e2e/process-services-cloud/task-header-cloud.e2e.ts, e2e/search/search-multiselect.e2e.ts, e2e/search/search-page-component.e2e.ts, scripts/update-project.sh
=> [no-issue] fix test plus fix update script

lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4420
**Does this PR …
=> [ADF-4420] TaskHeaderCloud - fix show endDate

lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4430
**Does this PR …
=> [ADF-4430] Metadata-  fix error message

demo-shell/src/app/components/datatable/copy-content/datatable.component.html, demo-shell/src/app/components/datatable/copy-content/datatable.component.ts, e2e/core/datatable/data-table-component.e2e.ts, e2e/pages/adf/contentServicesPage.ts, e2e/pages/adf/demo-shell/customSourcesPage.ts, e2e/pages/adf/demo-shell/dataTablePage.ts, e2e/pages/adf/permissionsPage.ts, e2e/pages/adf/searchResultsPage.ts, lib/core/datatable/components/datatable/datatable.component.html, lib/testing/src/lib/core/pages/data-table-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
=> [ADF-4394]Add two more tests on copyContent

docs/upgrade-guide/upgrade31-32.md
> - [ ] Bugfix
Added upgrade guide for version 3.1 -> 3.2.
> - [ ] Yes
> - [x] No
=> [ADF-4416] Added upgrade guide 3.1 -> 3.2

.travis.yml, scripts/check-cs-env.js, scripts/check-ps-env.js
=> [NO-ISSUE] add check env is up also for CS ans PS

lib/content-services/content-node-share/content-node-share.dialog.html, lib/core/clipboard/clipboard.directive.ts, lib/core/datatable/components/datatable/json-cell.component.ts
Reverts Alfresco/alfresco-ng2-components#4623
=> Revert "[ADF-4405] [ADF-4423] Fix clipboard directive on json cell"

lib/core/userinfo/components/user-info.component.html, lib/core/userinfo/components/user-info.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4198
**Does this PR …
=> [ADF-4198] Core - fix user info close on esc key

e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts, e2e/process-services-cloud/task-list-properties.e2e.ts, e2e/process-services-cloud/taskListCloud.config.ts, e2e/process-services-cloud/tasks-custom-filters.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
=> [ADF-4310]Added sort tests for edit task filter cloud component

demo-shell/resources/i18n/en.json, demo-shell/src/app/components/cloud/cloud-settings.component.html, demo-shell/src/app/components/cloud/cloud-settings.component.ts, demo-shell/src/app/components/cloud/processes-cloud-demo.component.ts, demo-shell/src/app/components/cloud/services/cloud-layout.service.ts, e2e/content-services/document-list/document-list-properties.e2e.ts, e2e/pages/adf/contentServicesPage.ts, e2e/pages/adf/demo-shell/process-services/processCloudDemoPage.ts, e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts, e2e/process-services-cloud/process-list-selection-cloud.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
=> [ADF-4028][ADF-4047]Add process list cloud selection tests

e2e/pages/adf/demo-shell/process-services/taskDetailsCloudDemoPage.ts, e2e/process-services-cloud/task-form-cloud-component.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/public-api.ts, lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts
=> [ADF-4128]Add complete task tests

e2e/process-services-cloud/task-list-properties.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
=> [ADF-4388]Added edit task filter cloud component - taskId filter tests

demo-shell/src/app/app.module.ts, demo-shell/src/app/app.routes.ts, demo-shell/src/app/components/cloud/cloud-viewer.component.css, demo-shell/src/app/components/cloud/cloud-viewer.component.html, demo-shell/src/app/components/cloud/cloud-viewer.component.ts, demo-shell/src/app/components/cloud/task-details-cloud-demo.component.ts, e2e/process-services-cloud/start-process-cloud.e2e.ts, lib/core/form/components/widgets/core/form-field.model.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts, lib/process-services-cloud/src/lib/form/components/upload-cloud.widget.html, lib/process-services-cloud/src/lib/form/components/upload-cloud.widget.scss, lib/process-services-cloud/src/lib/form/components/upload-cloud.widget.ts, lib/process-services-cloud/src/lib/form/models/form-cloud.model.ts, lib/process-services-cloud/src/lib/form/services/form-cloud.service.spec.ts, lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
=> [ADF-4340] FormCloud - Be able to upload a file from the local source

lib/content-services/content-node-share/content-node-share.dialog.html, lib/core/clipboard/clipboard.directive.spec.ts, lib/core/clipboard/clipboard.directive.ts, lib/core/datatable/components/datatable/datatable-cell.component.ts, lib/core/datatable/components/datatable/json-cell.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4423
https://issues.alfresco.com/jira/browse/ADF-4405
Json …
=> [ADF-4405] [ADF-4423] Fix clipboard directive on json cell

docs/process-services-cloud/components/task-form-cloud.component.md
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4437
https://issues.alfresco.com/jira/browse/ADF-4445
The …
=> [ADF-4437][ADF-4445] Fix docs about Task Form Cloud component

e2e/core/auth-guard/auth-guard-sso.e2e.ts
> - [ ] Bugfix
Automation test for AuthGuard SSO …
=> [ADF-4407] Automate test for user without permission redirection

demo-shell/src/app/components/datatable/drag-and-drop/datatable-dnd.component.html, e2e/core/datatable/data-table-component.e2e.ts, e2e/pages/adf/demo-shell/dataTablePage.ts, e2e/pages/adf/navigationBarPage.ts
> - [ ] Bugfix
The header-drop and cell-drop events are triggered when a file is drag …
=> [ADF-4451] Automate Event handling during header row action.

lib/content-services/content-node-selector/content-node-selector-panel.component.scss, lib/content-services/upload/components/upload-drag-area.component.scss, lib/core/datatable/components/datatable/datatable.component.html, lib/core/datatable/components/datatable/datatable.component.scss, lib/core/layout/components/layout-container/layout-container.component.html, lib/core/layout/components/layout-container/layout-container.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4339
Improved the UI of the …
=> [ADF-4339] Fix documentList and ContentServices UI for IE11

demo-shell/src/app/components/template-list/template-demo.component.html, lib/core/datatable/components/datatable/datatable.component.html
> - [] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4434
The unnecessary icon …
=> [ADF-4434] Remove unnecessary icon in custom empty content template

demo-shell/src/app/components/cloud/task-details-cloud-demo.component.html, docs/process-services-cloud/components/task-form-cloud.component.md, lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.scss, lib/process-services-cloud/src/lib/styles/_index.scss, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.scss, lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.scss, lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4437
https://issues.alfresco.com/jira/browse/ADF-4445 …
=> [ADF-4445][ADF-4437] Add showRefreshButton to TaskFormCloud component doc

e2e/process-services-cloud/process-custom-filters.e2e.ts, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts
> - [ ] Bugfix
Uncomment test case
The test case excluded because it was failing in the pass, probably due to …
=> [ADF-4422] Fix unit/e2e tests

docs/process-services-cloud/components/process-list-cloud.component.md
=> [ADF-4429] Process List Cloud - Remove the pagination parameters.

docs/compatibility.md, docs/versionIndex.md
=> Compatibility matrix for ADF 3.2.

docs/release-notes/README.md, docs/release-notes/RelNote320.md
=> Release Note for ADF 3.2 (initial version)

docs/tutorials/activiti-7-and-adf.md
=> Activiti 7 and ADF tutorial review.

docs/release-notes/RelNote320.md
=> ADF 3.2 - Improve the release note with activiti features

demo-shell/package.json, lib/content-services/package.json, lib/core/package.json, lib/extensions/package.json, lib/insights/package.json, lib/process-services-cloud/package.json, lib/process-services/package.json, lib/testing/package.json, package.json
=> [3.2.0] pacakge.json update

demo-shell/src/app/components/notifications/notifications.component.html, demo-shell/src/app/components/notifications/notifications.component.ts, demo-shell/src/app/components/notifications/notifications.module.ts, lib/core/services/notification.service.ts, lib/core/styles/_index.scss, lib/core/styles/snackbar.scss
> - [ ] Bugfix
Add support for quick snackbar notifications with different styles …
=> [ADF-4484] Quick notifications

scripts/remove-alfresco-dependencies.sh
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4495
The remove alfresco dependencies script does not work …
=> [ADF-4495] Fix Remove dependencies script

lib/core/form/components/widgets/dropdown/dropdown.widget.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3192
**Does this PR …
=> [ADF-3192] Form - fix dropdown field alignment

scripts/check-activiti-env.js
=> Cloud script - Add users to the deploy phase

lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts, scripts/check-activiti-env.js
=> Cloud - Fix the context name

lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/people-cloud/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts, lib/process-services-cloud/src/lib/validators/numeric-field.validator.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4473
**Does this PR …
=> [ADF-4473] TaskCloud - add priority numeric validation

docs/release-notes/RelNote320.md
Better descriptions into the release notes about languages availability
> - [ ] Bugfix
N/A …
=> Better descriptions into the release notes

docs/compatibility.md, docs/versionIndex.md
=> Minor changes to documentation for ADF 3.2.1.

demo-shell/src/app/components/files/files.component.ts
> - [ ] Bugfix
add a snackbar to demo shell for metadata errors (`/files` demo only) …
=> [ADF-4489] metadata errors demoshell

lib/core/context-menu/context-menu-overlay.service.spec.ts, lib/core/context-menu/context-menu-overlay.service.ts
> - [ ] Bugfix
[ADF-4545](https://issues.alfresco.com/jira/browse/ADF-4545)
**Does …
=> [ADF-4545] Context Menu - RTL support

demo-shell/src/app.config.json, docs/core/components/language-menu.component.md, lib/core/language-menu/language-menu.component.html, lib/core/language-menu/language-menu.component.spec.ts, lib/core/language-menu/language-menu.component.ts, lib/core/language-menu/language.interface.ts
> - [ ] Bugfix
[ADF-4543](https://issues.alfresco.com/jira/browse/ADF-4543)
**Does …
=> [ADF-4543] Language Menu - set layout orientation

demo-shell/src/app/components/cloud/start-process-cloud-demo.component.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4389
**Does this PR …
=> [ADF-4389] StartProcessCloud - add validation for processName

lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts, lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.html, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4471
**Does this PR …
=> [ADF-4471] TaskCloud - disable editable fields when the task is unclaimed

lib/core/form/components/widgets/amount/amount.widget.html, lib/core/form/components/widgets/checkbox/checkbox.widget.html, lib/core/form/components/widgets/container/container.widget.html, lib/core/form/components/widgets/content/content.widget.html, lib/core/form/components/widgets/date-time/date-time.widget.html, lib/core/form/components/widgets/date/date.widget.html, lib/core/form/components/widgets/display-text/display-text.widget.html, lib/core/form/components/widgets/dropdown/dropdown.widget.html, lib/core/form/components/widgets/dynamic-table/dynamic-table.widget.html, lib/core/form/components/widgets/functional-group/functional-group.widget.html, lib/core/form/components/widgets/hyperlink/hyperlink.widget.html, lib/core/form/components/widgets/multiline-text/multiline-text.widget.html, lib/core/form/components/widgets/number/number.widget.html, lib/core/form/components/widgets/people/people.widget.html, lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.html, lib/core/form/components/widgets/tabs/tabs.widget.html, lib/core/form/components/widgets/text/text.widget.html, lib/core/form/components/widgets/typeahead/typeahead.widget.html, lib/core/form/components/widgets/upload-folder/upload-folder.widget.html, lib/core/form/components/widgets/upload/upload.widget.html, lib/process-services-cloud/src/lib/form/components/upload-cloud.widget.html
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4521
**Does this PR …
=> [ADF-4521] Form - Multilingual support

e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
=> [ADF-4538] Fix start-task-custom-app-cloud.e2e.ts

lib/process-services/form/start-form.component.spec.ts
=> [NO_ISSUE] - fix unit test on process-services

e2e/process-services-cloud/task-list-properties.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
=> [ADF-4540] Fix task-list-properties.e2e.ts

e2e/process-services-cloud/task-form-cloud-component.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
=> [ADF-4541] Fix task-form-cloud-component.e2e.ts

demo-shell/src/app.config.json
> - [x] Bugfix
[ADF-4578](https://issues.alfresco.com/jira/browse/ADF-4578)
**Does …
=> [ADF-4578] DemoShell - language menu shows 2 Arabic entries

scripts/affected-folder.sh, scripts/affected-libs.sh, scripts/check-branch-updated.sh, scripts/smart-build.sh
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4569
The script does not stop when the PR needs to be …
=> [ADF-4569] Fix affected-libs.sh script

scripts/affected-folder.sh, scripts/affected-libs.sh, scripts/check-branch-updated.sh
> - [x] Bugfix
The script was not adding the dependencies in deps.txt
**Does this PR …
=>  Improve Rebase branch script

e2e/pages/adf/demo-shell/process-services/peopleGroupCloudComponentPage.ts, e2e/process-services-cloud/people-group-cloud-component.e2e.ts
=> [ADF-4535] Fix people-group-cloud-component.e2e.ts

lib/core/layout/components/header/header.component.scss
> - [x] Bugfix
[ADF-4584](https://issues.alfresco.com/jira/browse/ADF-4584)
**Does …
=> [ADF-4584] Header RTL styling

e2e/test.config.js, lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts, lib/testing/src/lib/core/actions/identity/tasks.service.ts, lib/testing/src/lib/core/utils/file-browser.util.ts, scripts/check-env/check-activiti-env.js
=> Remove the dependency with TestConfig

scripts/test-e2e-lib.sh
> - [ ] Bugfix
Adding a debug option to the test script. …
=> Adding debug option to test script

e2e/test.config.js, lib/testing/src/lib/test.configuration.ts, lib/testing/src/public-api.ts
> - [ ] Bugfix
typed interface for test configuration 
should allow passing test …
=> typed interface for test configuration

e2e/core/user-info-component-cloud.e2e.ts, e2e/lite-server-proxy.js, e2e/proxy.conf.js, e2e/restAPI/APIUtil.js, e2e/test.config.js, protractor.conf.js, scripts/travis/e2e/content-services-e2e.sh, scripts/travis/e2e/core-e2e.sh, scripts/travis/e2e/insights-e2e.sh, scripts/travis/e2e/process-services-cloud-e2e.sh, scripts/travis/e2e/process-services-e2e.sh, scripts/travis/e2e/search-e2e.sh
=> [ADF-4587] Fix e2e tests

e2e/content-services/document-list/document-list-pagination.e2e.ts
=> Making C260107 more stable

demo-shell/src/app/components/app-layout/app-layout.component.ts, lib/core/services/user-preferences.service.spec.ts, lib/core/services/user-preferences.service.ts
> - [ ] Bugfix
[ADF-4582](https://issues.alfresco.com/jira/browse/ADF-4582)
**Does …
=> [ADF-4582] User preference - set layout orientation based on locale

demo-shell/src/app.config.json, e2e/content-services/document-list/document-list-copy-move.e2e.ts, e2e/content-services/permissions/site-permissions.e2e.ts, e2e/content-services/tag-component.e2e.ts, e2e/core/datatable/data-table-component.e2e.ts, e2e/process-services-cloud/task-header-cloud.e2e.ts, lib/testing/src/lib/core/pages/data-table-component.page.ts, package-lock.json, scripts/test-e2e-lib.sh
=> [ADF-4547] Fixing flaky tests

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4530
**Does this PR …
=> [ADF-4530] StartProcessCloud - fix show process definition dropdown

e2e/process-services-cloud/process-filters-cloud.e2e.ts, e2e/process-services-cloud/task-form-cloud-component.e2e.ts
> - [ ] Bugfix
Disabling failing tests …
=> Skip failing tests

scripts/npm-build-all.sh
> - [ ] Bugfix
fix & improve build stage - linting
fix the bug with the missing $ sign …
=> [ADF-4612] fix linting on npm-build-all script

e2e/content-services/tag-component.e2e.ts
> - [ ] Bugfix
Disabling tag-component failing tests …
=> Disable tag-component test

demo-shell/src/app/components/trashcan/trashcan.component.html, demo-shell/src/app/components/trashcan/trashcan.component.scss, lib/core/datatable/components/datatable/datatable.component.scss, lib/core/layout/components/layout-container/layout-container.component.scss
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4466
The checkboxes in …
=> [ADF-4466] Fix alignment issues - IE11

e2e/content-services/comments/comment-component.e2e.ts, e2e/process-services-cloud/apps-section-cloud.e2e.ts, lib/testing/README.md, protractor.conf.js, scripts/affected-libs.sh, scripts/test-e2e-lib.sh, scripts/travis/e2e/content-services-e2e.sh, scripts/travis/e2e/core-e2e.sh, scripts/travis/e2e/insights-e2e.sh, scripts/travis/e2e/process-services-cloud-e2e.sh, scripts/travis/e2e/process-services-e2e.sh, scripts/travis/e2e/search-e2e.sh
> - [ ] Bugfix
- remove the skip lint 
- ability to run specs
- affected e2e-cloud …
=> CI - Ability to run only e2e cloud in case is the only affected folder

lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4598
**Does this PR …
=> [ADF-4598] StartTask - revert start task assignee and candidateGroups validations

e2e/process-services-cloud/edit-task-filters-component.e2e.ts, e2e/process-services-cloud/task-form-cloud-component.e2e.ts, e2e/process-services-cloud/task-header-cloud.e2e.ts
=> [ADF-4477]Add a new check related to endDate

docs/upgrade-guide/upgrade26-30.md, docs/upgrade-guide/upgrade30-31.md, docs/upgrade-guide/upgrade31-32.md
=> Update of upgrade paths.

lib/process-services-cloud/src/lib/form/components/dropdown-cloud/dropdown-cloud.widget.html, lib/process-services-cloud/src/lib/form/components/dropdown-cloud/dropdown-cloud.widget.spec.ts, lib/process-services-cloud/src/lib/form/components/dropdown-cloud/dropdown-cloud.widget.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts, lib/process-services-cloud/src/lib/form/form-cloud.module.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4586
**Does this PR …
=> [ADF-4586] - fix preselecting value for DropdownCloud

demo-shell/src/app/components/cloud/task-details-cloud-demo.component.html, demo-shell/src/app/components/cloud/task-details-cloud-demo.component.ts, lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html, lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-form/task-form.module.ts
> - [ ] Bugfix
* Action buttons (claim/release/complete) are not refreshed upon completion of an action 
* Task form …
=> [ADF-4544] Cloud Task From - Refresh the buttons and form after an action is complete

lib/core/form/components/form-base.component.ts, lib/core/form/components/widgets/date/date.widget.spec.ts, lib/core/form/components/widgets/date/date.widget.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts, lib/process-services/form/form.component.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4443
**Does this PR …
=> [ADF-4461] FormCloud - fix date validations

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts, lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4530
**Does this PR …
=> [ADF-4530] StartTaskCloud - fix process definition list for empty names

e2e/content-services/tag-component.e2e.ts, e2e/pages/adf/tagPage.ts
=> [ADF-4613] Fixing tag-component.e2e.ts

lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
> - [] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4527
**Does this PR …
=> [ADF-4527] Fix buttons duplication error in taskFormCloudComponent

lib/content-services/search/components/animations.ts, lib/content-services/search/components/search-control.component.html, lib/content-services/search/components/search-control.component.scss, lib/content-services/search/components/search-control.component.spec.ts, lib/content-services/search/components/search-control.component.ts
> - [x] Bugfix
[ADF-4625](https://issues.alfresco.com/jira/browse/ADF-4625)
**Does …
=> [ADF-4625] Search Input does not respect RTL mode

lib/content-services/breadcrumb/dropdown-breadcrumb.component.scss
> - [x] Bugfix
[ADF-4626](https://issues.alfresco.com/jira/browse/ADF-4626)
**Does …
=> [ADF-4626] Breadcrumb - directionality styling

lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts, lib/process-services-cloud/src/lib/form/components/upload-cloud.widget.ts, lib/process-services-cloud/src/lib/form/models/form-cloud.model.ts, lib/process-services-cloud/src/lib/form/models/task-variable-cloud.model.ts, lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
> - [ ] Bugfix
The file is uploaded based on the hostECM
The content is picked from …
=> [ADF-4550] Form Cloud - Be able to upload a file on the content taken from the process-storage

docs/user-guide/rtl-support.md
> - [ ] Bugfix
[ADF-4618](https://issues.alfresco.com/jira/browse/ADF-4618)
**Does …
=> [ADF-4618] RTL languages support documentation

e2e/process-services-cloud/tasks-custom-filters.e2e.ts
=> [ADF-4034]Add test for delete standalone task and cancelled process.

e2e/process-services-cloud/task-list-properties.e2e.ts
> - [ ] Bugfix
Modified excluded e2e tests in order to not fail
https://issues.alfresco.com/jira/browse/ADF-4421 …
=> [ADF-4421] Fix excluded tests in task filters

e2e/process-services-cloud/task-list-properties.e2e.ts
Reverts Alfresco/alfresco-ng2-components#4721
=> Revert "[ADF-4421] Fix excluded tests in task filters"

e2e/process-services-cloud/task-list-properties.e2e.ts
> - [ ] Bugfix
Fix excluded e2e tests
https://issues.alfresco.com/jira/browse/ADF-4421 …
=> [ADF-4421] Fix excluded tests

lib/core/services/auth-guard-sso-role.service.ts, lib/core/services/auth-guard.service.spec.ts, lib/core/services/auth-guard.service.ts, scripts/i18n/extract-langs.sh
> - [ ] Bugfix
How to reproduce:
Behavior 1
UserA logs in Tab1
UserB logs in Tab2
Current behavior the user in Tab 1 will not be able to perform any action and will be redirected to the login …
=> [ADF-4637] logout cross tabs event

lib/core/datatable/components/datatable/datatable.component.scss, lib/process-services-cloud/src/lib/task/start-task/components/start-task-cloud.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4596
https://issues.alfresco.com/jira/browse/ADF-4137 …
=> [ADF-4636][ADF-4137][ADF-4596] Datatable and Assignee minor bugs

demo-shell/src/app.config.json, demo-shell/src/app/components/cloud/start-process-cloud-demo.component.html, demo-shell/src/app/components/cloud/start-process-cloud-demo.component.ts, docs/process-services-cloud/components/start-process-cloud.component.md, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts, lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts, lib/process-services-cloud/src/lib/process/start-process/models/process-definition-cloud.model.ts, lib/process-services-cloud/src/lib/process/start-process/models/process-payload-cloud.model.ts, lib/process-services-cloud/src/lib/process/start-process/start-process-cloud.module.ts
Ability to pre-fill a form with values
Ability to send variables
> - [ ] Bugfix
not able to start a process with a …
=> [ADF-4631] Start Process Cloud - Add the start form as part of a process

demo-shell/src/app/app.component.scss, lib/content-services/content-node-selector/content-node-selector-panel.component.scss, lib/content-services/content-node-selector/name-location-cell/name-location-cell.component.ts, lib/content-services/document-list/components/document-list.component.scss, lib/content-services/document-list/components/document-list.component.ts, lib/core/datatable/components/datatable/datatable.component.scss, lib/core/toolbar/toolbar.component.scss
> - [x] Bugfix
> - [x] Other... Please describe: style fixes
https://issues.alfresco.com/jira/browse/ADF-4426
Get the …
=> [ADF-4426] Move CSS overrides from ACA to ADF - 2nd round

demo-shell/src/app/app.module.ts, lib/core/core.module.ts
> - [x] Bugfix
The required localization file is a competence of the app
**Does this …
=> Move localisation file date in the app shell

demo-shell/src/app/components/files/files.component.ts, e2e/content-services/share-file/unshare-file.e2e.ts, lib/content-services/content-node-share/content-node-share.dialog.html, lib/content-services/content-node-share/content-node-share.dialog.ts, lib/content-services/content-node-share/content-node-share.directive.ts, lib/content-services/content-node-share/content-node-share.settings.ts
> - [x] Bugfix
Notes: these are the extra code changes on top of the …
=> [ADF-4640] share dialog fixes

lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
> - [x] Bugfix
Steps to reproduce the issue:
Create a task with a form
Navigate to the active task
Current behaviour:
Form is not displayed.
Expected behavior:
Form is displayed.
**Does this PR …
=> [ADF-4651] fix task form cloud

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts, lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
=> [ADF-4461] Start Process - Fix issue form and validation

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
> - [x] Bugfix
Start process cloud buttons not aligned to the right
https://issues.alfresco.com/jira/browse/ADF-4661 …
=> [REGRESSION] [ADF-4661] Fix Start Process Cloud Layout

lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts, lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts, lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts, lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts, lib/process-services-cloud/src/lib/process/start-process/models/process-payload-cloud.model.ts
=> [ADF-4631] Start Process Cloud - Fix start process form validation

lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
[ADF-4667](https://issues.alfresco.com/jira/browse/ADF-4667)
**Does …
=> [ADF-4667] Document list - sorting icon RTL fix

e2e/process-services-cloud/task-list-properties.e2e.ts
> - [ ] Bugfix
Change incorrect e2e test id …
=> Change incorrect e2e test id

lib/process-services-cloud/src/lib/form/models/form-cloud.model.ts
=> [ADF-4674] Cloud Add the default validation array

docs/core/services/jwt-helper.service.md, docs/license-info/license-info-v3.3.0.md, docs/process-services-cloud/services/task-filter-cloud.service.md, docs/release-notes/README.md, docs/release-notes/RelNote320.md, docs/release-notes/RelNote330.md, docs/versionIndex.md
=> [ADF-4656] Release note for ADF 3.3 in draft.

demo-shell/src/app.config.json, docs/core/pipes/localized-date.pipe.md, docs/user-guide/internationalization.md, docs/user-guide/localization.md, lib/core/card-view/models/card-view-datetimeitem.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4680
Add missing …
=> [ADF-4680] Add documentation for dateValues in app.config.json

lib/process-services-cloud/package.json, lib/process-services-cloud/src/lib/form/form-cloud.module.ts
> - [x] Bugfix
*  Added missing peer dependency in process-cloud-services
**Does this …
=> [ADF-dev-0000]  Added missing peer dependency in process-cloud-services

lib/process-services-cloud/package.json, lib/process-services-cloud/src/lib/form/form-cloud.module.ts
> - [x] Bugfix
* Added missing peer dependency in process-cloud-services
**Does this …
=> [ADF-Master] Added missing peer dependency in process-cloud-services

demo-shell/resources/i18n/da.json, demo-shell/resources/i18n/sv.json, lib/content-services/i18n/da.json, lib/content-services/i18n/sv.json, lib/core/form/components/widgets/core/form-field.model.ts, lib/core/i18n/da.json, lib/core/i18n/sv.json, lib/process-services-cloud/package.json, lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/form/form-cloud.module.ts, lib/process-services-cloud/src/lib/i18n/sv.json, lib/process-services/i18n/sv.json
=> 3.3.0 update

e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts
=> [ADF-4593] Fixing skipped tests in Start Task Cloud

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4642
Missing test
This test …
=> [ADF-4642] Add typeahead unit test for start process cloud component

e2e/process-services-cloud/process-custom-filters.e2e.ts
=> Enabled process-custom-filters-test

e2e/pages/adf/demo-shell/process-services-cloud/processDetailsCloudDemoPage.ts, e2e/process-services-cloud/config/start-process-cloud.config.ts, e2e/process-services-cloud/start-process-cloud.e2e.ts, e2e/process-services-cloud/start-task-form-cloud.e2e.ts, lib/testing/src/lib/core/pages/form/widgets/numberWidget.ts, lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
=> [ADF-4448] Automate Start and Save a task with a form.

e2e/process-services-cloud/config/edit-process-filter.config.ts, e2e/process-services-cloud/process-filter-results.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
=> [ADF-4026] - automate process filter results check

lib/content-services/content-node-selector/content-node-selector-panel.component.spec.ts, lib/content-services/content-node-selector/content-node-selector.service.spec.ts, lib/content-services/content-node-selector/content-node-selector.service.ts
> - [x] Bugfix
https://github.com/Alfresco/alfresco-ng2-components/issues/4821
**Does …
=> [ADF-4707] add properties in node selector search

cspell.json, demo-shell/src/app/components/file-view/file-view.component.html, e2e/process-services-cloud/apps-section-cloud.e2e.ts, e2e/process-services-cloud/edit-process-filters-component.e2e.ts, e2e/process-services-cloud/edit-task-filters-component.e2e.ts, e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts, e2e/process-services-cloud/people-group-cloud-component.e2e.ts, e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts, e2e/process-services-cloud/process-custom-filters.e2e.ts, e2e/process-services-cloud/process-filter-results.e2e.ts, e2e/process-services-cloud/process-filters-cloud.e2e.ts, e2e/process-services-cloud/process-header-cloud.e2e.ts, e2e/process-services-cloud/process-list-cloud-component.e2e.ts, e2e/process-services-cloud/process-list-selection-cloud.e2e.ts, e2e/process-services-cloud/start-process-cloud.e2e.ts, e2e/process-services-cloud/start-task-custom-app-cloud.e2e.ts, e2e/process-services-cloud/start-task-form-cloud.e2e.ts, e2e/process-services-cloud/task-filters-cloud.e2e.ts, e2e/process-services-cloud/task-header-cloud.e2e.ts, e2e/process-services-cloud/task-list-properties.e2e.ts, e2e/process-services-cloud/task-list-selection.e2e.ts, e2e/process-services-cloud/tasks-custom-filters.e2e.ts, lib/testing/src/lib/core/actions/identity/applications.service.ts, lib/testing/src/lib/core/actions/identity/identity.service.ts, lib/testing/src/lib/core/actions/identity/public-api.ts, lib/testing/src/lib/process-services-cloud/app/app-list-cloud.page.ts
=> [ADF-4576]Add new tests for application cloud component

e2e/process-services-cloud/task-header-cloud.e2e.ts
=> [ADF-4687] should pick up default date format from the app config

lib/core/login/components/login.component.spec.ts
> - [x] Bugfix
remove login unit test failing call in the network using the spy
**Does …
=> fix login unit test to nit emit error in the network

e2e/content-services/metadata/metadata-smoke-tests.e2e.ts, e2e/process-services-cloud/process-filter-results.e2e.ts, e2e/process-services/process-instance-details.e2e.ts, e2e/process-services/task-details.e2e.ts, e2e/util/constants.js, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts, lib/testing/src/lib/process-services-cloud/actions/process-instances.service.ts, scripts/travis/e2e/process-services-cloud-e2e.sh
> - [x] Bugfix
Random failing test:
```
1) Process filters cloud [C306892] Should be able to filter by process status …
```
=> [ADF-4715][ADF-4717] fix process-filter-results random failing tests

demo-shell/src/app/components/cloud/community/community-task-details-cloud.component.scss, demo-shell/src/app/components/cloud/task-details-cloud-demo.component.scss, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.html
> - [x] Bugfix
Fix the typo in the CSS class name …
=> fix css class name typo

lib/testing/src/lib/core/pages/login-sso.page.ts
=> Changes required to adf-testing

e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts, e2e/process-services-cloud/task-list-selection.e2e.ts, package-lock.json
=> [C297472] Should be able to see selected tasks

lib/core/form/components/widgets/core/form-field.model.spec.ts, lib/core/form/components/widgets/core/form-field.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4720
**Does this PR …
=> [ADF-4720] FormFieldModel fix error when has no variables

lib/core/about/about.component.ts
=> [ADF-4729] AboutComponent - Read the versions.json from the relative path

lib/core/login/components/login.component.html, lib/core/login/components/login.component.ts, lib/core/services/sites.service.spec.ts
> - [x] Bugfix
Clean unit test :
- Login 
- Site …
=> Clean unit test in login component and site

e2e/process-services/dynamic-table-date-picker.e2e.ts, lib/core/form/components/widgets/dynamic-table/date-cell-validator-model.ts, lib/core/form/components/widgets/dynamic-table/editors/date/date.editor.html, lib/core/form/components/widgets/dynamic-table/editors/date/date.editor.spec.ts, lib/core/form/components/widgets/dynamic-table/editors/date/date.editor.ts
> - [x] Bugfix
1. Allow the user to remove date if it is not mandatory
2. Shows correct date when we view a row
3. Able to remove existing date (if it is not …
=> [ADF-4716] Dynamic Table not working properly (regression)

lib/core/layout/components/layout-container/layout-container.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4732
allow folder names …
=> [ADF-4732] ellipsis fix

demo-shell/src/app/components/files/files.component.html, e2e/content-services/directives/edit-folder-directive.e2e.ts, e2e/content-services/directives/favorite-directive.e2e.ts, e2e/content-services/directives/favourite-directive.e2e.ts, e2e/pages/adf/contentServicesPage.ts, e2e/pages/adf/demo-shell/customSourcesPage.ts, e2e/pages/adf/trashcanPage.ts, lib/testing/src/lib/core/pages/data-table-component.page.ts
=> e2e tests for favourite directive

lib/cli/README.md, lib/cli/scripts/docker-publish.ts
add the tag to the docker image
publish the docker image
clean the docker image
> - [ ] Bugfix …
=> [ADF-4733] Adf-cli - Add basic readme to run the docker publish with or without login

lib/cli/scripts/docker-publish.ts
=> [ADF-4733]AdfCli - Fix typo on docker -f command

cspell.json, e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts, e2e/process-services-cloud/process-custom-filters.e2e.ts, e2e/process-services-cloud/process-filter-results.e2e.ts, e2e/process-services-cloud/process-filters-cloud.e2e.ts, e2e/process-services-cloud/process-list-cloud-component.e2e.ts, e2e/process-services-cloud/process-list-selection-cloud.e2e.ts, e2e/process-services-cloud/start-task-form-cloud.e2e.ts, e2e/process-services-cloud/task-form-cloud-component.e2e.ts, e2e/process-services-cloud/task-list-properties.e2e.ts, e2e/process-services-cloud/tasks-custom-filters.e2e.ts, e2e/util/resources.js, lib/core/layout/components/layout-container/layout-container.component.scss, package.json, scripts/build/build-all-lib.sh
… name
> - [ ] Bugfix
- Refactor e2e PS-Cloud
- add sleep before query
**Does this PR …
=> Refactor e2e PS-Cloud and add sleep before query

e2e/content-services/directives/restore-content-directive.e2e.ts, e2e/pages/adf/contentServicesPage.ts, e2e/pages/adf/trashcanPage.ts, lib/testing/src/lib/core/pages/data-table-component.page.ts, lib/testing/src/lib/core/utils/browser-actions.ts
=> restore content directive e2e tests

demo-shell/package.json, lib/cli/package.json, lib/content-services/package.json, lib/core/package.json, lib/extensions/package.json, lib/insights/package.json, lib/process-services-cloud/package.json, lib/process-services/package.json, lib/testing/package.json, package.json
Update ADF packages version 3.4.0-beta8
=> Update ADF packages version 3.4.0-beta8

lib/content-services/document-list/data/share-datatable-adapter.spec.ts, lib/content-services/document-list/services/document-actions.service.spec.ts, lib/content-services/document-list/services/document-list.service.spec.ts, lib/content-services/document-list/services/folder-actions.service.spec.ts, lib/core/directives/check-allowable-operation.directive.spec.ts, lib/core/services/content.service.spec.ts, lib/core/services/content.service.ts, lib/core/services/download.service.spec.ts, lib/core/services/download.service.ts, lib/core/services/public-api.ts, lib/core/services/thumbnail.service.spec.ts, lib/core/services/thumbnail.service.ts, lib/core/userinfo/services/ecm-user.service.spec.ts, lib/core/userinfo/services/ecm-user.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4647
- split Download …
=> [ADF-4647] download service

lib/process-services/form/start-form.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4650
Minor css change to …
=> [ADF-4650] Fix RTL view for  form validation icon

lib/core/i18n/en.json, lib/core/viewer/components/unknown-format/unknown-format.component.html, lib/core/viewer/components/viewer.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4480
If after 20 secs the …
=> [ADF-4480] Change Viewer behaviour when opening unsupported files

e2e/content-services/sso/sso-download-directive-component.e2e.ts, e2e/core/auth-guard/auth-guard-sso.e2e.ts, e2e/core/login/login-sso/login-sso.e2e.ts, e2e/core/user-info-component-cloud.e2e.ts, e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts, e2e/process-services-cloud/people-group-cloud-component.e2e.ts, e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts, e2e/process-services-cloud/process-filter-results.e2e.ts, e2e/process-services-cloud/start-task-form-cloud.e2e.ts, e2e/test.config.js
> - [ ] Bugfix
ClientId shouldn't be in the config file …
=> [ADF-4259] ClientId shouldn't be in the config file

demo-shell/src/app/app.module.ts, demo-shell/src/app/components/cloud/task-details-cloud-demo.component.html, demo-shell/src/app/components/cloud/task-details-cloud-demo.component.ts
=> [ADF-4471]Reload task header after claim/unclaim

e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts, e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts
> - [ ] Bugfix
Automation for Start Task - Group Cloud Component
**Does this PR …
=> [ADF-3993] Automation for Start Task - Group Cloud

lib/content-services/document-list/components/document-list.component.spec.ts, lib/content-services/karma.conf.js
> - [ ] Bugfix
Clean unit tedt Content service log from 404 spy missing
**Does this PR …
=> fix cs document list unit test spy

e2e/process-services-cloud/form-field/visibility-condition.e2e.ts, e2e/resources/forms/checkbox-visibility-condition.ts
=> [ADF-4747]Change the old VisibilityCondition format with the new one in e2e tests

lib/cli/README.md, lib/cli/scripts/kubectl-image.ts
=> [ADF-4733] AdfCli - Kubectl-image add option to install the kubectl

e2e/pages/adf/process-services/processDetailsPage.ts, e2e/pages/adf/process-services/startProcessPage.ts, e2e/process-services/start-process-component.e2e.ts, lib/process-services/process-list/components/process-instance-tasks.component.html, lib/testing/src/lib/core/pages/form/widgets/dateWidget.ts, lib/testing/src/lib/process-services/pages/start-process-dialog.page.ts
=> [ADF-4682]The Date is not saved correctly on Process-services form

lib/testing/src/lib/core/pages/data-table-component.page.ts, lib/testing/src/lib/core/utils/browser-actions.ts
=> Add rightclick method to browseractions

lib/testing/src/lib/core/pages/data-table-component.page.ts
=> Added the rightclick method to DataTableComponentPage

lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts, lib/core/card-view/models/card-view-dateitem.model.ts, lib/core/pipes/localized-date.pipe.spec.ts, lib/core/pipes/localized-date.pipe.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4684
Displayed date is …
=>  [ADF-4684] Content Metadata Card dates should be localised

scripts/travis/update/update-children.sh, scripts/travis/update/update-project.sh
> - [ ] Bugfix
The update scripts needs to check the JS-API version that could beb different from the core
**What is …
=> update project script possible different JS-API

lib/cli/scripts/kubectl-image.ts, lib/process-services-cloud/package-lock.json
=> AdfCli - k8s use a variable as serviceName

lib/cli/README.md, lib/cli/scripts/update-version.ts
=> [ADF-4757] adf-cli - Add the update version command

lib/cli/scripts/update-version.ts
=> adf-cli - Improve the regexp to cover corner cases

e2e/process-services-cloud/people-group-cloud-component.e2e.ts, e2e/process-services/form-component.e2e.ts, e2e/process-services/widgets/date-time-widget.e2e.ts, e2e/process-services/widgets/date-widget.e2e.ts, lib/core/form/components/widgets/amount/amount.widget.html, lib/core/form/components/widgets/amount/amount.widget.scss, lib/core/form/components/widgets/date-time/date-time.widget.scss, lib/core/form/components/widgets/date/date.widget.scss, lib/testing/src/lib/core/pages/form/formPage.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4650
The amount widget had the styles hardcoded
**What is …
=> [ADF-4650] Fix and refactor amount, date and date-time widgets

lib/cli/scripts/kubectl-delete.ts
=> AdfCli - Expose a kubectl command to delete pods

lib/core/form/components/widgets/core/form-field-types.ts, lib/core/form/components/widgets/core/form-field.model.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4760
**Does this PR …
=> [ADF-4760] - fix task form completion with a header field

lib/core/form/services/widget-visibility-cloud.service.spec.ts, lib/core/form/services/widget-visibility.service.spec.ts, lib/core/form/services/widget-visibility.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4758
**Does this PR …
=> [ADF-4758] - reset form value when field is not visible

demo-shell/package.json, lib/cli/package.json, lib/content-services/package.json, lib/core/package.json, lib/extensions/package.json, lib/insights/package.json, lib/process-services-cloud/package.json, lib/process-services/package.json, lib/testing/package.json, package.json
Update ADF packages version 3.4.0-beta15
=> Update ADF packages version 3.4.0-beta15

lib/core/form/services/widget-visibility-cloud.service.spec.ts, lib/core/form/services/widget-visibility.service.spec.ts, lib/core/form/services/widget-visibility.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4774
**Does this PR …
=> [ADF-4774] - fix visibility condition between checkbox fields

package-lock.json, package.json
=> Fix the vulnerabilities ADF 3.4.0

lib/core/form/services/widget-visibility-cloud.service.spec.ts, lib/core/form/services/widget-visibility.service.spec.ts, lib/core/form/services/widget-visibility.service.ts, lib/core/mock/form/widget-visibility-cloud.service.mock.ts, lib/core/mock/form/widget-visibility.service.mock.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4782
**Does this PR …
=> [ADF-4782] VisibilityConditions - fix chaining conditions

demo-shell/src/app/components/process-service/process-service.component.scss, lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts, lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4755
**Does this PR …
=> [DW-4755] [CardViewDateComponent] Provide a way to reset date value.

demo-shell/package.json, lib/cli/package.json, lib/content-services/package.json, lib/core/form/services/widget-visibility-cloud.service.spec.ts, lib/core/form/services/widget-visibility.service.spec.ts, lib/core/form/services/widget-visibility.service.ts, lib/core/package.json, lib/extensions/package.json, lib/insights/package.json, lib/process-services-cloud/package.json, lib/process-services/package.json, lib/testing/package.json, package.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4797
**Does this PR …
=> [ADF-4797] - fix null value for display text when the field it's not visible

lib/content-services/breadcrumb/breadcrumb.component.html, lib/content-services/i18n/en.json
> - [x] Bugfix
[ADF-4497](https://issues.alfresco.com/jira/browse/ADF-4497)
**Does …
=> [ADF-4497] ARIA role must be appropriate for the Breadcrumb element

lib/core/i18n/en.json, lib/core/login/components/login.component.html, lib/core/login/components/login.component.spec.ts, lib/core/login/components/login.component.ts, lib/testing/src/lib/core/pages/login.page.ts
> - [x] Bugfix
[ADF-4802](https://issues.alfresco.com/jira/browse/ADF-4802)
**Does …
=> [ADF-4802] Login accessibility	

.travis.yml
> - [ ] Bugfix
The release and tag is a manual activiti
When master got merged the …
=> CI/CD Improvement - Create a release with tag when we merge master

lib/core/datatable/components/datatable/datatable.component.html, lib/core/i18n/en.json
> - [x] Bugfix
[ADF-4830](https://issues.alfresco.com/jira/browse/ADF-4830)
**Does …
=> [ADF-4830] DocumentList - sort state is not being announced

angular.json, demo-shell/src/app/components/about/about.component.html, demo-shell/src/app/components/about/about.component.ts, demo-shell/tsconfig.json, lib/core/about/about.component.html, lib/core/about/about.component.ts, lib/core/i18n/en.json, package.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4816
Refactor About …
=> [ADF-4816] Refactor About component

lib/cli/README.md, lib/cli/scripts/npm-publish.ts
=> [ADF-4833] Adf-cli - Add the npm publish command

.travis.yml
=> [ADF-4834] Travis CI/CD - Add step to publish alpha on npm

e2e/core/card-view/card-view-component.e2e.ts, e2e/pages/adf/cardViewComponentPage.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4799
https://issues.alfresco.com/jira/browse/ADF-4801 …
=> [ADF-4799][ADF-4801] Automation tests for CardView clear date field and selectbox None option

lib/core/datatable/components/datatable/datatable.component.html
> - [x] Bugfix
[ADF-4832](https://issues.alfresco.com/jira/browse/ADF-4832)
**Does …
=> [ADF-4832] DocumentList - Selected state is not being conveyed to screen reader user

lib/content-services/permission-manager/components/add-permission/add-permission.component.ts
**Note:** Tests and docs should not be necessary. Further, all existing tests finish successfully.
<br/>
> - [x] Bugfix
**What is the current behaviour?** (You can also link to an open issue …
=> [ADF-4976] Fix variable being referenced before initialization

e2e/process-services-cloud/form-field/visibility-condition.e2e.ts, e2e/resources/forms/checkbox-visibility-condition.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/APM-1259
**Does this PR …
=> [ADF-4837] - Add Checkbox visibility e2e tests

lib/content-services/permission-manager/components/permission-list/permission-list.component.scss, lib/core/datatable/components/datatable/datatable.component.scss
> - [ ] Bugfix
> - [x] Other... Please describe: new scss variables
https://issues.alfresco.com/jira/browse/ADF-4846 …
=> [ADF-4846] Move to ADF the style overrides from ACA

docs/user-guide/extensibility.md
removed the word 'a'.
> - [ ] Bugfix …
=> Propose a correction to what appears to be a minor typo

e2e/content-services/document-list/document-list-actions.e2e.ts, e2e/pages/adf/content-services/breadcrumb/breadCrumbDropdownPage.ts, e2e/pages/adf/demo-shell/dataTablePage.ts, lib/testing/ng-package.json, lib/testing/src/lib/content-services/pages/document-list.page.ts, lib/testing/src/lib/core/pages/data-table-component.page.ts, lib/testing/src/lib/core/pages/login-sso.page.ts, lib/testing/src/lib/core/utils/browser-actions.ts, scripts/travis/build/build.sh
> - [ ] Bugfix
One test in e2e CS is failing because a wrong query xpath
**Does this …
=> fix content service document list action test

e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts, e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts, lib/core/userinfo/services/identity-user.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4847
The existing api call …
=> [ADF-4847] Not able to find any user in Assignee field when creating a task

lib/content-services/document-list/components/library-name-column/library-name-column.component.ts, lib/content-services/document-list/components/name-column/name-column.component.ts, lib/content-services/i18n/en.json
> - [x] Bugfix
[ADF-4839](https://issues.alfresco.com/jira/browse/ADF-4839)
**Does …
=> [ADF-4839] Document List - column name link accessibility

e2e/process-services-cloud/task-form-cloud-component.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts
> - [ ] Bugfix
Automation test for form buttons refresh after action
**Does this PR …
=> [ADF-4544] Automation for form button refresh after action

lib/content-services/upload/components/file-uploading-dialog.component.html
> - [x] Bugfix
[ADF-4845](https://issues.alfresco.com/jira/browse/ADF-4845)
**Does …
=> [ADF-4845] Uploader - Expanded/collapsed state not exposed

docs/process-services-cloud/components/process-list-cloud.component.md, docs/process-services-cloud/components/task-list-cloud.component.md, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.html, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> - [ ] Bugfix
- provide support for toggling sticky header for cloud task list
**Does …
=> [ADF-4854] sticky header for task list

scripts/travis/release/git-tag-beta.sh
=> [ADF-4860] Travis add tag beta on cron job

lib/content-services/i18n/en.json, lib/content-services/upload/components/file-uploading-dialog.component.html
> - [x] Bugfix
[ADF-4855](https://issues.alfresco.com/jira/browse/ADF-4855)
**Does …
=> [ADF-4855] Upload dialog - Buttons must have discernible text

lib/content-services/i18n/en.json, lib/content-services/upload/components/file-uploading-dialog.component.html, lib/content-services/upload/components/file-uploading-dialog.component.spec.ts, lib/content-services/upload/components/file-uploading-dialog.component.ts
> - [x] Bugfix
[ADF-4862](https://issues.alfresco.com/jira/browse/ADF-4862)
**Does …
=> [ADF-4862] Upload dialog - reading order

lib/core/form/services/form-rendering.service.spec.ts, lib/core/form/services/form-rendering.service.ts
=> [ACTIVITI-3739] make display show json types

e2e/pages/adf/demo-shell/process-services/processCloudDemoPage.ts, e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts, e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
=> [ADF-4828] Should display the custom action menu for Process Cloud List

lib/testing/src/lib/core/actions/identity/roles.service.ts, lib/testing/src/lib/core/pages/pagination.page.ts
=> [DW-1328] added the create and delete role api for test preconditions

lib/core/datatable/components/datatable/datatable.component.html, lib/core/i18n/en.json, lib/testing/src/lib/core/pages/data-table-component.page.ts
> - [x] Bugfix
[ADF-4831](https://issues.alfresco.com/jira/browse/ADF-4831)
**Does …
=> [ADF-4831] DocumentList - filetype alternative text is not meaningful

lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4826
Loader is shown until …
=> [ADF-4826] Process/Task list first displays "No Process/Task Found" and then loads the Process/Tasks

demo-shell/src/app/app.module.ts, demo-shell/src/app/app.routes.ts, demo-shell/src/app/components/error/demo-error.component.html, demo-shell/src/app/components/error/demo-error.component.scss, demo-shell/src/app/components/error/demo-error.component.ts, docs/core/components/error-content.component.md, e2e/core/error-component.e2e.ts, lib/core/templates/error-content/error-content.component.html, lib/core/templates/error-content/error-content.component.scss, lib/core/templates/error-content/error-content.component.spec.ts, lib/core/templates/error-content/error-content.component.ts, lib/testing/src/lib/core/pages/error.page.ts
Move the custom buttons on demoshell
Fix unit test
Remove usefull e2e
> - [ ] Bugfix …
=> [ADF-4867] adf-error-component refactor

e2e/content-services/upload/cancel-upload.e2e.ts, lib/content-services/upload/components/file-uploading-list-row.component.html, lib/content-services/upload/components/file-uploading-list.component.spec.ts, lib/content-services/upload/components/file-uploading-list.component.ts
> - [x] Bugfix
[ADF-4838](https://issues.alfresco.com/jira/browse/ADF-4838)
**Does …
=> [ADF-4838] Upload Dialog - canceling a pending file cancels the file in progress

scripts/release/release.sh, scripts/travis/build/build.sh, scripts/travis/release/release.sh
=> [ADF-4863] Use npx instead of absolute adf-cli path

lib/content-services/content-node-selector/content-node-dialog.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4798
Currently, Disabled …
=> [ADF-4798] - [adf-content-node-selector] File icons are not showing properly

.travis.yml, e2e/test.config.js, lib/testing/src/lib/core/actions/identity/applications.service.ts, lib/testing/src/lib/core/actions/identity/identity.service.ts, lib/testing/src/lib/core/actions/identity/query.service.ts, lib/testing/src/lib/core/actions/identity/tasks.service.ts, lib/testing/src/lib/core/utils/logger.ts, lib/testing/src/lib/core/utils/public-api.ts, lib/testing/src/lib/process-services-cloud/actions/process-definitions.service.ts, lib/testing/src/lib/process-services-cloud/actions/process-instances.service.ts, lib/testing/src/lib/test.configuration.ts, protractor.conf.ts, scripts/travis/e2e/process-services-cloud-e2e.sh
> - [ ] Bugfix
- Check CS works before PS Cloud test
- Log test class
**Does this PR …
=> Log class in e2e plus check PS cloud CS works before run test

lib/core/form/components/widgets/core/form-field-validator.ts, lib/core/form/components/widgets/core/form-field.model.ts, lib/core/form/services/widget-visibility.service.spec.ts, lib/core/form/services/widget-visibility.service.ts, lib/core/mock/form/widget-visibility.service.mock.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACTIVITI-3746
**Does this PR …
=> [ACTIVITI-3746] - fix form completion with tab fields

lib/testing/src/lib/core/actions/identity/group-identity.service.ts, protractor.conf.ts, scripts/test-e2e-lib.sh, scripts/travis/e2e/process-services-cloud-e2e.sh
=> Add as group suffix the travis build number

lib/process-services/mock/process/process-comments.mock.ts, lib/process-services/mock/process/process.model.mock.ts, lib/process-services/process-comments/process-comments.component.spec.ts, lib/process-services/process-list/components/process-instance-details.component.spec.ts
> - [x] Bugfix
* Fixed failing unit tests on process-services …
=> [Process-services] Fixed failing unit tests on process-services.

lib/core/datatable/components/datatable/datatable.component.html, lib/core/datatable/components/datatable/datatable.component.spec.ts, lib/core/datatable/components/datatable/datatable.component.ts, lib/core/i18n/en.json
> - [ ] Bugfix
[ADF-4892](https://issues.alfresco.com/jira/browse/ADF-4892)
**Does …
=> [ADF-4892] DocumentList - set appropriate column aria-sort state

e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts, e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts, e2e/process-services-cloud/task-list-cloud-action-menu.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
=> [ADF-4829] - Add e2e tests for custom action menu in TaskList and ProcessList

scripts/check-env/check-activiti-env.js
=> added superadminuser as aps_admin user when deploying the apps

lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
> - [x] Bugfix
Not able to upload from ACS with start process widget with form. …
=> [ADF-4906] [ADF] Not able upload file from ACS when start process with form

scripts/travis/update/update-project.sh
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4914
Currently, we're using …
=> [ADF-4914] Fix update versions script on Generator and AMA

lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4913
This PR fixes the …
=> [ADF-4913] Fix Gallery View in datatable Component

scripts/travis/update/update-project.sh
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4922
Fix update project …
=> [ADF-4922] Fix update project script for Generator and Modeler

demo-shell/src/app.config.json, lib/core/app-config/schema.json, lib/core/models/oauth-config.model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4810
**Does this PR …
=> [ADF-4810] sso public urls configuration

docs/core/components/login.component.md
=> [ADF-4810] sso public urls docs

package-lock.json, package.json
> - [ ] Bugfix
> - [x] Other... Please describe: upgrage js-api …
=> [ADF-4810][ADF-4824] get the latest @alfresco/js-api with SSO fixes

lib/core/i18n/en.json
> - [ ] Bugfix
**Update file type text**
https://issues.alfresco.com/jira/browse/ADF-4831 …
=> [ADF-4831] Document list - generic filetype text

lib/core/i18n/en.json, lib/process-services-cloud/src/lib/form/components/attach-file-cloud-widget/attach-file-cloud-widget.component.html, lib/process-services-cloud/src/lib/form/components/attach-file-cloud-widget/attach-file-cloud-widget.component.spec.ts, lib/process-services-cloud/src/lib/form/components/attach-file-cloud-widget/attach-file-cloud-widget.component.ts, lib/process-services-cloud/src/lib/form/components/upload-cloud.widget.html, lib/process-services-cloud/src/lib/form/components/upload-cloud.widget.ts, lib/process-services-cloud/src/lib/form/services/process-cloud-content.service.ts
> - [x] Bugfix
- fix issue with attaching second file
- fix issue with removing files …
=> [ADF-4921] upload widget fixes

docs/compatibility.md, docs/release-notes/README.md, docs/release-notes/RelNote350.md
=> [ADF-4873] Release note in draft.

e2e/core/login/login-sso/login-sso.e2e.ts, lib/core/i18n/en.json, lib/core/settings/host-settings.component.html, lib/core/settings/host-settings.component.ts, package-lock.json, package.json
> - [x] Bugfix
Fix settings SSO pubblicurls for setting component
**Does this PR …
=> [ADF-4810] fix sso settings

lib/core/viewer/components/viewer.component.html
> - [x] Bugfix
[ADF-4939](https://issues.alfresco.com/jira/browse/ADF-4939)
**Does …
=> [ADF-4939] Viewer - mime type icon alt text

lib/core/viewer/components/viewer.component.html, lib/core/viewer/viewer.module.ts
> - [x] Bugfix
[ADF-4938](https://issues.alfresco.com/jira/browse/ADF-4938)
**Does …
=> [ADF-4938] Viewer - focus on trigger on close 

lib/content-services/upload/components/file-uploading-dialog.component.spec.ts, lib/content-services/upload/components/file-uploading-dialog.component.ts
> - [x] Bugfix
[ADF-4862](https://issues.alfresco.com/jira/browse/ADF-4862)
**Does …
=> [ADF-4862] Upload - refocus dialog on files added

docs/tutorials/preparing-environment.md
=> Documentation - grammar corrections and rewording

lib/core/viewer/components/viewer.component.html
> - [x] Bugfix
[ADF-4934](https://issues.alfresco.com/jira/browse/ADF-4934)
**Does …
=> [ADF-4934] Viewer - sidebar expanded/collapsed state exposed via ARIA

README.md
=> improve build release readme stauts

README.md
=> fix travis url

lib/core/i18n/en.json, lib/core/viewer/components/pdfViewer.component.html, lib/core/viewer/components/viewer.component.html
> - [ ] Bugfix
[ADF-4940](https://issues.alfresco.com/jira/browse/ADF-4940)
**Does …
=> [ADF-4940] Viewer - actions aria labels

cspell.json, e2e/pages/adf/demo-shell/process-services/processCloudDemoPage.ts, e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts, e2e/process-services-cloud/start-task-form-cloud.e2e.ts, e2e/process-services-cloud/task-list-selection.e2e.ts, e2e/util/resources.js, scripts/travis/e2e/process-services-cloud-e2e.sh, scripts/travis/e2e/process-services-e2e.sh
> - [ ] Bugfix
Fix PS cloud test …
=> [AAE-550] Fix PS cloud test

lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
=> fix task header priorit tests

lib/core/viewer/components/imgViewer.component.html, lib/core/viewer/components/imgViewer.component.scss, lib/core/viewer/components/imgViewer.component.spec.ts, lib/core/viewer/components/imgViewer.component.ts
> - [ ] Bugfix
[ADF-4937](https://issues.alfresco.com/jira/browse/ADF-4937)
**Does …
=> [ADF-4937] Viewer - Drag and Drop is not operable with keyboard alone

lib/cli/README.md, lib/cli/scripts/init-aae-env.ts, lib/cli/tsconfig.json, package.json
=> [ADF-4916] Create the adf-cli init-aae-env command

lib/content-services/document-list/services/node-actions.service.ts, lib/core/directives/node-download.directive.ts, lib/core/services/download.service.ts, lib/process-services-cloud/src/lib/form/components/attach-file-cloud-widget/attach-file-cloud-widget.component.spec.ts, lib/process-services-cloud/src/lib/form/components/attach-file-cloud-widget/attach-file-cloud-widget.component.ts, lib/process-services-cloud/src/lib/form/components/upload-cloud.widget.ts, lib/process-services-cloud/src/lib/form/services/process-cloud-content.service.ts
> - [x] Bugfix
- fix issue with the corrupted attachments
- obtain ECM ticket before …
=> [ADF-4926] fix attachments downloading

lib/testing/src/lib/process-services-cloud/public-api.ts, lib/testing/src/lib/process-services-cloud/resources/resources.ts
> - [ ] Bugfix
Right now all the resources config of differents apps are inside the same file …
=> [ADF-4948] Move the the resources as part of testing lib Part-1

lib/content-services/breadcrumb/breadcrumb.component.scss
> - [x] Bugfix
[ADF-4952](https://issues.alfresco.com/jira/browse/ADF-4952)
**Does …
=> [ADF-4952] Breadcrumb - focus style issues 

demo-shell/src/custom-style-dev.scss, lib/core/layout/components/layout-container/layout-container.component.scss, package-lock.json
> - [x] Bugfix
remove overwrite Angular style  that prevent the correct use of the sidenav …
=> remove overwrite Angular style 

demo-shell/src/app/components/search/search-result.component.ts, lib/content-services/content-node-selector/content-node-selector.service.ts, lib/content-services/content-node-share/content-node-share.directive.spec.ts, lib/content-services/search/components/search-filter/search-filter.component.ts, lib/content-services/search/components/search.component.ts, lib/core/clipboard/clipboard.service.ts, lib/core/login/components/login.component.ts, lib/core/services/directionality-config.service.ts, lib/core/services/search.service.ts, lib/process-services/src/lib/process-list/services/process-filter.service.ts
> - ~~[ ] Tests for the changes have been added (for bug fixes / features)~~
> - ~~[ ] Docs have been added / updated (for bug fixes / features)~~
> - [x] Bugfix
The library contains code that is not compatible with Angular v8 and v9. …
=> [#4961] Angular v9 (ivy) compatibility fixes #5153

lib/content-services/content-metadata/components/content-metadata/content-metadata.component.html, lib/content-services/content-metadata/components/content-metadata/content-metadata.component.scss
> - [x] Bugfix
[ADF-4963](https://issues.alfresco.com/jira/browse/ADF-4963)
**Does …
=> [ADF-4963] Info Drawer - Focus indicator is not clearly visible

lib/testing/src/lib/core/actions/api.service.ts, lib/testing/src/lib/core/actions/identity/query.service.ts, lib/testing/src/lib/form-cloud/actions/form-cloud.service.ts, lib/testing/src/lib/form-cloud/actions/public-api.ts, lib/testing/src/lib/form-cloud/public-api.ts, lib/testing/src/lib/process-services-cloud/actions/message-events.service.ts, lib/testing/src/lib/process-services-cloud/actions/public-api.ts
=> [DW-1521] added message-events api methods

lib/core/services/cookie.service.ts
> - [ ] Bugfix
ADF sets a cookie without a name with a value of test-cookie, as a way …
=> [ADF-4897] delete test-cookie after check

e2e/core/card-view/card-view-component.e2e.ts, e2e/pages/adf/cardViewComponentPage.ts, e2e/pages/adf/metadataViewPage.ts, e2e/pages/adf/process-services/taskDetailsPage.ts, lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html, lib/core/card-view/components/card-view-textitem/card-view-textitem.component.scss
> - [x] Bugfix
[ADF-4958](https://issues.alfresco.com/jira/browse/ADF-4958) …
=> [ADF-4958] [ADF-4959] Info Drawer - Buttons don't have role and accessible by keyboard alone

lib/core/layout/components/header/header.component.html
> - [ ] Bugfix
[ADF-4967]
[ADF-4967] …
=> [ADF-4967] Header - link does not have a role

docs/core/components/viewer.component.md, lib/core/viewer/components/viewer.component.html, lib/core/viewer/components/viewer.component.ts
> - [ ] Bugfix
[ADF-4965](https://issues.alfresco.com/jira/browse/ADF-4965)
**Does …
=> [ADF-4965] Viewer - pass navigate before and next event

lib/testing/src/lib/core/pages/form/formFields.ts, lib/testing/src/lib/core/pages/form/widgets/checkboxWidget.ts
=> Added isChecked method to verify the status of checkbox widget

lib/content-services/content-metadata/components/content-metadata-card/content-metadata-card.component.html
> - [x] Bugfix
[ADF-4975](https://issues.alfresco.com/jira/browse/ADF-4975)
**Does …
=> [ADF-4975] Info Drawer - Main Edit button should have an aria-label

e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts, e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts, e2e/process-services-cloud/task-list-cloud-action-menu.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
=> [ADF-4893] added test for the visible flag

lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts, lib/testing/src/lib/core/actions/identity/applications.service.ts
> - [ ] Bugfix
When we retrieve the app from the server we list it in a random order …
=> [AAE-520] order apps by name when retrieve from the server

e2e/pages/adf/process-services/processListPage.ts, e2e/pages/adf/process-services/processServiceTabBarPage.ts, e2e/process-services-cloud/task-form-cloud-component.e2e.ts, e2e/process-services/empty-process-list-component.e2e.ts, lib/testing/src/lib/core/utils/browser-actions.ts, lib/testing/src/lib/form-cloud/actions/form-cloud.service.ts, lib/testing/src/lib/process-services-cloud/resources/resources.ts
> - [x] Bugfix
Some e2e releies on the ID in the resources files to test the app 
The …
=> [ADF-4976] Fix cloud ps e2e errors

package.json, scripts/app-config-replace.js, scripts/test-e2e-lib.sh, scripts/travis/e2e/insights-e2e.sh, scripts/travis/e2e/process-services-cloud-e2e.sh, scripts/travis/e2e/process-services-e2e.sh, scripts/travis/e2e/search-e2e.sh
> - [ ] Bugfix
In order to run the e2e I removed sed that has some issues on some envs …
=> [ADF-4957] Use Replace JS instead of sed to run e2e

demo-shell/src/app/app.routes.ts, docs/core/services/auth-guard-ecm.service.md, lib/core/services/auth-guard-base.ts, lib/core/services/auth-guard-bpm.service.spec.ts, lib/core/services/auth-guard-bpm.service.ts, lib/core/services/auth-guard-ecm.service.spec.ts, lib/core/services/auth-guard-ecm.service.ts, lib/core/services/auth-guard.service.spec.ts, lib/core/services/auth-guard.service.ts, lib/core/settings/host-settings.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4936
Allow the AuthGuard to …
=> [ADF-4936] Auth guard redirect fix

e2e/pages/adf/demo-shell/dataTablePage.ts, e2e/pages/adf/process-services/processFiltersPage.ts, e2e/pages/adf/process-services/taskDetailsPage.ts, e2e/pages/adf/process-services/tasksPage.ts, e2e/pages/adf/trashcanPage.ts, lib/content-services/src/lib/directives/node-lock.directive.spec.ts, lib/content-services/src/lib/directives/node-lock.directive.ts, lib/core/datatable/components/datatable/datatable-row.component.spec.ts, lib/core/datatable/components/datatable/datatable-row.component.ts, lib/core/datatable/components/datatable/datatable.component.html, lib/core/datatable/components/datatable/datatable.component.scss, lib/core/datatable/components/datatable/datatable.component.spec.ts, lib/core/datatable/components/datatable/datatable.component.ts, lib/core/datatable/components/datatable/filesize-cell.component.ts, lib/core/datatable/datatable.module.ts, lib/core/datatable/public-api.ts, lib/testing/src/lib/core/pages/data-table-component.page.ts
> - [x] Bugfix
[ADF-2990](https://issues.alfresco.com/jira/browse/ADF-2990)
**Does …
=> [ADF-2990] Datatable - row navigation

docs/core/components/search-cloud.component.md, lib/core/core.module.ts, lib/core/index.ts, lib/core/models/search-cloud.model.ts, lib/core/search-cloud/components/search-text-cloud/search-text-cloud.component.html, lib/core/search-cloud/components/search-text-cloud/search-text-cloud.component.spec.ts, lib/core/search-cloud/components/search-text-cloud/search-text-cloud.component.ts, lib/core/search-cloud/index.ts, lib/core/search-cloud/public-api.ts, lib/core/search-cloud/search-cloud.component.scss, lib/core/search-cloud/search-cloud.component.spec.ts, lib/core/search-cloud/search-cloud.component.ts, lib/core/search-cloud/search-cloud.module.ts, lib/core/services/search-cloud.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-534
**Does this PR …
=> [AAE-534] Core - add search cloud component

e2e/pages/adf/demo-shell/process-services/processCloudDemoPage.ts, e2e/pages/adf/process-services/startProcessPage.ts, e2e/process-services-cloud/form-field/visibility-condition.e2e.ts, lib/testing/src/lib/core/pages/form/formFields.ts, lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts
…tions
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4849 …
=> [ADF-4849] [APM-1226] - Automate boolean and number  visibility conditions

lib/testing/src/lib/core/utils/logger.ts
> - [x] Bugfix
When config is not set in the browser param the log fail 
**Does this …
=> [no-issue] fix log when config is not set

e2e/process-services-cloud/apps-section-cloud.e2e.ts, e2e/process-services-cloud/edit-process-filters-component.e2e.ts, e2e/process-services-cloud/edit-task-filters-component.e2e.ts, e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts, e2e/process-services-cloud/form-field/visibility-condition.e2e.ts, e2e/process-services-cloud/people-group-cloud-component.e2e.ts, e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts, e2e/process-services-cloud/process-custom-filters.e2e.ts, e2e/process-services-cloud/process-filter-results.e2e.ts, e2e/process-services-cloud/process-filters-cloud.e2e.ts, e2e/process-services-cloud/process-header-cloud.e2e.ts, e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts, e2e/process-services-cloud/process-list-cloud-component.e2e.ts, e2e/process-services-cloud/process-list-selection-cloud.e2e.ts, e2e/process-services-cloud/start-process-cloud.e2e.ts, e2e/process-services-cloud/start-task-form-cloud.e2e.ts, e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts, e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts, e2e/process-services-cloud/task-filters-cloud.e2e.ts, e2e/process-services-cloud/task-form-cloud-component.e2e.ts, e2e/process-services-cloud/task-header-cloud.e2e.ts, e2e/process-services-cloud/task-list-cloud-action-menu.e2e.ts, e2e/process-services-cloud/task-list-properties.e2e.ts, e2e/process-services-cloud/task-list-selection.e2e.ts, e2e/process-services-cloud/tasks-custom-filters.e2e.ts, lib/testing/src/lib/core/actions/identity/identity.service.ts, lib/testing/src/lib/core/actions/identity/roles.service.ts, lib/testing/src/lib/process-services-cloud/resources/resources.ts
> - [ ] Bugfix
Use ACTIVITI_ roles instead of APS_ roles …
=> [DW-1560] switch to ACTIVITI roles

demo-shell/resources/i18n/en.json, demo-shell/src/app/app.module.ts, demo-shell/src/app/app.routes.ts, demo-shell/src/app/components/app-layout/app-layout.component.ts, demo-shell/src/app/components/cloud/task-details-cloud-demo.component.html, demo-shell/src/app/components/cloud/task-details-cloud-demo.component.ts, demo-shell/src/app/components/cloud/task-header-cloud-demo.component.html, demo-shell/src/app/components/cloud/task-header-cloud-demo.component.scss, demo-shell/src/app/components/cloud/task-header-cloud-demo.component.ts, docs/process-services-cloud/components/task-header-cloud.component.md, lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts, lib/process-services-cloud/src/lib/process/process-header/services/process-header-cloud.service.ts, lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts, lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts, lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts, lib/process-services-cloud/src/lib/services/user-preference-cloud.service.ts, lib/process-services-cloud/src/lib/task/directives/claim-task.directive.ts, lib/process-services-cloud/src/lib/task/directives/complete-task.directive.ts, lib/process-services-cloud/src/lib/task/directives/unclaim-task.directive.ts, lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.html, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts, licenses.txt
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4979
The Task Header Cloud …
=> [ADF-4979] Add onChanges detection for Task Header Cloud component

lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
=> [ADF-4979] TaskHeader - Fix loop

.mergify.yml
> - [ ] Bugfix
- enable mergify
- auto-merge for dependabot (coming soon)
- auto-merge …
=> enable mergify

e2e/process-services-cloud/apps-section-cloud.e2e.ts, e2e/process-services-cloud/edit-process-filters-component.e2e.ts, e2e/process-services-cloud/edit-task-filters-component.e2e.ts, e2e/process-services-cloud/form-field/date-widget.e2e.ts, e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts, e2e/process-services-cloud/form-field/visibility-condition-tabs.e2e.ts, e2e/process-services-cloud/form-field/visibility-condition.e2e.ts, e2e/process-services-cloud/people-group-cloud-component.e2e.ts, e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts, e2e/process-services-cloud/process-custom-filters.e2e.ts, e2e/process-services-cloud/process-filter-results.e2e.ts, e2e/process-services-cloud/process-filters-cloud.e2e.ts, e2e/process-services-cloud/process-header-cloud.e2e.ts, e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts, e2e/process-services-cloud/process-list-cloud-component.e2e.ts, e2e/process-services-cloud/process-list-selection-cloud.e2e.ts, e2e/process-services-cloud/start-process-cloud.e2e.ts, e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts, e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts, e2e/process-services-cloud/task-filters-cloud.e2e.ts, e2e/process-services-cloud/task-form-cloud-component.e2e.ts, e2e/process-services-cloud/task-header-cloud.e2e.ts, e2e/process-services-cloud/task-list-cloud-action-menu.e2e.ts, e2e/process-services-cloud/task-list-properties.e2e.ts, e2e/process-services-cloud/task-list-selection.e2e.ts, e2e/process-services-cloud/tasks-custom-filters.e2e.ts, e2e/test.config.js, lib/testing/src/lib/core/pages/login-sso.page.ts, scripts/app-config-replace.js, scripts/travis/e2e/process-services-cloud-e2e.sh
> - [x] Bugfix
PS cloud e2e needs a users usage review …
=> Refactor e2e PS-CLOUD

lib/process-services/src/lib/attachment/process-attachment-list.component.ts, lib/process-services/src/lib/attachment/task-attachment-list.component.ts, lib/process-services/src/lib/people/components/people-list/people-list.component.ts, lib/process-services/src/lib/people/components/people-search-field/people-search-field.component.ts, lib/process-services/src/lib/people/components/people-search/people-search.component.ts, lib/process-services/src/lib/people/components/people/people.component.ts, lib/process-services/src/lib/task-list/models/user-event.model.ts, lib/process-services/src/lib/task-list/models/user-group.model.ts, lib/process-services/src/lib/task-list/services/tasklist.service.ts, lib/process-services/src/lib/task-list/validators/task-description.validator.ts, lib/testing/src/lib/core/actions/identity/group-identity.service.ts, lib/testing/src/lib/core/actions/identity/identity.service.ts, lib/testing/src/lib/core/actions/identity/tasks.service.ts, lib/testing/src/lib/core/pages/data-table-component.page.ts, lib/testing/src/lib/core/pages/form/formFields.ts, lib/testing/src/lib/core/utils/logger.ts, lib/testing/src/lib/process-services-cloud/actions/message-events.service.ts, lib/testing/src/lib/process-services-cloud/actions/process-definitions.service.ts, lib/testing/src/lib/process-services-cloud/pages/dialog/edit-process-filter-dialog.page.ts, lib/testing/src/lib/process-services-cloud/pages/dialog/edit-task-filter-dialog.page.ts, lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts, lib/testing/src/lib/process-services/pages/form-fields.page.ts
> - [ ] Bugfix
add missing typing information for various methods
**Does this PR …
=> add missing typing information

lib/core/datatable/components/datatable/datatable.component.html
> - [ ] Bugfix
> - [x] Other... Please describe: Accessibility improvement
Please check https://issues.alfresco.com/jira/browse/ADF-4986
**What is the …
=> [ADF-4986] Move or copy - Empty cells should not receive focus

e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
> - [ ] Bugfix
Wrong import e2e …
=> Fix e2e test visibility

lib/cli/README.md, lib/cli/bin/adf-cli, lib/cli/package-lock.json, lib/cli/package.json, lib/cli/scripts/artifact-from-s3.ts, lib/cli/scripts/artifact-to-s3.ts, lib/cli/scripts/docker-publish.ts, lib/cli/scripts/exec.ts, lib/cli/scripts/init-aae-env.ts, lib/cli/scripts/kubectl-delete.ts, lib/cli/scripts/kubectl-image.ts, lib/cli/scripts/logger.ts, lib/cli/scripts/npm-publish.ts, lib/cli/scripts/update-commit-sha.ts, lib/cli/scripts/update-version.ts, package-lock.json, package.json, scripts/check-env/check-ps-env.js
> - [ ] Bugfix
- Refactor current cli script
- Remove log parameter and use log class …
=> [ADF-4982] Refactor CLI script and add new S3 scripts

demo-shell/src/app/components/cloud/task-header-cloud-demo.component.html, demo-shell/src/app/components/cloud/task-header-cloud-demo.component.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
…TaskHeaderCloudComponent
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4979 …
=> [ADF-4979] TaskHeaderCloudComponent Add error emit when appName or taskId is not provided

lib/testing/src/lib/core/actions/identity/query.service.ts
=> added the method to retrieve the processInstanceId based on the processname

e2e/process-services-cloud/task-header-cloud.e2e.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-463
**Does this PR …
=> [AAE-463] - change dueDate render component

demo-shell/src/app/components/cloud/task-header-cloud-demo.component.html, demo-shell/src/app/components/cloud/task-header-cloud-demo.component.ts
> - [ ] Bugfix
In order to test the behaviour of the component validation needs to be removed from demo shell
**What …
=> [ADF-4979] Remove unnecessary demo shell required validation

demo-shell/src/app/components/cloud/tasks-cloud-demo.component.html, docs/process-services-cloud/components/edit-task-filter-cloud.component.md, docs/process-services-cloud/components/task-list-cloud.component.md, e2e/process-services-cloud/config/task-list-cloud.config.ts, lib/process-services-cloud/src/lib/i18n/en.json, lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts, lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts, lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-header/mocks/fake-task-details-response.mock.ts, lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-list/mock/fakeTaskResponseMock.ts, lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4992.
* Tasks were not able to query by a standalone prop. …
=> [ADF-4992] [TaskListCloudComponent] Use standalone property in the task query api

package-lock.json, package.json
> - [ ] Bugfix
- upgrade node-sass library …
=> upgrade node-sass to support node 12

e2e/core/card-view/card-view-component.e2e.ts, e2e/pages/adf/cardViewComponentPage.ts
https://issues.alfresco.com/jira/browse/AAE-485
A user can delete the …
=> [AAE-485] - empty value for CardView Int Item e2e test

lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
> - [ ] Bugfix
no method for getStatusByName in task list page
https://issues.alfresco.com/jira/browse/AAE-811
**What …
=> [AAE-811] Add getStatusByName in task list page

docs/core/components/search-text-input.component.md, lib/core/search-text/search-text-input.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-849
**Does this PR …
=> [AAE-849] improve search component

lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html, lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts, lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
> - [x] Bugfix
[ADF-4995](https://issues.alfresco.com/jira/browse/ADF-4995)
**Does …
=> [ADF-4995] Metadata - edit mode cannot be access via keyboard

lib/core/services/auth-guard-sso-role.service.spec.ts, lib/core/services/auth-guard-sso-role.service.ts, lib/core/services/jwt-helper.service.spec.ts, lib/core/services/jwt-helper.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4994
**Does this PR …
=> [ADF-4994] Move realmRole functions inside JwtHelperService.

lib/core/form/services/widget-visibility-cloud.service.spec.ts, lib/core/form/services/widget-visibility.service.spec.ts, lib/core/form/services/widget-visibility.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4787
Visibility condition …
=> [ADF-4787] Invalid value of number field is parsed and fields with visibility conditions based on the number field are visible

lib/cli/scripts/init-aae-env.ts
deployment-service
modeling-service
dmn-service
> - [ ] Bugfix
Add an health check on the main microservices
**What …
=> [ADF-5008] Add an health checks on the services:

lib/cli/scripts/update-version.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/AAE-880
update-version subcommand was not working with …
=> [AAE-880] Fix updater script in the cli

lib/core/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5002
**Does this PR …
=> [ADF-5002] Datatable - fix focus selection for grid list

lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts, lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/DW-1563
COMPLETE button is …
=> [DW-1563] Complete button is not present for empty forms

lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html, lib/core/card-view/components/card-view-textitem/card-view-textitem.component.scss, lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts, lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts, lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5004
* Now clickable items …
=> [ADF-5004] [CardViewTextItemComponent] Provide a way to have an icon for the clickable items

lib/process-services-cloud/src/lib/form/components/dropdown-cloud/dropdown-cloud.widget.html, lib/process-services-cloud/src/lib/form/components/dropdown-cloud/dropdown-cloud.widget.spec.ts, lib/process-services-cloud/src/lib/form/components/dropdown-cloud/dropdown-cloud.widget.ts
> - [x] Bugfix
Preselected values are not showing in the form cloud 
https://issues.alfresco.com/jira/browse/ADF-5013 …
=> [ADF-5013] Dropdown does not display the default value

docs/core/components/login.component.md, docs/core/directives/logout.directive.md, docs/user-guide/README.md, docs/user-guide/kerberos.md
> - [ ] Bugfix
Add more info related to kerberos …
=> [DOCS-5508] Add more info for kerberos

lib/core/form/components/widgets/core/form-field.model.ts, lib/core/form/components/widgets/date-time/date-time.widget.spec.ts, lib/core/form/components/widgets/date-time/date-time.widget.ts, lib/core/form/components/widgets/date/date.widget.spec.ts, lib/core/form/components/widgets/date/date.widget.ts, lib/process-services-cloud/src/lib/form/components/date-cloud/date-cloud.widget.spec.ts, lib/process-services-cloud/src/lib/form/components/date-cloud/date-cloud.widget.ts
Reverts Alfresco/alfresco-ng2-components#5041
=> Revert "[ADF-4861] Fix memory leak in Date widgets and Form Cloud Model"

docs/compatibility.md, docs/release-notes/README.md, docs/release-notes/RelNote360.md
=> [ADF-4945] Draft of the release note for 3.6.0.

lib/content-services/src/lib/document-list/services/custom-resources.service.spec.ts, lib/content-services/src/lib/document-list/services/custom-resources.service.ts
> - [ ] Bugfix
[ADF-5015](https://issues.alfresco.com/jira/browse/ADF-5015)
**Does …
=> [ADF-5015] DocumentList - favorites properties

e2e/process-services-cloud/start-task-form-cloud.e2e.ts, lib/testing/src/lib/core/pages/form/widgets/attachFileWidgetCloud.ts
> - [ ] Bugfix
> - [x] Other... Please describe: E2e for https://issues.alfresco.com/jira/browse/ADF-4823
**Does this PR …
=> [ADF-4823] [e2e] Displaying a file in a form does not work

.travis.yml, lib/cli/scripts/npm-publish.ts, scripts/travis/update/update-project.sh
> - [x] Bugfix
Some scripts has some minor issues …
=> Improve scripts after release

lib/cli/scripts/exec.ts, lib/cli/scripts/npm-publish.ts, lib/cli/scripts/update-commit-sha.ts, scripts/travis/deploy/deploy.sh, scripts/travis/deploy/pr-publish.sh
> - [x] Bugfix
The npm script always try to publish npm pacakges also if is not needed …
=> [ADF-5033] Improve publish script

lib/process-services-cloud/src/lib/process/directives/delete-process.directive.spec.ts, lib/process-services-cloud/src/lib/process/directives/delete-process.directive.ts, lib/process-services-cloud/src/lib/process/directives/process-directive.module.ts, lib/process-services-cloud/src/lib/process/directives/public-api.ts, lib/process-services-cloud/src/lib/process/process-cloud.module.ts, lib/process-services-cloud/src/lib/process/services/process-cloud.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5032
delete process …
=> [ADF-5032] Add delete process directive

e2e/core/datatable/data-table-component.e2e.ts
=> [AAE-1080]Remove datatable tests related to demo-shell only.

e2e/process-services-cloud/form-field/visibility-condition.e2e.ts, e2e/resources/forms/displayValue-visibilityConditions.ts, lib/testing/src/lib/core/pages/form/widgets/displayValueWidget.ts
> - [ x] Tests for the changes have been added (for bug fixes / features)
> - [ ] Bugfix
> - [ x] Other... Please describe: automating regression tests
https://issues.alfresco.com/jira/browse/ADF-5022 …
=> [ADF-5022] added automation for Display Value Widget

lib/testing/src/lib/process-services-cloud/resources/resources.ts
=> update the resources file to have the connectors

lib/testing/src/lib/core/dialog/edit-json-dialog.ts, lib/testing/src/lib/core/dialog/public-api.ts, lib/testing/src/lib/core/pages/form/formFields.ts, lib/testing/src/lib/core/pages/viewerPage.ts, lib/testing/src/lib/core/public-api.ts
=> Add editjson dialog

angular.json
> - [x] Bugfix
Demo shell correct configuration …
=> Fix angular configuration demo shell

lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
=> [AAE-840]Add method to start a process knowing the name and the processDefinition

lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
=> [AAE-1169] Use default ecmHost in case of startFormEvent

lib/testing/src/lib/process-services-cloud/resources/resources.ts
=> [AAE-840]Fixed the process definition name

lib/core/form/components/widgets/core/form-field.model.ts, lib/core/services/identity-group.service.spec.ts, lib/core/services/identity-group.service.ts, lib/core/services/identity-user.service.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts, lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html, lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts, lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html, lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
…e form
> - [ ] Bugfix
The form is able to show the people widget
**single mode**
`{ …
=> [AAE-1152] Making sure the people and group widget is working fine as part of form

lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html, lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts, lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html, lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.html, lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.html, lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
=> Fix readonly Fix add remove

lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html, lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts, lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html, lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
=> Making sure the people does not change the original obj reference

demo-shell/src/app/components/cloud/start-process-cloud-demo.component.html, demo-shell/src/app/components/cloud/start-process-cloud-demo.component.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts, lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html, lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html, lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
=> AAE - Fix the attach content from alfresco and local

lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
=> skip temporary the code

lib/testing/src/lib/core/pages/notification-history.page.ts, protractor.excludes.json
=> [AAE-1180]Fix datatable tests

e2e/pages/adf/cardViewComponentPage.ts, e2e/pages/adf/demo-shell/process-services/peopleGroupCloudComponentPage.ts, e2e/pages/adf/demo-shell/process-services/processListDemoPage.ts, e2e/pages/adf/demo-shell/process-services/taskListDemoPage.ts, e2e/pages/adf/dialog/folderDialog.ts, e2e/pages/adf/dialog/shareDialog.ts, e2e/pages/adf/dialog/uploadToggles.ts, e2e/pages/adf/metadataViewPage.ts, e2e/pages/adf/notificationPage.ts, e2e/pages/adf/process-services/analyticsPage.ts, e2e/pages/adf/process-services/attachFormPage.ts, e2e/pages/adf/process-services/dialog/createChecklistDialog.ts, e2e/pages/adf/process-services/startProcessPage.ts, e2e/pages/adf/tagPage.ts, lib/testing/src/lib/content-services/pages/search/date-range-filter.page.ts, lib/testing/src/lib/core/pages/form/widgets/dropdownWidget.ts, lib/testing/src/lib/core/pages/settings.page.ts, lib/testing/src/lib/core/pages/viewerPage.ts, lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts
> - [ ] Bugfix
> - [ x] Refactoring (no functional changes, no api changes)
https://issues.alfresco.com/jira/browse/AAE-1178
deleted un-necessary …
=> [AAE-1178] ADF - deleted un-necessary steps 

demo-shell/src/app/components/card-view/card-view.component.ts, docs/core/components/card-view.component.md, lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.html, lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.scss, lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.spec.ts, lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.ts, lib/core/card-view/models/card-view-arrayitem.model.ts, lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1200
**Does this PR …
=> [AAE-1200] AAE - FE - Provide a way to define icon on CardViewArrayItemComponent

docs/tutorials/working-with-nodes-api-service.md
=> [ADF-4996] Update working-with-nodes-api-service.md

lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1238
done
**Does this PR …
=> [AAE-1238] Re-enable appVersion check

e2e/core/card-view/card-view-component.e2e.ts, e2e/pages/adf/cardViewComponentPage.ts, lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html, lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts, lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts, lib/testing/src/lib/core/pages/card-view/public-api.ts, lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts, package.json
=> [AAE-865]Create card view text item PO

e2e/core/user-info-component.e2e.ts, lib/testing/src/lib/core/pages/user-info.page.ts
> - [ ] Bugfix
fix userinfo e2e …
=> fix userinfo e2e

lib/core/package.json
=> Update package.json dependency pdfjs version

lib/process-services-cloud/src/lib/group/components/group-cloud.component.html, lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.html, lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1344 (Bug: Removed all preselected users on removing of a …
=> [AAE-1344] [FE] - Removed all pre-selected users on removing of single pre-selected user.

demo-shell/resources/i18n/en.json, demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.html, demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1351
**Does this PR …
=> [AAE-1351] [GroupCloudComponent] Validate pre-selected groups

lib/core/i18n/fr.json
> - [ NA] Tests for the changes have been added (for bug fixes / features)
> - [NA ] Docs have been added / updated (for bug fixes / features)
https://issues.alfresco.com/jira/browse/LOC-186
Amended …
=> Fix for LOC-186 - mistranslation in French

lib/core/services/auth-guard-base.ts
> - [x] Bugfix
We need to close the dialog also in the redirect scenario
**Does this …
=> [ADF-5009] close dialog in the redirect

.travis.yml
> - [ ] Bugfix
When the JS-API try to propagate the new version we need to build and …
=> new js-api should be deployed if build is ok

lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts, lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts, lib/process-services-cloud/src/lib/form/services/form-cloud.service.spec.ts, lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1336
done
**Does this PR …
=> [AAE-1336] add version on completeTaskForm

lib/testing/src/lib/core/actions/identity/tasks.service.ts, lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts, lib/testing/src/lib/core/pages/data-table-component.page.ts, lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
=> [AAE-1361]Add complete task of a process method

e2e/core/user-info-component.e2e.ts, lib/core/userinfo/components/user-info.component.html, lib/core/userinfo/components/user-info.component.ts, lib/testing/src/lib/core/pages/user-info.page.ts
> - [x] Bugfix
select first user info when open the first time
**Does this PR …
=> [AAE-1174] select first user info when open the first time

docs/content-services/components/content-node-selector.component.md, lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html, lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts, lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts, lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts, lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
> - [ ] Bugfix
[ADF-5062](https://issues.alfresco.com/jira/browse/ADF-5062)
**Does …
=> [ADF-5062] Content Node Selector - show inputs based on configuration

lib/core/form/components/widgets/dynamic-table/editors/amount/amount.editor.html, lib/core/form/components/widgets/dynamic-table/editors/amount/amount.editor.scss, lib/core/form/components/widgets/dynamic-table/editors/amount/amount.editor.spec.ts, lib/core/form/components/widgets/dynamic-table/editors/amount/amount.editor.ts, lib/core/form/components/widgets/dynamic-table/editors/row.editor.html, lib/core/form/components/widgets/index.ts
=> Adding amount row editor for dynamic table

lib/core/form/components/widgets/core/form-field.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1235
**Does this PR …
=> [AAE-1235] - fix task completion with datetime form widget

demo-shell/resources/i18n/en.json, demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.html, demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.ts, docs/process-services-cloud/components/group-cloud.component.md, docs/process-services-cloud/components/people-cloud.component.md, e2e/process-services-cloud/people-group-cloud-component.e2e.ts, e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts, e2e/process-services-cloud/start-task/start-task-custom-app-cloud.e2e.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.html, lib/process-services-cloud/src/lib/group/components/group-cloud.component.scss, lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts, lib/process-services-cloud/src/lib/i18n/en.json, lib/process-services-cloud/src/lib/people/components/people-cloud.component.html, lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts, lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1372
People/Group cloud …
=> [AAE-1372] Refactor People/Group cloud component

lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts, lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
> - [ ] Bugfix
Not able to fetch applications based on a specific role
Able to fetch …
=> [AAE-1501] EditProcessCloud/EditTaskCloud - Ability to fetch applications by role

e2e/process-services-cloud/form-field/people-group-of-people.e2e.ts
> - [ ] Bugfix
fixed e2e tests- single mode  …
=> [AAE-1152] fixed tests using single mode displayed as a tag too

.travis.yml
> - [ ] Bugfix
remove update PR env …
=> remove update PR env

lib/content-services/src/lib/document-list/data/share-datatable-adapter.ts
> - [ ] Bugfix
Wrong import, AMA can't be built using local ADF packages.
Fixed import …
=> Fix wrong import

lib/core/form/components/widgets/date-time/date-time.widget.html, lib/core/form/components/widgets/date/date.widget.html
> - [X] Bugfix
There is no keyboard trap on the material datepicker widget.
There is a …
=> [ACA-2475] keyboard trap

e2e/content-services/tag-component.e2e.ts
> - [ ] Bugfix
Remove unesfull test …
=> Remove flaky test

scripts/travis/deploy/deploy.sh, scripts/travis/deploy/rancher-update.sh
> - [ ] Bugfix
Fix deploy pipeline development …
=> Fix deploy pipeline development

e2e/content-services/share-file/share-file.e2e.ts, lib/content-services/src/lib/search/components/search-control.component.ts
> - [x] Bugfix
fix flaky share test …
=> fix flaky share test

demo-shell/resources/i18n/en.json, lib/core/i18n/en.json, lib/process-services-cloud/src/lib/i18n/en.json
> - [ ] Bugfix
> - [x] Other... Please describe: UI string review …
=> [ADF-5048] Review UI strings

lib/cli/package.json, lib/cli/scripts/init-aae-env.ts
Cli command doens't work because pass the wrong object
**Does this PR …
=> fix release project cli and dependency

lib/core/datatable/components/datatable/datatable.component.ts, package-lock.json, package.json
> - [x] Bugfix
columns in datatable are duplicated for certain scenarios
- fixes issue …
=> [AAE-1564][DW-1654] improved datatable schema

lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1562
The already selected …
=> [AAE-1562] Fix should not be able to search already selected user

docs/release-notes/RelNote370.md
Draft of ADF 3.7 release note
> - [ x] Docs have been added / updated (for bug fixes / features)
> - [ ] Bugfix
N/A
N/A …
=> Draft of ADF 3.7 release note

.stylelintignore, lib/core/viewer/components/pdfViewer.component.ts, lib/core/viewer/components/pdfViewerHost.component.scss
> - [X] Bugfix
fix destroy worker and internalize css pdfjs …
=> [AAE-1591] fix destroy worker and internalize css pdfjs

scripts/travis/e2e/process-services-cloud-e2e.sh
> - [x] Bugfix
change user for cloud test …
=> change user for cloud test

lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
> - [X] Bugfix
changes.preSelectUsers.currentValue can be null
**Does this PR …
=> [AAE-1615] fix preselect user check

demo-shell/src/app.config.json, lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts, lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts, lib/process-services-cloud/src/lib/task/start-task/models/task-details-cloud.model.ts
> - [x] Bugfix
[APW]Remove DELETED status from process instances filter dropdown …
=> [AAE-1360] Remove DELETED status from process instances filter dropdown

.travis.yml, scripts/travis/update/trigger-travis-children.sh
> - [x] Bugfix
trigger child build after merge like JS-API …
=> trigger child build after merge like JS-API

lib/content-services/src/lib/breadcrumb/breadcrumb.component.spec.ts
> - [ ] Bugfix
- add extra unit tests for breadcrumb component (related to document …
=> [ADF-5067] extra unit tests for breadcrumb

demo-shell/src/app/app.routes.ts
> - [x] Bugfix
- fix issue with admin accounts not able to view the cloud demos
**Does …
=> allow admins to view cloud demos

demo-shell/src/app/app.routes.ts
Reverts Alfresco/alfresco-ng2-components#5436
=> Revert "allow admins to view cloud demos"

demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.html, demo-shell/src/app/components/cloud/people-groups-cloud-demo.component.ts, e2e/process-services-cloud/people-group-cloud-component.e2e.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts, lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts, lib/process-services-cloud/src/lib/types.ts
> - [x] Bugfix
- more unit tests for group/people picker components
- clean code for …
=> [ADF-5065] people and group picker tests, clean code

lib/process-services-cloud/src/lib/group/components/group-cloud.component.html, lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts, lib/process-services-cloud/src/lib/people/components/people-cloud.component.html, lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
=> [AAE-1539] People/Group - Add a formControl for the chip field

cspell.json, e2e/pages/adf/demo-shell/process-services-cloud/processDetailsCloudDemoPage.ts, e2e/pages/adf/demo-shell/process-services/tasksCloudDemoPage.ts, e2e/pages/adf/process-services/processListPage.ts, e2e/process-services-cloud/process-filter-results.e2e.ts, e2e/process-services-cloud/process-filter-task.e2e.ts, e2e/process-services-cloud/process-list-selection-cloud.e2e.ts, e2e/process-services-cloud/task-form-cloud-component.e2e.ts, e2e/process-services-cloud/tasks-custom-filters.e2e.ts, lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts, lib/testing/src/lib/process-services-cloud/resources/resources.ts
> - [ ] Bugfix
it contains automation for the following cases
1.C290040 Should be able to open the Task Details page by clicking on the process name
2.C290041 Should be displayed the "No Process …
=> [ADF-5066] APS2 › Process List test need to be automated

docs/compatibility.md
> - [ ] Bugfix
Add content and process compatibility for ADF 3.7.0
**Does this PR …
=> [ADF-5075] Update compatibility matrix for 3.7.0

.travis.yml, lib/core/datatable/components/datatable/datatable.component.html, scripts/travis/e2e/content-services-e2e.sh
> - [x] Bugfix
Sorted column title is incorrectly read by screen reader: "Descending by <translation.key>", instead …
=> [ADF-5073] Sorted column header is incorrectly read by a screen reader

scripts/check-env/check-cs-env.js, scripts/travis/update/trigger-travis-children.sh
> - [x]  The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Bugfix
Fix build scripts …
=> Fix build scripts

e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts, e2e/protractor.excludes.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1179
There were two e2e tests (C291954, C291955) that were …
=> [AAE-1179] Fix Start Task with Groups E2E tests

e2e/process-services-cloud/form-field/visibility-condition.e2e.ts, e2e/process-services/widgets/widget-visibility-condition.e2e.ts, e2e/resources/forms/multiple-visibility-conditions.ts, lib/testing/src/lib/core/pages/form/formFields.ts, lib/testing/src/lib/core/pages/form/widgets/checkboxWidget.ts
> - [ ] Bugfix
Fix e2e visibility widget methods
https://issues.alfresco.com/jira/browse/AAE-1764 …
=> [AAE-1764] Fix testing methods checking visibility of widgets

lib/core/layout/components/sidenav-layout/sidenav-layout.component.spec.ts
> - [ ] Bugfix
UT added for sidenave component
https://issues.alfresco.com/jira/browse/AAE-1838 …
=> [AAE-1838] Sidenav Unit test

.vscode/closest-config-finder.sh, .vscode/launch.json, e2e/content-services/upload/cancel-upload.e2e.ts, e2e/pages/adf/dialog/uploadDialog.ts, scripts/start.sh
> - [ ] Bugfix
Enabled e2e for cancel-upload test …
=> AAE-1792 - reenabled test on upload
