Alfresco/alfresco-ng2-components

- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
> - [ ] Bugfix
Automation
https://issues.alfresco.com/jira/browse/AAE-1803
This PR …
> [AAE-1803] Add Unit tests for custom templates

- lib/content-services/src/lib/upload/components/file-uploading-dialog.component.spec.ts
> [AAE-1794] - added extra unit test

- lib/core/datatable/components/datatable/datatable.component.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1831
done
**Does this PR …
> [AAE-1831] DataTable Unit test

- e2e/process-services/process-filters-component.e2e.ts
- lib/process-services/src/lib/process-list/components/process-instance-details.component.spec.ts
> - [ ] Bugfix
Automation
https://issues.alfresco.com/jira/browse/AAE-1937
done
**Does …
> [AAE-1937] Process Filters E2E APS1

- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
> - [ ] Bugfix
Unit test added for edit task filters (cloud)
https://issues.alfresco.com/jira/browse/AAE-1952
**What …
> [AAE-1952] Task › Edit task filters › Actions E2E Unit test

- demo-shell/src/app.config.json
…ed in English. They are correctly translated now.
**Does this PR …
> DW-1321: Fix for Incomplete List of Languages menu

- lib/process-services/src/lib/task-list/components/task-list.component.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1925
E2e tests transformed …
> [AAE-1925] Add unit tests for Task List Component

- lib/core/about/about-application-modules/about-application-modules.component.html
- lib/core/about/about-application-modules/about-application-modules.component.scss
- lib/core/about/about-application-modules/about-application-modules.component.spec.ts
- lib/core/about/about-github-link/about-github-link.component.html
- lib/core/about/about-github-link/about-github-link.component.scss
- lib/core/about/about-github-link/about-github-link.component.spec.ts
- lib/core/about/about-product-version/about-product-version.component.html
- lib/core/about/about-product-version/about-product-version.component.scss
- lib/core/about/about-product-version/about-product-version.component.spec.ts
- lib/core/about/about.mock.ts
- lib/testing/src/lib/core/pages/about.page.ts
- package.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2021
**Does this PR …
> [AAE-2021] Unit tests for about components

- lib/testing/src/lib/process-services-cloud/resources/resources.ts
> - [ ] Bugfix
remove unused user access permissions for simpleapp, candidatebaseapp, subprocessapp …
> [AAE-2001] Remove APS_USER APS_ADMIN roles from app permissions

- lib/core/form/components/widgets/text/text.widget.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1939
E2e tests that could …
> [AAE-1939] Add unit tests to Text Widget

- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.spec.ts
- lib/content-services/src/lib/search/components/search-slider/search-slider.component.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1954
done
**Does this PR …
> [AAE-1954] Search Unit test

- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1940
Unit tests added to …
> [AAE-1940] Add unit tests for Radio Buttons Widget

- lib/cli/scripts/docker-publish.ts
- scripts/build/build-cli.sh
> adf-cli Provide a way to pass buildArgs to the docker build

- e2e/content-services/permissions/site-permissions.e2e.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1842
Automate C277196 e2e …
> [AAE-1842] Automate C277196 Version manager permissions

- e2e/content-services/about-content-services.component.e2e.ts
- e2e/process-services-cloud/about-process-services-cloud.component.e2e.ts
- e2e/process-services/about-process-services.e2e.ts
- lib/core/about/about-product-version/about-product-version.component.html
- lib/process-services/src/lib/content-widget/attach-file-widget.components.spec.ts
- lib/testing/src/lib/core/pages/about.page.ts
- lib/testing/src/lib/core/pages/public-api.ts
- package.json
> - [ ] Bugfix
* Added About page into testing pack …
> [AAE-2021] Automate About component

- lib/cli/scripts/kubectl-clean-app.ts
> adf-cli - K8s Ability to clean app using the like and interval time

- e2e/content-services/upload/cancel-upload.e2e.ts
> fix cancel

- e2e/process-services/processlist-pagination.e2e.ts
- e2e/process-services/task-details-form.e2e.ts
- e2e/util/resources.js
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1921
done
**Does this PR …
> [AAE-1921] Start Process e2e APS1 and removed [C280015]

- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1950
https://issues.alfresco.com/jira/browse/AAE-1882 …
> [AAE-1950] and [AAE-1882] more unit test

- e2e/process-services-cloud/form-field/visibility-condition.e2e.ts
- e2e/resources/forms/dropdown-visibility-condition.ts
- lib/core/form/components/widgets/dropdown/dropdown.widget.spec.ts
- lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.html
- lib/testing/src/lib/core/pages/form/widgets/dropdown-widget.page.ts
> - [ ] Bugfix
Automation tests
Manual tests for the General properties, the Advanced Manual Options, and the …
> [AAE-1943] Dropdown widget unit test

- lib/core/form/components/widgets/amount/amount.widget.spec.ts
> [AAE-1944] - Amount Widget Unit test

- lib/content-services/src/lib/search/components/search-chip-list/search-chip-list.component.html
- lib/content-services/src/lib/search/components/search-chip-list/search-chip-list.component.spec.ts
- lib/content-services/src/lib/search/components/search-filter/search-filter.component.ts
> - [ ] Bugfix
- additional unit tests
> - [ ] Yes
> - [x] No
If this PR contains a breaking …
> [AAE-1959] additional tests for search chip list

- lib/core/form/components/form-renderer.component.spec.ts
- lib/core/form/components/mock/form-renderer.component.mock.ts
> AAE-1941 - Added unit test for Number Widget

- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1949
done
**Does this PR …
> [AAE-1949] Form Attach File Widget AAE unit test

- e2e/content-services/document-list/document-list-actions.e2e.ts
- e2e/content-services/document-list/document-list-pagination.e2e.ts
- e2e/content-services/document-list/document-list-selection.e2e.ts
- e2e/core/viewer/viewer-properties.e2e.ts
- e2e/pages/adf/content-services.page.ts
- e2e/pages/adf/process-services/process-details.page.ts
- e2e/process-services/start-process-component.e2e.ts
- lib/testing/src/lib/core/pages/viewer.page.ts
- lib/testing/src/lib/process-services/pages/select-apps-dialog.page.ts
> - [ ] Bugfix
e2e automation
AAE-1880
e2e automation …
> [AAE-1880] e2e document-list selection mode

- demo-shell/src/app.config.json
- docs/content-services/components/search-date-range.component.md
- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html
- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.spec.ts
- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.ts
> - [ ] Bugfix
The maxDate is fixed to today and can't be modified or configured. …
> [ADF-5085] Adding possibility to search for future dates search-date-range component 

- e2e/pages/adf/demo-shell/process-services/tasks-cloud-demo.page.ts
- e2e/process-services-cloud/task-header-cloud.e2e.ts
- lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts
- lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/start-tasks-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
> AAE-1951 - added extra test cases for start task and assignee

- lib/core/directives/check-allowable-operation.directive.spec.ts
> - [ ] Bugfix
remove the test that has identical body as "updates element on nodes …
> remove duplicated test

- e2e/pages/adf/card-view-component.page.ts
- lib/testing/src/lib/core/pages/card-view/card-view-boolean-item.page.ts
- lib/testing/src/lib/core/pages/card-view/public-api.ts
> [AAE-1895]Create card-view-boolean-item page

- e2e/process-services-cloud/config/task-filter.config.ts
- e2e/process-services-cloud/task-list-properties.e2e.ts
- e2e/process-services-cloud/tasks-claim-release.e2e.ts
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
- lib/testing/src/lib/process-services-cloud/resources/resources.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1953
done
**Does this PR …
> [AAE-1953] Claim Reclaim Task AAE E2E

- lib/testing/src/lib/core/pages/data-table-component.page.ts
> - [ ] Bugfix
testing method fix
https://issues.alfresco.com/jira/browse/AAE-2126 …
> [AAE-2126] Fix checkbox click testing method in datatable page

- e2e/content-services/upload/excluded-file.e2e.ts
- e2e/content-services/upload/upload-dialog.e2e.ts
- e2e/pages/adf/content-services.page.ts
- e2e/pages/adf/demo-shell/process-services/tasks-cloud-demo.page.ts
- e2e/pages/adf/dialog/share-dialog.page.ts
- e2e/pages/adf/dialog/upload-dialog.page.ts
- e2e/pages/adf/dialog/upload-toggles.page.ts
- e2e/pages/adf/process-services/dialog/app-settings-toggles.page.ts
- e2e/pages/adf/version-manager.page.ts
- e2e/util/resources.js
- lib/testing/src/lib/core/pages/login.page.ts
- lib/testing/src/lib/core/pages/public-api.ts
- lib/testing/src/lib/core/pages/viewer.page.ts
- lib/testing/src/lib/core/utils/browser-actions.ts
- lib/testing/src/lib/material/pages/public-api.ts
- lib/testing/src/lib/material/pages/toggle.page.ts
- scripts/test-e2e-lib.sh
- scripts/travis/e2e/content-services-e2e.sh
> - [ ] Bugfix
automating e2e tests - uploading folders (uploading folder in a folder, uploading folder with an excluded file inside)
**What is the current behaviour?** (You can also link to …
> [AAE-1846] [AAE-1857] automated e2e tests uploading folders

- lib/testing/src/lib/core/pages/form/widgets/hyperlink-widget.page.ts
> [AAE-1895]Retrieve href attribute of hyperlink

- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4522
done
**Does this PR …
> [ADF-4522] Metadata value is not rolled back upon error

- e2e/content-services/share-file/share-file.e2e.ts
- e2e/pages/adf/dialog/share-dialog.page.ts
- e2e/process-services/dynamic-table-date-picker.e2e.ts
- e2e/search/components/search-date-range.e2e.ts
- lib/testing/src/lib/content-services/pages/search/date-range-filter.page.ts
- lib/testing/src/lib/core/pages/card-view/card-view-boolean-item.page.ts
- lib/testing/src/lib/core/pages/card-view/card-view-date-item.page.ts
- lib/testing/src/lib/core/pages/card-view/public-api.ts
- lib/testing/src/lib/material/pages/date-picker-calendar.page.ts
- lib/testing/src/lib/material/pages/date-picker.page.ts
- lib/testing/src/lib/material/pages/date-time-picker-calendar.page.ts
- lib/testing/src/lib/material/pages/date-time-picker.page.ts
- lib/testing/src/lib/material/pages/public-api.ts
> [ADF-1895]Refactor date-time-picker and date-picker

- lib/process-services-cloud/karma.conf.js
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
- lib/process-services-cloud/src/lib/mock/en.json
- lib/process-services-cloud/src/lib/mock/fr.json
- lib/process-services-cloud/src/lib/testing/process-service-cloud.testing.module.ts
> - [ ] Bugfix
Automation :-
C309880 - Should a form support multilingual Labels  …
> [AAE-1923] Multilingual form unit test

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
- lib/content-services/src/lib/content-node-share/content-node-share.dialog.scss
- lib/content-services/src/lib/i18n/en.json
> - [ X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ X] Tests for the changes have been added (for bug fixes / features)
> - [X ] Docs have been added / updated (for bug fixes / features)
> - [X ] Bugfix
Physical label is not present on either form field
Physical label …
> ACA 2618 - 2619 - Share Dialog - Physical Labels

- demo-shell/src/app/components/files/files.component.html
- e2e/content-services/directives/delete-directive.e2e.ts
- e2e/pages/adf/content-services.page.ts
- lib/core/directives/node-delete.directive.ts
- lib/testing/src/lib/content-services/actions/permission.actions.ts
- lib/testing/src/lib/content-services/actions/public-api.ts
- lib/testing/src/lib/content-services/pages/document-list.page.ts
> AAE-1841 - added delete directive test

- lib/testing/src/lib/core/pages/card-view/card-view-select-item.page.ts
- lib/testing/src/lib/core/pages/card-view/public-api.ts
> - [ ] Bugfix
Creating a PO for adf-card-view-selectitem ADF component, used in AMA …
> [AAE-1772]Add CardSelectItemPage PO

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
> - [x] Bugfix
replace title element not to confuse screen readers
**Does this PR …
> [ACA-2614] fix share link dialog header a11y

- lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/i18n/en.json
> - [x] Bugfix
- remove extra focus from the "inherit" column
- fix layout and a11y
- …
> [ACA-2566][ACA-2567] permissions a11y fixes

- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.html
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
> - [x] Bugfix
partial set of fixes for the calendar card item:
- do not tab on hidden …
> calendar card item a11y fixes

- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-2368
PDF is getting scrolled while editing the content …
> [ACA-2368] UI Issues while editing Metadata in the Preview Page #1091

- lib/core/card-view/card-view.module.ts
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.html
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/i18n/en.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3726
A user can now copy …
> [ADF-3726] Add copy to clipboard support to card view properties

- lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2198 …
> [AAE-2198] Error thrown on start process with pre-selected multiple files on start form.

- lib/process-services/src/lib/process-list/components/process-audit.directive.spec.ts
- lib/process-services/src/lib/process-list/components/process-audit.directive.ts
- package-lock.json
- package.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2041
fixed
**Does this PR …
> [AAE-2041] [APS-1] [ADF] download process audit log not working

- lib/content-services/src/lib/search/components/search-chip-list/search-chip-list.component.scss
- lib/content-services/src/lib/search/components/search-chip-list/search-chip-list.component.ts
- lib/content-services/src/lib/styles/_index.scss
> - [ ] Bugfix
No change of color when chip focused.
The chip turn accent when …
> [ADF-5094] Changed focused chip color

- lib/core/login/components/login.component.html
> - [ ] Bugfix
Color of login's submit button is primary.
Color of login's …
> [ADF-5090] Change color of input button

- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html
> - [ ] Bugfix
Calendar in search-date-range component is by default primary color. …
> [ADF-5093] Change datepicker color

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
> - [x] Bugfix
- fix regression with Share Link dialog (untoggling the expiration date …
> share link: fix regression with expiration toggle

- demo-shell/src/app/components/process-service/process-service.component.html
- docs/process-services/components/start-process.component.md
- lib/process-services/src/lib/process-list/components/start-process.component.html
- lib/process-services/src/lib/process-list/components/start-process.component.scss
- lib/process-services/src/lib/process-list/components/start-process.component.ts
> Start process: Make the title optional

- demo-shell/src/app/components/content-node-selector/content-node-selector.component.html
- docs/content-services/components/content-metadata-card.component.md
- docs/content-services/components/content-node-selector-panel.component.md
- docs/content-services/services/content-node-dialog.service.md
- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.service.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.service.ts
- lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog-component.interface.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.html
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2202
**Does this PR …
> [AAE-2202] Not able to search for files

- demo-shell/src/app.config.json
- docs/content-services/components/content-metadata-card.component.md
- docs/core/components/card-view.component.md
- e2e/process-services-cloud/task-header-cloud.e2e.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/core/card-view/components/card-view-item-dispatcher/card-view-item-dispatcher.component.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/card-view/components/card-view/card-view.component.html
- lib/core/card-view/components/card-view/card-view.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-3726
The possibility of …
> [ADF-3726] Enable/disable Copy to clipboard in Metadata from config

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
> - [x] Bugfix
- revert some of the code introduced earlier
- fix issues with PUT …
> fix shared link dialog regressions

- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- lib/content-services/src/lib/i18n/en.json
> - [x] Bugfix
The title of the uplaod dialog is fixed on the current folder when the dialog open. …
> [AAE-2200] Fix upload dialog title

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.spec.ts
- lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
> - [x] Bugfix
add debouncing for the time update, as distinct does not work correctly …
> share link: add time debouncing

- lib/core/notifications/services/notification.service.spec.ts
- lib/core/notifications/services/notification.service.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Enhancement
Described in #5561
Notification action value gets …
> [#5561] Translate notification action value

- e2e/process-services-cloud/people-group-cloud-component.e2e.ts
> Fix people-group-cloud-filter-component.e2e.ts

- lib/core/services/discovery-api.service.ts
> [ACA-2734] Fix API - Return an error in case the response isn't a json

- e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
- e2e/process-services-cloud/process-filter-results.e2e.ts
- e2e/process-services-cloud/process-filters-cloud.e2e.ts
- e2e/process-services-cloud/process-header-cloud.e2e.ts
- e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts
- e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
- e2e/process-services-cloud/start-process-cloud.e2e.ts
- e2e/process-services-cloud/start-task-form-cloud.e2e.ts
- e2e/protractor.excludes.json
- lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5116
**Does this PR …
> [ADF-5116] Make ADF's pipeline GREEN again

- e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
- e2e/process-services-cloud/process-task-attach-file.e2e.ts
- lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
- lib/testing/src/lib/process-services-cloud/resources/resources.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-1948
**Does this PR …
> [AAE-1948] Form Attach File cloud widget E2E

- e2e/content-services/directives/delete-directive.e2e.ts
- e2e/process-services-cloud/task-header-cloud.e2e.ts
- e2e/process-services-cloud/tasks-custom-filters.e2e.ts
- e2e/protractor.excludes.json
- e2e/protractor/save-remote.js
- e2e/test.config.js
- lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts
- lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
- package-lock.json
- package.json
- protractor.conf.ts
- scripts/test-e2e-lib.sh
- scripts/travis/e2e/content-services-e2e.sh
- scripts/travis/e2e/process-services-cloud-e2e.sh
> - [ ] Bugfix
remove not used report
Fix USERNAME AND PAS upload PS cloud e2e screenshot
Exclude test not working …
> Fix E2E run

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.scss
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
- lib/process-services-cloud/src/lib/styles/_index.scss
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3020
The fileds process name and process definition name …
> [ACA-3020] Start process on process cloud updated the labels (always floating)

- lib/core/comments/comment-list.component.scss
> - [ ] Bugfix
Color of the text in comment has low contrast with its background when a comment is selected. …
> [ACA-2523] Update comment text colors

- docs/process-services/components/process-list.component.md
- docs/process-services/components/task-list.component.md
- lib/process-services/src/lib/process-list/components/process-list.component.html
- lib/process-services/src/lib/process-list/components/process-list.component.ts
- lib/process-services/src/lib/task-list/components/task-list.component.html
- lib/process-services/src/lib/task-list/components/task-list.component.ts
> [ACA-3170]Task/Process Add the sticky header feature

- e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
- e2e/process-services-cloud/process-custom-filters.e2e.ts
- e2e/process-services-cloud/process-header-cloud.e2e.ts
- e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
- e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
- e2e/process-services-cloud/start-task-form-cloud.e2e.ts
- e2e/process-services-cloud/tasks-custom-filters.e2e.ts
- e2e/protractor.excludes.json
- lib/testing/src/lib/core/actions/identity/group-identity.service.ts
- lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/process-header-cloud-component.page.ts
1. C305010
2. C311290
3. C317658
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5118 …
> [ADF-5118] Enable E2E

- e2e/content-services/directives/create-folder-directive.e2e.ts
- e2e/content-services/document-list/document-list-component.e2e.ts
- e2e/content-services/document-list/document-list-permissions.e2e.ts
- e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
- e2e/pages/adf/content-services.page.ts
- e2e/process-services-cloud/process-filter-results.e2e.ts
- e2e/process-services-cloud/process-header-cloud.e2e.ts
- e2e/process-services-cloud/task-header-cloud.e2e.ts
- e2e/protractor.excludes.json
- lib/testing/src/lib/content-services/actions/upload.actions.ts
- lib/testing/src/lib/core/pages/data-table-component.page.ts
- lib/testing/src/lib/core/pages/form/widgets/date-time-widget.page.ts
- lib/testing/src/lib/core/utils/browser-actions.ts
- lib/testing/src/lib/process-services-cloud/pages/people-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
> - [x] Bugfix
Try improve e2e PS cloud  …
> add slower type method for user picker

- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/tree-view/components/tree-view.component.html
- lib/content-services/src/lib/tree-view/components/tree-view.component.scss
- lib/content-services/src/lib/tree-view/components/tree-view.component.spec.ts
> - [x] Bugfix
[MNT-21469](https://issues.alfresco.com/jira/browse/MNT-21469)
**Does …
> [MNT-21469] TreeView component has events on icon only

- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
> - [X] Bugfix
Applying the feature of filtering folders for drag&drop
**Does this PR …
> [ACA-1894] - fixed missing behaviour for drag&drop

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-list/mock/process-list-service.mock.ts
- lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2197 …
> [AAE-2020] Add release version filter for process instances

- lib/testing/src/lib/core/utils/string.util.ts
> - [ ] Bugfix
We need to generate the app names with only lowercase characters …
> [AAE-2456] - Added a new function for generate lowercase and number strings

- lib/content-services/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services/src/lib/i18n/en.json
> - [ ] Bugfix
> - [] Documentation
UI string review …
> [ADF-5132] Review UI strings

- docs/README.md
- docs/core/services/discovery-api.service.md
- docs/core/services/upload.service.md
- docs/process-services-cloud/components/process-filters-cloud.component.md
- docs/process-services-cloud/components/process-list-cloud.component.md
- docs/process-services-cloud/components/task-filters-cloud.component.md
- docs/process-services-cloud/services/start-process-cloud.service.md
- docs/process-services/components/process-filters.component.md
- docs/process-services/components/process-list.component.md
- docs/process-services/components/task-filters.component.md
- docs/process-services/components/task-form.component.md
- docs/process-services/components/task-list.component.md
- docs/versionIndex.md
- scripts/travis/update/update-children.sh
- scripts/travis/update/update-project.sh
> - [ ] Bugfix
documentation update …
> documentation update

- e2e/process-services/comment-component-processes.e2e.ts
- e2e/process-services/custom-process-filters-sorting.e2e.ts
- e2e/process-services/custom-tasks-filters.e2e.ts
- e2e/process-services/process-attachment-list-action-menu.e2e.ts
- e2e/process-services/start-process-component.e2e.ts
- lib/testing/src/lib/core/actions/APS/models.service.ts
- lib/testing/src/lib/core/actions/APS/process.util.ts
- lib/testing/src/lib/process-services/pages/start-process.page.ts
> [ACA-3040]Modify some methods of start-process PO

- lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2505
**Does this PR …
> [AAE-000] fix the start process failing in APW

- e2e/protractor.excludes.json
- scripts/affected-libs.sh
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5122
Uncomment test to see …
> [ADF-5122] Unexclude C309674 test

- e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
- lib/testing/src/lib/process-services-cloud/pages/group-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2505
done
**Does this PR …
> [AAE-2505] [PS cloud] Should not allow to start the process if is not created

- demo-shell/package.json
- lib/cli/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/extensions/package.json
- lib/insights/package.json
- lib/process-services-cloud/package.json
- lib/process-services/package.json
- lib/testing/package.json
- package.json
Update JS-API packages version 3.8.0
> Update JS-API packages version 3.8.0

- lib/cli/README.md
- lib/cli/bin/adf-cli
- lib/cli/package-lock.json
- lib/cli/package.json
- lib/cli/scripts/artifact-from-s3.ts
- lib/cli/scripts/artifact-to-s3.ts
- lib/cli/scripts/docker-publish.ts
- lib/cli/scripts/init-aae-env.ts
- lib/cli/scripts/kubectl-clean-app.ts
- lib/cli/scripts/kubectl-delete.ts
- lib/cli/scripts/kubectl-image.ts
- lib/cli/scripts/npm-publish.ts
- lib/cli/scripts/update-commit-sha.ts
- lib/cli/scripts/update-version.ts
> - [x] Bugfix
- development mode (building CLI in watch mode, linking and running …
> ADF CLI fixes

- .travis.yml
- scripts/git-util/check-branch-updated.sh
- scripts/release/release.sh
- scripts/travis/build/build.sh
- scripts/travis/release/release-npm.sh
- scripts/travis/update/update-project.sh
> - [ ] Bugfix
prepare script to change name development to develop
**Does this PR …
> [AAE-2570] prepare script to change name development to develop

- lib/testing/src/lib/core/actions/identity/query.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5135
done
**Does this PR …
> [ADF-5135] Eventual Consistency Helper for e2e tests.

- lib/testing/src/lib/process-services-cloud/resources/resources.ts
> - [x] Bugfix
The path is outdated and we cannot release anymore from development, it has to be done from develop …
> Fix resources path for releasing apps

- README.md
- e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
- lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
- lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
- lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
>  [AAE-2557] - fixed variable mapping on start process

- e2e/content-services/notifications-component.e2e.ts
- e2e/pages/adf/demo-shell/notification.page.ts
- lib/testing/src/lib/core/pages/public-api.ts
- lib/testing/src/lib/core/pages/snackbar.page.ts
> [ACA-3269]Move notificationPage to adf testing package

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
- licenses.txt
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3273
**Does this PR …
> [ACA-3273] - fix start process empty message

- lib/core/notifications/components/notification-history.component.spec.ts
- lib/core/notifications/components/notification-history.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-2537
**Does this PR …
> [AAE-2537] - fix mark as read notification

- lib/extensions/src/lib/config/action.extensions.ts
> - [ ] Bugfix
Data property is not part of the ContentActionRef type
added data …
> [ACA-3251] Extenssion type data added

- demo-shell/src/app/components/app-layout/cloud/form-demo/cloud-form-demo.component.ts
- demo-shell/src/app/components/form/form.component.ts
- lib/core/services/dynamic-component-mapper.service.ts
- lib/process-services-cloud/src/lib/form/components/cloud-form-rendering.service.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
- lib/process-services-cloud/src/lib/form/form-cloud.module.ts
- lib/process-services-cloud/src/lib/process-services-cloud.module.ts
- lib/process-services/src/lib/form/form.component.ts
- lib/process-services/src/lib/form/process-form-rendering.service.ts
- lib/process-services/src/lib/process.module.ts
- lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
> - [x] Bugfix
prevent Form and Cloud Form creating own instances of the services …
> [ADF-5106] fix stencil registration

- lib/core/app-config/app-config.service.ts
- lib/core/form/services/activiti-alfresco.service.ts
- lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
- lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3245
The repository name is …
> [ACA-3245] Fetch alfresco repo name from an API

- lib/testing/src/lib/core/pages/login-sso.page.ts
- protractor.conf.ts
> Ability to change the route

- e2e/content-services/directives/restore-content-directive.e2e.ts
- e2e/content-services/document-list/document-list-actions.e2e.ts
- lib/testing/src/lib/core/pages/bread-crumb.page.ts
- lib/testing/src/lib/core/pages/public-api.ts
> [ACA-3028]Move breacrumb page to adf testing package

- demo-shell/src/app/components/about/about.component.html
- demo-shell/src/app/components/about/about.component.ts
- lib/core/about/about-github-link/about-github-link.component.html
- lib/core/about/about-github-link/about-github-link.component.spec.ts
- lib/core/about/about-server-settings/about-server-settings.component.html
- lib/core/about/about-server-settings/about-server-settings.component.scss
- lib/core/about/about-server-settings/about-server-settings.component.spec.ts
- lib/core/about/about-server-settings/about-server-settings.component.ts
- lib/core/about/about.module.ts
- lib/core/about/public-api.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3317
As part of the task …
> [ACA-3317] Split About component into smaller components

- lib/testing/src/lib/process-services-cloud/resources/resources.ts
> - [ ] Bugfix
i've updated the resources file with the name of the new form & processes added in simpleapp
**What …
> updated resources file with the new added form & processes

- lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
- lib/core/about/about-github-link/about-github-link.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3317
Make About Github Link …
> [ACA-3317] Make About Github Link Component input properties optional

- lib/process-services/src/lib/process-list/components/process-filters.component.ts
- lib/process-services/src/lib/process-list/services/process-filter.service.ts
- lib/process-services/src/lib/task-list/services/task-filter.service.spec.ts
- lib/process-services/src/lib/task-list/services/task-filter.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3326
Index was added in the …
> [ACA-3326] Create the default filters following the new order

- lib/testing/src/lib/core/pages/data-table/column.ts
- lib/testing/src/lib/core/pages/data-table/data-table-builder.ts
- lib/testing/src/lib/core/pages/data-table/data-table-item.ts
- lib/testing/src/lib/core/pages/data-table/date-column.ts
- lib/testing/src/lib/core/pages/data-table/public-api.ts
- lib/testing/src/lib/core/pages/data-table/text-column.ts
…om adf testing package]. Currently the majority of the methods that we have on this class are working only on 'text' column type. The scope of this PR was to make them work on all types of columns (text, image, date, fileSize, location, json) and also custom columns that may be created on different applications or other pages.
> - [ ] Bugfix
> - [ ] Code style update (formatting, local …
> [ACA-2989]Creating data-table-component PO to support all kind of columns, including custom

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
- lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3271
**Does this PR …
> [ACA-3271] START PROCESS button is inactive first time when process model is loaded

- lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-2975
**Does this PR …
> [ACA-2975] fix start process wrong response

- lib/process-services/src/lib/process-list/components/start-process.component.html
- lib/process-services/src/lib/process-list/components/start-process.component.scss
- lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3359
**Does this PR …
> [ACA-3359] Disable processName/ProcessDefintions drop down if no application selected.

- lib/core/form/components/form-field/form-field.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3286
**Does this PR …
> [ACA-3286] User gets error when removing the attached file

- lib/core/form/components/form-field/form-field.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.ts
Reverts Alfresco/alfresco-ng2-components#5735
> Revert "[ACA-3286] User gets error when removing the attached file"

- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
> - [x] Bugfix
See https://issues.alfresco.com/jira/browse/ACA-3074
Fixed
**Does this …
> [ACA-3074] Fix preselected file loading issue

- lib/core/services/sites.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5154
This PR only exposes …
> [ADF-5154] Add missing API endpoints to SitesService

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
> - [ X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
Currently the share dialog is missing a persistent label on the expiration date field
**What is the …
> [ACA-2618] - fix: addition of persistent label

- lib/testing/src/lib/core/actions/api.ts
- lib/testing/src/lib/core/models/public-api.ts
- lib/testing/src/lib/core/utils/browser-actions.ts
- lib/testing/src/lib/process-services-cloud/actions/application.ts
- lib/testing/src/lib/process-services-cloud/actions/descriptor.ts
- lib/testing/src/lib/process-services-cloud/actions/modeling-api.ts
- lib/testing/src/lib/process-services-cloud/actions/project.ts
simplify api
> - [ ] Bugfix
add export missing model …
> add export missing model

- lib/testing/src/lib/core/actions/api.service.ts
> - [x] Bugfix
not use testconfig if is not present …
> not use testconfig if is not present

- lib/testing/src/lib/core/actions/api.service.ts
> - [x] Bugfix
improve api service configuration …
> improve api service configuration

- lib/content-services/src/lib/document-list/components/document-list.component.ts
> - [x] Bugfix
Show WIP inside document-list.
This work is still there but hidden as …
> Hide WIP filter inside document-list

- lib/core/templates/empty-content/empty-content.component.scss
> [ACA-3358] Fix icon opacity 

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3292
**Does this PR …
> [ACA_3292] - Add queued task as part of default task filter

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/src/lib/document-list/components/document-list.component.html
- lib/content-services/src/lib/document-list/components/document-list.component.scss
- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/mock/document-list.component.mock.ts
- lib/content-services/src/lib/search/base-query-builder.service.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.html
- lib/content-services/src/lib/search/components/search-header/search-header.component.scss
- lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
- lib/content-services/src/lib/search/components/search-slider/search-slider.component.html
- lib/content-services/src/lib/styles/_index.scss
- lib/core/datatable/components/datatable/datatable.component.scss
> Dev baptiste aca 3430

- lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
> - [x] Bugfix
Fix start process e2e page …
> Fix start process e2e page

- lib/testing/src/lib/core/pages/bread-crumb.page.ts
> Check for presence of the element before getText() in BreadcrumbPage PO.

- e2e/process-services-cloud/edit-process-filters-component.e2e.ts
- e2e/process-services-cloud/process-custom-filters.e2e.ts
- e2e/process-services-cloud/process-filters-cloud.e2e.ts
- e2e/process-services-cloud/process-header-cloud.e2e.ts
- e2e/process-services-cloud/process-list-cloud-action-menu.e2e.ts
- e2e/process-services-cloud/process-list-selection-cloud.e2e.ts
- e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
- e2e/process-services-cloud/start-process-cloud.e2e.ts
- e2e/process-services-cloud/start-task-form-cloud.e2e.ts
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Change required for DW
https://issues.alfresco.com/jira/browse/ACA-3109 …
> [ACA-3109] Change order of default process filters for DW

- lib/cli/README.md
- lib/cli/scripts/kubectl-image.ts
> Ability to set the image of pods based on label

- lib/cli/README.md
- lib/cli/scripts/kubectl-image.ts
Reverts Alfresco/alfresco-ng2-components#5781
> Revert "Ability to set the image of pods based on label"

- lib/cli/README.md
- lib/cli/scripts/kubectl-image.ts
> adf-cli k8s image - Be able to override image by label and namespace

- lib/core/form/components/widgets/amount/amount.widget.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3454
**Does this PR …
> [ACA-3454] disable floating label for ammount

- lib/testing/src/lib/process-services-cloud/resources/resources.ts
> - [ ] Bugfix
> - [x] Other... Please describe: E2E resources …
> Add attach file forms and processes to resources file

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
- lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3461
**Does this PR …
> [ACA-3461] Start Process - show form for preselected process

- lib/content-services/src/lib/permission-manager/components/add-permission/search-config-permission.service.ts
- lib/content-services/src/lib/permission-manager/public-api.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5161
This service can have …
> [ADF-5161] Add query token injection for search query builder

- lib/core/datatable/components/datatable-cell/datatable-cell.component.spec.ts
- lib/core/datatable/components/datatable-cell/datatable-cell.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3474
done
**Does this PR …
> [ACA-3474] [Info Drawer] Error on save 

- lib/content-services/src/lib/search/components/search-header/search-header.component.html
> - [ ] Bugfix
Removed a color code from the html that was not used
**Does this PR …
> [ACA-3426] - removed not used color code

- docs/README.md
- docs/content-services/components/document-list.component.md
- docs/content-services/components/search-header.component.md
- docs/content-services/services/search-query-builder.service.md
- docs/core/components/datatable.component.md
- docs/core/services/card-item-types.service.md
- docs/core/services/form-rendering.service.md
- docs/core/services/sites.service.md
- docs/extensions/services/extension.service.md
- docs/process-services-cloud/components/process-list-cloud.component.md
- docs/process-services-cloud/components/task-form-cloud.component.md
- docs/process-services-cloud/components/task-list-cloud.component.md
- docs/process-services-cloud/directives/claim-task-cloud.directive.md
- docs/process-services-cloud/pipes/process-name-cloud.pipe.md
- docs/process-services-cloud/services/form-cloud.service.md
- docs/process-services-cloud/services/start-process-cloud.service.md
- docs/process-services/components/process-list.component.md
- docs/process-services/components/start-process.component.md
- docs/process-services/components/task-form.component.md
- docs/process-services/components/task-header.component.md
- docs/process-services/components/task-list.component.md
- docs/process-services/directives/claim-task.directive.md
- docs/process-services/pipes/process-name.pipe.md
- docs/process-services/services/process-filter.service.md
- docs/process-services/services/task-filter.service.md
- docs/versionIndex.md
- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
- scripts/travis/update/update-children.sh
- scripts/travis/update/update-project.sh
- scripts/update-version.sh
> - [ ] Bugfix
Documentation review …
> Documentation review

- lib/testing/src/lib/core/utils/logger.ts
> - [ ] Bugfix
error message if log level is set with wrong name
**Does this PR …
> error message if log level is set with wrong name

- lib/testing/src/lib/core/utils/browser-actions.ts
> - [ ] Bugfix
Update browser-actions.ts to warn instead of error when needs to backup on clickscript
**What is the …
> Update browser-actions.ts to warn instead of error

- e2e/core/viewer/file-extensions/viewer-excel.component.e2e.ts
- e2e/core/viewer/file-extensions/viewer-image.component.e2e.ts
- e2e/core/viewer/file-extensions/viewer-powerpoint.component.e2e.ts
- e2e/core/viewer/file-extensions/viewer-text.component.e2e.ts
- e2e/core/viewer/file-extensions/viewer-word.component.e2e.ts
- lib/core/styles/_index.scss
- lib/core/viewer/components/unknown-format/unknown-format.component.html
- lib/core/viewer/components/unknown-format/unknown-format.component.scss
- lib/testing/src/lib/core/pages/viewer.page.ts
> - [x] Bugfix
For dark theming the unknown text field is not readable 
**Does this PR …
> Fix unknown style

- lib/core/form/components/widgets/date-time/date-time.widget.html
- lib/core/form/components/widgets/date-time/date-time.widget.scss
- lib/core/form/components/widgets/date/date.widget.html
- lib/core/form/components/widgets/date/date.widget.scss
- lib/core/form/components/widgets/multiline-text/multiline-text.widget.html
- lib/core/form/components/widgets/multiline-text/multiline-text.widget.scss
- lib/core/form/components/widgets/number/number.widget.html
- lib/core/form/components/widgets/number/number.widget.scss
- lib/core/form/components/widgets/text/text.widget.scss
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5163
Placeholder layout …
> [ADF-5163] [Regression] Fix placeholder on Form widgets

- lib/process-services/src/lib/i18n/en.json
- lib/process-services/src/lib/task-list/components/task-form/task-form.component.html
- lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5167
**Does this PR …
> [ADF-5167] [FORM] Task action name inconsistency

- demo-shell/src/app/components/search/search-result.component.ts
- lib/content-services/src/lib/search/search.module.ts
> - [X] Bugfix
User doesn't need to add the @Inject in the constructor of the classes …
> [ACA-3520] - fixed providing by default of the service

- demo-shell/src/app.config.json
> Fixed search configuration to look for facet widgets

- lib/cli/scripts/kubectl-clean-app.ts
> Fix the js-api instance and remove access to the database

- demo-shell/src/app.config.json
- docs/content-services/components/search-text.component.md
- lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.ts
- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.html
- lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
- lib/content-services/src/lib/search/components/search-number-range/search-number-range.component.ts
- lib/content-services/src/lib/search/components/search-radio/search-radio.component.ts
- lib/content-services/src/lib/search/components/search-text/search-text.component.ts
- lib/content-services/src/lib/search/components/search-widget-container/search-widget-container.component.ts
- lib/content-services/src/lib/search/search-header-query-builder.service.spec.ts
- lib/content-services/src/lib/search/search-header-query-builder.service.ts
- lib/content-services/src/lib/search/search-widget.interface.ts
fix navigation
add new property search text prefix and suffix
> - [x] Bugfix
Can't make a search with only one letter …
> [ACA-3507] [ACA-3523] Fix Filters

- lib/cli/scripts/kubectl-clean-app.ts
> adf-cli clean script - Be able to delete based on time

- lib/testing/src/lib/core/pages/login-sso.page.ts
> - [ ] Bugfix
The login page is using the default protractor action to navigate to a URL …
> AAE-2972 Use BrowserActions in login page

- lib/process-services/src/lib/mock/process/start-process.component.mock.ts
- lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3548
**Does this PR …
> [ACA-3548] Convert Start Process manual cases to unit tests

- lib/cli/scripts/init-aae-env.ts
- scripts/build/build-cli.sh
> adf-cli - return the project release

- .travis.yml
- Dockerfile
> Travis: Fix the path for the docker image

- lib/testing/src/lib/core/pages/login-sso.page.ts
> use the tag and not id because does not exist

- lib/testing/src/lib/process-services-cloud/resources/resources.json
Update adf-testing resources.json file with:
* Add forms with attach file widgets(single, multiple, local)
* Add processes with the above forms on start event 
> - [ ] Bugfix
> - [x] Other... Please describe: New resources for …
> [ACA-3373] Add resources for Process Cloud e2e tests

- scripts/travis/build/build.sh
> Update the adf deps before install

- docs/insights/components/analytics-report-list.component.md
> [#5858] Fix elements of tags

- docs/process-services/components/process-list.component.md
> [#5860] Fix end tag.

- docs/core/components/start-form.component.md
- lib/process-services/src/lib/form/start-form.component.ts
> Update start-form.component documentation

- docs/process-services/components/process-instance-header.component.md
- lib/core/app-config/schema.json
- lib/process-services/src/lib/process-list/components/process-instance-header.component.spec.ts
- lib/process-services/src/lib/process-list/components/process-instance-header.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3596
**Does this PR …
> [ACA-3596] process-header change assignee property key to createdBy

- demo-shell/src/app.config.json
> - [ ] Bugfix
When filtering for size folders will be always showed.
**Does this PR …
> [ADF-5179] - added folders for size filters

- lib/content-services/src/lib/document-list/components/library-role-column/library-role-column.component.spec.ts
- lib/content-services/src/lib/document-list/components/library-role-column/library-role-column.component.ts
- lib/content-services/src/lib/i18n/en.json
> - [ ] Bugfix
Deafult site role added …
> [ACA-3613] Inconsistent role value between library views

- lib/testing/src/lib/core/actions/users.actions.ts
> - [ ] Bugfix
Added try catch to every user creation: on ECM, on APS1 and on …
> [dev-crisj-ACA-3611]Refactor createUser method

- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3073
**Does this PR …
> [AAE-3073] Fix error  due to formatSorting() in APW

- lib/content-services/src/lib/upload/components/upload-button.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3739
Can't upload a new version from browse files mode. …
> [ACA-3739] Can't upload a new version

- lib/core/pagination/pagination.component.spec.ts
- lib/core/pagination/pagination.component.ts
> - [x] Bugfix
- slightly rework and cleanup pagination component to be compatible …
> fix pagination issues

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
Reverts Alfresco/alfresco-ng2-components#5882
This change trigger too many change events
> Revert "[ACA-3499] Card View Textitem update on change"

- docs/content-services/components/content-node-selector-panel.component.md
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3114
**Does this PR …
> [AAE-3114] Ability to restrict search to a root folder

- lib/core/directives/version-compatibility.directive.ts
- lib/core/services/version-compatibility.service.spec.ts
- lib/core/services/version-compatibility.service.ts
> - [ ] Bugfix
Better acs versioning
https://issues.alfresco.com/jira/browse/ACA-3765 …
> [ACA-3765] [ADF] move reusable versioning logic

- demo-shell/src/app/app.module.ts
- demo-shell/src/app/components/cloud/start-process-cloud-demo.component.ts
- docs/content-services/components/content-node-selector-panel.component.md
- docs/content-services/components/document-list.component.md
- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
- lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
- lib/process-services-cloud/src/lib/process-services-cloud.module.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
> [AAE-3115] Content node selector - Ability to select multiple files

- scripts/test-e2e-lib.sh
> Use travis chrome version

- cspell.json
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/card-view/models/card-view-baseitem.model.spec.ts
- lib/core/card-view/models/card-view-baseitem.model.ts
- lib/core/card-view/models/card-view-floatitem.model.spec.ts
- lib/core/card-view/models/card-view-intitem.model.spec.ts
- lib/core/card-view/models/card-view-textitem.model.spec.ts
- lib/core/card-view/validators/card-view-item-length.valiator.ts
- lib/core/card-view/validators/card-view-item-match.valiator.ts
- lib/core/card-view/validators/card-view-item-minmax.valiator.ts
- lib/core/card-view/validators/card-view.validators.ts
- lib/core/card-view/validators/validators.map.ts
- lib/core/i18n/en.json
> - [ ] Bugfix
[ACA-3742](https://issues.alfresco.com/jira/browse/ACA-3742)
**Does …
> [ACA-3742] Metadata - constraints validation

- lib/core/services/nodes-api.service.ts
> - [ ] Bugfix
[ADF-5201](https://issues.alfresco.com/jira/browse/ADF-5201)
**Does …
> [ADF-5201] Metadata - Update node pass 'definition' field

- e2e/process-services-cloud/edit-task-filters-component.e2e.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3751
**Does this PR …
> [ACA-3751] Disable save & delete buttons for default task filters

- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/file-view/file-view.component.html
- demo-shell/src/app/components/file-view/file-view.component.ts
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.html
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
- demo-shell/src/app/services/preview.service.ts
- docs/content-services/components/version-list.component.md
- docs/content-services/components/version-manager.component.md
- docs/core/components/viewer.component.md
- docs/core/directives/node-download.directive.md
- e2e/content-services/version/version-actions.e2e.ts
- e2e/core/pages/version-manager.page.ts
- e2e/core/viewer/viewer-custom-toolbar-info-drawer.e2e.ts
- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/version-manager/version-list.component.html
- lib/content-services/src/lib/version-manager/version-list.component.spec.ts
- lib/content-services/src/lib/version-manager/version-list.component.ts
- lib/content-services/src/lib/version-manager/version-manager.component.html
- lib/content-services/src/lib/version-manager/version-manager.component.spec.ts
- lib/content-services/src/lib/version-manager/version-manager.component.ts
- lib/core/directives/node-download.directive.spec.ts
- lib/core/directives/node-download.directive.ts
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.ts
- lib/core/viewer/services/view-util.service.ts
- lib/testing/src/lib/core/pages/viewer.page.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-100
**Does this PR …
> [ACA-100] View a previous version 

- docs/process-services-cloud/components/task-header-cloud.component.md
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.scss
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3107
**Does this PR …
> [ACA-3107] add possibility to hide task name from the sidenav

- lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3162
**Does this PR …
> [AAE-3162] [ADF-APS1] Local storage option of attach file widget is not displayed

- lib/process-services-cloud/src/lib/i18n/en.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3637
**Does this PR …
> [ACA-3645] add missing task list translation key

- e2e/process-services/pages/process-details.page.ts
- e2e/process-services/process-instance-details.e2e.ts
- e2e/process-services/start-process-component.e2e.ts
- e2e/protractor.excludes.json
- lib/testing/src/lib/core/pages/card-view/card-view-date-item.page.ts
- lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts
- lib/testing/src/lib/core/pages/data-table/column.ts
- lib/testing/src/lib/core/pages/data-table/data-table-item.ts
- lib/testing/src/lib/core/pages/info-drawer.page.ts
- lib/testing/src/lib/core/pages/material/tabs.page.ts
- lib/testing/src/lib/core/pages/public-api.ts
- lib/testing/src/lib/process-services/pages/process-instance-header.page.ts
- lib/testing/src/lib/process-services/pages/public-api.ts
- lib/testing/src/lib/process-services/pages/task-header.page.ts
- scripts/test-e2e-lib.sh
> [ACA-3590]Created process-instance-header, info-drawer and task-header POs

- docs/content-services/components/content-node-selector-panel.component.md
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
> [AAE-3113] Node selector - Be able to restrict the breadcrums to a specific root

- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
* Made processDefinitionName optional
> - [x] Bugfix
Error thrown in ADW unit test …
> [ACA-3687] Implement Process definition name filter dropdown in Process List

- .gitignore
- e2e/protractor.conf.js
> - [ ] Bugfix
Improve smart runner configuration …
> Improve smart runner

- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3208
**Does this PR …
> [AAE-3208] Remove local file widget param for attach-file-cloud-widget

- docs/process-services-cloud/components/edit-process-filter-cloud.component.md
- docs/process-services-cloud/components/edit-task-filter-cloud.component.md
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3727
**Does this PR …
> [ACA-3727] - Process Filters add possibility to hide process filter name

- docs/process-services-cloud/components/edit-task-filter-cloud.component.md
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3728
**Does this PR …
> [ACA-3728] Remove the filter name from the custom filter header

- demo-shell/src/app/components/files/files.component.html
> - [ ] Bugfix
Not sortable id and lock in demo shell …
> Not sortable id and lock in demo shell

- CONTRIBUTING.md
> [#5950] Fix branch name.

- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3762
**Does this PR …
> [ACA-3762] Task/Process filters not working with updatePagination

- docs/process-services/components/process-instance-details.component.md
> [#5956] Property enclose in []

- e2e/protractor.excludes.json
> - [ ] Bugfix
excluded C286516 …
> excluded C286516

- e2e/protractor.excludes.json
> - [ ] Bugfix
Remove excluded test  …
> [AAE-296] Remove excluded test

- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3551
**Does this PR …
> [ACA-3551] - Change icon for the view option

- lib/core/i18n/en.json
> - [ ] Bugfix
[ACA-3742](https://issues.alfresco.com/jira/browse/ACA-3742)
**Does …
> [ACA-3742] - update i18n error strings

- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/services/widget-visibility-cloud.service.spec.ts
- lib/core/form/services/widget-visibility.service.spec.ts
- lib/core/form/services/widget-visibility.service.ts
> - [X] Bugfix
visibility condition for label radio box …
> [ADF-5159] fix visibility condition for label radio box

- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
> - [X] Bugfix
Set the parent when current folder id change for search-headers.
**Does …
> Fixed parent changing for search header

- lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts
> - [ ] Bugfix
add the `loaded` event for the process header so that applications can …
> [ADF-5198] process header loaded event

- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/mock/form/form.component.mock.ts
- lib/core/pagination/pagination.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
- lib/process-services/src/lib/form/form.component.spec.ts
> - [X] Bugfix
fix save not modified Form with dropdown …
> [AAE-2984] fix save not modified Form with dropdown

- lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
> [ADF-5165] - added involved user for task

- docs/content-services/components/content-node-selector.component.md
- lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
> - [ ] Bugfix
update doc node selector and interface …
> update doc node selector and interface

- lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3203
The tooltip was …
> [AAE-2378] Add tooltip to People and Group Cloud Widgets

- lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
> - [x] Bugfix
[ACA-3839](https://issues.alfresco.com/jira/browse/ACA-3839)
**Does …
> [ACA-3839] Document List - clear filter called multiple times

- lib/content-services/src/lib/search/components/search-widget-container/search-widget-container.component.ts
> - [X] Bugfix
Search header filters are not reapplied when refreshing the page
Search …
> [ACA-3506] - Fixed refresh for filters on ADF

- lib/process-services/src/lib/mock/task/task-details.mock.ts
- lib/process-services/src/lib/task-list/components/task-form/task-form.component.html
- lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts
- lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5165
**Does this PR …
> [ADF-5165][Form] Save button is not displayed for Involved task

- lib/core/viewer/components/pdf-viewer-thumb.component.spec.ts
- lib/core/viewer/components/pdf-viewer-thumb.component.ts
- lib/core/viewer/components/pdf-viewer-thumbnails.component.spec.ts
- lib/core/viewer/components/pdf-viewer-thumbnails.component.ts
- package-lock.json
- package.json
> - [X] Bugfix
fix use of more recent pdf viewer versions …
> [ACA-3853] fix use of more recent pdf viewer versions

- angular.json
> - [ ] Bugfix
fix commonjs errors on demo shell startup …
> [ADF-5211] fix commonjs warnings

- lib/core/viewer/services/view-util.service.ts
> - [x] Bugfix
fix error in preview …
> [ACA-3854] fix error in preview

- e2e/content-services/version/version-permissions.e2e.ts
- e2e/protractor.excludes.json
- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- nx.json
> - [ ] Bugfix
Execute test when change exclude file …
> Execute test when change exclude file

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/files/filtered-search.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3542
The filter sorting …
> [ACA-3542] Fix Filter sorting initialization

- lib/core/datatable/directives/drop-zone.directive.ts
- lib/core/directives/upload.directive.spec.ts
- lib/core/directives/upload.directive.ts
> - [ ] Bugfix
add "copy" effect to drag/drop components …
> drag and drop improvements (copy effect)

- scripts/ci/utils/artifact-to-s3.sh
> - [ ] Bugfix
less log output during caching …
> less talkative caching

- lib/testing/src/lib/core/actions/identity/query.service.ts
* Get application process instances by status
> - [ ] Bugfix
> - [x] Other... Please describe: E2E improvement
**Does …
> [ACA-3863] Add query-service call for E2E tests

- docs/content-services/services/audit.service.md
- lib/content-services/src/lib/audit/audit.service.spec.ts
- lib/content-services/src/lib/audit/audit.service.ts
> - [ ] Bugfix
Since there is no AuditService, we need to use the [Audit …
> New Service create - AuditService

- package-lock.json
- package.json
Reverts Alfresco/alfresco-ng2-components#6034
> Revert "Bump scss-bundle from 2.3.2 to 3.1.2"

- lib/testing/src/lib/core/pages/data-table/data-table-item.ts
> [ACA-3800]Add method to datatable PO for selecting row with CMD

- lib/core/services/identity-group.service.ts
> - [ ] Bugfix
- adds missing `getAssignedRoles` and `getEffectiveRoles` APIs to the …
> add missing group role APIs

- lib/process-services-cloud/src/lib/i18n/en.json
> [ACA-3737] Process cloud properties review labels

- lib/core/services/oauth2.service.ts
> - [x] Bugfix
fix the regression with the PUT method instead of POST for group …
> fix http method regression

- lib/cli/scripts/npm-publish.ts
- package-lock.json
- package.json
- scripts/travis/build/build.sh
> publish improvements

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.service.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.service.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3406
**Does this PR …
> [AAE-3406] - Fix advanced search inside content-node selector

- lib/core/services/auth-guard-ecm.service.ts
> [MNT-21636] - added redirection when SSO is enabled for external link

- demo-shell/src/app/components/process-service/process-attachments.component.ts
- demo-shell/src/app/components/process-service/task-attachments.component.ts
- lib/core/services/discovery-api.service.ts
- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
- lib/process-services/src/lib/task-list/services/process-upload.service.ts
- lib/process-services/src/lib/task-list/services/task-upload.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/MNT-21789
rendition will be …
> [MNT-21789] ADW - Disable ACS Thumbnail Generation cause ADF Upload Service to fail any file upload with 501 error

- demo-shell/src/app/app.module.ts
- demo-shell/src/app/app.routes.ts
- demo-shell/src/app/components/app-layout/cloud/form-demo/cloud-form-demo.component.ts
- demo-shell/src/app/components/cloud/custom-form-components/sample-widget.component.ts
- demo-shell/src/app/components/cloud/process-cloud-layout.component.ts
> - [ ] Bugfix
Tested the following for custom widgets:
**Note:** create widget named …
> [Docs] cloud custom form widget examples

- docs/process-services-cloud/components/process-list-cloud.component.md
- docs/process-services-cloud/services/start-process-cloud.service.md
- docs/process-services-cloud/services/task-cloud.service.md
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3623
**Does this PR …
> [ACA-3623] Process definition name filter in task list

- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3507
**Does this PR …
> [AAE-3507] ADF - Change default destination folder alias -root- to -my-

- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
> [ACA-3884] AttachFileCloud - Pass the replaced value

- lib/cli/scripts/check-cs-env.ts
> Sanity check - Be able to pass params

- e2e/protractor.excludes.json
- lib/core/services/version-compatibility.service.spec.ts
- lib/core/services/version-compatibility.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5237
Unexclude C362240 and …
> [ADF-5237] Unexclude C362240 and C362241

- demo-shell/src/app.config.json
- e2e/process-services-cloud/edit-process-filters-component.e2e.ts
- e2e/process-services-cloud/process-custom-filters.e2e.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.html
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3722
**Does this PR …
> [ACA-3722] - rename process name sort option

- lib/core/form/components/widgets/core/form-field-types.ts
- lib/core/form/components/widgets/core/form.model.spec.ts
- lib/core/form/components/widgets/core/form.model.ts
- lib/core/form/components/widgets/core/index.ts
- lib/core/form/components/widgets/core/upload-widget-content-link.model.ts
- lib/core/form/components/widgets/file-viewer/file-viewer.widget.html
- lib/core/form/components/widgets/file-viewer/file-viewer.widget.scss
- lib/core/form/components/widgets/file-viewer/file-viewer.widget.ts
- lib/core/form/components/widgets/index.ts
- lib/core/form/form-base.module.ts
- lib/core/form/services/form-rendering.service.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.scss
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
- lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
- lib/process-services-cloud/src/lib/services/form-fields.interfaces.ts
- lib/process-services-cloud/src/lib/styles/_index.scss
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3514 …
> [AAE-3514] Create file viewer widget

- e2e/process-services-cloud/task-list-properties.e2e.ts
- e2e/process-services-cloud/task-list-selection.e2e.ts
- e2e/protractor.excludes.json
- lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5245
[ADF-5245] Fix …
> [ADF-5245] Fix C297478, C297485 and C297472

- e2e/process-services-cloud/people-group-cloud-filter-component.e2e.ts
- e2e/process-services-cloud/start-task/start-task-group-cloud.e2e.ts
- e2e/protractor.excludes.json
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5241
https://issues.alfresco.com/jira/browse/ADF-5243 …
> [ADF-5241] [ADF-5243] [ADF-5244] Fix C291954, C291955, C291993 and C291995

- lib/cli/scripts/kubectl-image.ts
> [ACA-3973] K8s - namespaces - Replace all the occurrences

- .travis.yml
- e2e/content-services/directives/favorite-directive.e2e.ts
- e2e/core/pages/login-shell.page.ts
- e2e/core/pages/notification.page.ts
- e2e/core/settings-component.e2e.ts
- e2e/process-services-cloud/task-list-properties.e2e.ts
- e2e/process-services/custom-tasks-filters.e2e.ts
- e2e/search/components/search-check-list.e2e.ts
- lib/testing/src/lib/core/pages/data-table-component.page.ts
- lib/testing/src/lib/core/pages/login.page.ts
- lib/testing/src/lib/core/pages/snackbar.page.ts
- lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
> Test improve

- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
- lib/process-services-cloud/src/lib/models/date-cloud-filter.model.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3683
**Does this PR …
> [ACA-3683] - implement started date process filter

- e2e/process-services/attach-file-content-service.e2e.ts
- e2e/process-services/attach-folder.e2e.ts
- e2e/process-services/standalone-task.e2e.ts
- e2e/protractor.excludes.json
- lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
- lib/testing/src/lib/core/actions/api.service.ts
- lib/testing/src/lib/core/actions/public-api.ts
- lib/testing/src/lib/core/actions/search.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5236
fixed
**Does this PR …
> [ADF-5236] C246534 Failing

- docs/process-services/components/form.component.md
- lib/core/form/components/form-renderer.component.spec.ts
- lib/core/form/components/widgets/container/container.widget.html
- lib/core/form/components/widgets/container/container.widget.scss
- lib/core/form/components/widgets/container/container.widget.spec.ts
- lib/core/form/components/widgets/container/container.widget.ts
- lib/core/form/components/widgets/core/form.model.ts
- lib/core/form/services/form.service.ts
- lib/process-services/src/lib/form/form.component.ts
> - [X] Bugfix
Hidden Fiels still keeps taking space into the form page 
Hidden fields …
> [MNT-21705] - fixed column display for fields

- lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.html
> - [x] Bugfix
[ACA-3903](https://issues.alfresco.com/jira/browse/ACA-3903)
**Does …
> [ACA-3903] DocumentList - header filters are missing aria-labels

- lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
* Update performed in EditTaskFilterCloudComponentPage and EditProcessFilterCloudComponentPage
> - [ ] Bugfix
> - [x] Other... Please describe: Update customize filter locator
**What is the current behaviour?** (You can also …
> [ACA-3689] Update customize filter locator

- lib/process-services-cloud/src/lib/task/task-filters/public-api.ts
> - [x] Bugfix
Expose ServiceTaskListCloudComponent in public api
**Does this PR …
> [AAE-3469] Expose ServiceTaskListCloudComponent in public api

- lib/process-services-cloud/src/lib/task/task-filters/public-api.ts
> Expose ServiceTaskFilterCloudService in public API

- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
- lib/process-services-cloud/src/public-api.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3651
**Does this PR …
> [AAE-3651] FE - Export DateCloudFilterType from process-services-cloud lib

- demo-shell/src/app/components/form/form.component.html
- demo-shell/src/app/components/form/form.component.ts
- demo-shell/src/app/services/in-memory-form.service.ts
> - [ ] Bugfix
Adding testing system for the form hide/keep space for hidden fields …
> Added switch to be able to check the form behaviour

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/dialogs/download-zip/download-zip.dialog.spec.ts
- lib/core/login/components/login.component.spec.ts
> - [x] Bugfix
- fix rxjs imports that result in double-bundling of the library
**Does …
> fix rxjs imports

- demo-shell/src/app/components/cloud/service-task-list-cloud-demo.component.html
- demo-shell/src/app/components/cloud/service-task-list-cloud-demo.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/service-task-filter-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5260
The service task list …
> [ADF-5260] Fix Service task list initialization in DemoShell

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
> - [ ] Bugfix
[ACA-3626](https://issues.alfresco.com/jira/browse/ACA-3626)
**Does …
> [ACA-3626] Cloud Task - completed date filter 

- lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
Add process definition name selection
> - [ ] Bugfix
> - [x] Other... Please describe: Update in adf-testing package …
> [ACA-3689] Update edit-process-filter-cloud-component PO

- e2e/process-services-cloud/task-list-properties.e2e.ts
- e2e/protractor.excludes.json
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.ts
- lib/process-services-cloud/src/lib/models/date-cloud-filter.model.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-4010
**Does this PR …
> [ACA-3010] - Process/Task Cloud fix wrong date range

- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3627
**Does this PR …
> [ACA-3627] - Add completedBy filter again

- lib/core/toolbar/toolbar.component.html
- lib/core/toolbar/toolbar.module.ts
> - [ ] Bugfix
minimal change to add i18n support to the toolbar title attribute …
> add support for toolbar title i18n

- lib/content-services/src/lib/search/base-query-builder.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5262
The execution method …
> [ADF-5262] Fix query execution in BaseQueryBuilderService

- lib/core/form/components/form-renderer.component.spec.ts
- lib/core/form/components/mock/form-renderer.component.mock.ts
> [ADF-5259] - addded unit test for custom widget

- e2e/content-services/directives/create-library-directive.e2e.ts
- e2e/content-services/directives/favorite-directive.e2e.ts
- e2e/content-services/document-list/document-list-pagination.e2e.ts
- e2e/content-services/document-list/document-list-properties.e2e.ts
- e2e/core/pages/dialog/create-library-dialog.page.ts
- e2e/core/pages/navigation-bar.page.ts
- e2e/process-services-cloud/pages/tasks-cloud-demo.page.ts
- e2e/process-services/info-drawer.e2e.ts
- e2e/process-services/pages/task-details.page.ts
- e2e/process-services/widgets/hyperlink-widget.e2e.ts
- e2e/protractor.conf.js
- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/content-services/src/lib/document-list/services/document-list.service.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
- lib/process-services/src/lib/app-list/apps-list.component.spec.ts
- lib/testing/src/lib/core/pages/card-view/card-view-text-item.page.ts
- lib/testing/src/lib/core/pages/data-table-component.page.ts
- lib/testing/src/lib/core/pages/viewer.page.ts
- package-lock.json
- scripts/travis/e2e/content-services-e2e.sh
- scripts/travis/e2e/core-e2e.sh
- scripts/travis/e2e/insights-e2e.sh
- scripts/travis/e2e/process-services-cloud-e2e.sh
- scripts/travis/e2e/process-services-e2e.sh
- scripts/travis/e2e/search-e2e.sh
> - [x] Bugfix
Empty page displayed all the time when load content fix 
**Does this PR …
> [ADF-5263] Empty page displayed all the time when load content fix 

- lib/extensions/src/lib/config/document-list.extensions.ts
- lib/extensions/src/lib/config/navbar.extensions.ts
> - [x] Bugfix
- add the interface property that is used by ACA and needs for clean …
> add missing interface property

- e2e/process-services-cloud/task-list-properties.e2e.ts
- e2e/protractor.excludes.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5261
fixed
**Does this PR …
> [ADF-5261] Fix excluded flaky tests C297689, C297690

- docs/content-services/components/search-filter.component.md
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- lib/content-services/src/lib/i18n/en.json
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3637
**Does this PR …
> [AAE-3637] Attach file - Upload button is not disabled when the user is in search mode

- lib/process-services/src/lib/i18n/en.json
> [AAE-3764]Fix typo for CLAIM button on form - process services

- lib/content-services/src/lib/search/components/search-panel/search-panel.component.html
- lib/content-services/src/lib/search/components/search-panel/search-panel.component.scss
- lib/content-services/src/lib/search/components/search-panel/search-panel.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3790
The search panel is …
> [AAE-3790] - Fix search panel scroll in content node selector

- .travis.yml
- e2e/protractor.conf.js
- lib/core/services/auth-guard-base.ts
- lib/core/services/auth-guard-bpm.service.ts
- lib/core/services/auth-guard-ecm.service.ts
- lib/core/services/auth-guard.service.spec.ts
- lib/core/services/auth-guard.service.ts
> - [x] Bugfix
Fix Redirect URL …
> Fix Redirect URL

- lib/core/services/cookie.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5270
**Does this PR …
> [ADF-5270] Fix delete cookie in path

- lib/content-services/src/lib/upload/components/file-uploading-dialog.component.html
- lib/content-services/src/lib/upload/components/file-uploading-list-row.component.html
- lib/content-services/src/lib/upload/components/file-uploading-list-row.component.spec.ts
> - [x] Bugfix
- add extra unit tests to cover manual regression cases
- fix layout …
> additional unit tests for the upload

- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html
- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.spec.ts
- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5269
**Does this PR …
> [ADF-5269] - fix datatable date filter

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3742
**Does this PR …
> [AAE-3742] fix wrong behavior when editing properties on card view

- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5268
**Does this PR …
> [ADF-5268] Fix card view losing focus when typing

- lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.spec.ts
- lib/content-services/src/lib/search/search-header-query-builder.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-4041
**Does this PR …
> [ACA-4041] Filter not emitting the latest value

- lib/core/services/auth-guard-base.ts
> Override the redirectTo with the loginFragment

- lib/content-services/src/lib/document-list/components/document-list.component.ts
> - [X] Bugfix
Sorting by size on DL won't work
Fixed the sorting by size
**Does this …
> [ACA-4013] - fixed sorting for document list - size

- lib/testing/src/lib/core/models/user.model.ts
- scripts/test-e2e-lib.sh
> - [ ] Bugfix
Fix user model default email domain …
> Fix user model default email domain

- lib/core/services/auth-guard-base.ts
> Return the createUrlTree to see the redirect

- lib/cli/scripts/kubectl-image.ts
> adf-cli - Fix typo on namespace

- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-4052
**Does this PR …
> [ACA-4052] - Add today option back

- lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
* Add setCompleteDateFilterDropDown()
> - [ ] Bugfix
> - [x] Other... Please describe: Add a new method in ADF to be used in ADW e2e tests
**What is …
> [ACA-3662] Add setCompleteDateFilterDropDown() method

- .travis.yml
> - [x] Bugfix
arch: arm64-graviton2 …
> Try new travis Graviton

- lib/core/form/components/form-renderer.component.spec.ts
- lib/core/form/components/widgets/container/container.widget.html
- lib/core/form/components/widgets/container/container.widget.scss
- lib/core/form/components/widgets/container/container.widget.spec.ts
- lib/core/form/components/widgets/container/container.widget.ts
- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/components/widgets/core/form.model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3587 …
> [AAE-3587] Use grid to allow using rowspan

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
> - [ ] Bugfix
[ADF-5280](https://issues.alfresco.com/jira/browse/ADF-5280)
**Does …
> [ADF-5280] [Cloud] Tasks - Created Date filter

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3908
**Does this PR …
> [AAE-3908] - fix clear value icon on card view text item

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/mock/content-model.mock.ts
- lib/content-services/src/lib/search/components/search-panel/search-panel.component.html
- lib/content-services/src/lib/search/components/search-panel/search-panel.component.scss
- lib/content-services/src/lib/search/components/search-panel/search-panel.component.ts
- lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
> - [ ] Bugfix
Styling updates
https://issues.alfresco.com/jira/browse/AAE-3405
The …
> [AAE-3405] - Optimise attach file widget UI

- lib/testing/src/lib/core/pages/material/date-picker-calendar.page.ts
*Add selectDateRange() to be re-used in ADW
> - [ ] Bugfix
> - [x] Other... Please describe: Add selectDateRange method in to be used in ADW
**What is …
> [ACA-4089] Add new method in DatePickerCalendarPage

- lib/cli/scripts/kubectl-image.ts
> Fix the if condition on namespaces

- lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
*Add setCompletedBy() method in edit-task-filter-cloud-component.page.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Add setCompletedBy() new method in ADF to use in ADW project for E2E tests …
> [ACA-3664] Add new method in ADF to validate tasks filtering by CreatedBy filter

- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
- lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
*Modify setCompletedBy();
*Modify class name in base-edit-task-filter-cloud.component.html
> - [ ] Bugfix
> - [x] Other... Please describe: Modify setCompletedBy method to set the selected assignee …
> [ACA-4089] Modify setCompletedBy method to set the selected assignee

- lib/core/services/translate-loader.service.ts
> - [ ] Bugfix
- less spamming in the console about i18n resources
**Does this PR …
> remove spamming of i18n warnings to console log

- lib/testing/src/lib/process-services/actions/process.util.ts
> [ACA-4057] Add getProcessInstanceByName method

- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-4071
**Does this PR …
> [ACA-4071] [ADW-Cloud]Task header takes too much to be loaded after claiming a task

- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
- lib/process-services-cloud/tsconfig.lib.json
- lib/tsconfig.json
- lib/tsconfig.spec.json
- tsconfig.json
> - [ ] Bugfix
- cleanup the filters code before refactorings (upcoming PRs)
- use …
> [AAE-3992] cleanup the code before refactoring

- lib/content-services/src/lib/search/public-api.ts
> exported search-datetime range component

- lib/core/form/services/widget-visibility-cloud.service.spec.ts
- lib/core/form/services/widget-visibility.service.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
- lib/process-services-cloud/src/lib/form/models/task-variable-cloud.model.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
> - [X] Bugfix
Task variable are not correctly evaluated in the visibility condition …
> [MNT-22003] - fixed check on variable for visibility service

- docs/process-services-cloud/components/task-form-cloud.component.md
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-4018 …
> [ACA-828] Add showTitle input in TaskCloudForm component

- lib/core/form/models/task-process-variable.model.ts
- lib/process-services-cloud/src/lib/form/models/task-variable-cloud.model.ts
> Added optional on variable models to avoid breaking changes

- lib/core/services/alfresco-api.service.ts
> - [X] Bugfix
error 401 will trigger logout and redirect forcibly to login 
To …
> [ACS-827] - added whitelisted element and method for checking them

- lib/core/directives/directive.module.ts
- lib/core/directives/public-api.ts
- lib/core/directives/tooltip-card/tooltip-card.component.html
- lib/core/directives/tooltip-card/tooltip-card.component.scss
- lib/core/directives/tooltip-card/tooltip-card.component.ts
- lib/core/directives/tooltip-card/tooltip-card.directive.spec.ts
- lib/core/directives/tooltip-card/tooltip-card.directive.ts
- lib/core/styles/_index.scss
> - [ ] Bugfix
There is no simple way of displaying a tooltip containing an image in the application
**What is the …
> AAE-3936 Tooltip card directive

- lib/core/directives/directive.module.ts
> [AAE-3936] Fix error in directive component

- lib/testing/src/lib/core/utils/browser-actions.ts
> Fixed floating promise

- scripts/ci/utils/init-apsone-env.js
> [DRAFT] Adding script for updating users on APS1

- lib/core/assets/images/ic-process.svg
- lib/core/assets/images/save.svg
- lib/core/assets/images/task.svg
- lib/core/services/thumbnail.service.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-3957 …
> [ACA-3957] - Replace icons on process cloud

- e2e/process-services-cloud/task-list-properties-sort.e2e.ts
- e2e/process-services-cloud/tasks-custom-filters.e2e.ts
- e2e/protractor.excludes.json
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/process-services-cloud/src/lib/task/models/public-api.ts
- lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
- lib/testing/src/lib/core/pages/data-table-component.page.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-4077 …
> [AAE-4077] - TaskCloud: Refactor priority

- .travis.yml
- lib/cli/README.md
- lib/cli/package-lock.json
- lib/cli/scripts/init-aps-env.ts
- scripts/ci/check-env/check-ps-env.sh
> - [x] Bugfix
Add upload license script …
> Add upload license script

- lib/core/directives/version-compatibility.directive.spec.ts
- lib/core/directives/version-compatibility.directive.ts
> Fix versioncompatibility directive

- lib/core/form/components/form-renderer.component.spec.ts
- lib/core/form/components/widgets/core/form.model.ts
> - [X] Bugfix
Enable/disable form spacing mode is not set correctly
The behaviour is …
> [ADF-5294] - fixed problem on form rendering

- lib/content-services/tsconfig.lib.json
- lib/core/tsconfig.lib.json
- lib/insights/tsconfig.lib.json
- lib/process-services/tsconfig.lib.json
- tsconfig.dev.json
> - [x] Bugfix
- IDEs should properly work now with the jasmine methods (IntelliJ …
> fix jasmine and karma integration for IDEs

- lib/core/assets/images/dynamic_feed-24px.svg
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-3957 …
> [ACA-3957] - replace task icon

- e2e/protractor.excludes.json
> - [ ] Bugfix
Include back C587084 …
> Include back C587084

- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
> - [x] Bugfix
add safety checks to avoid random crashes in unit tests and certain …
> [ACA-4205] safety checks to avoid crashes in doclist

- .travis.yml
- e2e/content-services/pages/permissions.page.ts
- e2e/content-services/permissions/permissions-component.e2e.ts
- e2e/protractor.excludes.json
- lib/testing/src/lib/core/actions/search.service.ts
- scripts/lint.sh
> - [ ] Bugfix
fixed permission e2e …
> [ADF-5283] Fix Permission Flaky test

- docs/release-notes/RelNote420.md
Ok to bring this into the next version of ADF.
> - [ ] Bugfix
N/A
N/A
**Does this PR …
> Removed the TODO placeholders from the release note.

- demo-shell/src/app/components/cloud/tasks-cloud-demo.component.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4218 …
> [ACA-4218] - fix tomorrow date range filter

- lib/core/toolbar/toolbar.component.html
> - [x] Bugfix
add the missing title class so that toolbar title can be better tested …
> add missing toolbar title class

- lib/core/toolbar/toolbar.component.spec.ts
> - [ ] Bugfix
- add spec file for the toolbar
- add title css test for the toolbar …
> add missing toolbar tests

- lib/cli/scripts/docker-publish.ts
> - [ ] Bugfix
the docker build is performed for every tag
the docker build is …
> [AAE-4369] adf-cli - Build the docker image only once and create tag link

- e2e/core/pages/navigation-bar.page.ts
- e2e/process-services-cloud/pages/service-task-list.page.ts
- e2e/process-services-cloud/service-task-list-cloud-component.e2e.ts
- e2e/protractor.excludes.json
- e2e/test.config.js
- e2e/util/constants.js
> - [ ] Bugfix
e2e service task
https://alfresco.atlassian.net/browse/AAE-3472
e2e …
> [AAE-3472] e2e service task

- lib/cli/scripts/docker-publish.ts
> Fix - Add all-tags as additional option

- lib/cli/scripts/docker-publish.ts
> docker-publish fix - Push the image with tag

- README.md
> - [ ] Bugfix
README link navigates to a 404 …
> Fix broken tutorial link

- lib/content-services/src/lib/document-list/components/node.event.ts
> - [x] Bugfix
- fix the compile errors found by latest typescript (incorrectly …
> fix typescript errors (latest typescript)

- e2e/protractor.excludes.json
> - [ ] Bugfix
excluded e2e C311290
e2e C311290 is broken
excluded e2e C311290 for …
> [ADF-5308] excluded e2e C311290

- lib/process-services-cloud/src/lib/app/components/app-details-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/app/components/app-details-cloud.component.ts
- lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.ts
- lib/process-services-cloud/src/lib/app/mock/app-model.mock.ts
- lib/process-services-cloud/src/lib/app/models/application-instance.model.ts
- lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
> - [ ] Bugfix
- turn `ApplicationInstanceModel` into interface to reduce code …
> add missing app instance types

- lib/cli/package-lock.json
- lib/cli/package.json
> adf-cli init-aae-env - Add request as dependency

- e2e/protractor.excludes.json
- package-lock.json
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5308
This test should be …
> [ADF-5308] Unexclude C311290

- docs/README.md
- docs/core/directives/infinite-select-scroll.directive.md
- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/site-dropdown/sites-dropdown.component.html
- lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts
- lib/content-services/src/lib/site-dropdown/sites-dropdown.component.ts
- lib/core/directives/directive.module.ts
- lib/core/directives/infinite-select-scroll.directive.spec.ts
- lib/core/directives/infinite-select-scroll.directive.ts
- lib/core/directives/public-api.ts
- lib/core/i18n/en.json
> - [ ] Bugfix
[ADF-5311](https://alfresco.atlassian.net/browse/ADF-5311)
**Does this …
> [ADF-5311] Extract infinite select scroll loading logic to a reusable component

- lib/cli/scripts/scan-env.ts
> - [ ] Bugfix
After 10 failed attempts, an error retrieved from the API will be …
> [ACA-4247] Improve login error logs in scan-env command in adf-cli

- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- lib/content-services/src/lib/i18n/en.json
- lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-4426 …
> [AAE-4426] Add upload from local tab in attach file widget

- lib/cli/scripts/scan-env.ts
> - [ ] Bugfix
Login using Basic authentication
Login using SSO
**Does this PR …
> [ACA-4252] Update authentication to SSO

- lib/cli/README.md
- lib/cli/scripts/check-plugin-env.ts
- lib/cli/scripts/plugins/governance-check-plugin.ts
- lib/cli/scripts/plugins/governance-health.ts
- lib/cli/scripts/plugins/plugin-model.ts
- lib/cli/scripts/plugins/process-automation-check-plugin.ts
- lib/cli/scripts/plugins/process-service-check-plugin.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4229 …
> [ACA-4229] [ADW-AGS] Move Governance plugin check script to ADF CLI

- e2e/protractor.conf.js
- lib/core/login/components/login.component.ts
- lib/core/services/auth-guard-base.ts
- lib/core/services/auth-guard-bpm.service.spec.ts
- lib/core/services/auth-guard-bpm.service.ts
- lib/core/services/auth-guard-ecm.service.ts
- lib/core/services/auth-guard.service.spec.ts
- lib/core/services/auth-guard.service.ts
- package-lock.json
- package.json
> - [X] Bugfix
Fix redirect URL for viewer
Fix SSO login show when the user is logged in …
> [MNT-21636] Fix redirect URL for viewer

- docs/abn-tree.yml
- docs/getting-started.md
> Getting started tutorial on ADF.

- lib/core/blank-page/blank-page.component.ts
- lib/core/blank-page/blank-page.module.ts
- lib/core/blank-page/index.ts
- lib/core/blank-page/public-api.ts
- lib/core/core.module.ts
- lib/core/index.ts
> - [ ] Bugfix
Added a blank page component used for debugging after login. Previously …
> [AAE-4384] Add blank page component

- lib/cli/scripts/init-aae-env.ts
- lib/testing/src/lib/core/pages/viewer.page.ts
> - [x] Bugfix
Fix viewer page loading method …
> Fix viewer page loading method

- lib/core/templates/empty-content/empty-content.component.scss
> - [x] Bugfix
- fix vertical positioning of "empty content" (reduces all kinds of …
> "Empty content" centering fixes

- lib/core/directives/logout.directive.spec.ts
- lib/core/directives/logout.directive.ts
> [AAE-4534] Logout directive - handle the route based on app config

- lib/cli/scripts/init-aae-env.ts
> improve the init by failing in case the app are not running

- lib/cli/scripts/resources.ts
> Check if the order matter

- scripts/lint.sh
> Install NX if is in Travis Update lint.sh

- lib/cli/scripts/resources.ts
* Add formWithSingleInput form and outputVariablesMappin process to resources.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Update simpleapp …
> [AAE-4547] Add new process and form to simpleapp

- lib/cli/scripts/scan-env.ts
> - [ ] Bugfix
Non-SSO related errors simply output the entire error object to the terminal. …
> [AAE-4553] Improve error logs in scan-env

- lib/core/form/components/widgets/core/form-field-file-source.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
- lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-4504 …
> [AAE-4504] FE - [ADF] Fetch destination Folder Path from a static path

- lib/cli/scripts/resources.ts
- lib/testing/src/lib/process-services-cloud/resources/resources.json
> [AAE-4547] Add new process definition to simpleapp

- e2e/process-services-cloud/start-task-form-cloud.e2e.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
- lib/testing/src/lib/content-services/pages/upload-button.page.ts
- lib/testing/src/lib/core/models/file.model.ts
- lib/testing/src/lib/core/pages/form/widgets/tab.page.ts
- lib/testing/src/lib/process-services-cloud/pages/form/widget/attach-file-widget-cloud.page.ts
> [ACA-4265]Refactor attachFileFromLocal method

- docs/abn-tree.yml
- docs/tutorials/creating-your-first-adf-application.md
- docs/user-guide/debug-test-build-and-promote.md
> Tutorial on creating ADF based applications.

- docs/core/components/notification-history.component.md
- docs/core/services/notification.service.md
- lib/core/i18n/en.json
- lib/core/material.module.ts
- lib/core/notifications/components/notification-history.component.html
- lib/core/notifications/components/notification-history.component.scss
- lib/core/notifications/components/notification-history.component.spec.ts
- lib/core/notifications/components/notification-history.component.ts
- lib/core/notifications/helpers/notification.factory.ts
- lib/core/notifications/models/notification.model.ts
- lib/core/notifications/notification-history.module.ts
- lib/core/notifications/pipes/notification-icon.pipe.ts
- lib/core/notifications/services/notification.service.ts
- lib/core/styles/_index.scss
- lib/testing/src/lib/core/pages/notification-history.page.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-4529
ADF's Notification …
> [AAE-4529] Refactor Notification History Component

- lib/cli/scripts/plugins/governance-check-plugin.ts
- lib/cli/scripts/plugins/governance-health.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4266 …
> [ACA-4266] Improve governance plugin check logs

- demo-shell/src/app/app.routes.ts
- lib/core/services/auth-guard-base.ts
- lib/core/services/auth-guard-bpm.service.spec.ts
- lib/core/services/auth-guard-bpm.service.ts
- lib/core/services/auth-guard-ecm.service.spec.ts
- lib/core/services/auth-guard-ecm.service.ts
- lib/core/services/auth-guard-sso-role.service.spec.ts
- lib/core/services/auth-guard.service.ts
> - [x] Bugfix
Refactor redirect URL …
> [MNT-21636] Refactor redirect URL

- lib/core/services/auth-guard-base.ts
> - [x] Bugfix
Fix promise redirect …
> Fix promise redirect

- e2e/protractor.excludes.json
> - [ ] Bugfix
excluded flaky test C260241
flaky test C260241 - https://alfresco.atlassian.net/browse/ADF-5335
**What …
> excluded flaky test C260241

- .github/dependabot.yml
> - [ ] Bugfix
add certain libs to the dependabot ignore list to avoid CI/CD spamming …
> configure dependabot excludes

- lib/process-services/src/lib/form/start-form.component.ts
> Avoid to recall the method if no change detect is affected

- demo-shell/src/app.config.json
- lib/content-services/src/lib/aspect-list/aspect-list.component.html
- lib/content-services/src/lib/aspect-list/aspect-list.component.scss
- lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.module.ts
- lib/content-services/src/lib/aspect-list/aspect-list.service.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.service.ts
- lib/content-services/src/lib/aspect-list/node-aspect.service.spec.ts
- lib/content-services/src/lib/aspect-list/node-aspect.service.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/core/card-view/services/card-view-update.service.spec.ts
- lib/core/card-view/services/card-view-update.service.ts
> Aspect List - added spinner and refresh

- demo-shell/src/app.config.json
> Enabling default aspects for card component

- scripts/travis/update/update-project.sh
> Improve update-project script to update adf-cli and adf-testing packages

- e2e/content-services/permissions/site-permissions.e2e.ts
- lib/core/services/auth-guard-base.ts
- lib/core/services/auth-guard-bpm.service.spec.ts
- lib/core/services/auth-guard-bpm.service.ts
- lib/core/services/auth-guard-ecm.service.spec.ts
- lib/core/services/auth-guard-ecm.service.ts
- lib/core/services/auth-guard.service.spec.ts
- lib/core/services/auth-guard.service.ts
> - [x] Bugfix
Use URLTree to redirect …
> [MNT-21636] Use URLTree for redirect

- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
[ADF-5339](https://alfresco.atlassian.net/browse/ADF-5339)
**Does this …
> [ADF-5339]  ESCAPE should close opened dialog not the overlay viewer

- scripts/travis/update/update-project.sh
> Auto PR - Add the ADF number to easily identify the version

- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4208 …
> [ACA-4208] - Fix process date filter for range

- lib/core/userinfo/components/user-info.component.html
- lib/core/userinfo/components/user-info.component.spec.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-4624 …
> [AAE-4624] - fix user initials for identity user with bpm

- e2e/protractor.excludes.json
- nx.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ADF-5285 …
> [ADF-5285] Re-include test

- lib/cli/scripts/scan-env.ts
> - [x] Bugfix
- No longer retries after a login error
- Catch JSON parse errors
- …
> [AAE-4710] Error-proof scan-env

- lib/cli/scripts/init-aae-env.ts
- scripts/ci/check-env/check-ps-cloud-env.sh
> cli init-aae - Remove useless properties

- scripts/travis/update/pr-creator.js
> Override the pr title in case already exists

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/app.module.ts
- demo-shell/src/app/components/cloud/cloud-layout.component.ts
- demo-shell/src/app/services/app-notifications-factory.ts
- demo-shell/src/app/services/app-notifications.service.ts
- e2e/process-services-cloud/task-counters-cloud.e2e.ts
- lib/process-services-cloud/src/lib/services/notification-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/services/notification-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
- lib/testing/src/lib/core/pages/notification-history.page.ts
- lib/testing/src/lib/process-services-cloud/pages/task-filters-cloud-component.page.ts
- package-lock.json
- package.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4299
Add e2e tests for task …
> [ACA-4299] Add e2e tests for task counters and notifications

- lib/content-services/src/lib/aspect-list/aspect-list.component.scss
> [ADF-5345] - fixed border for aspect dialog

- lib/process-services-cloud/src/lib/services/notification-cloud.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ADF-5349
Smart ws protocol based …
> [ADF-5349] WebSocket protocol based on BpmHost

- lib/core/pipes/full-name.pipe.ts
- lib/core/userinfo/components/user-info.component.html
- lib/core/userinfo/components/user-info.component.spec.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5348 …
> [ADF-5348] - fix user info icons

- e2e/protractor.excludes.json
> - [ ] Bugfix
re-include test C299187
https://alfresco.atlassian.net/browse/ADF-5285 …
> [ADF-5285] re-include test C299187

- lib/core/viewer/components/viewer.component.ts
> - [X] Bugfix
When the version is changed the preview is not refreshed
Refreshing the …
> [ACA-4202] - refreshing the preview when version has changed

- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
Reverts Alfresco/alfresco-ng2-components#6690
Reverting to come up with a better fix for later
> Revert "[AAE-4637] Fix varying height of dialog when clicking on the Upload from your device tab"

- lib/core/viewer/components/media-player.component.scss
> - [ ] Bugfix
Changed the right css property
Changed the right css property
**Does …
> [ATS-873] Fix css property

- lib/testing/src/lib/core/actions/identity/query.service.ts
> [AAE-4713] Improve Message Events method

- e2e/protractor.excludes.json
> [ADF-5308] - re enabling excluded test

- e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
> Added extra checks for fixing the e2e

- e2e/protractor.excludes.json
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> - [x] Bugfix
fix an issue with recursive updates when process filter has not changed …
> [AAE-4749] process filter notification fixes

- lib/core/directives/logout.directive.spec.ts
- lib/core/directives/logout.directive.ts
> - [x] Bugfix
The logout does not happen and the user is redirected to the home page …
> [ACA-4322] Logout - Avoid the redirect in case SSO auth

- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
> - [x] Bugfix
- fix model object init when using with multiple versions
**Does this …
> [ACA-4198] fix appVersion init for multiple versions

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
> - [ ] Bugfix
Convert manual tests to unit tests
https://alfresco.atlassian.net/browse/ADF-5357 …
> [ADF-5357] - Convert process name manual tests to unit tests

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
Reverts Alfresco/alfresco-ng2-components#6777
> Revert "[ADF-5354] Content node selector is not working properly for read-only folders"

- .travis.yml
> Move the upstream to a lower level

- .travis.yml
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- scripts/ci/job_hooks/after_e2e.sh
- scripts/ci/job_hooks/before_e2e.sh
- scripts/ci/job_hooks/before_install.sh
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4344 …
> [ACA-4344] - increase debounce time on process filters

- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.html
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ADF-5355 …
> [ADF-5355] - Fix attach button visibility when using external source

- lib/testing/src/lib/core/pages/viewer.page.ts
- lib/testing/src/lib/process-services-cloud/actions/process.services.ts
- lib/testing/src/lib/process-services-cloud/actions/public-api.ts
- lib/testing/src/lib/process-services-cloud/resources/resources.json
> [ACA-4340]Add method for createProcessInstanceAndClaimFirstTask

- lib/content-services/src/lib/content-metadata/services/content-type-property.service.ts
> [ADF-5358] - fixed duplicated type on reopening viewer

- docs/core/components/login.component.md
- lib/core/app-config/schema.json
- lib/core/models/oauth-config.model.ts
> - [ ] Bugfix
Add some more info on the refresh token timeout
**Does this PR …
> Add some more info on the refresh token timeout

- e2e/content-services/metadata/metadata-content-type.e2e.ts
- e2e/core/pages/metadata-view.page.ts
- lib/content-services/src/lib/content-type/content-type-dialog.component.html
- lib/content-services/src/lib/content-type/content-type-dialog.component.spec.ts
- lib/testing/src/lib/content-services/actions/model.actions.ts
- lib/testing/src/lib/content-services/actions/public-api.ts
> - [ ] Bugfix
Automation
Automate change type …
> [ADF-5318] E2E Content Change type

- .travis.yml
- lib/process-services-cloud/src/lib/task/task-filters/components/base-task-filters-cloud.component.scss
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5359
Improve response time …
> [ADF-5359] Improve response time for filter counters

- lib/testing/src/lib/core/test-element.ts
> - [ ] Bugfix
additional JS docs for the TestElement members …
> additional API docs for the TestElement

- lib/testing/src/lib/process-services-cloud/resources/resources.json
* Change resources.json file by adding widgets to inputform for SIMPLE_APP
> - [ ] Bugfix
> - [x] Other... Please describe: Add widgets to inputform for SIMPLE_APP to use in ADW e2e
**What is the current behaviour?** (You can …
> [ACA-4350] Add widgets to inputform for SIMPLE_APP

- lib/testing/src/lib/process-services-cloud/actions/descriptor.ts
> [AAE-4751] Modify Delete method

- e2e/process-services-cloud/form-field/json-widget.e2e.ts
- e2e/process-services-cloud/task-list/tasks-claim-release.e2e.ts
- lib/testing/src/lib/core/pages/form/widgets/json-widget.page.ts
- lib/testing/src/lib/core/pages/form/widgets/widget.ts
> [ACA-4337]Move APW tests: claim/release standalone task, json widget

- lib/testing/src/lib/process-services-cloud/resources/resources.json
> - [ ] Bugfix
> - [x] Other... Please describe: Adding resources for use with e2e tests …
> [AAE-4823] Add resources used in e2e tests in ADW

- lib/testing/src/lib/process-services-cloud/resources/resources.json
> - [ ] Bugfix
> - [x] Other... Please describe: Adding reusable e2e process/form widget ids to candidatebaseapp resource file …
> [AAE-4817] E2E - Add process/form wdget ids in the CANDIDATEBASEAPP resources file

- lib/core/directives/directive.module.ts
- lib/core/directives/library-favorite.directive.spec.ts
- lib/core/directives/library-favorite.directive.ts
- lib/core/directives/library-membership.directive.spec.ts
- lib/core/directives/library-membership.directive.ts
- lib/core/directives/public-api.ts
> - [ ] Bugfix
- move membership directives and unit tests from ACA
**Does this PR …
> migrate library directives from ACA

- lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts
> [AAE-4817] Add reusble method in ProcessListCloudComponent page object

- e2e/protractor.conf.js
> [ADF-5225] smoke test suite

- lib/testing/src/lib/core/utils/string.util.ts
- lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/task-list-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/resources/resources.json
> [AAE-4824] Add more widgets to resources and cloud related methods

- demo-shell/src/app.config.json
- demo-shell/src/app/components/cloud/processes-cloud-demo.component.html
- demo-shell/src/app/components/cloud/processes-cloud-demo.component.ts
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4220 …
> [ACA-4220] - preselect initator values by username

- lib/testing/src/lib/process-services-cloud/resources/resources.json
> [ACA-4324]MovAdd details about tasks in resource files

- lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Update page object …
> [ACA-3652] Add Assignment custom filter in task filter cloud component page

- .github/dependabot.yml
> Run dependabot on sunday

- lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.scss
> - [X] Bugfix
fix button filter color in high contrast …
> [ADF-5212] fix button filter color in high contrast

- lib/cli/scripts/docker-publish.ts
> Docker publish - Remove the pathProject as mandatory

- demo-shell/src/app.config.json
- demo-shell/src/app/components/document-list/extension-presets/name-column/name-column.component.ts
- demo-shell/src/app/components/files/files.component.html
- docs/content-services/components/document-list.component.md
- lib/content-services/src/lib/document-list/components/name-column/name-column.component.spec.ts
- lib/content-services/src/lib/document-list/components/name-column/name-column.component.ts
> - [x] Bugfix
- use column key to resolve the name value
- add additional unit tests …
> [ADF-5156] Name column fixes

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.html
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-3619 …
> [ACA-3619] - change assignment placeholder

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/content-services/src/lib/document-list/data/share-data-row.model.ts
- lib/content-services/src/lib/document-list/data/share-datatable-adapter.spec.ts
- lib/content-services/src/lib/document-list/data/share-datatable-adapter.ts
- lib/content-services/src/lib/mock/document-library.model.mock.ts
- lib/content-services/src/lib/mock/document-list.component.mock.ts
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/core/datatable/data/data-row.model.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-4841 …
> [AAE-4841] - Fix content node selector current selection is lost after uploading files

- lib/cli/README.md
- lib/cli/scripts/docker-publish.ts
- lib/cli/scripts/docker.ts
- scripts/travis/release/release-docker.sh
> docker command: Create 2 different actions publish and link

- lib/core/form/components/widgets/core/form-field.model.ts
> - [X] Bugfix
the Number widget partially handled decimal numbers
the Number widget …
> add enableFractions in form values on number widget

- e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
- e2e/core/pages/metadata-view.page.ts
- e2e/core/viewer/viewer-content-services-component.e2e.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/content-services/src/lib/content-metadata/services/basic-properties.service.ts
- lib/content-services/src/lib/content-metadata/services/content-metadata.service.spec.ts
- lib/content-services/src/lib/content-metadata/services/content-metadata.service.ts
- lib/content-services/src/lib/content-metadata/services/content-type-property.service.spec.ts
- lib/content-services/src/lib/content-metadata/services/content-type-property.service.ts
- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.spec.ts
- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
> [ADF-5362] - Content type properties should be showed when content type is changed.

- .travis.yml
> - [ ] Bugfix
> - [] Feature
Run develop only once a day …
> Run develop only once a day

- lib/core/form/components/widgets/container/container.widget.scss
> [ADF-5370] - fixed style for container dimension

- lib/core/directives/tooltip-card/tooltip-card.component.html
- lib/core/directives/tooltip-card/tooltip-card.component.scss
- lib/core/directives/tooltip-card/tooltip-card.component.ts
- lib/core/directives/tooltip-card/tooltip-card.directive.spec.ts
- lib/core/directives/tooltip-card/tooltip-card.directive.ts
> - [ ] Bugfix
The tooltip card only displays an image and a text. 
It can receive a …
> [AAE-4879] Update tooltip card to receive custom HTML

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-3700 …
> [ACA-3700] - add suspended date filter

- e2e/protractor.conf.js
- lib/testing/src/lib/core/actions/api.service.ts
> [ADF-5225] smoke test

- docs/core/services/people-content.service.md
- lib/core/mock/ecm-user.service.mock.ts
- lib/core/models/ecm-user.model.ts
- lib/core/services/people-content.service.spec.ts
- lib/core/services/people-content.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-4995
* Expanded …
> [AAE-4995] Expand ADF PeopleContentService to create new person

- lib/core/testing/setup-test-bed.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-4863 …
> [AAE-4863] Fixed the async and done warning due to new version of Karma

- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-3700 …
> [ACA-3700] - fix suspended data filter not preserving data

- e2e/protractor.excludes.json
- lib/testing/src/lib/core/pages/form/widgets/attach-file-widget.page.ts
> Improve checkFilesAreAttachedToWidget() method

- scripts/travis/e2e/e2e.sh
> - [ ] Bugfix
Run all e2e for cron jobs …
> Run all e2e for cron jobs

- .travis.yml
- scripts/travis/release/deprecate-develop-build.sh
- scripts/travis/update/pr-creator.js
> - [ ] Bugfix
- Add deprecate develop build script
- Make pipeline deploy on develop …
> improve travis ci

- .travis.yml
- scripts/ci/job_hooks/before_install.sh
- scripts/ci/jobs/dbpci-build-guard-check
- scripts/ci/partials/_ci-flags-parser.sh
> - [ ] Bugfix
See https://alfresco.atlassian.net/browse/ACS-1526
> - [ ] Yes
> - [x] No
If this …
> [ACS-1526] Fail on Draft and unapproved PRs

- lib/content-services/src/lib/i18n/en.json
> - [x] Bugfix
fix swsdp in breadcrumb …
> [ADF-5371] fix swsdp in breadcrumb

- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-dialog.component.html
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-dialog.component.scss
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.scss
- lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.html
- lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.scss
- lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.ts
- lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
- lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.scss
- lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.service.ts
- lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.scss
- lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.spec.ts
- lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.ts
- lib/content-services/src/lib/permission-manager/components/user-role-column/user-role-column.component.ts
> [ACA-4361] Review permission list

- angular.json
- lib/core/viewer/components/viewer.component.scss
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4406 …
> CropperJS dependency from styles to assets 

- lib/core/data-column/data-column-header.component.ts
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/data/object-datacolumn.model.ts
> - [x] Bugfix
fixes https://alfresco.atlassian.net/browse/ACA-4407
**Does this PR …
> [ACA-4361] Fix data column conflict

- demo-shell/src/app/components/card-view/card-view.component.ts
- e2e/core/pages/metadata-view.page.ts
- e2e/process-services/pages/task-details.page.ts
- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.html
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
- lib/core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/card-view/interfaces/card-view-item-properties.interface.ts
- lib/core/card-view/models/card-view-baseitem.model.ts
- lib/core/card-view/models/card-view-dateitem.model.ts
- lib/core/card-view/models/card-view-floatitem.model.ts
- lib/core/card-view/models/card-view-intitem.model.ts
- lib/core/card-view/models/card-view-textitem.model.ts
- lib/core/card-view/validators/card-view-item-float.validator.ts
- lib/core/card-view/validators/card-view-item-int.validator.ts
- lib/core/pipes/decimal-number.pipe.ts
- lib/core/pipes/multi-value.pipe.spec.ts
- lib/core/pipes/multi-value.pipe.ts
- lib/testing/src/lib/process-services-cloud/pages/task-header-cloud-component.page.ts
…Decimal properties
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5390 …
> [ADF-5390] [ADF-5391] Add multivalue cardview for Date, Datetime, Integers and Decimal properties.

- lib/core/viewer/components/viewer.component.html
> - [ ] Bugfix
event missing: https://github.com/Alfresco/alfresco-ng2-components/pull/6992/files#diff-cf86b498147a2df …
> [ADF-5393] add missing event on image viewer

- lib/cli/README.md
- scripts/ci/job_hooks/after_e2e.sh
- scripts/ci/job_hooks/before_e2e.sh
> - [ ] Bugfix
Scan environment will only run on cron. …
> [ACS-1525] Only run scan environment on cron

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
> Start Process Cloud - Use the cloud key for validate error

- docs/content-services/components/content-node-selector-panel.component.md
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- package-lock.json
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-5124?jql=text%20~%20%22counter%22%20AND%20reporter%20in%20(5f …
> [AAE-5124] Show counter only when attaching files

- docs/user-guide/app-extensions.md
> - [ ] Bugfix
provide details on the `$replace` features of the app extensions
**Does …
> update docs on the extension value replace

- lib/core/viewer/components/img-viewer.component.spec.ts
- lib/core/viewer/components/img-viewer.component.ts
> [AAE-5146] Viewer - Reset button is in fact Full Screen button in ADW

- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-3700 …
> [ACA-3700] - fix suspened date start date

- lib/core/notifications/components/notification-history.component.spec.ts
- lib/core/notifications/components/notification-history.component.ts
> - [x] Bugfix
change notification history service storage variable
**Does this PR …
> [ADF-5379] change notification history service storage variable

- lib/core/form/components/form-renderer.component.scss
> - [x] Bugfix
Header when collapsible is not aligned
Header is aligned and of the …
> Fixing header style as now it's not aligned anymore

- lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4422 …
> [ACA-4422] Resolved - Edit Aspects Dialog should close when pressing ESC

- lib/core/viewer/components/pdf-viewer.component.spec.ts
- lib/core/viewer/components/pdf-viewer.component.ts
> - [x] Bugfix
AAE-4009
Page is scaled to fit the container when it's initialised …
> [AAE-4009] Fix horizontal scroll issue for pdf-viewer

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
> [ADF-5397] Resolved - selection count should show at the end

- lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.html
- lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4421
fixed
**Does this PR …
> [ACA-4421] [Edit Aspects] Apply button should be disabled by default

- lib/core/form/components/widgets/container/container.widget.scss
> [ADF-5398] Form fix style

- lib/core/info-drawer/info-drawer.component.ts
- lib/core/viewer/components/viewer-sidebar.component.ts
> - [x] Bugfix
[ADF-5399](https://alfresco.atlassian.net/browse/ADF-5399)
**Does this …
> [ADF-5399] Viewer- Editing a property by pressing the letter "r" inside the info drawer in the image viewer unexpectedly rotates the image

- e2e/process-services-cloud/task-list/edit-process-filters-component.e2e.ts
- lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
> [ACA-4458]Add expand cloud custom filter method

- .travis.yml
- scripts/npm-move-tag.sh
- scripts/travis/build/build-libs.sh
- scripts/travis/release/release-npm.sh
Make publish run on API
> - [X] Bugfix
Fix some build scripts …
> Fix some build scripts

- lib/core/services/content.service.spec.ts
- lib/core/services/content.service.ts
…
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5148
fixed
**Does this PR …
> [ADF-5148] ContentService.hasPermissions() should check inhertied permission

- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-4974 …
> [AAE-4974] FE - Remove scroll bar from empty "Upload from your device" list

- demo-shell/src/app/components/cloud/community/community-task-details-cloud.component.html
- demo-shell/src/app/components/cloud/community/community-task-details-cloud.component.ts
- demo-shell/src/app/components/cloud/task-details-cloud-demo.component.html
- demo-shell/src/app/components/cloud/task-details-cloud-demo.component.ts
- lib/process-services-cloud/src/lib/task/directives/claim-task-cloud.directive.spec.ts
- lib/process-services-cloud/src/lib/task/directives/complete-task.directive.spec.ts
- lib/process-services-cloud/src/lib/task/directives/unclaim-task-cloud.directive.spec.ts
- lib/process-services-cloud/src/lib/task/directives/unclaim-task-cloud.directive.ts
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-5280
fixed
**Does this PR …
> [AAE-5280] Better error handling for user task

- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.spec.ts
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.ts
…er multiple times
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACA-4464
fixed …
> [ACA-4464] Add user/groups - should not be able to select the same user multiple times

- lib/testing/src/lib/core/pages/form/form-fields.ts
- lib/testing/src/lib/core/pages/form/widgets/attach-file-widget.page.ts
> [ACA-4474]Add checkWidgetsAreVisible method

- e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
- e2e/process-services-cloud/start-task/start-process-cloud.e2e.ts
- e2e/process-services-cloud/start-task/start-task-form-cloud.e2e.ts
- e2e/process-services/process/start-process-component.e2e.ts
- e2e/protractor.excludes.json
- lib/testing/src/lib/process-services-cloud/pages/start-process-cloud-component.page.ts
- lib/testing/src/lib/process-services/pages/start-process.page.ts
> [ACA-4474]Add isStartProcessButtonEnabled method

- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
> [AAE-2617] To get access to datatable component from process-list component

- e2e/protractor.excludes.json
> [ADF-5421]Include test back

- lib/testing/shared/package.json
Patch for other apps repositories.
> Expose shared library as subdirectory

- docs/core/services/people-content.service.md
- lib/core/services/people-content.service.spec.ts
- lib/core/services/people-content.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-5392 …
> [AAE-5392] - Add find people api call

- lib/content-services/src/lib/content-metadata/services/content-type-property.service.ts
- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
- lib/core/card-view/components/card-view/card-view.component.html
- lib/core/card-view/components/card-view/card-view.component.spec.ts
- lib/core/card-view/components/card-view/card-view.component.ts
- lib/core/card-view/interfaces/card-view-selectitem-properties.interface.ts
- lib/core/card-view/models/card-view-selectitem.model.spec.ts
- lib/core/card-view/models/card-view-selectitem.model.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> [ACA-4436] - added option for select item to display None

- lib/core/form/components/widgets/core/form-field-validator.spec.ts
- lib/core/form/components/widgets/core/form-field-validator.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4450 …
> [ACA-4450] - fix disable complete button on invalid datetime

- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-5432?src=confmacro
NO FILTER …
> [AAE-5432] - Fix no filter should be selected by default

- lib/core/form/components/widgets/core/form-field.model.spec.ts
- lib/core/form/components/widgets/core/form-field.model.ts
> - [x] Bugfix
https://github.com/Alfresco/alfresco-ng2-components/issues/7094
**Does …
> [7094] Fix empty save people groups 

- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
> [ACA-4503] Fix close all dialogs

- demo-shell/src/app.config.json
- e2e/process-services/tasks/info-drawer.e2e.ts
- lib/testing/src/lib/protractor/content-services/pages/search/search-text.page.ts
> [ADF-5440] update ADF  e2e for APS 2.0

- lib/content-services/src/lib/search/components/search-facet-field/search-facet-field.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5439
done
**Does this PR …
> [ADF-5439] New bubble filters with expandible list extends too much when there are too many elements

- angular.json
> Improve tslint configuration

- Dockerfile
> 1.20-alpine

- scripts/travis/update/update-project.sh
> - [ ] Bugfix
- run CI on all the automatic upgrade PRs (this reduces the efforts to …
> force CI on the automatic ADF/JS-API upgrades

- lib/content-services/src/lib/breadcrumb/breadcrumb.theme.scss
- lib/core/card-view/components/card-view-textitem/card-view-textitem.theme.scss
- lib/core/datatable/components/datatable/datatable.theme.scss
- lib/core/styles/_index.scss
- lib/core/viewer/components/img-viewer.theme.scss
- lib/core/viewer/components/pdf-viewer-thumbnails.theme.scss
> - [x] Bugfix
- fix theme paths
- fix color palette for some classes (using …
> Theme bugfixes

- lib/content-services/theming/_index.scss
- lib/core/theming/_index.scss
- lib/insights/theming/_index.scss
- lib/process-services-cloud/theming/_index.scss
- lib/process-services/theming/_index.scss
> rollback theming enhancements

- e2e/process-services/form/attach-form-component.e2e.ts
- e2e/process-services/pages/attach-form.page.ts
- e2e/process-services/tasks/standalone-task.e2e.ts
- lib/process-services/src/lib/mock/task/task-details.mock.ts
- lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts
- lib/testing/src/lib/protractor/core/pages/form/form-fields.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-1767
Unit test and E2e …
> [ACS-1767] [ADF] - Convert C329803 and C329800 cases

- lib/core/services/people-content.service.spec.ts
- lib/core/services/people-content.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-5529 …
> [AAE-5529] Include sorting params in the PeopleContentQueryRequestModel

- lib/process-services-cloud/src/lib/process-services-cloud.module.ts
> [AAE-5560] ProcessServiceCloudModule - be able to inject a different preference service instance

- lib/content-services/src/lib/search/components/search-sorting-picker/search-sorting-picker.component.spec.ts
- lib/content-services/src/lib/search/services/base-query-builder.service.ts
- lib/content-services/src/lib/search/services/search-header-query-builder.service.spec.ts
- lib/content-services/src/lib/search/services/search-query-builder.service.spec.ts
> - [ ] Bugfix
Improve search for testability …
> [ADF-5429] Improve search for testability

- lib/extensions/src/lib/config/action.extensions.ts
> - [x] Bugfix
add missing `color` property …
> add missing api to extensions interface

- docs/core/components/search-text-input.component.md
- lib/core/search-text/search-text-input.component.html
- lib/core/search-text/search-text-input.component.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ADF-5460
New placeholder input …
> [ADF-5460] Add placeholder to SearchTextInputComponent

- docs/core/services/auth-guard-sso-role.service.md
- lib/core/services/auth-guard-sso-role.service.spec.ts
- lib/core/services/auth-guard-sso-role.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-5414 …
> [AAE-5414] - SSO Auth Guard - Add the concept of excluded roles

- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/version-manager/version-manager.component.html
- lib/content-services/src/lib/version-manager/version-upload.component.html
- lib/content-services/src/lib/version-manager/version-upload.component.spec.ts
- lib/content-services/src/lib/version-manager/version-upload.component.ts
> [ACA-3669] Incorrect Version Number Displayed

- lib/content-services/src/lib/i18n/zh-CN.json
- lib/process-services-cloud/src/lib/i18n/ar.json
- lib/process-services-cloud/src/lib/i18n/cs.json
- lib/process-services-cloud/src/lib/i18n/da.json
- lib/process-services-cloud/src/lib/i18n/de.json
- lib/process-services-cloud/src/lib/i18n/es.json
- lib/process-services-cloud/src/lib/i18n/fi.json
- lib/process-services-cloud/src/lib/i18n/fr.json
- lib/process-services-cloud/src/lib/i18n/it.json
- lib/process-services-cloud/src/lib/i18n/ja.json
- lib/process-services-cloud/src/lib/i18n/nb.json
- lib/process-services-cloud/src/lib/i18n/nl.json
- lib/process-services-cloud/src/lib/i18n/pl.json
- lib/process-services-cloud/src/lib/i18n/pt-BR.json
- lib/process-services-cloud/src/lib/i18n/ru.json
- lib/process-services-cloud/src/lib/i18n/sv.json
- lib/process-services-cloud/src/lib/i18n/zh-CN.json
> - [NA ] Tests for the changes have been added (for bug fixes / features)
> - [NA ] Docs have been added / updated (for bug fixes / features)
> - [ ] Bugfix
> - [ x] Other... Please describe: Updated localised UI files in 16 languages
**Does this PR …
> LOC-323 - Updated UI for ADF 4.6 in 16 languages

- docs/core/components/viewer.component.md
> - [ ] Bugfix
Update documentation extension viewer …
> Update documentation extension viewer

- lib/core/services/auth-guard.service.ts
> [ADF-5462] - fixed logout redirect on other tabs

- .gitignore
- lib/core/viewer/components/pdf-viewer.component.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
- lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
> [ADF-5173] - improved fix for closing pdfjs worker error

- lib/core/form/components/widgets/functional-group/functional-group.widget.html
- lib/core/form/components/widgets/functional-group/functional-group.widget.spec.ts
- lib/core/form/components/widgets/functional-group/functional-group.widget.ts
- lib/core/form/components/widgets/people/people.widget.html
- lib/core/form/components/widgets/people/people.widget.spec.ts
- lib/core/form/components/widgets/people/people.widget.ts
> [ADF-5464] [form]Mandatory field validations are not applied once content removed

- demo-shell/src/app.config.json
- lib/core/form/components/widgets/core/form-field-rule.ts
- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/components/widgets/core/index.ts
- lib/core/i18n/en.json
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.scss
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/mocks/linked-dropdown.mock.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-6025 …
> [AAE-6025] - Resolve linked dropdowns during runtime

- lib/testing/src/lib/protractor/process-services-cloud/pages/form/widget/attach-file-widget-cloud.page.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-6295 …
> [AAE-6295] Updated attach-file-widget-cloud.page.ts

- demo-shell/src/app.config.json
- lib/core/userinfo/components/user-info.component.spec.ts
- lib/core/userinfo/components/user-info.component.ts
> - [x] Bugfix
You might came across the [blink users …
> [ADF-5465] Not being redirected to login page when Kerberos is enabled

- lib/cli/README.md
- lib/cli/bin/adf-cli
- lib/cli/package-lock.json
- lib/cli/package.json
- lib/cli/scripts/changelog.ts
- lib/cli/templates/changelog-html.ejs
- lib/cli/templates/changelog-md.ejs
> - [ ] Bugfix
Add support for git log generation with bot filtering and multiple …
> [ACS-2197] changelog generation with ADF CLI

- README.md
- lib/content-services/README.md
- lib/core/README.md
- lib/process-services-cloud/README.md
- lib/stories/README.md
> - [ ] Bugfix
Libraries docs doesn't have information about Storybook.
Libraries have …
> [AAE-6358] Storybook sections on GitHub docs

- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
> [AAE-6224] - fixed form field values when rest dropdown has loaded value

- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-6354
fixed
**Does this PR …
> [AAE-6354] [FE] radio button rest preselct from mapping

- lib/process-services-cloud/src/lib/form/components/form-definition-selector-cloud.component.stories.ts
- lib/process-services-cloud/src/lib/form/mocks/form-cloud.service.mock.ts
- lib/process-services-cloud/src/lib/form/mocks/form-definition-selector-cloud.service.mock.ts
- lib/process-services-cloud/src/lib/form/mocks/form-representation.mock.ts
- lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.interface.ts
- lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/form/services/form-definition-selector-cloud.service.ts
> [AAE-5962] Storybook stories for FormDefinitionSelectorCloud component

- lib/process-services-cloud/src/lib/process/mock/process-cloud.service.mock.ts
- lib/process-services-cloud/src/lib/process/mock/process-instance-details-cloud.mock.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/mock/process-filters-cloud.mock.ts
- lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.stories.ts
- lib/process-services-cloud/src/lib/process/services/process-cloud.interface.ts
- lib/process-services-cloud/src/lib/process/services/process-cloud.service.ts
> [AAE-5958] Storybook stories for ProcessHeaderCloud component

- e2e/process-services-cloud/form-field/dropdown-widget.e2e.ts
- lib/testing/src/lib/protractor/core/pages/form/widgets/dropdown-widget.page.ts
- lib/testing/src/lib/protractor/process-services-cloud/resources/resources.ts
> - [ ] Bugfix
New E2Es for multiselect dropdown …
> AAE-6348 E2E for multiselect dropdown

- .travis.yml
> Log in dockerhub to avoid pull rate limit

- lib/core/form/components/widgets/core/form-field.model.ts
- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-6417 …
> [AAE-6417] [FE] [FORM] preselect the logged user

- lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.stories.ts
> [AAE 5966] Storybook stories for AppListCloud component

- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.stories.ts
- lib/process-services-cloud/src/lib/common/mock/date-range-filter.mock.ts
> [AAE-5964] Storybook stories for DateRangeFilter component

- e2e/core/datatable/data-table-component.e2e.ts
> - [ ] Bugfix
Remove duplicate E2E of Unit …
> [ADF-5228] Remove duplicate E2E of Unit

- lib/core/services/identity-user.service.spec.ts
- lib/core/services/identity-user.service.ts
- lib/core/services/jwt-helper.service.ts
> Retrieve jwt user info from id token

- lib/process-services-cloud/src/lib/models/process-definition-cloud.model.ts
> - [ ] Bugfix
We don't have a category field in  ProcessDefinitionCloud model …
> [AAE-6310] Add a category in process definition model

- lib/core/form/components/widgets/date-time/date-time.widget.scss
- lib/core/i18n/en.json
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.scss
> - [x] Bugfix
remove depend on from the general render …
> [AAE-6954] remove depend on from the general render

- lib/cli/scripts/docker.ts
> [adf-cli] - Expose property for custom dockerfile name

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
> - [x] Bugfix
use correct "copy" icon for copy link button in node share dialog …
> [ACA-3744] correct copy icon for share dialog

- lib/content-services/src/lib/upload/directives/file-draggable.directive.spec.ts
- lib/content-services/src/lib/upload/directives/file-draggable.directive.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4554
- fix CSS styling for …
> [ACA-4554] drag and drop fixes and unit tests

- e2e/process-services-cloud/task-list/task-list-properties.e2e.ts
> [AAE-7062] Fixed failing e2e tests

- lib/testing/src/lib/protractor/core/pages/data-table/data-table-item.ts
> - [ ] Bugfix
e2e method improvement …
> Improve a datatable e2e method

- lib/content-services/src/lib/content-type/index.ts
- lib/content-services/src/lib/content-type/public-api.ts
- lib/core/form/components/widgets/core/container-column.model.ts
- lib/core/form/components/widgets/core/form-field-utils.ts
- lib/core/form/components/widgets/core/form-field-validator.ts
- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/components/widgets/core/form-outcome.model.ts
- lib/core/form/components/widgets/core/form-widget.model.ts
- lib/core/form/components/widgets/core/form.model.ts
- lib/core/form/components/widgets/core/index.ts
- lib/core/form/components/widgets/core/process-form-model.interface.ts
- lib/core/form/components/widgets/core/tab.model.ts
- lib/core/form/components/widgets/dynamic-table/dynamic-row-validation-summary.model.ts
- lib/core/form/events/form-error.event.ts
- lib/core/form/events/form-field.event.ts
- lib/core/form/events/form.event.ts
- lib/core/form/events/validate-dynamic-table-row.event.ts
- lib/core/form/events/validate-form-field.event.ts
- lib/core/form/events/validate-form.event.ts
- lib/core/form/public-api.ts
- lib/core/form/services/form-validation-service.interface.ts
- lib/core/form/services/form.service.ts
- lib/core/language-menu/language-menu.component.ts
- lib/core/services/language-item.interface.ts
- lib/core/services/language.service.ts
- lib/core/services/public-api.ts
- lib/core/services/user-preferences.service.ts
> - [x] Bugfix
- fix circular dependencies and provide workarounds where possible …
> [AAE-7119] Fix circular dependencies

- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
> - [ ] Bugfix
> - [ ] Other... Please describe: Added unit test on cloud process/filters 
https://alfresco.atlassian.net/browse/AAE-5835
**What is the …
> [AAE-5835] Add unit test to check is selected Process/Task filter highlighting

- lib/cli/.eslintrc.json
- lib/cli/scripts/changelog.ts
- lib/cli/scripts/check-cs-env.ts
- lib/cli/scripts/docker.ts
- lib/cli/scripts/init-aae-env.ts
- lib/cli/scripts/init-acs-env.ts
- lib/cli/scripts/init-aps-env.ts
- lib/cli/scripts/kube-utils.ts
- lib/cli/scripts/kubectl-clean-app.ts
- lib/cli/scripts/kubectl-delete.ts
- lib/cli/scripts/kubectl-image.ts
- lib/cli/scripts/licenses.ts
- lib/cli/scripts/plugins/check-env.ts
- lib/cli/scripts/plugins/governance-health.ts
- lib/cli/scripts/plugins/plugin-model.ts
- lib/cli/scripts/plugins/process-automation-check-plugin.ts
- lib/cli/scripts/plugins/process-service-check-plugin.ts
- lib/cli/scripts/resources.ts
- lib/cli/tooling/dotenv.ts
> - [ ] Bugfix
- fix eslint warnings for the CLI project
- reduce code duplication for …
> [AAE-7240] fix eslint issues in CLI project

- lib/testing/src/lib/protractor/core/pages/material/dropdown.page.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Adding method needed to complete e2e test in alfresco-apps
**Does this …
> [AAE-5840] Adding dropdown method needed for e2e test

- lib/core/services/public-api.ts
- lib/core/services/sort-by-category.service.spec.ts
- lib/core/services/sort-by-category.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-6376
Sort-by-category logic is used in different …
> [AAE-6376] Adding Sort by Category service

- demo-shell/package.json
- lib/cli/package-lock.json
- lib/cli/package.json
- lib/content-services/package.json
- lib/core/package.json
- lib/extensions/package.json
- lib/insights/package.json
- lib/process-services-cloud/package-lock.json
- lib/process-services-cloud/package.json
- lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts
- lib/process-services/package.json
- lib/testing/package.json
- package-lock.json
- package.json
Signed-off-by: eromano <eugenioromano16@gmail.com>
> - [ ] Bugfix
fix cloud variables  …
> fix cloud variables 4.8.1

- lib/cli/scripts/init-aae-env.ts
> adf-cli - Give the ability to specify a different sso host from the gateway

- e2e/protractor.excludes.json
- lib/testing/src/lib/protractor/core/pages/form/widgets/tab.page.ts
> [AAE-7662] attach file modal TabPage selector update - protractor

- angular.json
- lib/core/info-drawer/info-drawer.component.spec.ts
- lib/core/viewer/components/viewer.component.spec.ts
> - [ ] Bugfix
- fix material icons rendering for Core unit tests
- add additional …
> additional unit tests for Viewer component

- lib/process-services-cloud/src/lib/services/public-api.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-7801 …
> [AAE-7801] Export TaskListCloudServiceInterface and BaseCloudService

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-header/mocks/task-details-cloud.mock.ts
> [AAE-7376] Added process instance link in task details

- .travis.yml
> Playwright travis.yml update

- e2e/protractor.excludes.json
> - [ ] Bugfix
> - [x] Other... Please describe: test was excluded because of bug, the bug is now fixed
**Does this PR …
> [AAE-7705] unexclude fixed test

- lib/cli/scripts/init-aps-env.ts
> adf-cli init-aps: Fail in case of error

- lib/testing/src/lib/protractor/core/pages/material/dropdown.page.ts
- lib/testing/src/lib/protractor/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
- lib/testing/src/lib/protractor/process-services-cloud/pages/edit-task-filter-cloud-component.page.ts
…
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-5880
**Does this PR …
> [AAE-5880] Add Tasks Create, DueDate range testing methods in the testing page

- lib/cli/package-lock.json
- lib/cli/package.json
- lib/cli/scripts/init-aae-env.ts
- lib/cli/scripts/kubectl-clean-app.ts
- lib/cli/scripts/scan-env.ts
- lib/content-services/package.json
- lib/core/package.json
- lib/extensions/package.json
- lib/process-services-cloud/package.json
- lib/process-services/package.json
- lib/testing/package.json
- package-lock.json
- package.json
> Manually upgrade to latest js-api

- lib/testing/src/lib/protractor/core/pages/card-view/card-view-text-item.page.ts
- lib/testing/src/lib/protractor/process-services-cloud/pages/task-header-cloud-component.page.ts
> [AAE-7818] e2e - Task involved users can access process instance details

- angular.json
- lib/core/form/components/form-field/form-field.component.spec.ts
- lib/core/form/components/form-field/form-field.component.ts
- lib/core/form/components/form-renderer.component.spec.ts
- lib/core/form/components/form-renderer.component.ts
- lib/core/form/components/widgets/core/form.model.spec.ts
- lib/core/form/components/widgets/core/form.model.ts
- lib/core/form/components/widgets/widget.component.spec.ts
- lib/core/form/components/widgets/widget.component.ts
- lib/core/form/events/form-rules.event.ts
- lib/core/form/events/index.ts
- lib/core/form/models/form-rules.model.spec.ts
- lib/core/form/models/form-rules.model.ts
- lib/core/form/public-api.ts
- lib/core/form/services/form.service.spec.ts
- lib/core/form/services/form.service.ts
- lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
- lib/process-services/src/lib/form/form.component.visibility.spec.ts
- lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts
> [AAE-8086] Propagate form events

- angular.json
- lib/core/form/models/form-rules.model.spec.ts
- lib/core/form/models/form-rules.model.ts
- lib/core/form/services/form.service.spec.ts
- lib/core/form/services/form.service.ts
> [AAE-8086] Remove form rules events that kill performance

- lib/core/form/components/widgets/core/form-field.model.ts
- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
- lib/process-services-cloud/src/lib/people/mock/user-cloud.mock.ts
> [AAE-8061] Add groups restriction to people widget

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/datatable/datatable.component.html
- demo-shell/src/app/components/datatable/datatable.component.scss
- demo-shell/src/app/components/datatable/datatable.component.ts
- lib/core/datatable/components/datatable/datatable.component.html
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-7819
Custom header template …
> [AAE-7819] Change columns order - fix for custom header

- .eslintrc.json
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-8554 …
> [AAE-8554] - Fix linked dropdown values are displayed but not submitted

- lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5480 …
> [ADF-5480] Fix partially hidden icon on permissions

- lib/core/form/models/form-rules.model.spec.ts
- lib/core/form/models/form-rules.model.ts
> Fix rules event filtering when no form is provided

- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
> - [X] Bugfix
use all the filter fields to count the elements
**Does this PR …
> [AAE-7056] use all the filter fields to count the elements

- e2e/process-services-cloud/pages/people-group-cloud-component.page.ts
- e2e/process-services-cloud/people/people-group-cloud-filter-component.e2e.ts
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
- lib/process-services-cloud/src/lib/people/mock/user-cloud.mock.ts
- lib/testing/src/lib/protractor/process-services-cloud/pages/group-cloud-component.page.ts
- lib/testing/src/lib/protractor/process-services-cloud/pages/people-cloud-component.page.ts
> [AAE-8061] Fix the group restriction for people widget

- demo-shell/src/app/components/datatable/datatable.component.html
- demo-shell/src/app/components/datatable/datatable.component.ts
- docs/core/components/data-column.component.md
- docs/core/components/datatable.component.md
- lib/core/datatable/components/columns-selector/columns-selector.component.html
- lib/core/datatable/components/columns-selector/columns-selector.component.scss
- lib/core/datatable/components/columns-selector/columns-selector.component.spec.ts
- lib/core/datatable/components/columns-selector/columns-selector.component.ts
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/core/datatable/data/data-column.model.ts
- lib/core/datatable/data/data-table.schema.ts
- lib/core/datatable/data/object-datacolumn.model.ts
- lib/core/datatable/datatable.module.ts
- lib/core/datatable/directives/main-data-table-action-template.directive.spec.ts
- lib/core/datatable/directives/main-data-table-action-template.directive.ts
- lib/core/datatable/public-api.ts
- lib/core/i18n/en.json
- lib/core/pipes/filter-array.pipe.ts
- lib/core/pipes/filter-out-every-object-by-prop.pipe.spec.ts
- lib/core/pipes/filter-out-every-object-by-prop.pipe.ts
- lib/core/pipes/filter-string.pipe.spec.ts
- lib/core/pipes/filter-string.pipe.ts
- lib/core/pipes/pipe.module.ts
- lib/core/pipes/public-api.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-7817
Added possibility to add …
> [AAE-7817] Show hide columns on datatable

- .eslintrc.json
- .vscode/settings.json
- package-lock.json
- package.json
> - [ ] Bugfix
- use the correct version of the rxjs plugin for eslint
- fix the …
> [AAE-8659] fix eslint configuration for rxjs

- lib/core/pagination/pagination.component.html
- lib/core/pagination/pagination.component.spec.ts
- lib/core/pagination/pagination.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/MNT-22924 …
> [MNT-22924] Fix slow search results loading, limit number of pages

- demo-shell/src/app.config.json
> [AAE-8652] OAuth - use default profile email as scope

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
> - [X] Bugfix
fix small viewport attach file …
> [MNT-22844] fix small viewport attach file

- lib/core/form/components/form-renderer.component.scss
> - [ ] Bugfix
SCSS placeholders styles …
> [AAE-8948] Fix placeholders styles for left labels

- docs/core/services/user-access.service.md
- e2e/core/login/login-component.e2e.ts
- e2e/process-services-cloud/access/user-access-cloud.e2e.ts
- lib/core/mock/user-access.mock.ts
- lib/core/models/application-access.model.ts
- lib/core/models/public-api.ts
- lib/core/models/user-access.model.ts
- lib/core/services/auth-guard-sso-role.service.spec.ts
- lib/core/services/auth-guard-sso-role.service.ts
- lib/core/services/public-api.ts
- lib/core/services/user-access.service.spec.ts
- lib/core/services/user-access.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-8748 …
> [AAE-8748] - Auth guards call api when access is not in JWT

- lib/content-services/src/lib/dialogs/confirm.dialog.ts
> [AAE-8740] Fix default ConfirmDialogComponent title

- lib/core/services/auth-guard-sso-role.service.spec.ts
- lib/core/services/auth-guard-sso-role.service.ts
> - [X] Bugfix
The auth SSO guard always query if the user is a content administrator, even when the content provider …
> [AAE-8155] Check if it is content admin only when content provider is available

- lib/core/services/auth-guard-sso-role.service.spec.ts
- lib/core/services/auth-guard-sso-role.service.ts
> [AAE-8155] Fix typo in providers

- e2e/process-services-cloud/task-list/tasks-claim-release.e2e.ts
- e2e/protractor.excludes.json
- lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
> [ADF-5479] Disable clam/release button for standalone tasks on APA

- docs/process-services-cloud/components/people-cloud.component.md
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
> [AAE-8076] Add groupsRestriction input to docs

- lib/core/services/user-access.service.spec.ts
- lib/core/services/user-access.service.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-9094 …
> [AAE-9094] - Fix app breaking when configured with BASIC auth

- e2e/core/login/login-component.e2e.ts
- lib/core/login/components/login.component.spec.ts
> - [ ] Bugfix
Convert e2e to unit …
> Convert login fields validation e2e to unit

- e2e/process-services/form/attach-file-content-service.e2e.ts
> [ADF-5494] Remove useless imports

- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
> Transform e2e into unit

- scripts/build/build-content-services.sh
- scripts/build/build-core.sh
- scripts/build/build-extensions.sh
- scripts/build/build-insights.sh
- scripts/build/build-process-services-cloud.sh
- scripts/build/build-process-services.sh
- scripts/build/build-testing.sh
> Fix the nx path to avoid installing it globally

- e2e/process-services-cloud/process/process-custom-filters.e2e.ts
- e2e/process-services-cloud/task-list/edit-process-filters-component.e2e.ts
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-9293 …
> [AAE-9293] Allow editing and restoring default process cloud filter

- lib/core/form/components/form-renderer.component.html
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-9135
Added id to …
> [AAE-9135] Print simple form

- scripts/travis/update/update-project.sh
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-9337 …
> [AAE-9337] Improve update project script

- lib/core/form/components/widgets/core/form-field.model.ts
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-9128
date-widget check if …
> [AAE-9298] FE ADF Date widget handle dynamic date values

- lib/core/language-menu/language-menu.component.spec.ts
- lib/core/language-menu/language-menu.component.ts
> [AAE-9112] Included a output event on change of language

- .nxignore
- lib/cli/scripts/resources.ts
> [AAE-9370] Add manageruser to default apps

- lib/core/models/general-user.model.ts
- lib/core/models/public-api.ts
- lib/core/pipes/full-name.pipe.ts
- lib/core/pipes/user-initial.pipe.spec.ts
- lib/core/pipes/user-initial.pipe.ts
- lib/core/userinfo/components/user-info.component.spec.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-9310?filter=-1
**Does this PR …
> [AAE-9310] Add missing initial on task assignment dialog

- lib/core/datatable/components/columns-selector/columns-selector.component.html
- lib/testing/src/lib/protractor/core/pages/data-table-component.page.ts
- lib/testing/src/lib/protractor/core/pages/data-table/columns-selector.ts
- lib/testing/src/lib/protractor/core/pages/data-table/public-api.ts
- lib/testing/src/lib/protractor/process-services-cloud/pages/process-list-cloud-component.page.ts
- lib/testing/src/lib/protractor/process-services-cloud/pages/task-list-cloud-component.page.ts
- lib/testing/src/lib/protractor/process-services-cloud/resources/resources.ts
> [AAE-7865] Configuration of columns in Task and Process Lists in ADW e2e

- .travis.yml
- scripts/travis/update/pr-creator.js
- scripts/travis/update/update-project.sh
> [AAE-9462] Being able to add contributors of the current upstream

- lib/core/services/user-access.service.spec.ts
- lib/core/services/user-access.service.ts
- lib/process-services-cloud/src/lib/group/services/identity-group.service.ts
- lib/process-services-cloud/src/lib/people/services/identity-user.service.ts
> [AAE-9311] Use new micro service ingress for people/group

- angular.json
> - [ ] Bugfix
Local unit test execution issues
https://alfresco.atlassian.net/browse/AAE-10065 …
> [AAE-10065] - Fix can't debug unit tests on ADF

- lib/core/ng-package.json
- lib/core/package.json
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-10091
Added missing adf-core …
> [AAE-10091] Add adf-core missing dependencies

- lib/cli/README.md
- lib/cli/scripts/check-plugin-env.ts
- lib/cli/scripts/init-acs-env.ts
- lib/cli/scripts/init-aps-env.ts
- lib/cli/scripts/plugins/check-env.ts
- lib/cli/scripts/scan-env.ts
> [AAE-9169] adf-cli - Change the doc and add clientId input

- lib/core/icon/icon.component.stories.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-10104
**Does this PR …
> [AAE-10104] Storybook stories for Icon component

- lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-9348 …
> [AAE-9348] Fix validate for people and group widgets

- lib/core/language-menu/language-menu.component.stories.ts
- lib/core/language-menu/language-menu.module.ts
- lib/core/language-menu/language-picker.component.stories.ts
- lib/core/language-menu/language-picker.component.ts
- lib/core/mock/language.service.mock.ts
- lib/core/services/language.service.interface.ts
- lib/core/services/language.service.ts
- package-lock.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-10103
Added new stories for …
> [AAE-10103] language-menu storybook

- lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-9220 …
> [AAE-9219] replay errored service task part 2

- lib/core/comments/comment-list.component.stories.ts
- lib/core/comments/comments.component.stories.ts
- lib/core/comments/comments.module.ts
- lib/core/mock/comment-content-service.mock.ts
- lib/core/mock/comment-content.mock.ts
- lib/core/mock/comment-process-service.mock.ts
- lib/core/mock/comment-process.mock.ts
- lib/core/services/comment-content.service.interface.ts
- lib/core/services/comment-content.service.spec.ts
- lib/core/services/comment-content.service.ts
- lib/core/services/comment-process.service.interface.ts
- lib/core/services/comment-process.service.spec.ts
- lib/core/services/comment-process.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-10125
**Does this PR …
> [AAE-10125] Storybook stories for Comments component

- lib/core/context-menu/context-menu-overlay.service.ts
> [AAE-10149] Material Overlay - Use flexibleConnectedTo and remove deprecated

- scripts/travis/build/npm-check-bundles.sh
> check-bundle ng13

- .travis.yml
> - [ ] Bugfix
> - [x] Other... Please describe: remove duplicated job …
> [AAE-10347] Remove playwright travis job duplication

- lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.spec.ts
> Fix incorrect import in card view array

- angular.json
> [AAE-10460] fix storybook config

- angular.json
- lib/core/src/lib/form/components/widgets/core/form-field.model.ts
- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.scss
- nx.json
> [AAE-10219] Add css to align according to alignment property in RadioField

- .travis.yml
- nx.json
- scripts/travis/affected-contains.sh
> Run e2e only when lib affected

- lib/core/src/lib/userinfo/components/user-info.component.spec.ts
- lib/core/src/lib/userinfo/components/user-info.component.ts
> [AAE-9464] - Fetch profile picture from ACS only in case of ECM

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.html
> Fix assignment type translations

- .travis.yml
- scripts/build/build-all-lib.sh
- scripts/travis/affected-contains.sh
- scripts/travis/e2e/e2e.sh
> Short circuit e2e in case lib not affected

- scripts/travis/build/npm-check-bundles.sh
> app config schema - Not anymore used

- lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4609 …
> [ACA-4609] Fix regression checkbox list shown horizontally

- .travis.yml
- e2e/protractor.conf.js
- e2e/protractor.excludes.json
- lib/testing/src/lib/protractor/core/pages/material/dropdown.page.ts
> - [ ] Bugfix
> - [x] Other... Please describe: fixing e2es …
> [AAE-10468] e2es Task List fixes

- docs/release-notes/RelNote500.md
Added content to describe content, features and upgrade.
> - [ ] Bugfix
**Does this PR …
> Release notes for ADF 5

- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
- lib/process-services-cloud/src/lib/models/date-format-cloud.model.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/public-api.ts
> - [ ] Bugfix
Fix deprecation warning
https://alfresco.atlassian.net/browse/AAE-10311 …
> [AAE-10311] - Fix deprecation warning about dates in cloud unit tests

- lib/core/src/lib/form/components/widgets/date-time/date-time.widget.spec.ts
- lib/core/src/lib/form/components/widgets/date/date.widget.spec.ts
> - [ ] Bugfix
Fix deprecation warnings
https://alfresco.atlassian.net/browse/AAE-10316 …
> [AAE-10316] - Fix moment js deprecation warnings in core

- lib/core/src/lib/datatable/components/datatable/datatable.component.stories.ts
> - [ ] Bugfix
[AAE-6991](https://alfresco.atlassian.net/browse/AAE-6991)
Added …
> [AAE-6991] Stories for datatable component

- scripts/travis/update/update-project.sh
> Fix update-project github user

- lib/content-services/src/lib/breadcrumb/breadcrumb.component.html
- lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.spec.ts
- lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.html
- lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.spec.ts
- lib/core/src/lib/datatable/components/datatable-cell/datatable-cell.component.spec.ts
- lib/core/src/lib/datatable/components/datatable-cell/datatable-cell.component.ts
- lib/core/src/lib/datatable/components/date-cell/date-cell.component.ts
- lib/core/src/lib/datatable/components/filesize-cell/filesize-cell.component.ts
- lib/core/src/lib/i18n/en.json
- lib/core/src/lib/notifications/components/notification-history.component.html
- lib/core/src/lib/pipes/user-initial.pipe.spec.ts
- lib/core/src/lib/pipes/user-initial.pipe.ts
- lib/core/src/lib/userinfo/components/user-info.component.html
- lib/core/src/lib/userinfo/components/user-info.component.spec.ts
- lib/testing/src/lib/protractor/core/pages/user-info.page.ts
> - [x] Bugfix
"Personal files" screen has some accessibility issue.
Accessibility …
> [ACS-3537] - Fix accessibility issues in ACA personal files

- lib/content-services/src/lib/document-list/components/document-list.component.html
- lib/content-services/src/lib/i18n/en.json
- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/i18n/en.json
> - [x] Bugfix
"Trashcan" ACA screen has some accessibility issues.
Accessibility …
> ACS-3544 Fix accessibility issues in ACA trashcan

- lib/core/src/lib/layout/components/header/header.component.stories.ts
- lib/core/src/lib/layout/components/sidebar-action/sidebar-action-menu.component.ts
- lib/core/src/lib/layout/components/sidebar-action/sidebar-action.component.stories.ts
- lib/core/src/lib/layout/components/sidenav-layout/sidenav-layout.component.stories.ts
- lib/core/src/lib/layout/components/sidenav-layout/sidenav-layout.component.ts
> [AAE-10281] Stories for components in Layout module in ADF Core

- lib/core/src/lib/rich-text-editor/mocks/rich-text-editor.mock.ts
- lib/core/src/lib/rich-text-editor/rich-text-editor.component.stories.ts
> - [ ] Bugfix
[AAE-10453](https://alfresco.atlassian.net/browse/AAE-10453)
Added …
> [AAE-10453] Stories for rich-text-editor component

- docs/release-notes/README.md
> Update README.md with link to Rel Note 5.0.0

- lib/testing/src/lib/protractor/core/pages/login.page.ts
> [AAE-10706] Selector login fix

- lib/core/src/lib/card-view/components/card-view-arrayitem/card-view-arrayitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-boolitem/card-view-boolitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.ts
- lib/core/src/lib/card-view/components/card-view-mapitem/card-view-mapitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/src/lib/card-view/components/card-view/card-view.component.stories.ts
- lib/core/src/lib/card-view/mock/card-view-content.mock.ts
- lib/core/src/lib/mock/card-view-content.mock.ts
> - [ ] Bugfix
[https://alfresco.atlassian.net/browse/AAE-10446](https://alfresco.atlassian.net/browse/AAE-10446) …
> [AAE-10446] Storybook CardView module

- lib/process-services/src/lib/attachment/process-attachment-list.component.spec.ts
- lib/process-services/src/lib/attachment/task-attachment-list.component.spec.ts
- lib/process-services/src/lib/form/form.component.spec.ts
- lib/process-services/src/lib/form/start-form.component.mock.ts
- lib/process-services/src/lib/form/start-form.component.spec.ts
- lib/process-services/src/lib/mock/process/process-attachments.mock.ts
- lib/process-services/src/lib/mock/task/task-attachments.mock.ts
- lib/process-services/src/lib/people/components/people-search/people-search.component.spec.ts
- lib/process-services/src/lib/people/components/people/people.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
- lib/process-services/src/lib/process-list/services/process.service.spec.ts
- lib/process-services/src/lib/task-list/components/task-details.component.spec.ts
- lib/process-services/src/lib/task-list/services/tasklist.service.spec.ts
> - [ ] Bugfix
Unit test fixes
https://alfresco.atlassian.net/browse/AAE-10317
**Does …
> [AAE-10317] - Fix APS unit tests warning "Test has no expectations"

- lib/core/src/lib/userinfo/components/user-info.component.html
> ACA-4615 Restrict Edit Profile functionality to ECM users only

- lib/core/src/lib/form/components/widgets/core/form-field-validator.spec.ts
- lib/core/src/lib/form/components/widgets/core/form-field-validator.ts
>  [AAE-10643] Form validation should fail for dropdown required field and default value

- scripts/travis/e2e/e2e.sh
> - [ ] Bugfix
> - [x] Other... Please describe: updating run test script on Travis …
> [AAE-10707] - test e2e.sh fix

- .travis.yml
- e2e/protractor.excludes.json
- lib/core/src/lib/buttons-menu/buttons-menu.component.stories.ts
- lib/core/src/lib/buttons-menu/buttons-menu.module.ts
> - [ ] Bugfix
[https://alfresco.atlassian.net/browse/AAE-10102](https://alfresco.atlassian.net/browse/AAE-10102) …
> [AAE-10102] Storybook stories for Buttons Menu component

- lib/core/src/lib/datatable/data/object-datatable-adapter.spec.ts
- lib/core/src/lib/datatable/data/object-datatable-adapter.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-6153
Correct result of …
> [AAE-6153] Enable correct sorting while data are numbers

- scripts/travis/affected-contains.sh
- scripts/travis/e2e/e2e.sh
> fix cron run for e2e

- lib/content-services/src/lib/content-metadata/services/content-metadata.service.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/directives/node-counter.directive.spec.ts
- lib/content-services/src/lib/document-list/services/document-list.service.spec.ts
- lib/content-services/src/lib/document-list/services/node-actions.service.spec.ts
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-dialog.component.spec.ts
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.spec.ts
- lib/content-services/src/lib/search/components/search-control.component.spec.ts
- lib/content-services/src/lib/search/components/search-filter-chips/search-filter-menu-card/search-filter-menu-card.component.spec.ts
- lib/content-services/src/lib/search/services/search-query-builder.service.spec.ts
- lib/content-services/src/lib/upload/components/base-upload/upload-base.spec.ts
- lib/content-services/src/lib/upload/components/upload-drag-area.component.spec.ts
- lib/content-services/src/lib/version-manager/version-upload.component.spec.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-10320
**Does this PR …
> [AAE-10320] Fix Content Service unit tests - 'has no expectations'

- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/new-version-uploader/new-version-uploader.dialog.html
- lib/content-services/src/lib/version-manager/version-list.component.html
…ark issue
> - [x] Bugfix
issues in version dialog
1. descernible text
2. banner landmark
3. contentinfo landmark …
> [ACS-3549] Manage Versions Dialog

- lib/core/src/lib/userinfo/components/user-info.component.html
> ACA-4615 Reverting the view profile change for sso

- lib/core/src/lib/userinfo/components/user-info.component.html
> ACA-4615 Adding edit profile functionality for SSO users

- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/src/lib/card-view/validators/card-view-item-int.validator.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-10911
**Does this PR …
> [AAE-10911] Fix Cardview Int validator for only spaces

- lib/core/src/lib/services/user-access.service.spec.ts
- lib/core/src/lib/services/user-access.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-10556
**Does this PR …
> [AAE-10556] Admin with HxP - In case the roles API call fails the app crashes

- lib/content-services/src/lib/new-version-uploader/new-version-uploader.dialog.html
- lib/content-services/src/lib/version-manager/version-list.component.html
> - [x] Bugfix
heading is inappropriately coded as a heading.
Replace with proper …
> [acs-3549] fix accessibility issues from csv file

- lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.html
> - [x] Bugfix
The delete button is missing an accessible name/label
add aria-label to …
> [acs-3548] fixed csv file issue(880240)

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/aspect-list-sample/aspect-list-sample.component.html
- demo-shell/src/app/components/breadcrumb-demo/breadcrumb-demo.component.html
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/process-services/src/lib/i18n/en.json
- lib/process-services/src/lib/process-list/components/process-instance-tasks.component.html
> - [x] Bugfix
Some aria-label translations are missing
Translations has been added. …
> [ACS-3600] Add missing label translations

- .storybook/preview.js
- lib/core/.storybook/preview.js
- lib/core/src/lib/card-view/components/card-view-arrayitem/card-view-arrayitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-boolitem/card-view-boolitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-mapitem/card-view-mapitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.stories.ts
- lib/core/src/lib/card-view/components/card-view/card-view.component.stories.ts
- lib/core/src/lib/core.module.ts
- lib/core/src/lib/dialogs/download-zip/download-zip.dialog.stories.ts
- lib/core/src/lib/dialogs/edit-json/edit-json.dialog.stories.ts
- lib/core/src/lib/icon/icon.component.stories.ts
- lib/core/src/lib/language-menu/language-menu.component.stories.ts
- lib/core/src/lib/language-menu/language-picker.component.stories.ts
- lib/core/src/lib/layout/components/header/header.component.stories.ts
- lib/core/src/lib/layout/components/sidebar-action/sidebar-action.component.stories.ts
- lib/core/src/lib/layout/components/sidenav-layout/sidenav-layout.component.stories.ts
- lib/core/src/lib/notifications/components/add-notification.stories.component.ts
- lib/core/src/lib/notifications/components/notification-history.component.stories.ts
- lib/core/src/lib/notifications/notification-history.module.ts
- lib/core/src/lib/pagination/pagination.component.stories.ts
- lib/core/src/lib/search-text/search-text-input.component.stories.ts
- lib/core/src/lib/sorting-picker/sorting-picker.component.stories.ts
- lib/core/src/lib/templates/empty-content/empty-content.component.stories.ts
- lib/core/src/lib/templates/error-content/error-content.component.stories.ts
- lib/core/src/lib/userinfo/components/user-info.component.stories.ts
> - [ ] Bugfix
[AAE-10451](https://alfresco.atlassian.net/browse/AAE-10451)
Added …
> [AAE-10451] Stories for notification-history component

- docs/release-notes/RelNote500.md
> - [ ] Bugfix
> - [X ] Documentation
> - …
> fix tables not showing correctly on doc site

- lib/content-services/src/lib/document-list/services/custom-resources.service.ts
> - [x] Bugfix
fix the recent files query, fixes #7906  …
> [ADF-5502] fix recent files query

- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/directives/node-delete.directive.spec.ts
- lib/core/src/lib/directives/upload.directive.spec.ts
- lib/core/src/lib/form/components/widgets/checkbox/checkbox.widget.spec.ts
- lib/core/src/lib/form/components/widgets/content/content.widget.spec.ts
- lib/core/src/lib/form/components/widgets/core/form.model.spec.ts
- lib/core/src/lib/form/components/widgets/core/form.model.ts
- lib/core/src/lib/form/components/widgets/date-time/date-time.widget.spec.ts
- lib/core/src/lib/form/components/widgets/date/date.widget.spec.ts
- lib/core/src/lib/form/components/widgets/people/people.widget.spec.ts
- lib/core/src/lib/form/components/widgets/text/text.widget.spec.ts
- lib/core/src/lib/form/components/widgets/widget.component.spec.ts
- lib/core/src/lib/form/services/form.service.spec.ts
- lib/core/src/lib/form/services/widget-visibility-cloud.service.spec.ts
- lib/core/src/lib/form/services/widget-visibility.service.spec.ts
- lib/core/src/lib/layout/components/sidebar-action/sidebar-action-menu.component.spec.ts
- lib/core/src/lib/login/components/login.component.spec.ts
- lib/core/src/lib/services/authentication.service.spec.ts
- lib/core/src/lib/services/bpm-user.service.spec.ts
- lib/core/src/lib/services/download.service.spec.ts
- lib/core/src/lib/services/log.service.spec.ts
- lib/core/src/lib/services/people-process.service.spec.ts
- lib/core/src/lib/services/renditions.service.spec.ts
- lib/core/src/lib/viewer/components/viewer.component.spec.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-10644
**Does this PR …
> [AAE-10644] Fix tests that have no expectations - core lib part 2

- lib/core/src/lib/services/authentication.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/MNT-23233
Instead of contacting …
> MNT-23233: get users according to providers configuration

- lib/core/src/lib/app-config/app-config.service.spec.ts
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
> [AAE-10644] Fix tests that have no expectations - core lib part 1

- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
- lib/process-services/src/lib/task-list/components/task-form/task-form.component.html
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-11238
**Does this PR …
> [AAE-11238] Fix position of loading spinner on task loading

- lib/cli/scripts/init-aae-env.ts
> [AAE-10835] adf-cli Being able to pass params as input to handle custom cases

- lib/cli/scripts/init-aps-env.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-11217
**Does this PR …
> [AAE-11217] - Make init-aps script not rely on email domain

- angular.json
- lib/cli/package.json
- lib/cli/tsconfig.json
> Adf-cli - Move the cli bundle under dist/libs/cli

- lib/core/src/lib/about/about.component.html
- lib/core/src/lib/about/about.component.ts
> [AAE-11126] About Component - Deprecate commit sha

- .travis.yml
> Move check bundle after release npm
