- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
> - [x] Bugfix
[ACA-3240](https://issues.alfresco.com/jira/browse/ACA-3240)
**Does …
> [ACA-3240] Information inside custom aspects when properties have default value is wrong displayed

- lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.scss
> - [x] Bugfix
The radio buttons in the radio-buttons widgets are displayed next to the label wich is not the case …
> [ADF-5131] Radio buttons display below label

- lib/process-services/src/lib/form/start-form.component.scss
> - [x] Bugfix / Stylefix
When the window is too small, in the form component, the validation and reload buttons may …
> [AAE-2478] Add margin to the form title to avoid overlaping the buttons

- lib/core/form/components/form-field/form-field.component.spec.ts
- lib/core/form/components/form-field/form-field.component.ts
- lib/core/form/components/mock/form-renderer.component.mock.ts
- lib/core/form/services/widget-visibility.service.spec.ts
- lib/core/form/services/widget-visibility.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3235
**Does this PR …
> [ACA-3235] FE - Should not include invisible fields in payload on Start/Save adf-form.

- lib/core/services/sites.service.spec.ts
- lib/core/services/sites.service.ts
> - [ ] Bugfix
use new api siteservice to use memebership …
> [ACA-1606] use new api siteservice

- e2e/pages/adf/demo-shell/process-services/task-filters-demo.page.ts
- e2e/pages/adf/process-services/filters.page.ts
- e2e/pages/adf/process-services/process-filters.page.ts
- e2e/pages/adf/process-services/task-filters.page.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.scss
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.scss
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
- lib/process-services/src/lib/process-list/components/process-filters.component.html
- lib/process-services/src/lib/process-list/components/process-filters.component.scss
- lib/process-services/src/lib/process-list/components/process-filters.component.spec.ts
- lib/process-services/src/lib/process-list/components/process-filters.component.ts
- lib/process-services/src/lib/task-list/components/task-filters.component.html
- lib/process-services/src/lib/task-list/components/task-filters.component.scss
- lib/process-services/src/lib/task-list/components/task-filters.component.spec.ts
- lib/testing/src/lib/process-services-cloud/pages/process-filters-cloud-component.page.ts
- lib/testing/src/lib/process-services-cloud/pages/task-filters-cloud-component.page.ts
- lib/testing/src/lib/process-services/pages/filters.page.ts
- lib/testing/src/lib/process-services/pages/process-filters.page.ts
- lib/testing/src/lib/process-services/pages/task-filters.page.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5103 …
> [ADF-5103] FE - Process/task filter - Backporting the components styles to ADF

- lib/extensions/src/lib/services/extension.service.ts
> Ability to evaluate an object as payload

- README.md
- docs/content-services/components/content-node-selector-panel.component.md
- docs/process-services/components/process-list.component.md
- docs/process-services/components/task-list.component.md
- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- lib/content-services/src/lib/mock/public-api.ts
- lib/content-services/src/lib/mock/sites-dropdown.component.mock.ts
- lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts
- lib/content-services/src/lib/site-dropdown/sites-dropdown.component.ts
- lib/core/form/services/activiti-alfresco.service.ts
- lib/core/services/sites.service.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.html
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
- lib/process-services/src/lib/i18n/en.json
> - [x] Bugfix
The update of the title doesn't match the selected site but the selected node and not every time …
> [AAE-2200] Upload dialog title should match selected site.

- lib/core/form/components/widgets/checkbox/checkbox.widget.html
- lib/core/form/components/widgets/checkbox/checkbox.widget.spec.ts
- lib/core/form/components/widgets/checkbox/checkbox.widget.ts
- lib/core/form/components/widgets/core/form-field.model.spec.ts
- lib/core/form/components/widgets/core/form-field.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5143
The field value was being parsed at the widget level …
> [ADF-5143] Fix Checkbox widget value parsing

- demo-shell/resources/i18n/en.json
- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.html
- demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
- docs/content-services/components/document-list.component.md
- docs/content-services/components/upload-button.component.md
- docs/content-services/components/upload-drag-area.component.md
- docs/content-services/components/upload-version-button.component.md
- docs/content-services/components/version-manager.component.md
- docs/core/components/datatable.component.md
- lib/content-services/src/lib/document-list/components/document-list.component.html
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/content-services/src/lib/document-list/data/share-data-row.model.ts
- lib/content-services/src/lib/document-list/data/share-datatable-adapter.ts
- lib/content-services/src/lib/upload/components/base-upload/upload-base.ts
- lib/content-services/src/lib/upload/components/upload-button.component.html
- lib/content-services/src/lib/upload/components/upload-button.component.spec.ts
- lib/content-services/src/lib/upload/components/upload-button.component.ts
- lib/content-services/src/lib/upload/components/upload-drag-area.component.spec.ts
- lib/content-services/src/lib/upload/components/upload-drag-area.component.ts
- lib/content-services/src/lib/upload/components/upload-version-button.component.ts
- lib/content-services/src/lib/version-manager/version-manager.component.html
- lib/content-services/src/lib/version-manager/version-manager.component.spec.ts
- lib/content-services/src/lib/version-manager/version-manager.component.ts
- lib/content-services/src/lib/version-manager/version-upload.component.html
- lib/content-services/src/lib/version-manager/version-upload.component.ts
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-45
Currently I can not drop a file over another file to …
> [ACA-45] Drag and Drop a New Version

- lib/testing/src/lib/core/pages/form/form-fields.ts
- lib/testing/src/lib/process-services/pages/task-list.page.ts
> [ACA-3314] Add cancelButton and noFormTemplate form elements

- lib/core/form/components/widgets/container/container.widget.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3277
**Does this PR …
> [ACA-3277] - remove unnecessary style

- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
> - [x] Bugfix
Value not translated
Value should be translated
**Does this PR …
> [ACA-3252] Content Metadata - Use the translation key

- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
- lib/process-services/src/lib/mock/process/process-instances-list.mock.ts
- lib/process-services/src/lib/mock/task/task-list.mock.ts
- lib/process-services/src/lib/process-list/components/process-list.component.spec.ts
- lib/process-services/src/lib/process-list/components/process-list.component.ts
- lib/process-services/src/lib/task-list/components/task-list.component.spec.ts
- lib/process-services/src/lib/task-list/components/task-list.component.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3368
The columns are …
> [ACA-3368] Update datatable columns when presetColumn schema changes

- e2e/process-services/start-process-component.e2e.ts
- e2e/process-services/stencil.e2e.ts
- e2e/process-services/task-assignee.e2e.ts
- lib/testing/src/lib/process-services/pages/start-process.page.ts
> [ACA-3390]Add startProcessWithApplication method on StartProcessPage

- lib/content-services/src/lib/document-list/components/document-list.component.html
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.ts
> - [ ] Bugfix
No content exposed from the DataTable to the DocumentList.
In order to …
> [ADF-5153] Transclusion exposed from the DataTable to the DocumentList

- lib/extensions/src/lib/services/extension.service.ts
> [ACA-3382] Expression - Fix the obj reference

- lib/content-services/src/lib/breadcrumb/breadcrumb.component.html
Breadcrumbs text are not announcing as headings
Breadcrumbs will now …
> [ACA-2596] - fix: heading markup for bread crumbs

- demo-shell/src/app/components/process-service/process-service.component.html
- demo-shell/src/app/components/process-service/process-service.component.ts
- docs/process-services/components/start-process.component.md
- lib/core/templates/empty-content/empty-content.component.html
- lib/core/templates/empty-content/empty-content.component.scss
- lib/core/templates/template.module.ts
- lib/process-services/src/lib/i18n/en.json
- lib/process-services/src/lib/process-list/components/start-process.component.html
- lib/process-services/src/lib/process-list/components/start-process.component.scss
- lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process.component.ts
- lib/testing/src/lib/process-services-cloud/pages/task-form-cloud-component.page.ts
- lib/testing/src/lib/process-services/pages/start-process.page.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3358
**Does this PR …
> [ACA-3358] Show user friendly error templates when there are no applications/processDefinitions

- lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
- lib/process-services/src/lib/content-widget/attach-file-widget.components.spec.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ACA-2962
When the just link to …
> [ACA-2962] Fix attach file widget shows Local source when only link is enabled

- lib/core/form/components/widgets/hyperlink/hyperlink.widget.spec.ts
- lib/core/form/components/widgets/hyperlink/hyperlink.widget.ts
- lib/core/form/components/widgets/widget.component.ts
> - [x] Bugfix
value of the hyperlink is not used if valorized
hyperlink value is used …
> [MNT-21584] fix rendering Hyperlink

- e2e/pages/adf/process-services/process-list.page.ts
- e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
- e2e/process-services/process-filters-component.e2e.ts
- e2e/process-services/process-instance-details.e2e.ts
- e2e/process-services/stencil.e2e.ts
- e2e/process-services/task-assignee.e2e.ts
- e2e/process-services/widgets/amount-widget.e2e.ts
- e2e/process-services/widgets/attach-folder-widget.e2e.ts
- e2e/process-services/widgets/checkbox-widget.e2e.ts
- e2e/process-services/widgets/date-time-widget.e2e.ts
- e2e/process-services/widgets/date-widget.e2e.ts
- e2e/process-services/widgets/dropdown-widget.e2e.ts
- e2e/process-services/widgets/header-widget.e2e.ts
- e2e/process-services/widgets/multi-line-widget.e2e.ts
- e2e/process-services/widgets/number-widget.e2e.ts
- e2e/process-services/widgets/radio-buttons-widget.e2e.ts
- e2e/process-services/widgets/text-widget.e2e.ts
- lib/testing/src/lib/core/pages/form/form-fields.ts
- lib/testing/src/lib/process-services/pages/form-fields.page.ts
- lib/testing/src/lib/process-services/pages/process-filters.page.ts
- lib/testing/src/lib/process-services/pages/process-list.page.ts
- lib/testing/src/lib/process-services/pages/task-filters.page.ts
- Change the isCompleteFormButtonDisabled() method structure as per the [Code Style E2E 03-01](https://w3.alfresco.com/confluence/pages/viewpage.action?spaceKey=AP&title=Code+Style+E2E)
- Replace the isCompleteFormButtonDisabled() with isCompleteFormButtonEnabled() in the tests
- Add lists with the default tasks and process filters name in order to use a variable instead of a string (ADW eg. in the breadcrumb checks)
**What kind of change does this PR introduce?** (check one …
> [ACA-3329] Refactor isCompleteFormButtonDisabled method

- lib/core/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.scss
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5160
The CardView Key-Value Pairs Item overflows and does …
> [ADF-5160] Fix CardView Key-Value Pairs Item overflowing

- lib/core/form/services/activiti-alfresco.service.ts
- lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
- lib/process-services/src/lib/content-widget/attach-file-widget.components.spec.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3218
**Does this PR …
> [ACA-3218] Fix attach file widget - wrong payload when link is true

- e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts
- e2e/process-services-cloud/task-list-properties.e2e.ts
- e2e/protractor.excludes.json
- e2e/test.config.js
- lib/testing/src/lib/core/actions/api.service.ts
- lib/testing/src/lib/core/pages/form/form-fields.ts
- lib/testing/src/lib/core/utils/browser-actions.ts
- lib/testing/src/lib/core/utils/browser-visibility.ts
- lib/testing/src/lib/core/utils/logger.ts
- lib/testing/src/lib/process-services-cloud/actions/tasks.service.ts
- scripts/travis/e2e/process-services-cloud-e2e.sh
> - [ ] Bugfix
> - [z] Other... Please describe:
exclude failing test before the revert of the time modify is finalized …
> exclude failing test before the revert of the time modify is finalized

- lib/content-services/src/lib/search/base-query-builder.service.ts
- lib/content-services/src/lib/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/src/lib/search/search-header-query-builder.service.spec.ts
- lib/content-services/src/lib/search/search-query-builder.service.spec.ts
> - [ ] Bugfix
previous feature changed a public method introducing a breaking change …
> [ACA-3426] - reverted method renaming

- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/search/components/search-header/search-header.component.html
- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
> - [x] Bugfix
There is no translate for column title inside the tooltip of the search-header. …
> [ACA-3426] Add translate pipe to search-header tooltip

- docs/core/directives/version-compatibility.directive.md
- lib/core/core.module.ts
- lib/core/directives/directive.module.ts
- lib/core/directives/version-compatibility.directive.spec.ts
- lib/core/directives/version-compatibility.directive.ts
- lib/core/search-text/search-text-input.component.spec.ts
- lib/core/services/public-api.ts
- lib/core/services/version-compatibility-factory.ts
- lib/core/services/version-compatibility.service.spec.ts
- lib/core/services/version-compatibility.service.ts
- lib/core/testing/core.testing.module.ts
- lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5158
This new directive …
> [ADF-5158] ECM Version Directive

- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3447
When uploading a new version, if the upload is …
> [ACA-3447] Cancel upload of new version removes existing version

- lib/content-services/src/lib/search/search-header-query-builder.service.spec.ts
- lib/content-services/src/lib/search/search-header-query-builder.service.ts
> - [x] Bugfix
The search-header-service add duplicate column names inside the activeFilters array which disturb the …
> [ACA-3527] Add check to activeFilters update

- e2e/content-services/permissions/permissions-component.e2e.ts
- e2e/content-services/permissions/site-permissions.e2e.ts
- e2e/pages/adf/permissions.page.ts
- lib/testing/src/lib/content-services/dialog/add-permissions-dialog.page.ts
- lib/testing/src/lib/content-services/dialog/public-api.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5174
We need to expose the …
> [ADF-5174] Add Permisssions Dialog to adf-testing Lib

- lib/cli/scripts/kubectl-clean-app.ts
> adf-cli k8s-clean-app - Add more logs and default interval

- lib/testing/src/lib/core/pages/login-sso.page.ts
> - [ ] Bugfix
The login page for e2e tests fails randomly
Add password visibility to …
> [AAE-2972] Add password visibility to login sso page

- lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
> - [X] Bugfix
When clear is clicked all the filters are gone
When clear is clicked …
> [ADF-5175] - perform the search when at least one filter is active

- lib/content-services/src/lib/search/components/search-header/search-header.component.html
- lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
> - [ ] Bugfix
The search-header executes the search only when the "Apply" button is clicked. …
> [ADF-5177] Search-header execute when enter is pressed

- lib/core/datatable/components/datatable/datatable.component.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3529
**Does this PR …
>  [ACA-3529] Custom filter doesn't work properly when Direction is set to ASC

- lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.spec.ts
- lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.ts
- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
- lib/content-services/src/lib/search/components/search-number-range/search-number-range.component.ts
- lib/content-services/src/lib/search/components/search-radio/search-radio.component.ts
- lib/content-services/src/lib/search/components/search-slider/search-slider.component.ts
- lib/content-services/src/lib/search/components/search-text/search-text.component.ts
- lib/content-services/src/lib/search/components/search-widget-container/search-widget-container.component.ts
- lib/content-services/src/lib/search/search-widget.interface.ts
> - [X] Bugfix
Apply an empty value is not resetting the filters
Apply an empty value …
> [ADF-5176] - fixed apply when no value is given

- demo-shell/src/app.config.json
- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/search/components/search-header/search-header.component.html
- lib/content-services/src/lib/search/components/search-text/search-text.component.html
> [ADF-5178] - add translation for filters

- docs/core/components/info-drawer-layout.component.md
- docs/core/components/info-drawer.component.md
- lib/core/info-drawer/info-drawer-layout.component.html
- lib/core/info-drawer/info-drawer-layout.component.ts
- lib/core/info-drawer/info-drawer.component.html
- lib/core/info-drawer/info-drawer.component.spec.ts
- lib/core/info-drawer/info-drawer.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3614
**Does this PR …
> [ACA-3614] Add a way to not show info drawer header

- lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.html
- lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.spec.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.html
- lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
> - [ ] Bugfix
Multiple filters can be open at the same time using tab, tab doesn't navigate inside filter.
**What is …
> [ADF-5180] Add keyboard accessibility for filters

- lib/process-services/src/lib/content-widget/attach-file-widget.component.html
- lib/process-services/src/lib/content-widget/attach-folder-widget.component.html
> - [x] Bugfix
No translate pipe on attach file/folder widget titles.
Translate si …
> [ADF-5063] Add translate pipe to attach file/folder widget titles

- lib/content-services/src/lib/search/components/search-header/search-header.component.html
- lib/content-services/src/lib/search/components/search-header/search-header.component.spec.ts
- lib/content-services/src/lib/search/components/search-header/search-header.component.ts
> - [x] Bugfix
Pressing enter in the text input of a filter applies the filter but doesn't close the menu.
**What is …
> [ADF-5177] Pressing enter close filter menu

- lib/content-services/src/lib/search/search-header-query-builder.service.ts
> - [x] Bugfix
The clear button could remove other filters than the current filter when the current filter isn't …
> [ADF-5175] Fix clear button removing multiple filter

- lib/testing/src/lib/core/pages/form/form-fields.ts
- lib/testing/src/lib/process-services/actions/public-api.ts
- lib/testing/src/lib/process-services/actions/task.util.ts
> [ACA-3184][ACA-3185] Create Task Util class

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
> - [x] Bugfix
The Card View Textitem sends an update event only on blur or when enter is pressed. …
> [ACA-3499] Card View Textitem update on change

- e2e/process-services-cloud/task-form-cloud-component-tab.e2e.ts
- e2e/process-services-cloud/task-form-cloud-component.e2e.ts
- e2e/protractor.conf.js
- scripts/travis/e2e/content-services-e2e.sh
- scripts/travis/e2e/core-e2e.sh
- scripts/travis/e2e/process-services-cloud-e2e.sh
- scripts/travis/e2e/process-services-e2e.sh
- scripts/travis/e2e/search-e2e.sh
> - [ ] Bugfix
automated C315180, C310200 and C313200
https://issues.alfresco.com/jira/browse/AAE-1960
**What is …
> [ADF-1960] automated C315180, C310200 and C313200

- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/src/lib/content-metadata/services/content-metadata.service.ts
- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.spec.ts
- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
- lib/content-services/src/lib/document-list/services/document-list.service.ts
- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.html
- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
- lib/core/card-view/interfaces/card-view-item-properties.interface.ts
- package-lock.json
- package.json
> - [ ] Bugfix
[ADF-3484](https://issues.alfresco.com/jira/browse/ADF-3484)
**Does …
> [ADF-3484] - Metadata drop-down list option for properties constrained by a list of values

- .travis.yml
- docs/core/services/sites.service.md
- lib/core/pipes/user-initial.pipe.ts
- lib/core/services/sites.service.ts
- lib/testing/src/lib/content-services/pages/document-list.page.ts
- lib/testing/src/lib/core/pages/data-table-component.page.ts
- package-lock.json
- package.json
- scripts/travis/unit-test/content.sh
- scripts/travis/unit-test/core-extension.sh
- scripts/travis/unit-test/process-cloud.sh
- scripts/travis/unit-test/process.sh
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3492
Expose site groups …
> [ACA-3492] ADF - Expose new Groups Endpoints

- e2e/process-services-cloud/edit-process-filters-component.e2e.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3678
**Does this PR …
> [ACA-3678] Disable save & delete buttons for default process filters

- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
> - [ ] Bugfix
Folder and files are ordered
By default folders are on top and files …
> Put folder on top by default

- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component-data.interface.ts
> [AAE-3115] Make selectionMode optioanl in ContentNodeSelectorComponentData

- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
> - [x] Bugfix
[ADF-5204](https://issues.alfresco.com/jira/browse/ADF-5204)
**Does …
> [ADF-5204] Metadata - Error message still appears after exiting Edit form

- lib/content-services/src/lib/dialogs/folder.dialog.html
- lib/content-services/src/lib/dialogs/folder.dialog.spec.ts
- lib/content-services/src/lib/dialogs/folder.dialog.ts
- lib/core/i18n/en.json
> - [x] Bugfix
[ACA-3745](https://issues.alfresco.com/jira/browse/ACA-3745)
**Does …
> [ACA-3745] Folder - update metadata default copies the name in the title field

- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
Currently in ADF & ACA, when viewing a previous version, in the viewer on top the title of the node's …
> [ADF-5209] When viewing a previous version, the title is not displayed correctly.

- lib/content-services/src/lib/upload/directives/file-draggable.directive.spec.ts
- lib/content-services/src/lib/upload/directives/file-draggable.directive.ts
> - [x] Bugfix
fixes #5740 explicitly set drop effect …
> fix drop effect

- e2e/process-services-cloud/edit-task-filters-component.e2e.ts
* Add createNewCustomFilter() method in edit-task-filters-component.e2e.ts
> - [ ] Bugfix
> - [x] Other... Please describe: E2E test for Delete, Save and Save as actions that should be displayed and enabled when clicking on …
> [ACA-3731] E2E test to validate Save, Save as and Delete buttons availability on custom filters

- lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
> - [x] Bugfix
if the component is used multiple times, the non-unique "ID" clashes at runtime …
> remove unused ID and fix the duplicate warning

- lib/core/form/components/widgets/core/form-outcome.model.spec.ts
- lib/core/form/components/widgets/core/form-outcome.model.ts
- lib/core/form/components/widgets/core/tab.model.spec.ts
- lib/core/form/services/widget-visibility-cloud.service.spec.ts
- lib/core/form/services/widget-visibility.service.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-612
Visibility Conditions are not evaluated on Form …
> [AAE-612] Support for Form Outcome Visibility Conditions

- e2e/process-services-cloud/edit-process-filters-component.e2e.ts
* Add createNewProcessCustomFilter() method in edit-process-filters-component.e2e.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Delete Save and Save as actions should be displayed and enabled when clicking on custom filter …
> [ACA-3795] E2E test to validate Delete Save and Save as actions should be displayed and enabled when clicking on custom filter header

- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
> - [x] Bugfix
Order by cm type makes Sites that is type cm:sites always on the top …
> [ADF-5210] Order by folder on default

- lib/core/form/components/widgets/amount/amount.widget.html
- lib/core/form/components/widgets/checkbox/checkbox.widget.html
- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/components/widgets/date-time/date-time.widget.html
- lib/core/form/components/widgets/display-text/display-text.widget.html
- lib/core/form/components/widgets/hyperlink/hyperlink.widget.html
- lib/core/form/components/widgets/multiline-text/multiline-text.widget.html
- lib/core/form/components/widgets/number/number.widget.html
- lib/core/form/components/widgets/people/people.widget.html
- lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.html
- lib/core/form/components/widgets/text/text.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/upload-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3203
The Form Cloud Fields …
> [AAE-3203] Add tooltip to Form Cloud Widgets

- e2e/protractor.excludes.json
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3200
**Does this PR …
> [AAE-3200] Attach button of content node selector becomes enabled when selecting a folder

- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
* Added unit tests
> - [ ] Bugfix
> - [x] Other... Please describe: Unit tests added …
> [ACA-3678] Disable Save and Delete Button for Default Filters

- e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
- e2e/process-services-cloud/start-task-form-cloud.e2e.ts
- e2e/protractor.excludes.json
- lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
- lib/testing/src/lib/core/pages/info-drawer.page.ts
- lib/testing/src/lib/process-services-cloud/pages/form/widget/attach-file-widget-cloud.page.ts
> [AAE-3209]Fix e2e about attach file from local

- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3804
**Does this PR …
> [ACA-3804] Add All option in process definition name filter dropdown

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3219
The generateProcessInstance() is called before the …
> [AAE-3219] Start process button is disabled when page is first displayed

- lib/core/mock/identity-group.service.mock.ts
- lib/core/services/identity-group.service.spec.ts
- lib/core/services/identity-group.service.ts
- lib/core/services/identity-user.service.ts
- lib/core/services/oauth2.service.ts
> - [ ] Bugfix
- introduce new `OAuth2Service` that unifies and simplifies custom api …
> [AAE-2718] List available roles for a group

- demo-shell/src/app/components/files/filtered-search.component.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/core/datatable/components/datatable/datatable.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.ts
> - [X] Bugfix
Column key is used on sorting for process and now that the value has been changed into the sorting key …
> Readded column key as key parameter

- e2e/process-services-cloud/process-task-attach-content-file-cloud.e2e.ts
> Fix process-task-attach-content-file-cloud.e2e.ts afterAll

- lib/core/form/components/widgets/core/form-field-metadata.ts
- lib/core/form/services/form.service.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
- lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
- lib/process-services-cloud/src/lib/i18n/en.json
> - [ ] Bugfix
There is no way to refresh the form values based on the value of another component …
> [AAE-3084] Add retrieve metadata option in upload widget

- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/document-list/services/custom-resources.service.spec.ts
- lib/content-services/src/lib/document-list/services/custom-resources.service.ts
- lib/core/services/ecm-user.service.spec.ts
- lib/core/services/ecm-user.service.ts
- lib/testing/src/lib/core/actions/identity/identity.service.ts
> - [ ] Bugfix
use People Api instead of legacy one
update custom resources service to …
> use people api and new js api where possible

- e2e/protractor.excludes.json
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
- lib/process-services-cloud/src/lib/form/models/form-cloud-representation.model.ts
- lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3204
**Does this PR …
> [AAE-3204] 'Invalid destination folder path' displayed when clicking on attach file widget of type alfresco & local when destination folder is empty.

- lib/core/form/components/widgets/core/form-field.model.spec.ts
- lib/core/form/components/widgets/core/form-field.model.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5165
Checkbox widgets were all checked when the task was …
> [ADF-5165] [Regression] Fix Checkbok widget in completed tasks

- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
- lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
> - [X] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3204
The id needs to be …
> [AAE-3204] Fix destinationFolder breadcrumb restriction not working

- lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.ts
> - [ ] Bugfix
not possible to easily style from the outside apps
allow styling from …
> allow styling cloud header from the outside

- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.spec.ts
- lib/core/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
- lib/core/card-view/interfaces/card-view-selectitem-properties.interface.ts
> - [ ] Bugfix
Select box can use numbers as value in the card view
**Does this PR …
> Select box can use numbers as value in the card view

- lib/content-services/package.json
- lib/process-services-cloud/package.json
> - [x] Bugfix
fix typo in the version of flex-layout dependency
fixes #6039 
**Does …
> fix flex-layout version

- lib/core/form/components/widgets/core/form.model.spec.ts
- lib/core/form/components/widgets/core/form.model.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
- lib/process-services-cloud/src/lib/form/mocks/cloud-form.mock.ts
> - [X] Bugfix
When the empty value for a dropdown is selected, the retrieve metadata functionality does not populate …
> [AAE-3273] Manage empty option in retrieve content metadata dropdowns

- lib/testing/src/lib/core/pages/data-table/data-table-item.ts
- lib/testing/src/lib/core/pages/form/widgets/attach-file-widget.page.ts
- lib/testing/src/lib/process-services/pages/start-process.page.ts
> [ACA-3441] Add method to attach file widget PO

- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.html
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.scss
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
- lib/process-services-cloud/src/lib/common/process-common.module.ts
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
- lib/process-services-cloud/src/lib/process/process-filters/process-filters-cloud.module.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5230
**Does this PR …
> [ADF-5230] - Implement process date range filter

- lib/core/viewer/components/img-viewer.component.html
- lib/core/viewer/components/img-viewer.component.ts
- lib/core/viewer/components/media-player.component.html
- lib/core/viewer/components/media-player.component.ts
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-4481
If you were to upload …
> [ADF-4481] Fix Viewer peview for unsupported new versions

- lib/core/form/components/widgets/amount/amount.widget.spec.ts
- lib/core/form/components/widgets/checkbox/checkbox.widget.spec.ts
- lib/core/form/components/widgets/date-time/date-time.widget.spec.ts
- lib/core/form/components/widgets/hyperlink/hyperlink.widget.spec.ts
- lib/core/form/components/widgets/people/people.widget.spec.ts
- lib/core/form/components/widgets/radio-buttons/radio-buttons.widget.spec.ts
- lib/core/form/components/widgets/text/text.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
> - [ ] Bugfix
Missing tests
https://issues.alfresco.com/jira/browse/AAE-3296
Unit …
> [AAE-3296] Add unit tests for Tooltips in Form Widgets

- lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3942
**Does this PR …
> [ACA-3942] Enable assignee edit button only when userTask shared among the candidates

- e2e/core/infinite-scrolling.e2e.ts
- e2e/core/pages/content-services.page.ts
- e2e/core/pagination-empty-current-page.e2e.ts
- e2e/process-services/attach-file-content-service.e2e.ts
- e2e/protractor.conf.js
- e2e/protractor.excludes.json
- lib/testing/src/lib/content-services/dialog/content-node-selector-dialog.page.ts
- lib/testing/src/lib/core/pages/data-table-component.page.ts
- lib/testing/src/lib/core/pages/pagination.page.ts
> include attach file test

- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
It allows you to define a more dynamic path as destination folder such as
-root-/-appname-/folder
and at runtime it would be replaced with 
-root-/myapp/folder
> - [ ] Bugfix
**What is the …
> [ACA-3884]Attach cloud file - Ability to use the -appname- as placeholder in the destinationFolder 

- lib/cli/scripts/kubectl-image.ts
… case of missing container for a label
> - [ ] Bugfix …
> [ACA-3973] K8s image - fetch all the namespaces and handle the missing container

- lib/core/i18n/en.json
- lib/core/viewer/components/pdf-viewer-thumb.component.html
- lib/core/viewer/components/pdf-viewer-thumb.component.spec.ts
- lib/core/viewer/components/pdf-viewer-thumb.component.ts
- lib/core/viewer/components/pdf-viewer-thumbnails.component.html
- lib/core/viewer/components/pdf-viewer-thumbnails.component.scss
- lib/core/viewer/components/pdf-viewer-thumbnails.component.spec.ts
- lib/core/viewer/components/pdf-viewer-thumbnails.component.ts
- lib/core/viewer/components/pdf-viewer.component.html
- lib/core/viewer/components/pdf-viewer.component.ts
> - [x] Bugfix
[ACA-3899](https://issues.alfresco.com/jira/browse/ACA-3899)
**Does …
> [ACA-3899] Viewer thumbnails cannot be accessed by keyboard

- lib/core/card-view/card-view.module.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3499
The Card View Text Item input required to click …
> [ADF-3499] Make Card View Text Item reactive to user input

- demo-shell/src/app.config.json
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.html
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.ts
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.html
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
- scripts/lint.sh
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3692
**Does this PR …
> [ACA-3692] - Add completed date/due date/started date filter

- docs/process-services-cloud/services/task-cloud.service.md
- lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3977
**Does this PR …
> [ACA-3977] FE - Integrate new user assign API

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
- lib/process-services-cloud/src/lib/task/task-filters/task-filters-cloud.module.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3627
**Does this PR …
> [ACA-3643] - add completedBy filter on tasks

- lib/testing/src/lib/process-services/actions/public-api.ts
- lib/testing/src/lib/process-services/actions/user-filters.util.ts
- lib/testing/src/lib/process-services/pages/filters.page.ts
- lib/testing/src/lib/process-services/pages/process-filters.page.ts
- lib/testing/src/lib/process-services/pages/process-list.page.ts
- lib/testing/src/lib/process-services/pages/task-filters.page.ts
> - [ ] Bugfix
- Add user-filter.util class that corresponds to [user-filters : Retrieve and manage user filters](http://adwdev.envalfresco.com/activiti-app/api-explorer.html#/user-filters) …
> [ACA-3312] Add user-filter util class

- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
> [AAE-3410] NodeSelector - Use user alias (-my-) name as default for upload of type Alfresco Content only

- lib/testing/src/lib/core/pages/data-table-component.page.ts
The e2es in the ADF apps are broken.
> Fix broken e2e tests because of the lack of thrown error

- e2e/core/viewer/viewer-content-services-component.e2e.ts
> - [ ] Bugfix
e2e test automation
https://issues.alfresco.com/jira/browse/ADF-4481 …
> [ADF-4481] e2e test for uploading an unsupported file

- demo-shell/src/app/components/cloud/service-task-list-cloud-demo.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/models/filter-cloud-model.ts
- lib/process-services-cloud/src/lib/task/task-list/models/service-task-cloud.model.ts
- lib/process-services-cloud/src/lib/task/task-list/public-api.ts
- lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
> - [ ] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3694
This PR adds a new …
> [AAE-3694] Add new Service Method for service task integration

- docs/content-services/components/content-node-selector-panel.component.md
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
- lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/AAE-3410
**Does this PR …
> [AAE-3410] Restrict breadcrumb if upload widget type set to Alfresco Content

- lib/core/i18n/ar.json
- lib/core/i18n/cs.json
- lib/core/i18n/da.json
- lib/core/i18n/de.json
- lib/core/i18n/en.json
- lib/core/i18n/es.json
- lib/core/i18n/fi.json
- lib/core/i18n/fr.json
- lib/core/i18n/it.json
- lib/core/i18n/ja.json
- lib/core/i18n/nb.json
- lib/core/i18n/nl.json
- lib/core/i18n/pl.json
- lib/core/i18n/pt-BR.json
- lib/core/i18n/ru.json
- lib/core/i18n/sv.json
- lib/core/i18n/zh-CN.json
> - [x] Bugfix
- fix error message …
> fix error message for CSRF

- lib/testing/src/lib/core/actions/users.actions.ts
> - [ ] Bugfix
Default login with admin if not to create user e2e
**Does this PR …
> Default login with admin if not to create user e2e

- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
> - [x] Bugfix
[ADF-5279](https://issues.alfresco.com/jira/browse/ADF-5279)
**Does …
> [ADF-5279] Date range type filter selection triggers list reload

- lib/testing/src/lib/process-services/pages/process-list.page.ts
- lib/testing/src/lib/process-services/pages/task-list.page.ts
> - [ ] Bugfix
Add waitTillContentLoaded() step in check Content Is (Not) Displayed By …
> [ACA-4049] Improve check for content on lists

- lib/process-services/src/lib/content-widget/attach-file-widget-dialog-component.interface.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.spec.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.component.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.spec.ts
- lib/process-services/src/lib/content-widget/attach-file-widget-dialog.service.ts
- lib/process-services/src/lib/content-widget/attach-file-widget.component.spec.ts
- lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ADF-5170
done
**Does this PR …
> [ADF-5170] [upload] not able to upload file/folder from external content service specfic path

- lib/testing/src/lib/process-services/actions/process.util.ts
> [ACA-4057]Create process with random name

- lib/core/directives/version-compatibility.directive.ts
- lib/core/services/version-compatibility.service.spec.ts
- lib/core/services/version-compatibility.service.ts
> - [x] Bugfix
https://issues.alfresco.com/jira/browse/ACA-3870
In slow internet …
> [ACA-3870] Fix Version Compatibility Initialization

- docs/content-services/components/content-node-selector-panel.component.md
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- lib/content-services/src/lib/i18n/en.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-3966 …
> [AAE-3966] FE - Disable the upload button when the user doesn't have permissions in a folder

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/mock/search-query.mock.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACA-4099
The * has been added in …
> [ACA-4099] Fix search query in content node selector

- demo-shell/src/app.config.json
- e2e/search/search-filters.e2e.ts
- lib/content-services/src/lib/mock/search-filter-mock.ts
- lib/content-services/src/lib/search/components/search-filter/search-filter.component.spec.ts
- lib/content-services/src/lib/search/components/search-filter/search-filter.component.ts
> - [ ] Bugfix
This PR improve the search filter component by hiding facets without filter category.
All configured …
> Improve search filter component: hide a facet if there is no filter category

- lib/testing/src/lib/process-services/actions/process.util.ts
**Please check if the PR fulfils these requirements**
> - [ ] Bugfix
> - [ …
> [ACA-4057] Edit getProcessInstanceByName method to search the process instance directly by its name

- demo-shell/proxy.conf.js
> - [x] Bugfix
add the missing call to load env file in the proxy
**Does this PR …
> add missing env variables for proxy file

- e2e/process-services/widgets/amount-widget.e2e.ts
- lib/core/form/components/widgets/amount/amount.widget.html
- lib/core/form/components/widgets/amount/amount.widget.scss
- lib/core/form/components/widgets/amount/amount.widget.spec.ts
- lib/testing/src/lib/core/pages/form/widgets/amount-widget.page.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5223
This widget wasn't …
> [ADF-5223] Fix Amount widget styling

- e2e/process-services/pages/attachment-list.page.ts
- e2e/process-services/process-attachment-list-action-menu.e2e.ts
- e2e/process-services/standalone-task.e2e.ts
- lib/testing/src/lib/core/pages/data-table-component.page.ts
- lib/testing/src/lib/core/utils/browser-actions.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Extend e2e testing framework …
> [ACA-3373] Add e2e multi item select method in DataTable component

- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.spec.ts
- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/MNT-21920
When an integer text …
> [MNT-21920] Fix Card View Integers initialization when they are set to 0

- docs/content-services/components/version-upload.component.md
- lib/content-services/src/lib/version-manager/version-upload.component.html
- lib/content-services/src/lib/version-manager/version-upload.component.ts
- lib/core/form/models/task-process-variable.model.ts
- lib/process-services-cloud/src/lib/form/models/task-variable-cloud.model.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-721
We can use the component …
> [ACS-721] Improve End/Cancel Editing UX (part 1) - implement single menu option & dialog

- demo-shell/src/app/components/error/demo-error.component.html
- e2e/content-services/permissions/permissions-component.e2e.ts
- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
- lib/core/i18n/en.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4124
ADF's Add Permission …
> [ACA-4124] Change name displayed for groups in Add Permission Panel Component

- lib/testing/src/lib/core/utils/browser-actions.ts
> Fix clickUntilIsNotVisible by removing one return

- lib/extensions/src/lib/config/extension.config.ts
- lib/extensions/src/lib/config/schema/plugin-extension.schema.json
- lib/extensions/src/lib/services/extension-loader.service.spec.ts
- lib/extensions/src/lib/services/extension-loader.service.ts
- lib/extensions/src/lib/services/extension.service.ts
> - [ ] Bugfix
[ADF-5284](https://alfresco.atlassian.net/browse/ADF-5284)
**Does this …
> [ADF-5284] Restore original plugin functionality

- .travis.yml
- e2e/core/infinite-scrolling.e2e.ts
- scripts/ci/check-env/check-cs-env.sh
- scripts/ci/check-env/check-ps-cloud-env.sh
- scripts/ci/check-env/check-ps-env.sh
- scripts/travis/e2e/content-services-e2e.sh
- scripts/travis/e2e/core-e2e.sh
- scripts/travis/e2e/process-services-cloud-e2e.sh
- scripts/travis/e2e/process-services-e2e.sh
- scripts/travis/e2e/search-e2e.sh
> - [ x] Tests for the changes have been added (for bug fixes / features)
> - [x ] Docs have been added / updated (for bug fixes / features)
> - [ ] Bugfix
> - [x ] Build related changes
Improve env check …
> Improve env check

- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4124
For groups it should …
> [ACA-4124] Display authorityName when authorityDisplayName is missing

- lib/process-services/src/lib/process-list/services/process-filter.service.spec.ts
- lib/process-services/src/lib/process-list/services/process-filter.service.ts
- lib/process-services/src/lib/task-list/services/task-filter.service.spec.ts
- lib/process-services/src/lib/task-list/services/task-filter.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-4127
Returns API response …
> [AAE-4127] [process-services] [APS1] Return Create Filters API response instead of the default payload

- lib/content-services/src/lib/document-list/components/document-list.component.ts
> - [x] Bugfix
It's not possible reset the pagination of DL from outside and sometimes this is needed (navigation …
> [ACA-4168] - changed to public reset pagination

- lib/core/form/components/widgets/container/container.widget.spec.ts
- lib/core/form/components/widgets/container/container.widget.ts
> [AAE-1379] - fixed form rapresentation

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-4090 …
> [AAE-4090] [ADW - Cloud] Warning message is displayed for one second in destination picker when Upload button is enabled

- demo-shell/src/app/components/files/files.component.html
- demo-shell/src/app/components/files/files.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5297
Success snackbar …
> [ADF-5297] Success Snackbar messages showning as errors

- lib/cli/README.md
- lib/cli/scripts/scan-env.ts
> ACA-4171 to ACA-4174 Display the number of activated and deactivated users

- lib/core/services/auth-guard.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5295
Supposing you have two …
> [ADF-5295] Fix Session not reloaded after User logs in in other tab

- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- lib/content-services/tsconfig.lib.json
- lib/core/viewer/components/viewer.component.ts
> - [x] Bugfix
- prevent Escape click bubble up to the Viewer component
- should fix …
> [ACA-2176] prevent Esc click event bubble into the Viewer

- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [X] Bugfix
Uploading as new version a file with the same name, the browser cache prevents the user to see the …
> [ACA-4202] - caching with version number for the url

- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
> - [x] Bugfix
- do not force data reload on sorting change, when the mode is "client" …
> [ACA-4205] reload on sorting only for server mode

- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4208 …
> [ACA-4208] - fix date filter by range

- lib/cli/scripts/scan-env.ts
> - [ ] Bugfix
The environment scan shows only number of activated and deactivated users. …
> ACA-4175 Show number of user's home folders during environment scan

- docs/core/components/sidenav-layout.component.md
- docs/core/directives/highlight.directive.md
- docs/core/services/content.service.md
- docs/core/services/highlight-transform.service.md
- docs/core/services/sites.service.md
- docs/core/services/thumbnail.service.md
- docs/process-services/components/process-attachment-list.component.md
> - [ ] Bugfix
ADF docs would not publish to the Builder Network due to escaped characters. …
> Remove escaped characters to fix ABN publish

- lib/cli/scripts/scan-env.ts
> - [ ] Bugfix
Environment scan will only show the number of active, deactivated users and home folders.
**What is …
> ACA-4176 & ACA-4177 Show number of groups, sites and files during environment scan

- lib/core/form/components/form-renderer.component.spec.ts
- lib/core/form/components/mock/form-renderer.component.mock.ts
> - [ ] Bugfix
Unit tests
https://alfresco.atlassian.net/browse/ADF-5014
Unit tests …
> [ADF-5014] unit tests are added for using date fields as visibility conditions

- lib/cli/scripts/scan-env.ts
> - [ ] Bugfix
Simple view of the data of the scan showing `label : value`.
Better …
> [ACA-4231] Added a table format to the scan-env command

- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-3467 …
> [AAE-3467] - Fix Uploaded files are not being attached after selecting more files

- lib/testing/src/lib/process-services-cloud/actions/project.ts
> - [ ] Bugfix
AAE-4364
Ability to delete release …
> [AAE-4364] Add delete release api call

- lib/testing/src/lib/process-services-cloud/actions/application.ts
- lib/testing/src/lib/process-services-cloud/actions/descriptor.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Retry api calls for e2e tests …
> [AAE-4295] E2E - Add retry api calls for delete descriptor and application

- e2e/content-services/directives/create-library-directive.e2e.ts
- e2e/content-services/lock-file.e2e.ts
- e2e/content-services/pages/lock-file.page.ts
- e2e/content-services/pages/permissions.page.ts
- e2e/content-services/pages/tag.page.ts
- e2e/content-services/permissions/permissions-component.e2e.ts
- e2e/content-services/permissions/site-permissions.e2e.ts
- e2e/content-services/tag-component.e2e.ts
- e2e/content-services/upload/upload-dialog.e2e.ts
- e2e/content-services/version/version-actions.e2e.ts
- e2e/content-services/version/version-permissions.e2e.ts
- e2e/content-services/version/version-properties.e2e.ts
- e2e/content-services/version/version-smoke-tests.e2e.ts
- e2e/core/pages/content-services.page.ts
- e2e/core/pages/dialog/create-library-dialog.page.ts
- e2e/core/pages/version-manager.page.ts
- e2e/core/viewer/viewer-content-services-component.e2e.ts
- e2e/core/viewer/viewer-custom-toolbar-info-drawer.e2e.ts
- e2e/process-services-cloud/pages/tasks-cloud-demo.page.ts
- e2e/process-services/empty-process-list-component.e2e.ts
- e2e/process-services/form-people-widget.e2e.ts
- e2e/process-services/pages/process-details.page.ts
- e2e/process-services/process-attachment-list-action-menu.e2e.ts
- e2e/process-services/process-filters-component.e2e.ts
- e2e/process-services/start-process-component.e2e.ts
- e2e/process-services/stencil.e2e.ts
- e2e/process-services/task-assignee.e2e.ts
- lib/content-services/src/lib/upload/components/upload-version-button.component.ts
- lib/testing/src/lib/core/public-api.ts
- lib/testing/src/lib/core/test-element.ts
> - [ ] Bugfix
Right now, we have a lot of code duplication in e2e page classes to perform same primitive operations …
> TestElement prototype to greatly reduce e2e coding time

- lib/testing/src/lib/process-services-cloud/pages/process-list-cloud-component.page.ts
* Add new method in process-list-cloud-component.page.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Add process definition name filter …
> [ACA-4223] Add process definition name filter

- lib/core/form/components/widgets/core/form.model.spec.ts
- lib/core/form/components/widgets/core/form.model.ts
- lib/process-services-cloud/src/lib/form/models/task-variable-cloud.model.ts
- lib/process-services-cloud/src/lib/form/services/form-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/MNT-22063
**Does this PR …
> [MNT-22051] - Fix form field mapping when value is zero

- lib/cli/package-lock.json
- lib/cli/package.json
- lib/cli/scripts/init-acs-env.ts
- lib/cli/scripts/resources.ts
- package-lock.json
- package.json
> [ADF-5324] - Expose a new adf-cli command to initialise acs-env

- lib/core/blank-page/blank-page.component.ts
- lib/core/blank-page/index.ts
- lib/core/blank-page/public-api.ts
- lib/core/index.ts
> - [ ] Bugfix
Blank page component previously available on certain other apps (such …
> [AAE-4384] Add blank page component

- lib/core/form/components/widgets/container/container.widget.scss
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.scss
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/MNT-22063
**Does this PR …
> [MNT-22063] - fix form cloud layout

- lib/core/login/components/login.component.spec.ts
- lib/core/login/components/login.component.ts
> Do redirect before implicit button

- e2e/content-services/directives/restore-content-directive.e2e.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-4430
When the tab is disabled …
> [AAE-4430] Upload from local tab visibility with info icon error message

- lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5328 …
> [ADF-5328] - fix replacing priority values error

- docs/content-services/components/breadcrumb.component.md
- docs/content-services/components/dropdown-breadcrumb.component.md
- lib/content-services/src/lib/breadcrumb/breadcrumb.component.html
- lib/content-services/src/lib/breadcrumb/breadcrumb.component.spec.ts
- lib/content-services/src/lib/breadcrumb/breadcrumb.component.ts
- lib/content-services/src/lib/breadcrumb/dropdown-breadcrumb.component.html
> - [ ] Bugfix
Given a readOnly property set to true, the breadcrumb and …
> [AAE-4569] Added readOnly property to breadcrumb components

- docs/core/components/login.component.md
- e2e/process-services/attach-file-content-service.e2e.ts
- lib/core/login/components/login.component.spec.ts
- lib/core/login/components/login.component.ts
- lib/testing/src/lib/core/actions/api.service.ts
- lib/testing/src/lib/process-services/pages/external-node-selector-dialog.page.ts
> [ADF-5332] Login basic auth - Ability to override the successRoute from app.config.json

- lib/process-services-cloud/ng-package.json
- lib/process-services-cloud/package.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ADF-5341
At the moment, Apollo is …
> [ADF-5341] Add Apollo direct dependencies

- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
> - [x] Bugfix
Each tab has a different content height meaning that switching between them visibly changes the height …
> [AAE-4637] Fix varying height of dialog when clicking on the Upload from your device tab

- lib/process-services/src/lib/form/start-form.component.mock.ts
- lib/process-services/src/lib/form/start-form.component.spec.ts
- lib/process-services/src/lib/form/start-form.component.ts
- lib/process-services/src/lib/process-list/components/start-process.component.html
- lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process.component.ts
> [ACA-3881] Able to start form with preselected ACS nodes

- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
[ADF-5346](https://alfresco.atlassian.net/browse/ADF-5346)
**Does this …
> [ADF-5346] DocumentList - header is not scrollable when the width of the browser is small

- lib/content-services/src/lib/search/components/search-datetime-range/search-datetime-range.component.spec.ts
- lib/content-services/src/lib/search/components/search-datetime-range/search-datetime-range.component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACA-4213
The BE search API …
> [ACA-4213] - Fix search datetime range in different timezones

- lib/content-services/src/lib/aspect-list/aspect-list.service.ts
- lib/content-services/src/lib/content-metadata/services/content-type-property.service.ts
- lib/content-services/src/lib/content-type/content-type.service.spec.ts
- lib/content-services/src/lib/content-type/content-type.service.ts
> [REPO-5552] more filtering capabilities for aspect/type api 

- lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.component.ts
> - [X] Bugfix
Custom aspect are not counted and preselected on the aspect list dialog …
> [ADF-5344] - fixed counter for custom aspects

- e2e/process-services-cloud/task-counters-cloud.e2e.ts
- lib/testing/src/lib/process-services-cloud/pages/task-filters-cloud-component.page.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4299
Fix C593066 e2e test - …
> [ACA-4299] Fix C593066 e2e test - task counter

- lib/core/viewer/components/pdf-viewer.component.ts
> - [x] Bugfix
[ADF-5347](https://alfresco.atlassian.net/browse/ADF-5347)
**Does this …
> [ADF-5347] Viewer - Closing  PDF before all pages are loaded causes errors

- lib/core/viewer/components/media-player.component.html
- lib/core/viewer/components/media-player.component.scss
> - [ ] Bugfix
The subtitles for audio files are displayed under the media controls. For video files, everything is …
> [ATS-873] Fix Subtitles in audio files

- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
> - [x] Bugfix
The "Apply" button in the attach file dialog is always enabled as long as a file is selected, even if …
> [AAE-3543] Attach button enabled only when all files uploaded

- lib/testing/src/lib/core/test-element.ts
* Add new method to TestElement class to be used in ADW e2e tests
> - [ ] Bugfix
> - [x] Other... Please describe: Add getInputValue() in TestElement class
**What is the current behaviour?** (You can also link to an open issue …
> [AAE-4547] Add getInputValue() in TestElement class

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
> - [x] Bugfix
[ADF-5354](https://alfresco.atlassian.net/browse/ADF-5354)
**Does this …
> [ADF-5354] Content node selector is not working properly for read-only folders

- lib/core/form/components/widgets/container/container.widget.scss
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.scss
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.scss
Reverts Alfresco/alfresco-ng2-components#6529
This PR introduces a regression with hidden field, when the mode is set to not have spaces for hidden fields. The form mode can be easily changed to use the grid instead for fixing this whilst we need a better solution for the flexible layout to show complex form correctly
> Revert "[MNT-22063] - fix form cloud layout"

- lib/testing/src/lib/core/pages/form/widgets/display-value-widget.page.ts
- lib/testing/src/lib/process-services-cloud/resources/resources.json
> - [ ] Bugfix
> - [x] Other... Please describe: Moving testing process and task names to adf testing resource file …
> [ACA-4307] Move Process task JSON mapping e2e process and task names to ADF resource file

- lib/testing/src/lib/process-services/actions/user-filters.util.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4096
A testing method to get …
> [ACA-4096] - Add getProcessFilters method in testing for APS - filters util

- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
- lib/process-services-cloud/src/lib/form/mocks/attach-file-cloud-widget.mock.ts
- lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-4697 …
> [AAE-4697] Restrict content node selector breadcrumb when destination folder path is wrong

- e2e/content-services/components/comment-component.e2e.ts
- e2e/content-services/components/lock-file.e2e.ts
- e2e/content-services/components/site-permissions.e2e.ts
- e2e/content-services/components/unshare-file.e2e.ts
- e2e/content-services/directives/create-library-directive.e2e.ts
- e2e/content-services/directives/delete-directive.e2e.ts
- e2e/content-services/document-list/document-list-copy-move-actions.e2e.ts
- e2e/content-services/document-list/document-list-permissions.e2e.ts
- e2e/content-services/metadata/metadata-permissions.e2e.ts
- e2e/content-services/upload/user-permission.e2e.ts
- e2e/content-services/upload/version-permissions.e2e.ts
- e2e/core/viewer/file-extensions/viewer-archive.component.e2e.ts
- e2e/core/viewer/file-extensions/viewer-component.e2e.ts
- e2e/core/viewer/file-extensions/viewer-excel.component.e2e.ts
- e2e/core/viewer/file-extensions/viewer-image.component.e2e.ts
- e2e/core/viewer/file-extensions/viewer-powerpoint.component.e2e.ts
- e2e/core/viewer/file-extensions/viewer-text.component.e2e.ts
- e2e/core/viewer/file-extensions/viewer-word.component.e2e.ts
- e2e/core/viewer/viewer-share-content.ts
- e2e/search/search-multiselect.e2e.ts
- e2e/util/constants.js
> - [x] Bugfix
- fix the e2e
- remove some deprecated uses of the js-api 
**Does this …
> [MNT-22236] update e2e to reflect permission i18n support

- lib/process-services-cloud/src/lib/i18n/en.json
> - [ ] Bugfix
Change labels
https://alfresco.atlassian.net/browse/AAE-4017
**Does …
> [AAE-4017] Change label: attach file retrieve metadata

- lib/content-services/src/lib/content-metadata/services/content-type-property.service.spec.ts
- lib/content-services/src/lib/content-metadata/services/content-type-property.service.ts
> - [X] Bugfix
Content type feature is not working with ACS version 6.2
For previous …
> [MNT-22298] - Added check for ACS version

- lib/process-services-cloud/src/lib/services/notification-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/services/notification-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4370
We should refresh the …
> [ACA-4370] Refresh filter counter on filter click

- lib/extensions/src/lib/config/extension-utils.spec.ts
- lib/extensions/src/lib/config/extension-utils.ts
> - [ ] Bugfix
Introduce a special notation for replacing JSON values on merge, the …
> [AAE-4842] Extensibility: support replacing values on merge

- lib/testing/src/lib/core/utils/string.util.ts
> Update wrong methods

- e2e/protractor.excludes.json
- lib/testing/src/lib/process-services-cloud/actions/process.services.ts
> [AAE-4924]Add method for createProcess with variables

- e2e/process-services-cloud/process/process-custom-filters.e2e.ts
- e2e/process-services-cloud/process/process-filter-results.e2e.ts
- lib/testing/src/lib/core/pages/material/dropdown.page.ts
- lib/testing/src/lib/process-services-cloud/pages/edit-process-filter-cloud-component.page.ts
> [ADF-5374]Fix flaky filters tests

- lib/content-services/src/lib/aspect-list/aspect-list.component.html
- lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.component.ts
> - [X] Bugfix
Aspect with no name set shows empty row
Aspect with no name set will …
> [ADF-5363] - when aspects has no name we will show the id instead

- lib/core/pipes/file-size.pipe.spec.ts
- lib/core/pipes/file-size.pipe.ts
> - [X] Bugfix
Pipe get an empty string whilst used on a template so this makes all the checks fail …
> [ADF-5372] - fixed wrong result pipe

- docs/content-services/directives/node-counter.directive.md
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.module.ts
- lib/content-services/src/lib/directives/content-directive.module.ts
- lib/content-services/src/lib/directives/node-counter.directive.spec.ts
- lib/content-services/src/lib/directives/node-counter.directive.ts
- lib/content-services/src/lib/i18n/en.json
> - [ ] Bugfix
No way to tell exactly how many files are selected without counting them manually. …
> [AAE-4428] Add selected file counter to attach file widget

- lib/core/datatable/components/datatable/datatable.component.scss
Reverts Alfresco/alfresco-ng2-components#6730
ADF data table sticky header affected.
> Revert "[ADF-5346] DocumentList - header is not scrollable when the width of the browser is small"

- lib/core/directives/tooltip-card/tooltip-card.directive.spec.ts
- lib/core/directives/tooltip-card/tooltip-card.directive.ts
> - [ ] Bugfix
If the tooltip card is being displayed and the element to which it is attached is deleted, the card …
> [AAE-4879] Detach tooltip card when directive is destroyed

- docs/core/services/auth-guard-sso-role.service.md
- e2e/protractor.excludes.json
- lib/core/mock/ecm-user.service.mock.ts
- lib/core/services/auth-guard-sso-role.service.spec.ts
- lib/core/services/auth-guard-sso-role.service.ts
- lib/core/services/people-content.service.spec.ts
- lib/core/services/people-content.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-4985
In a new feature, there …
> [AAE-4985] - Make SSO Role Service accept a content admin role that is not part of the JWT token

- lib/content-services/src/lib/permission-manager/services/node-permission.service.spec.ts
- lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
> - [x] Bugfix
If seach service is down we are showing error template
We should be …
> [ACA-4361] should be able to change permission if search service is down

- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
> [ADF-5362] - enabiling properties refresh on ADW/ACA

- e2e/protractor.conf.js
> - [ ] Bugfix
Log demo shell not starting …
> [E2E] Log demo shell not starting

- .travis.yml
> - [ ] Bugfix
Travis Ci only remove e2e on develop merge …
> Travis Ci only remove e2e on develop merge

- docs/content-services/components/document-list.component.md
- docs/core/services/auth-guard-sso-role.service.md
- docs/core/services/process-content.service.md
> - [] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
I'm afraid I don't have an issue ID, just requests passed on to me by Alex Truby from the Alfresco marketing folks that they'd like the ABN builds to work again.
Only documentation updates.
> - [ ] Bugfix
> - [ ] Other... Please …
> Abn content fixes

- e2e/protractor.conf.js
- nx.json
> - [x] Bugfix
> - [] Feature
Fix e2e protractor …
> Fix e2e protractor

- docs/core/services/people-content.service.md
- lib/content-services/src/lib/permission-manager/components/user-name-column/user-name-column.component.ts
- lib/content-services/src/lib/permission-manager/models/member.model.ts
- lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
- lib/core/mock/ecm-user.service.mock.ts
- lib/core/models/comment.model.ts
- lib/core/models/ecm-user.model.ts
- lib/core/services/people-content.service.spec.ts
- lib/core/services/people-content.service.ts
- lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
> [AAE-5021] Add listPeople method to PeopleContentService

- docs/core/services/process-content.service.md
Apologies; this is a follow up to #6957. I somehow managed to miss a couple of instances of the double backslash.
> More documentation syntax fixes

- lib/process-services/src/lib/task-list/components/task-filters.component.spec.ts
- lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4389 …
> [ACA-4389] [APS1] Convert some of process services extension E2E steps to unit-tests

- lib/core/i18n/en.json
- lib/core/viewer/components/img-viewer.component.html
- lib/core/viewer/components/img-viewer.component.spec.ts
- lib/core/viewer/components/img-viewer.component.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ADF-5377
Image-viewer component …
> [ADF-5377] Viewer: Image Crop

- lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.scss
- lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.scss
- lib/core/datatable/components/datatable/datatable.component.spec.ts
> - [ ] Bugfix
Unit test missing for data table custom header …
> [ACA-4407] unit test for data table custom header

- lib/core/form/services/activiti-alfresco.service.ts
> - [x] Bugfix
Update activiti-alfresco.service.ts to make it work with records
**Does …
> [MNT-22418] Update activiti-alfresco.service.ts to make it work with records

- lib/core/viewer/components/pdf-viewer-thumbnails.component.scss
> - [x] Bugfix
[ADF-5400](https://alfresco.atlassian.net/browse/ADF-5400)
**Does this …
> [ADF-5400] PDF viewer - The document page from the thumbnail pane is not highlighted

- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/mocks/attach-file-cloud-widget.mock.ts
- lib/process-services/src/lib/content-widget/attach-file-widget.component.html
- lib/process-services/src/lib/content-widget/attach-file-widget.component.ts
> - [X] Bugfix
Physical record wrongly show actions that can be performed whilst they are just link for physical …
> [MNT-22418] - disabling action for physical records

- lib/core/viewer/components/txt-viewer.component.scss
> - [x] Bugfix
Problems with overflow scroll in some cases
Fixed the issues stated in …
> [MNT-22030] ADW Previewer does not wrap long lines and there are no scroll-bars

- docs/core/services/people-content.service.md
- lib/core/services/people-content.service.spec.ts
- lib/core/services/people-content.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-5208
listPeople function …
> [AAE-5208] Add pagination info to listPeople function in PeopleContentService

- demo-shell/src/app/components/files/files.component.ts
- lib/content-services/src/lib/mock/upload.service.mock.ts
- lib/content-services/src/lib/upload/components/base-upload/upload-base.ts
- lib/content-services/src/lib/upload/components/upload-button.component.spec.ts
- lib/content-services/src/lib/upload/components/upload-drag-area.component.spec.ts
- lib/content-services/src/lib/upload/components/upload-files.event.ts
- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5369
fixed …
> [ADF-5369] HTTP 500 response in adf-upload-button is emitted as a success event

- docs/core/components/datatable.component.md
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts
- lib/core/comments/comments.component.spec.ts
- lib/core/datatable/components/datatable/datatable.component.html
- lib/core/datatable/components/datatable/datatable.component.scss
- lib/core/datatable/components/datatable/datatable.component.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-5362
A new option …
> [AAE-5362] Add option to make actions button visible only on hover

- docs/core/services/people-content.service.md
- lib/core/services/people-content.service.spec.ts
- lib/core/services/people-content.service.ts
Reverts Alfresco/alfresco-ng2-components#7119
> Revert "[AAE-5392] - Add find people api call"

- e2e/process-services-cloud/form-field/people-group-of-people.e2e.ts
- e2e/process-services/widgets/date-time-widget.e2e.ts
- lib/core/form/components/form-base.component.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services/src/lib/form/form.component.spec.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACA-4480
https://alfresco.atlassian.net/browse/ACA-4479
**What …
> [ACA-4479][ACA-4480] - Enable Save button when the form is invalid

- lib/core/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4455 Previous PR caused a scrollbar to show up in a …
> [ACA-4455] Fix horizontal scroller sometimes showing up on datatable

- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACA-4503 …
> [ACA-4503] Fix closing dialogs behind when closing the content selector dialog

- demo-shell/src/app.config.json
- demo-shell/src/app/components/search/search-filter-chips.component.ts
[ADF-5438] 'Clear' and 'Apply' are showed for the new 'Content Size' bubble
[ADF-5437] Content size bubble filter shows a clear button
[ADF-5436] Check list filter shows 'Clear All' when there's already the remove button
> - [ ] Bugfix
> - [ ] …
> [ADF-5438] Demoshell fixes

- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-5458
This PR rolls back …
> [AAE-5458] - Reset filters when the filter input is not defined (rollback code causing regression)

- demo-shell/src/app.config.json
- lib/core/services/authentication.service.spec.ts
- lib/core/services/authentication.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/MNT-22334
fixed
I have tested …
> [MNT-22334] ADW - User information not displayed when Kerberos is in use

- lib/core/templates/empty-content/empty-content.component.html
> - [X] Bugfix
When we login to Admin App, we see the landing page tooltip title as 'APP.LANDING_PAGE.TITLE'
**What …
> [AAE-5163] Landing page title tooltip is displayed correctly

- lib/core/form/components/widgets/core/form-field.model.spec.ts
- lib/core/form/components/widgets/core/form-field.model.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-5727 …
> [AAE-5727] Add 'today' and 'now' as default values for date and datetime widgets

- docs/extensions/components/preview-extension.component.md
- lib/core/viewer/components/viewer.component.html
- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
> - [ ] Bugfix
provide support for `*` wildcards when extending Viewer, allows having …
> [MNT-22613] Viewer wildcard extension

- docs/README.md
- docs/process-services-cloud/widgets/properties-viewer.widget.md
- lib/core/form/components/widgets/core/form.model.ts
- lib/process-services-cloud/src/lib/form/components/cloud-form-rendering.service.ts
- lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer-wrapper/properties-viewer-wrapper.component.html
- lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer-wrapper/properties-viewer-wrapper.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer-wrapper/properties-viewer.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer.widget.scss
- lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer.widget.ts
- lib/process-services-cloud/src/lib/form/form-cloud.module.ts
> - [ ] Bugfix
There is no way of displaying the metadata of the files in an attach widget form. …
> [MNT-22606] Add properties viewer as form widget

- lib/core/form/components/widgets/core/displayable-cm-properties.model.ts
- lib/core/form/components/widgets/core/index.ts
- lib/core/i18n/en.json
- lib/process-services-cloud/karma.conf.js
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.scss
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.html
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.scss
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.ts
- lib/process-services-cloud/src/lib/form/form-cloud.module.ts
- lib/process-services-cloud/src/lib/form/mocks/attach-file-cloud-widget.mock.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
- lib/testing/src/lib/protractor/core/pages/form/widgets/attach-file-widget.page.ts
- lib/testing/src/lib/protractor/process-services-cloud/pages/form/widget/attach-file-widget-cloud.page.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-6165 …
> [AAE-6165] Add capability in the Attach File of displaying metadata fields in addition to file name

- lib/core/layout/components/header/header.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-6346
'adf-toolbar--spacer' …
> [AAE-6346] ADW Header is not aligned to right

- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/mocks/dropdown.mock.ts
> - [ ] Bugfix
Search options for dropdown added
- Search filter will be display if it …
> [AAE-6572] Search capability for dropdowns

- lib/core/card-view/components/card-view-selectitem/select-filter-input/select-filter-input.component.spec.ts
- lib/core/card-view/components/card-view-selectitem/select-filter-input/select-filter-input.component.ts
> - [ ] Bugfix
mat select doesn't comes with unselect/restore old option when multiple option enabled
**What is the …
> [AAE-6623] Search and select multiple dropdown options

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
> - [ ] Bugfix
> - [] Other... Please describe:
When a user changes the process definition name from the dropdown, then it is possible to share the url …
> [AAE-6307] Setting a default process name 

- lib/core/form/components/widgets/amount/amount.widget.html
- lib/core/form/components/widgets/amount/amount.widget.spec.ts
- lib/core/form/components/widgets/date-time/date-time.widget.html
- lib/core/form/components/widgets/date/date.widget.html
- lib/core/form/components/widgets/multiline-text/multiline-text.widget.html
- lib/core/form/components/widgets/number/number.widget.html
- lib/core/form/components/widgets/text/text.widget.html
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-4915 …
> [ADF-4915][Form] FormField: When required is set to true, asterisk apppears in placeholder text

- docs/content-services/components/document-list.component.md
<adf-context-menu-holder> seems to be deprecated. The proposed solution seems to work.
> - [ ] Bugfix
**What is the …
> <adf-context-menu-holder> removed from adf document list

- lib/testing/src/lib/protractor/core/pages/card-view/card-view-text-item.page.ts
> - [ ] Bugfix
This one small change allows us to speed the test execution. In lot of …
> AAE-6757 Improving e2e tests relating to modeling-ee. Part one - improve flaky tests, ProcessModelerComponent

- lib/core/search-text/search-text-input.component.html
- lib/core/search-text/search-text-input.component.ts
> - [ ] Bugfix
update search input text to allow providing hint labels from external …
> [AAE-5715] support hint labels for search input

- e2e/protractor.excludes.json
- lib/process-services-cloud/src/lib/app/models/application-instance.model.ts
> - [ ] Bugfix
The version of the RuntimeBundle is not present as part of the model
RB …
> AAE-6861 - Add runtimeBundleVersion property to the Model

- lib/cli/scripts/init-aae-env.ts
- lib/cli/scripts/resources.ts
> [AAE-7035] Being able to load a dynamic file location

- e2e/protractor.excludes.json
> ADF-5467 re-enable test

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-6310
After navigate to process page with query params for …
> [AAE-6310] Fix for attaching files

- lib/core/form/components/widgets/core/form-field.model.spec.ts
- lib/core/form/components/widgets/core/form-field.model.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-7010 …
> [AAE-7010] - Fix nested linked dropdowns are not reset

- lib/extensions/.eslintrc.json
- lib/extensions/src/lib/components/dynamic-component/dynamic.component.spec.ts
- lib/extensions/src/lib/components/dynamic-component/dynamic.component.ts
- lib/extensions/src/lib/config/action.extensions.ts
- lib/extensions/src/lib/config/extension-utils.spec.ts
- lib/extensions/src/lib/config/extension-utils.ts
- lib/extensions/src/lib/config/sidebar.extensions.ts
- lib/extensions/src/lib/config/viewer.extensions.ts
- lib/extensions/src/lib/evaluators/core.evaluators.spec.ts
- lib/extensions/src/lib/evaluators/core.evaluators.ts
- lib/extensions/src/lib/mock/app-extension.service.mock.ts
- lib/extensions/src/lib/services/app-extension.service.ts
- lib/extensions/src/lib/services/extension-loader.service.ts
- lib/extensions/src/lib/services/extension.service.spec.ts
- lib/extensions/src/lib/services/extension.service.ts
- lib/extensions/src/lib/services/rule.service.ts
- lib/extensions/src/lib/services/startup-extension-factory.ts
> - [ ] Bugfix
- remove workaround rules for eslint
- fix eslint warnings/errors for …
> [AAE-7241] fix eslint warnings for Extensions project

- demo-shell/src/app.config.json
- docs/core/services/upload.service.md
- e2e/protractor.excludes.json
- lib/content-services/src/lib/upload/components/upload-drag-area.component.spec.ts
- lib/core/.eslintrc.json
- lib/core/services/upload.service.spec.ts
- lib/core/services/upload.service.ts
> - [ ] Bugfix
only 1 file is uploaded at a time making the upload process rather long …
> [MNT-22649] Support for concurrent uploads and configurable thread count

- e2e/content-services/upload/upload-dialog.e2e.ts
- e2e/content-services/upload/uploader-component.e2e.ts
- lib/content-services/src/lib/upload/components/file-uploading-dialog.component.html
- lib/content-services/src/lib/upload/components/file-uploading-list-row.component.html
- lib/content-services/src/lib/upload/components/file-uploading-list-row.component.spec.ts
- lib/content-services/src/lib/upload/components/file-uploading-list-row.component.ts
- lib/content-services/src/lib/upload/components/file-uploading-list.component.spec.ts
- lib/content-services/src/lib/upload/components/file-uploading-list.component.ts
- lib/core/datatable/components/datatable-cell/datatable-cell.component.ts
- lib/core/services/upload.service.ts
> - [x] Bugfix
- user successfully uploads 1000 files and then cancels 1 more file -> all 1001 file gets deleted
- …
> [ACA-4557] Upload Dialog fixes and refactoring

- lib/core/form/components/inplace-form-input/inplace-form-input.component.html
- lib/core/form/components/inplace-form-input/inplace-form-input.component.scss
- lib/core/form/components/inplace-form-input/inplace-form-input.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5472
1. Adding placeholder to …
> [ADF-5472] Missing placeholder for inplace input

- lib/core/datatable/data/data-table.schema.ts
- lib/process-services-cloud/src/lib/process-services-cloud.module.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/services/cloud-token.service.ts
- lib/process-services-cloud/src/lib/services/preference-cloud.interface.ts
- lib/process-services-cloud/src/lib/services/user-preference-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/models/tasks-cloud-preferences.ts
- lib/process-services-cloud/src/lib/task/task-list/public-api.ts
- lib/process-services-cloud/src/lib/task/task-list/task-list-cloud.module.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-7819
This is the third part …
> [AAE-7819] Change column order - load and save column order preferences for TASKS, moved preference service to components services - [3/3]

- lib/core/datatable/components/datatable/datatable.component.html
- lib/process-services-cloud/src/lib/process/process-list/process-list-cloud.module.ts
- lib/process-services-cloud/src/lib/task/task-list/task-list-cloud.module.ts
Provide preference services on for tasks/processes on component module level
> - [x] Bugfix
This should allow us to …
> Provide preference services on for tasks/processes on component module level

- lib/core/viewer/components/viewer.component.spec.ts
- lib/core/viewer/components/viewer.component.ts
multiple use in the form of viewer needs multiple instance of ViewUtilService
> - [X] Bugfix
multiple use viewer in …
> [AAE-8565] multiple use viewer in form

- .eslintrc.json
- lib/core/form/components/widgets/widget.component.spec.ts
- package-lock.json
- package.json
> - [ ] Bugfix
We have been able to merge a PR containing `fdescribe` without receiving an error in the pipeline …
> Add eslint ban rule

- lib/core/clipboard/clipboard.service.spec.ts
- lib/core/clipboard/clipboard.service.ts
> - [X] Bugfix
The copy to clipboard functionality is using a deprecated method, that leads the copy/paste shortcuts …
> [AAE-8648] Fix deprecated copy to clipboard api

- lib/core/datatable/public-api.ts
> - [x] Bugfix
After running `scripts/build/build-core.sh` we got error:
`Unsupported private class …
> Added missing top-level export for MainMenuDataTableTemplateDirective

- lib/core/form/components/form-renderer.component.scss
- lib/core/form/components/widgets/core/form-field.model.ts
- lib/core/form/components/widgets/form.theme.scss
- lib/core/form/components/widgets/number/number.widget.html
- lib/core/form/components/widgets/number/number.widget.spec.ts
- lib/core/form/components/widgets/text/text.widget.html
- lib/core/form/components/widgets/text/text.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
> - [ ] Bugfix
Refactor styles
Text, number and dropdown widget accept form compact …
> [AAE-8764] Enable left labels in text, number and dropdown cloud widget

- lib/core/services/people-content.service.spec.ts
- lib/core/services/people-content.service.ts
> - [x] Bugfix
reset the service flags upon logout to force re-caching of the state …
> [AAE-7077] Reset people content service cache on logout

- angular.json
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
- lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
> - [ ] Bugfix
There is no way of retrieving the static inputs for a start event form …
> [AAE-8929] Get start event form static inputs

- lib/process-services/src/lib/content-widget/attach-file-widget.component.html
- lib/process-services/src/lib/content-widget/attach-file-widget.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5272 …
> [ADF-5272] fe files upload form width is increasing if we upload file name too long

- lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-9314
Once user complete task …
> [AAE-9314] Fix preselected user display in completed task

- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.html
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.scss
- lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.spec.ts
> - [ ] Bugfix
Currently when listing files in a form using the ATTACH FILE widget, when a user needs to view the …
> [AAE-9190] - ATTACH FILE: view file content directly by clicking

- lib/process-services-cloud/src/lib/models/data-column-custom-data.ts
- lib/process-services-cloud/src/lib/models/filter-cloud-model.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-list/datatable/process-list-datatable-adapter.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
- lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
- lib/process-services-cloud/src/lib/services/variable-mapper.sevice.spec.ts
- lib/process-services-cloud/src/lib/services/variable-mapper.sevice.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/datatable/task-list-datatable-adapter.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-9461
Using …
> [AAE-9461] Change variable process definition id

- lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.html
- lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.scss
- lib/core/card-view/components/card-view-arrayitem/card-view-arrayitem.component.spec.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-10292
**Does this PR …
> [AAE-10292] Fix opening two dialogs for card view array items

- lib/core/templates/empty-content/empty-content.component.stories.ts
> - [ ] Bugfix
[https://alfresco.atlassian.net/browse/AAE-10202](https://alfresco.atlassian.net/browse/AAE-10202) …
> [AAE-10202] Storybook EmptyContent component

- lib/core/templates/error-content/error-content.component.stories.ts
- lib/core/templates/template.module.ts
> - [ ] Bugfix
Added three stories for ErrorContent Component:
- **Error Code Story** …
> [AAE-10214] Storybook ErrorContent Component

- lib/core/comments/comment-list.component.stories.ts
- lib/core/comments/comments.component.stories.ts
- lib/core/icon/icon.component.stories.ts
- lib/core/info-drawer/info-drawer.component.stories.ts
- lib/core/language-menu/language-menu.component.stories.ts
- lib/core/language-menu/language-picker.component.stories.ts
- lib/core/mock/comment-content-service.mock.ts
- lib/core/mock/comment-content.mock.ts
- lib/core/mock/comment-process-service.mock.ts
- lib/core/mock/comment-process.mock.ts
- lib/core/mock/language.service.mock.ts
- lib/core/services/comment-process.service.interface.ts
- lib/core/services/language.service.interface.ts
- lib/core/services/language.service.ts
- lib/core/templates/empty-content/empty-content.component.stories.ts
- lib/core/templates/error-content/error-content.component.stories.ts
- lib/core/templates/template.module.ts
> - [ ] Bugfix
Some headers had `Copyright 2022 Alfresco Software, Ltd.` in them, which is not the correct year for …
> change wrong licence header dates

- angular.json
- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.html
- lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.scss
- lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/mock/edit-task-filter-cloud.mock.ts
- lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
- scripts/build/build-all-lib.sh
- scripts/build/build-cli.sh
- scripts/build/build-core.sh
- scripts/build/build-testing.sh
> [AAE-9186] Filter tasks by assignee

- lib/core/src/lib/form/components/widgets/display-rich-text/display-rich-text.widget.ts
- lib/core/src/lib/rich-text-editor/editorjs-config.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-10377
Changing the import …
> [AAE-10377] Fix the rich text editor widget is not opening

- .eslintrc.json
- .husky/pre-commit
- lib/cli/.eslintrc.json
- lib/core/src/lib/pagination/pagination.component.spec.ts
- lib/core/src/lib/rich-text-editor/rich-text-editor.component.ts
- lib/testing/.eslintrc.json
- package.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-10474
The lint scripts were not being run because the …
> [AAE-10474] review why xit and console log is allowed to be committed

- lib/core/src/lib/search-text/search-text-input.component.stories.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Storybook stories
[AAE-10454](https://alfresco.atlassian.net/browse/AAE-10454) …
> [AAE-10454] Stories for search-text-input component

- lib/core/src/lib/form/components/form-base.component.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
- lib/process-services/src/lib/form/form.component.spec.ts
> - [X] Bugfix
Currently, when the user clicks on a custom outcome button (like 'Approves', 'Rejected', etc), we …
> AAE-2824: Managed to trigger executeOutcome when clicking on custom outcome buttons

- lib/core/src/lib/form/components/widgets/core/form-field-validator.spec.ts
> - [ ] Bugfix
> - [x] Other... Please describe: adding unit test
The problem appeared where during Form on Task user interaction, the text filed was …
> [AAE-10729] form empty string regex validation unit test

- cspell.json
- demo-shell/src/app/app.module.ts
- lib/cli/package-lock.json
- lib/core/api/alfresco-api/alfresco-api.http-client.spec.ts
- lib/core/api/alfresco-api/alfresco-api.http-client.ts
- lib/core/api/alfresco-api/alfresco-api.param-encoder.spec.ts
- lib/core/api/alfresco-api/alfresco-api.param-encoder.ts
- lib/core/api/alfresco-api/alfresco-api.response-error.ts
- lib/core/api/alfresco-api/alfresco-api.utils.spec.ts
- lib/core/api/alfresco-api/alfresco-api.utils.ts
- lib/core/src/lib/core.module.ts
- lib/core/src/lib/services/auth-bearer.interceptor.ts
- lib/core/src/lib/services/authentication.service.ts
> - [ ] Bugfix
Currently, we use superagent to make all requests inside alfersco/js-api, with prevents us from using …
> [AAE-10499] create angular based custom http client for alfresco js api

- lib/content-services/src/lib/dialogs/folder.dialog.html
> - [x] Bugfix
New folder dialog form fields lacks labels.
Correct labels has been …
> [ACS-3546] Add missing labels to folder dialog

- e2e/test.config.js
- lib/testing/src/lib/protractor/core/models/user.model.ts
> - [ ] Bugfix
Env issues
We have changed the email domain of the users created by the …
> Change email domain for users created by e2e

- e2e/test.config.js
- lib/testing/src/lib/protractor/core/models/user.model.ts
> - [ ] Bugfix
We have changed the email domain of the users created by the e2e tests from adf.com to example.com …
> Change email domain for users created by e2e to example.com

- e2e/test.config.js
- lib/testing/src/lib/protractor/core/models/user.model.ts
> - [ ] Bugfix
change configuration for e2e
We need to change the email that is used to generate users for e2e, it …
> Be able to provide the email domain for test users from an env var

- angular.json
- demo-shell/src/app/app.module.ts
- lib/core/api/alfresco-api/alfresco-api.http-client.ts
- lib/core/auth/README.md
- lib/core/auth/ng-package.json
- lib/core/auth/src/authentication-interceptor/README.md
- lib/core/auth/src/authentication-interceptor/authentication.interceptor.spec.ts
- lib/core/auth/src/authentication-interceptor/authentication.interceptor.ts
- lib/core/auth/src/authentication.ts
- lib/core/auth/src/index.ts
- lib/core/src/lib/core.module.ts
- lib/core/src/lib/services/auth-bearer.interceptor.ts
- lib/core/src/lib/services/authentication.service.ts
- tsconfig.json
> - [x] Bugfix
> - [] Documentation
An `AuthBearerInterceptor` was added to core module with is intercepting all request if not excluded …
> [AAE-10984]: feat: add context to requests and add new auth bear interceptor

- scripts/travis/update/update-project.sh
[PR](https://github.com/Alfresco/alfresco-content-app/pull/2745) can't be merged because it's using the default travis user
Make sure that the correct git author is used in every repository the update-project script is handling …
> Fix git author when updating multiple projects

- .github/actions/travis-event-type-load/action.yml
> - [ ] Bugfix
TRAVIS_EVENT_TYPE env var (used by TRAVIS CI) doesn't have a corresponding item in Github CI.
**What …
> [AAE-11221] - gh action to parse github.event_name into correct TRAVIS_EVENT_TYPE

- lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer.widget.ts
> - [ ] Bugfix
MetaData viewer widget works with only field values of type string. …
> AAE-10842: Modified properties viewer widget to handle file input

- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/new-version-uploader/new-version-uploader.dialog.html
- lib/content-services/src/lib/upload/components/upload-button.component.html
> - [x] Bugfix
New version modal has additional close button https://alfresco.atlassian.net/browse/ACA-4622
**What is …
> [ACA-4622] Remove additional close button, unify buttons style

- docs/content-services/directives/auto-focus.directive.md
- lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.html
- lib/content-services/src/lib/aspect-list/aspect-list.module.ts
- lib/content-services/src/lib/directives/auto-focus.directive.spec.ts
- lib/content-services/src/lib/directives/auto-focus.directive.ts
- lib/content-services/src/lib/directives/content-directive.module.ts
> - [x] Bugfix
Edit aspects dialog has incorrect initial focus.
Auto focus directive …
> [ACS-3701] Add auto focus directive

- lib/testing/src/lib/protractor/process-services/pages/start-process.page.ts
> - [ ] Bugfix
A hardcoded sleep was introduced to overcome a waiting issue.
The sleep …
> [AAE-11275] - e2e protractor - remove sleep step

- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
Content is lost, clipped, or obscured when the page is zoomed to 200%, Content overlaps other …
> [ACS-3731] move/copy dialog and content overlaps other than 320px issue fixed

- lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
- lib/content-services/src/lib/permission-manager/components/pop-over.directive.spec.ts
- lib/content-services/src/lib/permission-manager/components/pop-over.directive.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-3781
User is able now to …
> [ACS-3781] 878751 function cannot be performed by keyboard alone hiding the user groups

- e2e/content-services/components/permissions-component.e2e.ts
- e2e/content-services/components/site-permissions.e2e.ts
- e2e/core/notifications-component.e2e.ts
- e2e/core/pages/notification.page.ts
- lib/testing/src/lib/protractor/core/pages/snackbar.page.ts
> - [ ] Bugfix
The PR is just removing methods that we wrapped in methods with the …
> [AAE-11437] Remove snackbar duplications

- lib/content-services/src/lib/dialogs/dialog.module.ts
- lib/content-services/src/lib/dialogs/folder.dialog.html
- lib/content-services/src/lib/dialogs/library/library.dialog.html
> - [x] Bugfix
There is no focused element after opening modal for library or folder creation.  …
> [ACS-3758] Focus modal first focusable element after opening

- lib/content-services/src/lib/dialogs/folder.dialog.html
- lib/content-services/src/lib/dialogs/folder.dialog.scss
content doesn't reflow to fit the viewport at 400% zoom 
content …
> [ACS-3731] content reflow issue fixed to fit the viewport at 400% zoom sub task ACS-3889

- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/new-version-uploader/new-version-uploader.dialog.html
> - [x] Bugfix
Manage version dialog has missing close button -> https://alfresco.atlassian.net/browse/ACS-4087 …
> [ACS-4087] Restore missing close button for manage version dialog

- docs/content-services/services/new-version-uploader.dialog.service.md
- lib/content-services/src/lib/aspect-list/services/dialog-aspect-list.service.spec.ts
- lib/content-services/src/lib/aspect-list/services/dialog-aspect-list.service.ts
- lib/content-services/src/lib/aspect-list/services/node-aspect.service.spec.ts
- lib/content-services/src/lib/aspect-list/services/node-aspect.service.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.spec.ts
- lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
- lib/core/src/lib/datatable/data/data-row.model.ts
> - [x] Bugfix
Modals which were opened from personal files/libraries list or toolbar or more menu, after closing, …
> [ACS-3757] returning focus to element from which they were opened

- lib/core/src/lib/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5508
The checkmark is fully …
> [ADF-5508] Fix half hidden checkmark icon

- docs/content-services/interfaces/base-card-view-content-update.interface.md
- docs/content-services/services/card-view-content-update.service.md
- docs/core/interfaces/base-card-view-update.interface.md
- docs/core/interfaces/click-notification.interface.md
- docs/core/interfaces/update-notification.interface.md
- docs/core/services/card-view-update.service.md
- docs/upgrade-guide/upgrade50-60.md
- lib/content-services/src/lib/aspect-list/services/node-aspect.service.spec.ts
- lib/content-services/src/lib/aspect-list/services/node-aspect.service.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/content-services/src/lib/interfaces/base-card-view-content-update.interface.ts
- lib/content-services/src/lib/services/card-view-content-update.service.spec.ts
- lib/content-services/src/lib/services/card-view-content-update.service.ts
- lib/content-services/src/lib/services/index.ts
- lib/content-services/src/lib/services/public-api.ts
- lib/content-services/src/public-api.ts
- lib/core/src/lib/breaking-changes.md
- lib/core/src/lib/card-view/components/card-view-item-dispatcher/card-view-item-dispatcher.component.ts
- lib/core/src/lib/card-view/interfaces/base-card-view-update.interface.ts
- lib/core/src/lib/card-view/interfaces/card-view-item-properties.interface.ts
- lib/core/src/lib/card-view/interfaces/card-view.interfaces.ts
- lib/core/src/lib/card-view/interfaces/click-notification.interface.ts
- lib/core/src/lib/card-view/interfaces/update-notification.interface.ts
- lib/core/src/lib/card-view/services/card-view-update.service.spec.ts
- lib/core/src/lib/card-view/services/card-view-update.service.ts
> - [ ] Bugfix
Core `CardViewUpdateService` is coupled with content-services logic. …
> [AAE-10767] Make CardView Reusable

- scripts/test-e2e-lib.sh
> - [ ] Bugfix
> - [x] Other... Please describe: clean-up running e2e script
I think I added that export to the var before and it is unnecessary.
I …
> [AAE-11274] remove unnecessary var export

- lib/core/src/lib/viewer/components/pdf-viewer.component.ts
pdfjs works fine with Japanese characters with this options.
> - [ ] Bugfix
What is the current behaviour? (You can also link to an open issue here)
Browser does not load cmaps files correctly …
> [#7902] Fix to enable cmaps with pdfjs

- lib/cli/scripts/changelog.ts
> - [ ] Bugfix
The git log command does not work anymore with invert grep and we can’t generate the changelog …
> [AAE-11708] Use perl regexp instead of reverse grep in changelog

- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/mock/edit-task-filter-cloud.mock.ts
…ut to check for the processInstanceId changes to set the filter
> - [x] Bugfix …
> [AAE-11992] Fix processInstanceId filter empty

- lib/core/src/lib/clipboard/clipboard.directive.spec.ts
- lib/core/src/lib/clipboard/clipboard.directive.ts
> - [x] Bugfix
There was no way to perform the function using only the keyboard on the same screen or on a qualifying …
> [ACS-4051] Copy to clipboard button is now accessible through the keyboard enter earlier which was only accessible through mouse click

- lib/core/src/lib/clipboard/clipboard.directive.spec.ts
- lib/core/src/lib/clipboard/clipboard.directive.ts
Reverts Alfresco/alfresco-ng2-components#8119
> Revert "[ACS-4051] Copy to clipboard button is now accessible through the keyboard enter earlier which was only accessible through mouse click"

- lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
> - [x] Bugfix
Aria-Label was missing from inherited permissions toggle, so screen readers were not able to link the …
> [ACS-4253] - Added aria-label to form element

- lib/core/src/lib/viewer/components/pdf-viewer.component.html
> - [x] Bugfix
Clicking on showing which is located in pagination of toolbar of pdf, the visible label are not …
> [ACS-4242] Visible label/form field are not associated

- lib/core/src/lib/viewer/components/pdf-viewer.component.html
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-4263
Now screen reader reads …
> [ACS-4263] Add 'aria-pressed' attribute for reset button on content viewer page

- docs/content-services/services/tag.service.md
- lib/content-services/src/lib/tag/services/tag.service.spec.ts
- lib/content-services/src/lib/tag/services/tag.service.ts
> - [ ] Bugfix
Currently in ADF there is no method allowing to update tags. …
> [ACS-4411] updateTag method added to tags service

- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html
…al label for a text field
> - [x] Bugfix
Label is not persistent as placeholder is being used as the only visual …
> [ACS-4307] Label is not persistent as placeholder is being used as the only visual label for a text field

- lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.spec.ts
- lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5514
The active state of the …
> [ADF-5514] Fix red dot still present after filter being cleared

- e2e/protractor.excludes.json
- lib/process-services-cloud/src/lib/form/form-cloud.module.ts
- lib/process-services/src/lib/form/form.module.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-12558
Removed ContentModule …
> [AAE-12558] Fix load content-services translation resources

- lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.html
- lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.ts
> - [x] Bugfix
The button for remove permissions for a folder for a particular user was not working when enter key …
> [ACS-4254] Delete permissions button is now keyboard interact-able

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.scss
> - [x] Bugfix
content overlap issue at 400% zoom and close button is not visible in share dialog …
> [ACS-4322] content overlap issue fixed at 400% zoom and close button which was earlier not visible at 400% zoom is visible now.

- docs/content-services/components/tag-node-list.component.md
- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/tag/tag-node-list.component.html
- lib/content-services/src/lib/tag/tag-node-list.component.scss
- lib/content-services/src/lib/tag/tag-node-list.component.spec.ts
- lib/content-services/src/lib/tag/tag-node-list.component.ts
- lib/extensions/src/lib/components/dynamic-column/dynamic-column.component.ts
> - [ ] Bugfix
All tags are always displayed no matter if they're fit into the container or not. …
> [ACS-4124] Display only as much tags as fits container in tag node list

- lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
- lib/content-services/src/lib/permission-manager/components/pop-over.directive.spec.ts
- lib/content-services/src/lib/permission-manager/components/pop-over.directive.ts
Inherited permissions popover can now be opened and closed by enter key press. Additionally, added configurableFocusTrap to popover when it is opened and resolved focus jumping issue.
> - [x] Bugfix
> - [ ] Other... Please …
> [ACS-4252] Resolved accessibility issues around inherited permissions popover

- .github/actions/e2e/action.yml
- .github/actions/upload-cache-and-artifacts/action.yml
- .github/workflows/git-tag.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
Can be miss configured with different buckets
We need to maintain two variables:
They seems to be used in different ways because one contain s3:// the other not
> - [ ] Bugfix
**What is the …
> [dependabot issue] Use one bucket variable

- lib/testing/src/lib/protractor/core/pages/material/date-picker.page.ts
**Please check if the PR fulfils these requirements**
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-12662
There's no additional …
> [AAE-12662] Get rid of multiplicity of "more than one element found for locator" warnings in tests caused by redundant click 

- scripts/travis/update/update-project.sh
> - [ ] Bugfix
There is no upstream for ADF and JS API for applications repo. …
> [ACS-4634] Add ADF and JS API upstream to applications repo

- .github/workflows/release.yml
> AAE-12721 - when a PR is closed the part of the pipeline is still triggered

- docs/content-services/services/category-tree-datasource.service.md
- docs/content-services/services/category.service.md
- docs/core/services/search.service.md
- lib/content-services/src/lib/category/mock/category-mock.service.ts
- lib/content-services/src/lib/category/services/category-tree-datasource.service.spec.ts
- lib/content-services/src/lib/category/services/category-tree-datasource.service.ts
- lib/content-services/src/lib/category/services/category.service.spec.ts
- lib/content-services/src/lib/category/services/category.service.ts
- lib/content-services/src/lib/tree/components/tree.component.spec.ts
- lib/content-services/src/lib/tree/components/tree.component.ts
- lib/content-services/src/lib/tree/services/tree.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-4565
Added function which …
> [ACS-4565] add search for categories tree in admin cc

- lib/content-services/src/lib/upload/components/file-uploading-dialog.component.scss
… 400% or 320px equivalent which is fixed now
> - [x] Bugfix
Content was overlapping with other contents and some …
> [ACS-4326] Content was overlapping with other contents and some elements were missing when we zoom at 400% or 320px equivalent which is fixed

- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/search/components/search-facet-field/search-facet-field.component.html
> - [x] Bugfix
The button did not have a title or label. Also the button is a clear button but was using close icon. …
> [ACS-4294] Added title to clear button and changed its icon type to clear from close

- docs/content-services/components/tree.component.md
- lib/content-services/src/lib/tree/components/tree.component.html
- lib/content-services/src/lib/tree/components/tree.component.scss
- lib/content-services/src/lib/tree/components/tree.component.spec.ts
- lib/content-services/src/lib/tree/components/tree.component.ts
- lib/content-services/src/lib/tree/models/tree-context-menu-result.interface.ts
- lib/content-services/src/lib/tree/public-api.ts
- lib/content-services/src/lib/tree/tree.module.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-4592
Now we have possibility …
> [ACS-4592] missing right click menu on row and left click is only allow on indicator rotate

- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-12888
Field label is inside …
> [AAE-12888] moved label inside field for easier styling

- lib/core/src/lib/datatable/data-column/data-column.module.ts
- lib/core/src/lib/datatable/datatable.module.ts
- lib/core/tsconfig.lib.json
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-11707
When opening the VS Code, if I open the file …
> [AAE-11707] Fix wrong paths in adf-core

- lib/core/src/lib/api-factories/alfresco-api-v2-loader.service.ts
- lib/core/src/lib/services/alfresco-api.service.ts
> - [x] Bugfix
Impossible to reach the login page of the studio-hxp app because the app tries to connect using the …
> Dev alepore 12511 fix bc wrong auth url

- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
> - [x] Bugfix
If upload file is not selected, the 'create' buttons remains in enabled state. …
> [ACS-4106] changed place of mat-error tag & style change

- demo-shell/src/app/components/logout/logout.component.html
- demo-shell/src/app/components/logout/logout.component.scss
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-12874
H1 and H2 elements gets …
> [AAE-12784] elements get typography from theme

- demo-shell/src/app/components/notifications/notifications.component.ts
- e2e/core/notifications-component.e2e.ts
- lib/core/src/lib/snackbar-content/snackbar-content.component.html
remove initial value to not break tests already present
> - [X] Bugfix
The issue is present in the …
> [HXCS-1322] fix e2e NotificaionComponent demo

- lib/core/src/lib/login/components/login.component.scss
> - [ ] Bugfix
'Sign in' text is not aligned properly in login button
'Sign in' text …
> [ACA-4654] Sign in button isn't centred as expected

- lib/core/src/lib/form/components/widgets/core/form.model.ts
- lib/core/src/lib/form/components/widgets/core/upload-widget-content-link.model.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
> - [ ] Bugfix
> - [] Feature
'uploadWidget' string present in `FormModel` class in adf doesn't allow for extensions in hxp
**What is …
> [AAE-12318] Adjustments for HxP Attach-File widget

- lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.spec.ts
- lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4589
Previously, the "update" …
> [ACA-4589] Remove requirement for update permission on node to open manage versions dialog

- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.html
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5021
Label for existing tags …
> [ACS-5021] Fixed displaying label above existing tags list

- docs/core/components/viewer.component.md
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.html
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.spec.ts
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.ts
- lib/core/src/lib/viewer/components/viewer.component.spec.ts
- lib/core/src/lib/viewer/components/viewer.component.ts
> - [ ] Bugfix
DownloadPrompt for viewer component was implemented in ACA-4675. However, the 'Download' button in …
> [ACA-4677] Added download functionality on DownloadPromptDialog

- docs/content-services/services/category.service.md
- lib/content-services/src/lib/category/services/category.service.spec.ts
- lib/content-services/src/lib/category/services/category.service.ts
- lib/content-services/src/lib/search/services/search-facet-filters.service.spec.ts
- lib/content-services/src/lib/search/services/search-facet-filters.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-4788
The category names and …
> [ACS-4788] Add support for the Categories facet

- lib/content-services/src/lib/category/mock/category-mock.service.ts
- lib/content-services/src/lib/category/services/category-tree-datasource.service.spec.ts
- lib/content-services/src/lib/category/services/category-tree-datasource.service.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-4662
If the searched …
> [ACS-4662] Allow to see category children after search

- lib/content-services/src/lib/category/categories-management/categories-management.component.html
- lib/content-services/src/lib/category/categories-management/categories-management.component.ts
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.html
> - [x] Bugfix
Some translations aren't displayed correctly, label is visible when should not. …
> [ACS-4523] Fix translation and label

- lib/content-services/src/lib/i18n/en.json
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5147
"a" is changed to "an" …
> [ACS-5147] Fixed typo

- lib/content-services/src/lib/tree/components/tree.component.html
- lib/content-services/src/lib/tree/components/tree.component.spec.ts
- lib/content-services/src/lib/tree/components/tree.component.ts
- lib/content-services/src/lib/tree/services/tree.service.spec.ts
- lib/content-services/src/lib/tree/services/tree.service.ts
> - [x] Bugfix
Exapnading/collapsing tree nodes is bugged when switching between chevron and node name. Nodes are …
> [ACS-5143] Tree component expand/collapse fix

- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5155
Required error message …
> [ACS-5155] tags message about required field displayed after discarding changes

- lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.scss
> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-14376
Spinner is aligned …
> [AAE-14376] Spinner is not aligned after opening task details

- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
Upstream for ACA is failing. Context menu is not visible for rows.  …
> [ADF-5517] Reverted extra bug fixes changes

- lib/core/src/lib/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
- remove unnecessary space for Name column when in the link mode
- …
> [ACS-5305] fix name column link alignment

- .github/workflows/cron-e2e.yml
- .github/workflows/pull-request.yml
> - [x] Bugfix
Cron E2E runs forbidden-labels step which fails outside of PR runs. …
> [ADF-5546] Don't run forbidden labels job when cron runs e2es

- lib/cli/README.md
- lib/cli/scripts/init-aae-env.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-15436
- Properly awaits …
> [AAE-15436] Fix init-aae-env await for apps to be deployed

- lib/core/src/lib/common/services/highlight-transform.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5395
<script is not allowed …
> [ACS-5395] Fixed possibility to containing script by string

- lib/content-services/src/lib/document-list/components/document-list.component.scss
- lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.scss
> - [X] Bugfix
If you go directly from personal files to libraries and open managing of members for that library then …
> [ACS-5364] Page refresh breaks icon styles

- lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5398
Actually dot in regex …
> [ACS-5398] Fixed useless regular expression character

- .github/workflows/release.yml
> [AAE-15422] revert use of action

- lib/content-services/src/lib/document-list/components/document-list.component.ts
> - [ ] Bugfix
resetNewFolderPagination() is private, but it is used in ACA  …
> Make resetNewFolderPagination() method public

- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
The header row of adf-datatable, shifts a little towards right. …
> [ACS-5145] Align header row with data rows.

- demo-shell/src/app/components/social/social.component.ts
- demo-shell/src/app/components/social/social.module.ts
- lib/content-services/src/lib/social/like.component.ts
- lib/content-services/src/lib/social/rating.component.ts
- lib/content-services/src/lib/social/social.module.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5572?atlOrigin=eyJpIjoiMmNiZTVlN2ZiODdiNDUzZWFlODAwODc0MTU1Mz …
> [ACS-5572] Add deprecated attribute to Like and Rating components

- docs/content-services/components/search-chip-autocomplete-input.component.md
- docs/content-services/components/search-filter-autocomplete-chips.component.md
- docs/content-services/pipes/is-included.pipe.md
- lib/content-services/karma.conf.js
- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/material.module.ts
- lib/content-services/src/lib/pipes/is-included.pipe.spec.ts
- lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.html
- lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.scss
- lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.spec.ts
- lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.ts
- lib/content-services/src/lib/search/components/search-filter-autocomplete-chips/search-filter-autocomplete-chips.component.html
- lib/content-services/src/lib/search/components/search-filter-autocomplete-chips/search-filter-autocomplete-chips.component.spec.ts
- lib/content-services/src/lib/search/components/search-filter-autocomplete-chips/search-filter-autocomplete-chips.component.ts
- lib/content-services/src/lib/search/components/search-properties/search-properties.component.html
- lib/content-services/src/lib/search/components/search-properties/search-properties.component.spec.ts
- lib/content-services/src/lib/search/components/search-properties/search-properties.component.ts
- lib/content-services/src/lib/search/models/autocomplete-option.interface.ts
- lib/content-services/src/lib/search/models/search-widget-settings.interface.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5266
The same component as …
> [ACS-5266] Advanced Search - New component for Category facet

- lib/process-services/src/lib/mock/process/process-filters.mock.ts
- lib/process-services/src/lib/mock/task/task-filters.mock.ts
- lib/process-services/src/lib/process-list/services/process-filter.service.spec.ts
- lib/process-services/src/lib/process-list/services/process-filter.service.ts
- lib/process-services/src/lib/task-list/services/task-filter.service.spec.ts
- lib/process-services/src/lib/task-list/services/task-filter.service.ts
> - [x] Bugfix
Multiple process or task filters were rendering
added a check before …
> [ACS-5480] Bug Fix for multiple process/task filters

- lib/core/src/lib/info-drawer/info-drawer-layout.component.scss
> - [x] Bugfix
- port the fix for the vertical alignment of the info drawer title from …
> [ACS-5687] info drawer layout fix for header

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
- lib/content-services/src/lib/document-list/components/document-list.component.scss
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACA-4712
Changes required to …
> [ACA-4712] changes required to disallow using important for styles in aca

- lib/cli/scripts/changelog.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-5400
Fixed incomplete string …
> [ACS-5400] Fix incomplete string escaping 

- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
> - [x] Bugfix
While hovering the edit icon (pencil) is flickering in chip-list input …
> [ACS-5693] - Fix flickering edit icon (pencil) on hover in chip-list input

- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
After clicking on library in datatable it was always selected
After …
> [ACS-5738] unable to unselect libraries

- lib/content-services/src/lib/common/services/people-content.service.spec.ts
- lib/content-services/src/lib/common/services/people-content.service.ts
> - [x] Bugfix
When PeopleContentService.getPerson() is called it changes state of current user. So every time we …
> [ACS-5373] - Every getPerson() call changes current user

- lib/content-services/src/lib/category/categories-management/categories-management.component.spec.ts
- lib/content-services/src/lib/category/categories-management/categories-management.component.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
> - [X] Bugfix
Clicking on the 'Discard changes' hides categories input while tags input remains visible and input is …
> [ACS-5226] Make Categories & Tags View Details Edit consistent

- e2e/content-services/upload/version-actions.e2e.ts
- lib/content-services/src/lib/version-manager/version-list.component.html
- lib/content-services/src/lib/version-manager/version-list.component.spec.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5797
Restore button is …
> [ACS-5797] Disable restore action for the latest version of file

- lib/cli/scripts/init-aps-env.ts
> - [x] Bugfix
```
***** Step 1 - Check License *****
Aps does NOT have a valid License!
Aps License missing
Aps license file download from S3 bucket
Aps License failed! undefined
APS license error: check the configuration
```
```
***** Step 1 - Check License *****
Aps does NOT have a valid License!
Aps …
```
> OPSEXP-2250 Fix s3 download command in init aps

- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.spec.ts
- lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.service.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/mock/edit-task-filter-cloud.mock.ts
> - [x] Bugfix
moment depedency is present in date-range-filter.component.ts file and also in test cases
**What is …
> [APPS-2127] migrated dependency in date-range-filter component from moment to date-fns

- e2e/search/search-filters.e2e.ts
> - [x] Bugfix
moment dependency is present in search-filters.e2e.ts file
migrate …
> [APPS-2131] remove dependency from search-filters.e2e.ts file

- scripts/webdriver-update-newest/README.md
- scripts/webdriver-update-newest/chrome_xml_schema.js
- scripts/webdriver-update-newest/update-to-newest-webdriver.sh
- scripts/webdriver-update-newest/update_schema.js
> - [ ] Bugfix
> - [x] Other... Please describe: adding script to replace files in web drivers node_modules to download newest driver …
> [AAE-1653] Script to update webdriver locally ADF

- demo-shell/src/app/components/task-list-demo/task-list-demo.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5898
- setDueAfterFilter with moment library always sent …
> [ACS-5898] prevent custom task filters from always sending due after date

- lib/process-services/src/lib/pipes/process-name.pipe.spec.ts
- lib/process-services/src/lib/pipes/process-name.pipe.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5861
Replacing moment js to …
> [ACS-5861] Replace moment to date-fns in process-name.pipe.ts

- docs/content-services/components/content-metadata-card.component.md
- lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5281
Editable of metadata …
> [ACS-5281] Allow to change editable of content metadata from parent

- docs/eslint-angular/rules/use-none-component-view-encapsulation.md
- lib/eslint-angular/README.md
> [ACS-5520] add eslint-angular README, rephrase rule documentation

- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.scss
> - [x] Bugfix
Long label radio button overlaps the options when in horizontal alignment …
> [AAE-16202] Fix long label overlap on radio button

- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
When changing sorting in files and opening and closing preview for a file, the sorting is not applied …
> [ACA-4313] - Sort order doesn't work correctly

- lib/core/src/lib/notifications/components/notification-history.component.html
> - [ ] Bugfix
- the "mark all" for notifications history has issues with translations (i.e. German)
- see …
> Use icon for "mark all" notifications

- lib/cli/scripts/init-aae-env.ts
- package-lock.json
- package.json
> - [ ] Bugfix
We use depracted 'request' which can lead to eg. security problems. …
> [ACS-5271] - replace deprecated 'request' library

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
- lib/content-services/src/lib/content-node-share/content-node-share.dialog.spec.ts
- lib/content-services/src/lib/content-node-share/content-node-share.dialog.ts
- lib/content-services/src/lib/i18n/en.json
> - [X] Bugfix
- Currently it is possible to type in past date for link expiration, which leads to an request error …
> [ACS-5748] The file gets unshared when setting the past expiration date

- lib/content-services/src/lib/common/services/rendition.service.ts
- lib/content-services/src/lib/common/services/rendition.services.spec.ts
> - [x] Bugfix
the Retry feature from method: getRendition does not work, because of wrong condition in rendition …
> [ACS-6003] - waitRendition in rendition.service.ts not working

- lib/process-services/src/lib/process-list/services/process.service.spec.ts
- lib/process-services/src/lib/process-list/services/process.service.ts
> - [ ] Bugfix
Direct date-fns methods are used process.service.ts which needed date format changes when migrated …
> [ACS-5878] Updated ProcessService to use custom date-fns methods

- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/core/src/lib/pagination/infinite-pagination.component.spec.ts
- lib/core/src/lib/pagination/infinite-pagination.component.ts
> - [x] Bugfix
Clicking on load more on the copy/move file/folder dialog would refresh the list and scroll to top …
> [MNT-23648] Clicking on Load More button no longer causes scroll position to reset to top

- lib/content-services/src/lib/mock/permission-list.component.mock.ts
- lib/content-services/src/lib/permission-manager/services/node-permission.service.spec.ts
- lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
> - [X] Bugfix
When a user creates a folder with the same name as a site, the wrong permissions are applied.
**What …
> [ACS-6002] Add permissions displaying Site Permissions outside of Sites

- lib/process-services/src/lib/task-list/components/start-task.component.ts
> - [x] Bugfix
moment depedency is being used in start-task.component
migrated …
> [APPS-2133] migration of dependency from moment to date-fns in start-task.component

- lib/content-services/src/lib/dialogs/node-lock.dialog.spec.ts
- lib/content-services/src/lib/dialogs/node-lock.dialog.ts
> - [ ] Bugfix
- migrate node-lock dialog to date-fns
- clean useless tests
**Does …
> migrate node lock dialog to date-fns

- docs/README.md
- docs/content-services/components/content-metadata-card.component.md
- docs/content-services/interfaces/content-metadata-custom-panel.interface.md
- docs/versionIndex.md
- lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.html
- lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/content-services/src/lib/content-metadata/content-metadata.module.ts
- lib/content-services/src/lib/content-metadata/interfaces/content-metadata-custom-panel.interface.ts
> - [ ] Bugfix
Added option to pass custom metadata side panels with custom title and …
> [ACS-5611] Add custom metadata side panels to metadata card component

- lib/core/src/lib/common/utils/date-fns-utils.spec.ts
- lib/core/src/lib/common/utils/date-fns-utils.ts
- lib/core/src/lib/form/components/widgets/core/form-field-validator.spec.ts
- lib/core/src/lib/form/components/widgets/core/form-field-validator.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
> - [ ] Bugfix
- migrate date and datetime form field validators to date-fns (with …
> [APPS-2108] migrate form field validators to date-fns

- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
> - [ ] Bugfix
Added the option to expand custom metadata panel initially. …
> [ACS-5611] Add the option to initially expand custom panel

- lib/content-services/src/lib/dialogs/library/library.dialog.spec.ts
- lib/content-services/src/lib/dialogs/library/library.dialog.ts
> - [x] Bugfix
Library dialog showed no error when user was not created at backend. …
> [ACS-5831] Added Generic Error to Library Dialog.

- lib/core/src/lib/datatable/data-column/data-column.component.ts
- lib/core/src/lib/datatable/data/data-column.model.ts
- lib/core/src/lib/datatable/data/object-datacolumn.model.ts
- lib/extensions/src/lib/config/document-list.extensions.ts
- lib/process-services-cloud/src/lib/services/variable-mapper.sevice.ts
> - [x] Bugfix
Fixes incorrect import and document list extension BC done for …
> Fix AAE-16968 BC

- docs/content-services/components/document-list.component.md
- lib/content-services/src/lib/document-list/components/document-list.component.html
- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/content-services/src/lib/document-list/models/preset.model.ts
- lib/core/src/lib/datatable/components/columns-selector/columns-selector.component.html
- lib/core/src/lib/datatable/components/columns-selector/columns-selector.component.spec.ts
- lib/core/src/lib/datatable/components/columns-selector/columns-selector.component.ts
- lib/core/src/lib/datatable/data/data-table.schema.ts
- lib/extensions/src/lib/config/document-list.extensions.ts
> - [ ] Bugfix
In document list component columns are static. Once configured via html or json, they can't be …
> [ACS-5566] - Add configurable columns to document list

- lib/core/src/lib/card-view/components/base-card-view.ts
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
- lib/core/src/lib/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.ts
- lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.ts
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.ts
> - [x] Bugfix
- add missing encapuslation for css
- add missing host classes for …
> [ACS-5645] metadata fixes for encapsulation and host classes

- .eslintrc.js
- lib/content-services/src/lib/common/services/people-content.service.spec.ts
- lib/content-services/src/lib/common/services/people-content.service.ts
- lib/content-services/src/lib/common/services/rendition.service.ts
- lib/content-services/src/lib/common/services/rendition.services.spec.ts
- lib/content-services/src/lib/dialogs/node-lock.dialog.spec.ts
- lib/content-services/src/lib/directives/library-favorite.directive.spec.ts
- lib/content-services/src/lib/directives/library-membership.directive.spec.ts
- lib/content-services/src/lib/directives/node-delete.directive.spec.ts
- lib/content-services/src/lib/directives/node-favorite.directive.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/webscript/webscript.component.ts
- lib/core/src/lib/login/components/login.component.spec.ts
- lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.spec.ts
- lib/process-services/src/lib/process-list/components/process-filters.component.spec.ts
- lib/process-services/src/lib/process-list/services/process-filter.service.spec.ts
- lib/process-services/src/lib/process-list/services/process-filter.service.ts
- lib/process-services/src/lib/process-list/services/process.service.spec.ts
> - [x] Bugfix
- fix the SonarCloud issues for promise rejections
- enable …
> [ACS-6190] prefer-promise-reject-errors rule and fixes

- lib/content-services/src/lib/permission-manager/components/user-name-column/user-name-column.component.spec.ts
- lib/content-services/src/lib/permission-manager/components/user-name-column/user-name-column.component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-6222
When displayName is not …
> [ACS-6222] Fixed missing display name for groups

- lib/testing/src/lib/protractor/core/pages/data-table-component.page.ts
- lib/testing/src/lib/protractor/process-services-cloud/actions/project.ts
> fix linting for ADF

- docs/core/components/data-column.component.md
- lib/core/src/lib/datatable/components/datatable-cell/datatable-cell.component.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
- lib/core/src/lib/datatable/components/location-cell/location-cell.component.spec.ts
- lib/core/src/lib/datatable/components/location-cell/location-cell.component.ts
- lib/core/src/lib/datatable/datatable.module.ts
> [AAE-16995] Code refactor of LocationCellComponent

- demo-shell/src/app/components/task-list-demo/task-list.module.ts
- docs/core/components/data-column.component.md
- lib/core/src/lib/datatable/components/amount-cell/amount-cell.component.ts
- lib/core/src/lib/datatable/components/boolean-cell/boolean-cell.component.ts
- lib/core/src/lib/datatable/components/datatable-cell/datatable-cell.component.spec.ts
- lib/core/src/lib/datatable/components/datatable-cell/datatable-cell.component.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/datatable/components/date-cell/date-cell.component.html
- lib/core/src/lib/datatable/components/date-cell/date-cell.component.spec.ts
- lib/core/src/lib/datatable/components/date-cell/date-cell.component.ts
- lib/core/src/lib/datatable/components/filesize-cell/filesize-cell.component.ts
- lib/core/src/lib/datatable/components/json-cell/json-cell.component.ts
- lib/core/src/lib/datatable/components/location-cell/location-cell.component.ts
- lib/core/src/lib/datatable/components/number-cell/number-cell.component.ts
- lib/core/src/lib/datatable/data/data-column.model.ts
- lib/core/src/lib/datatable/data/object-datacolumn.model.ts
- lib/core/src/lib/datatable/datatable.module.ts
- lib/core/src/lib/pipes/localized-date.pipe.ts
- lib/core/src/lib/pipes/pipe.module.ts
- lib/core/src/lib/pipes/time-ago.pipe.ts
- lib/extensions/src/lib/config/document-list.extensions.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-16965
New `dateConfig` params …
> [AAE-16965] Improve data table date column

- lib/core/src/lib/notifications/components/notification-history.component.html
- lib/core/src/lib/notifications/components/notification-history.component.spec.ts
- lib/core/src/lib/notifications/components/notification-history.component.ts
- lib/core/src/lib/notifications/helpers/notification.factory.ts
- lib/core/src/lib/notifications/models/notification.model.ts
> - [x] Bugfix
If 'mark as all is pressed', the notifications restore upon reloading the page. …
> [ACS-5311] Notification History Bug Fix

- lib/core/src/lib/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6210
Text is not trimmed correctly with files names which …
> [ACS-6210] - ACA column alinement shifted when we have very long file folder name

- lib/core/src/lib/auth/oidc/auth-config.service.spec.ts
- lib/core/src/lib/auth/oidc/auth-config.service.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-17804
The `redirectUri` from …
> [AAE-17804] Fix login redirection, add redirectUri from the app.config

- lib/cli/scripts/init-aae-env.ts
> AAE-15874 enable local development for Simpleapp

- lib/core/src/lib/auth/oidc/auth-config.service.spec.ts
- lib/core/src/lib/auth/oidc/auth-config.service.ts
- lib/core/src/lib/layout/components/header/header.component.html
- lib/core/src/lib/layout/components/header/header.component.spec.ts
- lib/core/src/lib/layout/components/header/header.component.ts
… app.config.json
> - [x] Bugfix
- https://alfresco.atlassian.net/browse/AAE-17909
- …
> [AAE-17909][AAE-17964] fix silent-refresh url is not set with the value - fix background image set to undefined 

- lib/core/src/lib/viewer/components/pdf-viewer.component.html
- lib/core/src/lib/viewer/components/pdf-viewer.component.spec.ts
- lib/core/src/lib/viewer/components/pdf-viewer.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6067
When we change file then …
> [ACS-6067] viewer thumbnails not refresh on file change

- docs/content-services/components/document-list.component.md
- docs/core/components/datatable.component.md
- lib/content-services/src/lib/document-list/components/document-list.component.html
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
> - [ ] Bugfix
Added resize option to document list and option to disable blur when …
> [MNT-23166] Add resize flag to document list with option to disable blur

- lib/core/src/lib/notifications/components/notification-history.component.html
- lib/core/src/lib/notifications/components/notification-history.component.spec.ts
- lib/core/src/lib/notifications/components/notification-history.component.ts
- lib/core/src/lib/notifications/helpers/notification.factory.ts
- lib/core/src/lib/notifications/models/notification.model.ts
Reverts Alfresco/alfresco-ng2-components#9011
Reverting the PR as storage quotas issues arise in the application.
https://alfresco.atlassian.net/browse/AAE-17910
> Revert "[ACS-5311] Notification History Bug Fix" As storage quotas issues arise

- scripts/update-version.sh
> - [x] Bugfix
- fix the bug with JS-API own package not bumping after all libs are …
> [PRODENG-211] fix js-api version bump

- lib/core/src/lib/auth/oidc/redirect-auth.service.ts
> - [x] Bugfix
Requires OAuth enabled.
In ADW when you are not logged in, try to enter eg. your-app-link/#/trashcan. …
> [AAE-18541] - OAuth - redirect does not work

- lib/core/src/lib/pagination/pagination.component.scss
- lib/core/src/lib/toolbar/toolbar.component.scss
> - [ ] Bugfix
use !important for styles should be disallowed. 
Removed 'important' …
> [ADF-5570][ADF-5571]Removed important property from 'toolbar.component.scss' and 'pagination.component.scss' in ADF

- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-18450
**Does this PR …
> [AAE-18450] fixed form value not updating instantly on radio change

- docs/process-services/components/process-list.component.md
- docs/process-services/components/task-list.component.md
- lib/process-services/src/lib/process-list/components/process-list.component.html
- lib/process-services/src/lib/process-list/components/process-list.component.ts
- lib/process-services/src/lib/task-list/components/task-list.component.html
- lib/process-services/src/lib/task-list/components/task-list.component.ts
> - [ ] Bugfix
There is an option to specify is task and process lists should be …
> [MNT-23166] Make tasks and processes lists resizable

- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/datatable/components/datatable/datatable.component.scss
- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
- lib/extensions/src/lib/config/document-list.extensions.ts
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-6323
User can reorder columns …
> [ACS-6323] dynamic content list changing columns order with drag drop

- lib/content-services/src/lib/common/services/nodes-api.service.ts
- lib/core/src/lib/viewer/components/pdf-viewer.component.ts
> - [x] Bugfix
- fix PDF viewer when running with HTTP …
> [MNT-24098] fixes for pdf with HTTP

- lib/core/src/lib/app-config/app-config.service.spec.ts
- lib/core/src/lib/app-config/app-config.service.ts
- lib/js-api/src/alfrescoApi.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-18459
**Does this PR …
> [AAE-18459] Fix invalidateSession is called when auth is not initilized by js-api

- lib/core/src/lib/card-view/components/card-view-mapitem/card-view-mapitem.component.scss
> - [ ] Bugfix
The css of card-view-mapitem uses '!important'
removed '!important' …
> [ADF-5569] Removed !important from card-view-mapitem Component

- lib/content-services/src/lib/search/components/search-properties/search-properties.component.spec.ts
- lib/content-services/src/lib/search/components/search-properties/search-properties.component.ts
> - [x] Bugfix
Search properties facet clear button do not clear search filter
Search …
> [ACS-6399] - ACA search properties facet clear button do not clear search filter

- lib/extensions/src/lib/services/extension-loader.service.spec.ts
- lib/extensions/src/lib/services/extension-loader.service.ts
- lib/extensions/src/lib/services/extension.service.spec.ts
- lib/extensions/src/lib/services/extension.service.ts
> - [ ] Bugfix
We can pass directly extension value instead of adding json file name …
> Allow to use extension value in addition to passing JSON file name

- demo-shell/src/app.config.json
- docs/content-services/components/alfresco-viewer.component.md
- docs/core/components/viewer.component.md
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.html
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.spec.ts
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.ts
- lib/core/src/lib/viewer/components/viewer.component.html
- lib/core/src/lib/viewer/components/viewer.component.spec.ts
- lib/core/src/lib/viewer/components/viewer.component.ts
- lib/core/src/lib/viewer/models/viewer.model.ts
- lib/testing/src/lib/protractor/core/pages/viewer.page.ts
> - [ ] Bugfix
The button to close the preview is located on the left side while the other control buttons are on the …
> [MNT-23433] configure position for close button on Viewer

- lib/content-services/src/lib/permission-manager/components/permission-container/permission-container.component.scss
- lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.scss
> - [ ] Bugfix
use !important for styles should be disallowed.
I have removed …
> [ADF-5567] Removed important property from 'permission-list.component.scss' in ADF

- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
> - [ ] Bugfix
use !important for styles should be disallowed.
I have removed …
> [ADF-5568] Removed important property from 'card-view-dateitem.component.scss' in ADF

- lib/core/src/lib/card-view/components/card-view-boolitem/card-view-boolitem.component.ts
- lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view/card-view.component.html
- lib/core/src/lib/card-view/components/card-view/card-view.component.scss
> - [ ] Bugfix
Minor UI and styling adjustments
UI for the cardView Component when viewed inside CreateRules section …
> [ACS-6211] Fixed UI alignment issues in create rules screen (CardView and child components)

- docs/compatibility.md
- docs/versionIndex.md
> - [ ] Bugfix
compatibility matrix document was not updated.
compatibility matrix …
> [ADF-5556] Compatibility matrix document update.

- lib/content-services/src/lib/tag/tag-node-list.component.spec.ts
- lib/js-api/test/upload.spec.ts
> unit test fixes for migration

- lib/cli/scripts/changelog.ts
> - [x] Bugfix
**What is the current behaviour?**
https://alfresco.atlassian.net/browse/AAE-19365
Changelog generation fails in special cases, when commit message contains special characters …
> [AAE-19365] Fix for changelog generation

- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.scss
- lib/core/src/lib/card-view/components/card-view/card-view.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-19343
The selected variable …
> [AAE-19343] Fix attach file widget advanced properties are not properly displayed

- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.spec.ts
- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
Unknown type for mapping is enough as log error
> - [x] Bugfix
fix unwanted notification error …
> [AAE-19604] fix unwanted notification error

- lib/core/src/lib/auth/basic-auth/basic-alfresco-auth.service.ts
- lib/core/src/lib/auth/services/authentication.service.spec.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6596
If Alfresco ticket (ticket-ECM) has been invalidated …
> [ACS-6596] - verify ticket on app loading

- lib/content-services/src/lib/content-node-share/content-node-share.dialog.html
- lib/content-services/src/lib/content-node-share/content-node-share.dialog.scss
- lib/content-services/src/lib/content-node-share/content-node-share.dialog.spec.ts
- lib/core/src/lib/styles/_colors.scss
- lib/core/src/lib/styles/_index.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6212
Labels don't overlap …
> [ACS-6212] Fix overlaping labels and incorrect color for warning

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.service.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.service.ts
- lib/content-services/src/lib/mock/content-model.mock.ts
- lib/content-services/src/lib/mock/date-range-search-filter.mock.ts
- lib/content-services/src/lib/pipes/content-pipe.module.ts
- lib/content-services/src/lib/pipes/public-api.ts
- lib/content-services/src/lib/pipes/tab-labels.pipe.spec.ts
- lib/content-services/src/lib/pipes/tab-labels.pipe.ts
- lib/content-services/src/lib/search/components/search-date-range-tabbed/search-date-range-tabbed.component.html
- lib/content-services/src/lib/search/components/search-date-range-tabbed/search-date-range-tabbed.component.ts
> - [x] Bugfix
Search filter was missing important settings for `date-range` type …
> [AAE-19610] Add specific date range settings to search filter

- lib/content-services/src/lib/i18n/en.json
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-6584
Some symbols are forbidden by the API, creating tags …
> [ACS-6584] Added validation for illegal characters when creating a tag

- docs/core/components/data-column.component.md
- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/datatable/data-column/data-column.component.stories.ts
- lib/core/src/lib/datatable/data-column/data-column.component.ts
- lib/core/src/lib/datatable/data/data-column.model.ts
- lib/core/src/lib/datatable/data/object-datacolumn.model.ts
- lib/core/src/lib/mock/data-column.mock.ts
- lib/extensions/src/lib/config/document-list.extensions.ts
- lib/extensions/src/lib/config/schema/plugin-extension.schema.json
> - [x] Bugfix
All columns are resizable and it can't be changed.
`resizable` option …
> [ACS-6489] Add resizable option for column data model

- docs/content-services/components/infinite-scroll-datasource.md
- lib/content-services/src/lib/infinite-scroll-datasource/index.ts
- lib/content-services/src/lib/infinite-scroll-datasource/infinite-scroll-datasource.spec.ts
- lib/content-services/src/lib/infinite-scroll-datasource/infinite-scroll-datasource.ts
- lib/content-services/src/lib/infinite-scroll-datasource/public-api.ts
- lib/content-services/src/lib/version-manager/version-list.component.html
- lib/content-services/src/lib/version-manager/version-list.component.scss
- lib/content-services/src/lib/version-manager/version-list.component.spec.ts
- lib/content-services/src/lib/version-manager/version-list.component.ts
- lib/content-services/src/lib/version-manager/version-manager.component.html
- lib/content-services/src/lib/version-manager/version-manager.component.spec.ts
- lib/content-services/src/lib/version-manager/version-manager.module.ts
- lib/content-services/src/public-api.ts
> - [x] Bugfix
If a node has over 100 versions only first 100 is displayed.
There is a …
> [ACA-4729] Add infinite scroll to version list

- demo-shell/src/assets/app.extensions.json
- docs/content-services/components/alfresco-viewer.component.md
- docs/core/components/viewer-render.component.md
- docs/core/components/viewer.component.md
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.html
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.ts
- lib/core/src/lib/viewer/components/viewer-render.component.html
- lib/core/src/lib/viewer/components/viewer-render.component.spec.ts
- lib/core/src/lib/viewer/components/viewer-render.component.ts
- lib/core/src/lib/viewer/components/viewer.component.html
- lib/core/src/lib/viewer/components/viewer.component.ts
- lib/core/src/lib/viewer/directives/viewer-extension.directive.spec.ts
- lib/core/src/lib/viewer/directives/viewer-extension.directive.ts
- lib/core/src/lib/viewer/services/view-util.service.spec.ts
- lib/core/src/lib/viewer/services/view-util.service.ts
- lib/extensions/src/lib/services/app-extension.service.ts
- lib/extensions/src/lib/services/extension-loader.service.ts
> - [x] Bugfix
Extensions provided via HTML projection stopped working after viewer refactoring. …
> [ACS-6620] Proper viewer extension template projection to viewer renderer

- lib/content-services/src/lib/search/components/search-filter-container/search-filter-container.component.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/datatable/components/datatable/datatable.component.scss
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
- lib/core/src/lib/i18n/en.json
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6565
Fixes according to the …
> [ACS-6565] ADW - Document List View Header - UX Bugs

- demo-shell/src/app/components/card-view/card-view.component.ts
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
- lib/core/src/lib/card-view/models/card-view-dateitem.model.ts
- lib/core/src/lib/common/utils/date-fns-utils.ts
> - [X] Bugfix
CardView only-Date type should display only UTC dates with time 00:00:00 …
> [HXCS-2818] CardViewDateItem component ignore timezone when displaying dates

- lib/content-services/src/lib/document-list/services/custom-resources.service.ts
- lib/extensions/src/lib/config/extension-utils.spec.ts
- lib/extensions/src/lib/config/extension-utils.ts
> - [x] Bugfix
1. Extensions can't extend exsiting rules, they can only replace them. It's problem, when 2 extensions …
> [MNT-24151] - ADW: Users can see some actions Edit Offline" and "Upload New Version" for the declared record

- lib/core/src/lib/auth/oidc/auth-config.service.ts
> - [x] Bugfix
Currently there is no way for a user to be redirect to a specific page after login (happening only in …
> AAE-19762 Fix login redirect

- lib/content-services/src/lib/search/components/search-text/search-text.component.scss
> - [x] Bugfix
Constant width for textfield
[ACS-6643](https://alfresco.atlassian.net/browse/ACS-6643)
**What is the …
> [ACS-6643] Incorrect layout for Search widgets of the Text type

- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6585
If tag is existing, than …
> [ACS-6585] - [ACC] Removing a to be created tag, while the create tag input field has a 'Tag already exists' error, removes the error

- lib/js-api/src/api/content-custom-api/api/upload.api.ts
> - [x] Bugfix
When `relativePath` is undefined the file is being created under `undefined` folder instead of the …
> [ACS-6804] Fix upload API file placement when relative path is undefined

- lib/js-api/src/api/content-rest-api/api/nodes.api.ts
> - [x] Bugfix
getNodeContent throws an JS error when additional options are passed. …
> [ACS-6805] getNodeContent allows adding additional options

- lib/core/src/lib/card-view/components/card-view-arrayitem/card-view-arrayitem.component.html
- lib/core/src/lib/card-view/components/card-view-arrayitem/card-view-arrayitem.component.ts
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.html
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
- lib/core/src/lib/card-view/components/card-view-mapitem/card-view-mapitem.component.html
- lib/core/src/lib/card-view/components/card-view-mapitem/card-view-mapitem.component.ts
- lib/core/src/lib/common/utils/date-fns-utils.spec.ts
- lib/core/src/lib/common/utils/date-fns-utils.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6722
Using custom aspect with d:date property breaks ACA …
> [ACS-6722] aca custom aspect property of d date type breaks application

- lib/core/src/lib/card-view/models/card-view-dateitem.model.ts
> - [x] Bugfix
There are errors in the console when opening the details tab for record files in ADW and they are not …
> [HXCS-2818] - fix issues with ERROR RangeError: Invalid time value

- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/src/lib/pipes/decimal-number.pipe.spec.ts
- lib/core/src/lib/pipes/decimal-number.pipe.ts
> - [x] Bugfix
Decimal pipe is not able to handle arrays and new chips are added regardless applied validators which …
> [ACS-6812] Add new chip only when input value is valid

- lib/content-services/src/lib/breadcrumb/breadcrumb.component.scss
> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6888
There is a small padding for a breadcrumb when inside a …
> [ACS-6888] - The root folder of breadcrumbs is misplaced when viewed from a folder view

- lib/content-services/src/lib/auth-loader/content-auth-loader-factory.ts
- lib/content-services/src/lib/auth-loader/content-auth-loader.service.spec.ts
- lib/content-services/src/lib/auth-loader/content-auth-loader.service.ts
- lib/content-services/src/lib/content.module.ts
- lib/core/src/lib/api-factories/alfresco-api-v2-loader.service.ts
> - [x] Bugfix
requireAlfTicket is triggered in apps which don't need it and it causes errors in console.
**What is …
> [ACS-6748] BasicAlfrescoAuthService.requireAlfTicket should not be in adf/core

- lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.component.ts
> - [x] Bugfix
https://alfresco.atlassian.net/browse/MNT-24028
Updating aspects with Aspect List Dialog Component …
> [MNT-24082] fix aspect overwriting from dialog

- lib/content-services/src/lib/category/services/category.service.spec.ts
- lib/content-services/src/lib/category/services/category.service.ts
- lib/content-services/src/lib/tag/services/tag.service.spec.ts
- lib/content-services/src/lib/tag/services/tag.service.ts
> - [x] Bugfix
Tags and categories plugins are renamed. …
> [ACS-6924] Rename tags and categories plugins

- lib/core/src/lib/form/components/form-renderer.component.spec.ts
- lib/core/src/lib/form/components/form-renderer.component.ts
- lib/core/src/lib/form/components/middlewares/decimal-middleware.service.spec.ts
- lib/core/src/lib/form/components/middlewares/decimal-middleware.service.ts
- lib/core/src/lib/form/components/middlewares/middleware.ts
- lib/core/src/lib/form/components/mock/form-renderer.component.mock.ts
- lib/core/src/lib/form/components/widgets/decimal/decimal.component.html
- lib/core/src/lib/form/components/widgets/decimal/decimal.component.ts
- lib/core/src/lib/form/form-base.module.ts
> [AAE-20769] Fix precision for incoming values in bigdecimal field

- docs/content-services/services/search-query-builder.service.md
- lib/content-services/src/lib/search/public-api.ts
- lib/content-services/src/lib/search/search-configuration.token.ts
- lib/content-services/src/lib/search/services/search-query-builder.service.spec.ts
- lib/content-services/src/lib/search/services/search-query-builder.service.ts
> - [ ] Bugfix
allow injecting Search configuration at runtime, for the scenarios …
> [ACS-7284] injectable search configuration

- lib/content-services/src/lib/search/components/search-input/search-input.component.spec.ts
- lib/content-services/src/lib/search/components/search-input/search-input.component.ts
> - [x] Bugfix
- fix formatting for asterisk (`*`), do not append extra one
**Does …
> [ACS-7338] Fix search input formatting for asterisk

- lib/cli/scripts/audit.ts
- lib/cli/scripts/changelog.ts
- lib/cli/scripts/check-cs-env.ts
- lib/cli/scripts/check-plugin-env.ts
- lib/cli/scripts/docker.ts
- lib/cli/scripts/init-aae-env.ts
- lib/cli/scripts/init-acs-env.ts
- lib/cli/scripts/init-aps-env.ts
- lib/cli/scripts/licenses.ts
- lib/cli/scripts/plugins/check-env.ts
- lib/cli/scripts/plugins/plugin-model.ts
- package-lock.json
- package.json
> - [ ] Bugfix
- upgrade ADF CLI to latest `Commander`
- migrate code to use ESM …
> Upgrade ADF CLI to latest Commander library

- lib/core/src/lib/form/components/mock/form.mock.ts
- lib/core/src/lib/form/components/widgets/core/form-field-types.ts
- lib/core/src/lib/form/components/widgets/core/form.model.spec.ts
- lib/core/src/lib/form/components/widgets/core/form.model.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-21380 …
> AAE-21380 Skip value override for constant field type

- lib/core/src/lib/layout/components/layout-container/layout-container.component.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-6628
Arrows in tabs are …
> [ACS-6628] Display arrows for tabs for extensions manager

- lib/core/src/lib/common/utils/date-fns-utils.spec.ts
- lib/core/src/lib/common/utils/date-fns-utils.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/HXCS-3381 …
> HXCS-3381 fix date widget

- lib/core/src/lib/context-menu/context-menu-list.component.html
- lib/core/src/lib/context-menu/context-menu-list.component.ts
- lib/core/src/lib/context-menu/context-menu.directive.ts
- lib/core/src/lib/context-menu/context-menu.module.ts
- lib/core/src/lib/context-menu/public-api.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7380
Context menu is standalone …
> [ACS-7380][ADF] Break Context Menu dependency on Material Module

- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
> AAE-21755 Error when form is assigned to process start event

- lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.ts
> [AAE-21797] Datetime widget Min/Max values are checked on a field that is not required

- .eslintrc.js
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/permission-manager/components/user-icon-column/user-icon-column.component.spec.ts
- lib/core/src/lib/datatable/components/icon-cell/icon-cell.component.spec.ts
- lib/core/src/lib/dialogs/unsaved-changes-dialog/unsaved-changes-dialog.component.spec.ts
- lib/eslint-angular/main.js
- package-lock.json
- package.json
> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-21233
Enables eslint rule for …
> AAE-21233 Enable no angular material selectors rule for adf

- lib/content-services/src/lib/aspect-list/aspect-list.component.scss
> - [x] Bugfix
On small screens we don't see action buttons. Modal jumped in 5px after loading mode. …
> [ACS-6721] [ACA] Aspects dialog does not display butons on smaller screens

- docs/content-services/components/aspect-list-dialog.component.md
- docs/content-services/components/aspect-list.component.md
- lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.html
- lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.ts
- lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.component.ts
> - [x] Bugfix
Edit aspects dialog counter shows a sum of node's current not listed aspects and aspects selected in …
> [MNT-24028] edit aspects dialog counter bug

- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-21361
Currently, date widget treats minDateRangeValue as …
> AAE-21361 Modify date widget to handle negative values

- lib/content-services/src/lib/dialogs/folder.dialog.html
- lib/content-services/src/lib/dialogs/folder.dialog.spec.ts
- lib/content-services/src/lib/dialogs/folder.dialog.ts
> - [x] Bugfix
Create button still enable after clicking. Multiple API calls. …
> [ACS-6842] [ACA] Clicking "Create" button multiple times in folder creation modal sends the same folder creation request multiple times

- lib/content-services/src/lib/content-node-selector/content-node-dialog.service.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
- lib/content-services/src/lib/content-node-share/content-node-share.dialog.spec.ts
- lib/content-services/src/lib/content-node-share/content-node-share.module.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/content-services/src/lib/document-list/services/folder-actions.service.spec.ts
- lib/content-services/src/lib/document-list/services/node-actions.service.spec.ts
- lib/content-services/src/lib/permission-manager/services/node-permission-dialog.service.spec.ts
- lib/content-services/src/lib/tag/tag-list.component.spec.ts
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
- lib/core/src/lib/viewer/components/viewer.component.ts
> - [ ] Bugfix
Jira: ACS-7679
- remove the useless imports of the `AppConfigService` …
> [ACS-7679] Reduce the usage of AppConfigService in components and tests

- lib/core/src/lib/form/components/form-renderer.component.scss
> AAE-21256 Fix form widget styles

- lib/core/src/lib/form/components/widgets/amount/amount.widget.html
- lib/core/src/lib/form/components/widgets/amount/amount.widget.scss
> - [ ] Bugfix
Style fix
Amount widget with broken styles after Angular 15 migration …
> AAE-21393 Fix amount widget style

- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
> - [ ] Bugfix
Style fix
Dropdown widget with broken styles after Angular 15 migration …
> AAE-21392 Fix dropdown widget style

- lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/data-table/helpers/data-table-path-parser.helper.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/data-table/helpers/data-table-path-parser.helper.ts
- lib/process-services-cloud/src/lib/form/components/widgets/data-table/mocks/data-table-path-parser.helper.mock.ts
- lib/process-services-cloud/src/lib/form/components/widgets/data-table/mocks/data-table-widget.mock.ts
> - [x] Bugfix
https://hyland.atlassian.net/issues/AAE-22222 …
> AAE-22222 Fix JSON path doesn't work for square bracekts

- lib/content-services/src/lib/breadcrumb/dropdown-breadcrumb.component.html
- lib/content-services/src/lib/breadcrumb/dropdown-breadcrumb.component.scss
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
- lib/content-services/src/lib/site-dropdown/sites-dropdown.component.html
- lib/core/src/lib/styles/_mat-selectors.scss
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7572 …
> [ACS-7572] link rules dialog fixes

- lib/core/src/lib/notifications/components/add-notification.stories.component.ts
- lib/core/src/lib/notifications/components/notification-history.component.html
- lib/core/src/lib/notifications/components/notification-history.component.spec.ts
- lib/core/src/lib/notifications/components/notification-history.component.ts
- lib/core/src/lib/notifications/notification-history.module.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7386
no material module …
> [ACS-7386][ADF] Break Notifications dependency on Material Module

- lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.html
- lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
- lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
> - [ ] Bugfix
Style fix
Group widget with broken styles after Angular 15 migration …
> AAE-21703 Fix group widget style

- e2e-playwright/process-services-cloud/specs/people-cloud.e2e.ts
> - [ ] Bugfix
> - [x] Other... Please describe: Fix failing or flaky e2es for storybook.
https://hyland.atlassian.net/browse/AAE-22417
**What is the …
> AAE-22417 Fix storybook e2es

- lib/extensions/src/lib/services/app-extension.service.ts
…n app init (now to be done in ADW)
> - [x] Bugfix
App Extension service had code to apply extension state saved in …
> [ACS-7740] Removed ADF code to apply saved extensions management config on app init

- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
Reverts Alfresco/alfresco-ng2-components#9677
> Revert "AAE-12086 The error message is shown for completed task with read-only fields [ADW]"

- lib/process-services-cloud/package.json
- lib/process-services/src/lib/process-list/components/process-filters.component.scss
- lib/process-services/src/lib/task-list/components/task-filters.component.scss
> - [x] Bugfix
Labels of APS filters in side nav is not center aligned
Labels of APS …
> [ACS-7941] Fixed alignment of text inside buttons

- lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.ts
- lib/process-services-cloud/src/lib/form/components/widgets/data-table/helpers/data-table-path-parser.helper.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/data-table/helpers/data-table-path-parser.helper.ts
- lib/process-services-cloud/src/lib/form/components/widgets/data-table/mocks/data-table-path-parser.helper.mock.ts
- lib/process-services-cloud/src/lib/form/components/widgets/data-table/mocks/data-table-widget.mock.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-22577 …
> AAE-22577 Improve DataTable widget to support single object reference (e.g. only 1st element from array) - Case 3

- lib/process-services/src/lib/process-list/components/process-filters.component.scss
- lib/process-services/src/lib/task-list/components/task-filters.component.scss
> - [x] Bugfix
Tasks and processes filter had different spacing from rest of side nav …
> [ACS-7769] Fixed UI issue where Tasks and Processes filters had different spacing than the rest of side-nav

- lib/core/src/lib/common/services/sort-by-category.service.ts
> - [ ] Bugfix
`name` has been made optional in `SortableByCategoryItem` interface. …
> [ACS-7430] Make name optional in SortableByCategoryItem interface

- lib/content-services/src/lib/dialogs/library/library.dialog.html
- lib/content-services/src/lib/dialogs/library/library.dialog.scss
- lib/core/src/lib/styles/_mat-selectors.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8042
Inputs for library …
> [ACS-8042] Fixed styles for inputs in library creation

- lib/content-services/src/lib/prediction/services/prediction.service.spec.ts
- lib/content-services/src/lib/prediction/services/prediction.service.ts
- lib/js-api/src/api/hxi-connector-api/api/predictions.api.ts
- lib/js-api/src/api/hxi-connector-api/docs/PredictionsApi.md
> - [ ] Bugfix
New endpoint for confirming/rejecting predictions has been added. …
> [ACS-8037] Add new endpoint to confirm/reject prediction

- lib/core/src/lib/viewer/components/pdf-viewer/pdf-viewer.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-22443
https://hyland.atlassian.net/browse/MNT-24444
**What is …
> AAE-22443 disable insecure eval support for pdf viewer

- docs/release-notes/RelNote-6.10.0.md
- lib/content-services/src/lib/tree-view/components/tree-view.component.spec.ts
- lib/content-services/src/lib/tree-view/components/tree-view.component.ts
- lib/content-services/src/lib/tree-view/services/tree-view.service.ts
- lib/content-services/src/lib/tree-view/tree-view.module.ts
> - [ ] Bugfix
ACS-6124
the tree view component is not used in any internal applicaiton, not being tested and/or …
> [ACS-6124] Mark tree view component for deprecation

- lib/content-services/src/lib/category/categories-management/categories-management.component.html
- lib/content-services/src/lib/category/categories-management/categories-management.component.scss
- lib/content-services/src/lib/category/categories-management/categories-management.component.ts
- lib/content-services/src/lib/tag/tag.module.ts
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.html
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.scss
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
Minor UI fixes for create category dialog as well
> - [ ] Bugfix
UI Fixes for create tags and create category dialogs after angular upgrade
**What is the current behaviour?** (You can also link …
> [ACS-7979] Fixed UI for create tags dialog

- lib/process-services/src/lib/process-list/components/process-filters/process-filters.component.scss
- lib/process-services/src/lib/task-list/components/task-filters/task-filters.component.scss
> - [ ] Bugfix
Re-commiting fixes for alignment issue in filters button in side nav. These changes were pushed before as well, but seem to have gotten lost in rebase …
> [ACS-8212] Fixed alignment issue of filters button in sidenav

- lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-23134 …
> AAE-23134 Fix overlapping external property widgets when key is too long

- lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.spec.ts
> - [x] Bugfix
https://hyland.atlassian.net/issues/AAE-23115 …
> AAE-23115 Display key of the user attribute in external property preview

- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-23099
Datatable selection is …
> AAE-23099 Reset datatable selection on multiselect change to false

- lib/core/src/lib/card-view/validators/card-view-item-length.valiator.ts
- lib/core/src/lib/card-view/validators/card-view-item-length.validator.spec.ts
- lib/core/src/lib/card-view/validators/card-view-item-match.valiator.ts
- lib/core/src/lib/card-view/validators/card-view-item-match.validator.spec.ts
- lib/core/src/lib/card-view/validators/card-view-item-minmax.valiator.ts
- lib/core/src/lib/card-view/validators/card-view-item-minmax.validator.spec.ts
- lib/core/src/lib/card-view/validators/card-view-item-only-positive-int.validator.spec.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/MNT-24351
Some of card-view validators don't have array …
> [MNT-24351] Add missing array validation to card-view

- lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/AAE-23165 …
> AAE-23165 Not blocking task completion when there's no value selected in required radio buttons widget

- lib/core/src/lib/form/components/widgets/core/form-field-validator.spec.ts
- lib/core/src/lib/form/components/widgets/core/form-field-validator.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
- lib/process-services/src/lib/form/form.component.spec.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/AAE-23116 …
> AAE-23116 Dropdown should not display errors / call apis when it's in readOnly state [without refactor]

- lib/core/feature-flags/src/lib/components/flags/flags.component.html
> - [X] Bugfix
https://hyland.atlassian.net/browse/AAE-23369 …
> AAE-23369 Feature flag override dialog missing the label in header

- lib/content-services/src/lib/content-node-selector/content-node-selector.component.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8258 …
> [ACS-8258] Wrong background for 'move dialog' action buttons

- demo-shell/src/app/components/file-view/file-view.component.html
- demo-shell/src/app/components/file-view/file-view.component.ts
- demo-shell/src/app/components/file-view/file-view.module.ts
- lib/core/src/lib/core.module.ts
- lib/core/src/lib/info-drawer/info-drawer-layout.component.ts
- lib/core/src/lib/info-drawer/info-drawer.component.html
- lib/core/src/lib/info-drawer/info-drawer.component.stories.ts
- lib/core/src/lib/info-drawer/info-drawer.component.ts
- lib/core/src/lib/info-drawer/info-drawer.module.ts
- lib/core/src/lib/login/login.module.ts
- lib/process-services/src/lib/task-list/components/task-details/task-details.component.ts
> - [ ] Bugfix
- migrate Info Drawer to standalone components
- reduce amount of …
> ACS-8255: Migrate InfoDrawer component to Standalone

- docs/core/dialogs/dialog.md
- docs/core/interfaces/dialog.interface.md
- docs/core/models/dialog.model.md
- lib/core/src/lib/dialogs/dialog/dialog-data.interface.ts
- lib/core/src/lib/dialogs/dialog/dialog.component.spec.ts
- lib/core/src/lib/dialogs/dialog/dialog.component.ts
https://hyland.atlassian.net/browse/ACS-8254
> - [ ] Bugfix
can't pass data on confirmation `dataOnConfirm$`
**What …
> ACS-8254 [ADF] Add functionality to pass data on confirmation in DialogComponent

- lib/core/src/lib/common/utils/date-fns-utils.spec.ts
- lib/core/src/lib/common/utils/date-fns-utils.ts
- lib/core/src/lib/form/components/widgets/core/error-message.model.ts
- lib/core/src/lib/form/components/widgets/core/form-field-validator.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.ts
- lib/core/src/lib/form/components/widgets/date-time/date-time.widget.ts
This reverts commit f785e1e.**Please check if the PR fulfills these requirements**
> - [ ] Bugfix
Reverts:
- https://github.com/Alfresco/alfresco-ng2-components/pull/9891
- …
> Revert "[AAE-23640] Fix dates (#9916)"

- lib/js-api/src/alfrescoApi.ts
- lib/js-api/test/alfrescoApi.spec.ts
- lib/js-api/test/mockObjects/content-services/ecm-auth.mock.ts
> - [x] Bugfix
The config object is initialized with the ticket from browser local storage which can be invalid, …
> [MNT-24449] Validate ticket on config initialization

- demo-shell/src/app/components/app-layout/app-layout.component.html
- docs/README.md
- docs/core/components/avatar.component.md
- docs/core/components/button.component.md
- lib/core/src/lib/avatar/avatar.component.html
- lib/core/src/lib/avatar/avatar.component.md
- lib/core/src/lib/avatar/avatar.component.scss
- lib/core/src/lib/avatar/avatar.component.spec.ts
- lib/core/src/lib/avatar/avatar.component.ts
- lib/core/src/public-api.ts
> - [ ] Bugfix
- simple `Avatar` component (`<adf-avatar>`)
- theming and usage docs …
> ACS-8315: avatar component

- lib/core/src/lib/auth/oidc/redirect-auth.service.spec.ts
- lib/core/src/lib/auth/oidc/redirect-auth.service.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-24081
Token is refreshed …
> AAE-24081 Fix refresh token error with multiple tabs opened

- lib/core/src/lib/common/utils/date-fns-utils.spec.ts
- lib/core/src/lib/common/utils/date-fns-utils.ts
- lib/core/src/lib/form/components/widgets/core/error-message.model.ts
- lib/core/src/lib/form/components/widgets/core/form-field-validator.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.ts
- lib/core/src/lib/form/components/widgets/date-time/date-time.widget.ts
> - [ ] Bugfix
The datetime is always interpreted as local time, but this is not true when the datetime was …
> AAE-23666 Make Datetime timezone aware

- lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.ts
- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.ts
- lib/process-services/src/lib/form/form.component.spec.ts
- lib/process-services/src/lib/form/widgets/radio-buttons/radio-buttons.widget.spec.ts
- lib/process-services/src/lib/form/widgets/radio-buttons/radio-buttons.widget.ts
> AAE-22948 Radio buttons should not display errors / call apis when they're in readOnly state

- lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.ts
- lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-tabbed-content.component.spec.ts
- lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-tabbed-content.component.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/ACS-8081
The search query is updated when options are selected, …
> [ACS-8081] People facet - update the query on apply hit

- lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.scss
- lib/core/src/lib/styles/_mat-selectors.scss
> - [x] Bugfix
Dropdown arrows were too far to the left in create/edit rule window …
> [ACS-8451] Fixed arrow position for select dropdowns in create/edit rules dialog

- lib/extensions/src/lib/config/action.extensions.ts
https://hyland.atlassian.net/browse/ACS-8325
> - [ ] Bugfix
extend `ContentActionRef` …
> [ACS-8325] [Bulk Legal Hold] Create Bulk Actions Dropdown 

- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
- lib/process-services/src/lib/form/widgets/dropdown/dropdown.widget.html
- lib/process-services/src/lib/form/widgets/dropdown/dropdown.widget.spec.ts
- lib/process-services/src/lib/form/widgets/dropdown/dropdown.widget.ts
> - [X] Bugfix
AAE-24018
https://github.com/user-attachments/assets/df688bc9-262e-476a-88a8-5abfb04dcb02
**Note:** We …
> AAE-24018 Readonly dropdown with the rest config don't fetch options when form rule change it to not readonly

- lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.spec.ts
- lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8476
Attach file window opens …
> [ACS-8476] ADW - on localhost attach file widget is opening login page instead of node selector

- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
> - [x] Bugfix
Folder select input fields had broken UI after ng15 upgrade
Fixed UI …
> [ACS-8452] Fixed UI for folder select input fields in create/edit rules

- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/datatable/components/datatable/datatable.component.scss
- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/ACS-8247
The area around the …
> [ACS-8247] Fixed empty context menu for DataTable row

- lib/core/src/lib/search-text/search-text-input.component.html
- lib/core/src/lib/search-text/search-text-input.component.spec.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8514
Changed incorrect mat-icon …
> [ACS-8514] Use proper icon button in search text input

- lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.ts
- lib/process-services/src/lib/form/widgets/dropdown/dropdown.widget.spec.ts
- lib/process-services/src/lib/form/widgets/dropdown/dropdown.widget.ts
- lib/process-services/src/lib/form/widgets/radio-buttons/radio-buttons.widget.spec.ts
- lib/process-services/src/lib/form/widgets/radio-buttons/radio-buttons.widget.ts
> AAE-24007 Display radio buttons and dropdown options depending on optionType

- docs/process-services-cloud/components/people-cloud.component.md
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
> - [ ] Bugfix
It's not possible to customize the `appearance` and `subscriptSizing` of the `mat-form-field` inside …
> Allow for more customization of adf-cloud-people component

- lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.html
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8263 …
> [ACS-8263] Testing Angular 15 - Upload button in e2e-attach_file_local-process has additonal "d" at the end

- lib/content-services/src/lib/upload/components/file-uploading-list-row.component.html
- lib/content-services/src/lib/upload/components/file-uploading-list-row.component.scss
> - [x] Bugfix
Icons in the file upload overlay were getting cut off after ng16 upgrade …
> [ACS-8497] Resolved issue where icons in file upload overlay were not displaying properly

- lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.spec.ts
- lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-6423?focusedCommentId=1240084 …
> [ACS-6423] Add missing account id piece

- lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
> AAE-23830 Label for people component

- docs/content-services/services/document-list.service.md
- lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
- lib/content-services/src/lib/document-list/components/document-list.component.ts
- lib/content-services/src/lib/document-list/services/document-list.service.spec.ts
- lib/content-services/src/lib/document-list/services/document-list.service.ts
> - [ ] Bugfix
- ACS-8572: port the document list reloading from the ACA/ADW (this …
> ACS-8572: Support for reloading document list from outside

- lib/content-services/src/lib/search/components/search-text/search-text.component.html
- lib/content-services/src/lib/search/components/search-text/search-text.component.scss
> - [x] Bugfix
Clear Filter (X) button was getting cut off in name filter overlay …
> [ACS-8555] Name filter clear icon now no longer gets cut off

- lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/services/basic-properties.service.ts
- lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts
- lib/content-services/src/lib/dialogs/download-zip/download-zip.dialog.module.ts
- lib/core/src/lib/card-view/components/card-view-arrayitem/card-view-arrayitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view-keyvaluepairsitem/card-view-keyvaluepairsitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view-mapitem/card-view-mapitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view/card-view.component.spec.ts
- lib/core/src/lib/core.module.ts
- lib/core/src/lib/form/components/widgets/date-time/date-time.widget.spec.ts
- lib/core/src/lib/form/components/widgets/text/text.widget.spec.ts
- lib/core/src/lib/pipes/pipe.module.ts
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
- lib/process-services/src/lib/attachment/create-process-attachment/create-process-attachment.component.spec.ts
- lib/process-services/src/lib/attachment/task-attachment-list/task-attachment-list.component.spec.ts
- lib/process-services/src/lib/process-list/components/start-process/start-process.component.spec.ts
- lib/process-services/src/lib/testing/process.testing.module.ts
> - [ ] Bugfix
- fix the usage of pipes in the Content Metadata services
- remove Pipe …
> ACS-8586: Remove internal dependency on PipeModule

- e2e/content-services/components/viewer-content-services-component.e2e.ts
- lib/core/src/lib/i18n/en.json
> - [ ] Bugfix
Translation adjustment
Translation label for document viewer error was "Couldn't load preview. Unknown …
> HXCS-3181 Update translation label for viewer error

- lib/core/custom-theme/theme/typography.scss
> AAE-25326 Fix custom theme

- demo-shell/src/app/app.module.ts
- lib/core/src/lib/common/utils/date-fns-adapter.ts
- lib/core/src/lib/common/utils/datetime-fns-adapter.ts
- lib/core/src/lib/core.module.ts
- lib/insights/src/lib/analytics-process/components/analytics-report-parameters.component.ts
- lib/insights/src/lib/insights.module.ts
- lib/insights/src/lib/testing/insights.testing.module.ts
> - [x] Bugfix
- property export the date-fns related services, without requiring …
> Fix date-fns related exports for Core lib

- docs/core/components/viewer-render.component.md
- docs/core/components/viewer.component.md
- docs/extensions/components/preview-extension.component.md
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.html
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.html
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.ts
- lib/core/src/lib/viewer/components/viewer.component.html
- lib/core/src/lib/viewer/components/viewer.component.ts
- lib/extensions/src/lib/components/viewer/preview-extension.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/MNT-24553
It's possible to pass …
> [MNT-24553] Allow custom viewer extension components to obtain node id

- lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.ts
> - [x] Bugfix
Download button and comments section from manage versions dialog was missing …
> [ACS-8644] Fixed issue where download button and comments section was missing on manage versions dialog

- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8639 …
> ACS-8639 - [ACC ]Adding a space to the front/end of a tag name during tag creation removes the 'Tag already exists' validation message

- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.html
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.scss
- lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8638
Tags in creator don't have …
> [ACS-8638] - [ACC] User is able to 'select' tag chip while creating new tags in ACC

- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.ts
> - [x] Bugfix
Selection state on document list was not getting reset when selected document was no longer available …
> [ACS-8663] Fixed issue where datatable selection was not getting reset completely in some cases

- lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.spec.ts
- lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8648 …
> [ACS-8635] ADW: View button not working on create process

- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
- lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
> - [ ] Bugfix
The start and cancel button labels can not be customised in process cloud …
> AAE-25190 Retrieve start process cloud customisation

- docs/content-services/services/search-ai.service.md
- lib/content-services/src/lib/search-ai/services/search-ai.service.spec.ts
- lib/content-services/src/lib/search-ai/services/search-ai.service.ts
- lib/js-api/src/api/content-rest-api/api/search-ai.api.ts
- lib/js-api/src/api/content-rest-api/docs/SearchAiApi.md
- lib/js-api/src/api/content-rest-api/model/index.ts
- lib/js-api/src/api/content-rest-api/model/knowledgeRetrievalConfig.ts
- lib/js-api/src/api/content-rest-api/model/knowledgeRetrievalConfigEntry.ts
- lib/js-api/test/content-services/searchAiApi.spec.ts
- lib/js-api/test/mockObjects/content-services/search-ai.mock.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8664
Added possibility to …
> [ACS-8664] generic question redirection to hx insight

- lib/core/package.json
- lib/core/src/lib/auth/models/oauth-config.model.ts
- lib/core/src/lib/auth/oidc/auth-config.service.spec.ts
- lib/core/src/lib/auth/oidc/auth-config.service.ts
- lib/core/src/lib/auth/oidc/redirect-auth.service.spec.ts
- lib/core/src/lib/auth/oidc/redirect-auth.service.ts
- package-lock.json
- package.json
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-24139 …
> AAE-24139 Fix unauthorized user error when access token is not valid

- lib/core/src/lib/card-view/components/card-view-selectitem/select-filter-input/select-filter-input.component.html
- lib/core/src/lib/card-view/components/card-view-selectitem/select-filter-input/select-filter-input.component.scss
> - [x] Bugfix
UI for Type To Narrow field was broken. Clear 'X' button was overlapping with the form field underline …
> [ACS-8556] Resolved issue where UI for type to narrow field in the add aspect dropdown was broken

- lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.spec.ts
- lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.ts
- lib/content-services/src/lib/search/components/search-text/search-text.component.spec.ts
- lib/content-services/src/lib/search/components/search-text/search-text.component.ts
> - [x] Bugfix
Filters in document list header were not getting reset when navigating between folders
**What is the …
> [ACS-8666] Fixed issue where header filters were not getting reset when navigating between folders

- lib/process-services-cloud/src/lib/task/task-filters/components/base-task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-25268 …
> [AAE-25268] emit filter key when it's value increased or decreased

- lib/core/src/lib/viewer/components/img-viewer/img-viewer.component.ts
ACS-24317 fix src double call
First part 
https://hyland.atlassian.net/browse/MNT-24317
> - [x] Bugfix
double call …
> [MNT-24317]Audit app creates multiple entries on document preview in ADW

- lib/core/src/lib/dialogs/dialog/dialog.component.html
- lib/core/src/lib/dialogs/dialog/dialog.component.scss
https://hyland.atlassian.net/browse/ACS-8602
the issue accrues after angular migration. because of `::before` space above title was too big.
> - [x] Bugfix
**What is the current behaviour?** …
> [ACS-8602] [Legal Hold] The tabs names in "Manage Legal Holds" window are not matching the design

- lib/process-services-cloud/src/lib/form/components/widgets/display-rich-text/display-rich-text.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/display-rich-text/display-rich-text.widget.ts
> - [X] Bugfix
AAE-26043
AAE-26043 …
> AAE-26043 Use text alignment set in rich text editor

- lib/content-services/src/lib/search/components/search-control.component.spec.ts
- lib/core/src/lib/search-text/search-text-input.component.html
- lib/core/src/lib/search-text/search-text-input.component.scss
- lib/core/src/lib/search-text/search-text-input.component.spec.ts
- lib/core/src/lib/search-text/search-text-input.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-25888
Expandable search text input offset by approximate not …
> AAE-25888 Offset SearchTextInput expansion based on search icon width

- lib/core/src/lib/viewer/components/viewer.component.spec.ts
- lib/core/src/lib/viewer/components/viewer.component.ts
> - [X] Bugfix
Non responsive download prompt dialog will pop up even if the viewer was rendered properly using …
> [ACS-8823] Viewer - do not show non responsive dialog if blobFile was provided

- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.spec.ts
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.ts
> - [X] Bugfix
Doc files can not be rendered in the viewer
https://hyland.atlassian.net/browse/ACS-8841
**What is the …
> [ACS-8841] Fix viewer rendering for doc files

- lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
- lib/process-services-cloud/src/lib/form/services/display-mode.service.spec.ts
- lib/process-services-cloud/src/lib/form/services/display-mode.service.ts
- lib/process-services-cloud/src/lib/services/form-fields.interfaces.ts
> - [ ] Bugfix
AAE-26142
AAE-26142 …
> AAE-26142 Allow standalone form display configuration

- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.spec.ts
- lib/content-services/src/lib/viewer/components/alfresco-viewer.component.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/ACS-8865
DOCX files could not load preview for the first 20 …
> [ACS-8865] Viewer / DOCX files could not load preview for the first 20 seconds - error 409 for renditions

- lib/process-services/src/lib/process-list/components/process-filters/process-filters.component.scss
- lib/process-services/src/lib/task-list/components/task-filters/task-filters.component.scss
> - [x] Bugfix
Sidnav text for processes and tasks filter was black
Sidenav text for …
> [ACS-8741] Sidenav text for Process and Task filters is now grey

- lib/core/src/lib/layout/components/layout-container/layout-container.component.scss
> - [x] Bugfix
Layout container was allowing content to overflow screen. In this case, scroll logic was handled at …
> AAE-26181 Fix layout container overflowing screen

- lib/core/src/lib/auth/guard/auth-guard-bpm.service.spec.ts
- lib/core/src/lib/auth/guard/auth-guard-ecm.service.spec.ts
- lib/core/src/lib/auth/guard/auth-guard.service.spec.ts
- lib/core/src/lib/auth/guard/auth-guard.service.ts
- lib/core/src/lib/auth/oidc/auth.module.ts
- lib/core/src/lib/auth/oidc/auth.service.ts
- lib/core/src/lib/auth/oidc/oidc-auth.guard.spec.ts
- lib/core/src/lib/auth/oidc/oidc-auth.guard.ts
- lib/core/src/lib/auth/oidc/oidc-authentication.service.spec.ts
- lib/core/src/lib/auth/oidc/oidc-authentication.service.ts
- lib/core/src/lib/auth/oidc/redirect-auth.service.spec.ts
- lib/core/src/lib/auth/oidc/redirect-auth.service.ts
- lib/core/src/lib/auth/oidc/retry-login.service.spec.ts
- lib/core/src/lib/auth/oidc/retry-login.service.ts
- lib/core/src/lib/auth/oidc/token.interceptor.spec.ts
- lib/core/src/lib/auth/oidc/token.interceptor.ts
- lib/core/src/lib/auth/services/time-sync.service.spec.ts
- lib/core/src/lib/auth/services/time-sync.service.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-26163
- After 3 failed login …
> AAE-26163 Fix infinite loop when authentication error event occured

- docs/process-services-cloud/components/people-cloud.component.md
- docs/process-services-cloud/components/task-list-cloud.component.md
- lib/process-services-cloud/src/lib/models/filter-cloud-model.ts
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-list/services/process-task-list-cloud.service.ts
- lib/process-services-cloud/src/lib/services/cloud-token.service.ts
- lib/process-services-cloud/src/lib/services/task-list-cloud.service.interface.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts
- lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-26192 …
> AAE-26192 New task search API

- docs/core/services/saved-searches.service.md
- lib/content-services/src/lib/common/services/saved-searches.service.spec.ts
- lib/content-services/src/lib/common/services/saved-searches.service.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8634
Name of saved searches …
> [ACS-8634] Change saved searches config file name

- lib/content-services/src/lib/content-metadata/services/content-metadata.service.spec.ts
- lib/content-services/src/lib/content-metadata/services/content-metadata.service.ts
> - [x] Bugfix
When there are aspects with the same title in a custom model, the UI metadata panels will also have …
> [MNT-24698] Add aspect name to the title when there are duplicated aspect titles

- lib/core/src/lib/datatable/components/datatable/datatable.component.html
- lib/core/src/lib/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8955
Icons are centered …
> [ACS-8955] [ACA] Data Table / Column Pills Drag button is not centered horizontally

- lib/content-services/src/lib/search/components/search-text/search-text.component.html
- lib/content-services/src/lib/search/components/search-text/search-text.component.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8921
Filter is fixed
**Does …
> [ACS-8921][ACA] Data Table / The input field in "Filter by Name" dialog is enormous in comparison with the UI design

- lib/content-services/src/lib/common/services/saved-searches.service.spec.ts
- lib/content-services/src/lib/common/services/saved-searches.service.ts
- lib/content-services/src/lib/search/services/base-query-builder.service.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8991
Saved searches may run …
> [ACS-8991] Saved searches potential file conflict fix

- lib/core/src/lib/form/components/widgets/core/container.model.spec.ts
- lib/core/src/lib/form/components/widgets/core/container.model.ts
- lib/core/src/lib/form/components/widgets/header/header.widget.html
- lib/core/src/lib/form/components/widgets/header/header.widget.spec.ts
- lib/core/src/lib/form/components/widgets/header/header.widget.ts
> - [ ] Bugfix
Header is always visible.
Header can be optional. …
> AAE-28106 Make the header ( label + style ) optional with a checkbox [Preview/Runtime display]

- lib/process-services-cloud/src/lib/models/filter-cloud-model.ts
- lib/process-services-cloud/src/lib/models/task-list-sorting.model.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
- lib/process-services-cloud/src/lib/process/process-list/models/process-list-sorting.model.ts
- lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-25145
Sorting using process …
> AAE-25145 Sort process and task lists by process variables

- lib/process-services-cloud/src/lib/common/public-api.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
- lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
> AAE-25144 Process variables filters

- lib/core/src/lib/dialogs/unsaved-changes-dialog/unsaved-changes-dialog.component.scss
- lib/core/src/lib/dialogs/unsaved-changes-dialog/unsaved-changes-dialog.model.ts
- lib/core/src/lib/dialogs/unsaved-changes-dialog/unsaved-changes.guard.spec.ts
- lib/core/src/lib/dialogs/unsaved-changes-dialog/unsaved-changes.guard.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8999
New suggested label is …
> [ACS-8999] rename confirmation button label for closing conversation dialog

- lib/core/src/lib/form/components/form-field/form-field.component.spec.ts
- lib/core/src/lib/form/components/form-field/form-field.component.ts
- lib/core/src/lib/form/components/widgets/date-time/date-time.widget.ts
- lib/core/src/lib/form/components/widgets/date/date.widget.ts
- lib/core/src/lib/form/components/widgets/index.ts
- lib/core/src/lib/form/components/widgets/reactive-widget.interface.ts
- lib/core/src/lib/form/components/widgets/widget.component.ts
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
- lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
- lib/process-services/src/lib/form/widgets/dropdown/dropdown.widget.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-27343 …
> AAE-27343 Listen to form rules changes from reactive widgets

- lib/process-services-cloud/src/lib/i18n/en.json
- lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-29002 …
> AAE-29002 Allow to filter processes by parentId

- lib/content-services/src/lib/search/components/search-filter-tabbed/search-filter-tabbed.component.spec.ts
- lib/content-services/src/lib/search/components/search-filter-tabbed/search-filter-tabbed.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8918
Text is not sliding when …
> [ACS-8918] search date filter changing between created and modified tabs slides the text inside the tabs too

- lib/content-services/src/lib/content-node-selector/content-node-selector-panel/content-node-selector-panel.component.spec.ts
- lib/content-services/src/lib/content-node-selector/content-node-selector-panel/content-node-selector-panel.component.ts
> - [x] Bugfix
Copy/Move button is enabled if user switches from Personal Files to My Libraries via the dropdown in …
> [ACA-4556] Copy/Move button is now disabled on the My Libraries Page in Copy/Move dialog

- lib/cli/scripts/init-aps-env.ts
> - [x] Bugfix
Error in aps tenant creation is being swallowed without emitting any log about it …
> OPSEXP-2987 init-aps-env error reporting on tenant creation failure

- docs/process-services-cloud/components/process-list-cloud.component.md
- docs/process-services-cloud/components/task-list-cloud.component.md
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/services/cloud-token.service.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
> Change process and task search api selection from token-provided to input-provided

- lib/insights/src/lib/analytics-process/components/analytics-generator.component.spec.ts
- lib/insights/src/lib/analytics-process/components/analytics-generator.component.ts
- lib/insights/src/lib/analytics-process/components/analytics-report-heat-map.component.spec.ts
- lib/insights/src/lib/analytics-process/components/analytics-report-list.component.spec.ts
- lib/insights/src/lib/diagram/models/chart/bar-chart.model.ts
- lib/insights/src/lib/diagram/models/chart/pie-chart.model.ts
- lib/insights/src/lib/mock/analytics/analytics-component.mock.ts
- lib/insights/src/lib/mock/analytics/analytics-params-report-component.mock.ts
- lib/insights/src/lib/testing/insights.testing.module.ts
> - [x] Bugfix
- fix various Insights unit tests
- remove jasmine.Ajax where possible …
> [ACS-8771] bug fixes in insights, reduce jasmine.ajax

- lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-29384 …
> AAE-29384 Fix for process variable filtering

- lib/core/src/lib/auth/guard/auth-guard.service.spec.ts
- lib/core/src/lib/auth/guard/auth-guard.service.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/ACS-8961
onLogout is emitted when …
> [ACS-8961] Emit onLogout when redirected to login page

- lib/core/src/lib/notifications/components/notification-history.component.scss
> - [x] Bugfix
Notification bell was coming in black color after ng17 upgrade …
> [ACS-9084] Fixed incorrect color for notification bell icon

- lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
> - [x] Bugfix
People widget was not respecting the read only setting.
https://hyland.atlassian.net/browse/AAE-29299 …
> AAE-29299 Fix people widget read only

- lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts
> - [x] Bugfix
[AAE-15221](https://hyland.atlassian.net/browse/AAE-15221)
Allow …
> AAE-15221 Allow multiple roles when fetching deployed applications

- lib/core/src/lib/form/components/form-renderer.component.html
- lib/core/src/lib/form/components/widgets/core/form-field-types.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
- lib/core/src/lib/form/components/widgets/core/form-field.model.ts
> AAE-30066 Render sections in form builder

- docs/core/services/saved-searches.service.md
- lib/content-services/src/lib/common/services/saved-searches.service.spec.ts
- lib/content-services/src/lib/common/services/saved-searches.service.ts
- lib/js-api/src/api/content-rest-api/api/preferences.api.ts
- lib/js-api/src/api/content-rest-api/docs/PreferencesApi.md
> - [ ] Bugfix
Saved Searches will no longer be stored in configuration file in favor …
> [ACS-9166] Migrate Saved Searches to preferences API from config file

- docs/core/services/saved-searches.service.md
- lib/content-services/src/lib/common/services/saved-searches.service.spec.ts
- lib/content-services/src/lib/common/services/saved-searches.service.ts
- lib/js-api/src/api/content-rest-api/api/preferences.api.ts
- lib/js-api/src/api/content-rest-api/docs/PreferencesApi.md
Reverts Alfresco/alfresco-ng2-components#10559
> Revert "[ACS-9166] Migrate Saved Searches to preferences API from config file"

- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter/edit-service-task-filter-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter/edit-task-filter-cloud.component.spec.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-30162
If the taskFilter input …
> AAE-30162 Don't retreive task filter if present

- lib/core/src/lib/comments/comments.component.html
- lib/core/src/lib/comments/comments.component.scss
- lib/core/src/lib/comments/comments.component.spec.ts
- lib/core/src/lib/comments/comments.component.ts
- lib/core/src/lib/i18n/en.json
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-4749
Add button for comment is …
> [ACS-4749] add button is enabled for comment contains only spaces

- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
- lib/content-services/src/lib/content-metadata/services/basic-properties.service.ts
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.ts
- lib/core/src/lib/card-view/models/card-view-baseitem.model.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/ACS-8824
- Some forbidden symbols ignored by validator 
- Save …
> [ACS-8824] Disable node properties save button if values are invalid

- lib/core/src/lib/common/index.ts
- lib/core/src/lib/common/models/default-languages.model.ts
- lib/core/src/lib/common/services/user-preferences.service.spec.ts
- lib/core/src/lib/common/services/user-preferences.service.ts
- lib/core/src/lib/language-menu/service/language.service.ts
- lib/core/src/lib/layout/components/layout-container/layout-container.component.html
- lib/core/src/lib/layout/components/layout-container/layout-container.component.scss
> - [x] Bugfix
For right-to-left languages (such as arabic), textOrientation would get reset after browser refresh. …
> [ACS-9119] Fixed textOrientation getting reset on arabic after browser refresh

- lib/core/src/lib/form/components/widgets/date-time/date-time.widget.html
- lib/core/src/lib/form/components/widgets/date-time/date-time.widget.spec.ts
- lib/core/src/lib/form/components/widgets/date-time/date-time.widget.ts
- lib/core/src/lib/form/components/widgets/date/date.widget.html
- lib/core/src/lib/form/components/widgets/date/date.widget.spec.ts
- lib/core/src/lib/form/components/widgets/date/date.widget.ts
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.html
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.spec.ts
- lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-27984
fieldValueChanged is called on widget init as well as …
> AAE-27984 Fix fieldValueChanged called on init and blur for date widgets

- lib/content-services/src/lib/common/services/saved-searches.service.ts
> - [ ] Bugfix
[AAE-30901](https://hyland.atlassian.net/browse/AAE-30901)
**Does this …
> AAE-30901 Allow to use different saveSearch API service

- lib/content-services/src/lib/dialogs/folder/folder.dialog.spec.ts
- lib/content-services/src/lib/dialogs/folder/folder.dialog.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-9252 …
> [ACS-9252] Create Button Not Enabled After Resolving Duplicate Folder Name Warning

- lib/core/src/lib/styles/_components-variables.scss
- lib/core/src/lib/styles/_reference-variables.scss
- lib/process-services/src/lib/process-list/components/process-filters/process-filters.component.scss
- lib/process-services/src/lib/task-list/components/task-filters/task-filters.component.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-9225
Color contrast ratio for …
> [ACS-9225] serious a11y testing side bar elements must meet minimum color contrast ratio thresholds

- lib/core/src/lib/card-view/models/card-view-baseitem.model.spec.ts
- lib/core/src/lib/card-view/models/card-view-baseitem.model.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/MNT-24909
When property has a …
> [MNT-24909] Check if property constraint is handled by validators available in ADF

- lib/process-services-cloud/src/lib/form/components/widgets/display-rich-text/display-rich-text.widget.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters/process-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters/process-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters/task-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters/task-filters-cloud.component.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/AAE-31996
First time when the …
> AAE 31996 refresh button on filters not working as expected

- lib/core/src/lib/form/components/form-base.component.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
- lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
> - [] Docs have been added / updated (for bug fixes / features)
> - [x] Bugfix
A Start Process button is shown when the start event is a form, but it has custom required outcomes. …
> AAE-32255 Start Process button in start event is showing and failing for form with custom outcomes

- lib/process-services-cloud/src/lib/task/task-list/components/service-task-list/service-task-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/task/task-list/components/service-task-list/service-task-list-cloud.component.ts
- lib/process-services-cloud/src/lib/task/task-list/mock/fake-task-response.mock.ts
> - [x] Bugfix
[AAE-27160](https://hyland.atlassian.net/browse/AAE-27160)
Columns in the service task list cannot be sorted.  This is because the sortKey doesn't match column key since there is an additional layer in the data (`entry`).  Attempting to update the sortKey to match, for example `entry.startDate`, allows the columns to sort correctly, but API calls include `entry.startDate` as the column name in query parameters. …
> AAE-27160 Fix the structure of data returned from service-tasks API

- lib/content-services/src/lib/directives/library-favorite.directive.spec.ts
- lib/content-services/src/lib/directives/library-favorite.directive.ts
- lib/content-services/src/lib/directives/node-favorite.directive.spec.ts
- lib/content-services/src/lib/directives/node-favorite.directive.ts
- lib/content-services/src/lib/i18n/en.json
> - [ ] Bugfix
There are no notifications for favorite nodes directive.
Snackbar …
> [ACS-9398] Add snackbar notifications for favorite node directive

- lib/core/src/lib/viewer/components/viewer.component.html
- lib/core/src/lib/viewer/components/viewer.component.scss
- lib/core/src/lib/viewer/components/viewer.component.spec.ts
- lib/core/src/lib/viewer/components/viewer.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-5190
Document's name is trimmed …
> [ACS-5190] document name text alignement and long name trim issue

- lib/core/src/lib/common/services/storage.service.spec.ts
- lib/core/src/lib/common/services/storage.service.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
- lib/process-services-cloud/src/lib/services/local-preference-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/services/local-preference-cloud.service.ts
> - [x] Bugfix
The local storage is provided, the used method only works for the user cloud storage. I adjusted …
> AAE-32763 Custom column visibility is not persistent after refresh

- docs/core/components/viewer-render.component.md
- docs/core/components/viewer.component.md
- docs/core/services/process-content.service.md
- lib/core/src/lib/form/components/widgets/core/content-link.model.ts
- lib/core/src/lib/viewer/components/unknown-format/unknown-format.component.html
- lib/core/src/lib/viewer/components/unknown-format/unknown-format.component.spec.ts
- lib/core/src/lib/viewer/components/unknown-format/unknown-format.component.ts
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.html
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.ts
- lib/core/src/lib/viewer/components/viewer.component.html
- lib/core/src/lib/viewer/components/viewer.component.ts
- lib/process-services/src/lib/form/services/process-content.service.spec.ts
- lib/process-services/src/lib/form/services/process-content.service.ts
- lib/process-services/src/lib/form/widgets/document/content.widget.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-9406 …
> [ACS-9406] Add getContentRenditionTypePreview to process-content service

- lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
- lib/content-services/src/lib/search/components/search.component.html
> - [ ] Bugfix
> - [X] Other... Please describe: a11y
https://hyland.atlassian.net/browse/ACS-9435
**Does this PR …
> [ACS-9435] Resolve a11y issues for 'Add use/group' dialog

- docs/process-services/services/task-filter.service.md
- lib/process-services/src/lib/task-list/components/task-filters/task-filters.component.spec.ts
- lib/process-services/src/lib/task-list/components/task-filters/task-filters.component.ts
- lib/process-services/src/lib/task-list/services/task-filter.service.spec.ts
- lib/process-services/src/lib/task-list/services/task-filter.service.ts
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-9552
Involved filter has been …
> [ACS-9552] Add obsolete task list filters migration

- lib/core/src/lib/form/components/form-renderer.component.html
- lib/core/src/lib/form/components/form-renderer.component.spec.ts
- lib/core/src/lib/form/components/mock/form-renderer.component.mock.ts
- lib/process-services/src/lib/form/widgets/dynamic-table/dynamic-table.widget.spec.ts
- lib/process-services/src/lib/form/widgets/dynamic-table/dynamic-table.widget.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/MNT-24715
The form with dynamic table is not rendered in ADW at …
> [MNT-24715] App with APS does not show display value of dynamic table

- lib/core/src/lib/datatable/components/datatable/datatable.component.html
> - [ ] Bugfix
Accessibility issue
Checkboxes for selecting files in datatable.component were giving an accessibility …
> [ACS-9227] Fixed interactive controls must not be nested issue in datatable.component.html

- lib/content-services/src/lib/search-ai/services/search-ai.service.spec.ts
- lib/js-api/src/api/content-rest-api/docs/SearchAiApi.md
- lib/js-api/src/api/content-rest-api/model/aiAnswerObjectReference.ts
- lib/js-api/src/api/content-rest-api/model/aiAnswerReference.ts
- lib/js-api/src/api/content-rest-api/model/index.ts
- lib/js-api/test/content-services/searchAiApi.spec.ts
- lib/js-api/test/mockObjects/content-services/search-ai.mock.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-9564
Models are changed to …
> [ACS-9564] Corrected models after change of Knowledge Retrieval answer structure

- lib/process-services-cloud/src/lib/task/task-form/components/user-task-cloud/user-task-cloud.component.html
- lib/process-services-cloud/src/lib/task/task-form/components/user-task-cloud/user-task-cloud.component.spec.ts
> - [x] Bugfix
Checkbox is shown on claim task screen.
https://hyland.atlassian.net/browse/AAE-34478
**What is the …
> AAE-34478 Hide "open next task" checkbox on claim screen

- lib/core/feature-flags/src/lib/services/debug-features.service.spec.ts
- lib/core/feature-flags/src/lib/services/debug-features.service.ts
- lib/core/feature-flags/src/lib/services/storage-features.service.spec.ts
- lib/core/feature-flags/src/lib/services/storage-features.service.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-19688
StorageFeaturesService …
> AAE-19688 Persist feature flag overrides in session storage

- lib/core/src/lib/app-config/app-config.loader.spec.ts
- lib/core/src/lib/app-config/app-config.loader.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-34959
If the identity provider …
> AAE-34959 Fix Application CORS issue if withCredentials equal to true

- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters/process-filters-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/process/process-filters/components/process-filters/process-filters-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
- lib/process-services-cloud/src/lib/task/task-filters/components/task-filters/task-filters-cloud.component.spec.ts
https://hyland.atlassian.net/browse/AAE-34365
> - [X] Bugfix
In workspace we are showing different counters. Currently we are displaying counters for e.g. "Completed …
> AAE-34656 Hide all counters in Workspace which do not provide value

- lib/core/src/lib/form/components/form-renderer.component.html
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.html
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.spec.ts
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.ts
This reverts commit 413fce8cb73f01a28023f76284fec2b27102dd1e.
> - [ ] Bugfix
Reverting …
> Revert "AAE-34641 Refactor viewer-render loading (#10868)"

- docs/content-services/components/alfresco-viewer.component.md
- docs/core/components/viewer-render.component.md
- docs/core/components/viewer.component.md
- lib/core/src/lib/viewer/components/txt-viewer/txt-viewer.component.spec.ts
- lib/core/src/lib/viewer/components/txt-viewer/txt-viewer.component.ts
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.html
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.spec.ts
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.ts
- lib/extensions/src/lib/components/viewer/preview-extension.component.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-35649
Now viewer renderer …
> [AAE-35649] Viewer renderer wait until subsequent renderers will finish

- lib/core/src/lib/i18n/en.json
- lib/core/src/lib/viewer/components/pdf-viewer/pdf-viewer.component.html
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.html
Improves accessibility by adding screen reader support to loading indicators.
This ensures that users with disabilities are informed when the document is loading, improving the overall user experience.
> - [ ] Bugfix
> - [ ] …
> AAE-35728 Add aria-label to viewer loading bars

- lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
- lib/content-services/src/lib/aspect-list/aspect-list.component.ts
- lib/content-services/src/lib/aspect-list/interfaces/custom-aspect-paging.interface.ts
- lib/content-services/src/lib/aspect-list/public-api.ts
- lib/content-services/src/lib/aspect-list/services/aspect-list.service.spec.ts
- lib/content-services/src/lib/aspect-list/services/aspect-list.service.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/MNT-24459
Now when there are still …
> [MNT-24459] Aspect list get all aspects when not all were fetched by first call

- lib/content-services/src/lib/category/categories-management/categories-management.component.html
- lib/content-services/src/lib/category/categories-management/categories-management.component.spec.ts
- lib/content-services/src/lib/category/categories-management/categories-management.component.ts
- lib/content-services/src/lib/i18n/en.json
> - [X] Bugfix
https://hyland.atlassian.net/browse/ACS-9327
Added prohibited symbols …
> [ACS-9327] Add prohibited symbols validation for Categories dialog

- lib/core/src/lib/viewer/components/img-viewer/img-viewer.component.scss
- lib/core/src/lib/viewer/components/unknown-format/unknown-format.component.scss
- lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.scss
- lib/core/src/lib/viewer/components/viewer.component.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-36397
Image is no longer …
> [AAE-36397] ADF viewer image is no longer cropped

- lib/content-services/src/lib/version-manager/version-list.component.scss
> - [x] Bugfix
When the adf-version-list component is used outside of a dialog, the version list is not visible. …
> [ADF-5583] Update style to make version visible outside dialog

- lib/core/src/lib/translation/provide-i18n.ts
- lib/core/src/lib/translation/public-api.ts
https://hyland.atlassian.net/browse/AAE-36615
new top-level standalone provider api
Before
```typescript
provideTranslateService({
loader: {
provide: TranslateLoader,
useExisting: TranslateLoaderService,
deps: [HttpClient],
},
defaultLanguage: 'en',
}),
provideTranslations('app', 'resources'),
provideTranslations('shared-identity', `assets/shared-identity`),
provideTranslations('shared-filters-smart', `resources/shared/filters/smart`),
```
After
```typescript
provideI18N({
defaultLanguage: 'en',
assets: [
['app', 'resources'],
['shared-identity', `assets/shared-identity`],
['shared-filters-smart', `resources/shared/filters/smart`]
]
})
```
> AAE-36615 new provideI18N api

- lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.html
- lib/content-services/src/lib/search/components/search-check-list/search-check-list.component.spec.ts
- lib/core/src/lib/testing/unit-testing-utils.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7266
Checkboxes are before …
> [ACS-7266] checkboxes in sorting boxes are put on the right side of the text instead of the left side

- lib/extensions/src/lib/providers.ts
- lib/extensions/src/lib/services/component-register.service.ts
- lib/extensions/src/lib/services/extension.service.ts
- lib/extensions/src/lib/services/rule.service.ts
https://hyland.atlassian.net/browse/AAE-37287
Introduce a `provideExtensions` helper API to reduce code related to extension configuration
```typesript 
providers: [
provideExtensions({
authGuards: {
auth1: guard1,
auth2: guard2
},
evaluators: {
eval1: evaluator1,
eval2: evaluator2
},
components: {
component: component1
}
});
]
```
> AAE-37287 provideExtensions provider api for Angular standalone

- lib/core/src/lib/datatable/components/datatable/datatable.component.scss
> - [x] Bugfix
[[ADW][ACA][ACC] – Dragging a column header hides the headers to its …
> [ACS-9986] [ADW][ACA][ACC] – Dragging a column header hides the headers to its right.

- lib/content-services/src/lib/common/services/people-content.service.spec.ts
- lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
- lib/content-services/src/lib/content-metadata/services/content-metadata.service.spec.ts
- lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.spec.ts
- lib/content-services/src/lib/security/services/security-controls-groups-marks-security.service.spec.ts
- lib/content-services/src/lib/tag/services/tag.service.spec.ts
- lib/core/api/src/lib/adf-http-client.service.ts
- lib/core/src/lib/auth/mock/identity-user.service.mock.ts
- lib/core/src/lib/auth/oidc/auth-config.service.spec.ts
- lib/core/src/lib/auth/oidc/auth-config.service.ts
- lib/core/src/lib/auth/oidc/oidc-authentication.service.spec.ts
- lib/core/src/lib/auth/oidc/redirect-auth.service.spec.ts
- lib/core/src/lib/auth/services/identity-user.service.ts
- lib/core/src/lib/auth/services/time-sync.service.spec.ts
- lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
- lib/process-services-cloud/src/lib/form/services/content-cloud-node-selector.service.ts
- lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
- lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
- lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
- lib/process-services-cloud/src/lib/task/task-form/components/user-task-cloud-buttons/claim-task/claim-task-cloud.directive.ts
- lib/process-services-cloud/src/lib/task/task-form/components/user-task-cloud-buttons/unclaim-task/unclaim-task-cloud.directive.ts
- lib/process-services-cloud/src/lib/task/task-form/components/user-task-cloud/complete-task/complete-task.directive.ts
- lib/process-services-cloud/src/lib/task/task-list/services/service-task-list-cloud.service.spec.ts
- lib/process-services/src/lib/form/widgets/functional-group/functional-group.widget.spec.ts
> - [ ] Bugfix
The deprecated `toPromise()` method is still used in multiple parts of the codebase …
> AAE-35340 Replace deprecated toPromise() usages with firstValueFrom / lastValueFrom

- lib/core/api/src/lib/alfresco-api/alfresco-api.utils.spec.ts
- lib/core/api/src/lib/alfresco-api/alfresco-api.utils.ts
> - [X] Bugfix
https://hyland.atlassian.net/browse/MNT-25274
Multi-valued properties uploaded as a single string …
> [MNT-25274] Fixed issue while uploading files with multi-valued properties

- lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
- lib/process-services-cloud/src/lib/form/components/form-cloud.component.scss
> - [ ] Bugfix
> - [x] Other... Please describe: CSS fix.
When opening a form in fullscreen with a toolbar on top, there's extra padding on top of the …
> AAE-37563 Fix for extra padding on top of fullscreen toolbar

- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.html
- lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
- lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
- lib/core/src/lib/styles/_mat-selectors.scss
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-10145
Size of font and …
> [ACS-10145] Corrected font size and alignment for date field in metadata properties panel

- lib/content-services/src/lib/search/services/base-query-builder.service.ts
- lib/content-services/src/lib/search/services/search-header-query-builder.service.spec.ts
- lib/content-services/src/lib/search/services/search-query-builder.service.spec.ts
> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-10384
Search doesn't throw …
> [ACS-10384] after recent changes search query builder can t process non latin characters
