lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.scss
lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-7666 …

[AAE-7666] Add error message when REST API fails for radio buttons

---

e2e/core/pages/comments.page.ts
e2e/process-services/pages/process-details.page.ts
e2e/process-services/pages/task-details.page.ts
lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.scss
lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.html
lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.html
lib/core/src/lib/comments/comment-list.component.html
lib/core/src/lib/comments/comment-list.component.spec.ts
lib/core/src/lib/comments/comments.component.html
lib/core/src/lib/comments/comments.component.scss
lib/core/src/lib/comments/comments.component.spec.ts
lib/core/src/lib/i18n/en.json
lib/process-services/src/lib/process-comments/process-comments.component.spec.ts
lib/testing/src/lib/protractor/core/pages/card-view/card-view-date-item.page.ts
lib/testing/src/lib/protractor/process-services/pages/start-process.page.ts

> - [x] Bugfix
Accessibility issues for metadata sidebar related with heading, missing aria-labels, missing labels …

ACS-3545 a 11 y aca metadata sidebar

---

.travis.yml
scripts/travis/release/release-demoshell-docker.sh
scripts/travis/release/release-storybook-docker.sh

Pipeline - Split the build from release

---

.travis.yml
demo-shell/src/index.html

[AAE-11279] Pipeline - Build libs and apps in the same stage and avoid install

---

.travis.yml
demo-shell/src/index.html

Use npm bin/nx

---

.travis.yml

Run release only on merge and upstream on cron

---

demo-shell/src/app/components/about/about.component.html
demo-shell/src/app/components/about/about.component.scss
demo-shell/src/app/components/about/about.component.ts
docs/core/components/about.component.md
lib/core/src/lib/about/about-package/package-list.component.ts
lib/core/src/lib/about/about-panel.directive.ts
lib/core/src/lib/about/about-repository-info/about-repository-info.component.html
lib/core/src/lib/about/about-repository-info/about-repository-info.component.ts
lib/core/src/lib/about/about-repository-info/repository-info.interface.ts
lib/core/src/lib/about/about.component.html
lib/core/src/lib/about/about.module.ts
lib/core/src/lib/about/public-api.ts

> - [ ] Bugfix
About has a lot of various ECM/BPM dependencies and cannot be easily used in various apps and …

[AAE-10766] presentational and reusable About

---

demo-shell/src/app/components/cloud/community/community-start-process-cloud.component.ts
demo-shell/src/app/components/cloud/community/community-start-task-cloud.component.ts
demo-shell/src/app/components/file-view/file-view.component.ts
demo-shell/src/app/components/files/version-manager-dialog-adapter.component.ts
docs/README.md
docs/core/components/snackbar-content.component.md
docs/core/components/snackbar-content.md
docs/core/services/notification.service.md
docs/versionIndex.md
e2e/core/pages/notification.page.ts
lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.spec.ts
lib/content-services/src/lib/upload/components/upload-drag-area.component.ts
lib/core/src/lib/core.module.ts
lib/core/src/lib/i18n/en.json
lib/core/src/lib/notifications/components/notification-history.component.spec.ts
lib/core/src/lib/notifications/services/notification.service.spec.ts
lib/core/src/lib/notifications/services/notification.service.ts
lib/core/src/lib/snackbar-content/index.ts
lib/core/src/lib/snackbar-content/public-api.ts
lib/core/src/lib/snackbar-content/snack-bar-data.ts
lib/core/src/lib/snackbar-content/snackbar-content.component.html
lib/core/src/lib/snackbar-content/snackbar-content.component.scss
lib/core/src/lib/snackbar-content/snackbar-content.component.spec.ts
lib/core/src/lib/snackbar-content/snackbar-content.component.ts
lib/core/src/lib/snackbar-content/snackbar-content.module.ts
lib/core/src/public-api.ts
lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
lib/testing/src/lib/protractor/core/pages/snackbar.page.ts

> - [x] Bugfix
Some snackbars were autoclosing very quickly and there was not way to close it manually which caused …

ACS-3640 a 11 y aca 881740 snackbar messages disappear without option to adjust timing

---

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.scss
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts

> - [ ] Bugfix
[AAE-11319](https://alfresco.atlassian.net/browse/AAE-11319)
Added …

[AAE-11319] start process loading spinner

---

lib/content-services/src/lib/content-node-selector/content-node-selector.component.spec.ts
lib/content-services/src/lib/content-node-selector/content-node-selector.component.ts
lib/content-services/src/lib/new-version-uploader/new-version-uploader.service.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-3888
Correct role is applied …

[ACS-3888] Correct role for new version dialog

---

lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.html
lib/content-services/src/lib/aspect-list/aspect-list.component.html
lib/content-services/src/lib/aspect-list/services/dialog-aspect-list.service.ts

> - [x] Bugfix
There are some accessibility issues
1. Form elements must have labels
2. Banner landmark should not be …

[ACS-3863] Edit aspect dialog accessibility issues

---

e2e/process-services/pages/task-details.page.ts
lib/content-services/src/lib/breadcrumb/breadcrumb.component.html
lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
lib/content-services/src/lib/i18n/en.json
lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
lib/content-services/src/lib/search/components/search.component.html
lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
lib/core/src/lib/comments/comments.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.html

Accessibility issues present
Accessibility issues fixed
**Does this …

[ACS-3548] Accessibility issues

---

lib/core/src/lib/icon/icon.component.html
lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
lib/process-services/src/lib/content-widget/attach-file-widget.component.html
lib/testing/src/lib/protractor/core/pages/form/widgets/attach-file-widget.page.ts

> - [x] Bugfix
Some duplicated ids exists check: https://alfresco.atlassian.net/browse/ACS-3658 …

[ACS-3658] Fix duplicated ids

---

lib/process-services-cloud/src/lib/form/components/widgets/attach-file/file-properties-table-cloud.component.html
lib/process-services/src/lib/content-widget/attach-file-widget.component.html
lib/process-services/src/lib/i18n/en.json

Buttons does not have discernible text
Buttons have discernible text, …

[ACS-4051] 880283, 880284, 880285 Critical CSV issues buttons must have discernible text fixed

---

lib/content-services/src/lib/i18n/en.json
lib/content-services/src/lib/upload/components/file-uploading-dialog.component.html
lib/content-services/src/lib/upload/components/file-uploading-list-row.component.html
lib/content-services/src/lib/upload/components/file-uploading-list-row.component.spec.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-3791
Corrected labels for …

[ACS-3791] Renaming labels for uploader screen

---

lib/content-services/src/lib/content-node-share/content-node-share.dialog.html

…essed
Function cannot be performed by keyboard alone
Function can be …

[ACS-4051] CSV issues 880196 Function cannot be performed by keyboard alone addressed

---

lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.html
lib/process-services-cloud/src/lib/i18n/en.json
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
lib/process-services/src/lib/process-list/components/start-process.component.html

[ACS-4050]critical issues from csv 880282, 880449, 880280

---

lib/process-services/src/lib/content-widget/attach-file-widget.component.html
lib/process-services/src/lib/process-list/components/start-process.component.html

> - [x] Bugfix
Start process page Issues resolved from csv file issue ID 880320,880281 …

[ACS-3553] Fix process page accessibility from csv(880320,880281)

---

lib/process-services/src/lib/content-widget/attach-file-widget.component.html
lib/process-services/src/lib/process-list/components/start-process.component.html

Reverts Alfresco/alfresco-ng2-components#8017

Revert "[ACS-3553] Fix process page accessibility from csv(880320,880281)"

---

lib/extensions/src/lib/config/navbar.extensions.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-11418
**Does this PR …

[AAE-11418] Add missing rules prop to NavBar interfaces

---

lib/core/src/lib/form/components/form-renderer.component.spec.ts
lib/core/src/lib/form/components/mock/form-renderer.component.mock.ts
lib/core/src/lib/form/components/widgets/amount/amount.widget.spec.ts
lib/core/src/lib/form/components/widgets/date/date.widget.spec.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-11653 …

[AAE-11653] Automate part of ADF Form Widgets

---

docs/upgrade-guide/upgrade50-60.md

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-11695
**Does this PR …

[AAE-11695] add breaking changes notes

---

docs/upgrade-guide/upgrade50-60.md
lib/core/src/lib/models/pagination.model.ts
lib/core/src/lib/pagination/infinite-pagination.component.spec.ts
lib/core/src/lib/pagination/infinite-pagination.component.ts
lib/core/src/lib/pagination/pagination.component.spec.ts

> - [ ] Bugfix
remove js-api dependency for pagination …

[AAE-10775] remove js-api dependency for pagination

---

.editorconfig
.github/actions/before-install/action.yml
.github/actions/download-build-artifacts/action.yml
.github/actions/e2e/action.yml
.github/actions/get-latest-tag-sha/action.yml
.github/actions/setup/action.yml
.github/actions/travis-env-var-facade/action.yml
.github/actions/upload-build-artifacts/action.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
e2e/protractor/save-remote.js
lib/cli/scripts/docker.ts
lib/cli/scripts/npm-publish.ts
scripts/ci/job_hooks/after_e2e.sh
scripts/ci/job_hooks/before_e2e.sh
scripts/ci/job_hooks/before_install.sh
scripts/ci/partials/_ci-flags-parser.sh
scripts/travis/affected-contains.sh
scripts/travis/e2e/e2e.sh
scripts/travis/release/docker-tag.sh
scripts/travis/release/release-demoshell-docker.sh
scripts/travis/release/release-npm.sh
scripts/travis/release/release-storybook-docker.sh

****Please check if the PR fulfills these requirements**
> - [ ] Bugfix
> - [ x] Feature
> …

[AAE-7986] Migrate ADF from Travis to Github actions

---

.github/workflows/pull-request.yml

[AAE-11822] fix/build-demoshell

---

.github/workflows/pull-request.yml
.github/workflows/release.yml

[AAE-11822] fix demoshell

---

lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-11714
(cropped image)
Image …

AAE-11714 changed max-width for cropped image

---

scripts/ci/job_hooks/before_install.sh

> - [x] Bugfix
this commit fixes the COMMIT_MESSAGE in case of "*" and "\n" newlines …

[AAE-11843]-fix-before_install_script

---

.vscode/extensions.json

> - [ ] Bugfix
Added a karma test explorer plugin suggestion for the VS Code workspace …

[AAE-11727] add suggested karma test explorer plugin

---

.github/workflows/release.yml

fixed release

---

lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.spec.ts
lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
lib/process-services-cloud/src/lib/services/base-cloud.service.ts

> - [ ] Bugfix
Process variables being sent as query parameters in admin app.
Process …

[AAE-11588] Send Process Variables as a post body in admin process instances

---

lib/content-services/karma.conf.js
lib/content-services/src/lib/social/rating.component.spec.ts
lib/content-services/src/lib/testing/content.testing.module.ts
lib/content-services/src/lib/version-manager/version-list.component.spec.ts
lib/content-services/src/lib/version-manager/version-list.component.ts

> - [x] Bugfix
- fix image setup for karma to avoid 404 errors for icons
- setup …

[AAE-10319] unit test fixes for content-services lib

---

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-11740
We are starting process …

[AAE-11740] replaced api for starting process

---

lib/core/src/lib/directives/tooltip-card/tooltip-card.directive.spec.ts
lib/core/src/lib/login/components/login.component.spec.ts
lib/core/src/lib/login/components/login.component.ts
lib/core/src/lib/userinfo/components/user-info.component.spec.ts

> - [x] Bugfix
- fix errors in the Login unit tests
- fix errors in the User Info unit …

[AAE-10315] fix karma 404 for images and certain errors in the Core unit tests

---

demo-shell/src/app/components/document-list/extension-presets/name-column/name-column.component.ts
docs/upgrade-guide/upgrade50-60.md
lib/content-services/src/lib/aspect-list/services/node-aspect.service.spec.ts
lib/content-services/src/lib/aspect-list/services/node-aspect.service.ts
lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
lib/content-services/src/lib/document-list/components/library-name-column/library-name-column.component.ts
lib/content-services/src/lib/document-list/components/library-role-column/library-role-column.component.ts
lib/content-services/src/lib/document-list/components/library-status-column/library-status-column.component.ts
lib/content-services/src/lib/document-list/components/name-column/name-column.component.ts
lib/content-services/src/lib/version-manager/version-manager.component.spec.ts
lib/content-services/src/lib/version-manager/version-manager.component.ts
lib/core/src/lib/datatable/components/datatable-cell/datatable-cell.component.ts
lib/core/src/lib/datatable/components/date-cell/date-cell.component.ts
lib/core/src/lib/datatable/components/filesize-cell/filesize-cell.component.ts
lib/core/src/lib/datatable/components/json-cell/json-cell.component.ts
lib/core/src/lib/datatable/components/location-cell/location-cell.component.ts
lib/core/src/lib/services/alfresco-api.service.ts
lib/core/src/lib/services/nodes-api.service.ts
lib/core/src/lib/viewer/components/viewer.component.spec.ts
lib/core/src/lib/viewer/components/viewer.component.ts

> - [ ] Bugfix
moce nodeudpate from alfrescoapiservice to nodesapiservice
**Does this …

[AAE-11486] move NodeUdpdate in nodeapiservice

---

.github/workflows/adf_alpha.yml
.github/workflows/cron.yml

> - [ ] Bugfix
task: https://alfresco.atlassian.net/browse/AAE-11910
1. [cron workflow …

AAE-11910 - setup cron pipe to trigger alpha_adf and add a workflow_dispatch to execute manually adf tests

---

.github/workflows/adf_alpha.yml
.github/workflows/cron.yml

AAE-11910 - cron schedule fix

---

lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-11810
Added conditional class …

AAE-11810 added conditional class to indicate validation error

---

.github/actions/before-install/action.yml
.github/actions/e2e/action.yml
.github/actions/setup/action.yml
.github/actions/travis-env-var-facade/action.yml
.github/workflows/release.yml

[ci:force] test
[affected:pippo] ciao
[affected:*] test
refactor
> - [ ] Bugfix
**Does …

[AAE-11817]-bugfix-on-gh-action-envvar

---

.github/actions/before-install/action.yml

[AAE-11817]-release-fix

---

.github/actions/setup/action.yml
.github/workflows/adf_alpha.yml
.github/workflows/cron.yml
scripts/travis/update/update-project.sh

> - [ ] Bugfix
adf-test script fixed and add a dry-run to keep the env safe.
[without …

AAE-11940 - fix alpha adf test in cron workflow

---

.github/actions/before-install/action.yml

[AAE-11817]-release fix if condition

---

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts
lib/process-services-cloud/src/lib/process/start-process/models/process-instance-cloud.model.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4647
Values from form are …

[ACA-4647] Fix for e2e

---

scripts/travis/release/release-npm.sh

[AAE-12054] publish on npm alpha tag

---

.github/workflows/adf_alpha.yml
.github/workflows/pull-request.yml
docker/build.sh

AAE-11940 - npm err fix in trigger-adf workflow

---

.github/workflows/git-tag.yml
scripts/travis/release/git-tag.sh

> - [ ] Bugfix
github action to release a git tag on master branch after push event …

AAE-12037 git-tag stage

---

.github/workflows/pull-request.yml
angular.json
lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.stories.ts

[AAE-1274] CI opt - Build only core/content/process storybook

---

.github/workflows/pull-request.yml

[AAE-12057] unit tests: force e2e only after build-libs, lint, unit-tests

---

.github/actions/travis-env-var-facade/action.yml

[AAE-12123] env var interpolation bugfix

---

docs/content-services/services/tag.service.md
lib/content-services/src/lib/tag/services/tag.service.spec.ts
lib/content-services/src/lib/tag/services/tag.service.ts
package-lock.json
package.json

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-4118
Added functions to …

[ACS-4118] create a tag from tags list

---

.github/workflows/adf_alpha.yml
.github/workflows/pull-request.yml

AAE-12046 - add pre-condition on approval

---

.github/workflows/pull-request.yml

[AAE-12057] add description to unit tests

---

.github/actions/setup/action.yml
.github/workflows/pull-request.yml
e2e/content-services/upload/version-actions.e2e.ts
e2e/protractor.excludes.json

> - [ ] Bugfix
> - [x] Other... Please describe: enable excluded e2e
as the issue was fixed, we forgot to enable test …

enable e2e: C260040

---

angular.json
lib/config/index.js
lib/config/webpack.style.js

[AAE-12124] Use a function to remove js files

---

lib/content-services/src/lib/node-comments/node-comments.component.ts
lib/content-services/src/lib/node-comments/node-comments.module.ts
lib/process-services/src/lib/task-comments/task-comments.component.ts
lib/process-services/src/lib/task-comments/task-comments.module.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACA-4650
Comments can be added …

[ACA-4650] Use NodeCommentsService for ADF_COMMENTS_SERVICE

---

.github/workflows/codeql-analysis.yml

> - [ ] Bugfix
The CodeQL analysis v1 will be deprecated - …

[ACS-4413] Upgrade CodeQL analysis to v2

---

lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter-cloud.component.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-12239
**Does this PR …

AAE-12239: Managed to populate processInstanceId in service tasks filters

---

lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.spec.ts
lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-12063
Method and relevant …

AAE-12063 removed startCreatedProcess with relevant unit tests

---

e2e/protractor.excludes.json
lib/core/src/lib/services/thumbnail.service.spec.ts
lib/core/src/lib/services/thumbnail.service.ts

> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-10979
**Does this PR …

AAE-10979: Added support to display html icon for mht file format

---

lib/core/src/lib/form/components/form-base.component.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.spec.ts
lib/process-services-cloud/src/lib/task/directives/claim-task-cloud.directive.spec.ts
lib/process-services-cloud/src/lib/task/directives/claim-task-cloud.directive.ts
lib/process-services-cloud/src/lib/task/directives/complete-task.directive.spec.ts
lib/process-services-cloud/src/lib/task/directives/complete-task.directive.ts
lib/process-services-cloud/src/lib/task/directives/unclaim-task-cloud.directive.spec.ts
lib/process-services-cloud/src/lib/task/directives/unclaim-task-cloud.directive.ts
lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.spec.ts

> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-8306 …

[AAE-8306] - Managed to disable complete/claim/release buttons on first click

---

lib/cli/scripts/changelog.ts

[AAE-11708] Fix changelog author filtering programatically

---

lib/core/src/lib/snackbar-content/snackbar-content.component.html

> - [X] Bugfix
snackbar messages were read by screen readers 
Exclue snackbar messages …

[ACS-4282] [ACS-4271] [ACS-4298] [ACS-4327] [ACS-4328] Exclue snackbar from screen reader

---

.github/workflows/pull-request.yml

> - [ ] Bugfix
updated unit test name in pr pipeline …

AAE-12357: update unit test name

---

.github/workflows/pull-request.yml

AAE-12412 - dependabot actor check

---

.github/workflows/pull-request.yml

[AAE-12412] alfresco-build user whitelisted

---

lib/extensions/src/lib/services/extension.service.spec.ts
lib/extensions/src/lib/services/extension.service.ts

Added possibility to subscribe on extension config file loading.
> - [ ] Bugfix
Allow …

[AAE-12146] Update getFeature typings

---

.github/actions/setup/action.yml
.github/workflows/release.yml
scripts/next_version.sh

AAE-12452 - Version published in NPM should have PR number id in the name not gh-run_id

---

lib/content-services/src/lib/i18n/en.json
lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.html

Reverts Alfresco/alfresco-ng2-components#8213

Revert "[ACS-4307] Label is not persistent as placeholder is being used as the only visual label for a text field"

---

docs/content-services/services/tag.service.md
lib/content-services/src/lib/tag/services/tag.service.spec.ts
lib/content-services/src/lib/tag/services/tag.service.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-4296
There is no duplicated …

[ACS-4296] changes required after removing tags service from apps

---

lib/core/src/lib/layout/components/header/header.component.html

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-4274
Title has marked as …

[ACS-4274] Add role heading and aria level in header template

---

.github/workflows/pull-request.yml

devel: schedule check

---

demo-shell/src/app.config.json
lib/process-services-cloud/src/lib/i18n/en.json

> - x ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-3136 …

[AAE-12249] add description field

---

e2e/protractor.excludes.json
lib/content-services/src/lib/tag/services/tag.service.spec.ts
lib/content-services/src/lib/tag/services/tag.service.ts

> - [ ] Bugfix
searchTags function returns observable for ResultSetPaging. 
searchTags …

[ACS-4296] adding mapping in tags service

---

.github/actions/e2e/action.yml
.github/workflows/pull-request.yml

AAE-12192 - adding upload artifacts action

---

lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.ts

[AAE-12260] - fixing form field mapping

---

lib/core/package.json
package-lock.json
package.json

> - [ ] Bugfix
Upgrade to latest editorjs to fix the issue with the cypress dependency …

upgrade js-editor to drop cypress dependency

---

lib/core/shell/src/lib/components/shell/shell.component.html
lib/core/shell/src/lib/components/shell/shell.component.ts
lib/core/shell/src/lib/services/shell-app.service.ts

> - [ ] Bugfix
extra configuration support for shell navbar to allow applications …

[ACS-3742] extra cfg support for shell navbar

---

demo-shell/src/custom-style-dev.scss
lib/core/src/lib/styles/_index.scss
lib/core/src/lib/styles/prebuilt/adf-blue-orange.scss
lib/core/src/lib/styles/prebuilt/adf-blue-purple.scss
lib/core/src/lib/styles/prebuilt/adf-cyan-orange.scss
lib/core/src/lib/styles/prebuilt/adf-cyan-purple.scss
lib/core/src/lib/styles/prebuilt/adf-green-orange.scss
lib/core/src/lib/styles/prebuilt/adf-green-purple.scss
lib/core/src/lib/styles/prebuilt/adf-indigo-pink.scss
lib/core/src/lib/styles/prebuilt/adf-pink-bluegrey.scss
lib/core/src/lib/styles/prebuilt/adf-purple-green.scss

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-12668
**Does this PR …

[AAE-12668] refactored typography for themes

---

.github/actions/travis-env-var-facade/action.yml
.github/workflows/adf_alpha.yml
scripts/travis/update/update-project.sh

Being able to upstream alfresco-apps or alfresco-applications

---

docs/user-guide/theming.md
docs/user-guide/typography.md

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-12716
Documentation has been …

AAE-12716 updated the typography documentation

---

demo-shell/karma.conf.js
lib/content-services/karma.conf.js
lib/core/karma.conf.js
lib/core/src/lib/clipboard/clipboard.service.spec.ts
lib/extensions/karma.conf.js
lib/insights/karma.conf.js
lib/process-services-cloud/karma.conf.js
lib/process-services/karma.conf.js
lib/testing/karma.conf.js

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-10594
Unit tests run in …

[AAE-10594] Run unit tests in headless mode

---

lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.html
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.html
lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts

AAE-12274: Added support for column resizing to process and task lists

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
lib/core/src/lib/datatable/components/datatable/datatable.component.ts
lib/core/src/lib/datatable/data/data-table.schema.ts
lib/core/src/lib/datatable/data/object-datacolumn.model.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.html
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-preferences.ts
lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.html
lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-list/models/tasks-cloud-preferences.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-12578
When user changes the …

AAE-12578 added fn to save col width with preferences

---

.github/workflows/adf_alpha.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

> - [ ] Bugfix
stop old pipelines when new one are triggered on a specific branch, …

AAE-12767-concurrency-group

---

.github/workflows/pull-request.yml

HXOR-109 - add json checker in PR workflow

---

demo-shell/src/custom-style-dev.scss
docs/upgrade-guide/upgrade50-60.md

Fixed error on custom style and added doc for BC

---

.github/workflows/adf_alpha.yml
.github/workflows/release.yml

AAE-12767 - fix concurrency: only on PR workflow

---

lib/content-services/src/lib/breadcrumb/breadcrumb.component.html

> - [x] Bugfix
heading role was added to breadcrumb, which should not be there as it does not act as heading
**What …

[ACS-4281] removed heading role from breadcrumbs.

---

.github/workflows/adf_alpha.yml
.github/workflows/cron-e2e.yml
.github/workflows/cron-upstream.yml
scripts/travis/update/update-project.sh

Cron - Separate cron e2e from upstream and for different repo

---

docs/core/components/datatable.component.md

Updated datatable component docs

---

.github/workflows/release.yml
lib/cli/scripts/npm-publish.ts
scripts/travis/release/release-npm.sh

[AAE-12831] ADF Publish the adf pkgs on gh registry

---

lib/cli/scripts/npm-publish.ts
scripts/travis/release/release-npm.sh

publish on gh first

---

docs/content-services/services/tag.service.md
lib/content-services/src/lib/tag/services/tag.service.spec.ts
lib/content-services/src/lib/tag/services/tag.service.ts

> - [ ] Bugfix
Currently there is no method to completely delete a tag
https://alfresco.atlassian.net/browse/ACS-4331 …

[ACS-4331] Add deleteTag method to tag service

---

scripts/github/release/release-npm.sh

fix release npm

---

.github/workflows/pull-request.yml

we added a job after the e2e in order to have a proper branch protection check
> - [ ] Bugfix …

[HXOR-164] pr check job

---

.github/workflows/release.yml
angular.json

Use as default prod

---

angular.json

Use the right path for testing

---

lib/core/ng-package.json
lib/core/package.json

…lar-oauth2-oidc-jwks'
> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-13016 …

[AAE-13016] Can't resolve 'angular-oauth2-oidc' after merge OIDC PR

---

.github/actions/before-install/action.yml
.github/workflows/pull-request.yml

AAE-12589 - fixing ci:force flag

---

.github/workflows/adf_alpha.yml
scripts/github/update/update-project.sh

Fix for ADF -> APPS upstream

---

.github/workflows/pull-request.yml

AAE-12589 fix cron e2e schedule avoiding ci:force flag checker

---

.github/workflows/pull-request.yml

Fix ci force for dependabot check

---

.github/workflows/release.yml

Use PAT to publish pkgs

---

.github/workflows/release.yml

[HXOR-158] release wont start if pr closed but not approved

---

.github/workflows/package_dispatch.yml

repository-dispatch custom event to monorepo

---

.github/workflows/package_dispatch.yml

change event name

---

.github/workflows/package_dispatch.yml

registry_package change payload

---

.github/workflows/package_dispatch.yml

dispatch package event - change payload values

---

.github/workflows/package_dispatch.yml

change context

---

.github/workflows/package_dispatch.yml

dispatch event - remove await

---

.github/workflows/package_dispatch.yml

dispatch event - Use escape to read var

---

.github/workflows/package_dispatch.yml

dispatch event - use v6

---

.github/workflows/package_dispatch.yml

dispatch event - attempt with await

---

.github/workflows/package_dispatch.yml

dispatch event - use PAT

---

.github/workflows/pull-request.yml

> - [ ] Bugfix
PR is not checked as expected.
when a PR exists, github.head_ref …

HXOR-193 in the pull-request flow, branch name in the flag parser should be managed better

---

.github/workflows/pull-request.yml
angular.json
lib/content-services/karma.conf.js
lib/core/karma.conf.js
lib/extensions/karma.conf.js
lib/insights/karma.conf.js
lib/process-services-cloud/karma.conf.js
lib/process-services/karma.conf.js

> - [ ] Bugfix
Fix code coverage …

[AAE-12242] Fix code coverage

---

.github/workflows/pull-request.yml

HXOR-241 - finalize job needs to be improved by adding a setup check

---

demo-shell/src/app/components/datatable/datatable.component.scss
demo-shell/src/app/components/files/files.component.scss
demo-shell/src/app/components/log/log.component.css
demo-shell/src/app/components/process-list-demo/process-list-demo.component.scss
demo-shell/src/app/components/task-list-demo/task-list-demo.component.scss
lib/insights/src/lib/analytics-process/components/widgets/dropdown/dropdown.widget.scss

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-13063
**Does this PR …

[AAE-13063] replaced custom color with theme related

---

lib/testing/src/lib/protractor/core/pages/snackbar.page.ts

> - [X] Bugfix
broken e2e tests in notification demo page
fix e2e test
**Does this PR …

[HXCS-1310] fix e2e notification

---

CONTRIBUTING.md
docs/user-guide/theming.md

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-13060
**Does this PR …

[AAE-13060] documented css global variables

---

.github/workflows/pull-request.yml

> - [ ] Bugfix
There is a issue with ci:force
Corrected issue with ci:force like it …

HXOR-99 [ci:force] commits on adf is not working properly

---

.github/workflows/cron-upstream.yml
scripts/github/update/update-project.sh

Remove the ability to run upstream from adf [do not merge]

---

lib/content-services/src/lib/i18n/en.json

> - [ ] Bugfix
This i18n string should be added today for the upcoming PR regarding this ticket …

[ACS-4523] Add strings to translate

---

lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts

[AAE-12288] Fix bc

---

.github/actions/e2e/action.yml
.github/workflows/pull-request.yml
scripts/github/affected-contains.sh
scripts/github/e2e/e2e.sh

> - [ ] Bugfix
Pipeline fix
https://alfresco.atlassian.net/browse/AAE-13200
**Does …

[AAE-13200] - Fix GH workflow e2e not affected when testing lib is modified

---

.github/workflows/release.yml

> - [ ] Bugfix
Node version incompatible with used modules (pdfjs and angular dependency) …

[AAE-13093] - Fix demoshell and storybook publishing not working

---

.github/workflows/release.yml

[AAE-13093] - Fix invalid node version for release workflow

---

.github/workflows/release.yml

[AAE-13093] - Fix yml file indentation, use npm cache

---

.github/workflows/release.yml

[AAE-13093] - Use node v16 for publish docker

---

.github/workflows/release.yml
Dockerfile

[AAE-13093] - Set node version of dockerfile to 16.20

---

lib/core/custom-theme/theme/custom-background-color.scss

[AAE-12782] Custom theme - add custom color for app-bar

---

.github/workflows/package_dispatch.yml

Dispatch Event- Retry 3 times in case of failing

---

scripts/next_version.sh

AAE-13608 - Use the gh run id as image suffix

---

release.sh

AAE-11622 - add release script

---

lib/core/src/lib/core.module.ts

[AAE-13141] fix: remove faulty interceptor with caused CORS issues

---

.github/workflows/upstream-js.yml
scripts/github/update/latest-version-of.js
scripts/github/update/useme-to-test-restokit.js

[AAE-13775] Upstream Js API

---

.github/workflows/upstream-js.yml
scripts/github/update/check-pr-already-exist.js
scripts/github/update/latest-version-of.js

[AAE-13775] Upstream js - fix issue

---

.github/workflows/release.yml

AAE-13893 - add condition for master release

---

e2e/process-services-cloud/form-field/task-visibility-condition.e2e.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-13884
Unit test -> …

[AAE-13884] Remove duplicated test C315169

---

docs/upgrade-guide/upgrade50-60.md

> - [ ] Bugfix
refine and fix markup of the upgrade guide …

refine upgrade to 6.0.0 guide

---

.github/workflows/release.yml

> - [x] Bugfix
it's using different flag
It should use dry run flag
**Does this PR …

[HXOR-200] Standardize dry run flags as dry-run-flag: ${{ inputs.dry-run-flag }}

---

lib/process-services-cloud/package-lock.json
lib/process-services-cloud/package.json

[AAE-14166] - fixing dependencies for editorjs

---

scripts/next_version.sh

[AAE-14166] - fixing script for version

---

cspell.json
lib/core/src/lib/auth/services/user-access.service.spec.ts
lib/core/src/lib/auth/services/user-access.service.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-14184
added appkey to query …

[AAE-14184] App key as parameter when fetching roles

---

lib/process-services-cloud/src/lib/task/task-filters/components/base-task-filters-cloud.component.scss

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-13971
Button has proper …

[AAE-13971] changed color to accent contrast

---

e2e-playwright/process-services-cloud/specs/groups-cloud.e2e.ts
lib/process-services-cloud/src/lib/group/components/group-cloud.component.html
lib/process-services-cloud/src/lib/i18n/en.json

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-11270
Error message is …

[AAE-11270] replaced error message with shorter version

---

lib/cli/scripts/init-aae-env.ts

> - [ ] Bugfix
Default apps are not being deployed with environment
Default apps can …

[AAE-13661] Modify init-aae-env file to accept env parameter

---

lib/process-services-cloud/src/lib/form/form-cloud.module.ts
lib/process-services-cloud/src/lib/form/public-api.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-14332
**Does this PR …

[AAE-14332] Fix export in FormCloudModule

---

lib/core/src/lib/viewer/components/img-viewer.component.spec.ts
lib/core/src/lib/viewer/components/img-viewer.component.ts
lib/core/src/lib/viewer/components/mock/adf-viewer-container-more-actions.component.mock.ts
lib/core/src/lib/viewer/components/mock/adf-viewer-container-open-with.component.mock.ts
lib/core/src/lib/viewer/components/mock/adf-viewer-container-sidebar.component.mock.ts
lib/core/src/lib/viewer/components/mock/adf-viewer-container-toolbar-actions.component.mock.ts
lib/core/src/lib/viewer/components/mock/adf-viewer-container-toolbar.component.mock.ts
lib/core/src/lib/viewer/components/viewer-render.component.html
lib/core/src/lib/viewer/components/viewer-render.component.spec.ts
lib/core/src/lib/viewer/components/viewer-render.component.ts
lib/core/src/lib/viewer/components/viewer.component.html
lib/core/src/lib/viewer/components/viewer.component.spec.ts
lib/core/src/lib/viewer/components/viewer.component.ts

> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-5137
Navigation between …

[ACS-5137] Fixed navigation between images

---

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.scss

[AAE-14032] - fixed style for attach button

---

lib/content-services/src/lib/i18n/en.json
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.scss
lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.spec.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.html

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5171
some ui changes for …

[ACS-5171] Facets section - UI changes

---

docs/core/components/datatable.component.md

Update datatable.component.md documentation

---

lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.html
lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-14061
spinner is present …

[AAE-14061] Fix spinner disappearing too early in task lists

---

e2e/protractor.excludes.json

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ADF-5540
Enabled e2e [C277288] …

[ADF-5540] Enable C277288 e2e

---

demo-shell/src/app/components/app-layout/app-layout.component.ts
lib/core/src/lib/app-config/app-config.service.ts
lib/core/src/lib/layout/components/header/header.component.html
lib/core/src/lib/layout/components/header/header.component.scss
lib/core/src/lib/layout/components/header/header.component.ts
lib/core/src/lib/styles/_index.scss

[AAE-14030] Custom header text color is not working on apa

---

docs/upgrade-guide/README.md
docs/upgrade-guide/upgrade411-50.md

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5532
Added ADF upgrade guide …

[ADF-5532] ADF Upgrade guide(upgrade411-50.md)

---

lib/core/src/lib/app-config/app-config.service.ts
lib/core/src/lib/layout/components/header/header.component.ts

[AAE-14030] Fix header custom color

---

lib/cli/templates/auditPage.ejs

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ADF-5544
We are not saving vulnerabilities in audit report …

[ADF-5544] Missing Vulnerabilities in adf-cli audit

---

.gitignore
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.scss

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-14850
With the proposed …

[AAE-14850] Fix outcome buttons position

---

lib/core/src/lib/viewer/components/img-viewer.component.spec.ts
lib/core/src/lib/viewer/components/img-viewer.component.ts

> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-14759
**Does this PR …

[AAE-14759] Fixed image viewer when going to full screen mode

---

.github/workflows/git-tag.yml
Dockerfile

upgrade docker build to 18
> - [ ] Bugfix …

fix tag work flow

---

lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-14851
**Does this PR …

[AAE-14851] Convert manual tests to unit for C587091, C587092

---

lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-14469
We can provide minimum …

[AAE-14469] added constraint for typed value

---

lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts

[AAE-14699] Improved unit test description

---

.github/workflows/pull-request.yml

Fix dry run flag

---

lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-filter-menu-card/search-filter-menu-card.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-filter-menu-card/search-filter-menu-card.component.scss
lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.html

> - [ ] Bugfix
Facets and filters close button is not reachable via keyboard and shift + tab closes the popup.
**What …

[ACS-5342] Accessibility fixes for filters and facets

---

lib/eslint-angular/ng-package.json
lib/eslint-angular/package.json

> - [x] Bugfix
Incorrect path. 
Corrected path. …

[ACS-5290] Corrected path

---

scripts/github/build/npm-check-bundles.sh

> - [x] Bugfix
Extra comma 
Removed comma  …

[ACS-5290] Remove comma

---

.github/workflows/pull-request.yml

> - [ ] Bugfix
Add slack message on cron fail …

[ADF-5547] Add slack message on cron fail

---

scripts/github/build/npm-check-bundles.sh

> - [x] Bugfix
Incorrect script 
Fixed script  …

ACS-5290 Fixed script

---

.github/workflows/pull-request.yml

Fix warning chat message

---

scripts/update-version.sh

> - [x] Bugfix
- use `>=` by default when updating library peer deps
**Does this PR …

fix update-version to use ">=" by default

---

lib/cli/scripts/resources.ts

[AAE-14070] Update permission for user to app

---

.github/workflows/upstream-js.yml
lib/cli/package-lock.json
lib/cli/package.json

> - [ ] Bugfix
Now js-api version in adf-cli will be aligned with js-api version in …

Fix js-api version in adf-cli

---

lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.scss
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.spec.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.scss
lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.spec.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.ts
lib/content-services/src/lib/search/components/search-logical-filter/search-logical-filter.component.html
lib/content-services/src/lib/search/components/search-logical-filter/search-logical-filter.component.spec.ts

> - [ ] Bugfix
UI and styles for facets and filters has been updated. …

[ACS-5347] New styles for facets and filters states

---

lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.html

> - [ ] Bugfix
> - [X] Other... Please describe: Accessibility
Required ARIA attributes must be provided …

[ACS-5341] Accessibility fix for Tags and Location filters component

---

lib/cli/scripts/init-aae-env.ts

Fixing the end slash for the url otherwise the call will fail

---

lib/process-services/src/lib/process-list/components/process-filters.component.html
lib/process-services/src/lib/process-list/components/process-filters.component.spec.ts
lib/process-services/src/lib/process-list/components/process-filters.component.ts
lib/process-services/src/lib/task-list/components/task-filters.component.html
lib/process-services/src/lib/task-list/components/task-filters.component.spec.ts
lib/process-services/src/lib/task-list/components/task-filters.component.ts

> - [x] Bugfix
When I click on any menu item in files this adf-active class does not …

[ACS-5308] Highlight the selected filter in ADW

---

.github/actions/e2e/action.yml
.github/workflows/cron-e2e.yml
.github/workflows/git-tag.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

add E2E_IDENTITY_HOST_APA env var

---

lib/cli/package-lock.json
lib/cli/package.json
lib/content-services/package.json
lib/core/package.json
lib/extensions/package.json
lib/process-services-cloud/package.json
lib/process-services/package.json
lib/testing/package.json
tools/doc/package.json

use latest JS-API library

---

.github/workflows/upstream-js.yml

> - [ ] Bugfix
Upstream modifies only main package.json js-api version.
Upstream …

Use latest js-api in each lib package json

---

.github/workflows/pull-request.yml

Fix ADF cronjob slackbot warning message

---

lib/core/src/lib/common/services/cookie.service.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5397
Whitespaces are handled …

[ACS-5397] Corrected checking whitespace characters in regexp

---

demo-shell/src/app.config.json
lib/process-services-cloud/src/lib/app/mock/app-model.mock.ts
lib/process-services-cloud/src/lib/app/models/application-instance.model.ts
lib/process-services-cloud/src/lib/app/services/apps-process-cloud.service.ts

> - [ ] Bugfix
`ApplicationInstanceModel` and `Descriptor` interfaces did not reflect added properties from BE
**What …

[AAE-15252] Update ADF interfaces to reflect update from BE

---

e2e/protractor.excludes.json
lib/testing/src/lib/protractor/core/pages/material/date-time-picker-calendar.page.ts

> - [ ] Bugfix
> - [x] Other... Please describe: changing calendar locators to work on both BDU calendars
**Does this PR …

[AAE-15269] update calendar locators

---

.github/workflows/release.yml

simulating a change without code

---

.github/workflows/pull-request.yml

improve jobs deps

---

.github/workflows/pull-request.yml

Reverts Alfresco/alfresco-ng2-components#8717

Revert "improve jobs deps"

---

.github/workflows/cron-e2e.yml

test e2e - will be reverted

---

.github/workflows/cron-e2e.yml

Reverts Alfresco/alfresco-ng2-components#8723

Revert "test e2e - will be reverted"

---

lib/core/src/lib/login/components/login.component.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-5403
Prevented possibility to …

[ACS-5403] Prevent possibility to override prototype

---

.github/workflows/cron-e2e.yml

Cron e2e - run from Mon to Fri

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.scss
lib/testing/src/lib/protractor/core/pages/data-table-component.page.ts

> - [X] Bugfix
https://alfresco.atlassian.net/browse/ACS-5314
Now data table row is …

[ACS-5314] Data table row should be clickable anywhere

---

lib/process-services/src/lib/process-list/components/process-filters.component.scss
lib/process-services/src/lib/task-list/components/task-filters.component.scss

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5406
Removed some usages of …

[ACS-5406] Removed some importants

---

lib/core/src/lib/form/components/form-field/form-field.component.spec.ts
lib/core/src/lib/form/components/form-field/form-field.component.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.ts
lib/core/src/lib/form/components/widgets/core/form.model.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
lib/process-services-cloud/src/lib/form/services/form-cloud.service.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-15522
**Does this PR …

[AAE-15522] Fix - Dropdown variable error messages are displayed at modeling part 2

---

lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
lib/content-services/src/lib/document-list/components/document-list.component.ts
lib/core/src/lib/datatable/components/datatable/datatable.component.ts

> - [x] Bugfix
- fix missing "private" for certain document list api
- update unit …

Hide document list private api

---

e2e/content-services/components/comment-component.e2e.ts
lib/core/src/lib/comments/comments.component.spec.ts
lib/core/src/lib/comments/comments.component.ts
lib/core/src/lib/common/services/highlight-transform.service.ts
lib/core/src/lib/pipes/user-initial.pipe.spec.ts

> - [ ] Bugfix
'Incomplete multi-character sanitization' - codeQL error
extra …

[ACS-5399] Fix incomplete multi-character sanitization

---

lib/core/src/lib/pipes/user-initial.pipe.ts

[AAE-15575] Fix username pipe div text assign

---

demo-shell/src/app/components/webscript/webscript.component.ts
demo-shell/src/app/components/webscript/webscript.module.ts
lib/content-services/src/lib/webscript/webscript.component.ts
lib/content-services/src/lib/webscript/webscript.module.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5571?atlOrigin=eyJpIjoiOThiNDIzMDA1NDRkNGVkNGJjMWJlMjBkNmYwNm …

[ACS-5571] Add deprecated attribute to Webscript component

---

demo-shell/src/app/app.module.ts
docs/core/services/translation.service.md
lib/content-services/src/lib/content.module.ts
lib/core/src/lib/core.module.ts
lib/core/src/lib/testing/core.story.module.ts
lib/core/src/lib/translation/translation.service.spec.ts
lib/core/src/lib/translation/translation.service.ts
lib/insights/src/lib/insights.module.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process-services-cloud.module.ts
lib/process-services-cloud/src/lib/testing/process-services-cloud-story.module.ts
lib/process-services/src/lib/process.module.ts

> - [ ] Bugfix
- introduce the simplified way of providing the translations
- new …

[ACS-5629] enhanced way of providing translations

---

.github/actions/setup-chrome/action.yml

[AAE-15762] downgrade google chrome to 114

---

.github/workflows/release.yml

HXOR-167: send slack message in case of release failures

---

lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.html
lib/content-services/src/lib/content-metadata/components/content-metadata-card/content-metadata-card.component.ts

> - [x] Bugfix
- allow toggling tags/categories in the metadata card
- fixes #8765 …

flags for tags and categories in metadata

---

.prettierrc
demo-shell/resources/i18n/en.json
demo-shell/src/app/components/files/files.component.html
demo-shell/src/app/components/files/files.component.scss
demo-shell/src/app/components/files/files.component.ts
e2e/content-services/document-list/document-list-permissions.e2e.ts
e2e/content-services/document-list/document-list-thumbnails-tooltips.e2e.ts
e2e/core/pages/content-services.page.ts
e2e/core/pages/data-table.page.ts
e2e/core/pages/dialog/upload-dialog.page.ts
e2e/core/pages/dialog/upload-toggles.page.ts
e2e/core/pages/login-shell.page.ts
e2e/core/pages/navigation-bar.page.ts
e2e/process-services-cloud/pages/process-cloud-demo.page.ts
e2e/process-services/process/start-process-component.e2e.ts
e2e/search/components/search-sorting-picker.e2e.ts
e2e/search/search-page.e2e.ts
lib/content-services/src/lib/document-list/components/document-list.component.ts

> - [ ] Bugfix
**Update the Files** page in Demo Shell
- remove "Recent" files from …

[ACS-5743] Cleanup Content tests (Demo Shell)

---

lib/core/src/lib/form/components/widgets/core/form-field-types.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.ts
lib/core/src/lib/i18n/en.json
lib/process-services-cloud/src/lib/form/components/cloud-form-rendering.service.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.scss
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.ts
lib/process-services-cloud/src/lib/form/mocks/data-table-widget.mock.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-15815
Example UI of rendered …

[AAE-15815] Create Data Table widget

---

.github/dependabot.yml

Test New grouping Depndabot

---

lib/core/src/lib/form/components/widgets/core/index.ts

> - [ ] Bugfix
Missing export variableConfig interface needed in monorepo
**Does this …

[AAE-15815] Export variable config interface

---

lib/core/src/lib/about/about-panel.directive.ts
lib/core/src/lib/about/about.component.html

> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-15988
**Does this PR …

[AAE-15988] Update About component

---

lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html

> - [x] Bugfix
Labels for chips input are now correctly displayed. …

[ACS-5836] Display label for chips

---

lib/content-services/src/lib/document-list/components/document-list.component.ts

> - [x] Bugfix
fix subscription (memory) leak in the document list component
**Does …

Fix memory/performance leak in Document List component

---

demo-shell/src/app/components/task-list-demo/task-list-demo.component.ts

> - [x] Bugfix
Moment depedency is being present in task-list-demo.component.ts …

[APPS-2110] migrated dependency from moment to date-fns in task-list-demo.component.ts

---

lib/process-services-cloud/src/lib/pipes/process-name-cloud.pipe.spec.ts
lib/process-services-cloud/src/lib/pipes/process-name-cloud.pipe.ts

> - [x] Bugfix
Currently ProcessNameCloudPipe has moment dependency
Migrated …

[ACS-5860] Migration of ProcessNameCloudPipe from moment to date-fns dependency

---

lib/cli/scripts/init-aps-env.ts

> - [ ] Bugfix
Added error logging while uploading aps license
**Does this PR …

Add error logging while updateing aps license

---

lib/core/src/lib/comments/comment-list/comment-list.component.spec.ts
lib/core/src/lib/pipes/time-ago.pipe.spec.ts
lib/core/src/lib/pipes/time-ago.pipe.ts

> - [ ] Bugfix
We were using moment library.
We are using date-fns
**Does this PR …

[ACS-5859] Changing time-ago.pie from moment to date-fns.

---

lib/process-services-cloud/src/lib/app/models/application-instance.model.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-15764
rollback property is …

[AAE-15764] Add rollback property to the model

---

lib/process-services/src/lib/task-list/components/task-list.component.ts

> - [x] Bugfix
moment depedency is present in task-list.component.ts
removed moment …

[APPS-2128] remove moment dependency from task-list.component.ts 

---

e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.spec.ts
lib/content-services/src/lib/search/components/search-date-range/search-date-range.component.ts
lib/insights/src/lib/analytics-process/components/analytics-report-parameters.component.ts
lib/process-services/src/lib/task-list/components/start-task.component.ts

> - [x] Bugfix
moment dependency and moment adapter is present in the component …

[APPS-2135] [APPS-2155] migration of dependency from moment to date-fns

---

.github/workflows/release-branch.yml
.github/workflows/release.yml

remove unused action in release

---

.github/workflows/release-branch.yml

change script to fix the alpha version overlap

---

demo-shell/src/app/components/search/search-config-test.service.ts
docs/breaking-changes/breaking-change-2.6.0-3.0.0.md
docs/content-services/components/search.component.md
docs/content-services/services/search-query-builder.service.md
docs/core/interfaces/search-configuration.interface.md
docs/core/services/search-configuration.service.md
docs/core/services/search.service.md
lib/content-services/src/lib/common/interfaces/search-configuration.interface.ts
lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component-search.spec.ts
lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.ts
lib/content-services/src/lib/mock/search-query.mock.ts
lib/content-services/src/lib/mock/search.component.mock.ts
lib/content-services/src/lib/permission-manager/components/add-permission/search-config-permission.service.ts
lib/content-services/src/lib/permission-manager/services/node-permission.service.ts
lib/content-services/src/lib/search/services/base-query-builder.service.ts
lib/content-services/src/lib/search/services/search-configuration.service.ts
lib/content-services/src/lib/search/services/search-query-builder.service.spec.ts
lib/content-services/src/lib/search/services/search.service.ts

> - [ ] Bugfix
- mirgate from QueryBody (type alias) to a real SearchResult type …

[ACS-5839] migrate from QueryBody to SearchResult type

---

lib/content-services/src/lib/document-list/services/lock.service.spec.ts
lib/content-services/src/lib/document-list/services/lock.service.ts

> - [ ] Bugfix
The service was earlier using moment.js
The service is now using …

[ACS-5876] Change from moment to date-fns for lock.service.

---

lib/core/src/lib/auth/public-api.ts

[AAE-16236] Fix missing service export

---

lib/core/src/lib/form/components/form-renderer.component.scss

> - [ ] Bugfix
add mobile query to visualize form under one column for small viewport …

[AAE-15828] add mobile query to visualize form under one column for small viewport

---

e2e/process-services/tasks/custom-tasks-filters.e2e.ts

[APPS-2160] migration of dependency from moment to date-fns in custom-tasks-filters.e2e.ts

---

lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.scss

> - [x] Bugfix
Long label radio button overlaps the options when in horizontal alignment …

[AAE-16202] Fix long label overlap on radio button

---

lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-14704 …

[AAE-14704] Fix viewers showing removed file

---

lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.ts
lib/process-services-cloud/src/lib/form/mocks/data-table-widget.mock.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-16303
**Does this PR …

[AAE-16303] Handle nested property data source in data table

---

lib/core/custom-theme/material-theme.scss
lib/core/custom-theme/theme/custom-palette-creator.scss
lib/core/custom-theme/theme/custom-theme-palettes.scss
lib/core/custom-theme/theme/default-colors.scss
lib/core/custom-theme/theme/theme-configuration.scss.tpl
lib/core/custom-theme/theme/typography.scss

[AAE-16219] Theming for HxP is not working

---

e2e/protractor.excludes.json
e2e/search/components/search-sorting-picker.e2e.ts
e2e/search/pages/search-filters.page.ts
e2e/search/search-filters.e2e.ts
e2e/search/search-multiselect.e2e.ts
lib/cli/package-lock.json
lib/content-services/src/lib/search/components/search-chip-autocomplete-input/search-chip-autocomplete-input.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.spec.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-tabbed-content.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-tabbed-content.component.spec.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-tabbed-content.component.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.ts
lib/content-services/src/lib/search/components/search-filter/search-filter.component.html
lib/content-services/src/lib/search/public-api.ts
lib/content-services/src/lib/search/search.module.ts
lib/testing/src/lib/protractor/content-services/pages/search/search-check-list.page.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5742
Fixed failing search …

 [ACS-5742] Fix Search e2e's

---

.github/codeql/codeql-config.yml
.github/workflows/codeql-analysis.yml

> - [ ] Bugfix
Currently `paths-ignore` keywords used for on.<push|pull_request>.paths in a workflow. When they are …

[ACS-6004] Exclude paths from CodeQL analysis 

---

lib/core/src/lib/services/alfresco-api.interface.ts
lib/core/src/lib/services/alfresco-api.service.ts
lib/core/src/lib/services/public-api.ts

[AAE-16491] Fix session invalidation for Http 401 response

---

lib/core/src/lib/viewer/components/pdf-viewer.component.html
lib/core/src/lib/viewer/components/pdf-viewer.component.scss
lib/core/src/lib/viewer/components/pdf-viewer.component.spec.ts
lib/core/src/lib/viewer/components/pdf-viewer.component.ts

> - [X] Bugfix
When a very large Tiff file is opened in .pdf format, it is impossible to navigate horizontally …

[MNT-23560] TIFF PDF Renderer Error

---

lib/process-services/src/lib/process-list/services/process.service.spec.ts
lib/process-services/src/lib/process-list/services/process.service.ts

> - [ ] Bugfix
Moment Library is being used in process.service.ts.
Replaced moment …

[ACS-5878] Migrated moment occurrences to date-fns equivalent in ProcessService

---

e2e/content-services/document-list/document-list-component.e2e.ts
e2e/process-services-cloud/process/process-header-cloud.e2e.ts
e2e/process-services-cloud/task-list/task-header-cloud.e2e.ts
e2e/process-services/process/process-instance-details.e2e.ts
e2e/process-services/tasks/info-drawer.e2e.ts

Reverts Alfresco/alfresco-ng2-components#8864

Revert "[APPS-2157] [APPS-2158] [APPS-2161] [APPS-2162] [APPS-2165] migration of e2e test cases from moment to date-fns"

---

docs/core/components/data-column.component.md
e2e/process-services/pages/filters.page.ts
e2e/process-services/pages/tasks-list.page.ts
e2e/process-services/tasks/custom-tasks-filters.e2e.ts
lib/core/src/lib/datatable/data-column/data-column.component.ts
lib/core/src/lib/datatable/data/data-column.model.ts
lib/core/src/lib/datatable/data/data-table.schema.ts
lib/core/src/lib/datatable/data/object-datacolumn.model.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
lib/process-services/src/lib/i18n/en.json
lib/process-services/src/lib/process-list/components/process-list.component.spec.ts
lib/process-services/src/lib/task-list/components/task-list.component.spec.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-5613
We needed possibility to …

[ACS-5613] process preview on popup displaying the details of selected running process on the popup

---

docs/core/services/process-content.service.md
lib/process-services/src/lib/form/services/process-content.service.ts

> - [ ] Bugfix
Add new method to get processes and tasks related to content.
**Does …

[ACS-5601] Add getProcessesAndTasksOnContent to process content service

---

lib/process-services/src/lib/app-list/apps-list.component.spec.ts
lib/process-services/src/lib/app-list/apps-list.component.ts
lib/process-services/src/lib/attachment/create-process-attachment.component.ts
lib/process-services/src/lib/attachment/create-task-attachment.component.ts
lib/process-services/src/lib/attachment/process-attachment-list.component.ts
lib/process-services/src/lib/attachment/task-attachment-list.component.ts
lib/process-services/src/lib/common/services/people-process.service.ts
lib/process-services/src/lib/form/form.component.ts
lib/process-services/src/lib/form/services/activiti-alfresco.service.ts
lib/process-services/src/lib/form/services/process-content.service.ts
lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget-dialog.service.ts
lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.ts
lib/process-services/src/lib/form/widgets/document/content.widget.ts
lib/process-services/src/lib/people/components/people-search/people-search.component.spec.ts
lib/process-services/src/lib/process-comments/services/comment-process.service.ts
lib/process-services/src/lib/process-list/components/process-audit.directive.ts
lib/process-services/src/lib/process-list/components/process-filters.component.ts
lib/process-services/src/lib/process-list/components/process-instance-details.component.ts
lib/process-services/src/lib/process-list/components/process-instance-tasks.component.ts
lib/process-services/src/lib/process-list/components/process-list.component.ts
lib/process-services/src/lib/process-list/components/start-process.component.spec.ts
lib/process-services/src/lib/process-list/components/start-process.component.ts
lib/process-services/src/lib/process-user-info/process-user-info.component.ts
lib/process-services/src/lib/task-list/components/checklist.component.ts
lib/process-services/src/lib/task-list/components/task-details.component.ts
lib/process-services/src/lib/task-list/components/task-filters.component.ts
lib/process-services/src/lib/task-list/components/task-form/task-form.component.ts
lib/process-services/src/lib/task-list/components/task-header.component.ts
lib/process-services/src/lib/task-list/components/task-list.component.ts
lib/process-services/src/lib/task-list/services/tasklist.service.ts

> - [ ] Bugfix
before enabling jsdoc linting, fix errors and warnings in the process …

[ACS-6071] documentation fixes for process lib

---

lib/process-services-cloud/src/lib/app/components/app-details-cloud.component.ts
lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts
lib/process-services-cloud/src/lib/form/components/widgets/properties-viewer/properties-viewer-wrapper/properties-viewer-wrapper.component.ts
lib/process-services-cloud/src/lib/group/components/group-cloud.component.spec.ts
lib/process-services-cloud/src/lib/group/components/group-cloud.component.ts
lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts
lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-filters/services/process-filter-cloud.service.ts
lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
lib/process-services-cloud/src/lib/services/user-preference-cloud.service.ts
lib/process-services-cloud/src/lib/task/services/task-cloud.service.ts
lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-filters/components/service-task-filters-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.spec.ts
lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-filters/services/service-task-filter-cloud.service.ts
lib/process-services-cloud/src/lib/task/task-filters/services/task-filter-cloud.service.ts
lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts

> - [ ] Bugfix
before enabling the jsdoc linting, fix errors and warnings in process …

[ACS-6071] fix docs for process cloud

---

lib/cli/scripts/init-aae-env.ts
lib/process-services-cloud/src/lib/process/start-process/services/start-process-cloud.service.ts
package-lock.json
package.json

> - [x] Bugfix
revert the request library removal until a better fix found
**Does this …

[AAE-16884] revert request removal

---

lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.ts
lib/process-services-cloud/src/lib/form/mocks/data-table-widget.mock.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-16969
**Does this PR …

[AAE-16969] Remove force casting of all types to text

---

lib/insights/src/lib/analytics-process/components/analytics-report-parameters.component.spec.ts
lib/insights/src/lib/analytics-process/components/analytics-report-parameters.component.ts
lib/insights/src/lib/diagram/models/chart/bar-chart.model.ts
lib/insights/src/lib/testing/insights.testing.module.ts

> - [ ] Bugfix
- migrate analytics report to date-fns
- provide missing typings and …

[APPS-2108] migrate analytics report to date-fns

---

lib/core/src/lib/common/utils/date-fns-utils.ts
lib/core/src/lib/form/models/widget-visibility.model.ts
lib/core/src/lib/form/services/widget-visibility-cloud.service.spec.ts
lib/core/src/lib/form/services/widget-visibility.service.spec.ts
lib/core/src/lib/form/services/widget-visibility.service.ts

> - [ ] Bugfix
The service was earlier using moment.js
- migrate widget visibility …

[ACS-5877] Migrate widget-visibility service do date-fns

---

lib/core/src/lib/form/components/widgets/core/form-field-validator.spec.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts

> - [ ] Bugfix
- migrate various unit tests to date-fns …

[APPS-2108] migrate unit tests to date-fns

---

lib/cli/scripts/init-aae-env.ts
lib/process-services/src/lib/form/widgets/people/people.widget.ts
package-lock.json
package.json

> - [ ] Bugfix
Codebase was using depracated request library
Replaced request library …

[ACS-6019] [ACS-6021] [ACS-6023] Replaced request with node-fetch

---

lib/cli/package-lock.json
lib/cli/package.json
package-lock.json
package.json

> - [ ] Bugfix
Added node-fetch to adf-cli package.json …

[ACS-6019] Added node-fetch to adf-cli package.json

---

e2e/content-services/metadata/metadata-smoke-tests.e2e.ts
e2e/protractor.excludes.json
lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
lib/core/src/lib/card-view/models/card-view-baseitem.model.ts
lib/core/src/lib/card-view/models/card-view-dateitem.model.ts
lib/core/src/lib/card-view/validators/card-view-item-float.validator.ts
lib/core/src/lib/card-view/validators/card-view-item-int.validator.ts
lib/core/src/lib/common/utils/moment-date-adapter.ts
lib/core/src/lib/pipes/localized-date.pipe.ts
lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts

> - [ ] Bugfix
- migrate cardview and task filter components to date-fns
- generics …

[APPS-2108] migrate cardview and task filters to date-fns

---

docs/core/datetime.md
docs/release-notes/RelNote-6.4.0.md

> - [ ] Bugfix
initial documentation on the date/time adapters
**Does this PR …

[APPS-2255] documentation on date adapters

---

lib/content-services/src/lib/tag/tag-node-list.component.html

> - [ ] Bugfix
Getting this "Elements must only use supported ARIA attributes" and "ARIA input fields must have an …

[ACS-6126] Fixed accessibility issues

---

docs/core/components/data-column.component.md
lib/core/src/lib/datatable/components/amount-cell/amount-cell.component.html
lib/core/src/lib/datatable/components/amount-cell/amount-cell.component.spec.ts
lib/core/src/lib/datatable/components/amount-cell/amount-cell.component.ts
lib/core/src/lib/datatable/components/datatable/datatable.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
lib/core/src/lib/datatable/components/mocks/datatable.mock.ts
lib/core/src/lib/datatable/data/data-column.model.ts
lib/core/src/lib/datatable/data/object-datacolumn.model.ts
lib/core/src/lib/datatable/datatable.module.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-16964
Amount column type …

[AAE-16964] Handle amount data table cloumn type

---

docs/core/components/data-column.component.md
lib/core/src/lib/datatable/components/datatable/datatable.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
lib/core/src/lib/datatable/components/mocks/datatable.mock.ts
lib/core/src/lib/datatable/components/number-cell/number-cell.component.html
lib/core/src/lib/datatable/components/number-cell/number-cell.component.spec.ts
lib/core/src/lib/datatable/components/number-cell/number-cell.component.ts
lib/core/src/lib/datatable/data/data-column.model.ts
lib/core/src/lib/datatable/data/object-datacolumn.model.ts
lib/core/src/lib/datatable/datatable.module.ts
lib/extensions/src/lib/config/document-list.extensions.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-16962
**Does this PR …

[AAE-16962] Handle number data table column type

---

demo-shell/src/app/components/app-layout/app-layout.component.ts
lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.ts

> - [x] Bugfix
fix errors parsing card view date item values …

[ACS-5645] card view dateitem parse fix

---

lib/process-services-cloud/src/lib/form/date-formats.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6189
Date format is …

[ACS-6189] Corrected date format

---

lib/content-services/src/lib/dialogs/library/library.dialog.ts

> - [x] Bugfix
Generic Modal does not exist for Library Modal.
Generic error added. …

[ACS-5831] Adding generic error to Library Modal.

---

lib/process-services-cloud/src/lib/common/date-range-filter/date-range-filter.component.ts
lib/process-services-cloud/src/lib/common/process-common.module.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6189
Moved date adapter from …

[ACS-6189] Moved date adapter from module to component

---

lib/cli/scripts/resources.ts

> - [ ] Bugfix
Simpleapp doesn't have the local development flag enabled.
Simpleapp …

AAE-15874 enable local development option for simpleapp

---

demo-shell/src/app/components/card-view/card-view.component.html
demo-shell/src/app/components/card-view/card-view.component.scss
demo-shell/src/app/components/card-view/card-view.component.ts
demo-shell/src/app/components/cloud/shared/cloud-settings.component.html
demo-shell/src/app/components/cloud/shared/cloud-settings.component.scss
demo-shell/src/app/components/file-view/file-view.component.html
demo-shell/src/app/components/settings/host-settings.component.html
demo-shell/src/app/components/settings/host-settings.component.scss

> - [ ] Bugfix
- remove the usage of `mat-card` in the demo shell
- remove internal …

[ACS-6245] remove mat-card and internal styling from demo shell

---

lib/core/custom-theme/theme/custom-palette-creator.scss

[AAE-16970] Custom colors are not calculating correctly in default UI

---

lib/core/src/lib/styles/_components-variables.scss

Fix missing primary scss variable

---

lib/core/src/lib/layout/components/header/header.component.html
lib/core/src/lib/layout/components/header/header.component.spec.ts
lib/core/src/lib/layout/components/header/header.component.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-17551
**Does this PR …

[AAE-17551] added backgroundImage property for header

---

lib/core/src/lib/app-config/app.config.schema.json

[AAE-17748] Remove secret from required prop from app.config.schema.json

---

lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts

> - [x] Bugfix
- fix broken expression code …

fix broken expression code in people cloud

---

lib/core/src/lib/layout/components/header/header.component.html
lib/core/src/lib/layout/components/header/header.component.spec.ts
lib/core/src/lib/layout/components/header/header.component.stories.ts
lib/core/src/lib/layout/components/header/header.component.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-17807
**Does this PR …

[AAE-17807] fix for header background color

---

package-lock.json
package.json

[ADF-5561] Remove unused dep

---

lib/content-services/src/lib/document-list/services/custom-resources.service.ts
lib/content-services/src/lib/permission-manager/components/add-permission/search-config-permission.service.ts
lib/content-services/src/lib/search/components/search-filter-autocomplete-chips/search-filter-autocomplete-chips.component.ts
lib/content-services/src/lib/search/models/autocomplete-option.interface.ts

[ACS-4794] ES query migration changes

---

lib/content-services/src/lib/content-node-share/content-node-share.dialog.scss

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6225
Removed extra gray area …

[ACS-6225] Removed extra gray area around share link dialog

---

.github/actions/before-install/action.yml
.github/workflows/release.yml

Reverts Alfresco/alfresco-ng2-components#9091

Revert "[AAE-18105] Fix release workflow: release-npm step doesn't publish al…"

---

lib/core/src/lib/form/components/form-renderer.component.spec.ts
lib/core/src/lib/form/components/mock/form-renderer.component.mock.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-17859
Mark …

[AAE-17859] Convert manual C309872 to unit test

---

demo-shell/src/app.config.json
lib/core/src/lib/app-config/app.config.schema.json
lib/core/src/lib/auth/oidc/auth-config.service.spec.ts
lib/core/src/lib/auth/oidc/auth-config.service.ts

> - [x] Bugfix
- fix loading all oauth configuration fields …

[ACS-6328] fix oauth config loading

---

lib/cli/package-lock.json
lib/cli/package.json
lib/content-services/package.json
lib/core/package.json
lib/extensions/package.json
lib/process-services-cloud/package.json
lib/process-services/package.json
lib/testing/package.json

[PRODENG-211] update js-api deps

---

.github/actions/npm-check-bundle/action.yml
scripts/github/build/npm-check-bundles.sh

> - [x] Bugfix
- rework the bundle check script to take individual package versions …

[PRODENG-211] update npm bundle check

---

lib/core/src/lib/auth/authentication-interceptor/auth-bearer.interceptor.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-18175
**Does this PR …

[AAE-18175] Unable to Import Descriptor in HXP Environment

---

angular.json

Trigger a new release

---

scripts/update-version.sh

> - [x] Bugfix
- pin cli to js-api 7.2.0 while investigating better solution
- minor …

[ACS-6370] temporary pin ADF cli to js-api 7.2.0

---

scripts/github/build/npm-check-bundles.sh

> - [x] Bugfix
- fix bundle check for js-api …

[AAE-18464] fix bundle check for js-api

---

scripts/update-version.sh

> - [x] Bugfix
- remove old workarounds for js-api version bump
**Does this PR …

[ACS-6370] fix js-api version bump

---

.github/workflows/release.yml

ADF release - Notify correct channel

---

.github/dependabot.yml
.github/workflows/pull-request.yml

> - [x] Bugfix
Dependabot configuration contains errors due to groups configuratio. 
As consequence the Dependabot …

Fix dependabot.yml

---

docs/content-services/components/aspect-list-dialog.component.md
docs/content-services/components/aspect-list.component.md
docs/content-services/services/category.service.md
docs/content-services/services/tag.service.md
docs/user-guide/search-configuration-guide.md
e2e/protractor.excludes.json
lib/content-services/src/lib/aspect-list/aspect-list-dialog-data.interface.ts
lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.html
lib/content-services/src/lib/aspect-list/aspect-list-dialog.component.spec.ts
lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
lib/content-services/src/lib/aspect-list/aspect-list.component.ts
lib/content-services/src/lib/aspect-list/services/dialog-aspect-list.service.spec.ts
lib/content-services/src/lib/aspect-list/services/dialog-aspect-list.service.ts
lib/content-services/src/lib/category/services/category.service.spec.ts
lib/content-services/src/lib/category/services/category.service.ts
lib/content-services/src/lib/search/models/search-category.interface.ts
lib/content-services/src/lib/tag/services/tag.service.spec.ts
lib/content-services/src/lib/tag/services/tag.service.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/ACS-6252
Allowing to hide things …

[ACS-6252] support disabling the tags and categories feature in the applications

---

demo-shell/src/app/components/files/files.component.html
demo-shell/src/app/components/files/files.component.ts
e2e/content-services/document-list/document-list-component.e2e.ts
e2e/core/pages/content-services.page.ts
lib/core/src/lib/datatable/components/date-cell/date-cell.component.html
lib/core/src/lib/datatable/components/date-cell/date-cell.component.spec.ts
lib/core/src/lib/datatable/components/date-cell/date-cell.component.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-17666
**Does this PR …

[AAE-17666] Remove date cell e2es covered by unit tests

---

.github/actions/artifact-extract/action.yml
.github/actions/setup/action.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cron-e2e.yml
.github/workflows/git-tag.yml
.github/workflows/package_dispatch.yml
.github/workflows/pull-request.yml
.github/workflows/rebase.yml
.github/workflows/release-branch.yml
.github/workflows/release.yml

Reverts Alfresco/alfresco-ng2-components#9163

Revert "Check js api unit test issue"

---

.github/actions/setup/action.yml

Reverts Alfresco/alfresco-ng2-components#9165

Revert "Revert "build(deps): bump actions/setup-node in /.github/actions/setu…"

---

lib/cli/scripts/resources.ts

[AAE-19026] Fix app permissions

---

lib/process-services/src/lib/form/services/activiti-alfresco.service.ts

> - [x] Bugfix
It's impossible to start a process with a file which has been created via template. …

[ACS-6412] - Some operations are broken when executed on file created from template

---

lib/core/src/lib/auth/services/authentication.service.spec.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-18267
**Does this PR …

[AAE-18267] change unit test setup for auth service

---

lib/content-services/src/lib/category/categories-management/categories-management.component.spec.ts
lib/core/src/lib/datatable/components/date-cell/date-cell.component.spec.ts
lib/core/src/lib/form/components/widgets/date-time/date-time.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/rich-text-editor/rich-text-editor.component.spec.ts
lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
lib/process-services/src/lib/form/start-form.component.spec.ts
lib/process-services/src/lib/process-list/components/start-process.component.spec.ts

remaining unit test fixes for the Angular 15 update

---

lib/content-services/src/lib/tag/tag-node-list.component.spec.ts

fix content-services unit test fails

---

lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-19372
**Does this PR …

[AAE-19372] fix assignee input not being clickable

---

.github/actions/artifact-append/action.yml
.github/actions/artifact-extract/action.yml
.github/actions/artifact-initialize/action.yml
.github/actions/e2e/action.yml
.github/workflows/pull-request.yml
lib/core/custom-theme/theme/custom-palette-creator.scss

Solve deprecation warning in the theme creation
> - [ ] Bugfix
Solve deprecation warning in the theme creation
**What …

[AAE-17674] Solve deprecation warning in the theme creation

---

lib/core/custom-theme/theme/custom-palette-creator.scss

 [AAE-17674] Solve deprecation warning in the theme creation

---

lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.html
lib/process-services-cloud/src/lib/form/components/widgets/attach-file/attach-file-cloud-widget.component.scss

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-19621
**Does this PR …

[AAE-19621] Fix icon cut off in attach file button

---

lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.ts
lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts

> - [X] Bugfix
https://alfresco.atlassian.net/browse/HXCS-2988 …

[HXCS-2988] fix dates in CardViweDateItemComponent

---

lib/process-services-cloud/src/lib/task/task-filters/components/task-assignment-filter/task-assignment-filter.component.html

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-15206?focusedCommentId=1237220 …

[AAE-15206] add missing label to task assignment filter

---

lib/process-services-cloud/src/lib/group/components/group-cloud.component.html

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-15294
**Does this PR …

[AAE-15294] add missing token class to cloud group component

---

docs/core/components/login.component.md
lib/core/src/lib/app-config/app.config.schema.json
lib/js-api/docs/authentication.md

> - [ ] Bugfix
remove unused authpath …

[AAE-13305] remove unused authpath

---

.github/workflows/release.yml

[ADF-5577] CI/CD - Release add concurrency

---

lib/core/src/lib/form/models/widget-visibility.model.ts
lib/core/src/lib/form/services/widget-visibility.service.spec.ts

> - [X] Bugfix
https://alfresco.atlassian.net/browse/AAE-19968
**Does this PR …

[AAE-19968] Field visibility condition using Integer and greater than not working

---

lib/cli/scripts/resources.ts

[AAE-18758] Consistency with deploy payload in be uats

---

lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
lib/core/src/lib/card-view/components/card-view/card-view.component.scss

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-20250
**Does this PR …

[AAE-20250] fixed label overlapping input for readonly cardview textitem

---

lib/core/src/lib/layout/components/header/header.component.html

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-20428
**Does this PR …

[AAE-20428] - Admin application - header is missing name of the app and user menu

---

lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/group/group-cloud.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.ts

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-20282 …

AAE-20282 fix submit button enabled when required people/groups widget empty

---

lib/content-services/src/lib/document-list/services/custom-resources.service.ts

> - [x] Bugfix
There is error when fetching recent files.
Recent files are fetched …

[MNT-24151] - ADW: Users can see some actions Edit Offline" and "Upload New Version" for the declared record - fix

---

cspell.json
lib/content-services/src/lib/common/services/content.service.spec.ts
lib/content-services/src/lib/content-metadata/services/config/layout-oriented-config.service.spec.ts
lib/content-services/src/lib/dialogs/download-zip/mock/download-zip-service.mock.ts
lib/content-services/src/lib/dialogs/library/library.dialog.ts
lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
lib/content-services/src/lib/mock/date-range-search-filter.mock.ts
lib/content-services/src/lib/pipes/tab-labels.pipe.ts
lib/content-services/src/lib/search/components/search-date-range-tabbed/search-date-range-tabbed.component.ts

Linting fixes

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html

[ACS-6565] ADW - Document List View Header - UX Bugs - icon fix

---

lib/js-api/src/api/content-rest-api/api/nodes.api.ts

> - [ ] Bugfix
Nodes are not removed in the specified order
Nodes are deleted in the …

[ACS-5994] JS-API - perform node deletion in order

---

lib/js-api/docs/authentication.md

[MNT-22836] - Docs for Support of PKCE

---

lib/content-services/src/lib/document-list/data/share-data-row.model.ts
lib/content-services/src/lib/document-list/data/share-datatable-adapter.ts

> - [x] Bugfix
When updating a node, it's size and some other properties disappear from list view. …

[ACS-6817] Size and Modified by is not displayed after editing file/folder properties

---

lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.scss

> - [x] Bugfix
https://alfresco.atlassian.net/browse/AAE-20791
**Does this PR …

AAE-20791 fixed task form spinner alignment

---

docs/content-services/interfaces/content-metadata-custom-panel.interface.md
docs/content-services/interfaces/content-metadata-panel.interface.md
lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata-header.component.ts
lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.html
lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.spec.ts
lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.ts
lib/content-services/src/lib/content-metadata/interfaces/card-view-group.interface.ts
lib/content-services/src/lib/content-metadata/interfaces/content-metadata-custom-panel.interface.ts
lib/content-services/src/lib/content-metadata/interfaces/content-metadata-panel.interface.ts
lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.spec.ts
lib/content-services/src/lib/content-metadata/services/property-groups-translator.service.ts

> - [x] Bugfix
Property panel feature has a lot of different bugs and isn't working as expected. …

[ACS-6831] Property panel refactoring

---

lib/content-services/src/lib/search/components/search-datetime-range/search-datetime-range.component.html
lib/content-services/src/lib/search/components/search-filter/search-filter-card/search-filter-card.component.html

> - [ ] Bugfix
Buttons for date-time widgets are coming from wrapper
**Does this PR …

[AAE-19610] Fix duplicated buttons for date-time filter widget

---

lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.spec.ts
lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-19372
**Does this PR …

AAE-19372 Fix clickable area on cardview textitem

---

.github/actions/e2e/action.yml
.github/workflows/pull-request.yml

AAE-0000 e2e affected were not running on ADF pipeline

---

lib/content-services/src/lib/version-manager/version-list.component.html
lib/content-services/src/lib/version-manager/version-list.component.scss

> - [x] Bugfix
https://alfresco.atlassian.net/browse/ACS-6581
Comments for version …

[ACS-6581] Wrap comments into multiple lines

---

e2e/protractor.excludes.json

> - [ ] Bugfix
failing tests due to this bug -> https://alfresco.atlassian.net/browse/AAE-21222 …

AAE-21222 exclude e2es

---

cspell.json
lib/core/src/lib/form/components/widgets/core/form-field-types.ts
lib/core/src/lib/form/components/widgets/core/form-field-validator.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.ts
lib/core/src/lib/form/components/widgets/form.theme.scss
lib/core/src/lib/i18n/en.json
lib/process-services-cloud/src/lib/form/components/cloud-form-rendering.service.ts
lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.scss
lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-20848
**Does this PR …

AAE-20848 Add display external property widget

---

lib/content-services/src/lib/search/components/index.ts
lib/content-services/src/lib/search/components/search-check-list/index.ts
lib/content-services/src/lib/search/components/search-chip-autocomplete-input/index.ts
lib/content-services/src/lib/search/components/search-date-range-tabbed/index.ts
lib/content-services/src/lib/search/components/search-datetime-range/index.ts
lib/content-services/src/lib/search/components/search-facet-field/index.ts
lib/content-services/src/lib/search/components/search-filter-autocomplete-chips/index.ts
lib/content-services/src/lib/search/components/search-filter-chips/index.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.html
lib/content-services/src/lib/search/components/search-filter-container/index.ts
lib/content-services/src/lib/search/components/search-filter-tabbed/index.ts
lib/content-services/src/lib/search/components/search-filter/index.ts
lib/content-services/src/lib/search/components/search-form/index.ts
lib/content-services/src/lib/search/components/search-logical-filter/index.ts
lib/content-services/src/lib/search/components/search-number-range/index.ts
lib/content-services/src/lib/search/components/search-panel/index.ts
lib/content-services/src/lib/search/components/search-properties/index.ts
lib/content-services/src/lib/search/components/search-radio/index.ts
lib/content-services/src/lib/search/components/search-slider/index.ts
lib/content-services/src/lib/search/components/search-sorting-picker/index.ts
lib/content-services/src/lib/search/components/search-text/index.ts
lib/content-services/src/lib/search/components/search-widget-container/index.ts
lib/content-services/src/lib/search/forms/index.ts
lib/content-services/src/lib/search/mocks/index.ts
lib/content-services/src/lib/search/models/index.ts
lib/content-services/src/lib/search/public-api.ts
lib/content-services/src/lib/search/search.module.ts
lib/content-services/src/lib/search/services/index.ts

> - [x] Bugfix
not all components and types are exported by the `content-services` library …

[ACS-7312] fix missing Search component exports, support projection

---

lib/process-services-cloud/src/lib/app/models/application-instance.model.ts

> - [ ] Bugfix
https://alfresco.atlassian.net/browse/AAE-20447
**Does this PR …

AAE-20447 Add new field to choose auth flow type for custom UIs

---

docs/content-services/components/search-input.component.md
lib/content-services/src/lib/search/components/search-input/search-input.component.ts

> - [x] Bugfix
fix incorrect selector for new component …

[ACS-7338] fix search input component selector

---

.husky/pre-commit
.lintstagedrc.json
lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.ts

> - [ ] Bugfix
- enable Prettier / ESLint / StyleLint linting and fixing for …

[ACS-7357] pre-commit linting for code and styles

---

lib/core/src/lib/styles/_components-variables.scss
lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.scss
lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.spec.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-21336 …

AAE-21336 Display selected external property in preview state

---

.husky/pre-commit
lib/core/src/lib/about/about-extension-list/about-extension-list.component.ts
lib/core/src/lib/about/about-github-link/about-github-link.component.ts
lib/core/src/lib/about/about-license-list/about-license-list.component.ts
lib/core/src/lib/about/about-module-list/module-list.component.ts
lib/core/src/lib/about/about-package/package-list.component.ts
lib/core/src/lib/about/about-panel.directive.ts
lib/core/src/lib/about/about-platform-version/about-platform-version.component.ts
lib/core/src/lib/about/about-repository-info/about-repository-info.component.ts
lib/core/src/lib/about/about-server-settings/about-server-settings.component.ts
lib/core/src/lib/about/about-status-list/about-status-list.component.ts
lib/core/src/lib/about/about.component.ts
lib/core/src/lib/about/about.mock.ts
lib/core/src/lib/about/about.module.ts

> - [x] Bugfix
- convert About to Standalone components
- break dependency on Material …

[ACS-7379] Break About Module dependency on Material Module

---

lib/core/src/lib/form/components/widgets/amount/amount.widget.html
lib/core/src/lib/form/components/widgets/amount/amount.widget.scss

> - [ ] Bugfix
Style update
Amount widget with broken styles after Angular 15 migration …

AAE-21393 Fix amount widget style

---

lib/core/src/lib/toolbar/toolbar-divider.component.ts
lib/core/src/lib/toolbar/toolbar-title.component.ts
lib/core/src/lib/toolbar/toolbar.component.ts
lib/core/src/lib/toolbar/toolbar.module.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7388
component is standalone …

[ACS-7388][ADF] Break Toolbar dependency on Material Module

---

.github/workflows/pull-request.yml

AAE-21718 CI daily fix pipeline

---

lib/content-services/src/lib/upload/components/file-uploading-dialog.component.html
lib/content-services/src/lib/upload/components/file-uploading-dialog.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7446 …

[ACS-7446] - Upload progress box issues

---

lib/cli/scripts/init-aae-env.ts
lib/cli/scripts/resources.ts

[AAE-21869](https://hyland.atlassian.net/browse/AAE-21869)
[AAE-21869]: https://hyland.atlassian.net/browse/AAE-21869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AAE-21870 Disable task notification for default apps

---

docs/content-services/components/search-check-list.component.md
docs/content-services/components/search-datetime-range.component.md
docs/content-services/components/search-logical-filter.component.md
docs/content-services/components/search-number-range.component.md
docs/content-services/components/search-radio.component.md
docs/content-services/components/search-slider.component.md
docs/content-services/components/search-text.component.md
docs/content-services/interfaces/search-widget.interface.md
docs/content-services/services/search-query-builder.service.md
docs/user-guide/search-configuration-guide.md

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-6644
Search docs are reviewed …

[ACS-6644] review search documentation and examples for adf

---

lib/core/src/lib/notifications/components/notification-history.component.scss

[ACS-7528] - Notification and user icons are a bit different

---

lib/core/src/lib/search-text/search-text-input.component.ts
lib/core/src/lib/search-text/search-text-input.module.ts
lib/core/src/lib/search-text/search-trigger.directive.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7387
component is converted to …

[ACS-7387][ADF] Break Search Text dependency on Material Module

---

lib/core/src/lib/notifications/components/notification-history.component.html
lib/core/src/lib/notifications/components/notification-history.component.scss

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7530 …

[ACS-7530] - Notifications popup looks a bit differently

---

lib/content-services/src/lib/version-manager/version-list.component.html
lib/content-services/src/lib/version-manager/version-list.component.scss

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7414 …

[ACS-7414] -  manage versions dialog after rebase

---

lib/process-services-cloud/src/lib/form/components/widgets/people/people-cloud.widget.html
lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
lib/process-services-cloud/src/lib/people/components/people-cloud.component.spec.ts

> - [ ] Bugfix
Style fix
People widget with broken styles after Angular 15 migration …

AAE-21697 Fix people form widget style

---

lib/content-services/src/lib/common/services/upload.service.spec.ts
lib/content-services/src/lib/new-version-uploader/new-version-uploader.module.ts
lib/core/src/lib/app-config/app-config.module.ts
lib/core/src/lib/app-config/app-config.pipe.ts
lib/core/src/lib/app-config/app-config.service.spec.ts
lib/core/src/lib/core.module.ts

> - [ ] Bugfix
- convert `AppConfigPipe` to standalone pipe
- mark `AppConfigModule` …

[ACS-7382] Standalone AdfConfigPipe pipe

---

lib/core/src/lib/pipes/date-time.pipe.ts
lib/core/src/lib/pipes/decimal-number.pipe.ts
lib/core/src/lib/pipes/file-size.pipe.ts
lib/core/src/lib/pipes/file-type.pipe.ts
lib/core/src/lib/pipes/filter-out-every-object-by-prop.pipe.ts
lib/core/src/lib/pipes/filter-string.pipe.ts
lib/core/src/lib/pipes/format-space.pipe.ts
lib/core/src/lib/pipes/full-name.pipe.ts
lib/core/src/lib/pipes/localized-role.pipe.ts
lib/core/src/lib/pipes/mime-type-icon.pipe.ts
lib/core/src/lib/pipes/moment-date.pipe.ts
lib/core/src/lib/pipes/moment-datetime.pipe.ts
lib/core/src/lib/pipes/multi-value.pipe.spec.ts
lib/core/src/lib/pipes/multi-value.pipe.ts
lib/core/src/lib/pipes/pipe.module.ts
lib/core/src/lib/pipes/text-highlight.pipe.ts
lib/core/src/lib/pipes/user-initial.pipe.ts

> - [ ] Bugfix
- convert angular pipes in the Core module to Angular Standalone
- mark …

[ACS-7597] Convert Core pipes to Standalone

---

lib/content-services/src/lib/dialogs/library/library.dialog.html
lib/content-services/src/lib/dialogs/library/library.dialog.scss

[ACS-7575] Create library dialog fixes

---

lib/content-services/src/lib/dialogs/folder.dialog.html
lib/content-services/src/lib/dialogs/folder.dialog.scss
lib/content-services/src/lib/dialogs/folder.dialog.ts

> - [X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-formt)
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7534 …

[ACS-7534] Create/edit folder dialog fixes

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
lib/process-services/src/lib/task-list/components/task-list.component.spec.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-22119 …

AAE-22119 Fix Datatable checkbox accessibility breaking change

---

lib/process-services-cloud/src/lib/services/variable-mapper.sevice.spec.ts
lib/process-services-cloud/src/lib/services/variable-mapper.sevice.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-21967
We should use sanitized …

AAE-21967 Use column id to reference process variables

---

lib/cli/package-lock.json
lib/core/package.json
lib/js-api/package.json

> - [ ] Bugfix
bump `angular-oauth2-oidc-jwks` for adf-core
bump `superagent` , …

Bump formidable and superagent in js-api and adf-cli

---

lib/core/src/lib/snackbar-content/snackbar-content.component.scss
lib/core/src/lib/styles/_mat-selectors.scss
lib/core/src/lib/styles/material.theme.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7560
Info notification has …

[ACS-7560] undo deletion notification

---

lib/core/src/lib/styles/material.theme.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7560
Info notification borders …

[ACS-7560] border radius info notification

---

lib/core/src/lib/context-menu/context-menu-list.component.html

> - [x] Bugfix
Context menu list component is not working properly
Context menu list …

AAE-21937 Fix context menu list component

---

lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/helpers/data-table-path-parser.helper.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/helpers/data-table-path-parser.helper.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/mocks/data-table-adapter.mock.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/mocks/data-table-path-parser.helper.mock.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-22345 …

AAE-22345 Support access to array elements by index

---

lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.scss

ACS-7561 - permissions page

---

lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts

> - [X] Bugfix
AAE-22037
AAE-22037 …

AAE-22037 Set static value for form variables in start event form

---

lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts

> - [X] Bugfix
https://hyland.atlassian.net/browse/AAE-12086 …

AAE-12086 The error message is shown for completed task with read-only fields [ADW]

---

cspell.json
lib/process-services-cloud/src/lib/form/components/widgets/display-rich-text/display-rich-text.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/display-rich-text/display-rich-text.widget.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-22612 …

AAE-22612 Fix unwanted comma in rich text editor

---

.github/workflows/pull-request.yml
.github/workflows/release.yml

AAE-22635 Auto upstream for hxp

---

lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-dialog.component.scss
lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html
lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.scss

[ACS-7998] - Add permissions input

---

lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.spec.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7474
There is no 'Expression …

[ACS-7474] - fix 'Expression has changed' Angular error in People facet

---

lib/content-services/src/lib/dialogs/folder.dialog.html
lib/content-services/src/lib/dialogs/folder.dialog.scss
lib/core/src/lib/styles/_mat-selectors.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7999
Styles for create/edit …

[ACS-7999] Fix inputs for edit and create folder

---

lib/content-services/src/lib/prediction/index.ts
lib/content-services/src/lib/prediction/public-api.ts
lib/content-services/src/lib/prediction/services/index.ts
lib/content-services/src/lib/prediction/services/prediction.service.spec.ts
lib/content-services/src/lib/prediction/services/prediction.service.ts
lib/content-services/src/public-api.ts
lib/js-api/index.ts
lib/js-api/src/alfrescoApi.ts
lib/js-api/src/api/hxi-connector-api/README.md
lib/js-api/src/api/hxi-connector-api/api/base.api.ts
lib/js-api/src/api/hxi-connector-api/api/index.ts
lib/js-api/src/api/hxi-connector-api/api/predictions.api.ts
lib/js-api/src/api/hxi-connector-api/docs/Prediction.md
lib/js-api/src/api/hxi-connector-api/docs/PredictionEntry.md
lib/js-api/src/api/hxi-connector-api/docs/PredictionPaging.md
lib/js-api/src/api/hxi-connector-api/docs/PredictionPagingList.md
lib/js-api/src/api/hxi-connector-api/docs/PredictionsApi.md
lib/js-api/src/api/hxi-connector-api/index.ts
lib/js-api/src/api/hxi-connector-api/model/index.ts
lib/js-api/src/api/hxi-connector-api/model/prediction.ts
lib/js-api/src/api/hxi-connector-api/model/predictionEntry.ts
lib/js-api/src/api/hxi-connector-api/model/predictionPaging.ts
lib/js-api/src/api/hxi-connector-api/model/predictionPagingList.ts
lib/js-api/src/index.ts
lib/js-api/src/to-deprecate/alfresco-api-type.ts

> - [ ] Bugfix
New API and service for predictions comming from HxI connector has been …

[ACS-8025] Add new service and API for predictions

---

lib/content-services/src/lib/tree/components/tree.component.html
lib/content-services/src/lib/tree/components/tree.component.spec.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7982
Tree chevrons are now …

[ACS-7982] ACC - fix categories tree

---

lib/process-services-cloud/package-lock.json
lib/process-services-cloud/package.json

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-22612 …

AAE-22612 Update process services cloud package json

---

lib/core/src/lib/form/components/form-renderer.component.scss
lib/core/src/lib/styles/_mat-selectors.scss

AAE-22783 Fix form elements label style

---

lib/core/src/lib/comments/comments.component.html
lib/core/src/lib/comments/comments.component.scss

[ACS-8021] Inputs for comments

---

lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.scss

[ACS-8008] - Inputs for properties panel "General info"

---

lib/core/src/lib/info-drawer/info-drawer.component.scss

[ACS-8052] inputs for general info for libraries

---

lib/core/src/lib/form/components/form-renderer.component.ts

> - [x] Bugfix
Import for UpperCasePipe was missing in form-renderer component.
Added …

Added missing import for UpperCasePipe

---

lib/core/src/lib/form/components/form-base.component.ts
lib/core/src/lib/form/components/widgets/core/form-outcome.model.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts

AAE-22720 Add a new "Skip validation" option in outcome properties

---

lib/core/src/lib/templates/error-content/error-content.component.html

> - [ ] Bugfix
Updated typography in error component as per material 15
Error component was using typography as per …

[ACS-8069] Updated error-content.component.html to be aligned with the new mat typography classes in angular material v15

---

lib/core/src/lib/styles/_mat-selectors.scss

> - [ ] Bugfix
Added missing selector
Selector for mat-list-item-disabled got lost in rebase, resulting in error in …

Added missing selector for mat-list-item-disabled 

---

lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7583
There are more symbols …

[ACS-7583] ACC tag rename get fail with some special char.

---

lib/core/src/lib/layout/components/layout-container/layout-container.component.spec.ts
lib/core/src/lib/layout/components/layout-container/layout-container.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-7552
Navbar gets disabled on resize of browser
**What is the …

[ACS-7552] - ACA menu column get disabled on resize of browser

---

lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts

> - [x] Bugfix
Add possibility to use sortkey as preset …

AAE-18917 Add possibility to use sortkey as preset

---

lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html
lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss
lib/content-services/src/lib/site-dropdown/sites-dropdown.component.html

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8066
Styles for inputs in link …

[ACS-8066] Style inputs for link rule dialog

---

lib/core/src/lib/dialogs/dialog/dialog.component.html

> - [x] Bugfix
Primary buttons left align without additional buttons.
Primary buttons …

[ACS-8104] Fix buttons alignment

---

lib/core/src/lib/form/components/form-renderer.component.spec.ts
lib/core/src/lib/form/components/form-renderer.component.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.html

AAE-22944 Disable form rules form read only form

---

docs/core/components/search-text-input.component.md
lib/core/src/lib/search-text/search-text-input.component.html
lib/core/src/lib/search-text/search-text-input.component.ts
lib/core/src/lib/styles/_mat-selectors.scss

[ACS-7973] [ACC] header layout

---

lib/content-services/src/lib/site-dropdown/sites-dropdown.component.spec.ts

> - [x] Bugfix
Unit tests for sites dropdown component were broken. 
Unit tests for …

[ACS-8066] fix unit tests

---

lib/core/src/lib/notifications/components/notification-history.component.html
lib/core/src/lib/notifications/components/notification-history.component.scss
lib/core/src/lib/styles/_mat-selectors.scss

[ACS-8092] [ACA] testing angular 15 notifications bell is much smaller and is further from the profile page 2

---

lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.scss

[ACS-8098] [ACA] Testing Angular 15 - Move Popup placeholder missing

---

lib/core/src/lib/dialogs/confirm-dialog/confirm.dialog.html
lib/core/src/lib/dialogs/confirm-dialog/confirm.dialog.scss
lib/core/src/lib/dialogs/confirm-dialog/confirm.dialog.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7980
styles are updated
**Does …

[ACS-7980][ACC] - Delete tag

---

lib/testing/src/lib/protractor/core/pages/material/date-picker-calendar.page.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-22965
fix changed selector for …

AAE-22965 fix datepicker focused element selector

---

package-lock.json

> - [ ] Bugfix
dependency update
https://hyland.atlassian.net/browse/AAE-23122 …

AAE-23122 bump braces version from 3.0.2 to 3.0.3

---

lib/core/src/lib/pagination/pagination.component.scss

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8196
arrows in good poosition …

[ACS-8196][ACC] pagination icon misplaced 

---

lib/core/src/lib/snackbar-content/snackbar-content.component.scss

> - [ ] Bugfix
UI for snackbars with long text content was broken
Snackbars having long text content, along with an …

[ACS-8230] Fixed UI for snackbars with long text content and action buttons

---

lib/core/src/lib/form/components/form-renderer.component.scss

[ACS-8231] [ADW] processes button styling on hover

---

docs/core/dialogs/dialog.md
docs/core/interfaces/dialog.interface.md
lib/core/src/lib/dialogs/dialog/dialog-data.interface.ts
lib/core/src/lib/dialogs/dialog/dialog.component.html
lib/core/src/lib/dialogs/dialog/dialog.component.spec.ts
lib/core/src/lib/dialogs/dialog/dialog.component.ts

https://hyland.atlassian.net/browse/ACS-8198
> - [ ] Bugfix
can't pass data to `contentComponent` …

[ACS-8198] [ADF] Add functionality to pass data to DialogComponet

---

lib/core/src/lib/card-view/components/card-view-arrayitem/card-view-arrayitem.component.html
lib/core/src/lib/card-view/components/card-view-arrayitem/card-view-arrayitem.component.scss

AAE-23144 Fix mat chip style from card view arrayitem

---

lib/cli/.eslintrc.json
lib/content-services/.eslintrc.json
lib/core/.eslintrc.json
lib/extensions/.eslintrc.json
lib/extensions/src/lib/extensions.module.ts
lib/process-services-cloud/.eslintrc.json
lib/process-services/.eslintrc.json
lib/testing/.eslintrc.json

> - [x] Bugfix
- restore the missing `ExtensionModule.forChild`
- mark the `forChild` …

Fix ExtensionsModule.forChild regression

---

scripts/webdriver-update-newest/update-to-newest-webdriver.sh

> - [ ] Bugfix
update-to-newest-webdriver.sh script is not compatible with non-mac based systems.  …

Updated update-to-newest-webdriver.sh to be compatible with linux

---

.github/workflows/release.yml

AAE-22822 Ci workflow dispatch

---

lib/core/src/lib/i18n/ar.json
lib/core/src/lib/i18n/cs.json
lib/core/src/lib/i18n/da.json
lib/core/src/lib/i18n/de.json
lib/core/src/lib/i18n/en.json
lib/core/src/lib/i18n/es.json
lib/core/src/lib/i18n/fi.json
lib/core/src/lib/i18n/fr.json
lib/core/src/lib/i18n/it.json
lib/core/src/lib/i18n/ja.json
lib/core/src/lib/i18n/nb.json
lib/core/src/lib/i18n/nl.json
lib/core/src/lib/i18n/pl.json
lib/core/src/lib/i18n/pt-BR.json
lib/core/src/lib/i18n/ru.json
lib/core/src/lib/i18n/sv.json
lib/core/src/lib/i18n/zh-CN.json

AAE-22837 Move dialog msg in core until nex major version

---

demo-shell/src/app/components/file-view/file-view.component.html
demo-shell/src/app/components/file-view/file-view.component.ts
demo-shell/src/app/components/file-view/file-view.module.ts
lib/core/src/lib/core.module.ts
lib/core/src/lib/info-drawer/info-drawer-layout.component.ts
lib/core/src/lib/info-drawer/info-drawer.component.html
lib/core/src/lib/info-drawer/info-drawer.component.stories.ts
lib/core/src/lib/info-drawer/info-drawer.component.ts
lib/core/src/lib/info-drawer/info-drawer.module.ts
lib/core/src/lib/login/login.module.ts
lib/process-services/src/lib/task-list/components/task-details/task-details.component.ts

Reverts Alfresco/alfresco-ng2-components#9846

Revert "ACS-8255: Migrate InfoDrawer component to Standalone"

---

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts
lib/process-services-cloud/src/lib/process/start-process/mock/start-process.component.mock.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-23379 …

AAE-23379 Fix - required attach file allows to start process

---

lib/process-services-cloud/src/lib/process/process-filters/components/process-filters-cloud.component.html
lib/process-services-cloud/src/lib/task/task-filters/components/base-task-filters-cloud.component.html

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-23478 …

AAE-23478 replace incorrect nav-list with action-list

---

lib/process-services/src/lib/process-list/components/start-process/start-process.component.scss

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8272 …

[ACS-8272] [ADW]  angular 15 upgrade misplaced buttons cancel and start process

---

lib/core/src/lib/form/components/form-renderer.component.html

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8273 …

[ACS-8273] [ADW] Testing Angular 15 - Process' tab names are uppercased

---

lib/core/src/lib/datatable/components/datatable/datatable.component.scss
lib/core/src/lib/dynamic-chip-list/dynamic-chip-list.component.scss

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8275 …

[ACS-8275] [ACA] Angular 15 tags are not displayed correctly

---

angular.json

Add angular.json file

---

lib/cli/scripts/audit.ts
lib/cli/scripts/check-cs-env.ts
lib/cli/scripts/check-plugin-env.ts
lib/cli/scripts/init-aae-env.ts
lib/cli/scripts/init-acs-env.ts
lib/cli/scripts/init-aps-env.ts
lib/cli/scripts/licenses.ts

Angular 16 migration - fix env scripts types

---

lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-23494 …

AAE-23494 Fix - Required Date field still allows user to submit form

---

lib/core/src/lib/search-text/search-text-input.component.html
lib/core/src/lib/search-text/search-text-input.component.scss
lib/core/src/lib/search-text/search-text-input.component.ts

AAE-23556 Search input component alignment

---

.github/workflows/release-branch.yml
lib/core/src/lib/common/services/log.service.ts

fix "affected" nx command

---

lib/core/src/lib/card-view/components/card-view-arrayitem/card-view-arrayitem.component.html
lib/core/src/lib/card-view/components/card-view-arrayitem/card-view-arrayitem.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-23622 …

AAE-23622 group restriction buttons

---

lib/core/src/lib/common/utils/date-fns-utils.spec.ts
lib/core/src/lib/common/utils/date-fns-utils.ts
lib/core/src/lib/form/components/widgets/core/form-field-validator.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.ts
lib/core/src/lib/form/components/widgets/date-time/date-time.widget.ts

> - [X] Bugfix
The dates are not properly parsed, we are not aware of timezones
**Does …

[AAE-23640] Fix dates

---

lib/core/src/lib/form/components/form-renderer.component.scss
lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
lib/process-services-cloud/src/lib/form/components/form-cloud.component.scss
lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.html
lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud.component.scss

AAE-23704 Fixed outcome buttons text alignment

---

lib/core/src/lib/auth/oidc/auth-config.service.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8301 …

[ACS-8301] -  Test the ADW integration with HXIAM

---

lib/content-services/src/lib/content-metadata/components/content-metadata/content-metadata.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8275 …

[ACS-8275] Testing Angular 15 - Tags are not displayed correctly

---

lib/core/src/lib/viewer/components/viewer.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8253 …

[ACS-8253] viewer file name change position on navigation

---

lib/core/src/lib/avatar/avatar.component.md
lib/core/src/lib/button/button.component.html
lib/core/src/lib/button/button.component.md
lib/core/src/lib/button/button.component.scss
lib/core/src/lib/button/button.component.ts

> - [x] Bugfix
- attribute rendering fixes for `adf-button`: do not render `undefined` …

ACS-8109: button component fixes

---

lib/content-services/src/lib/agent/services/agent.service.spec.ts
lib/content-services/src/lib/search-ai/services/search-ai.service.spec.ts
lib/js-api/src/api/content-rest-api/api/search-ai.api.ts
lib/js-api/test-results/.last-run.json
lib/js-api/test/content-services/agentsApi.spec.ts
lib/js-api/test/content-services/searchAiApi.spec.ts
lib/js-api/test/mockObjects/content-services/agent.mock.ts
lib/js-api/test/mockObjects/content-services/search-ai.mock.ts
lib/js-api/test/mockObjects/index.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8398
PR for adding unit tests …

[ACS-8398] Unit tests for agents and search ai 

---

lib/content-services/src/lib/search/components/search-text/search-text.component.scss

… 
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8444
Underline looks like …

[ACS-8444] - [ACA] Testing Angular 15 - Underline in filter boxes are not bolded

---

lib/cli/package-lock.json
lib/cli/package.json
lib/cli/project.json
scripts/update-version.sh

Fixing npm publish as cli is failing building with new js-api version

---

lib/core/feature-flags/src/lib/components/flags/flags.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/HXCS-4163 …

[HXCS-4163] aligned icons on dialog

---

lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
lib/core/src/lib/form/components/widgets/checkbox/checkbox.widget.html
lib/core/src/lib/form/components/widgets/checkbox/checkbox.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-24675 …

AAE-24675 Fix text alignment in dateitem card view element

---

lib/cli/scripts/init-aps-env.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8349 …

[ACS-8349] Update init-aps-env scripts with new API endpoints

---

.github/workflows/pull-request.yml
.github/workflows/release.yml

AAE-24980 Fix ADF release warning username message

---

.github/workflows/release.yml

AAE-25053 Remove wrong if statements from release ADF workflow

---

.lintstagedrc.json
lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
lib/core/src/lib/datatable/components/datatable/datatable.component.ts
lib/core/src/lib/icon/icon.component.scss
lib/core/src/lib/icon/icon.component.ts
lib/core/src/lib/info-drawer/info-drawer-layout.component.scss
lib/core/src/lib/viewer/components/viewer.component.scss

> - [x] Bugfix
- drop custom styles for the adf-icon
- fix Viewer icons
- fix Info …

[ACS-8498] [ACA] Testing Angular 15 - Toolbar buttons layout is broken

---

.github/workflows/release.yml

Reverts Alfresco/alfresco-ng2-components#10044

Revert "AAE-25053 Remove wrong if statements from release ADF workflow"

---

.github/workflows/pull-request.yml
.github/workflows/release.yml

AAE-24980 ADF release warning message fix

---

lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8503
Attached file name is …

[ACS-8503] Attached file icon properly aligned

---

lib/process-services/src/lib/task-list/components/task-standalone/task-standalone.component.html
lib/process-services/src/lib/task-list/components/task-standalone/task-standalone.component.scss

> - [ ] Bugfix
UI Fixes after ng15 upgrade
Standalone task form component had UI issues after ng15 upgrade
**What is …

[ACS-8211] Fixed UI issues in standalone task component after ng15 upgrade

---

lib/content-services/src/lib/search/components/search-control.component.spec.ts
lib/core/src/lib/layout/components/sidenav-layout/sidenav-layout.component.scss
lib/core/src/lib/search-text/search-text-input.component.html
lib/core/src/lib/search-text/search-text-input.component.scss
lib/core/src/lib/search-text/search-text-input.component.spec.ts
lib/core/src/lib/search-text/search-text-input.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8502 …

[ACS-8502] missing alignment for menu and search button

---

lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.scss

AAE-23521 Fix remove redundand margin

---

lib/core/src/lib/pagination/pagination.component.scss

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8447
Pagination buttons are …

[ACS-8447] Align pagination buttons

---

lib/core/src/lib/styles/_mat-selectors.scss

https://hyland.atlassian.net/browse/ACS-8458
> - [ ] Bugfix …

[ACS-8458] Review css selectors

---

docs/content-services/services/legal-hold.service.md
lib/content-services/src/lib/category/services/category.service.spec.ts
lib/content-services/src/lib/category/services/category.service.ts
lib/content-services/src/lib/common/services/nodes-api.service.ts
lib/content-services/src/lib/document-list/services/custom-resources.service.ts
lib/content-services/src/lib/legal-hold/services/legal-hold.service.ts
lib/content-services/src/lib/legal-hold/services/legal-holds.service.spec.ts
lib/content-services/src/lib/search/services/base-query-builder.service.ts
lib/core/src/lib/styles/_mat-selectors.scss
lib/extensions/src/lib/config/action.extensions.ts
lib/js-api/index.ts
lib/js-api/src/api/gs-core-rest-api/api/legal-hold.api.ts
lib/js-api/src/api/gs-core-rest-api/docs/BulkAssignHoldResponse.md
lib/js-api/src/api/gs-core-rest-api/docs/BulkHoldAddResponse.md
lib/js-api/src/api/gs-core-rest-api/docs/LegalHoldApi.md
lib/js-api/src/api/gs-core-rest-api/model/bulkAssignHoldResponse.ts
lib/js-api/src/api/gs-core-rest-api/model/bulkHoldAddResponse.ts
lib/js-api/src/api/gs-core-rest-api/model/index.ts
lib/js-api/src/constants/index.ts
lib/js-api/src/constants/language.constants.ts
lib/js-api/src/index.ts
lib/js-api/test/mockObjects/content-services/search.mock.ts
lib/js-api/test/searchApi.spec.spec.ts

https://hyland.atlassian.net/browse/ACS-8036
> - [ ] Bugfix …

[ACS-8036] [FE] Legal Hold in ADW. Part 2 (Bulk)

---

lib/core/src/lib/viewer/components/pdf-viewer/pdf-viewer.component.scss

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8371
Viewer toolbar page …

[ACS-8371] Fix viewer toolbar page selector

---

lib/cli/project.json
lib/js-api/project.json

Ordered builds for js-api to avoid racing condition on dist folder

---

lib/core/src/lib/pipes/pipe.module.ts

> - [x] Bugfix
- restore core pipes as providers in the CoreModule
**Does this PR …

Core Pipes backwards compatibility

---

lib/core/src/lib/core.module.ts
lib/core/src/lib/pipes/pipe.module.ts

Core pipes backward compatibility v2

---

lib/core/src/lib/auth/oidc/auth-config.service.spec.ts
lib/core/src/lib/auth/oidc/auth-config.service.ts

AAE-18154 Fix redirect post logout uri

---

demo-shell/package.json
docs/license-info/README.md
docs/license-info/license-info-7.0.0-alpha.2.md
docs/release-notes/README.md
docs/release-notes/RelNote-7.0.0-alpha.2.md
docs/vulnerability/README.md
docs/vulnerability/audit-info-7.0.0-alpha.2.md
lib/cli/package-lock.json
lib/cli/package.json
lib/content-services/package.json
lib/core/package.json
lib/eslint-angular/package.json
lib/extensions/package.json
lib/insights/package.json
lib/js-api/package.json
lib/process-services-cloud/package-lock.json
lib/process-services-cloud/package.json
lib/process-services/package.json
lib/testing/package.json
package-lock.json
package.json

> - [ ] Bugfix
> - [ ] Other... Please describe: Release PR …

Release 7.0.0-alpha.2

---

lib/content-services/src/lib/tag/tags-creator/tags-creator.component.spec.ts
lib/content-services/src/lib/tag/tags-creator/tags-creator.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8640 …

[ACS-8640] - unable to create tag with certain special characters

---

lib/content-services/src/lib/breadcrumb/breadcrumb.component.scss

> - [x] Bugfix
Root item in breadcrumb had alignment issue when it was the only item vs when there were more items. …

[ACS-6888] Fixed alignment issue in breadcrumb component

---

lib/content-services/src/lib/search/components/search-date-range-tabbed/search-date-range/search-date-range.component.spec.ts

JIRA TICKET: https://hyland.atlassian.net/browse/ACS-7747
> - [x] Bugfix
Test is flaky …

ACS-7747 Fix flaky test

---

lib/core/src/lib/notifications/components/notification-history.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8682
Allignments are fixed. …

[ACS-8682] - [ACA] alignment missing on notification message and photo on notifications popup

---

lib/process-services/src/lib/form/widgets/dropdown/dropdown.widget.ts

AAE-0000 Fix imports

---

lib/process-services-cloud/src/lib/task/task-filters/components/base-task-filters-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-filters/components/task-filters-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-filters/mock/task-filters-cloud.mock.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-25268 …

AAE-25268 Added output for updated filter

---

lib/testing/src/lib/protractor/process-services/pages/start-process.page.ts

> - [ ] Bugfix
process e2e locator and visibility check fix …

ACS-8733 process e2e locator fix

---

e2e/protractor.excludes.json
lib/testing/src/lib/protractor/process-services/pages/start-process.page.ts

> - [ ] Bugfix
exclude flaky test, need fix …

[ACS-8733] exclude flaky test need fix

---

lib/content-services/src/lib/services/alfresco-api.service.ts

AAE-25817 Fix for initializing alfresco API

---

e2e/protractor.excludes.json
lib/process-services/src/lib/process-list/components/start-process/start-process.component.ts

ACS-8760 Fix default process name

---

lib/core/src/lib/form/components/widgets/core/form.model.ts
lib/core/src/lib/form/components/widgets/display-text/display-text.widget.scss
lib/core/src/lib/form/components/widgets/header/header.widget.scss
lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.scss

AAE-25387 Styles preview

---

lib/core/src/lib/layout/components/layout-container/layout-container.component.scss

Fixed white background issue in sidenav after ng16 upgrade

---

docs/process-services/components/process-list.component.md
lib/process-services/src/lib/process-list/components/process-list/process-list.component.html
lib/process-services/src/lib/process-list/components/process-list/process-list.component.spec.ts
lib/process-services/src/lib/process-list/components/process-list/process-list.component.ts

> - [ ] Bugfix
There's no handling of selection in process list.
Added output emitting …

[ACS-8745] handle row selection in process list

---

lib/process-services-cloud/ng-package.json
lib/process-services-cloud/package.json

AAE-25569 Fix dependencies

---

lib/core/src/lib/i18n/en.json

AAE-26023 Unify look of style properties names

---

docs/breaking-changes/breaking-change-6.10.0-7.0.0.md

AAE-22996 Update breaking change v7.0.0 dock

---

lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.spec.ts
lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.ts
lib/process-services/src/lib/form/widgets/upload/upload.widget.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8635 …

[ACS-8635] ADW: View button not working on create process

---

lib/core/src/lib/form/services/form.service.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
lib/process-services-cloud/src/lib/services/notification-cloud.service.ts

AAE-24992 Form rules for fields

---

lib/content-services/src/lib/tag/tags-creator/tags-creator.component.scss

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8661 …

[ACS-8661] Metadata tags long text overflow regression (Angular 15)

---

lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
lib/process-services-cloud/src/lib/form/components/form-cloud.component.scss
lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-22043
Container always …

AAE-22043 Fix long form flow outside container

---

lib/core/src/lib/common/utils/datetime-fns-adapter.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-25339 …

AAE-25339 Fix ADF Datetime adapter display format date

---

lib/core/src/lib/auth/guard/auth-guard-sso-role.service.spec.ts
lib/core/src/lib/auth/guard/auth-guard.service.spec.ts
lib/core/src/lib/auth/oidc/oidc-authentication.service.spec.ts
lib/core/src/lib/auth/services/identity-user.service.spec.ts
lib/core/src/lib/auth/services/jwt-helper.service.spec.ts
lib/core/src/lib/auth/services/jwt-helper.service.ts
lib/core/src/lib/auth/services/user-access.service.spec.ts
lib/core/src/lib/core.module.ts
lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-26321 …

AAE-26321 Add an injection token to JwtHelperService for OAuthStorage

---

lib/core/src/lib/auth/guard/auth-guard-sso-role.service.spec.ts
lib/core/src/lib/auth/guard/auth-guard.service.spec.ts
lib/core/src/lib/auth/oidc/oidc-authentication.service.spec.ts
lib/core/src/lib/auth/services/identity-user.service.spec.ts
lib/core/src/lib/auth/services/jwt-helper.service.spec.ts
lib/core/src/lib/auth/services/jwt-helper.service.ts
lib/core/src/lib/auth/services/user-access.service.spec.ts
lib/core/src/lib/core.module.ts
lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts

Reverts Alfresco/alfresco-ng2-components#10288
a less disruptive, backwards compatible solution is in the works

Revert "AAE-26321 Add an injection token to JwtHelperService for OAuthStorage"

---

lib/core/src/lib/auth/services/jwt-helper.service.spec.ts
lib/core/src/lib/auth/services/jwt-helper.service.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-26321 …

AAE-26321 Custom JWT storage service optional injection token

---

.eslintrc.js
.github/workflows/pull-from-crowdin.yml
.github/workflows/release.yml
crowdin.yml

Implemented workflows to push and pull translation to/from Crowdin 
> - [ ] Bugfix …

AAE-24008 Crowdin sync implementation

---

.github/workflows/release.yml

Fixed release workflow to build all libs

---

.github/workflows/pull-request.yml

AAE-27234 Fix Nx cache is not working

---

lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.spec.ts
lib/process-services-cloud/src/lib/app/components/app-list-cloud.component.ts
lib/process-services-cloud/src/lib/app/mock/app-model.mock.ts
lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-service-task-filter-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/edit-task-filter-cloud.component.spec.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-25418 …

AAE-25417 Align app status to follow state machine

---

lib/cli/scripts/init-aae-env.ts

AAE-25417 Update status to Deployed

---

lib/core/src/lib/context-menu/context-menu-list.component.scss
lib/core/src/lib/context-menu/context-menu-list.component.ts
lib/core/src/lib/datatable/components/datatable/datatable.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.scss

> - [ ] Bugfix
Limited drag area for dragging datatable rows.
Added fixes for missing …

[ACS-8634] Additional fixes

---

lib/process-services-cloud/src/lib/process/process-list/public-api.ts
lib/process-services-cloud/src/lib/process/process-list/services/process-task-list-cloud.service.ts

> - [ ] Bugfix
This service is used only in hxp and reverted mistakenly …

Revert mistakenly deleted file

---

lib/content-services/src/lib/search/components/search-date-range-tabbed/search-date-range/search-date-range.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8916
Icon is placed correctly …

[ACS-8916] [ACA] The calendar button in advanced search filters is placed too low in the date dialog

---

lib/content-services/src/lib/document-list/data/share-data-row.model.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-27309 …

AAE-27309 Add selectable property to datatable row

---

lib/core/api/src/lib/adf-http-client.service.spec.ts
lib/core/api/src/lib/adf-http-client.service.ts
lib/core/src/lib/auth/basic-auth/basic-alfresco-auth.service.spec.ts
lib/core/src/lib/auth/basic-auth/basic-alfresco-auth.service.ts

> - [x] Bugfix
APS login via Basic Auth was not working from ADF 6.5.0
APS login via …

[MNT-24614] Fixed APS basic auth login issue with ADF

---

lib/content-services/src/lib/mock/permission-list.component.mock.ts
lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.html
lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.scss
lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.spec.ts
lib/content-services/src/lib/permission-manager/components/permission-list/permission-list.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/MNT-24689
Options which user can't …

[MNT-24689] the add user or group icon is displayed within the folder permissions for a user with the collaborator role

---

lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-8919
Transition causing …

[ACS-8919] [ACA] Search / Advanced Search Facets / The borders of search facets thickens very slowly when clicked

---

lib/core/src/lib/datatable/data/data-table.schema.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts

> - [x] Bugfix
After changing columns visibility, we are not sending request for fetching new `processes/tasks` …

AAE-28286 Show process variables columns in datatable fix

---

lib/process-services-cloud/src/lib/models/filter-cloud-model.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts

> - [x] Bugfix
We are sending wrong payload for getting process variables for new PAI …

AAE-28333 Fix search process variabels payload for new API

---

lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts

AAE-28286 Clean redundant log

---

lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-28529
process list shows …

AAE-28529 Fix process list loading

---

lib/process-services-cloud/src/lib/models/filter-cloud-model.ts
lib/process-services-cloud/src/lib/process/process-list/services/process-task-list-cloud.service.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-28584 …

AAE-28584 Fix process tasks not showing after clicking in the list

---

lib/process-services-cloud/src/lib/models/filter-cloud-model.ts
lib/process-services-cloud/src/lib/models/process-variable-filter.model.ts
lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts
lib/process-services-cloud/src/public-api.ts

AAE-27328 Add process variables to the search for searching Tasks

---

lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
lib/core/src/lib/card-view/components/card-view/card-view.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-27113 …

[AAE-27113] Align edit assignee button correctly in process admin user task property editor

---

lib/process-services-cloud/src/lib/services/web-socket.service.ts

AAE-20808 Adding support for ws protocol in websocket service

---

lib/process-services-cloud/src/lib/services/web-socket.service.ts

AAE-20808 Fixed websocket protocol

---

lib/core/src/lib/form/models/form-rules.model.ts

AAE-28801 Make "FormRulesManager.onDestroy$" available for derived classes

---

lib/process-services-cloud/src/lib/models/filter-cloud-model.ts
lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts

Add process name to new API request body

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.scss
lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts
lib/core/src/lib/datatable/components/datatable/datatable.component.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.html
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts

AAE-28454 Improve datatable actions display

---

lib/process-services/src/lib/form/widgets/people/people.widget.html
lib/process-services/src/lib/form/widgets/people/people.widget.spec.ts
lib/process-services/src/lib/form/widgets/people/people.widget.ts
lib/process-services/src/lib/i18n/en.json

> - [ ] Bugfix
https://hyland.atlassian.net/browse/MNT-24657
Multiple selection …

[MNT-24657] Add multiple selection support for people widget

---

lib/core/src/lib/pipes/truncate.pipe.ts

[ACS-9012] Add missing null check for truncate pipe

---

lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.html
lib/process-services-cloud/src/lib/task/task-list/components/base-task-list-cloud.component.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-28454 …

AAE-28454 Add column merge to admin tasklist component

---

lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-29108 …

Add processInstanceId and parentId to new API request body

---

lib/content-services/src/lib/new-version-uploader/new-version-uploader.dialog.scss
lib/content-services/src/lib/new-version-uploader/new-version-uploader.dialog.ts
lib/core/src/lib/auth/oidc/auth.module.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-9052
Button position is …

[ACS-9052] manage versions close button is too low

---

lib/core/src/lib/pipes/public-api.ts

> - [x] Bugfix
Pipe was not properly exported.
Pipe is properly exported
**Does this …

Truncate pipe export fix

---

lib/core/src/lib/datatable/components/datatable/datatable.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-9015
More specific selector has …

[ACS-9015] Add more specific selector

---

lib/core/ng-package.json
lib/core/package.json

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-7905 …

[ACS-7905] ADF Core lib is missing dependency declaration

---

lib/process-services-cloud/src/lib/models/filter-cloud-model.ts
lib/process-services-cloud/src/lib/models/task-list-sorting.model.ts
lib/process-services-cloud/src/lib/process/process-list/components/process-list-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-list/models/process-cloud-query-request.model.ts
lib/process-services-cloud/src/lib/process/process-list/models/process-list-sorting.model.ts
lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-29219
https://hyland.atlassian.net/browse/AAE-29217
**What is …

AAE-29217 Align properties with user task and process instance search API

---

lib/process-services-cloud/src/lib/app/models/application-instance.model.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-11353 …

AAE-11353 Add canAccessAudit property

---

lib/core/src/lib/datatable/components/columns-selector/columns-selector.component.html
lib/core/src/lib/datatable/components/columns-selector/columns-selector.component.spec.ts

AAE-28910 Remove process icon from column selector

---

lib/core/src/lib/styles/_mat-selectors.scss
lib/core/src/lib/styles/material.theme.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-9075
Buttons color is correct …

[ACS-9075] buttons texts have different color

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html

AAE-29042 Added subtitle to arial-label

---

lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts
lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-29345
It's possible to filter …

AAE-29345 Add date filtering to service tasks page

---

lib/process-services-cloud/src/lib/task/task-list/components/service-task-list-cloud.component.ts

Fix change committed by mistake to service task request

---

lib/core/src/lib/datatable/components/columns-selector/columns-selector.component.ts

AAE-29501 Remove lodash-es import from columns selector

---

lib/process-services-cloud/src/lib/task/task-form/components/task-form-cloud/task-form-cloud.component.scss

> - [x] Bugfix
Long forms are not scrollable.
https://hyland.atlassian.net/browse/AAE-29885 …

AAE-29885 Fix form not scrollable

---

lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.ts
lib/process-services-cloud/src/lib/task/task-filters/models/filter-cloud.model.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-29942 …

AAE-29942 Make it possible to use URL params with new task and process API

---

lib/process-services-cloud/src/lib/models/process-variable-filter.model.ts

Add "ne" filter operator - 'not equal'
> - [ ] Bugfix …

AAE-29995 Add "ne" filter operator

---

lib/process-services-cloud/src/lib/task/task-filters/components/edit-task-filters/base-edit-task-filter-cloud.component.ts

Fix error in PR 10575

---

lib/process-services-cloud/src/lib/models/filter-cloud-model.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-29996
Saved task filter …

AAE-29996 Fix task filter counters in new API

---

lib/cli/package-lock.json
lib/cli/package.json
lib/content-services/package.json
lib/core/package.json
lib/eslint-angular/package.json
lib/extensions/package.json
lib/insights/package.json
lib/js-api/package.json
lib/process-services-cloud/package.json
lib/process-services/package.json
package-lock.json
package.json

Post release version bump

---

docs/core/services/saved-searches.service.md
lib/content-services/src/lib/common/services/saved-searches.service.spec.ts
lib/content-services/src/lib/common/services/saved-searches.service.ts
lib/js-api/src/api/content-rest-api/api/preferences.api.ts
lib/js-api/src/api/content-rest-api/docs/PreferencesApi.md

Reverts Alfresco/alfresco-ng2-components#10566
Brings back changes from https://github.com/Alfresco/alfresco-ng2-components/pull/10559

[ACS-9166] Migrate Saved Searches to preferences API from config file

---

lib/core/src/lib/form/components/widgets/date-time/date-time.widget.spec.ts
lib/core/src/lib/form/components/widgets/date-time/date-time.widget.ts
lib/core/src/lib/form/components/widgets/date/date.widget.spec.ts
lib/core/src/lib/form/components/widgets/date/date.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/file-viewer/file-viewer.widget.ts
lib/process-services/src/lib/form/widgets/dropdown/dropdown.widget.spec.ts
lib/process-services/src/lib/form/widgets/dropdown/dropdown.widget.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-30596 …

AAE-30596 Fix required reactive widgets do not visibility conditions

---

lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
lib/process-services-cloud/src/lib/people/components/people-cloud.component.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-30771 …

AAE-30771 Show username on hover in people component

---

lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts

AAE-30563 Fix for IsRequired for dropdown

---

package-lock.json
package.json

AAE-0000 - removing protractor dependencies

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.spec.ts

> - [x] Bugfix
[See AAE-28655](https://hyland.atlassian.net/browse/AAE-28655?atlOrigin=eyJpIjoiNDg4MzI5YWFlMDFiNDUxZjk …

AAE-28655 Fix for datatable not scrolling back up after paginations

---

lib/content-services/karma.conf.js
lib/core/karma.conf.js
lib/extensions/karma.conf.js
lib/insights/karma.conf.js
lib/process-services-cloud/karma.conf.js
lib/process-services/karma.conf.js

> - [ ] Bugfix
> Developer experience improvement
https://hyland.atlassian.net/issues/?filter=31844 …

AAE-25579 Toggle logs for skipped karma unit tests

---

lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip-tabbed/search-facet-chip-tabbed.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-facet-chip/search-facet-chip.component.spec.ts
lib/content-services/src/lib/search/components/search-filter-chips/search-filter-chips.component.html
lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.html

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-9230 …

[ACS-9230] a11y testing: Search Page / Search Filters / Certain ARIA roles must contain particular children

---

lib/core/src/lib/form/components/form-field/form-field.component.html
lib/core/src/lib/form/components/form-field/form-field.component.spec.ts
lib/core/src/lib/form/components/form-renderer.component.html
lib/core/src/lib/form/components/form-renderer.component.scss
lib/core/src/lib/form/components/form-renderer.component.spec.ts
lib/core/src/lib/form/components/form-renderer.component.ts
lib/core/src/lib/form/components/form-section/form-section.component.html
lib/core/src/lib/form/components/form-section/form-section.component.scss
lib/core/src/lib/form/components/form-section/form-section.component.spec.ts
lib/core/src/lib/form/components/form-section/form-section.component.ts
lib/core/src/lib/form/components/mock/form-renderer.component.mock.ts
lib/core/src/lib/form/components/mock/form.mock.ts
lib/core/src/lib/form/components/widgets/core/container-column.model.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.ts
lib/core/src/lib/form/components/widgets/core/form.model.spec.ts
lib/core/src/lib/form/components/widgets/core/form.model.ts
lib/core/src/lib/form/components/widgets/display-text/display-text.widget.scss
lib/process-services/src/lib/form/form.component.visibility.spec.ts
lib/process-services/src/lib/task-list/components/task-form/task-form.component.spec.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-30110 …

AAE-30110 Render sections in runtime

---

lib/cli/package-lock.json
lib/cli/package.json
lib/content-services/package.json
lib/core/package.json
lib/eslint-angular/package.json
lib/extensions/package.json
lib/insights/package.json
lib/js-api/package.json
lib/process-services-cloud/package.json
lib/process-services/package.json
package-lock.json
package.json

AAE-0000 - bumping the prerelease version

---

lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.ts
lib/core/src/lib/styles/_components-variables.scss
lib/core/src/lib/styles/_reference-variables.scss
lib/process-services/src/lib/form/widgets/functional-group/functional-group.widget.html
lib/process-services/src/lib/form/widgets/functional-group/functional-group.widget.scss
lib/process-services/src/lib/form/widgets/functional-group/functional-group.widget.spec.ts
lib/process-services/src/lib/form/widgets/functional-group/functional-group.widget.ts
lib/process-services/src/lib/form/widgets/people/people.widget.html
lib/process-services/src/lib/form/widgets/people/people.widget.scss
lib/process-services/src/lib/form/widgets/people/people.widget.spec.ts
lib/process-services/src/lib/form/widgets/people/people.widget.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/MNT-24456
Task's forms accept now …

[MNT-24456] aps with adw multi user and group fields do not accept multiple values

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-9223
Mentioned a11y issue …

[ACS-9223] a11y testing: Data Table - Form elements must have labels

---

lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-31453 …

AAE-31453 Correct disabled text cardview color

---

docs/content-services/components/document-list.component.md
lib/content-services/src/lib/document-list/components/document-list.component.html
lib/content-services/src/lib/document-list/components/document-list.component.spec.ts
lib/content-services/src/lib/document-list/components/document-list.component.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-8782
Allowed to hide hint for …

[ACS-8782] list of frozen files under a hold

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html

> - [ ] Bugfix
Accessibility fixed
Certain elements within the datatable component were lacking proper roles
**What …

[ACS-9224] Fixed critical accessibility issues in datatable.component

---

lib/content-services/src/lib/aspect-list/aspect-list.component.html
lib/content-services/src/lib/aspect-list/aspect-list.component.scss
lib/content-services/src/lib/aspect-list/aspect-list.component.spec.ts
lib/content-services/src/lib/aspect-list/aspect-list.component.ts

… be nested
> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-9233
a11y issues …

[ACS-9233] a11y testing: Edit Aspects - Interactive controls must no be nested

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html

Fix/[ACS-9224]  Revert fixed critical accessibility issues in datatable.component 

---

lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.ts

AAE-32478 Asynchronous Form - update datatable on variable change

---

lib/process-services-cloud/src/lib/task/task-form/components/user-task-cloud/user-task-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-form/components/user-task-cloud/user-task-cloud.component.ts

> - [x] Bugfix
Missing error handling when loading the task from TaskCloudService. …

AAE-32493 Add error handling for loading task

---

.github/workflows/pull-request.yml
nx.json

> - [ ] Bugfix
> - [x] Other... Please describe: Unit Test pipeline fix.
process-services-cloud is not considered when process-services is excluded. …

[AAE-32862] Unit Tests not triggered in pull request for alfresco-ng2-components (process-services-cloud)

---

lib/core/src/lib/styles/prebuilt/adf-blue-purple.scss
lib/core/src/lib/styles/prebuilt/adf-indigo-pink.scss
lib/core/src/lib/styles/prebuilt/adf-pink-bluegrey.scss
lib/core/src/lib/styles/prebuilt/adf-purple-green.scss
package-lock.json

Fix angular materials palletes

---

lib/cli/package-lock.json
lib/cli/package.json
lib/content-services/package.json
lib/core/package.json
lib/eslint-angular/package.json
lib/extensions/package.json
lib/insights/package.json
lib/js-api/package.json
lib/process-services-cloud/package.json
lib/process-services/package.json
package-lock.json
package.json

> - [ ] Bugfix
> - [x] Other... Please describe: Post-release version bump …

Post-release version bump

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-9375
Hovered spinner has …

[ACS-9375] Transparent background for hovered spinner

---

lib/core/src/lib/form/components/widgets/core/form-field.model.spec.ts
lib/core/src/lib/form/components/widgets/core/form-field.model.ts

AAE-33054 Fix undefiend tooltip

---

lib/core/src/lib/form/components/widgets/date-time/date-time.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.ts

AAE-33137 Asynchronous Form Enrichment does Not Populate Date Fields

---

lib/core/src/lib/i18n/en.json
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table-adapter.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/helpers/data-table-path-parser.helper.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/helpers/data-table-path-parser.helper.ts
lib/process-services-cloud/src/lib/form/components/widgets/data-table/mocks/data-table-widget.mock.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-33007 …

AAE-33007 Display empty data table without error

---

lib/process-services-cloud/src/lib/form/services/spinner/form-cloud-spinner.service.spec.ts
lib/process-services-cloud/src/lib/form/services/spinner/form-cloud-spinner.service.ts

AAE-33340 Async Form Enrichment - Spinner doesnt hide on process completion

---

lib/core/src/lib/form/components/widgets/core/form-field.model.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.spec.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/validators.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-33449
https://hyland.atlassian.net/browse/HXPMNT-748
**What is …

AAE-33449 HXPMNT-748 Hidden dropdown validation

---

.github/actions/before-install/action.yml
.github/workflows/pull-request.yml

> - [ ] Bugfix
We have to commit or rerun it by our selfs.
Github rerun the pipeline …

AAE-29010 Github actions rerun after first approval

---

.github/actions/before-install/action.yml
.github/workflows/pull-request.yml

> - [ ] Bugfix
We have to commit or rerun it by our selfs.
Github rerun the pipeline …

AAE-29010 GH actions rerun after approval

---

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-34135 …

AAE-34135 Confirmation on StartProcess

---

docs/upgrade-guide/upgrade-6.9.0-7.0.0.md
lib/core/src/lib/datatable/components/datatable/datatable.component.html

[ACS-9454] Create upgrade guide for ADF 7.0.0

---

lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.html
lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.spec.ts
lib/process-services/src/lib/form/widgets/content-widget/attach-file-widget.component.ts

> - [X] Bugfix
https://hyland.atlassian.net/browse/MNT-24950
Preview button state is not correct in some cases
**What …

[MNT-24950] Fix process file preview button state

---

lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.scss
lib/process-services-cloud/src/lib/form/components/widgets/data-table/data-table.widget.spec.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-33955 …

AAE-33955 Add placeholder for data table widget (preview)

---

.github/actions/before-install/action.yml
.github/workflows/pull-request.yml

This reverts commit f6c446498a79aa25981525e3f87ef50f78e120c7.
> - [ ] Bugfix
**Does …

Revert "AAE-29010 GH actions rerun after approval (#10772) (#10774)" - [AAE-34422] for details

---

lib/core/src/lib/form/components/widgets/amount/amount.widget.html

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-34328?focusedCommentId=2352338 …

AAE-34328 Remove additional space in amount widget currency

---

.github/actions/create-git-tag/create-git-tag.js

AAE-34426 Simulate a change to upstream adf

---

lib/process-services-cloud/src/lib/task/task-list/components/task-list/task-list-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-list/components/task-list/task-list-cloud.component.ts

AAE-33589 Get task variables when preferences are loaded

---

docs/core/components/viewer.component.md
lib/core/src/lib/viewer/components/pdf-viewer/pdf-viewer.component.spec.ts
lib/core/src/lib/viewer/components/pdf-viewer/pdf-viewer.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-34470 …

AAE-34470 Ignore content type of fetched pdfjs worker

---

lib/core/src/lib/styles/_index.scss

https://hyland.atlassian.net/browse/AAE-34497

AAE-34497 fix datetime picker theming

---

lib/core/src/lib/form/components/form-renderer.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-34594 …

AAE-34594 Remove redundant scroll bar from form renderer

---

lib/core/src/lib/form/components/form-renderer.component.scss
lib/process-services-cloud/src/lib/people/components/people-cloud.component.html

AAE-34335 Fix for styling discrepancies in form widgets

---

lib/core/src/lib/form/components/form-renderer.component.scss

AAE-34869 fixing padding issue

---

lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.ts

> - [ ] Bugfix
Open next task checkbox was shown in the "Start Process" view.
Open …

AAE-34731 Hide the open next task checkbox for the Start Process view

---

lib/process-services-cloud/src/lib/form/components/form-cloud.component.scss

AAE-34888 Fix overflows issue the last portion of the form is not visible

---

lib/core/src/lib/viewer/components/pdf-viewer/pdf-viewer.component.html
lib/core/src/lib/viewer/components/pdf-viewer/pdf-viewer.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-34826 …

AAE-34826 Incorrect scale for rendered pdf documents

---

crowdin.yml

> - [ ] Bugfix
Replace update_as_unapprovedwithupdate_without_changesin the root crowdin.yml file in …

AAE-34992 Improve crowdin update strategy

---

lib/core/src/lib/form/components/form-renderer.component.html
lib/core/src/lib/form/components/form-renderer.component.scss
lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
lib/process-services-cloud/src/lib/form/components/form-cloud.component.scss

AAE-34885 Form with tabs has incomplete frame in preview

---

lib/process-services-cloud/src/lib/form/components/form-cloud.component.html

> - [x] Bugfix
https://hyland.atlassian.net/browse/AAE-34479
Custom outcome button has …

AAE-34479 Added class for custom outcome button

---

lib/process-services-cloud/src/lib/form/components/form-cloud.component.scss

> - [X] Bugfix
https://hyland.atlassian.net/browse/AAE-35057
Scrollbar shown for full …

AAE-35057 Show Scrollbars on adf-cloud-form-content-card-fullscreen

---

lib/cli/package.json
lib/content-services/src/lib/dialogs/download-zip/download-zip.dialog.spec.ts
lib/content-services/src/lib/document-list/services/folder-actions.service.spec.ts
lib/core/package.json
lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
lib/process-services/src/lib/form/form.component.spec.ts
lib/process-services/src/lib/form/services/ecm-model.service.spec.ts
package-lock.json
package.json
tools/doc/package.json

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-9696
Version of rxjs is …

[ACS-9696] fix failing upgrade rxjs from 7.8.1 to 7.8.2

---

lib/core/src/lib/auth/basic-auth/basic-alfresco-auth.service.spec.ts
lib/core/src/lib/auth/oidc/oidc-authentication.service.spec.ts
lib/core/src/lib/auth/services/authentication.service.spec.ts
lib/core/src/lib/auth/services/base-authentication.service.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-35521 …

AAE-35521 Refactor AuthenticationService unit tests

---

lib/js-api/src/api/gs-core-rest-api/api/filePlans.api.ts
lib/js-api/src/api/gs-core-rest-api/docs/FilePlanRoleParametersWhere.md
lib/js-api/src/api/gs-core-rest-api/model/filePlanRoleParametersWhere.ts
lib/js-api/test/governance-services/filePlansApi.spec.ts
lib/js-api/test/mockObjects/goverance-services/file-plans.mock.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/MNT-24923
Possibility to filter …

[MNT-24923] legal hold hold capabilities are not verified properly

---

lib/core/src/lib/card-view/components/card-view/card-view.component.scss
lib/core/src/lib/form/components/form-renderer.component.scss
lib/core/src/lib/form/components/inplace-form-input/inplace-form-input.component.html
lib/core/src/lib/form/components/inplace-form-input/inplace-form-input.component.scss
lib/core/src/lib/form/components/widgets/amount/amount.widget.html
lib/core/src/lib/form/components/widgets/date-time/date-time.widget.html
lib/core/src/lib/form/components/widgets/date/date.widget.html
lib/core/src/lib/form/components/widgets/decimal/decimal.component.html
lib/core/src/lib/form/components/widgets/multiline-text/multiline-text.widget.html
lib/core/src/lib/form/components/widgets/number/number.widget.html
lib/core/src/lib/form/components/widgets/text/text.widget.html
lib/process-services-cloud/src/lib/form/components/form-cloud.component.scss

…stency with studio-hxp
> - [ ] Bugfix …

AAE-34902 Updating styles for input controls to maintain the ui consistency with studio hxp

---

lib/process-services-cloud/src/lib/task/services/task-cloud.service.spec.ts

> - [ ] Bugfix
Unit tests
https://hyland.atlassian.net/browse/AAE-35632 …

AAE-35632 Priority filter unit tests

---

lib/core/src/lib/form/components/form-renderer.component.scss
lib/core/src/lib/form/components/form-section/form-section.component.scss
lib/core/src/lib/form/components/widgets/amount/amount.widget.html
lib/core/src/lib/form/components/widgets/amount/amount.widget.scss
lib/core/src/lib/form/components/widgets/checkbox/checkbox.widget.html
lib/core/src/lib/form/components/widgets/checkbox/checkbox.widget.scss
lib/core/src/lib/form/components/widgets/checkbox/checkbox.widget.ts
lib/core/src/lib/form/components/widgets/date-time/date-time.widget.html
lib/core/src/lib/form/components/widgets/date-time/date-time.widget.scss
lib/core/src/lib/form/components/widgets/date/date.widget.html
lib/core/src/lib/form/components/widgets/date/date.widget.scss
lib/core/src/lib/form/components/widgets/date/date.widget.ts
lib/core/src/lib/form/components/widgets/decimal/decimal.component.html
lib/core/src/lib/form/components/widgets/multiline-text/multiline-text.widget.scss
lib/core/src/lib/form/components/widgets/number/number.widget.html
lib/core/src/lib/form/components/widgets/number/number.widget.scss
lib/core/src/lib/form/components/widgets/text/text.widget.html
lib/core/src/lib/form/components/widgets/text/text.widget.scss
lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/date/date-cloud.widget.scss
lib/process-services-cloud/src/lib/form/components/widgets/display-rich-text/display-rich-text.widget.scss
lib/process-services-cloud/src/lib/form/components/widgets/radio-buttons/radio-buttons-cloud.widget.scss

AAE-35310  Displaying different text fields on an eform doesn't align vertically or horizontally

---

lib/core/src/lib/form/components/form-renderer.component.scss

AAE-36112 Fix small devices

---

lib/core/src/lib/viewer/components/img-viewer/img-viewer.component.scss
lib/core/src/lib/viewer/components/unknown-format/unknown-format.component.scss
lib/core/src/lib/viewer/components/viewer-render/viewer-render.component.scss
lib/core/src/lib/viewer/components/viewer.component.scss

[AAE-36397] ADF viewer image is no longer cropped

---

lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-9789 …

[ACS-9789] Multiple styles issues for metadata sidebar

---

lib/core/src/lib/landing-page/index.ts
lib/core/src/lib/landing-page/provider.ts
lib/core/src/lib/landing-page/public-api.ts
lib/core/src/public-api.ts

AAE-36718 Expose a landing page provider for the landing-page-token

---

lib/core/src/lib/form/components/form-renderer.component.scss

AAE-36388 Alignment issue observed on form when multiple fields are set in one row

---

lib/core/src/lib/form/components/widgets/amount/amount.widget.scss

AAE-36023 fixing alignments and cropping issues on apa and workspace

---

lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.html
lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.scss
lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.html
lib/core/src/lib/card-view/components/card-view-textitem/card-view-textitem.component.scss
lib/core/src/lib/card-view/components/card-view/card-view.component.scss

AAE-36368 Multiple styles issues for metadata sidebar

---

lib/core/src/lib/form/components/widgets/text/text-mask.component.ts

AAE-36716 Fixing text form field blur mechanism in control Value Accessor

---

docs/core/components/viewer.component.md
lib/core/src/lib/viewer/components/viewer.component.html
lib/core/src/lib/viewer/components/viewer.component.scss
lib/core/src/lib/viewer/components/viewer.component.spec.ts
lib/core/src/lib/viewer/components/viewer.component.ts

JIRA TICKET:
https://hyland.atlassian.net/browse/AAE-25571
> - [ ] Bugfix
Only fileName is displayed in adf-viewer.
Title is display next to the …

AAE-25571 Add title to file name [ng18-backup update]

---

lib/core/src/lib/form/components/widgets/amount/amount.widget.scss

AAE-36023 Some form fields are not properly aligned and cropped out

---

package-lock.json
package.json

AAE-0000 It was not possible to install directly due to broken dep

---

lib/core/src/lib/form/components/widgets/amount/amount.widget.scss
lib/process-services/src/lib/form/widgets/functional-group/functional-group.widget.html
lib/process-services/src/lib/form/widgets/people/people.widget.html

AAE-36023 Some form fields are not properly aligned and cropped out ng19

---

scripts/github/build/npm-check-bundles.sh

Removed esm2022 check as is not supported anymore since Ng18

---

lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
lib/process-services/src/lib/form/widgets/functional-group/functional-group.widget.html
lib/process-services/src/lib/form/widgets/people/people.widget.html

AAE-36023 fixing auto floating issue and removing hardcoded appearance

---

lib/process-services-cloud/src/lib/people/components/people-cloud.component.html
lib/process-services/src/lib/form/widgets/functional-group/functional-group.widget.html
lib/process-services/src/lib/form/widgets/people/people.widget.html

AAE-36023 Making develop sync with ng18 backup branch

---

lib/core/src/lib/form/components/form-section/form-section.component.scss

AAE-36414 Section Mobile view fix

---

lib/core/src/lib/form/components/form-renderer.component.scss
lib/core/src/lib/form/components/widgets/amount/amount.widget.scss
lib/core/src/lib/form/components/widgets/date-time/date-time.widget.scss

AAE-36388 Form-field oneline alignment issue fix

---

lib/core/src/lib/form/components/form-renderer.component.html
lib/core/src/lib/form/components/widgets/core/form.model.spec.ts
lib/core/src/lib/form/components/widgets/core/form.model.ts

AAE-36536 Allow form sections to be at the root level of form

---

lib/core/src/lib/form/components/form-renderer.component.html
lib/core/src/lib/form/components/widgets/core/form.model.spec.ts
lib/core/src/lib/form/components/widgets/core/form.model.ts

AAE-36536 Allow form sections to be at the root level of form - [ng18-backup]

---

lib/core/src/lib/form/components/form-section/form-section.component.spec.ts
lib/core/src/lib/form/components/form-section/form-section.component.ts

AAE-36536 fix for root section and mobile form input layout - ng18-backup

---

lib/core/src/lib/i18n/en.json
lib/core/src/lib/search-text/search-text-input.component.html
lib/core/src/lib/search-text/search-text-input.component.spec.ts

AAE-36983 Updated translation keys in search-text-input.component.html

---

lib/core/src/lib/datatable/components/datatable/datatable.component.html
lib/core/src/lib/datatable/components/datatable/datatable.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/MNT-25110 …

[MNT-25110] Unwanted duplicated Horizontal scrollbar

---

lib/core/src/lib/form/components/form-section/form-section.component.scss

AAE-36538 Removed flex-direction:column for form section column on large screens

---

lib/core/karma.conf.js
lib/js-api/jest.config.ts
lib/js-api/src/test-setup.ts
package-lock.json
package.json

https://hyland.atlassian.net/browse/AAE-35934

AAE-35934 Cleanup dependencies

---

lib/core/src/lib/form/components/form-renderer.component.html
lib/core/src/lib/form/components/form-renderer.component.scss
lib/core/src/lib/form/components/form-section/form-section.component.scss
lib/process-services-cloud/src/lib/form/components/widgets/display-external-property/display-external-property.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.html
lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts

Ticket: https://hyland.atlassian.net/browse/AAE-36582
> - [x] Bugfix
Form elements were collapsing vertically/horizontally on diffrent screens
Form elements are correctly displayed …

AAE-36582 Fix forms misalignment in form renderer [ng18 backup]

---

lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.html
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.scss
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/start-process/components/start-process-cloud.component.ts

Handles cases where the error message from the backend is not a valid JSON.
If the message is not a valid JSON, it displays the error as a string.
This prevents the application from crashing when receiving error messages with wrong JSON format.
Fixes AAE-36869

AAE-36869 Handles error messages with wrong JSON format

---

lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.html
lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts

https://hyland.atlassian.net/browse/AAE-37006
> - [ ] Yes …

AAE-37006 Fix floating label overlapping in dateitem component

---

lib/core/src/lib/dynamic-chip-list/dynamic-chip-list.component.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-9978 …

[ACS-9978] DynamicChipListComponent not rendered as expected

---

lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.html
lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.spec.ts
lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.html
lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.spec.ts
lib/core/src/lib/card-view/components/card-view/card-view.component.spec.ts
lib/process-services-cloud/src/lib/process/process-header/components/process-header-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts
lib/process-services/src/lib/attachment/task-attachment-list/task-attachment-list.component.spec.ts
lib/process-services/src/lib/process-list/components/process-instance-header/process-instance-header.component.spec.ts

This reverts commit 9b6688ce10d2cbf68ca4d041050f974464f8a8de.
> - [ ] Bugfix
**Does …

Revert "CSX-73 Date and Select Satori (#11056)"

---

docs/license-info/README.md
docs/license-info/license-info-8.1.1.md
docs/release-notes/README.md
docs/release-notes/RelNote-8.1.1.md
docs/vulnerability/README.md
docs/vulnerability/audit-info-8.1.1.md
lib/cli/package-lock.json
lib/cli/package.json
lib/content-services/package.json
lib/core/package.json
lib/eslint-angular/package.json
lib/extensions/package.json
lib/insights/package.json
lib/js-api/package.json
lib/process-services-cloud/package.json
lib/process-services/package.json
package-lock.json
package.json

Release 8.1.1

---

.github/workflows/pull-from-crowdin.yml

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-10101
Cron job time window has …

[ACS-10101] Reduce cron job execution window

---

lib/cli/package-lock.json
lib/cli/package.json
lib/content-services/package.json
lib/core/package.json
lib/eslint-angular/package.json
lib/extensions/package.json
lib/insights/package.json
lib/js-api/package.json
lib/process-services-cloud/package.json
lib/process-services/package.json
package-lock.json
package.json

Fix Post release version bump to align with ACA

---

docs/core/services/user-preferences.service.md
lib/content-services/src/lib/common/services/discovery-api.service.ts
lib/content-services/src/lib/dialogs/download-zip/mock/download-zip-service.mock.ts
lib/content-services/src/lib/directives/node-download.directive.spec.ts
lib/content-services/src/lib/search/components/search-control.component.spec.ts
lib/content-services/src/lib/search/components/search-control.component.ts
lib/core/src/lib/auth/basic-auth/basic-alfresco-auth.service.spec.ts
lib/core/src/lib/auth/basic-auth/basic-alfresco-auth.service.ts
lib/core/src/lib/auth/guard/auth-guard-bpm.service.spec.ts
lib/core/src/lib/auth/guard/auth-guard-ecm.service.spec.ts
lib/core/src/lib/auth/guard/auth-guard-ecm.service.ts
lib/core/src/lib/auth/guard/auth-guard.service.spec.ts
lib/core/src/lib/auth/interfaces/authentication-service.interface.ts
lib/core/src/lib/auth/oidc/oidc-authentication.service.spec.ts
lib/core/src/lib/auth/oidc/oidc-authentication.service.ts
lib/core/src/lib/auth/services/authentication.service.spec.ts
lib/core/src/lib/auth/services/authentication.service.ts
lib/core/src/lib/auth/services/base-authentication.service.ts
lib/process-services-cloud/src/lib/app/components/app-list-cloud/app-list-cloud.component.spec.ts
lib/process-services-cloud/src/lib/form/components/form-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/process-filters/components/edit-process-filter/edit-process-filter-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-filters/mock/edit-task-filter-cloud.mock.ts
lib/process-services-cloud/src/lib/task/task-header/components/task-header-cloud.component.spec.ts

> - [ ] Bugfix
https://hyland.atlassian.net/browse/ACS-9768
Deprecated methods were …

[ACS-9768] remove deprecated methods from auth related components

---

docs/user-guide/releasing-patches.md

> - [ ] Bugfix
https://hyland.atlassian.net/browse/AAE-35385
📚 Patch release doc has …

AAE-35385 Improve releasing-patches guide

---

lib/process-services-cloud/src/lib/process/process-filters/components/process-filters/process-filters-cloud.component.spec.ts
lib/process-services-cloud/src/lib/process/process-filters/components/process-filters/process-filters-cloud.component.ts
lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.spec.ts
lib/process-services-cloud/src/lib/process/process-list/services/process-list-cloud.service.ts
lib/process-services-cloud/src/lib/task/task-filters/components/task-filters/task-filters-cloud.component.spec.ts
lib/process-services-cloud/src/lib/task/task-filters/components/task-filters/task-filters-cloud.component.ts
lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.spec.ts
lib/process-services-cloud/src/lib/task/task-list/services/task-list-cloud.service.ts

AAE-37368 Applying new tasks and process count APIs

---

lib/process-services-cloud/package.json

> - [ ] Bugfix
Fixes failing builds https://github.com/Alfresco/hxp-frontend-apps/actions/runs/17579632051/job/4993311 …

AAE-37573 Add editorjs-html to process-services-cloud dependencies

---

lib/content-services/src/lib/search/components/search-filter-autocomplete-chips/search-filter-autocomplete-chips.component.spec.ts
lib/content-services/src/lib/search/components/search-filter-autocomplete-chips/search-filter-autocomplete-chips.component.ts
lib/content-services/src/lib/search/models/autocomplete-option.interface.ts

> - [x] Bugfix
https://hyland.atlassian.net/browse/MNT-24388
Existing sites and …

[MNT-24388] fix location search facet

---

lib/process-services-cloud/src/lib/form/components/widgets/dropdown/dropdown-cloud.widget.ts

AAE-38287 Cannot select dropdown options when selection type is multiple

---

lib/process-services-cloud/src/lib/process/process-filters/models/process-filter-cloud.model.spec.ts

AAE-0000 Trigger alpha build

---

lib/process-services-cloud/src/lib/form/components/form-cloud.component.html
lib/process-services-cloud/src/lib/form/components/form-cloud.component.scss

[AAE-37563](https://hyland.atlassian.net/browse/AAE-37563)
> - [ ] Bugfix
> - [x] Other... Please describe: Updated forms to have a grey background in regular, fullscreen, and standalone fullscreen. …

AAE-37563 Added grey background to fullscreen and standalone fullscreen standalone forms

---

lib/js-api/package.json

Fixed js-api dep for superagent

---

lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.html
lib/core/src/lib/card-view/components/card-view-dateitem/card-view-dateitem.component.scss
lib/core/src/lib/card-view/components/card-view/card-view.component.scss

> - [x] Bugfix
https://hyland.atlassian.net/browse/ACS-10145
Text is not truncated in …

[ACS-10145] Fix truncated text in details info drawer
